### PR TITLE
SSDP replacer as cordova plugin

### PR DESCRIPTION
**Pull request by andrew-aladev**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1338)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4ff245b)

**Comment by ThaliTester** [comment]
Test (Success) 89623209 build is completed (4ff245b)

See https://github.com/ThaliTester/TestResults/tree/896232094ff245b_SSDP_replacer_as_cordova_plugin_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 896232094ff245b(4ff245b) has failed

See https://github.com/ThaliTester/TestResults/tree/896232094ff245b_SSDP_replacer_as_cordova_plugin_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1338#-:-KUJv9Wm6ytKo4VXOEK3:bnfp4nl)*

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1338#-:-KUR7jATWmb-KUTXQ-ka:bnfp4nl)*

**Pull request merged**
