### PR TITLE
Move us officially over to Next Generation

### LINKED ISSUE #621: Move us officially over to Next Generation
Take a quick pass to see which files we want to maintain over the transition

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #621

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/921)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (813ef4e)

**Comment by ThaliTester** [comment]
Test (Fail) 82279226 build is completed (813ef4e)

See https://github.com/ThaliTester/TestResults/tree/82279226813ef4e_Move_us_officially_over_to_Next_Generation_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
Reviewed 154 of 154 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[test/www/jxcore/bv_tests/disabled/testThaliCryptoManager.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-KPoxxxjbNVTxsV3NIv3:-KPoxxxjbNVTxsV3NIv4:blm83ph) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56750c6948508d45a8dc216d46a45d7e20ba7f83/test/www/jxcore/bv_tests/disabled/testThaliCryptoManager.js#L3)):*
> ```JavaScript
> "use strict";
> 
> var originalMobile = typeof Mobile === "undefined" ? undefined : Mobile;
> ```

I'm not sure if we should delete this. The reason is that this creates PKCS12 files which are needed to do things like mutual SSL auth which we may need to implement the connection between the Webview and Node (see @larryonoff and #320.

---

*[test/www/jxcore/bv_tests/disabled/pkcs12folderbad/pkcs12.pfx, line 0 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-KPoyHB3akRf5Pfg0xjl:-KPoyHB4mN0aJiQLnrPL:b-d3hwe5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/813ef4efb4a762212292582b61e18e28da041489/test/www/jxcore/bv_tests/disabled/pkcs12folderbad/pkcs12.pfx#L0)):*
We might need this file if we are bringing back the crypto PKCS12 tests

---

*[test/www/jxcore/meta_tests/testPerfTestFrameworkClient.js, line 4 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-KPoyZGUAlTYsc5vH9lg:-KPoyZGUAlTYsc5vH9lh:b-520igc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/813ef4efb4a762212292582b61e18e28da041489/test/www/jxcore/meta_tests/testPerfTestFrameworkClient.js#L4)):*
> ```JavaScript
> 
> var originalMobile = typeof Mobile === 'undefined' ? undefined : Mobile;
> var mockMobile = require('../bv_tests/mockmobile.js');
> ```

How does this test survive when mockmobile.js is dead?

---

*[thali/thalicryptomanager.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-KPoylonMkOHb_Io7Djz:-KPoylooJFpbwG4Xpu_q:bhbx1zr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56750c6948508d45a8dc216d46a45d7e20ba7f83/thali/thalicryptomanager.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

We may need this file for #320 

---

*[thali/Runtime/makeIntoCloseAllServer.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-KPoz2wmnS8KHuwVLj8S:-KPoz2wmnS8KHuwVLj8T:b-q4r1le) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56750c6948508d45a8dc216d46a45d7e20ba7f83/thali/Runtime/makeIntoCloseAllServer.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

Shouldn't this be under utils?

---

*[thali/Runtime/promiseQueue.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-KPozh9EdVOv1yDLtoDL:-KPozh9EdVOv1yDLtoDM:bjs1gql) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56750c6948508d45a8dc216d46a45d7e20ba7f83/thali/Runtime/promiseQueue.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

Shouldn't this be under util?

---

*[thali/Runtime/thaliMobile.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-KPozrzf4Lx-JTjEOpcK:-KPozrzf4Lx-JTjEOpcL:b-kp8fkm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56750c6948508d45a8dc216d46a45d7e20ba7f83/thali/Runtime/thaliMobile.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

What do you think of putting thaliMobile, thaliMobileNativeWrapper, thaliMobileNative, and thaliWifiInfrastructure into a folder called 'networking'? It seems to me that only thaliManager should be at the root since that is the function we expect users to generally call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (bc6daba)

**Comment by ThaliTester** [comment]
Test (Fail) 82279226 build is completed (bc6daba)

See https://github.com/ThaliTester/TestResults/tree/82279226bc6daba_Move_us_officially_over_to_Next_Generation_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (baf07fb)

**Comment by ThaliTester** [comment]
Test (Fail) 82279226 build is completed (baf07fb)

See https://github.com/ThaliTester/TestResults/tree/82279226baf07fb_Move_us_officially_over_to_Next_Generation_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
Please just fix the one issue I mentioned with thaliCryptoManager and then :lgtm: 

---

Reviewed 12 of 160 files at r1, 2 of 2 files at r2, 24 of 34 files at r3, 24 of 24 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/Runtime/thalicryptomanager.js, line 1 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-KPsuebBbq1eMZq6GMzO:-KPsuebBbq1eMZq6GMzP:b4ekkd0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/baf07fb4539f643f2d2494d307776d07497c105b/thali/Runtime/thalicryptomanager.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

Shouldn't this be under security? Also we should probably rename it to thaliCryptoManager.js (e.g. camel case)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-:-KPsuybeQ9_Dgs0O09Qg:bizqfuy)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (351c006)

**Comment by ThaliTester** [comment]
Test (Fail) 82279226 build is completed (351c006)

See https://github.com/ThaliTester/TestResults/tree/82279226351c006_Move_us_officially_over_to_Next_Generation_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
Once it passes build on CI then :lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-:-KPxwXPCCDTyfHaMR6b_:b-az6l9e)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (5856626)

**Comment by yaronyg** [comment]
@andrew-aladev please merge this into thaliproject/Thali_CordovaPlugin#928

**Comment by ThaliTester** [comment]
Test (Fail) 82279226 build is completed (5856626)

See https://github.com/ThaliTester/TestResults/tree/822792265856626_Move_us_officially_over_to_Next_Generation_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
@yaronyg I need some help help. I've found a problem:

[Here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812/thali/NextGeneration/thaliMobile.js#L892) we have:
```
ThaliMobileNativeWrapper.emitter.on(
  'nonTCPPeerAvailabilityChangedEvent',
  function (peer) {
    handlePeer(peer, connectionType);
  }
);

thaliWifiInfrastructure.on(
  'wifiPeerAvailabilityChanged',
  function (peer) {
    handlePeer(peer, connectionTypes.TCP_NATIVE);
  }
);
```

`handlePeer` does a lookup in it's hash table. Lookup is based on `connectionType` and `peerIdentifier`:
```
var cachedPeer = peerAvailabilities[peer.connectionType][peer.peerIdentifier];
```
Than `handlePeer` emits the `peerAvailabilityChanged`. So `thaliMobile` will emits same `peer` twice with different `connectionType`.

But `ThaliNotificationClient` doesn't like [it](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812/thali/NextGeneration/notification/thaliNotificationClient.js#L207).
```
assert(!this.peerDictionary.exists(peerStatus.peerIdentifier),
  'peerAvailabilityChanged event with the same peerId'+
  ' should not occur. peerIdentifier:' + peerStatus.peerIdentifier);
```

We can change this assert into:
```
assert(
  !(
    this.peerDictionary.exists(peerStatus.peerIdentifier) &&
    this.peerDictionary.get(peerStatus.peerIdentifier)
    .notificationAction._connectionType === peerStatus.connectionType
  ),
  'peerAvailabilityChanged event with the same peerId and ' +
  'connectionType should not occur. ' +
  'peerIdentifier: ' + peerStatus.peerIdentifier + ', ' +
  'connectionType: ' + peerStatus.connectionType
);
```

But this doesn't look good.

1. Maybe we should change `peerDictionary` to works with `dictionary[peer.connectionType][peer.peerIdentifier]` instead of `dictionary[peer.peerIdentifier]`.
2. Maybe we should create special `peerIdentifier` like `peer.connectionType + ':' + peer.peerIdentifier` and use it in `peerDictionary`
2. Maybe we should block `thaliMobile` from emitting same `peer.peerIdentifier` twice.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (27e8383)

**Comment by ThaliTester** [comment]
Test (Fail) 82279226 build is completed (27e8383)

See https://github.com/ThaliTester/TestResults/tree/8227922627e8383_Move_us_officially_over_to_Next_Generation_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
What doesn't make sense to me here is that the peerIDs used on Wifi are generated separately from the peerIDs used on the native connection. The WiFi peerIDs are UUIDs (look at ThaliWifiInfrastructure.startUpdateAdvertisingAndListening, look for the line where we set self.usn). The Android IDs are Bluetooth MAC addresses and the iOS IDs will be UUIDs. So there literally should never be a collision.

We have had an issue at some point (I'm embarrassed to say that I can't find it) to intentionally use the same peerID on the same transports in order to enable the same peerID on multiple transports to make it easier for peers to detect that someone is available over multiple transports and pick the better one but there are security and implementation issues that stopped us.

So for now the existing assert should be correct. We should never see the same peerID on two different transports.

---

Review status: 57 of 128 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-:-KQ1sOg9Sod6WyMvjNc9:b-u7aeea)*

**Comment by yaronyg** [comment]
@andrew-aladev I wanted to review this and include it now in vNext_yarong_417_812 so you don't have to do a super ugly merge later but there are still issues in here that haven't been answered. So instead I'm going to focus on getting cordova building properly again. But please resolve all the open issues here ASAP so I can merge it in before @artemjackson works on #916 and things get ugly.

---

Review status: 57 of 128 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/921#-:-KQ2TpuQIN6Wuk8D5HXy:bfq72gj)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (49478c0)

**Comment by ThaliTester** [comment]
Test (Fail) 82279226 build is completed (49478c0)

See https://github.com/ThaliTester/TestResults/tree/8227922649478c0_Move_us_officially_over_to_Next_Generation_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
We ran into too many merge issues. It's just not worth the time right now to figure out. The lesson is that we can't expect to refactor the entire code base while people are simultaneously working on that code base. We need to pick a point where vNext is stable and not let anyone make any changes until #621 is finished.

**Pull request closed without merging**
