### PR TITLE
Fix for 'test for data corruption'

### PR DESCRIPTION
**Pull request by mlesnic**
This is based on timer, because of possible race condition in case when we try to restart ThaliMobile (call stop and start) whenever any error occurs. Currently this test is at most ran 5 times, which I believe is more than enough. However, sometimes my Nexus can get into very sad state, that it is really really slow and doesn't make any connections, so it is still possible that this test will fail after 5 retries, but it clearly tells us that nexus bluetooth is pretty bad.

Fix for thaliproject/Thali_CordovaPlugin#1594 

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1715)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a470a85)

**Comment by ThaliTester** [comment]
Test 100892963 (a470a85) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100892963 build is completed (a470a85)

See https://github.com/ThaliTester/TestResults/tree/100892963a470a85_Fix_for__test_for_data_corruption__mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 100892963a470a85(a470a85) has failed

See https://github.com/ThaliTester/TestResults/tree/100892963a470a85_Fix_for__test_for_data_corruption__mlesnic/ for the fail logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-:-KaCAXOyxXN9NSYEMbKg:bnfp4nl)*

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-:-KaCT1ncwZc9cEIXwq_P:bg7igkv)*

**Comment by yaronyg** [comment]
Please fix identified comments.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 40 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-KaDZzAmHzJT4nGZ1HPa:-KaDZzAmHzJT4nGZ1HPb:br72iok) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a470a85a59bb0bf9a5ab259850c0890e64dbe58d/test/www/jxcore/bv_tests/testThaliMobile.js#L40)):*
> ```JavaScript
>   // long to establish bluetooth connection.
>   testTimeout:      5 * 60 * 1000,
>   teardownTimeout:  5 * 60 * 1000
> ```

The fact that we need such long timeouts is itself a bug. I understand and support the desire to move forward while we figure this out but we need a bug that captures the fact that Bluetooth is acting crazy and we need to put that bug number here.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2245 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-KaDZwq3x4QehIMbsgMZ:-KaDZwq4c9luTI9NSfat:b4ll7kb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a470a85a59bb0bf9a5ab259850c0890e64dbe58d/test/www/jxcore/bv_tests/testThaliMobile.js#L2245)):*
> ```JavaScript
>     var promiseQueue = new PromiseQueue();
> 
>     // This timer purpose is to manually restart ThaliMobile every 60 seconds.
> ```

What bug exactly is this working around and what is the bug # to fix it? Do we see the Bluetooth connection problems 'go away' because we start and stop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-:-KaD_EhWUZidTnc6OfxI:bk5hb9t)*

**Comment by mlesnic** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 40 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-KaDZzAmHzJT4nGZ1HPa:-KaHLN-8jCe0Hp8B5_9J:bun8ny9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a470a85a59bb0bf9a5ab259850c0890e64dbe58d/test/www/jxcore/bv_tests/testThaliMobile.js#L40)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

The fact that we need such long timeouts is itself a bug. I understand and support the desire to move forward while we figure this out but we need a bug that captures the fact that Bluetooth is acting crazy and we need to put that bug number here.
</blockquote></details>

I believe this can be related to #1569. testTimeout is longer because I wanted to give a 5 possible tries for this test, but it can be set as default to 3 mins. More important is teardownTimeout, because I notice that there is possible scenario when one device is already done (has pulled all data from other devices) but the other ones can still try to pull data from that device, and when it is already done, the other devices cannot connect, and as a result, this test fails due to timeout.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2245 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-KaDZwq3x4QehIMbsgMZ:-KaHQT9ey_RBQu50aVaN:bfe3gqk) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a470a85a59bb0bf9a5ab259850c0890e64dbe58d/test/www/jxcore/bv_tests/testThaliMobile.js#L2245)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

What bug exactly is this working around and what is the bug # to fix it? Do we see the Bluetooth connection problems 'go away' because we start and stop?
</blockquote></details>

I created an issue for this, please check #1719.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 40 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-KaDZzAmHzJT4nGZ1HPa:-KaIk2Oy1CuRpxI0fgtu:b1il0b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a470a85a59bb0bf9a5ab259850c0890e64dbe58d/test/www/jxcore/bv_tests/testThaliMobile.js#L40)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary><blockquote>

I believe this can be related to #1569. testTimeout is longer because I wanted to give a 5 possible tries for this test, but it can be set as default to 3 mins. More important is teardownTimeout, because I notice that there is possible scenario when one device is already done (has pulled all data from other devices) but the other ones can still try to pull data from that device, and when it is already done, the other devices cannot connect, and as a result, this test fails due to timeout.
</blockquote></details>

Right so the goal here to resolve this would be:
1. Make sure we have a bug that captures the problem (e.g. #1569)
2. In the source code above put in a comment of the form "These time outs are excessive because of issues we are having with Bluetooth, see #1569. When #1569 is fixed we will be able to reduce these time outs to a reasonable level."

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2245 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-KaDZwq3x4QehIMbsgMZ:-KaIkP8WEAh7hz-KVI4v:b-xi1k2e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a470a85a59bb0bf9a5ab259850c0890e64dbe58d/test/www/jxcore/bv_tests/testThaliMobile.js#L2245)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary><blockquote>

I created an issue for this, please check #1719.
</blockquote></details>

Excellent, so now we need to reference that bug in the code right here. In other words, finish your comment here with "This issue is tracked in #1719".

There are two reasons we include the bug numbers in the code. First, when a bug is resolved it makes it easier to find where we need to fix things. Second, when I make a fix as a result of a bug I'll often mark the fix with the bug number so that people can understand why we had to make the fix in the first place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8c10861)

**Comment by ThaliTester** [comment]
Test 100892963 (8c10861) build started.

**Comment by mlesnic** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 40 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-KaDZzAmHzJT4nGZ1HPa:-KaMsPMtZV9hlVm0IkVt:bwdiftc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a470a85a59bb0bf9a5ab259850c0890e64dbe58d/test/www/jxcore/bv_tests/testThaliMobile.js#L40)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Right so the goal here to resolve this would be:
1. Make sure we have a bug that captures the problem (e.g. #1569)
2. In the source code above put in a comment of the form "These time outs are excessive because of issues we are having with Bluetooth, see #1569. When #1569 is fixed we will be able to reduce these time outs to a reasonable level."
</blockquote></details>

Okay, I also thought that this could be related to #1614, but Andrew already provided a solution to this issue, and it is merged to main iOS branch but timeout issue still occurs so I will leave it as it is.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2245 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-KaDZwq3x4QehIMbsgMZ:-KaM_i8K6bVTbdIHjLzQ:bb6un1j) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a470a85a59bb0bf9a5ab259850c0890e64dbe58d/test/www/jxcore/bv_tests/testThaliMobile.js#L2245)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Excellent, so now we need to reference that bug in the code right here. In other words, finish your comment here with "This issue is tracked in #1719".

There are two reasons we include the bug numbers in the code. First, when a bug is resolved it makes it easier to find where we need to fix things. Second, when I make a fix as a result of a bug I'll often mark the fix with the bug number so that people can understand why we had to make the fix in the first place.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715)*

**Comment by ThaliTester** [comment]
Test (Fail) 100892963 build is completed (8c10861)

See https://github.com/ThaliTester/TestResults/tree/1008929638c10861_Fix_for__test_for_data_corruption__mlesnic/ for the logs

**Comment by jareksl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1715#-:-KaNo4OHhP0wLPg2K-kt:bnfp4nl)*

**Pull request merged**
