### PR TITLE
Fix implemented iOS native-mode functionality

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1759)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e04a92f)

**Comment by ThaliTester** [comment]
Test 103282205 (e04a92f) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 103282205 build is completed (e04a92f)

See https://github.com/ThaliTester/TestResults/tree/103282205e04a92f_Fix_implemented_iOS_native-mode_functionality_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fd1d69c)

**Comment by ThaliTester** [comment]
Test 103282205 (fd1d69c) build started.

**Comment by ThaliTester** [comment]
Test (Success) 103282205 build is completed (fd1d69c)

See https://github.com/ThaliTester/TestResults/tree/103282205fd1d69c_Fix_implemented_iOS_native-mode_functionality_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 103282205fd1d69c(fd1d69c) has failed

See https://github.com/ThaliTester/TestResults/tree/103282205fd1d69c_Fix_implemented_iOS_native-mode_functionality_dersim-davaod/ for the fail logs

**Comment by dersim-davaod** [comment]
For now we have following failing tests:
`can do HTTP requests after connections are cut`
`Can shift large amounts of data` (issue #1761)
`cannot call multiConnect with invalid syncValue` (fixed in #1756)
`enqueue and run in order`
`enqueueAtTop and run backwards`

The first and the second issues are probably related to using GCDAsyncSocket library.
I've tried another socket framework [BlueSocket](https://github.com/IBM-Swift/BlueSocket) and looks like using this framework fix these issues.
I continue investigation today.

**Comment by evabishchevich** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 62 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1759#-KbohW12mFxgPV893TD4:-KbohW12mFxgPV893TD5:bvvigms) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd1d69c897b7fea48bcb0ae9ff7ffe6a03a11c61/build.sh#L62)):*
> ```Shell
> echo ""
> echo "run desktop tests"
> #jx runTests.js --networkType WIFI
> ```

Let's enable the tests back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1759)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 62 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1759#-KbohW12mFxgPV893TD4:-Kbq0crV_neBVcRdB5uY:b-fpto37) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd1d69c897b7fea48bcb0ae9ff7ffe6a03a11c61/build.sh#L62)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

Let's enable the tests back
</blockquote></details>

What @evabishchevich said!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1759#-:-Kbq267jescD3A20656j:bnfp4nl)*

**Comment by czyzm** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 62 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1759#-KbohW12mFxgPV893TD4:-KbsLH-XYbRNIihviDhG:bw9dtm4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd1d69c897b7fea48bcb0ae9ff7ffe6a03a11c61/build.sh#L62)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

What @evabishchevich said!
</blockquote></details>

Please uncomment those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1759)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (245b6bc)

**Comment by ThaliTester** [comment]
Test 103282205 (245b6bc) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 103282205 build is completed (245b6bc)

See https://github.com/ThaliTester/TestResults/tree/103282205245b6bc_Fix_implemented_iOS_native-mode_functionality_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (95c65e8)

**Comment by ThaliTester** [comment]
Test 103282205 (95c65e8) build started.

**Comment by ThaliTester** [comment]
Test (Success) 103282205 build is completed (95c65e8)

See https://github.com/ThaliTester/TestResults/tree/10328220595c65e8_Fix_implemented_iOS_native-mode_functionality_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 10328220595c65e8(95c65e8) has failed

See https://github.com/ThaliTester/TestResults/tree/10328220595c65e8_Fix_implemented_iOS_native-mode_functionality_dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (679c014)

**Comment by ThaliTester** [comment]
Test 103282205 (679c014) build started.

**Comment by ThaliTester** [comment]
Test (Success) 103282205 build is completed (679c014)

See https://github.com/ThaliTester/TestResults/tree/103282205679c014_Fix_implemented_iOS_native-mode_functionality_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 103282205679c014(679c014) has failed

See https://github.com/ThaliTester/TestResults/tree/103282205679c014_Fix_implemented_iOS_native-mode_functionality_dersim-davaod/ for the fail logs

**Comment by dersim-davaod** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 62 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1759#-KbohW12mFxgPV893TD4:-Kc2mLCb5PdvnZ2Mdfdz:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd1d69c897b7fea48bcb0ae9ff7ffe6a03a11c61/build.sh#L62)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

Please uncomment those.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1759)*

**Pull request merged**
