### PR TITLE
#903 Implemented missing iOS functionality for wifiBasedNativeMock

### LINKED ISSUE #903: Update wifiBasedNativeMock for iOS
We can do this before the new iOS code is even ready. That way you can not be blocked in make iOS changes for Node.

- [x] Make sure connect throws the right error if called on iOS
- [x] Implement multiConnect
- [x] Implement multiConnectConnectionFailure (if we use TCPServersManager we can use this via its failure event)
- [x] Implement disconnect (and make sure it throws the right error if we are on Android)

### PR DESCRIPTION
**Pull request by artemjackson**
Closes #903.

This PR is not completed yet. Submitted just for review.

- [x] Make sure connect throws the right error if called on iOS
- [x] Implement multiConnect
- [ ] Implement multiConnectConnectionFailure 
- [x] Implement disconnect (and make sure it throws the right error if we are on Android)

@yaronyg I have some questions that I'd like to discuss:
* I suggested that `connect` functionality could be used for `multiConnect` as well. So I moved common part of `connect` to `_connect` method that is used by `connect` and `multiConnect`. Was it a right suggestion?
* I read some different descriptions how `multiConnect` errors should be handled:
  * One was that we should handle `multiConnect` errors in `multiConnectResolved`
  * Another one was that we should handle `multiConnect` errors in `multiConnectConnectionFailure`

 Could you please clarify which errors should be handled in  `multiConnectResolved` and `multiConnectConnectionFailure`?

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/957)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (6bc2f77)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (a89b2ec)

**Comment by ThaliTester** [comment]
Test (Fail) 83272992 build is completed (6bc2f77)

See https://github.com/ThaliTester/TestResults/tree/832729926bc2f77__903_Implemented_missing_iOS_functionality_for_wifiBasedNativeMock_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 83272992 build is completed (a89b2ec)

See https://github.com/ThaliTester/TestResults/tree/83272992a89b2ec__903_Implemented_missing_iOS_functionality_for_wifiBasedNativeMock_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (0321fb3)

**Comment by ThaliTester** [comment]
Test (Success) 83272992 build is completed (0321fb3)

See https://github.com/ThaliTester/TestResults/tree/832729920321fb3__903_Implemented_missing_iOS_functionality_for_wifiBasedNativeMock_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 832729920321fb3(0321fb3) has failed

See https://github.com/ThaliTester/TestResults/tree/832729920321fb3__903_Implemented_missing_iOS_functionality_for_wifiBasedNativeMock_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
> I suggested that connect functionality could be used for multiConnect as well. So I moved common part of connect to _connect method that is used by connect and multiConnect. Was it a right suggestion?
> 
No because multiconnect has a different response pattern than connect so they should be separate. I also want to leave open the possibility of support both connection and multiConnect simultaneously on the same platform (imagine a future version of iOS that supports both MPCF as well as direct Bluetooth). So we should keep them separate.

> I read some different descriptions how multiConnect errors should be handled:
> 
> 
> One was that we should handle multiConnect errors in multiConnectResolved
> 
> Another one was that we should handle multiConnect errors in multiConnectConnectionFailure
> 
multiConnectConnectionFailure is just to notify node when an existing MCSession is lost. In other words one can't get a multiConnectConnectionFailure until one has first gotten a multiConnectResolved because if there is no MCSession then there is no MCSession to lose.
> 
> 
> Could you please clarify which errors should be handled in  multiConnectResolved and multiConnectConnectionFailure?
Please see above.. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-:-KQS4piAbgDZDDxjnzD9:b-4pwp5b)*

**Comment by yaronyg** [comment]
My comment above about the re-use of connect isn't right so please ignore. The other comments on multiConnectConnectionFailure and multiConnectResolved are correct.

Also note that we can't check in any new code that doesn't have tests. So we need to update the testThaliMobileNative file to include tests for the new multiConnect, disconnect and connect functionality.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 385 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSC04ZjUIgAcaFHXQq:-KQSC04_2o19ql8lF33A:basuz5r) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L385)):*
> ```JavaScript
> };
> 
> MobileCallInstance.prototype._disconnect =
> ```

Per the definition of multiConnectConnectionFailure we also need to fire that event. See thaliMobileNative's definition of multiConnectConnectinFailure. Is that already captured in some other work item (which is my guess, but I thought I should ask just in case).

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 631 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSF45rxNjtGbThqNMr:-KQSF45rxNjtGbThqNMs:b-1py7j6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L631)):*
> ```JavaScript
> 
>       if (!error && response) {
>         var conenction = JSON.parse(response);
> ```

NB: /conenction/connection/

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 639 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSG9cqAWs5DImK2vVc:-KQSG9cqAWs5DImK2vVd:bx10zqx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L639)):*
> ```JavaScript
>       // {@link module:WifiBasedNativeMock~MobileCallInstance.registerToNative}
>       // callback
>       callback(null);
> ```

Doesn't there have to be two callbacks? One for the immediate callback to multiConnect (which should either be null or 'Platform does not support multiConnect') and then multiConnectResolvedCallback?

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 654 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSGSaK6XJR7x18_rB4:-KQSGSaK6XJR7x18_rB5:b-uu2qu5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L654)):*
> ```JavaScript
> MobileCallInstance.prototype.disconnect = function(peerIdentifier, callback) {
>   if (this.platform === platformChoice.ANDROID) {
>     return callback('Platform does not support multiConnect');
> ```

BTW these strings really need to match the spec because we are going to have to write tests for them. In this case the string is defined as 'Not multiConnect platform' (see thaliMobileNative). Now your string is nicer and I'm fine with it but in that case please edit thaliMobileNative's definition of disconnect as part of this PR.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 699 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSH4GIqZfJnng1TZDr:-KQSH4GIqZfJnng1TZDs:bdi0030) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L699)):*
> ```JavaScript
>  */
> MobileCallInstance.prototype.callNative = function () {
>   switch (this.mobileMethodName) {
> ```

Doesn't disconnect also have to be added to this list?

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 867 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSHR8GCjuHkjl62YqU:-KQSHR8GCjuHkjl62YqV:b-ttm16w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L867)):*
> ```JavaScript
>  * @param {module:thaliMobileNative~multiConnectResolved} callback
>  */
> MobileCallInstance.prototype.multiConnectResolved = function (callback) {
> ```

Shouldn't this just be the place where we register the function that is supposed to be called back? Look at incomingConnectionToPortNumberFailed above as an example.

Shouldn't we have a separate utility method that we call when we finish with a multiConnect call that then calls that callback with the right sync value and result?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-:-KQSD7n0QD1nm36J7vjQ:bxq12m9)*

**Comment by artemjackson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 639 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSG9cqAWs5DImK2vVc:-KQVC18Q1KK_WtEnTnNC:biqslez) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L639)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Doesn't there have to be two callbacks? One for the immediate callback to multiConnect (which should either be null or 'Platform does not support multiConnect') and then multiConnectResolvedCallback?
</details>
Callback with `Platform does not support multiConnect` error is already [here](https://github.com/thaliproject/Thali_CordovaPlugin/pull/957/files#diff-eaf1b2c967345873ec2ef5471b1aee6fR622)
Regarding to`multiConnectResolvedCallback`, the callback may be not registered yet when being called. It means that`Mobile('multiConnectResolved').registerToNative(callback)` may be not called.
E.g. :
```
Mobile('multiConnect').callNative(syncValue, peerIdentifier, function (...) {
    ...
});

// some code 

Mobile('multiConnectResolved').registerToNative(function (...) {
    ...
});
```
Therefore the `multiConnectResolvedCallback` can not be called here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957)*

**Comment by artemjackson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 654 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSGSaK6XJR7x18_rB4:-KQVIGIMKnj88ZO_MwHT:b-68s9mj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L654)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> BTW these strings really need to match the spec because we are going to have to write tests for them. In this case the string is defined as 'Not multiConnect platform' (see thaliMobileNative). Now your string is nicer and I'm fine with it but in that case please edit thaliMobileNative's definition of disconnect as part of this PR.
</details>
Oh, sorry, this error string was mistaken for [another one](https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_artemjackson_903/thali/NextGeneration/thaliMobileNative.js#L448).
Should we use the error string above or should I fix it to be `Not multiConnect platform`?

BTW it would be great if we compared `Error` objects in tests rather than volatile strings (they are not even constants!)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957)*

**Comment by artemjackson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 699 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSH4GIqZfJnng1TZDr:-KQVMfx0cKj4lmS9dyld:ba4cgaj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L699)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Doesn't disconnect also have to be added to this list?
</details>
Yes, it must be added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957)*

**Comment by artemjackson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 867 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSHR8GCjuHkjl62YqU:-KQVMvxbog8lnE0H-Hkk:b-x5bsun) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L867)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Shouldn't this just be the place where we register the function that is supposed to be called back? Look at incomingConnectionToPortNumberFailed above as an example.
> 
> Shouldn't we have a separate utility method that we call when we finish with a multiConnect call that then calls that callback with the right sync value and result?
</details>
We need to discuss it during the call. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957)*

**Comment by artemjackson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 631 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957#-KQSF45rxNjtGbThqNMr:-KQVbSvexNA7w4rkqrSr:b-h3j5rv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0321fb35197b9d88989faac8d6161b9bc6385139/test/www/jxcore/lib/wifiBasedNativeMock.js#L631)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: /conenction/connection/
</details>
It forced me to install spell-check :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/957)*

**Comment by artemjackson** [comment]
@yaronyg this is still in a working state.

**Comment by artemjackson** [comment]
Re-submit when it's finished.

**Pull request closed without merging**
