### PR TITLE
Specify tests order via config

### PR DESCRIPTION
**Pull request by chapko**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1680)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4a4c081)

**Comment by ThaliTester** [comment]
Test 99261278 (4a4c081) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99261278 build is completed (4a4c081)

See https://github.com/ThaliTester/TestResults/tree/992612784a4c081_Specify_tests_order_via_config_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 992612784a4c081(4a4c081) has failed

See https://github.com/ThaliTester/TestResults/tree/992612784a4c081_Specify_tests_order_via_config_chapko/ for the fail logs

**Comment by yaronyg** [comment]
Please respond to my one comment and then :lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/config.json, line 6 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1680#-KZghMZCZtQi3wiYvXTA:-KZghMZD9GUdH-lEQa7E:b-31qa9k) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4a4c08194d5840e437a4cb566f52b095125661b8/test/www/jxcore/config.json#L6)):*
> ```JSON
>   },
>   "preferredOrder": [
>     "testMakeIntoCloseAllServer.js",
> ```

We need to record somewhere why we picked this order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1680#-:-KZgi7cxXLWOiyzxaimx:b7lt6ow)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1680#-:-KZzj-knCuGyxIZhup6J:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b72b2a5)

**Comment by ThaliTester** [comment]
Test (Success) 99261278 build is completed (b72b2a5)

See https://github.com/ThaliTester/TestResults/tree/99261278b72b2a5_Specify_tests_order_via_config_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 99261278b72b2a5(b72b2a5) has failed

See https://github.com/ThaliTester/TestResults/tree/99261278b72b2a5_Specify_tests_order_via_config_chapko/ for the fail logs

**Pull request merged**
