### PR TITLE
#853 Updated jxcore-cordova version to 0.1.2b

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/885)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ffbc155)

**Comment by artemjackson** [comment]
Some wrong code got here. Remove all unrelated code. Closed.

**Comment by ThaliTester** [comment]
Test (Success) 81492074 build is completed (ffbc155)

See https://github.com/ThaliTester/TestResults/tree/81492074ffbc155__853_Updated_jxcore-cordova_version_to_0_1_2b_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 81492074ffbc155(ffbc155) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/81492074ffbc155__853_Updated_jxcore-cordova_version_to_0_1_2b_artemjackson/ for the logs

**Pull request closed without merging**
