### PR TITLE
Disable non-local installation and throw an error in other case

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1381)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (54b94ec)

**Comment by larryonoff** [comment]
@yaronyg please review

**Comment by ThaliTester** [comment]
Test (Success) 90049939 build is completed (54b94ec)

See https://github.com/ThaliTester/TestResults/tree/9004993954b94ec_Disable_not_local_installation_and_throw_an_error_in_other_case_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 9004993954b94ec(54b94ec) has failed

See https://github.com/ThaliTester/TestResults/tree/9004993954b94ec_Disable_not_local_installation_and_throw_an_error_in_other_case_larryonoff/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1381)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1381#-:-KUTbcBUQQP_ixBRb7jn:bnfp4nl)*

**Pull request merged**
