### PR TITLE
Implement the failedNativeConnectionEvent for iOS (multiConnectConnectionFailure)

### PR DESCRIPTION
**Pull request by squid48**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1469)

### CODE REVIEW

**Comment by chapko** [comment]
@squid48 there is only small typo. So just fix it and then it is :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 454 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1469#-KW9jmeRKno6KDccLWKf:-KW9jmeRKno6KDccLWKg:bhyis9h) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8f91f92cbd6c473f4ea19c84b68abbb9cda02d76/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L454)):*
> `'connection type is tcp'`

in this case it is MPCF :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1469#-:-KW9k68HgrUTSEuMffom:b3gdduj)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d35e269)

**Comment by ThaliTester** [comment]
Test (Fail) 91962866 build is completed (d35e269)

See https://github.com/ThaliTester/TestResults/tree/91962866d35e269_Implement_the_failedNativeConnectionEvent_for_iOS__multiConnectConnectionFailure__squid48/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1469#-:-KWZQFLIZrjImU78XVL_:bnfp4nl)*

**Pull request closed without merging**
