### PR TITLE
changed Connection Timed Out error's description

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/947)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (a4f621d)

**Comment by ThaliTester** [comment]
Test (Success) 83084099 build is completed (a4f621d)

See https://github.com/ThaliTester/TestResults/tree/83084099a4f621d_changed_Connection_Timed_Out_error_s_description_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 83084099a4f621d(a4f621d) has failed

See https://github.com/ThaliTester/TestResults/tree/83084099a4f621d_changed_Connection_Timed_Out_error_s_description_baydet/ for the fail logs

**Comment by yaronyg** [comment]
Thanks for finding and fixing this! But we have abandoned vNext_yarong_780. All work is now on either vNext or vNext_yarong_417_812. Please move the change there.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/947#-:-KQNRNcdiU-izrhONb97:b-l5t9vb)*

**Comment by baydet** [comment]
Done.

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/947#-:-KQSj6wsQDdWWwhgjZZa:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (2fdb9e4)

**Comment by ThaliTester** [comment]
Test (Fail) 83084099 build is completed (2fdb9e4)

See https://github.com/ThaliTester/TestResults/tree/830840992fdb9e4_changed_Connection_Timed_Out_error_s_description_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (807e426)

**Comment by ThaliTester** [comment]
Test (Success) 83084099 build is completed (807e426)

See https://github.com/ThaliTester/TestResults/tree/83084099807e426_changed_Connection_Timed_Out_error_s_description_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 83084099807e426(807e426) has failed

See https://github.com/ThaliTester/TestResults/tree/83084099807e426_changed_Connection_Timed_Out_error_s_description_baydet/ for the fail logs

**Comment by baydet** [comment]
@yaronyg, I assume there is a problem in base branch - it could be not updated with vNext what may be the reason of "JavaCall recevied a call for unknown method ExecuteNativeTests" error. Please take a look if you have the latest changes from vNext

**Comment by yaronyg** [comment]
I just submitted PR #1003. Once that gets approved then we should be able to successfully submit this PR.

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/947#-:-KR5ucoMdHofjYZZ8ow1:b-9w37eb)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (4f1e3c4)

**Comment by ThaliTester** [comment]
Test (Success) 83084099 build is completed (4f1e3c4)

See https://github.com/ThaliTester/TestResults/tree/830840994f1e3c4_changed_Connection_Timed_Out_error_s_description_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 830840994f1e3c4(4f1e3c4) has failed

See https://github.com/ThaliTester/TestResults/tree/830840994f1e3c4_changed_Connection_Timed_Out_error_s_description_baydet/ for the fail logs

**Pull request merged**
