### PR TITLE
Added unexpected error handler

### LINKED ISSUE #1350: jx npm run test-coordinated doesn't return error when tests fail

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1350.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1563)

### CODE REVIEW

**Comment by yaronyg** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 171 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1563#-KXHUfPmXQnO4BczVWja:-KXHUfPnT8eB7rsXCGMT:byxxt5r) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e27ae22fccbeffdfed95215a217f5a52d1cc93f6/test/www/jxcore/lib/CoordinatedClient.js#L171)):*
> ```JavaScript
>   .then(function () {
>     if (hadError) {
>       throw latestError;
> ```

NB: There is no actual difference between throwing latestError and 'return Promise.reject(lastestError)'. But for style reasons we try to stay consistent so if we are inside a promise then we should reject with a promise.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 504 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1563#-KXHV3JE2Sb82-tBEN2o:-KXHV3JFPYwDdeCozivb:b71jy27) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e27ae22fccbeffdfed95215a217f5a52d1cc93f6/test/www/jxcore/lib/CoordinatedClient.js#L504)):*
> ```JavaScript
> CoordinatedClient.prototype.unexpectedResult = function (result) {
>   if (result.ok) {
>     // Unexpected successfull result is ok.
> ```

Shouldn't this still be an error? The fact that we got an unexpected result shows that something is really wrong with the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1563)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (51844b4)

**Comment by ThaliTester** [comment]
Test 95017841 (51844b4) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95017841 build is completed (51844b4)

See https://github.com/ThaliTester/TestResults/tree/9501784151844b4_Added_unexpected_error_handler_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 9501784151844b4(51844b4) has failed

See https://github.com/ThaliTester/TestResults/tree/9501784151844b4_Added_unexpected_error_handler_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7e1fb69)

**Comment by ThaliTester** [comment]
Test 95017841 (7e1fb69) build started.

**Comment by andrew-aladev** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 171 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1563#-KXHUfPmXQnO4BczVWja:-KXQ6-mrGPpgJAJfdfWM:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/51844b46f5042b244fc8eb3f04d094c074f31b5c/test/www/jxcore/lib/CoordinatedClient.js#L171)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: There is no actual difference between throwing latestError and 'return Promise.reject(lastestError)'. But for style reasons we try to stay consistent so if we are inside a promise then we should reject with a promise.
</details>
Done.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 504 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1563#-KXHV3JE2Sb82-tBEN2o:-KXQ60osiSLlG7i6U0Tf:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/51844b46f5042b244fc8eb3f04d094c074f31b5c/test/www/jxcore/lib/CoordinatedClient.js#L504)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Shouldn't this still be an error? The fact that we got an unexpected result shows that something is really wrong with the test.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1563)*

**Comment by ThaliTester** [comment]
Test (Fail) 95017841 build is completed (7e1fb69)

See https://github.com/ThaliTester/TestResults/tree/950178417e1fb69_Added_unexpected_error_handler_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1563#-:-KXgKaTC8qsJfoaNgpVU:bnfp4nl)*

**Pull request merged**
