### PR TITLE
Update mobile_test.json

### PR DESCRIPTION
**Pull request by jareksl**
As the configuration of the CI has changed, we need to update the mobile_test.json.
The value of the key csname is used to upload generated test app to the test node and has to be consistent with 'Thali test' provisioning profile.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1870)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (250d573)

**Comment by ThaliTester** [comment]
Test 121460753 (250d573) build started.

**Comment by jareksl** [comment]
*[a discussion](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1870#-KkV65GrB9l_kplzSKZr:-KkV65GrB9l_kplzSKZs:b-w3o6ms) (no related file):*
Please note that this PR contains also changes done within #1867 as it was not merged with the master yet. The only relevant part is the change in the mobile_test.json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1870)*

**Comment by ThaliTester** [comment]
Test (Success) 121460753 build is completed (250d573)

See https://github.com/ThaliTester/TestResults/tree/121460753250d573_Update_mobile_test_json_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 121460753250d573(250d573) has failed

See https://github.com/ThaliTester/TestResults/tree/121460753250d573_Update_mobile_test_json_jareksl/ for the fail logs

**Comment by yaronyg** [comment]
Please see comment about domain name.

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[mobile_test.json, line 10 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1870#-KkkpkTkDogoXVbukci4:-KkkpkTlbLMaz1RNRWTH:b-jw99yx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/250d573c207f699f5b137f89f2d1bfa84d70d1e3/mobile_test.json#L10)):*
> ```JSON
>   "priority": "normal",
>   "csname": {
>     "android": "com.rockwellautomation.thalitest",
> ```

This can't be right. This is an open source project. It wouldn't do to make it specific to a particular company. If you would like you can of course use org.thaliproject.thalitest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1870#-:-Kkkpy9liDuDTxdwoKDX:b3f62s9)*

**Pull request closed without merging**
