### PR TITLE
Added retry for runTestOnAllParticipants

### LINKED ISSUE #1595: Coordinated replication action test needs to be fixed
The test is apparently unreliable. It's not currently clear why.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1595.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1689)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3c9286c)

**Comment by ThaliTester** [comment]
Test 99393312 (3c9286c) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99393312 build is completed (3c9286c)

See https://github.com/ThaliTester/TestResults/tree/993933123c9286c_Added_retry_for_runTestOnAllParticipants_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 993933123c9286c(3c9286c) has failed

See https://github.com/ThaliTester/TestResults/tree/993933123c9286c_Added_retry_for_runTestOnAllParticipants_andrew-aladev/ for the fail logs

**Comment by chapko** [comment]
+@andrew-aladev -@chapko 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/testUtils.js, line 689 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689#-K_-CLCJzPPYXjhZlqgG:-K_-CLCJzPPYXjhZlqgH:bauslg2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3c9286c4048049530c4b0bcb10db3518c68a95e6/test/www/jxcore/lib/testUtils.js#L689)):*
> ```JavaScript
>       })
>       .catch(function (error) {
>         return fail(notificationForUs, notificationForUs.keyId, error);
> ```

I think you can leave only `notificationForUs` argument, I don't see the case when we want to call `fail` with keyId different from `notificationForUs.keyId`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689#-:-K_-EJcrSGnxnnLbGAgH:bk5kwey)*

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 668 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689#-K_1j2su2KDQmLw8XwjK:-K_1j2su2KDQmLw8XwjL:bec4jff) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3c9286c4048049530c4b0bcb10db3518c68a95e6/test/www/jxcore/lib/testUtils.js#L668)):*
> ```JavaScript
> 
>       logger.warn('error ignored: \'%s\' ', String(error));
>       return Promise.delay(RETRY_DELAY)
> ```

Won't this force all of our tests to take at least 10 seconds before they exit since they have to wait for this delay to complete? Our tests take forever as it is. Wouldn't it be better to use a setTimeout that we can then cleanup when completed is set to true?

---

*[test/www/jxcore/lib/testUtils.js, line 693 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689#-K_1jlQN63me2rG5Tk0s:-K_1jlQOVDT4gr5o-TdM:bddo85r) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3c9286c4048049530c4b0bcb10db3518c68a95e6/test/www/jxcore/lib/testUtils.js#L693)):*
> ```JavaScript
>     }
> 
>     thaliNotificationClient.on(
> ```

Shouldn't we unregister this handler when we are done with the test? Just to make things clean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689)*

**Comment by yaronyg** [comment]
Please address the comments and then :lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689#-:-K_1k4f2SL_LaP3_Rzjf:b-cjtmme)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4d5ad12)

**Comment by ThaliTester** [comment]
Test 99393312 (4d5ad12) build started.

**Comment by andrew-aladev** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 668 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689#-K_1j2su2KDQmLw8XwjK:-K_4_zm0NQk3mztFeEXE:b5w9rxi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3c9286c4048049530c4b0bcb10db3518c68a95e6/test/www/jxcore/lib/testUtils.js#L668)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Won't this force all of our tests to take at least 10 seconds before they exit since they have to wait for this delay to complete? Our tests take forever as it is. Wouldn't it be better to use a setTimeout that we can then cleanup when completed is set to true?
</blockquote></details>

Fixed with promise cancel.

---

*[test/www/jxcore/lib/testUtils.js, line 689 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689#-K_-CLCJzPPYXjhZlqgG:-K_4a2-pBPnW6leepZVg:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3c9286c4048049530c4b0bcb10db3518c68a95e6/test/www/jxcore/lib/testUtils.js#L689)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

I think you can leave only `notificationForUs` argument, I don't see the case when we want to call `fail` with keyId different from `notificationForUs.keyId`.
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/testUtils.js, line 693 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689#-K_1jlQN63me2rG5Tk0s:-K_4a3FfY60z-WegjExt:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3c9286c4048049530c4b0bcb10db3518c68a95e6/test/www/jxcore/lib/testUtils.js#L693)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Shouldn't we unregister this handler when we are done with the test? Just to make things clean?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1689)*

**Comment by ThaliTester** [comment]
Test (Fail) 99393312 build is completed (4d5ad12)

See https://github.com/ThaliTester/TestResults/tree/993933124d5ad12_Added_retry_for_runTestOnAllParticipants_andrew-aladev/ for the logs

**Pull request merged**
