### PR TITLE
Fixed reconnect after close

### LINKED ISSUE #1374: Test "#startUpdateAdvertisingAndListening - ending remote peers connection kills the local connection" failed and 'destroy remote peers connection kills the local connection'
Mode : NATIVE
branch : master_1327
commit : 5fa2c6495ef7af136bd528d89f9516f5a0b5a023

Logs
6p - https://gist.github.com/evabishchevich/eb32c7f410234e544d0b716769458f24
6p - https://gist.github.com/evabishchevich/4ee45c3866cb212ac7799207071b5d12
s7 - https://gist.github.com/evabishchevich/ab71e4b7f553522488090500f818a5de

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1374.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1710)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c49686b)

**Comment by ThaliTester** [comment]
Test 100139766 (c49686b) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 100139766 build is completed (c49686b)

See https://github.com/ThaliTester/TestResults/tree/100139766c49686b_Fixed_reconnect_after_close_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aeece48)

**Comment by ThaliTester** [comment]
Test 100139766 (aeece48) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100139766 build is completed (aeece48)

See https://github.com/ThaliTester/TestResults/tree/100139766aeece48_Fixed_reconnect_after_close_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 100139766aeece48(aeece48) has failed

See https://github.com/ThaliTester/TestResults/tree/100139766aeece48_Fixed_reconnect_after_close_andrew-aladev/ for the fail logs

**Comment by jareksl** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 93 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaBpEYG-Lgdg93RWO-E:-KaBpEYG-Lgdg93RWO-F:b-y1ct8z) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/aeece4814f1eacd62d8ddd07bfc36f30d83f00cb/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L93)):*
> ```JavaScript
> 
>           if (retryIndex >= RETRY_COUNT) {
>             var error = 'Too many connect retries';
> ```

Variable error is already declared.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 179 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaC7FmoNa4BgVsE4yel:-KaC7FmoNa4BgVsE4yem:btk8qd4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/aeece4814f1eacd62d8ddd07bfc36f30d83f00cb/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L179)):*
> ```JavaScript
>       }
> 
>       var port = new Number(listeningPort);
> ```

NB: Can't we just use parseInt ?

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 188 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaC2CojVXda0OXX4ZFp:-KaC2CojVXda0OXX4ZFq:b-6j6qr2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/aeece4814f1eacd62d8ddd07bfc36f30d83f00cb/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L188)):*
> ```JavaScript
>         listeningPort: port
>       });
>     }
> ```

missing semicolon

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 196 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaC1xozXn0OJg37747k:-KaC1xozXn0OJg37747l:b-a7ijws) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/aeece4814f1eacd62d8ddd07bfc36f30d83f00cb/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L196)):*
> ```JavaScript
> 
>         if (error) {
>           var error = new Error(format(
> ```

var error is already declared. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710)*

**Comment by jareksl** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (07b9425)

**Comment by ThaliTester** [comment]
Test 100139766 (07b9425) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 100139766 build is completed (07b9425)

See https://github.com/ThaliTester/TestResults/tree/10013976607b9425_Fixed_reconnect_after_close_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3e3ec72)

**Comment by ThaliTester** [comment]
Test 100139766 (3e3ec72) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 100139766 build is completed (3e3ec72)

See https://github.com/ThaliTester/TestResults/tree/1001397663e3ec72_Fixed_reconnect_after_close_andrew-aladev/ for the logs

**Comment by jareksl** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-:-KaDRRMp0Fd3yrGBePib:bg7igkv)*

**Comment by jareksl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710)*

**Comment by yaronyg** [comment]
Please fix comments and then :LGTM:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 4 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaDuJlnbYQ8vKnN2vJZ:-KaDuJloPim02IYkUSO3:b-vgtk5d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3e3ec72988d8c90800a0bb48287e38aa882ac7c9/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L4)):*
> ```JavaScript
> 
> var util   = require('util');
> var format = util.format;
> ```

Why not get rid of the previous line and just use var format = require('util').format?

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 65 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaDuTArlxtFmv6_nCEe:-KaDuTArlxtFmv6_nCEf:br7t64d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3e3ec72988d8c90800a0bb48287e38aa882ac7c9/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L65)):*
> ```JavaScript
> function connectToPeer(peer, quitSignal) {
>   var connectMethod;
>   if (platform.isAndroid) {
> ```

Why are we using cascading if statements? This is what switch was invented for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-:-KaDvPPox5E2YAvnXBuk:b-5oqf56)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0cd47bd)

**Comment by ThaliTester** [comment]
Test 100139766 (0cd47bd) build started.

**Comment by andrew-aladev** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 93 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaBpEYG-Lgdg93RWO-E:-KaMXAIC8vD-_QkZdPde:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/07b9425599223fb076551ea917e25a184ba9ea74/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L93)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

Variable error is already declared.
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 179 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaC7FmoNa4BgVsE4yel:-KaMXBMM4uyP3HJN41ZJ:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/07b9425599223fb076551ea917e25a184ba9ea74/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L179)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

NB: Can't we just use parseInt ?
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 188 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaC2CojVXda0OXX4ZFp:-KaMXBskqrQT410rqcP0:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/07b9425599223fb076551ea917e25a184ba9ea74/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L188)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

missing semicolon
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 196 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaC1xozXn0OJg37747k:-KaMXCVQUy5E6MnxH9aJ:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/07b9425599223fb076551ea917e25a184ba9ea74/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L196)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

var error is already declared. 
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 4 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaDuJlnbYQ8vKnN2vJZ:-KaMX0r-VhrJ7a0LqKtb:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0cd47bd5fe27019c9ae65aa47599f1cbb1d6f9eb/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L4)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why not get rid of the previous line and just use var format = require('util').format?
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 65 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaDuTArlxtFmv6_nCEe:-KaMX27EDs1D2HXCIsxf:b-juagek) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0cd47bd5fe27019c9ae65aa47599f1cbb1d6f9eb/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L65)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why are we using cascading if statements? This is what switch was invented for.
</blockquote></details>

But we have no value for switch, we have only several bools.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710)*

**Comment by ThaliTester** [comment]
Test (Fail) 100139766 build is completed (0cd47bd)

See https://github.com/ThaliTester/TestResults/tree/1001397660cd47bd_Fixed_reconnect_after_close_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (107e6bf)

**Comment by ThaliTester** [comment]
Test 100139766 (107e6bf) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 100139766 build is completed (107e6bf)

See https://github.com/ThaliTester/TestResults/tree/100139766107e6bf_Fixed_reconnect_after_close_andrew-aladev/ for the logs

**Comment by jareksl** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 65 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaDuTArlxtFmv6_nCEe:-KaNne1_GGxNGPg9aa4d:b-xx7j0b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0cd47bd5fe27019c9ae65aa47599f1cbb1d6f9eb/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L65)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary><blockquote>

But we have no value for switch, we have only several bools.
</blockquote></details>

Which argues that we should change platform to return an enum because you have to admit this code looks pretty silly. But we can fix that later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-:-KaNnlhgjDBTETYbYK7J:bnfp4nl)*

**Comment by andrew-aladev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 65 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710#-KaDuTArlxtFmv6_nCEe:-KaO8gshuHn8_KwioA-c:b32w1t) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0cd47bd5fe27019c9ae65aa47599f1cbb1d6f9eb/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L65)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Which argues that we should change platform to return an enum because you have to admit this code looks pretty silly. But we can fix that later.
</blockquote></details>

Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1710)*

**Pull request merged**
