### PR TITLE
Update jxcore-cordova to 0.1.12 version

### PR DESCRIPTION
**Pull request by jareksl**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1889)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f9539cc)

**Comment by ThaliTester** [comment]
Test 123283391 (f9539cc) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 123283391 build is completed (f9539cc)

See https://github.com/ThaliTester/TestResults/tree/123283391f9539cc_Update_jxcore-cordova_to_0_1_12_version_jareksl/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1889#-:-KlUd6qggzz0lqLmrR8p:bnfp4nl)*

**Pull request merged**
