### PR TITLE
Temporary test for install reliability.

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/432)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5084821)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (5084821)

See https://github.com/ThaliTester/TestResults/tree/557421425084821_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c670d62)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (54ee7cc)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (efc1afe)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (3046194)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (c670d62)

See https://github.com/ThaliTester/TestResults/tree/55742142c670d62_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (54ee7cc)

See https://github.com/ThaliTester/TestResults/tree/5574214254ee7cc_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (efc1afe)

See https://github.com/ThaliTester/TestResults/tree/55742142efc1afe_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (3046194)

See https://github.com/ThaliTester/TestResults/tree/557421423046194_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0454eb2)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (0454eb2)

See https://github.com/ThaliTester/TestResults/tree/557421420454eb2_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3319410)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (3319410)

See https://github.com/ThaliTester/TestResults/tree/557421423319410_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a5c2fdb)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b7b43f5)

**Comment by ThaliTester** [comment]
Test (Success) 55742142 build is completed (a5c2fdb)

See https://github.com/ThaliTester/TestResults/tree/55742142a5c2fdb_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (b7b43f5)

See https://github.com/ThaliTester/TestResults/tree/55742142b7b43f5_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (91fbec1)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (a5acd90)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (91fbec1)

See https://github.com/ThaliTester/TestResults/tree/5574214291fbec1_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (a5acd90)

See https://github.com/ThaliTester/TestResults/tree/55742142a5acd90_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 55742142a5c2fdb(a5c2fdb) has failed

See https://github.com/ThaliTester/TestResults/tree/55742142a5c2fdb_Temporary_test_for_install_reliability__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (51a41e5)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8cce9af)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (245ce58)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (108f5fe)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (51a41e5)

See https://github.com/ThaliTester/TestResults/tree/5574214251a41e5_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (8cce9af)

See https://github.com/ThaliTester/TestResults/tree/557421428cce9af_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (245ce58)

See https://github.com/ThaliTester/TestResults/tree/55742142245ce58_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (108f5fe)

See https://github.com/ThaliTester/TestResults/tree/55742142108f5fe_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e8134b1)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8dacdeb)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (e8134b1)

See https://github.com/ThaliTester/TestResults/tree/55742142e8134b1_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (8dacdeb)

See https://github.com/ThaliTester/TestResults/tree/557421428dacdeb_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (08ebfb3)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b4a6003)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (932d5e2)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (0c0b840)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (984c9f7)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (08ebfb3)

See https://github.com/ThaliTester/TestResults/tree/5574214208ebfb3_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (b4a6003)

See https://github.com/ThaliTester/TestResults/tree/55742142b4a6003_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (932d5e2)

See https://github.com/ThaliTester/TestResults/tree/55742142932d5e2_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (9c468af)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (675f38e)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (4331455)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (41a3cbc)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (77ed97e)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (0c0b840)

See https://github.com/ThaliTester/TestResults/tree/557421420c0b840_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (984c9f7)

See https://github.com/ThaliTester/TestResults/tree/55742142984c9f7_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (9c468af)

See https://github.com/ThaliTester/TestResults/tree/557421429c468af_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (675f38e)

See https://github.com/ThaliTester/TestResults/tree/55742142675f38e_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (4331455)

See https://github.com/ThaliTester/TestResults/tree/557421424331455_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (41a3cbc)

See https://github.com/ThaliTester/TestResults/tree/5574214241a3cbc_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (77ed97e)

See https://github.com/ThaliTester/TestResults/tree/5574214277ed97e_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c6cb7f0)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (714016d)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (544c63d)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (943596d)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (33a175b)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (c6cb7f0)

See https://github.com/ThaliTester/TestResults/tree/55742142c6cb7f0_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (714016d)

See https://github.com/ThaliTester/TestResults/tree/55742142714016d_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (544c63d)

See https://github.com/ThaliTester/TestResults/tree/55742142544c63d_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (943596d)

See https://github.com/ThaliTester/TestResults/tree/55742142943596d_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (33a175b)

See https://github.com/ThaliTester/TestResults/tree/5574214233a175b_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (73f6cf9)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (73f6cf9)

See https://github.com/ThaliTester/TestResults/tree/5574214273f6cf9_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (88332e3)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (88332e3)

See https://github.com/ThaliTester/TestResults/tree/5574214288332e3_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f7e01f4)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (64eda22)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (2f02390)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (f7e01f4)

See https://github.com/ThaliTester/TestResults/tree/55742142f7e01f4_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (64eda22)

See https://github.com/ThaliTester/TestResults/tree/5574214264eda22_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (2f02390)

See https://github.com/ThaliTester/TestResults/tree/557421422f02390_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (93edc33)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (155eff2)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (dbd6e48)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (b772da3)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (b5c5e17)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (e86cd55)

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (93edc33)

See https://github.com/ThaliTester/TestResults/tree/5574214293edc33_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (155eff2)

See https://github.com/ThaliTester/TestResults/tree/55742142155eff2_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (dbd6e48)

See https://github.com/ThaliTester/TestResults/tree/55742142dbd6e48_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (b772da3)

See https://github.com/ThaliTester/TestResults/tree/55742142b772da3_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (b5c5e17)

See https://github.com/ThaliTester/TestResults/tree/55742142b5c5e17_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55742142 build is completed (e86cd55)

See https://github.com/ThaliTester/TestResults/tree/55742142e86cd55_Temporary_test_for_install_reliability__vjrantal/ for the logs

**Comment by vjrantal** [comment]
Worked now 7/7 so seems reliable.

**Pull request closed without merging**
