### PR TITLE
illigal argument fix

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1584)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1c681a9)

**Comment by ThaliTester** [comment]
Test 95911002 (1c681a9) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95911002 build is completed (1c681a9)

See https://github.com/ThaliTester/TestResults/tree/959110021c681a9_illigal_argument_fix_vasilevskayaem/ for the logs

**Comment by yaronyg** [comment]
@vasilevskayaem Why wasn't this submitted for check in? As it is I decided not to do a revert because it just makes a huge mess of everything and instead I'm deleting setBufferSizes. But this would probably have been better.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1584#-:-KXrNEHlf4GavbZCE0_z:b-6onrhd)*

**Pull request closed without merging**
