### PR TITLE
Updating .jshintrc per Issue #331

### PR DESCRIPTION
**Pull request by mpodwysocki**
Updating with additional checks to make our code cleaner

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/332)

### CODE REVIEW

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

<sup>**[.jshintrc, line 4 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3HC0ilMkv0TURHCG69)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L4)):</sup>
Shouldn't we set esversion to 5?
Freeze also seems like a good idea.
latedef also makes a lot of sense
maxdepth set to 2 or 3 also seems wise


---

<sup>**[.jshintrc, line 5 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3HBXrSE_eJ17ZWQ5_U)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L5)):</sup>
immed is going bye bye. Shouldn't we bring in jscs? This would give us much better control over our style


---

<sup>**[.jshintrc, line 6 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3HBrz8ovoWkFEbib2q)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L6)):</sup>
Same as immed


---

<sup>**[.jshintrc, line 7 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3HCvIzRTgplNZgbA-N)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L7)):</sup>
I'm sure it will make somebody unhappy but I'd love to add nocomma
I don't think it's a big deal but it seems pretty harmless to throw in nonbsp
nonew seems good as well
singleGroups seems good


---

<sup>**[.jshintrc, line 12 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IPeJu-p0uauiDi_SR)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L12)):</sup>
Do we actually want browser set to true? The code in the Thali_CordovaPlugin project doesn't run in the browser.


---

<sup>**[.jshintrc, line 14 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IQVTuwO29U9Y0IXL5)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L14)):</sup>
Do we want strict set to global? This would also let us get rid of the deprecated globalstrict


---

<sup>**[.jshintrc, line 15 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IQ3CskpW1lUl1_sIu)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L15)):</sup>
I can't find trailing as a listed option in http://jshint.com/docs/options


---

<sup>**[.jshintrc, line 16 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IQQ6qwfVvpPVYRUol)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L16)):</sup>
globalstrict is being deprecated so we should probably remove it.


---

<sup>**[.jshintrc, line 17 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IQn8qqdOuIKoX__-E)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L17)):</sup>
I can't find white listed in http://jshint.com/docs/options


---

<sup>**[.jshintrc, line 18 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IQxQAf1RzpfvNhnFv)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L18)):</sup>
This is being deprecated. Again, shouldn't we use JSCS?


---

<sup>**[.jshintrc, line 21 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IRGX4mtRzqgDQqAAZ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L21)):</sup>
Which warning is W030?


---

<sup>**[.jshintrc, line 22 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IRN9VC49YSXB6l0jB)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L22)):</sup>
Since JXCore is Node 0.10 and as Node 0.10 doesn't support EcmaScript 6 is defining this as a predef a bad idea? For now we have to explicit require a library like lie or we won't have promises and this could hide that until runtime. Once we use EcmaScript 6 runtimes on all our platforms we can revisit.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332)

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by mpodwysocki** [comment]
<sup>**[.jshintrc, line 18 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IQxQAf1RzpfvNhnFv)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L18)):</sup>
Will look into jscs after this...


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332)

**Comment by mpodwysocki** [comment]
<sup>**[.jshintrc, line 21 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3IRGX4mtRzqgDQqAAZ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af451c0cb8a4190d652a43d9c9c424c2c270f488/.jshintrc#L21)):</sup>
Got rid of it instead, put in expr: true


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332)

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[.jscsrc, line 2 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3LJf4eS0grJ-uGjrHI)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/16f6c8a22e70d55d6f7ef743bdc3c27694b08434/.jscsrc#L2)):</sup>
I'm not sure I agree on this one. The reason is that I sometimes have unused params to remind me of the fact that the argument is being passed to me but I'm not currently using it. This is really common with callbacks. I'm torn on this one.


---

<sup>**[.jscsrc, line 9 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3LKV9P9ax-i_kOOlHG)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/16f6c8a22e70d55d6f7ef743bdc3c27694b08434/.jscsrc#L9)):</sup>
Shouldn't we have checkRedundantReturns: true?
Also we should have checkTypes: strictNativeCase, this one has been driving me crazy and my own docs are a mess because of it. Would love to have this checked.
I'm also shocked you didn't jump on checkRedundantAccess with "enforceLeadingUnderscore"
I'm also surprised you didn't jump on leadingUnderscoreAccess
I suspect requireDescriptionCompleteSentence is probably a good idea


---

<sup>**[.jscsrc, line 70 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3LXYZg3TWmkzQXp5by)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/16f6c8a22e70d55d6f7ef743bdc3c27694b08434/.jscsrc#L70)):</sup>
I'm really drawn ot maximumNumberOfLines. There is a limit there somewhere, say 1000 lines after which it's time to split.
We should set requireCamelCaseOrUpperCaseIdentifier to true
The temptation to set requireVarDeclFirst is really high. :)
We absolutely must set safeContextKeyword, I prefer self to that but whatever. We need this to be consistent!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332)

**Comment by mpodwysocki** [comment]
_[.jscsrc, line 2 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3LJf4eS0grJ-uGjrHI:-K3NCIVxm1NmSumzYYZA:-39924976) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/16f6c8a22e70d55d6f7ef743bdc3c27694b08434/.jscsrc#L2)):_
I'm not because it forces you to use what you declare.  Remember that if you have multiple parameters and only using the last one, then it won't count against you.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332)_

**Comment by mpodwysocki** [comment]
_[.jscsrc, line 70 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3LXYZg3TWmkzQXp5by:-K3NFBNEXv99seMNG0x5:509158388) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/16f6c8a22e70d55d6f7ef743bdc3c27694b08434/.jscsrc#L70)):_
Set the this = self for safeContextKeyword.
Let's hold off on the requireVarDeclFirst at the moment.
Agreed on the line limit which would keep us from big balls of mud, although if our documentation is that long, is that worth it?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332)_

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by yaronyg** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[.jscsrc, line 70 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332#-K3LXYZg3TWmkzQXp5by:-K3QdwuUopIeh8H7euM_:842956316) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/16f6c8a22e70d55d6f7ef743bdc3c27694b08434/.jscsrc#L70)):_
My goal is that as the docs get implemented we delete the procedural parts of the doc and just use the code. I expect to review code by seeing what was deleted in the doc and confirming the code matches.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332)_

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/332)*

**Comment by yaronyg** [comment]
:shipit:

**Pull request merged**
