### PR TITLE
Fixed t.sync by using relative path

### LINKED ISSUE #1613: t.sync() fails on iOS devices
*'Coordinated pull replication from notification test'* fails on iOS devices. It looks like `t.sync()` somehow disconnects devices from coordinated server.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1613.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1648)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (816c514)

**Comment by ThaliTester** [comment]
Test 98149861 (816c514) build started.

**Comment by ThaliTester** [comment]
Test (Success) 98149861 build is completed (816c514)

See https://github.com/ThaliTester/TestResults/tree/98149861816c514_Fixed_t_sync_by_using_relative_path_andrew-aladev/ for the logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 25 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1648#-KZ1kSEZapV1fPvg3hWi:-KZ1kSEZapV1fPvg3hWj:b-jksmod) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/816c5142eb77474fb1124ae4772d43f092669849/test/www/jxcore/lib/CoordinatedClient.js#L25)):*
> ```JavaScript
> 
> var DEFAULT_SERVER_PORT = Number(process.env.COORDINATED_PORT) || 3000;
> var CURRENT_PATH        = __dirname;
> ```

NB: `__dirname` by definition is a current path, so I think there's no need to have additional name for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1648#-:-KZ1oHes7oAo8i3Zwlne:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 98149861816c514(816c514) has failed

See https://github.com/ThaliTester/TestResults/tree/98149861816c514_Fixed_t_sync_by_using_relative_path_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 25 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1648#-KZ1kSEZapV1fPvg3hWi:-KZ3buk3WfpfevA19ZvN:b-wu5bae) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/816c5142eb77474fb1124ae4772d43f092669849/test/www/jxcore/lib/CoordinatedClient.js#L25)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

NB: `__dirname` by definition is a current path, so I think there's no need to have additional name for it.
</blockquote></details>

NB: I agree. Unless we intend to somehow manipulate CURRENT_PATH so it != __dirname then we should just use __dirname. Yes, it's a magic value but it's a very well known one in Node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1648#-:-KZ3cIyeyUwGGaPCb_4-:bnfp4nl)*

**Pull request merged**
