### PR TITLE
Update jxcore to 0.3.1.10

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1796)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2a9649b)

**Comment by ThaliTester** [comment]
Test 105848630 (2a9649b) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 105848630 build is completed (2a9649b)

See https://github.com/ThaliTester/TestResults/tree/1058486302a9649b_Update_jxcore_to_0_3_1_10_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
It's just version update. We tested it locally, everything is ok

**Pull request merged**
