### PR TITLE
#1017 DO_NOT_MERGE Testing CI with only one test that should pass

### LINKED ISSUE #1017: Get one test to pass in CI
Something is wrong with coordination server in CI. To try and figure out what we should get one of the platforms that are working (we'll tell you which one) and then write a single test (disable/delete all the other ones, please do this in a new branch since we will throw this branch away) that just passes and see if we can get that to reliably work in CI.

### PR DESCRIPTION
**Pull request by artemjackson**
DO NOT MERGE

Only for CI testing purpose

Closes #1017 

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1020)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (94fce99)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (543e137)

**Comment by ThaliTester** [comment]
Test (Fail) 84843296 build is completed (94fce99)

See https://github.com/ThaliTester/TestResults/tree/8484329694fce99__1017_DO_NOT_MERGE_Testing_CI_with_only_one_test_that_should_pass_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 84843296 build is completed (543e137)

See https://github.com/ThaliTester/TestResults/tree/84843296543e137__1017_DO_NOT_MERGE_Testing_CI_with_only_one_test_that_should_pass_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 84843296543e137(543e137) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/84843296543e137__1017_DO_NOT_MERGE_Testing_CI_with_only_one_test_that_should_pass_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (09337e6)

**Comment by ThaliTester** [comment]
Test (Success) 84843296 build is completed (09337e6)

See https://github.com/ThaliTester/TestResults/tree/8484329609337e6__1017_DO_NOT_MERGE_Testing_CI_with_only_one_test_that_should_pass_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8484329609337e6(09337e6) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8484329609337e6__1017_DO_NOT_MERGE_Testing_CI_with_only_one_test_that_should_pass_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (00bfcdc)

**Comment by ThaliTester** [comment]
Test (Success) 84843296 build is completed (00bfcdc)

See https://github.com/ThaliTester/TestResults/tree/8484329600bfcdc__1017_DO_NOT_MERGE_Testing_CI_with_only_one_test_that_should_pass_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8484329600bfcdc(00bfcdc) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8484329600bfcdc__1017_DO_NOT_MERGE_Testing_CI_with_only_one_test_that_should_pass_artemjackson/ for the logs

**Comment by artemjackson** [comment]
@yaronyg It's really strange that native tests of this branch pass 3 times in a row but parent's branch tests don't.
A deeper investigation is needed.

**Comment by artemjackson** [comment]
Proved that CI works well. Closed.

**Pull request closed without merging**
