### PR TITLE
Add test for bad parameters in multiConnect, edit wifiBasedNativeMock

### PR DESCRIPTION
**Pull request by squid48**
thaliproject/Thali_CordovaPlugin#1079

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1706)

### CODE REVIEW

**Comment by ThaliTester** [comment]
Test 99652131 (69fe96d) build started.

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1706#-:-K_9fmYP6-EN8eN8Yp19:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 99652131 build is completed (69fe96d)

See https://github.com/ThaliTester/TestResults/tree/9965213169fe96d_Add_test_for_bad_parameters_in_multiConnect__edit_wifiBasedNativeMock_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 9965213169fe96d(69fe96d) has failed

See https://github.com/ThaliTester/TestResults/tree/9965213169fe96d_Add_test_for_bad_parameters_in_multiConnect__edit_wifiBasedNativeMock_squid48/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1706#-:-K_ANFansmidKO1sSsjs:bnfp4nl)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1706#-:-K_YkB63LaY-iOo9lh8D:bnfp4nl)*

**Comment by evabishchevich** [comment]
Ready to merge because thaliproject/Thali_CordovaPlugin#1705  already closed. @andrew-aladev please,  look at it one more time and merge this PR if everything is ok.

**Pull request merged**
