### PR TITLE
#758 Added shrinkwrap files

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/905)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (68baf36)

**Comment by ThaliTester** [comment]
Test (Success) 81802856 build is completed (68baf36)

See https://github.com/ThaliTester/TestResults/tree/8180285668baf36__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8180285668baf36(68baf36) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8180285668baf36__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by yaronyg** [comment]
@artemjackson - What did you have to change in order to get this to work? 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/905#-:-KPUy03BIswce9fMtH6N:b-uzfgfo)*

**Comment by artemjackson** [comment]
I removed `node_modules` and all `npm-shrinkwrap.json`, set `jx npm registry` to use local sinopia and did shrinkwrap again.
It was a problem that `jx npm registry` was not set correctly.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/905#-:-KPX3Vy979OT4ka2eJgV:b-4yh8ze)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/905#-:-KPYR_w6FKCe6IDI_Com:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (44342f8)

**Comment by ThaliTester** [comment]
Test (Success) 81802856 build is completed (44342f8)

See https://github.com/ThaliTester/TestResults/tree/8180285644342f8__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8180285644342f8(44342f8) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8180285644342f8__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Pull request merged**
