### PR TITLE
I os 898 2

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1249)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d34ccd7)

**Comment by yaronyg** [comment]
This work is by @chapko and was reviewed and approved by both @andrew-aladev and myself. But I screwed up the original PR. So I have created this one and merged it with our iOS branch.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1249#-:-KTHELM0_vSmoa4yRNxh:bfhs4z4)*

**Comment by ThaliTester** [comment]
Test (Success) 87998460 build is completed (d34ccd7)

See https://github.com/ThaliTester/TestResults/tree/87998460d34ccd7_I_os_898_2_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 87998460d34ccd7(d34ccd7) has failed

See https://github.com/ThaliTester/TestResults/tree/87998460d34ccd7_I_os_898_2_yaronyg/ for the fail logs

**Pull request merged**
