### PR TITLE
Update compile sdk version to 25

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1851)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (42f3537)

**Comment by ThaliTester** [comment]
Test 113657308 (42f3537) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 113657308 build is completed (42f3537)

See https://github.com/ThaliTester/TestResults/tree/11365730842f3537_Update_compile_sdk_version_to_25_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ae914df)

**Comment by ThaliTester** [comment]
Test 113657308 (ae914df) build started.

**Comment by ThaliTester** [comment]
Test (Success) 113657308 build is completed (ae914df)

See https://github.com/ThaliTester/TestResults/tree/113657308ae914df_Update_compile_sdk_version_to_25_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 113657308ae914df(ae914df) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/113657308ae914df_Update_compile_sdk_version_to_25_evabishchevich/ for the logs

**Comment by mlesnic** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1851#-:-KgmChvvPdYW6a4mqKmU:bnfp4nl)*

**Pull request merged**
