### PR TITLE
Move off JXcore where we can

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1092)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ae0496b)

**Comment by ThaliTester** [comment]
Test (Success) 85960304 build is completed (ae0496b)

See https://github.com/ThaliTester/TestResults/tree/85960304ae0496b_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 85960304ae0496b(ae0496b) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/85960304ae0496b_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by yaronyg** [comment]
Please merge thaliproject/Thali_CordovaPlugin#1025 and then close thaliproject/Thali_CordovaPlugin#1025

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ae4d880)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (ae4d880)

See https://github.com/ThaliTester/TestResults/tree/85960304ae4d880_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by larryonoff** [comment]
@yaronyg I've cherry-picked your changes from thaliproject/Thali_CordovaPlugin#1025. Please note the following:

1. 'vNext' doesn't have 'installCustomPouchDB.js' so 'installCustomPouchDB.js' and 'setUpDesktop.sh' changes aren't included.
2. 'thali/package.json' was also skipped because I'm not sure that it should be in 'vNext' now.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (90f13ee)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (90f13ee)

See https://github.com/ThaliTester/TestResults/tree/8596030490f13ee_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by yaronyg** [comment]
:lgtm: (once it actually passes in CI of course)

---

Reviewed 1 of 1 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-:-KS8YeiplcZkAKtb6LEB:b-ochqs1)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (7caafcd)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (7caafcd)

See https://github.com/ThaliTester/TestResults/tree/859603047caafcd_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (756d9b7)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (756d9b7)

See https://github.com/ThaliTester/TestResults/tree/85960304756d9b7_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (5adc988)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (5adc988)

See https://github.com/ThaliTester/TestResults/tree/859603045adc988_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ec0d8a1)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (ec0d8a1)

See https://github.com/ThaliTester/TestResults/tree/85960304ec0d8a1_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (1ea1ffb)

**Comment by ThaliTester** [comment]
Test (Success) 85960304 build is completed (1ea1ffb)

See https://github.com/ThaliTester/TestResults/tree/859603041ea1ffb_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 859603041ea1ffb(1ea1ffb) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/859603041ea1ffb_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e9d96a8)

**Comment by larryonoff** [comment]
@yaronyg I started having some doubts that we're doing right things here. We install node modules for thali via node (not via jx). So is it right? What was the reason using custom npm for jx version?

**Comment by ThaliTester** [comment]
Test (Success) 85960304 build is completed (e9d96a8)

See https://github.com/ThaliTester/TestResults/tree/85960304e9d96a8_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 85960304e9d96a8(e9d96a8) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/85960304e9d96a8_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fe37dec)

**Comment by ThaliTester** [comment]
Test (Success) 85960304 build is completed (fe37dec)

See https://github.com/ThaliTester/TestResults/tree/85960304fe37dec_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 85960304fe37dec(fe37dec) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/85960304fe37dec_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by yaronyg** [comment]
@larryonoff Unfortunately this PR doesn't really show any issues because its build.sh has lines 58-60 commented out. So even if these changes completely blew up everything we wouldn't actually know. :( So before we can accept this we have to uncomment lines 58-60 and if tests are failing we need to disable them until we get to a set that do succeed.

---

Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/install/install.js, line 307 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-KSDVW961buSwxU2CinV:-KSDVW961buSwxU2CinW:bws96oj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe37dec531dc7e765186d2b3c76d67b12b4f52ad/thali/install/install.js#L307)):*
> ```JavaScript
>   // scenarios.
>   //
>   // 5 folders up
> ```

NB: I don't think you need the comment.

---

*[thali/install/setUpDesktop.sh, line 3 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-KSDVaDMnmr-Z6TjF0-e:-KSDVaDMnmr-Z6TjF0-f:bg2whav) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/90f13ee4412c3828dde49e40c09b2641b63c888a/thali/install/setUpDesktop.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> 
> NODEJS_ORG_MIRROR=https://jxcore.azureedge.net
> ```

Per our conversation we need this.

---

*[thali/install/setUpDesktop.sh, line 6 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-KSDXF3pgPrbboS-LIHV:-KSDXF3qO5FDkiAH_iGc:b-ioqlzf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe37dec531dc7e765186d2b3c76d67b12b4f52ad/thali/install/setUpDesktop.sh#L6)):*
> ```Shell
> set -e
> 
> cd `dirname $0`
> ```

TestServer MUST NOT need jx so if you get a failure using normal npm there we have an issue.
For the thali subdirectory I'm not so sure. I think npm should be o.k.
However test/www/jxcore is a different story. I would expect we have to use 'jx npm' there but please give it a try as is once you uncomment lines 58-60 in build.sh and see what happens.

---

*[thali/install/setUpTests.sh, line 68 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-KSDXuPBi-ELzXaH8l8Y:-KSDXuPCw5iZtk9Bjfxa:bcxlfhb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe37dec531dc7e765186d2b3c76d67b12b4f52ad/thali/install/setUpTests.sh#L68)):*
> ```Shell
> 
>   cd $TEST_PROJECT_ROOT_DIR/www/jxcore;ERROR_ABORT
>   npm install $REPO_ROOT_DIR/thali --save --no-optional --production;ERROR_ABORT
> ```

As I mentioned above I think this should work but we need to check

---

*[thali/install/setUpTests.sh, line 83 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-KSDYD_GiMqjzHHymfH1:-KSDYD_GiMqjzHHymfH2:bdzrxg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe37dec531dc7e765186d2b3c76d67b12b4f52ad/thali/install/setUpTests.sh#L83)):*
> ```Shell
>   # keys) that makes Android unhappy so we remove it below in addition to the gz
>   # files.
>   npm install --no-optional --production;ERROR_ABORT
> ```

This one I'm a little worried about but let's test and see if it works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-:-KSDWsQ5A-YICjR3wbOK:b7zixyx)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (727dacc)

**Comment by larryonoff** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/install/install.js, line 307 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-KSDVW961buSwxU2CinV:-KSGwMA_IPLv-Q4MCqir:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe37dec531dc7e765186d2b3c76d67b12b4f52ad/thali/install/install.js#L307)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: I don't think you need the comment.
</details>
Done.

---

*[thali/install/setUpDesktop.sh, line 3 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092#-KSDVaDMnmr-Z6TjF0-e:-KSGwPgs3e_qmI7hDuiT:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/90f13ee4412c3828dde49e40c09b2641b63c888a/thali/install/setUpDesktop.sh#L3)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Per our conversation we need this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1092)*

**Comment by ThaliTester** [comment]
Test (Success) 85960304 build is completed (727dacc)

See https://github.com/ThaliTester/TestResults/tree/85960304727dacc_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 85960304727dacc(727dacc) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/85960304727dacc_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7cb52d1)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (7cb52d1)

See https://github.com/ThaliTester/TestResults/tree/859603047cb52d1_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (f513406)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (f513406)

See https://github.com/ThaliTester/TestResults/tree/85960304f513406_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (ffade56)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (ffade56)

See https://github.com/ThaliTester/TestResults/tree/85960304ffade56_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9092e41)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (9092e41)

See https://github.com/ThaliTester/TestResults/tree/859603049092e41_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by larryonoff** [comment]
The same issues are in vNext. I created branch from vNext and enabled node tests and the same failures, see https://github.com/ThaliTester/TestResults/tree/863711223fa86da_DON_T_MERGE__only_to_test_vNext_larryonoff/

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (19a1080)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (19a1080)

See https://github.com/ThaliTester/TestResults/tree/8596030419a1080_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3d5017f)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (3d5017f)

See https://github.com/ThaliTester/TestResults/tree/859603043d5017f_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (3ece497)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (3ece497)

See https://github.com/ThaliTester/TestResults/tree/859603043ece497_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by larryonoff** [comment]
@yaronyg 

We're having new issues. The coordinates tests

1. Just hangs on my machine
2. Fails without any useful information on CI.

See CI logs, https://github.com/ThaliTester/TestResults/tree/859603043ece497_Move_off_JXcore_where_we_can_larryonoff.

So I see two possible solutions here.

1. Investigate what's wrong.
2. rebase this into super-branch, but before we need merge super-branch into vNext or vNext into super-branch.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 8. task. (1f673c3)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (1f673c3)

See https://github.com/ThaliTester/TestResults/tree/859603041f673c3_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by yaronyg** [comment]
We'll hold on this until everything is merged into vNext

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (2966b23)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (2966b23)

See https://github.com/ThaliTester/TestResults/tree/859603042966b23_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (796935f)

**Comment by ThaliTester** [comment]
Test (Fail) 85960304 build is completed (796935f)

See https://github.com/ThaliTester/TestResults/tree/85960304796935f_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by larryonoff** [comment]
closing in favour of thaliproject/Thali_CordovaPlugin#1200

**Pull request closed without merging**
