### PR TITLE
V next tompaana 486

### PR DESCRIPTION
**Pull request by tompaana**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/503)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cde8cd1)

**Comment by ThaliTester** [comment]
Test (Fail) 57659382 build is completed (cde8cd1)

See https://github.com/ThaliTester/TestResults/tree/57659382cde8cd1_V_next_tompaana_486_tompaana/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b63fd0b)

**Comment by ThaliTester** [comment]
Test 57659382b63fd0b(b63fd0b) has failed

See https://github.com/ThaliTester/TestResults/tree/57659382b63fd0b_V_next_tompaana_486_tompaana/ for the fail logs

**Comment by juhanak** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 152 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/503#-K9Ra_-5oAjAuQTBkBnq:-K9Ra_-5oAjAuQTBkBnr:-76387978) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b63fd0b4047608a1a5a58913680b11cd52aebfb3/src/android/java/io/jxcore/node/ConnectionHelper.java#L152)):*
No action required but this seems little strange design if both outgoing & incoming connections are killed and only incoming connection count is returned.  

---

*[src/android/java/io/jxcore/node/PeerAndConnectionModel.java, line 169 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/503#-K9RV9pAw-dDajQEC_CF:-K9RV9pAw-dDajQEC_CG:-1176146273) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b63fd0b4047608a1a5a58913680b11cd52aebfb3/src/android/java/io/jxcore/node/PeerAndConnectionModel.java#L169)):*
closeAndRemoveIncomingConnectionThread & closeAndRemoveOutgoingConnectionThread are very similar.. If reasonable, can input parameters be aligned? For instance, closeAndRemoveOutgoingConnectionThread to take incomingSocketId?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/503)*

**Comment by tompaana** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 152 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/503#-K9Ra_-5oAjAuQTBkBnq:-K9W4LJzT1GikQUolaq_:1235050111) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b63fd0b4047608a1a5a58913680b11cd52aebfb3/src/android/java/io/jxcore/node/ConnectionHelper.java#L152)):*
The reason for this is that - as far as I can tell - incoming connections should be closed by the peer who established them, not us. Thus, the number of incoming connections we have to kill interests us.

---

*[src/android/java/io/jxcore/node/PeerAndConnectionModel.java, line 169 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/503#-K9RV9pAw-dDajQEC_CF:-K9W4qLfitZywSLz0Crc:1339663171) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b63fd0b4047608a1a5a58913680b11cd52aebfb3/src/android/java/io/jxcore/node/PeerAndConnectionModel.java#L169)):*
Perhaps, but note that they have their own containers. We can do this in the next release.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/503)*

**Pull request merged**
