### PR TITLE
DO_NOT_MERGE CI smoke test #74

### PR DESCRIPTION
**Pull request by mlesnic**
[https://github.com/thaliproject/CI/issues/74]
Added script which creates one native and one node test. Then edit proper files to execute only these tests.

This PR is not finished, there is no test for iOS. The final PR will be also to vNext, this one is to vNext_yarong_417_812 because this is the branch where node tests are working, so I can check if everything is ok with testing node layer. 

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1027)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (526c333)

**Comment by ThaliTester** [comment]
Test (Success) 85019474 build is completed (526c333)

See https://github.com/ThaliTester/TestResults/tree/85019474526c333_Create_CI_smoke_test__74_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 85019474526c333(526c333) has failed

See https://github.com/ThaliTester/TestResults/tree/85019474526c333_Create_CI_smoke_test__74_mlesnic/ for the fail logs

**Comment by jareksl** [comment]
*[test/www/jxcore/CITestMode.js, line 41 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1027#-KRYSt87VqHKcMlYS85Y:-KRYSt88e6S74Dp2jwmz:b-q4h4jp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/526c3337ea48744e66a223c1379924e587c2f03b/test/www/jxcore/CITestMode.js#L41)):*
> ```JavaScript
>   try {
>     var path = '../../../src/android/test/io/jxcore/node/CITestClass.java';
>     var content = 'package io.jxcore.node;\nimport org.junit.Test;\nimport static org.hamcrest.CoreMatchers.is;\
> ```

Better would be to copy these files instead of create them on the fly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1027)*

**Comment by mlesnic** [comment]
For some reason phones are not connecting to Coordination Server.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (3366852)

**Comment by ThaliTester** [comment]
Test (Success) 85019474 build is completed (3366852)

See https://github.com/ThaliTester/TestResults/tree/850194743366852_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 850194743366852(3366852) has failed

See https://github.com/ThaliTester/TestResults/tree/850194743366852_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (bab212f)

**Comment by ThaliTester** [comment]
Test (Success) 85019474 build is completed (bab212f)

See https://github.com/ThaliTester/TestResults/tree/85019474bab212f_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 85019474bab212f(bab212f) has failed

See https://github.com/ThaliTester/TestResults/tree/85019474bab212f_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (d947a2e)

**Comment by ThaliTester** [comment]
Test (Success) 85019474 build is completed (d947a2e)

See https://github.com/ThaliTester/TestResults/tree/85019474d947a2e_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 85019474d947a2e(d947a2e) has failed

See https://github.com/ThaliTester/TestResults/tree/85019474d947a2e_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (fcda771)

**Comment by ThaliTester** [comment]
Test (Success) 85019474 build is completed (fcda771)

See https://github.com/ThaliTester/TestResults/tree/85019474fcda771_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 85019474fcda771(fcda771) has failed

See https://github.com/ThaliTester/TestResults/tree/85019474fcda771_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (898df24)

**Comment by ThaliTester** [comment]
Test (Success) 85019474 build is completed (898df24)

See https://github.com/ThaliTester/TestResults/tree/85019474898df24_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 85019474898df24(898df24) has failed

See https://github.com/ThaliTester/TestResults/tree/85019474898df24_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dae17e3)

**Comment by ThaliTester** [comment]
Test (Success) 85019474 build is completed (dae17e3)

See https://github.com/ThaliTester/TestResults/tree/85019474dae17e3_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 85019474dae17e3(dae17e3) has failed

See https://github.com/ThaliTester/TestResults/tree/85019474dae17e3_DO_NOT_MERGE_CI_smoke_test__74_mlesnic/ for the fail logs

**Comment by mlesnic** [comment]
There is something wrong with running node tests. It seems that after native tests are finished, the application is restarted and unit native tests are executed over and over until timeout.

**Pull request closed without merging**
