### PR TITLE
New test server for super branch

### LINKED ISSUE #1058: Merge PR with new server into new super branch

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1058 

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1061)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c926e20)

**Comment by ThaliTester** [comment]
Test (Success) 85594025 build is completed (c926e20)

See https://github.com/ThaliTester/TestResults/tree/85594025c926e20_New_test_server_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 85594025c926e20(c926e20) has failed

See https://github.com/ThaliTester/TestResults/tree/85594025c926e20_New_test_server_for_super_branch_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:LGTM: but per the email I sent out please make sure to respond to the NB comments explaining how you handled them. Thanks!

---

Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[test/TestServer/package.json, line 14 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRuZFajUnmvUk-tyZi_:-KRuZFakHkHuL0TdFhUR:bsyzuez) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/TestServer/package.json#L14)):*
> ```JSON
>     "node-uuid": "1.4.7"
>   },
>   "devDependencies": {
> ```

NB: How do we even have dev dependencies at this point? Don't we need everything to run the test server? In other words who would install the test server with "--production"? And what would we expect to happen?

---

*[test/TestServer/TestFramework.js, line 33 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRud4yGIRqkFJjqUnA4:-KRud4yGIRqkFJjqUnA5:bouz8h9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/TestServer/TestFramework.js#L33)):*
> ```JavaScript
>     asserts.isNumber(minCount);
> 
>     if (count && count > 0) {
> ```

NB: If count doesn't exist then shouldn't asserts.isNumber(count) above fail?

---

*[test/TestServer/TestFramework.js, line 51 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRudOF9vOBJEfDaEzxb:-KRudOF9vOBJEfDaEzxc:bycw7t) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/TestServer/TestFramework.js#L51)):*
> ```JavaScript
>   created: 'created',
>   started: 'started',
>   succeed: 'succeed',
> ```

NB: Technically this should be succeeded not succeed

---

*[test/TestServer/config/Socket.js, line 5 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRuYdDjP_XSXs24xAwF:-KRuYdDjP_XSXs24xAwG:b-6oqnwa) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/TestServer/config/Socket.js#L5)):*
> ```JavaScript
> module.exports = {
>   retryCount:   120,
>   retryTimeout: 3 * 1000
> ```

NB: Doesn't this mean the total timeout is 6 minutes? For a single socket? Doesn't that seem a bit extreme?

---

*[test/TestServer/config/UnitTest.js, line 7 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRuUM2-26Inw3QsW4w-:-KRuUM2-26Inw3QsW4w0:bcjrk4w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/TestServer/config/UnitTest.js#L7)):*
> ```JavaScript
> module.exports = {
>   devices: {
>     ios: 3,
> ```

NB: We used to have a feature where if we set the device count to -1 then this meant "Take as many devices as you can but (per the next section) make sure we have AT LEAST minDevices". Looking at the code I think we lost that feature. So I'm opening an issue because I think we should put it back. https://github.com/thaliproject/Thali_CordovaPlugin/issues/1075

---

*[test/TestServer/utils/logger.js, line 1 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRuTdJ1rVmQaNbzRHOQ:-KRuTdJ2URLIweR49zB5:b3w5ozi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/TestServer/utils/logger.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

NB: If the object is called ThaliLogger then shouldn't the file also be called ThaliLogger.js?

---

*[test/www/jxcore/meta_tests/disabled/testUnitTestFramework.js, line 18 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRpK0AVwNlSV4ZO38pE:-KRpK0AW7pZvSAN2tK5y:b-q1aodd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/www/jxcore/meta_tests/disabled/testUnitTestFramework.js#L18)):*
> ```JavaScript
> });
> 
> var createTestDevice = function (socket, platform, index) {
> ```

NB: How can we disable this test? Don't we desperately need it to validate that the test framework is working correctly? Or do you think testTests.js is sufficient? And if we don't need this test shouldn't we delete the file? Or is the plan to work on this file later?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-:-KRus9KYALGPt2aqZq4A:b-fshnzg)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (a312277)

**Comment by ThaliTester** [comment]
Test (Fail) 85594025 build is completed (a312277)

See https://github.com/ThaliTester/TestResults/tree/85594025a312277_New_test_server_for_super_branch_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
Removed `if count`, fixed `succeeded`, `logger -> ThaliLogger`, `promise -> Promise`, added ability to use `count === -1`, fixed disabled test.

TODO we need to create more tests for test server, but we have more important tasks now. We can remove `devDependencies` now.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (88149d6)

**Comment by ThaliTester** [comment]
Test (Success) 85594025 build is completed (88149d6)

See https://github.com/ThaliTester/TestResults/tree/8559402588149d6_New_test_server_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 8559402588149d6(88149d6) has failed

See https://github.com/ThaliTester/TestResults/tree/8559402588149d6_New_test_server_for_super_branch_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
Please respond to the NB's but otherwise :lgtm: 

---

Reviewed 2 of 6 files at r2, 18 of 18 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/TestServer/UnitTestFramework.js, line 33 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KS3BSKu6cT7pEeTR1yH:-KS3BSKu6cT7pEeTR1yI:b-d2rfve) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88149d69044d44803ee700ad4a6fd898353d91f8/test/TestServer/UnitTestFramework.js#L33)):*
> ```JavaScript
>   UnitTestFramework.super_.prototype.startTests.apply(this, arguments);
> 
>   var platform = this.platforms[platformName];
> ```

NB: Shouldn't we check if the platformName we received matches one of the values in platforms? I realize that we will fail anyway when we try for devices[0] but it might be nice to have a cleaner error.

---

*[test/TestServer/test/disabled/testTestServer.js, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KS3C4_-GeLzwkVq2Iis:-KS3C4_0U-7DBQ_jBo6G:byw8z1l) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88149d69044d44803ee700ad4a6fd898353d91f8/test/TestServer/test/disabled/testTestServer.js#L1)):*
> ```JavaScript
> var test = require('tape');
> ```

NB: Why disable versus delete? Do you intend to bring it back? What was wrong with it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-:-KS3CsqejcaFn_fun8tu:b-4ihcvz)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (8c32634)

**Comment by andrew-aladev** [comment]
Review status: 17 of 61 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/TestServer/config/Socket.js, line 5 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRuYdDjP_XSXs24xAwF:-KS7fRqJbwhnm4BxYmI8:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/TestServer/config/Socket.js#L5)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Doesn't this mean the total timeout is 6 minutes? For a single socket? Doesn't that seem a bit extreme?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061)*

**Comment by andrew-aladev** [comment]
Review status: 17 of 61 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/meta_tests/testUnitTestFramework.js, line 18 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KRpK0AVwNlSV4ZO38pE:-KS7fbGw21FMGm4ZGlCz:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c926e20c56a698fb57ee6c50bea4e23ee5f8faf8/test/www/jxcore/meta_tests/testUnitTestFramework.js#L18)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: How can we disable this test? Don't we desperately need it to validate that the test framework is working correctly? Or do you think testTests.js is sufficient? And if we don't need this test shouldn't we delete the file? Or is the plan to work on this file later?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061)*

**Comment by andrew-aladev** [comment]
Review status: 17 of 61 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/TestServer/UnitTestFramework.js, line 33 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KS3BSKu6cT7pEeTR1yH:-KS7fdBT0VkLnfIO7OHg:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88149d69044d44803ee700ad4a6fd898353d91f8/test/TestServer/UnitTestFramework.js#L33)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Shouldn't we check if the platformName we received matches one of the values in platforms? I realize that we will fail anyway when we try for devices[0] but it might be nice to have a cleaner error.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061)*

**Comment by andrew-aladev** [comment]
Review status: 17 of 61 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/TestServer/test/disabled/testTestServer.js, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061#-KS3C4_-GeLzwkVq2Iis:-KS7fhmUZzdOnwI4Vd1C:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88149d69044d44803ee700ad4a6fd898353d91f8/test/TestServer/test/disabled/testTestServer.js#L1)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Why disable versus delete? Do you intend to bring it back? What was wrong with it?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1061)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (97fb9a8)

**Comment by ThaliTester** [comment]
Test (Success) 85594025 build is completed (8c32634)

See https://github.com/ThaliTester/TestResults/tree/855940258c32634_New_test_server_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 85594025 build is completed (97fb9a8)

See https://github.com/ThaliTester/TestResults/tree/8559402597fb9a8_New_test_server_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 855940258c32634(8c32634) has failed

See https://github.com/ThaliTester/TestResults/tree/855940258c32634_New_test_server_for_super_branch_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test 8559402597fb9a8(97fb9a8) has failed

See https://github.com/ThaliTester/TestResults/tree/8559402597fb9a8_New_test_server_for_super_branch_andrew-aladev/ for the fail logs

**Pull request merged**
