### PR TITLE
PouchDB has been updated to the latest version

### LINKED ISSUE #1644: Test us with the latest version of PouchDB
Since we have to fix a bug in PouchDB it means we have to move to the latest PouchDB so please replace PouchDB in our test project.json and see what happens.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1644.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1666)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f015f80)

**Comment by ThaliTester** [comment]
Test 98792387 (f015f80) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 98792387 build is completed (f015f80)

See https://github.com/ThaliTester/TestResults/tree/98792387f015f80_PouchDB_has_been_updated_to_the_latest_version_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/installCustomPouchDB.js, line 164 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZSzey2Bh8ixP0OrVgb:-KZSzey2Bh8ixP0OrVgc:b-qmsxga) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f015f80f85980a5cf66e22cbf6626cf84537023a/test/www/jxcore/installCustomPouchDB.js#L164)):*
> ```JavaScript
>   var targetDir = 'customPouchDir';
> 
>   var customPouchDirPath = path.join(__dirname, targetDir);
> ```

Last we checked you said this didn't work. Does it work now? I'm guessing not because I see that our code to build our own custom version of PouchDB is still disabled. But in that case why replace the existing code in this function at all?

---

*[test/www/jxcore/package.json, line 27 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZSw_2Okq5RLDbQHoqp:-KZSw_2PgBLcoNILrbEs:b-rs2auz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f015f80f85980a5cf66e22cbf6626cf84537023a/test/www/jxcore/package.json#L27)):*
> ```JSON
>     "concat-map": "0.0.1",
>     "express": "4.13.3",
>     "express-pouchdb": "2.1.1",
> ```

We depend on a fix in https://github.com/yaronyg/pouchdb-server/commits/thali-release that handles express-pouchdb's bad behavior in some situations, specifically https://github.com/yaronyg/pouchdb-server/commit/a012907ef1c1ed624ce3eaadcbc515b3aa033e4d. Did this get fixed? Because if not then we really need to use our custom release of express-pouchdb. And if it is fixed then we should completely disable installCustomPouchDB.js.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 43 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZSuK41lUdb4098TSC7:-KZSuK42f9ZTx0JJWYpw:b-7tgkuf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f015f80f85980a5cf66e22cbf6626cf84537023a/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L43)):*
> ```JavaScript
>     events.on('error', function (error) {
>       logger.error('Error while fetching db changes: \'%s\', stack: \'%s\'', String(error), error.stack);
>       events.cancel();
> ```

This worries me a lot. If we do get an error then we essentially disable checkpoint capability all together. Don't we at least need  to call the handlers and tell then that things have gone bad?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d04bf58)

**Comment by ThaliTester** [comment]
Test 98792387 (d04bf58) build started.

**Comment by andrew-aladev** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/installCustomPouchDB.js, line 164 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZSzey2Bh8ixP0OrVgb:-KZVkNE5BCCy8bXgS4xN:b-h3d69v) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f015f80f85980a5cf66e22cbf6626cf84537023a/test/www/jxcore/installCustomPouchDB.js#L164)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Last we checked you said this didn't work. Does it work now? I'm guessing not because I see that our code to build our own custom version of PouchDB is still disabled. But in that case why replace the existing code in this function at all?
</blockquote></details>

Yes, It works fine with "npm run set-version -- 6.2.0-prerelease && npm run release". The last command will publish all pouchdb packages into sinopia.

---

*[test/www/jxcore/package.json, line 27 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZSw_2Okq5RLDbQHoqp:-KZVwBiMBH7mIlCr7oib:b-mzhoqa) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f015f80f85980a5cf66e22cbf6626cf84537023a/test/www/jxcore/package.json#L27)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

We depend on a fix in https://github.com/yaronyg/pouchdb-server/commits/thali-release that handles express-pouchdb's bad behavior in some situations, specifically https://github.com/yaronyg/pouchdb-server/commit/a012907ef1c1ed624ce3eaadcbc515b3aa033e4d. Did this get fixed? Because if not then we really need to use our custom release of express-pouchdb. And if it is fixed then we should completely disable installCustomPouchDB.js.
</blockquote></details>

Reverted 1.0.6-thali.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 43 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZSuK41lUdb4098TSC7:-KZWAH1TBa0FK-Lyduuh:btkb7dd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f015f80f85980a5cf66e22cbf6626cf84537023a/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L43)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

This worries me a lot. If we do get an error then we essentially disable checkpoint capability all together. Don't we at least need  to call the handlers and tell then that things have gone bad?
</blockquote></details>

I've added a `db.emit('error', error)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666)*

**Comment by ThaliTester** [comment]
Test (Fail) 98792387 build is completed (d04bf58)

See https://github.com/ThaliTester/TestResults/tree/98792387d04bf58_PouchDB_has_been_updated_to_the_latest_version_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (68556af)

**Comment by ThaliTester** [comment]
Test 98792387 (68556af) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 98792387 build is completed (68556af)

See https://github.com/ThaliTester/TestResults/tree/9879238768556af_PouchDB_has_been_updated_to_the_latest_version_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
Please resolve comments and then :lgtm: 

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 115 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZXUCqn_PC-0ac25uCM:-KZXUCqn_PC-0ac25uCN:bjvkmyq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L115)):*
> ```JavaScript
> }
> 
> var executeAsync = function (fn) {
> ```

If memory serves Chapko introduced a function just like this, can you please coordinate with him and call his version so we only have to have this code once?

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 119 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZXURYyUNTd6RqwwfFx:-KZXURYyUNTd6RqwwfFy:b-nkerc8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L119)):*
> ```JavaScript
>     var self = this;
>     var args = arguments;
>     process.nextTick(function () {
> ```

Wouldn't it be a lot more friendly to use setImmediate here? Otherwise what is the point of executeAsync if we are using nextTick? With nextTick we literally aren't doing anything async.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-:-KZXUjThnnE83aqNeUgT:bamy0m9)*

**Comment by chapko** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/package.json, line 23 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZaJb4NiCUeuUOuyrmp:-KZaJb4NiCUeuUOuyrmq:b-v7ak3e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/package.json#L23)):*
> ```JSON
>     "uuid": "2.0.2",
>     "winston": "2.2.0",
>     "js-extend": "1.0.1"
> ```

Do we still need both js-extend and object-assign? If I remember correctly we have used js-extend only in `PouchDBGenerator`

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 94 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZamZunBs1rgbx4sYB_:-KZamZup1wIpE94Wjzyp:b-vxu3za) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L94)):*
> ```JavaScript
>   // Public methods
>   CheckpointPlugin.prototype.registerHandler = function (handler) {
>     handlers.push(handler);
> ```

We can make this handler asynchronous once here and just call it directly later

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 115 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZXUCqn_PC-0ac25uCM:-KZaK-dXkJKG2PKvEt2i:b640pn1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L115)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

If memory serves Chapko introduced a function just like this, can you please coordinate with him and call his version so we only have to have this code once?
</blockquote></details>

Yes, I added similar function in #1664 PR in utils/common.js but it uses `setImmediate`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666)*

**Comment by andrew-aladev** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/package.json, line 23 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZaJb4NiCUeuUOuyrmp:-KZfsLZw1FnSLxQ0RpIl:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/package.json#L23)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

Do we still need both js-extend and object-assign? If I remember correctly we have used js-extend only in `PouchDBGenerator`
</blockquote></details>

Done.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 94 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZamZunBs1rgbx4sYB_:-KZfsRyZJZmq8x3Z8XaS:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L94)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

We can make this handler asynchronous once here and just call it directly later
</blockquote></details>

Done.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 115 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZXUCqn_PC-0ac25uCM:-KZfsTCNk9b82eMEjlky:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L115)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

Yes, I added similar function in #1664 PR in utils/common.js but it uses `setImmediate`
</blockquote></details>

Done.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 119 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-KZXURYyUNTd6RqwwfFx:-KZfsWTBzmJ6zsAEl4NJ:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68556aff980a441a207ce609d4bd01e9a13f4aef/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L119)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Wouldn't it be a lot more friendly to use setImmediate here? Otherwise what is the point of executeAsync if we are using nextTick? With nextTick we literally aren't doing anything async.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666)*

**Comment by chapko** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1666#-:-KZg-RuzhbYSYkRQ5fns:bnfp4nl)*

**Pull request merged**
