### PR TITLE
commented some native tests

### PR DESCRIPTION
**Pull request by vasilevskayaem**
commented IncomingSocketThreadTest and OutgoingSocketThreadTest

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1252)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fee2d0a)

**Comment by ThaliTester** [comment]
Test (Fail) 88057024 build is completed (fee2d0a)

See https://github.com/ThaliTester/TestResults/tree/88057024fee2d0a_commented_some_native_tests_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aec0907)

**Comment by ThaliTester** [comment]
Test (Success) 88057024 build is completed (aec0907)

See https://github.com/ThaliTester/TestResults/tree/88057024aec0907_commented_some_native_tests_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 88057024aec0907(aec0907) has failed

See https://github.com/ThaliTester/TestResults/tree/88057024aec0907_commented_some_native_tests_vasilevskayaem/ for the fail logs

**Comment by larryonoff** [comment]
this PR is outdated

**Pull request closed without merging**
