### PR TITLE
#777 Additional native unit tests

### PR DESCRIPTION
**Pull request by mlesnic**
PR that implements #777

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/850)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7027f2d)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (7027f2d)

See https://github.com/ThaliTester/TestResults/tree/807613747027f2d__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 807613747027f2d(7027f2d) has failed

See https://github.com/ThaliTester/TestResults/tree/807613747027f2d__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5de8823)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (5de8823)

See https://github.com/ThaliTester/TestResults/tree/807613745de8823__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 807613745de8823(5de8823) has failed

See https://github.com/ThaliTester/TestResults/tree/807613745de8823__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0d32244)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (0d32244)

See https://github.com/ThaliTester/TestResults/tree/807613740d32244__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 807613740d32244(0d32244) has failed

See https://github.com/ThaliTester/TestResults/tree/807613740d32244__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (2dabe25)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (2dabe25)

See https://github.com/ThaliTester/TestResults/tree/807613742dabe25__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 807613742dabe25(2dabe25) has failed

See https://github.com/ThaliTester/TestResults/tree/807613742dabe25__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (33f931a)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (33f931a)

See https://github.com/ThaliTester/TestResults/tree/8076137433f931a__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 8076137433f931a(33f931a) has failed

See https://github.com/ThaliTester/TestResults/tree/8076137433f931a__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e9ed5ae)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (e9ed5ae)

See https://github.com/ThaliTester/TestResults/tree/80761374e9ed5ae__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 80761374e9ed5ae(e9ed5ae) has failed

See https://github.com/ThaliTester/TestResults/tree/80761374e9ed5ae__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f9c4447)

**Comment by ThaliTester** [comment]
Test (Fail) 80761374 build is completed (f9c4447)

See https://github.com/ThaliTester/TestResults/tree/80761374f9c4447__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (50b0c73)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (50b0c73)

See https://github.com/ThaliTester/TestResults/tree/8076137450b0c73__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 8076137450b0c73(50b0c73) has failed

See https://github.com/ThaliTester/TestResults/tree/8076137450b0c73__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (304f7b9)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (304f7b9)

See https://github.com/ThaliTester/TestResults/tree/80761374304f7b9__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 80761374304f7b9(304f7b9) has failed

See https://github.com/ThaliTester/TestResults/tree/80761374304f7b9__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7a577d4)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (7a577d4)

See https://github.com/ThaliTester/TestResults/tree/807613747a577d4__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 807613747a577d4(7a577d4) has failed

See https://github.com/ThaliTester/TestResults/tree/807613747a577d4__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (bf0e3f7)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (bf0e3f7)

See https://github.com/ThaliTester/TestResults/tree/80761374bf0e3f7__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 80761374bf0e3f7(bf0e3f7) has failed

See https://github.com/ThaliTester/TestResults/tree/80761374bf0e3f7__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0d5db28)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (0d5db28)

See https://github.com/ThaliTester/TestResults/tree/807613740d5db28__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 807613740d5db28(0d5db28) has failed

See https://github.com/ThaliTester/TestResults/tree/807613740d5db28__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e4349a7)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (e4349a7)

See https://github.com/ThaliTester/TestResults/tree/80761374e4349a7__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 80761374e4349a7(e4349a7) has failed

See https://github.com/ThaliTester/TestResults/tree/80761374e4349a7__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ecfdb04)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (ecfdb04)

See https://github.com/ThaliTester/TestResults/tree/80761374ecfdb04__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 80761374ecfdb04(ecfdb04) has failed

See https://github.com/ThaliTester/TestResults/tree/80761374ecfdb04__777_Additional_native_unit_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (059c81f)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (059c81f)

See https://github.com/ThaliTester/TestResults/tree/80761374059c81f__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 80761374059c81f(059c81f) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/80761374059c81f__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9c91828)

**Comment by ThaliTester** [comment]
Test (Success) 80761374 build is completed (9c91828)

See https://github.com/ThaliTester/TestResults/tree/807613749c91828__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 807613749c91828(9c91828) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/807613749c91828__777_Additional_native_unit_tests_mlesnic/ for the logs

**Comment by yaronyg** [comment]
My top level concern with this PR is that it uses magic thread.sleep() wait times all over the place. That isn't safe. As you already experienced when you had to increase some wait times. There is nothing magical about a wait time. Something that usually takes 2 seconds can sometimes take 4 and then the tests fail for no obvious reason. Unreliable tests are useless because devs quickly learn to ignore them.

So every thread.sleep needs to be replaced with a production quality test check. That would be one where we actually check for the condition we are waiting for and only if it isn't there yet do we go for a very short sleep (no more than 200ms) and check again. So if we are waiting for a thread to start then use a semaphore (which still needs some kind of timer on it so that if there is a bug we don't wait forever and will error out). If we are waiting for a class to be created or destroyed then write a test to confirms if the class is created or destroyed and if it isn't yet then go to a short wait. And yes again we should check how many short waits we have had and if they exceed some limit then we need to error out.

But magic wait times are just not workable.

---

Reviewed 6 of 12 files at r1, 1 of 1 files at r2, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[src/android/test/com/test/thalitest/RegisterExecuteUT.java, line 30 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQXz30ydzgWMFfghd5_:-KQXz30ydzgWMFfghd5a:bu6pz23) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/com/test/thalitest/RegisterExecuteUT.java#L30)):*
> ```Java
>         ConnectionHelperTest.mConnectionHelper = new ConnectionHelper();
>         try {
>                 if(methodName.equals("onPeerLost")){
> ```

Isn't this what Switch was invented for? And please have a default so we can have some reasonable error if we get a call for a method we don't support.

---

*[src/android/test/com/test/thalitest/RegisterExecuteUT.java, line 31 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQXzJeCHX9kolfgGMnd:-KQXzJeCHX9kolfgGMne:b-3gej8u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/com/test/thalitest/RegisterExecuteUT.java#L31)):*
> ```Java
>         try {
>                 if(methodName.equals("onPeerLost")){
>                     Method onPeerLostMethod = ConnectionHelperTest.mConnectionHelper.getClass().getMethod(methodName, PeerProperties.class);
> ```

If we are going to play reflection games then why have the 'if' test at all? Why not just use reflection directly to get the method and if it doesn't show up then throw an error?

Otherwise I would suggest that if we are going to use a switch then we can just call the method properly, e.g. ConnectionHelperTest.mConnectionHelper.onPeerLost.

---

*[src/android/test/com/test/thalitest/RegisterExecuteUT.java, line 61 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQXzvbGF9CX7KGCO2f0:-KQXzvbGF9CX7KGCO2f1:bfnzns5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/com/test/thalitest/RegisterExecuteUT.java#L61)):*
> ```Java
> 
>                 try {
>                     Thread.sleep(2000);
> ```

What is the purpose of this delay?

---

*[src/android/test/com/test/thalitest/RegisterExecuteUT.java, line 96 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY-gGlEwyiQmQnfQdK:-KQY-gGlEwyiQmQnfQdL:b-toxm2x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/com/test/thalitest/RegisterExecuteUT.java#L96)):*
> ```Java
>                 try {
>                     if(!failures.equals("")){
>                         jsonObject.put("failures", failures);
> ```

This worries me as the failure string could potentially be quite large and I'm not sure what JXcore would do if we passed anything too big. Is there any reason we can't just return the failure data in the Android logs?

---

*[src/android/test/io/jxcore/node/ConnectionHelperTest.java, line 108 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY-vXLALPIJDFqDvJq:-KQY-vXLALPIJDFqDvJr:b-4e8bno) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/io/jxcore/node/ConnectionHelperTest.java#L108)):*
> ```Java
>     public void testDispose() throws Exception {
>         mConnectionHelper.dispose();
>         Thread.sleep(5000); //Wait for connectionHelper to dispose
> ```

Please see my comments above about waits.

---

*[src/android/test/io/jxcore/node/ConnectivityMonitorTest.java, line 65 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY0kiMCk629tt1qysj:-KQY0kiNSmPs7hTpEjcg:be6jh7d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/io/jxcore/node/ConnectivityMonitorTest.java#L65)):*
> ```Java
>             public void run() {
>                 try {
>                     Thread.sleep(5000);
> ```

Please see previous comment. No magical time outs. Whatever you are waiting for needs to be a 'busy' wait where you are checking some condition to see if it has been achieved and if not then going to sleep. But these kind of random time outs just guarantee unstable tests that will randomly fail for no apparent reason.

---

*[src/android/test/io/jxcore/node/ConnectivityMonitorTest.java, line 121 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY0vp6ZnD1CAMGYwn-:-KQY0vp7wisbMWvWAmaf:b97cnq4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/io/jxcore/node/ConnectivityMonitorTest.java#L121)):*
> ```Java
>         // Start monitoring connectivity, Wi-Fi and Bluetooth state changes.
>         mConnectivityMonitor.start();
>         Thread.sleep(5000);
> ```

Insert comment about not using Thread.sleep like this. And the fact that you had to increase the wait should tell you something.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 110 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY3iqHcyowse78sLMo:-KQY3iqHcyowse78sLMp:b-djly1r) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L110)):*
> ```Java
> 
>         mOutgoingSocketThread.start(); //Simulate end point to connect to
>         Thread.sleep(3000); //Wait for thread to start
> ```

Please just use a semaphore, not magical wait times.

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java, line 55 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY4pQ5QsxeCjlZpOan:-KQY4pQ6rm_C-gli-0N1:bq9fuih) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java#L55)):*
> ```Java
>         }
> 
>         if (mServerSocket != null) {
> ```

If mServerSocket is null don't we need to throw? I realize it should have been caught above but if this test fails then it wasn't.

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 13 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY5oILI3btmjhUxn8_:-KQY5oIMo15xQ-DHDuZF:b32v14s) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/test/www/jxcore/bv_tests/testNativeMethod.js#L13)):*
> ```JavaScript
>         setup: function (t) {
>             Mobile('peerAvailabilityChanged').registerToNative(function (peers) {
>                 if (typeof peers.forEach !== 'function') {
> ```

Peers is required to be an array. If you aren't getting an array that is a test failure.

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 20 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY65ERZ6ndq12c52tA:-KQY65ERZ6ndq12c52tB:bqgi3xv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/test/www/jxcore/bv_tests/testNativeMethod.js#L20)):*
> ```JavaScript
>                 });
>             });
>         t.end();
> ```

Please indent this line

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 33 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY6FG9jW8Hk8392ILy:-KQY6FG9jW8Hk8392ILz:b-ppui6e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/test/www/jxcore/bv_tests/testNativeMethod.js#L33)):*
> ```JavaScript
>                 console.log(result.Testing_);
>                 setImmediate(function () {
>                     t.equal(callbackPeer.peerIdentifier, '11:22:33:22:11:00-0',
> ```

Isn't this code depending on the peerAvailabilityChanged event happening before the setImmediate. Which is usually a good bet but not a 100% guaranteed one. The safe way to do this is take the registerToNative call out of setup and instead put it into the test. Then put this check into the callback function registered with registerToNative. You also need to put in a timer somewhere so that if there is a bug and the callback never happens the test will fail. But if the callback happens then the timer needs to be cancelled. This is a trivial use of setTimeout.

This comments applies to the next test too.

---

*[thali/package.json, line 33 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY6s5a_TsY4TU0bXXH:-KQY6s5bHz_NNIz5caJC:bzdew6j) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/thali/package.json#L33)):*
> ```JSON
>     "btconnectorlib2": "0.3.2",
>     "jxcore-cordova": "0.1.2b",
>     "jxcore-cordova-url": "https://jxcore.blob.core.windows.net/jxcore-release/jxcore-cordova/0.1.2b/release/io.jxcore.node.jx"
> ```

It doesn't really matter anymore since we have already fixed this but for future reference this URL points directly to storage rather than to the CDN. But we want to use the CDN because it has better availability. So please use jxcore.azureedge.net and not jxcore.blob.core.windows.net. This is just a FYI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-:-KOq0NIqu2b95nv9wIhS:b-vvli7o)*

**Comment by mlesnic** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[src/android/test/com/test/thalitest/RegisterExecuteUT.java, line 61 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQXzvbGF9CX7KGCO2f0:-KQ_VK_Yd2fb9NENg6vz:bss4a2b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/com/test/thalitest/RegisterExecuteUT.java#L61)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> What is the purpose of this delay?
</details>
Removed.

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java, line 55 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY4pQ5QsxeCjlZpOan:-KQZdbTFb6k399e1R7AO:ba9e4j2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java#L55)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> If mServerSocket is null don't we need to throw? I realize it should have been caught above but if this test fails then it wasn't.
</details>
This implementation is copied from the original OutgoingSocketThread class, so I assume it is proper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java, line 55 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850#-KQY4pQ5QsxeCjlZpOan:-KR-jZNy73PkpBtojxrW:b6fss2e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9c91828358cada6cadfca14a9ca8625a14a7ea02/src/android/test/io/jxcore/node/OutgoingSocketThreadMock.java#L55)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary>
> This implementation is copied from the original OutgoingSocketThread class, so I assume it is proper.
</details>
Nope, not a safe bet. We all know that the Android code has a lot of problems. So you can't ever just assume that something is o.k. because it was in the original code. You have to make sure you understand what it is doing and why.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/850)*

**Pull request merged**
