### PR TITLE
Implement incomingConnectionToPortNumberFailed native event.

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1534)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a169e88)

**Comment by ThaliTester** [comment]
Test (Success) 93986313 build is completed (a169e88)

See https://github.com/ThaliTester/TestResults/tree/93986313a169e88_Implement_incomingConnectionToPortNumberFailed_native_event__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 93986313a169e88(a169e88) has failed

See https://github.com/ThaliTester/TestResults/tree/93986313a169e88_Implement_incomingConnectionToPortNumberFailed_native_event__dersim-davaod/ for the fail logs

**Comment by evabishchevich** [comment]
@dersim-davaod What do we need to have this PR merged?

**Pull request closed without merging**
