### PR TITLE
#1167 Fixed ThaliMobile network type to use global network type if presented

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1176)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (90583c6)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (9c44d97)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (be52ee4)

**Comment by ThaliTester** [comment]
Test (Success) 86877966 build is completed (90583c6)

See https://github.com/ThaliTester/TestResults/tree/8687796690583c6_Fixed_ThaliMobile_network_type_to_use_global_network_type_if_presented_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 86877966 build is completed (9c44d97)

See https://github.com/ThaliTester/TestResults/tree/868779669c44d97_Fixed_ThaliMobile_network_type_to_use_global_network_type_if_presented_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 86877966 build is completed (be52ee4)

See https://github.com/ThaliTester/TestResults/tree/86877966be52ee4_Fixed_ThaliMobile_network_type_to_use_global_network_type_if_presented_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (6098730)

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[thali/NextGeneration/thaliMobile.js, line 76 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1176#-KSf0tykGROZ2fO75EN8:-KSf0tykGROZ2fO75EN9:bk9u4ly) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/60987305c50b56c3e63face7ec2c303fbe139939/thali/NextGeneration/thaliMobile.js#L76)):*
> ```JavaScript
>       return function() {
>         var args = arguments;
>         return wifiMethod.apply(null, args)
> ```

We can apply just arguments without args variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1176#-:-KSf14J5Qg_JjiMNfgVw:bnfp4nl)*

**Comment by artemjackson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[thali/NextGeneration/thaliMobile.js, line 76 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1176#-KSf0tykGROZ2fO75EN8:-KSf1pR34_21RYASYlKS:b-7o98ws) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/60987305c50b56c3e63face7ec2c303fbe139939/thali/NextGeneration/thaliMobile.js#L76)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary>
> We can apply just arguments without args variable.
</details>
yes, it's just for clarity 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1176)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (99efd68)

**Comment by artemjackson** [comment]
Merged as a hotfix

**Comment by ThaliTester** [comment]
Test (Fail) 86877966 build is completed (6098730)

See https://github.com/ThaliTester/TestResults/tree/868779666098730_Fixed_ThaliMobile_network_type_to_use_global_network_type_if_presented_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8687796690583c6(90583c6) has failed

See https://github.com/ThaliTester/TestResults/tree/8687796690583c6_Fixed_ThaliMobile_network_type_to_use_global_network_type_if_presented_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Fail) 86877966 build is completed (99efd68)

See https://github.com/ThaliTester/TestResults/tree/8687796699efd68__1167_Fixed_ThaliMobile_network_type_to_use_global_network_type_if_presented_artemjackson/ for the logs

**Pull request merged**
