### PR TITLE
Fix for service data issue seen on some devices

### PR DESCRIPTION
**Pull request by tompaana**
* Updated the plug-in to use library version 0.3.0, which has the manufacturer data fallback implemented.
* Removed HandshakeHelper since we now have the simplified handshake built in in the library (used if no peer name set) - one place less where things can go wrong.
* Restored LifeCycleMonitor class (loosely related to issue #642).
* Added check to JXcoreExtension.LoadExtensions to see if it is called twice (loosely related to issue #642).

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/643)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f0d5e10)

**Comment by ThaliTester** [comment]
Test (Success) 63377149 build is completed (f0d5e10)

See https://github.com/ThaliTester/TestResults/tree/63377149f0d5e10_Fix_for_service_data_issue_seen_on_some_devices_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 63377149f0d5e10(f0d5e10) has failed

See https://github.com/ThaliTester/TestResults/tree/63377149f0d5e10_Fix_for_service_data_issue_seen_on_some_devices_tompaana/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/643#-:-KD9SJbBljwbE-8LWOnA:1417088721)*

**Pull request merged**
