### PR TITLE
#896 Android only changes for thaliMobileNativeWrapper

### LINKED ISSUE #896: Android only changes for thaliMobileNativeWrapper
The following are highlights of changes in thaliMobileNativeWrapper that are unique to Android. I suggest you start there first and then fix the related tests so that we can check your changes directly into the mainline code. Of course these changes will involve other bugs (that I'm filing) because when you add getPort that is going to break a bunch of things.

- [x] Implement getPort
- [x] terminateConnection is now a private method, this is going to break tests and such, please update the code. Those tests should now be switched over to disconnect
- [x] Implement the failedNativeConnectionEvent for Android
- [x] Update nonTCPPeerAvailabilityChanged to return peerAvailable and generation as specified in the spec.
- [x] Note that we issue a nonTCPPeerAvailabilityChangedEvent in the code that handles listenerRecreatedAfterFailure but that codes doesn't use the new nonTCPPeerAvailabilityChanged formate specified in the previous work item. We have to put logic here to make sure that we return the same generation as the current one BUT the port MUST be different. We have to be careful of a rare race condition where the new port we get issued could potentially be the same as the old one!

### PR DESCRIPTION
**Pull request by chapko**
Closes #896

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1203)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (41cde1a)

**Comment by ThaliTester** [comment]
Test (Success) 87133026 build is completed (41cde1a)

See https://github.com/ThaliTester/TestResults/tree/8713302641cde1a__896_Android_only_changes_for_thaliMobileNativeWrapper_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 8713302641cde1a(41cde1a) has failed

See https://github.com/ThaliTester/TestResults/tree/8713302641cde1a__896_Android_only_changes_for_thaliMobileNativeWrapper_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1203#-:-KSn2WSfcHWW-a5p6q6P:bnfp4nl)*

**Comment by yaronyg** [comment]
Please switch this to the iOS branch, fix any merge conflicts, make sure it is passing reasonably locally and then submit.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9e2872c)

**Comment by ThaliTester** [comment]
Test (Fail) 87133026 build is completed (9e2872c)

See https://github.com/ThaliTester/TestResults/tree/871330269e2872c__896_Android_only_changes_for_thaliMobileNativeWrapper_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3ce6b97)

**Comment by ThaliTester** [comment]
Test (Fail) 87133026 build is completed (3ce6b97)

See https://github.com/ThaliTester/TestResults/tree/871330263ce6b97__896_Android_only_changes_for_thaliMobileNativeWrapper_chapko/ for the logs

**Pull request merged**
