### PR TITLE
Refactor promiseQueue implementation

### LINKED ISSUE #1044: PromiseQueue can't handle exceptions in enqueued tasks
Example:

```
var pq = new PromiseQueue();
var promise = pq.enqueue(function (resolve, reject) {
  throw new Error('error message');
});
```

`promise` is now stuck in pending state forever. The thrown error is lost in depth of PromiseQueue and can be only catched by the global `unhandledRejection` event.

I think the behavior should be the same as that of a `Promise` constructor (just enter promise into rejected state with the thrown error as a rejection reason).

### PR DESCRIPTION
**Pull request by chapko**
1. Fix unhandled rejections when function passed into enqueue method throws an error.
2. Refactor internal implementation so it create only one promise when someone enqueues new executor. Also it does not build entire promise chain after calling `enqueue` but rather chains next promise right before the next task starts.
3. Tests, of course.

Fixes #1044

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1848)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (925e479)

**Comment by ThaliTester** [comment]
Test 112800850 (925e479) build started.

**Comment by yaronyg** [comment]
Please see comment but otherwise :LGTM:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/promiseQueue.js, line 133 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1848#-KgFwIshe_jTI5pV-Lh5:-KgFwIshe_jTI5pV-Lh6:bwhwsx7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/925e4795c7c823587b4927afd7e12646d2c7e8f9/thali/NextGeneration/promiseQueue.js#L133)):*
> ```JavaScript
>   var task = this._tasks.shift();
>   if (task) {
>     this._activePromise = task.promise.then(this._run, this._run);
> ```

Why do we need _activePromise? We always handle both outcomes from the then so we shouldn't get an unhandled error exception or anything like that, right? Just curious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1848#-:-KgFwsU7zWB4ZoUlohP_:bii6com)*

**Comment by ThaliTester** [comment]
Test (Success) 112800850 build is completed (925e479)

See https://github.com/ThaliTester/TestResults/tree/112800850925e479_Refactor_promiseQueue_implementation_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 112800850925e479(925e479) has failed

See https://github.com/ThaliTester/TestResults/tree/112800850925e479_Refactor_promiseQueue_implementation_chapko/ for the fail logs

**Comment by jareksl** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1848#-:-KgIRzW1gaMo87MEnQgQ:bg7igkv)*

**Comment by jareksl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1848)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f460826)

**Comment by ThaliTester** [comment]
Test 112800850 (f460826) build started.

**Comment by chapko** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/promiseQueue.js, line 133 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1848#-KgFwIshe_jTI5pV-Lh5:-KgJRuLo1qxFPuDgWLm0:bkaonyr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/925e4795c7c823587b4927afd7e12646d2c7e8f9/thali/NextGeneration/promiseQueue.js#L133)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why do we need _activePromise? We always handle both outcomes from the then so we shouldn't get an unhandled error exception or anything like that, right? Just curious.
</blockquote></details>

Actually we don't need it. I just didn't notice that I don't use it anymore. So it can be safely removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1848)*

**Comment by ThaliTester** [comment]
Test (Success) 112800850 build is completed (f460826)

See https://github.com/ThaliTester/TestResults/tree/112800850f460826_Refactor_promiseQueue_implementation_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 112800850f460826(f460826) has failed

See https://github.com/ThaliTester/TestResults/tree/112800850f460826_Refactor_promiseQueue_implementation_chapko/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1848)*

**Pull request merged**
