### PR TITLE
PSK Support

### PR DESCRIPTION
**Pull request by yaronyg**
@vjrantal This PR uses #669 so we should get that reviewed and checked in before you review this one because that way all the changes already covered in that PR will disappear from this one and this review should be much easier.

This adds PSK support.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/670)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4960aa1)

**Comment by ThaliTester** [comment]
Test (Fail) 63980877 build is completed (4960aa1)

See https://github.com/ThaliTester/TestResults/tree/639808774960aa1_PSK_Support_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9baf6b3)

**Comment by ThaliTester** [comment]
Test (Fail) 63980877 build is completed (9baf6b3)

See https://github.com/ThaliTester/TestResults/tree/639808779baf6b3_PSK_Support_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f7420d4)

**Comment by ThaliTester** [comment]
Test (Fail) 63980877 build is completed (f7420d4)

See https://github.com/ThaliTester/TestResults/tree/63980877f7420d4_PSK_Support_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 63980877 build is completed (f7420d4)

See https://github.com/ThaliTester/TestResults/tree/63980877f7420d4_PSK_Support_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3799dbd)

**Comment by ThaliTester** [comment]
Test (Success) 63980877 build is completed (3799dbd)

See https://github.com/ThaliTester/TestResults/tree/639808773799dbd_PSK_Support_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 639808773799dbd(3799dbd) has failed

See https://github.com/ThaliTester/TestResults/tree/639808773799dbd_PSK_Support_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 6 of 14 files at r1, 1 of 1 files at r3, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/670)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7da7b77)

**Comment by ThaliTester** [comment]
Test (Fail) 63980877 build is completed (7da7b77)

See https://github.com/ThaliTester/TestResults/tree/639808777da7b77_PSK_Support_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9d5bfaa)

**Comment by ThaliTester** [comment]
Test (Success) 63980877 build is completed (9d5bfaa)

See https://github.com/ThaliTester/TestResults/tree/639808779d5bfaa_PSK_Support_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 639808779d5bfaa(9d5bfaa) has failed

See https://github.com/ThaliTester/TestResults/tree/639808779d5bfaa_PSK_Support_yaronyg/ for the fail logs

**Comment by juhanak** [comment]
:lgtm:

---

Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/670#-:-KE0rUwbJ6i3C9CWmCfv:1417088721)*

**Comment by juhanak** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/670)*

**Pull request merged**
