### PR TITLE
Switch to Unit Tests

### PR DESCRIPTION
**Pull request by tobybrad**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/393)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1adf945)

**Comment by ThaliTester** [comment]
Test (Fail) 54970261 build is completed (1adf945)

See https://github.com/ThaliTester/TestResults/tree/549702611adf945_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d7d3b81)

**Comment by ThaliTester** [comment]
Test (Fail) 54970261 build is completed (d7d3b81)

See https://github.com/ThaliTester/TestResults/tree/54970261d7d3b81_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c23922d)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (c23922d)

See https://github.com/ThaliTester/TestResults/tree/54970261c23922d_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 54970261c23922d(c23922d) has failed

See https://github.com/ThaliTester/TestResults/tree/54970261c23922d_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7d40def)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (7d40def)

See https://github.com/ThaliTester/TestResults/tree/549702617d40def_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 549702617d40def(7d40def) has failed

See https://github.com/ThaliTester/TestResults/tree/549702617d40def_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (fc259e9)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (fc259e9)

See https://github.com/ThaliTester/TestResults/tree/54970261fc259e9_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 54970261fc259e9(fc259e9) has failed

See https://github.com/ThaliTester/TestResults/tree/54970261fc259e9_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0263d9b)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (0263d9b)

See https://github.com/ThaliTester/TestResults/tree/549702610263d9b_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 549702610263d9b(0263d9b) has failed

See https://github.com/ThaliTester/TestResults/tree/549702610263d9b_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aa56788)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (aa56788)

See https://github.com/ThaliTester/TestResults/tree/54970261aa56788_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 54970261aa56788(aa56788) has failed

See https://github.com/ThaliTester/TestResults/tree/54970261aa56788_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8c0ebdb)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (ac9928f)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (8c0ebdb)

See https://github.com/ThaliTester/TestResults/tree/549702618c0ebdb_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (ac9928f)

See https://github.com/ThaliTester/TestResults/tree/54970261ac9928f_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (e0c50c1)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (e0c50c1)

See https://github.com/ThaliTester/TestResults/tree/54970261e0c50c1_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 549702618c0ebdb(8c0ebdb) has failed

See https://github.com/ThaliTester/TestResults/tree/549702618c0ebdb_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
Test 54970261ac9928f(ac9928f) has failed

See https://github.com/ThaliTester/TestResults/tree/54970261ac9928f_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
Test 54970261e0c50c1(e0c50c1) has failed

See https://github.com/ThaliTester/TestResults/tree/54970261e0c50c1_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (40aeaf4)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d953416)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (40aeaf4)

See https://github.com/ThaliTester/TestResults/tree/5497026140aeaf4_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (d953416)

See https://github.com/ThaliTester/TestResults/tree/54970261d953416_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 5497026140aeaf4(40aeaf4) has failed

See https://github.com/ThaliTester/TestResults/tree/5497026140aeaf4_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
Test 54970261d953416(d953416) has failed

See https://github.com/ThaliTester/TestResults/tree/54970261d953416_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3245198)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (3245198)

See https://github.com/ThaliTester/TestResults/tree/549702613245198_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 549702613245198(3245198) has failed

See https://github.com/ThaliTester/TestResults/tree/549702613245198_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9369e5e)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (9369e5e)

See https://github.com/ThaliTester/TestResults/tree/549702619369e5e_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0b97681)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (0b97681)

See https://github.com/ThaliTester/TestResults/tree/549702610b97681_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 549702619369e5e(9369e5e) has failed

See https://github.com/ThaliTester/TestResults/tree/549702619369e5e_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
Test 549702610b97681(0b97681) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/549702610b97681_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (79923a9)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (86051be)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (79923a9)

See https://github.com/ThaliTester/TestResults/tree/5497026179923a9_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by tobybrad** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/readme.md, line 7 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393#-K7kHq0EFBYxtUH1jsLD:-K7kHq0Ff1YfVIhyOJ4-:698782797) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/86051beed059fd7d51915d5cc894407891910ac5/thali/readme.md#L7)):*
This change was just to force CI the first time round IIRC

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393)*

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (86051be)

See https://github.com/ThaliTester/TestResults/tree/5497026186051be_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by vjrantal** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/TestFramework.js, line 41 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393#-K7kMW8N-rVMl4r0xKbQ:-K7kMW8N-rVMl4r0xKbR:1809132021) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/86051beed059fd7d51915d5cc894407891910ac5/test/TestServer/TestFramework.js#L41)):*
Is the behavior now so that if you omit number of devices or set it to be -1 the end result is the same, i.e., value taken from the arguments given to `index.js`?

I wonder would it make sense to document `userConfig` in the readme? I noticed there is something in the `UnitTestConfg.js` file, but a readme might be a better fit since these are relevant to performance tests as well and there is other documentation of the config file in there (that should be removed or updated since it isn't all accurate anymore after the changes).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393)*

**Comment by ThaliTester** [comment]
Test 5497026179923a9(79923a9) has failed

See https://github.com/ThaliTester/TestResults/tree/5497026179923a9_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
Test 5497026186051be(86051be) has failed

See https://github.com/ThaliTester/TestResults/tree/5497026186051be_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7cfd775)

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (7cfd775)

See https://github.com/ThaliTester/TestResults/tree/549702617cfd775_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by tobybrad** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/TestFramework.js, line 41 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393#-K7kMW8N-rVMl4r0xKbQ:-K7kPa5n4AI83-u-rc5j:-2055945170) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/86051beed059fd7d51915d5cc894407891910ac5/test/TestServer/TestFramework.js#L41)):*
-1 indicates use value from arguments, yes. I'll update the readme.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393)*

**Comment by ThaliTester** [comment]
Test 549702617cfd775(7cfd775) has failed

See https://github.com/ThaliTester/TestResults/tree/549702617cfd775_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7e2936d)

**Comment by tobybrad** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/TestFramework.js, line 41 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393#-K7kMW8N-rVMl4r0xKbQ:-K7l8xOrOM0A7sED9Zi_:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/86051beed059fd7d51915d5cc894407891910ac5/test/TestServer/TestFramework.js#L41)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393)*

**Comment by ThaliTester** [comment]
Test (Success) 54970261 build is completed (7e2936d)

See https://github.com/ThaliTester/TestResults/tree/549702617e2936d_Switch_to_Unit_Tests_tobybrad/ for the logs

**Comment by tobybrad** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/TestFramework.js, line 41 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393#-K7kMW8N-rVMl4r0xKbQ:-K7lG4bc36l_s7ioHONS:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/86051beed059fd7d51915d5cc894407891910ac5/test/TestServer/TestFramework.js#L41)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/393)*

**Comment by ThaliTester** [comment]
Test 549702617e2936d(7e2936d) has failed

See https://github.com/ThaliTester/TestResults/tree/549702617e2936d_Switch_to_Unit_Tests_tobybrad/ for the fail logs

**Pull request merged**
