### PR TITLE
Implement CustomNSError protocol for ThaliTest.AppContextError

### PR DESCRIPTION
**Pull request by asuhodolov**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1841)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cd7538d)

**Comment by ThaliTester** [comment]
Test 112016147 (cd7538d) build started.

**Comment by ThaliTester** [comment]
Test (Success) 112016147 build is completed (cd7538d)

See https://github.com/ThaliTester/TestResults/tree/112016147cd7538d_Implement_CustomNSError_protocol_for_ThaliTest_AppContextError_asuhodolov/ for the logs

**Comment by ThaliTester** [comment]
Test 112016147cd7538d(cd7538d) has failed

See https://github.com/ThaliTester/TestResults/tree/112016147cd7538d_Implement_CustomNSError_protocol_for_ThaliTest_AppContextError_asuhodolov/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e249d1d)

**Comment by ThaliTester** [comment]
Test 112016147 (e249d1d) build started.

**Comment by ThaliTester** [comment]
Test (Success) 112016147 build is completed (e249d1d)

See https://github.com/ThaliTester/TestResults/tree/112016147e249d1d_Implement_CustomNSError_protocol_for_ThaliTest_AppContextError_asuhodolov/ for the logs

**Comment by ThaliTester** [comment]
Test 112016147e249d1d(e249d1d) has failed

See https://github.com/ThaliTester/TestResults/tree/112016147e249d1d_Implement_CustomNSError_protocol_for_ThaliTest_AppContextError_asuhodolov/ for the fail logs

**Comment by drinkius** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1841#-:-Kg-t6mDYWtppiZ5UC1K:bnfp4nl)*

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1841#-:-KgEf6w03B-g759yaxLP:bnfp4nl)*

**Pull request merged**
