### PR TITLE
#902 Updated wifiBasedNativeMock for Android

### LINKED ISSUE #902: Updating wifiBasedNativeMock for Android
These changes should update wifiBasedNativeMock so it will work again with the new Android native infrastructure.

- [x] Update our desktop tests so that they run both unit tests and coordinator tests TWICE, once as Android and once as iOS
- [x] Finally implement the code that honors the platform passed into the constructor for wifiBasedNativeMock so that process.platform is overridden and returns the right value when we are on desktop
- [x] The wifiPeerAvailabilityChanged event we will get from the underlying thaliWifiInfrastructure code is now going to return generation and peerID, we need to be ready for that when we process it.
- [x] Update peerAvailabilityChanged to the new syntax (the previous work item will help)

### PR DESCRIPTION
**Pull request by artemjackson**
Closes #902.

* [x] Update our desktop tests so that they run both unit tests and coordinator tests TWICE, once as Android and once as iOS
  - This item is already implemented by @andrew-aladev and now it's a part of  the `superbranch`.
* [x] Finally implement the code that honors the platform passed into the constructor for wifiBasedNativeMock so that process.platform is overridden and returns the right value when we are on desktop
  - Implemented with help of  `platform` module
* [x] The wifiPeerAvailabilityChanged event we will get from the underlying thaliWifiInfrastructure code is now going to return generation and peerID, we need to be ready for that when we process it.
  - I just added `generation` field, I'll remove `hostname` and `port` in #904 (I think that is a proper place to do it)
* [x] Update peerAvailabilityChanged to the new syntax (the previous work item will help)
  - Updated by adding `generation` field

Regarding to 2-nd item: I think we should have an ability to reset overrided by `wifiBacedNativeMock` platform. E.g. we should provide `wifibasedNativeMock.reset()` to reset the `platform` and btw internal mock state (that could allow avoiding of some bugs that we've already seen before).
 

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1185)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (90a251e)

**Comment by ThaliTester** [comment]
Test (Fail) 86955080 build is completed (90a251e)

See https://github.com/ThaliTester/TestResults/tree/8695508090a251e__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4f70855)

**Comment by ThaliTester** [comment]
Test (Fail) 86955080 build is completed (4f70855)

See https://github.com/ThaliTester/TestResults/tree/869550804f70855__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (64de1f5)

**Comment by ThaliTester** [comment]
Test (Fail) 86955080 build is completed (64de1f5)

See https://github.com/ThaliTester/TestResults/tree/8695508064de1f5__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6bb4544)

**Comment by ThaliTester** [comment]
Test (Success) 86955080 build is completed (6bb4544)

See https://github.com/ThaliTester/TestResults/tree/869550806bb4544__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 869550806bb4544(6bb4544) has failed

See https://github.com/ThaliTester/TestResults/tree/869550806bb4544__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the fail logs

**Comment by chapko** [comment]
Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 32 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkdBBE3jeLFLia_sx7:-KSkdBBE3jeLFLia_sx8:b8qrua9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/testUtils.js#L32)):*
> ```JavaScript
> 
> var doToggle = function (toggleFunction, on) {
>   if (!isRealMobile) {
> ```

It is not the same as `typeof Mobile === 'undefined'`. Toggle functionality available in mock too

---

*[test/www/jxcore/lib/testUtils.js, line 144 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkg4-a4sShhJ6Vj5yo:-KSkg4-a4sShhJ6Vj5yp:b7xm1p4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/testUtils.js#L144)):*
> ```JavaScript
> module.exports.hasRequiredHardware = function () {
>   return new Promise(function (resolve) {
>     if (isRealMobile) {
> ```

It should be `isRealAndroid`, isn't it?

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 35 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkhSSKtCTQ7X97TEVu:-KSkhSSL0YG6Bunyp0SX:b-qf2b61) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/wifiBasedNativeMock.js#L35)):*
> ```JavaScript
>  * @enum {string}
>  */
> var platformChoice = {
> ```

We don't need this enum anymore.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 1003 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkjTsB30Fq6J9k0nAA:-KSkjTsCFktyP2f26jk1:b8v5xnu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/wifiBasedNativeMock.js#L1003)):*
> ```JavaScript
> // jscs:enable maximumLineLength
> function wifiPeerAvailabilityChanged(platform, thaliWifiInfrastructure) {
>   return function (peerIdentifier, generation) {
> ```

I don't see `generation` being used anywhere by callers. The only place this method is called is `test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js:177` and it is invoked with only one argument:

```javascript
if (needManualNotify) {
  Mobile.wifiPeerAvailabilityChanged('foo');
}
```

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 1028 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkgwjGgU8OvgygBSNF:-KSkgwjHGNMPqVtcQV88:bruob0t) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/wifiBasedNativeMock.js#L1028)):*
> ```JavaScript
>  */
> // jscs:enable jsDoc
> function WifiBasedNativeMock(_platform, _router) {
> ```

NB: I wouldn't use underscores here, just rename `platform` argument to `platformName` to avoid collision.

---

*[thali/NextGeneration/utils/platform.js, line 50 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkrTwHTFzSUlLJ4VQ7:-KSkrTwI1JpF8NLak5gd:b-542xpf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/thali/NextGeneration/utils/platform.js#L50)):*
> ```JavaScript
>     },
>     // Returns REAL values based on `process.platform`
>     '_name': {
> ```

Why not just `_realName`, `_isRealMobile`, `_isRealAndroid` and `_isRealIOS`? Currently the difference between `_isMobile` and `isMobile` is not clear without looking at this module implementation. And BTW you have already used `isRealMobile` variable in the code above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ed241b1)

**Comment by artemjackson** [comment]
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 32 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkdBBE3jeLFLia_sx7:-KSku2YeyDLNJSwCpXxR:bqog80t) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/testUtils.js#L32)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> It is not the same as `typeof Mobile === 'undefined'`. Toggle functionality available in mock too
</details>
Agreed

---

*[test/www/jxcore/lib/testUtils.js, line 144 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkg4-a4sShhJ6Vj5yo:-KSkuKbu2plDqHnhHskw:bqog80t) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/testUtils.js#L144)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> It should be `isRealAndroid`, isn't it?
</details>
Agreed

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 35 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkhSSKtCTQ7X97TEVu:-KSkuNO5b7aiaENnWTuw:b-81la7d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/wifiBasedNativeMock.js#L35)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> We don't need this enum anymore.
</details>
Right

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 1003 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkjTsB30Fq6J9k0nAA:-KSkuUjXpemOJVHG1-dk:b-o5wig2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/wifiBasedNativeMock.js#L1003)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> I don't see `generation` being used anywhere by callers. The only place this method is called is `test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js:177` and it is invoked with only one argument:
> 
> ```javascript
> if (needManualNotify) {
>   Mobile.wifiPeerAvailabilityChanged('foo');
> }
> ```
</details>
`generation` is added for future compatibility.
`testThaliMobileNativeWrapper.js:177` is not updated according to the `wifiPeerAvailabilityChanged` syntax in order not to break something in tests.

---

*[test/www/jxcore/lib/wifiBasedNativeMock.js, line 1028 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkgwjGgU8OvgygBSNF:-KSkvVpR69SfVFj99Zhq:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/test/www/jxcore/lib/wifiBasedNativeMock.js#L1028)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> NB: I wouldn't use underscores here, just rename `platform` argument to `platformName` to avoid collision.
</details>
Fixed

---

*[thali/NextGeneration/utils/platform.js, line 50 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-KSkrTwHTFzSUlLJ4VQ7:-KSkw25s9NCRx42bZQUW:b-ahcufz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb4544115d6b5b1096665be214c3a30443bf57d/thali/NextGeneration/utils/platform.js#L50)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> Why not just `_realName`, `_isRealMobile`, `_isRealAndroid` and `_isRealIOS`? Currently the difference between `_isMobile` and `isMobile` is not clear without looking at this module implementation. And BTW you have already used `isRealMobile` variable in the code above.
</details>
Make sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (a9104ac)

**Comment by ThaliTester** [comment]
Test (Success) 86955080 build is completed (ed241b1)

See https://github.com/ThaliTester/TestResults/tree/86955080ed241b1__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86955080ed241b1(ed241b1) has failed

See https://github.com/ThaliTester/TestResults/tree/86955080ed241b1__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86955080 build is completed (a9104ac)

See https://github.com/ThaliTester/TestResults/tree/86955080a9104ac__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86955080a9104ac(a9104ac) has failed

See https://github.com/ThaliTester/TestResults/tree/86955080a9104ac__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b1627bd)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ce5f438)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (36ab4dd)

**Comment by ThaliTester** [comment]
Test (Fail) 86955080 build is completed (ce5f438)

See https://github.com/ThaliTester/TestResults/tree/86955080ce5f438__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86955080b1627bd(b1627bd) has failed

See https://github.com/ThaliTester/TestResults/tree/86955080b1627bd__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the fail logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r5, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1185#-:-KSpA9hEi0yhDL4JwZ6h:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 86955080 build is completed (36ab4dd)

See https://github.com/ThaliTester/TestResults/tree/8695508036ab4dd__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8695508036ab4dd(36ab4dd) has failed

See https://github.com/ThaliTester/TestResults/tree/8695508036ab4dd__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the fail logs

**Pull request merged**
