### PR TITLE
Implement thaliMobile

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/583)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 210 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBeu-1ZioF9-E9HFpng:-KBeu-1ZioF9-E9HFpnh:1435534703) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/test/www/jxcore/bv_tests/testThaliMobile.js#L210)):*
NB: Nice way, btw, of using spies as a built in counter.

---

*[thali/NextGeneration/thaliMobile.js, line 156 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBev5-sWef4g9e2lV2t:-KBev5-sWef4g9e2lV2u:-1474402617) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L156)):*
Does it seem at all odd that if someone calls start and both thaliWifiInfrastructure and thaliMobileNativeWrapper return an error that we are still in thaliMobielStates.started = true? Of course if even one is true then we do return true. So maybe it makes sense. Not sure.

---

*[thali/NextGeneration/thaliMobile.js, line 593 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBVWanrveo56sLu4QIj:-KBVWanrveo56sLu4QIk:-174125283) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L593)):*
Why do you stringify and then parse it? Shouldn't that be a noop?

---

*[thali/NextGeneration/thaliMobile.js, line 680 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBejuzhT0igyufzSjRy:-KBejuzhT0igyufzSjRz:-1896942475) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L680)):*
NB:
var unavailabilityThreshold = connectionType === connectionTypes.TCP_NATIVE ? ThaliConfig.TCP_PEER_UNAVAILABILITY_THRESHOLD : ThaliConfig.NON_TCP_PEER_UNAVAILABILITY_THRESHOLD;

---

*[thali/NextGeneration/thaliMobile.js, line 694 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBekKj1KbXeB66lTNZ0:-KBekKj1KbXeB66lTNZ1:-144533759) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L694)):*
Let's imagine this is a non-tcp peer and let's further imagine that it hasn't gotten an update in awhile and thaliMobile decides to declare it not present. What is thaliMobileNativeWrapper doing? In other words when thaliMobileNativeWrapper sent up the peerAvailability event it sent along with it a port number it was listening on for connections to that peer. If thaliMobile has decided that the peer is no available then nobody is going to call that port (at least not unless another peer availability event shows up). So do we just let thaliMobileNativeWrapper sit on that port waiting for a connection that will never come? Does thaliMobileNativeWrapper have its own separate logic for when the peer won't be available and when it will clean things up? Certainly the native layer has its own logic on these things. Are we depending on that native layer to eventually send up a peerAvailability event saying the peer isn't available? Who is going to make sure that the port is closed?

---

*[thali/NextGeneration/thaliMobile.js, line 734 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBelxKEj9Ihf6vp6E-H:-KBelxKFG2wJU9iB6qAq:1287376147) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L734)):*
Is this just for debugging purposes or is it supposed to do something?

---

*[thali/NextGeneration/thaliMobile.js, line 859 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBemWmRXD5eCuKM4wTb:-KBemWmRXD5eCuKM4wTc:233392871) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L859)):*
What this error really means is that tcpServersManager set up a mux listener and sent it to the native layer and the native layer tried to connect to it and the connection failed. So the question becomes - when and how could that happen? And what, if anything, should we (or anyone else) do about it?

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 125 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBVTbpmRdrbqMarR0sc:-KBVTbpmRdrbqMarR0sd:1304297120) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliWifiInfrastructure.js#L125)):*
Why is there a comma after true? Shouldn't it be || and the next two are supposed to be together in one expression with an && in between?

What the logic you wrote above will do (with the comma) is evaluate self.states.stopping === true to true and discard that result and then just run the && statement below. This is called the comma operator and it is fairly evil.

This also argues that you're short at least one test, the one that would have detected this. :)

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 285 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBVUOhTud42sDL9TGn9:-KBVUOhTud42sDL9TGnA:1303990508) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliWifiInfrastructure.js#L285)):*
And it is the fact that you caught this that lets me sleep at night. :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583)*

**Comment by vjrantal** [comment]
Review status: 3 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[thali/NextGeneration/thaliMobile.js, line 156 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBev5-sWef4g9e2lV2t:-KBg81zmnraZX6LVFwNc:-514174444) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L156)):*
The way I was thinking about it is that the thaliMobileStates reflect what the caller of thaliMobile would want the states to be. So, even if one of the underlying starts fails, thaliMobile would get into a start state.

When network conditions change, thaliMobile will try to call underlying starts again since it kind of "guesses" that the failure to start may have been due to some radio being off.

If the upper layer wants a more specific handling for certain start error, the error message is bubbled upwards and such handling can be implemented in upper layers.

---

*[thali/NextGeneration/thaliMobile.js, line 593 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBVWanrveo56sLu4QIj:-KBg8x9FLwo4KM6nRU8z:1229422360) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L593)):*
This is a way to do a copy of the object so that we don't emit the same object that we cache. This was mainly done since the cached peer has a custom availableSince property that we don't want to get emitted.

I am going the stringify -> parse now in a few places so it could be refactored into a utility function like "copy data object". I'll do that next time I need this functionality.

---

*[thali/NextGeneration/thaliMobile.js, line 680 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBejuzhT0igyufzSjRy:-KBgAD2VS-1XUGZ-HEfP:453625793) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L680)):*
Done.

Yep - much better.

---

*[thali/NextGeneration/thaliMobile.js, line 694 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBekKj1KbXeB66lTNZ0:-KBgAwGnzOcoa3UNUuuF:-885551972) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L694)):*
This is a good question and I am not sure what approach would result into simplest and most robust solution. Should we create this as a separate issue under which we would decide the approach we take, i.e., take it offline from this PR?

---

*[thali/NextGeneration/thaliMobile.js, line 734 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBelxKEj9Ihf6vp6E-H:-KBgBByWP98KznipX2d8:-2002634424) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L734)):*
Debugging purposes.

When testing different network conditions on device (like switch Wifi off and then on), I wanted to have something printed in the logs when things don't match.

This could be gotten rid of at some point if seen too verbose, but I'd like to keep it still.

---

*[thali/NextGeneration/thaliMobile.js, line 859 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBemWmRXD5eCuKM4wTb:-KBgBlm68TThctjkdg2c:403702454) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L859)):*
That is right.

Based on my knowledge so far, we could handle this event within `thaliMobileNativeWrapper` and there would not be a need to handle it in `thaliMobile`.

I pushed a commit to this PR that removes this section from the specification to mark that we should handle it in `thaliMobileNativeWrapper` (that file already contains instructions about handling it).

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 125 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBVTbpmRdrbqMarR0sc:-KBgUmD4Lm96j3xHrjkL:1884662595) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliWifiInfrastructure.js#L125)):*
Done.

Clear mistake from me that I fixed.

Also a fair point about the test so added a test that would have shown this issue.

ps. I wish editors would at least warn if comma operators are used within if clause conditions - I bet people rarely really want to do that..

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583)*

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliMobile.js, line 694 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBekKj1KbXeB66lTNZ0:-KBiHPGMF87bcRQOlvAn:1608732338) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L694)):*
Please do.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 125 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBVTbpmRdrbqMarR0sc:-KBiIYgSusKvv0WmeGRo:301571078) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliWifiInfrastructure.js#L125)):*
IntelliJ does warn about this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[thali/NextGeneration/thaliMobile.js, line 694 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583#-KBekKj1KbXeB66lTNZ0:-KBl42NNKuBH3wA1ojZS:1647180051) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc1fb48016043f4ee5e67a3dfe239a67c17eab0a/thali/NextGeneration/thaliMobile.js#L694)):*
Done.

https://github.com/thaliproject/Thali_CordovaPlugin/issues/589

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/583)*

**Pull request merged**
