### PR TITLE
Returning SSID and enabling Wifi to turn on and off.

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1547)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7844ef3)

**Comment by ThaliTester** [comment]
Test 94785159 (7844ef3) build started.

**Comment by ThaliTester** [comment]
Test (Success) 94785159 build is completed (7844ef3)

See https://github.com/ThaliTester/TestResults/tree/947851597844ef3_Returning_SSID_and_enabling_Wifi_to_turn_on_and_off__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 947851597844ef3(7844ef3) has failed

See https://github.com/ThaliTester/TestResults/tree/947851597844ef3_Returning_SSID_and_enabling_Wifi_to_turn_on_and_off__evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (0056c32)

**Comment by ThaliTester** [comment]
Test 94785159 (0056c32) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 94785159 build is completed (0056c32)

See https://github.com/ThaliTester/TestResults/tree/947851590056c32_Returning_SSID_and_enabling_Wifi_to_turn_on_and_off__evabishchevich/ for the logs

**Comment by vasilevskayaem** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1547#-:-KXBBEkI-ee9iIoF9oS_:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (d624ac3)

**Comment by ThaliTester** [comment]
Test 94785159 (d624ac3) build started.

**Comment by ThaliTester** [comment]
Test (Success) 94785159 build is completed (d624ac3)

See https://github.com/ThaliTester/TestResults/tree/94785159d624ac3_Returning_SSID_and_enabling_Wifi_to_turn_on_and_off__evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
@yaronyg I've tested it locally. There are some failed node tests but they aren't connected with our functionality

**Comment by ThaliTester** [comment]
Test 94785159d624ac3(d624ac3) has failed

See https://github.com/ThaliTester/TestResults/tree/94785159d624ac3_Returning_SSID_and_enabling_Wifi_to_turn_on_and_off__evabishchevich/ for the fail logs

**Pull request merged**
