### PR TITLE
The replacement for vNext_yarong_417_1, vNext_yarong_780 & vNext_yarong_812

### PR DESCRIPTION
**Pull request by yaronyg**
This merges everything together. I'm presenting this PR as a merge to vNext_yarong_812 because that is actually the least disruptive way to visualize the changes. Unfortunately there are a few redundant changes that actually came from vNext_yarong_417_1 but not many. 

Right now I do have a problem that 'jx npm run setupUnit' doesn't succeed! I'll need to further investigate that tomorrow as part of #926. If either of you want to investigate what the copy file error is that would be great. But if not I'll handle it tomorrow.

But once this is cleared then vNext_yarong_417_812 is the branch that #916 (for @artemjackson) should come from.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/928)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a744340)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6ff00c4)

**Comment by ThaliTester** [comment]
Test (Success) 82642184 build is completed (a744340)

See https://github.com/ThaliTester/TestResults/tree/82642184a744340_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 82642184 build is completed (6ff00c4)

See https://github.com/ThaliTester/TestResults/tree/826421846ff00c4_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 82642184a744340(a744340) has failed

See https://github.com/ThaliTester/TestResults/tree/82642184a744340_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
Test 826421846ff00c4(6ff00c4) has failed

See https://github.com/ThaliTester/TestResults/tree/826421846ff00c4_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (ee193d2)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (ee193d2)

See https://github.com/ThaliTester/TestResults/tree/82642184ee193d2_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (de7de38)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (de7de38)

See https://github.com/ThaliTester/TestResults/tree/82642184de7de38_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ea44f00)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (ea44f00)

See https://github.com/ThaliTester/TestResults/tree/82642184ea44f00_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b5a6580)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (b5a6580)

See https://github.com/ThaliTester/TestResults/tree/82642184b5a6580_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Review status: 0 of 68 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/928#-:-KQ80K1t5aFQMarPtv4j:bnfp4nl)*

**Comment by andrew-aladev** [comment]
Reviewed 82 of 82 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/928)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4c75f89)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (4c75f89)

See https://github.com/ThaliTester/TestResults/tree/826421844c75f89_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cbac892)

**Comment by ThaliTester** [comment]
Test (Success) 82642184 build is completed (cbac892)

See https://github.com/ThaliTester/TestResults/tree/82642184cbac892_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 82642184cbac892(cbac892) has failed

See https://github.com/ThaliTester/TestResults/tree/82642184cbac892_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (ea62b6e)

**Comment by ThaliTester** [comment]
Test (Success) 82642184 build is completed (ea62b6e)

See https://github.com/ThaliTester/TestResults/tree/82642184ea62b6e_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 82642184ea62b6e(ea62b6e) has failed

See https://github.com/ThaliTester/TestResults/tree/82642184ea62b6e_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the fail logs

**Comment by artemjackson** [comment]
@andrew-aladev @yaronyg This PR looks like a nightmare. It does not work even with my fixes from #936.
The [test logs](https://github.com/ThaliTester/TestResults/tree/82865362e858c08__934_Fixed_the_Mobile_mock_logic_artemjackson/) looks not really informative

**Comment by yaronyg** [comment]
@artemjackson Per our conversation today clearly something is very different in SM than in V8 and hopefully the multiple issues we filed today that we found from the logs will tell us what's going on. The asserts that are firing are obviously a huge problem (as is the fact that firing an assert doesn't fail the test!) as is the fact that we are getting so many connection errors for no apparent reason.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ebf39af)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (ebf39af)

See https://github.com/ThaliTester/TestResults/tree/82642184ebf39af_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6d740a6)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (6d740a6)

See https://github.com/ThaliTester/TestResults/tree/826421846d740a6_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9737fed)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (9737fed)

See https://github.com/ThaliTester/TestResults/tree/826421849737fed_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5eb109e)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (5eb109e)

See https://github.com/ThaliTester/TestResults/tree/826421845eb109e_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (28b1ff3)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (28b1ff3)

See https://github.com/ThaliTester/TestResults/tree/8264218428b1ff3_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (e24e069)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (e24e069)

See https://github.com/ThaliTester/TestResults/tree/82642184e24e069_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (8631020)

**Comment by ThaliTester** [comment]
Test (Fail) 82642184 build is completed (8631020)

See https://github.com/ThaliTester/TestResults/tree/826421848631020_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/ for the logs

**Comment by yaronyg** [comment]
I'm closing this PR because we aren't ready for it.

**Pull request closed without merging**
