### PR TITLE
Make CI build and unit tests pass

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/593)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6a5dbc7)

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (6a5dbc7)

See https://github.com/ThaliTester/TestResults/tree/613623666a5dbc7_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0556c10)

**Comment by ThaliTester** [comment]
Test 613623666a5dbc7(6a5dbc7) has failed

See https://github.com/ThaliTester/TestResults/tree/613623666a5dbc7_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (0556c10)

See https://github.com/ThaliTester/TestResults/tree/613623660556c10_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 613623660556c10(0556c10) has failed

See https://github.com/ThaliTester/TestResults/tree/613623660556c10_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1dfc74c)

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (1dfc74c)

See https://github.com/ThaliTester/TestResults/tree/613623661dfc74c_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 613623661dfc74c(1dfc74c) has failed

See https://github.com/ThaliTester/TestResults/tree/613623661dfc74c_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (121daa0)

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (121daa0)

See https://github.com/ThaliTester/TestResults/tree/61362366121daa0_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 61362366121daa0(121daa0) has failed

See https://github.com/ThaliTester/TestResults/tree/61362366121daa0_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
@yaronyg: All enabled tests now pass in CI on both platforms (`info: 86/86 passed (0 failures)`). The CI doesn't yet report it as a success run. This seems to be due to a crash on low API level devices. Not sure if we would want that our app doesn't crash on those or just remove the low API level device from CI.

All in all, I suggest we try to merge this PR as is and handle above issue as a follow-up separately.

**Comment by yaronyg** [comment]
@vjrantal How did we even load on a low API device? Shouldn't it have rejected us because our SDK level is too high? But I agree we should take this change and fix the low api issue separately.

---

Reviewed 2 of 2 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 4 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593#-KBtb3fur-k-M5w5ofhr:-KBtawSe1negdi7XmpqB:-1674890288) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/121daa040b779ed410a78ae3c6d5d17a5e1ab650/test/www/jxcore/bv_tests/testThaliMobileNative.js#L4)):*
Please let me sleep at night by filing a bug that we have disabled this test on mobile so we are sure to re-activate it later?

---

*[test/www/jxcore/lib/testUtils.js, line 148 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593#-KBtc4xuQaylt-70y_6q:-KBtc4xuQaylt-70y_6r:-1919247323) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/121daa040b779ed410a78ae3c6d5d17a5e1ab650/test/www/jxcore/lib/testUtils.js#L148)):*
Shouldn't this be a throw? Something has clearly gone very wrong if we are getting back a value we don't expect.

---

*[thali/package.json, line 14 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593#-KBtaKFxemf_lrs-H51q:-KBtaKFyijOO3eNUjDkX:-2140821015) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/121daa040b779ed410a78ae3c6d5d17a5e1ab650/thali/package.json#L14)):*
I suspect it would be cleaner to have a branch that we treat as master and then do dev work some where else. It's just easier to understand than dealing with the ID of a specific commit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593#-:-KBtcIAbi4UxIqkozzH6:657385429)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (61fd38c)

**Comment by vjrantal** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 4 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593#-KBtb3fur-k-M5w5ofhr:-KBwemhJHK8BwEt8LPAx:-1737557150) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/121daa040b779ed410a78ae3c6d5d17a5e1ab650/test/www/jxcore/bv_tests/testThaliMobileNative.js#L4)):*
I'll keep https://github.com/thaliproject/Thali_CordovaPlugin/issues/592 open until I have put them back. Tomi has already done work to make Android pass these and on iOS only requires a small fix that I can try to do.

---

*[test/www/jxcore/lib/testUtils.js, line 148 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593#-KBtc4xuQaylt-70y_6q:-KBwf00UkdHSQQlQwNbq:305885545) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/121daa040b779ed410a78ae3c6d5d17a5e1ab650/test/www/jxcore/lib/testUtils.js#L148)):*
Once I actually start using this info when reporting to CI, I can add more severe error in case we get unexpected value.

---

*[thali/package.json, line 14 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593#-KBtaKFxemf_lrs-H51q:-KBwfH0AORRi5lnRuT0K:221644604) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/121daa040b779ed410a78ae3c6d5d17a5e1ab650/thali/package.json#L14)):*
I added a specific commit sha1 which is useful if I need to make backwards-incompatible changes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593)*

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (61fd38c)

See https://github.com/ThaliTester/TestResults/tree/6136236661fd38c_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 6136236661fd38c(61fd38c) has failed

See https://github.com/ThaliTester/TestResults/tree/6136236661fd38c_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5d5a4d6)

**Comment by ThaliTester** [comment]
Test 613623665d5a4d6(5d5a4d6) has failed

See https://github.com/ThaliTester/TestResults/tree/613623665d5a4d6_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a48397d)

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (a48397d)

See https://github.com/ThaliTester/TestResults/tree/61362366a48397d_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 61362366a48397d(a48397d) has failed

See https://github.com/ThaliTester/TestResults/tree/61362366a48397d_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (345141a)

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (345141a)

See https://github.com/ThaliTester/TestResults/tree/61362366345141a_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 61362366345141a(345141a) has failed

See https://github.com/ThaliTester/TestResults/tree/61362366345141a_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b6c9a6f)

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (b6c9a6f)

See https://github.com/ThaliTester/TestResults/tree/61362366b6c9a6f_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 61362366b6c9a6f(b6c9a6f) has failed

See https://github.com/ThaliTester/TestResults/tree/61362366b6c9a6f_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b225741)

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (b225741)

See https://github.com/ThaliTester/TestResults/tree/61362366b225741_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 61362366b225741(b225741) has failed

See https://github.com/ThaliTester/TestResults/tree/61362366b225741_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7b1a8f4)

**Comment by ThaliTester** [comment]
Test (Success) 61362366 build is completed (7b1a8f4)

See https://github.com/ThaliTester/TestResults/tree/613623667b1a8f4_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 613623667b1a8f4(7b1a8f4) has failed

See https://github.com/ThaliTester/TestResults/tree/613623667b1a8f4_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
:shipit: 

---

Reviewed 3 of 5 files at r8, 1 of 1 files at r9, 1 of 1 files at r11, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593#-:-KCX5AENDNjuWjAAH_u1:1148172450)*

**Comment by vjrantal** [comment]
Reviewed 4 of 4 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/593)*

**Pull request merged**
