### PR TITLE
Commented out ios build specific code for CI (#798)

### PR DESCRIPTION
**Pull request by czyzm**
Due to issues in CI regarding building iOS app we need to temporarily disable the iOS build.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/801)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ec711b8)

**Comment by ThaliTester** [comment]
Test (Fail) 78968685 build is completed (ec711b8)

See https://github.com/ThaliTester/TestResults/tree/78968685ec711b8_Commented_out_ios_build_specific_code_for_CI___798__czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (da35147)

**Comment by ThaliTester** [comment]
Test (Success) 78968685 build is completed (da35147)

See https://github.com/ThaliTester/TestResults/tree/78968685da35147_Commented_out_ios_build_specific_code_for_CI___798__czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (940d272)

**Comment by ThaliTester** [comment]
Test (Success) 78968685 build is completed (940d272)

See https://github.com/ThaliTester/TestResults/tree/78968685940d272_Commented_out_ios_build_specific_code_for_CI___798__czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 78968685da35147(da35147) has failed

See https://github.com/ThaliTester/TestResults/tree/78968685da35147_Commented_out_ios_build_specific_code_for_CI___798__czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
Test 78968685940d272(940d272) has failed

See https://github.com/ThaliTester/TestResults/tree/78968685940d272_Commented_out_ios_build_specific_code_for_CI___798__czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0f74377)

**Comment by ThaliTester** [comment]
Test (Fail) 78968685 build is completed (0f74377)

See https://github.com/ThaliTester/TestResults/tree/789686850f74377_Commented_out_ios_build_specific_code_for_CI___798__czyzm/ for the logs

**Comment by jareksl** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/801)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cf1db7a)

**Comment by ThaliTester** [comment]
Test (Fail) 78968685 build is completed (cf1db7a)

See https://github.com/ThaliTester/TestResults/tree/78968685cf1db7a_Commented_out_ios_build_specific_code_for_CI___798__czyzm/ for the logs

**Comment by jareksl** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/801)*

**Comment by jareksl** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/801#-:-KNkTqG6J4cw_59Ka3ay:1417088721)*

**Pull request merged**
