### PR TITLE
Enable internal socket.io debug logging

### PR DESCRIPTION
**Pull request by chapko**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1364)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6ecde56)

**Comment by ThaliTester** [comment]
Test (Success) 89856960 build is completed (6ecde56)

See https://github.com/ThaliTester/TestResults/tree/898569606ecde56_Enable_internal_socket_io_debug_logging_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 898569606ecde56(6ecde56) has failed

See https://github.com/ThaliTester/TestResults/tree/898569606ecde56_Enable_internal_socket_io_debug_logging_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1364#-:-KUTbpPqbTlHn2lWMPlw:bnfp4nl)*

**Pull request closed without merging**
