### PR TITLE
Ios p2p fixes

### PR DESCRIPTION
**Pull request by tobybrad**
Simplify state management, especially around reasons for disconnect happening, seems to do the trick.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/255)

### CODE REVIEW

**Comment by yaronyg** [comment]
I was expecting this to include a fix for #164 but I don't see it. That isn't a show stopper but I just wanted to make sure that this was supposed to fix #164.


---

Reviewed 15 of 15 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerClientSession.m, line 132 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/255#-K1jG8f5FUfY6myivZjL)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ded03d997e2a0fa1f5e617d803a0d85c0655a91b/src/ios/MultipeerConnectivity/THEMultipeerClientSession.m#L132)):</sup>
NIT - I realize you have the assert above to check a bad state but if the state machine changes or what have you wouldn't it be more robust to help us find errors if there was a final else here that threw? In fact have you considered just using an explicit state machine library? I did a search for "objective-c state machine" and found at least three on GitHub. Using a state machine first approach you would hang logic off the state machine transitions so 'impossible' situations are, well, impossible.


---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerPeerSession.m, line 92 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/255#-K1jRLKQYsPEPyCs6bCj)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ded03d997e2a0fa1f5e617d803a0d85c0655a91b/src/ios/MultipeerConnectivity/THEMultipeerPeerSession.m#L92)):</sup>
One suspects this shouldn't just be an assert but should be live code. If something does go wrong we want to make sure we capture it no matter what, not only if we are in debug.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/255)

**Comment by yaronyg** [comment]
I'm waiting for responses.

**Comment by yaronyg** [comment]
Toby will check if this is superseded by another of his checkins and if so he will close.

**Comment by tobybrad** [comment]
Indeed these commits are all in  PR 272. Closing.

**Pull request closed without merging**
