### PR TITLE
CI TEST - DO NOT MERGE

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/294)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (39d7bdd)

**Comment by ThaliTester** [comment]
Test (Success) 50095778 build is completed (39d7bdd)

See https://github.com/ThaliTester/TestResults/tree/5009577839d7bdd_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5009577839d7bdd(39d7bdd) has failed

See https://github.com/ThaliTester/TestResults/tree/5009577839d7bdd_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fdad79a)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (59cb689)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (48de7f3)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (3773c4f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (23c1375)

**Comment by ThaliTester** [comment]
Test (Success) 50095778 build is completed (fdad79a)

See https://github.com/ThaliTester/TestResults/tree/50095778fdad79a_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 50095778 build is completed (59cb689)

See https://github.com/ThaliTester/TestResults/tree/5009577859cb689_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 50095778 build is completed (48de7f3)

See https://github.com/ThaliTester/TestResults/tree/5009577848de7f3_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 50095778fdad79a(fdad79a) has failed

See https://github.com/ThaliTester/TestResults/tree/50095778fdad79a_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 50095778 build is completed (3773c4f)

See https://github.com/ThaliTester/TestResults/tree/500957783773c4f_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 50095778 build is completed (23c1375)

See https://github.com/ThaliTester/TestResults/tree/5009577823c1375_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5009577859cb689(59cb689) has failed

See https://github.com/ThaliTester/TestResults/tree/5009577859cb689_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 500957783773c4f(3773c4f) has failed

See https://github.com/ThaliTester/TestResults/tree/500957783773c4f_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 5009577823c1375(23c1375) has failed

See https://github.com/ThaliTester/TestResults/tree/5009577823c1375_CI_TEST_-_DO_NOT_MERGE_vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
Tests done.

**Pull request closed without merging**
