### PR TITLE
bring new iOS ThaliCore to vNext

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1112)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (533f65d)

**Comment by ThaliTester** [comment]
Test (Success) 86185956 build is completed (533f65d)

See https://github.com/ThaliTester/TestResults/tree/86185956533f65d_bring_new_iOS_ThaliCore_to_vNext_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 86185956533f65d(533f65d) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/86185956533f65d_bring_new_iOS_ThaliCore_to_vNext_baydet/ for the logs

**Comment by yaronyg** [comment]
The last commit I hadn't reviewed was [here](https://github.com/thaliproject/Thali_CordovaPlugin/commit/533f65dba44cfd8beca325099e2cad331d3f53f0) and I went through it and it looks fine. So :lgtm: 

---

Reviewed 2 of 95 files at r1.
Review status: 2 of 94 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1112#-:-KSDV9_OZw_sIqu2OJ6c:biwella)*

**Comment by baydet** [comment]
Reviewed 11 of 95 files at r1.
Review status: 13 of 94 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1112)*

**Pull request merged**
