### PR TITLE
#904 Added getHostInfo method to ThaliMobileNativeWrapper

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/929)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (20481df)

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (20481df)

See https://github.com/ThaliTester/TestResults/tree/8271732020481df__904_Added_getHostInfo_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7c8c3f2)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (8a1b637)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (017dabd)

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (7c8c3f2)

See https://github.com/ThaliTester/TestResults/tree/827173207c8c3f2__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (945ad85)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (4fe167b)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (09dd0d3)

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (8a1b637)

See https://github.com/ThaliTester/TestResults/tree/827173208a1b637__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (017dabd)

See https://github.com/ThaliTester/TestResults/tree/82717320017dabd__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (945ad85)

See https://github.com/ThaliTester/TestResults/tree/82717320945ad85__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (4fe167b)

See https://github.com/ThaliTester/TestResults/tree/827173204fe167b__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (09dd0d3)

See https://github.com/ThaliTester/TestResults/tree/8271732009dd0d3__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (4418f80)

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (4418f80)

See https://github.com/ThaliTester/TestResults/tree/827173204418f80__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by yaronyg** [comment]
This isn't assigned to me and it is currently failing its build so I assume it's not ready for review?

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (94da9fb)

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (94da9fb)

See https://github.com/ThaliTester/TestResults/tree/8271732094da9fb__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Comment by artemjackson** [comment]
@yaronyg It's not ready yet

**Comment by artemjackson** [comment]
TODO: Failed tests should be fixed to use updates from `peerAvailabilityChanged` event and `getPeerHostInfo` method

**Comment by artemjackson** [comment]
This Pr is not completed yet. Resubmit when it's finished. It should be done by fixing the failed tests according to new `peerHostInfo` retrieving implementation.

**Comment by artemjackson** [comment]
This Pr is not completed yet. Resubmit when it's finished. It should be done by fixing the failed tests according to new peerHostInfo retrieving implementation.

**Comment by yaronyg** [comment]
@artemjackson Is there an open issue to track what this PR was fixing so we make sure not to forget we need to deal with this?

**Comment by artemjackson** [comment]
@yaronyg Yes, sure #904

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (94da9fb)

**Comment by ThaliTester** [comment]
Test (Fail) 82717320 build is completed (94da9fb)

See https://github.com/ThaliTester/TestResults/tree/8271732094da9fb__904_Added_getHostInfo_method_to_ThaliMobileNativeWrapper_artemjackson/ for the logs

**Pull request closed without merging**
