### PR TITLE
swift 3 migration for ThaliCore

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1488)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (02819db)

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (02819db)

See https://github.com/ThaliTester/TestResults/tree/9234929402819db_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by drinkius** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 45 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1488#-KX6H3bUX-QF-yjQ4rKW:-KX6H3bUX-QF-yjQ4rKX:blpkcwc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/02819db4febc86ce754f107d4892d912acd51987/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L45)):*
> ```Swift
>             opened = true
>             let queue = DispatchQueue.global()
>             queue.async(execute: {
> ```

NB: use trailing closure instead?

queue.async {

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 57 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1488#-KX6HE3u9Y0u5ewJY4Tc:-KX6HE3u9Y0u5ewJY4Td:b-szfx9t) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/02819db4febc86ce754f107d4892d912acd51987/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L57)):*
> ```Swift
> 
>                 RunLoop.current.run(until: Date.distantFuture)
>             })
> ```

NB: use trailing closure instead?

}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1488)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c6efa05)

**Comment by ThaliTester** [comment]
Test 92349294 (c6efa05) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (c6efa05)

See https://github.com/ThaliTester/TestResults/tree/92349294c6efa05_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (acecaca)

**Comment by ThaliTester** [comment]
Test 92349294 (acecaca) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (acecaca)

See https://github.com/ThaliTester/TestResults/tree/92349294acecaca_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e4168ee)

**Comment by ThaliTester** [comment]
Test 92349294 (e4168ee) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (e4168ee)

See https://github.com/ThaliTester/TestResults/tree/92349294e4168ee_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (50fb430)

**Comment by ThaliTester** [comment]
Test 92349294 (50fb430) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (50fb430)

See https://github.com/ThaliTester/TestResults/tree/9234929450fb430_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e709125)

**Comment by ThaliTester** [comment]
Test 92349294 (e709125) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (e709125)

See https://github.com/ThaliTester/TestResults/tree/92349294e709125_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (88062dd)

**Comment by ThaliTester** [comment]
Test 92349294 (88062dd) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (88062dd)

See https://github.com/ThaliTester/TestResults/tree/9234929488062dd_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (42d0bf5)

**Comment by ThaliTester** [comment]
Test 92349294 (42d0bf5) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (42d0bf5)

See https://github.com/ThaliTester/TestResults/tree/9234929442d0bf5_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b58b82c)

**Comment by ThaliTester** [comment]
Test 92349294 (b58b82c) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (b58b82c)

See https://github.com/ThaliTester/TestResults/tree/92349294b58b82c_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ffbe177)

**Comment by ThaliTester** [comment]
Test 92349294 (ffbe177) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (ffbe177)

See https://github.com/ThaliTester/TestResults/tree/92349294ffbe177_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (428b75c)

**Comment by ThaliTester** [comment]
Test 92349294 (428b75c) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (428b75c)

See https://github.com/ThaliTester/TestResults/tree/92349294428b75c_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (756abff)

**Comment by ThaliTester** [comment]
Test 92349294 (756abff) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (756abff)

See https://github.com/ThaliTester/TestResults/tree/92349294756abff_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a1d445d)

**Comment by ThaliTester** [comment]
Test 92349294 (a1d445d) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (a1d445d)

See https://github.com/ThaliTester/TestResults/tree/92349294a1d445d_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0c52c37)

**Comment by ThaliTester** [comment]
Test 92349294 (0c52c37) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (0c52c37)

See https://github.com/ThaliTester/TestResults/tree/923492940c52c37_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ac8a80e)

**Comment by ThaliTester** [comment]
Test 92349294 (ac8a80e) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (ac8a80e)

See https://github.com/ThaliTester/TestResults/tree/92349294ac8a80e_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (bf9c281)

**Comment by ThaliTester** [comment]
Test 92349294 (bf9c281) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (bf9c281)

See https://github.com/ThaliTester/TestResults/tree/92349294bf9c281_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9703bc2)

**Comment by ThaliTester** [comment]
Test 92349294 (9703bc2) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (9703bc2)

See https://github.com/ThaliTester/TestResults/tree/923492949703bc2_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (87edbc5)

**Comment by ThaliTester** [comment]
Test 92349294 (87edbc5) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (87edbc5)

See https://github.com/ThaliTester/TestResults/tree/9234929487edbc5_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (20692f1)

**Comment by ThaliTester** [comment]
Test 92349294 (20692f1) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92349294 build is completed (20692f1)

See https://github.com/ThaliTester/TestResults/tree/9234929420692f1_swift_3_migration_for_ThaliCore_baydet/ for the logs

**Pull request closed without merging**
