### PR TITLE
Support passing data in coordinated tests

### PR DESCRIPTION
**Pull request by vjrantal**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/656)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1df08af)

**Comment by ThaliTester** [comment]
Test (Success) 63680118 build is completed (1df08af)

See https://github.com/ThaliTester/TestResults/tree/636801181df08af_Support_passing_data_in_coordinated_tests_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 636801181df08af(1df08af) has failed

See https://github.com/ThaliTester/TestResults/tree/636801181df08af_Support_passing_data_in_coordinated_tests_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9a557d1)

**Comment by ThaliTester** [comment]
Test (Fail) 63680118 build is completed (9a557d1)

See https://github.com/ThaliTester/TestResults/tree/636801189a557d1_Support_passing_data_in_coordinated_tests_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d4cb974)

**Comment by ThaliTester** [comment]
Test 63680118d4cb974(d4cb974) has failed

See https://github.com/ThaliTester/TestResults/tree/63680118d4cb974_Support_passing_data_in_coordinated_tests_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f1433de)

**Comment by ThaliTester** [comment]
Test (Success) 63680118 build is completed (f1433de)

See https://github.com/ThaliTester/TestResults/tree/63680118f1433de_Support_passing_data_in_coordinated_tests_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8429a86)

**Comment by ThaliTester** [comment]
Test (Fail) 63680118 build is completed (8429a86)

See https://github.com/ThaliTester/TestResults/tree/636801188429a86_Support_passing_data_in_coordinated_tests_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 63680118 build is completed (8429a86)

See https://github.com/ThaliTester/TestResults/tree/636801188429a86_Support_passing_data_in_coordinated_tests_vjrantal/ for the logs

**Comment by yaronyg** [comment]
Reviewed 1 of 3 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/UnitTestFramework.js, line 98 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/656#-KDUsAxT6-ETdOzm5H9q:-KDUsAxT6-ETdOzm5H9r:1786487808) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8429a867f780dec4a17495ac62b5b01564dee738/test/TestServer/UnitTestFramework.js#L98)):*
NB: device.socket.emit(msg, data ? data : null);

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/656)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/UnitTestFramework.js, line 98 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/656#-KDUsAxT6-ETdOzm5H9q:-KDWntNX35SSK6-V61j9:-258608967) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8429a867f780dec4a17495ac62b5b01564dee738/test/TestServer/UnitTestFramework.js#L98)):*
That would send a second argument whereas my code doesn't. I think it wouldn't hurt, but I was too afraid to break any existing functionality so that I kept the other code as intact as possible :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/656)*

**Pull request merged**
