### PR TITLE
Implemented extended results

### LINKED ISSUE #1574: Upgrade desktop tests reporting
1. report just test names that failed.
2. report number of tests failed / total / passed.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1574.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1578)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (75cdb25)

**Comment by ThaliTester** [comment]
Test 95541073 (75cdb25) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (30bd934)

**Comment by ThaliTester** [comment]
Test 95541073 (30bd934) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95541073 build is completed (75cdb25)

See https://github.com/ThaliTester/TestResults/tree/9554107375cdb25_Implemented_extended_results_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 95541073 build is completed (30bd934)

See https://github.com/ThaliTester/TestResults/tree/9554107330bd934_Implemented_extended_results_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 9554107330bd934(30bd934) has failed

See https://github.com/ThaliTester/TestResults/tree/9554107330bd934_Implemented_extended_results_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
Please fix finally otherwise :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 183 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1578#-KXgHZcTCNRfu_HkbVBn:-KXgHZcUHBFT81SzQyz-:bj92d31) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/30bd934e77ec07732b96ec95489004a657f218a5/test/www/jxcore/lib/CoordinatedClient.js#L183)):*
> ```JavaScript
>       );
>     })
>     .finally(function () {
> ```

I think it would be good to get rid of finally. It's a custom function that is only supported in Bluebird and I think it would be best if we can just support the promises standard. It also has somewhat surprising behavior. Finally returns nothing (the promise has to be resolved outside of the finally) and occurs outside the normal loop of execution. It's essentially a kind of weird destructor.

I think it would be much easier to think about the code if we just used a catch and a then handler. The catch shouldn't ever be called but it's good style to include it and have it log an 'end of the world' error. Then use a 'then' handler to do the work below.

---

*[test/www/jxcore/lib/SimpleTape.js, line 271 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1578#-KXgIhv9DmJT6FTGmCZv:-KXgIhvAtqh23GxvWRBV:bq1boe8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/30bd934e77ec07732b96ec95489004a657f218a5/test/www/jxcore/lib/SimpleTape.js#L271)):*
> ```JavaScript
>     })
>   )
>     .finally(function () {
> ```

Same issue with finally as in the previous file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1578#-:-KXgJGQ0J1QHMD78YXxu:b-dbuh3l)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ed06991)

**Comment by ThaliTester** [comment]
Test 95541073 (ed06991) build started.

**Comment by andrew-aladev** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 183 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1578#-KXgHZcTCNRfu_HkbVBn:-KXjzMLPmNptjO_c7MhG:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/30bd934e77ec07732b96ec95489004a657f218a5/test/www/jxcore/lib/CoordinatedClient.js#L183)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I think it would be good to get rid of finally. It's a custom function that is only supported in Bluebird and I think it would be best if we can just support the promises standard. It also has somewhat surprising behavior. Finally returns nothing (the promise has to be resolved outside of the finally) and occurs outside the normal loop of execution. It's essentially a kind of weird destructor.

I think it would be much easier to think about the code if we just used a catch and a then handler. The catch shouldn't ever be called but it's good style to include it and have it log an 'end of the world' error. Then use a 'then' handler to do the work below.
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/SimpleTape.js, line 271 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1578#-KXgIhv9DmJT6FTGmCZv:-KXjzNOFL2Z5cnRVahq4:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/30bd934e77ec07732b96ec95489004a657f218a5/test/www/jxcore/lib/SimpleTape.js#L271)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Same issue with finally as in the previous file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1578)*

**Comment by ThaliTester** [comment]
Test (Fail) 95541073 build is completed (ed06991)

See https://github.com/ThaliTester/TestResults/tree/95541073ed06991_Implemented_extended_results_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6d1bb28)

**Comment by ThaliTester** [comment]
Test 95541073 (6d1bb28) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95541073 build is completed (6d1bb28)

See https://github.com/ThaliTester/TestResults/tree/955410736d1bb28_Implemented_extended_results_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0c9ab96)

**Comment by ThaliTester** [comment]
Test 95541073 (0c9ab96) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95541073 build is completed (0c9ab96)

See https://github.com/ThaliTester/TestResults/tree/955410730c9ab96_Implemented_extended_results_andrew-aladev/ for the logs

**Pull request merged**
