### PR TITLE
added connect function

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1177)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (3534d83)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (68a1443)

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ios/AppContext.swift, line 76 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177#-KSeyxgj63s9Aoo1Ttk0:-KSeyxgj63s9Aoo1Ttk1:bz67mvt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68a144354ccd259a55a4e42ff7bde79f2d299f3d/src/ios/AppContext.swift#L76)):*
> ```Swift
>     case advertisingActive
>     case generation
>     case err
> ```

what does `err` mean ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177)*

**Comment by ThaliTester** [comment]
Test (Success) 86891305 build is completed (3534d83)

See https://github.com/ThaliTester/TestResults/tree/868913053534d83_added_connect_function_baydet/ for the logs

**Comment by baydet** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ios/AppContext.swift, line 76 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177#-KSeyxgj63s9Aoo1Ttk0:-KSezzIr6TxRP_OrC_gF:b-bqj22y) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68a144354ccd259a55a4e42ff7bde79f2d299f3d/src/ios/AppContext.swift#L76)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> what does `err` mean ?
</details>
JSON key for ConnectCallback
https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_780_patch/thali/NextGeneration/thaliMobileNative.js#L188

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177)*

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ios/AppContext.swift, line 76 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177#-KSeyxgj63s9Aoo1Ttk0:-KSf-Y12-TlHQMxKFr09:b-bhvwf2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68a144354ccd259a55a4e42ff7bde79f2d299f3d/src/ios/AppContext.swift#L76)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> JSON key for ConnectCallback
> https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_780_patch/thali/NextGeneration/thaliMobileNative.js#L188
</details>
I see. I don't like how it's called in JS, because it's too simple to understand what it means, but I see that it's named exactly as in JS. 

Please add some documentation for `JSONKey` enum, at least something short.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177)*

**Comment by baydet** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ios/AppContext.swift, line 76 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177#-KSeyxgj63s9Aoo1Ttk0:-KSf1STB5Q7fOK7PjTtz:b-qu6n94) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68a144354ccd259a55a4e42ff7bde79f2d299f3d/src/ios/AppContext.swift#L76)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I see. I don't like how it's called in JS, because it's too simple to understand what it means, but I see that it's named exactly as in JS. 
> 
> Please add some documentation for `JSONKey` enum, at least something short.
</details>
Good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (c474d20)

**Comment by ThaliTester** [comment]
Test (Success) 86891305 build is completed (68a1443)

See https://github.com/ThaliTester/TestResults/tree/8689130568a1443_added_connect_function_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86891305 build is completed (c474d20)

See https://github.com/ThaliTester/TestResults/tree/86891305c474d20_added_connect_function_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 868913053534d83(3534d83) has failed

See https://github.com/ThaliTester/TestResults/tree/868913053534d83_added_connect_function_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
Test 8689130568a1443(68a1443) has failed

See https://github.com/ThaliTester/TestResults/tree/8689130568a1443_added_connect_function_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
Test 86891305c474d20(c474d20) has failed

See https://github.com/ThaliTester/TestResults/tree/86891305c474d20_added_connect_function_baydet/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1177#-:-KShapsb0pYacP5PnCtX:bnfp4nl)*

**Pull request merged**
