### PR TITLE
Updated salti for attachments

### LINKED ISSUE #1553: Please update salti version in master to the one with the attachment fix

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1553.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1558)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8f8f84a)

**Comment by ThaliTester** [comment]
Test 94997229 (8f8f84a) build started.

**Comment by ThaliTester** [comment]
Test (Success) 94997229 build is completed (8f8f84a)

See https://github.com/ThaliTester/TestResults/tree/949972298f8f84a_Updated_salti_for_attachments_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 949972298f8f84a(8f8f84a) has failed

See https://github.com/ThaliTester/TestResults/tree/949972298f8f84a_Updated_salti_for_attachments_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1558#-:-KXHVFrF9GS9jsOIgeAv:bnfp4nl)*

**Pull request merged**
