### PR TITLE
#419 PR#876 with updated jxcore-cordova

### PR DESCRIPTION
**Pull request by artemjackson**
This is #876 with #866

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/889)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (98d0ec6)

**Comment by ThaliTester** [comment]
Test (Fail) 81634701 build is completed (98d0ec6)

See https://github.com/ThaliTester/TestResults/tree/8163470198d0ec6__419_PR_876_with_updated_jxcore_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3c80038)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (f6c81fd)

**Comment by ThaliTester** [comment]
Test (Fail) 81634701 build is completed (3c80038)

See https://github.com/ThaliTester/TestResults/tree/816347013c80038__419_PR_876_with_updated_jxcore-cordova_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 81634701 build is completed (f6c81fd)

See https://github.com/ThaliTester/TestResults/tree/81634701f6c81fd__419_PR_876_with_updated_jxcore-cordova_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 81634701f6c81fd(f6c81fd) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/81634701f6c81fd__419_PR_876_with_updated_jxcore-cordova_artemjackson/ for the logs

**Comment by yaronyg** [comment]
@artemjackson this PR is huge. Something is screwy with the history. You didn't edit most of these files. Why are there so many changes files here?

---

Review status: 0 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/889#-:-KPOLDGTvE40oSPESA8V:bni4jl)*

**Comment by artemjackson** [comment]
@yarong please look at #876 PR to get the idea.
This PP (#889) is just #876(original #419 solution) + #866(jxcore-cordova update)
I didn't want to spoil #876 so I submitted this(#889) one to #876.

---

Review status: 0 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/889#-:-KPOWpRHa5_q6gISzTL9:bsc5gyo)*

**Comment by artemjackson** [comment]
Please, re-submit this to `vNext_417_812`

**Pull request closed without merging**
