### PR TITLE
Add support for installing jxcore-cordova plugin using JXC

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/428)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (2eaa85f)

**Comment by ThaliTester** [comment]
Test (Fail) 55613145 build is completed (2eaa85f)

See https://github.com/ThaliTester/TestResults/tree/556131452eaa85f_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dd493c6)

**Comment by ThaliTester** [comment]
Test (Success) 55613145 build is completed (dd493c6)

See https://github.com/ThaliTester/TestResults/tree/55613145dd493c6_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 55613145dd493c6(dd493c6) has failed

See https://github.com/ThaliTester/TestResults/tree/55613145dd493c6_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ec36bdc)

**Comment by ThaliTester** [comment]
Test (Fail) 55613145 build is completed (ec36bdc)

See https://github.com/ThaliTester/TestResults/tree/55613145ec36bdc_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e2b298d)

**Comment by ThaliTester** [comment]
Test (Success) 55613145 build is completed (e2b298d)

See https://github.com/ThaliTester/TestResults/tree/55613145e2b298d_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 55613145e2b298d(e2b298d) has failed

See https://github.com/ThaliTester/TestResults/tree/55613145e2b298d_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 99 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7lWZgEXbmX9RhY49pH:-K7lWZgEXbmX9RhY49pI:830774380) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/test/www/jxcore/lib/testUtils.js#L99)):*
/exists/exits

---

*[test/www/jxcore/lib/testUtils.js, line 102 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7lWgvLrbbGwXVELrtc:-K7lWgvLrbbGwXVELrtd:1472539043) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/test/www/jxcore/lib/testUtils.js#L102)):*
Wouldn't it be safer to have this always return a new directory so that if two different parts of the tests both decide to use this function they won't write over each other?

---

*[test/www/jxcore/package.json, line 34 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7lYbNQPaB2toH6TCvC:-K7lYbNQPaB2toH6TCvD:811893471) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/test/www/jxcore/package.json#L34)):*
Any reason why this isn't in alphabetic order?

---

*[thali/install/install.js, line 179 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7l_JM84OgxbWR8GgC9:-K7l_499LdAeaxEUmVsD:601262624) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/thali/install/install.js#L179)):*
On the off chance that there was a real error couldn't we at least output the error value with a note saying that we are ignoring it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 102 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7lWgvLrbbGwXVELrtc:-K7lzpUfOuAX0wd9Hvlv:34971953) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/test/www/jxcore/lib/testUtils.js#L102)):*
This function is also used when I mocked the `GetDocumentsPath` and functions using that in our expect they get the same folder. If some other functionality needs a unique directory, I'd suggest adding a new function like `randomDirectory` that is different every time called.

---

*[test/www/jxcore/package.json, line 34 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7lYbNQPaB2toH6TCvC:-K7m-UtuaueZCo8kjcf_:1869052658) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/test/www/jxcore/package.json#L34)):*
No reason - will fix.

---

*[thali/install/install.js, line 179 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7l_JM84OgxbWR8GgC9:-K7m-bUnwyCxAb9rAA36:603972630) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/thali/install/install.js#L179)):*
I will add that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/testUtils.js, line 102 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7lWgvLrbbGwXVELrtc:-K7m4-zbhf6Ou7HPli2j:1860477291) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/test/www/jxcore/lib/testUtils.js#L102)):*
I just find this function really surprising. Typically when asking for a temporary directory one gets a new one, not the same one. As for GetDocumentsPath, if you want to ensure the same directory then THAT would be the place to store the value. Not here. At the very least do a rename to something like "staticTempDirectory". That will at least warn other devs that something surprising is going on.

DO NOT BLOCK on this comment. Resolve how you see appropriate and check in.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[test/www/jxcore/lib/testUtils.js, line 102 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7lWgvLrbbGwXVELrtc:-K7m67Vn6JdUBXehIJ97:1322483811) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/test/www/jxcore/lib/testUtils.js#L102)):*
Got it - I will think about this.

What I was maybe comparing this was https://nodejs.org/api/os.html#os_os_tmpdir or just doing `ls /tmp` in your terminal where you would get the same temporary directory.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/www/jxcore/lib/testUtils.js, line 102 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428#-K7lWgvLrbbGwXVELrtc:-K7m8g0Uk5XPfv9Tg7vA:1942122528) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e2b298d13168162003ead50fb52d9623d73582e7/test/www/jxcore/lib/testUtils.js#L102)):*
it all comes down the particular of speech. There is "a temporary directory" and there is "the temporary directory". :) One way or another we just need to make sure that the developer isn't surprised.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2f1a5c4)

**Comment by ThaliTester** [comment]
Test (Fail) 55613145 build is completed (2f1a5c4)

See https://github.com/ThaliTester/TestResults/tree/556131452f1a5c4_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ac86c0e)

**Comment by ThaliTester** [comment]
Test (Fail) 55613145 build is completed (ac86c0e)

See https://github.com/ThaliTester/TestResults/tree/55613145ac86c0e_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ac448d4)

**Comment by ThaliTester** [comment]
Test (Success) 55613145 build is completed (ac448d4)

See https://github.com/ThaliTester/TestResults/tree/55613145ac448d4_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 55613145ac448d4(ac448d4) has failed

See https://github.com/ThaliTester/TestResults/tree/55613145ac448d4_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ceff368)

**Comment by ThaliTester** [comment]
Test (Fail) 55613145 build is completed (ceff368)

See https://github.com/ThaliTester/TestResults/tree/55613145ceff368_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b105d0b)

**Comment by ThaliTester** [comment]
Test 55613145b105d0b(b105d0b) has failed

See https://github.com/ThaliTester/TestResults/tree/55613145b105d0b_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c131883)

**Comment by ThaliTester** [comment]
Test (Success) 55613145 build is completed (c131883)

See https://github.com/ThaliTester/TestResults/tree/55613145c131883_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 55613145c131883(c131883) has failed

See https://github.com/ThaliTester/TestResults/tree/55613145c131883_Add_support_for_installing_jxcore-cordova_plugin_using_JXC_vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 3 of 7 files at r1, 4 of 6 files at r2, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/428)*

**Pull request merged**
