### PR TITLE
#987 Another implementation of Thali Test Runner

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/993)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b662592)

**Comment by ThaliTester** [comment]
Test (Fail) 84097932 build is completed (b662592)

See https://github.com/ThaliTester/TestResults/tree/84097932b662592__934_Fixed_test_failures_on_SM_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (74644d3)

**Comment by ThaliTester** [comment]
Test (Fail) 84097932 build is completed (74644d3)

See https://github.com/ThaliTester/TestResults/tree/8409793274644d3__934_Fixed_test_failures_on_SM_artemjackson/ for the logs

**Comment by artemjackson** [comment]
It seems that the issue #987 does not relate to current implementation of thali test runner. Closed.

**Pull request closed without merging**
