### PR TITLE
change devices tests network type from Wi-Fi to Native

### PR DESCRIPTION
**Pull request by larryonoff**
Implements thaliproject/Thali_CordovaPlugin#1604

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1608)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (7ea785d)

**Comment by ThaliTester** [comment]
Test 96524298 (7ea785d) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96524298 build is completed (7ea785d)

See https://github.com/ThaliTester/TestResults/tree/965242987ea785d_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e6e8851)

**Comment by ThaliTester** [comment]
Test 96524298 (e6e8851) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96524298 build is completed (e6e8851)

See https://github.com/ThaliTester/TestResults/tree/96524298e6e8851_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (7ea785d)

**Comment by ThaliTester** [comment]
Test 965242987ea785d(7ea785d) has failed

See https://github.com/ThaliTester/TestResults/tree/965242987ea785d_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (64b746f)

**Comment by ThaliTester** [comment]
Test 96524298 (64b746f) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96524298 build is completed (64b746f)

See https://github.com/ThaliTester/TestResults/tree/9652429864b746f_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9bf19f4)

**Comment by ThaliTester** [comment]
Test 96524298 (9bf19f4) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96524298 build is completed (9bf19f4)

See https://github.com/ThaliTester/TestResults/tree/965242989bf19f4_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (ae159c7)

**Comment by ThaliTester** [comment]
Test 96524298 (ae159c7) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96524298 build is completed (ae159c7)

See https://github.com/ThaliTester/TestResults/tree/96524298ae159c7_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 96524298ae159c7(ae159c7) has failed

See https://github.com/ThaliTester/TestResults/tree/96524298ae159c7_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d78d566)

**Comment by ThaliTester** [comment]
Test 96524298 (d78d566) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96524298 build is completed (d78d566)

See https://github.com/ThaliTester/TestResults/tree/96524298d78d566_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 96524298d78d566(d78d566) has failed

See https://github.com/ThaliTester/TestResults/tree/96524298d78d566_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3906281)

**Comment by ThaliTester** [comment]
Test 96524298 (3906281) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96524298 build is completed (3906281)

See https://github.com/ThaliTester/TestResults/tree/965242983906281_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 965242983906281(3906281) has failed

See https://github.com/ThaliTester/TestResults/tree/965242983906281_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1608#-:-KYKaADZ3pulGB0-Q2vo:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ae159c7)

**Comment by ThaliTester** [comment]
Test 96524298 (ae159c7) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96524298 build is completed (ae159c7)

See https://github.com/ThaliTester/TestResults/tree/96524298ae159c7_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (edd5c74)

**Comment by ThaliTester** [comment]
Test 96524298 (edd5c74) build started.

**Comment by ThaliTester** [comment]
Test 96524298ae159c7(ae159c7) has failed

See https://github.com/ThaliTester/TestResults/tree/96524298ae159c7_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 96524298 build is completed (edd5c74)

See https://github.com/ThaliTester/TestResults/tree/96524298edd5c74_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 96524298edd5c74(edd5c74) has failed

See https://github.com/ThaliTester/TestResults/tree/96524298edd5c74_change_devices_tests_network_type_from_Wi-Fi_to_Native_larryonoff/ for the fail logs

**Pull request merged**
