### PR TITLE
Update to jxcore-cordova 0.1.0.

### LINKED ISSUE #435: Update to jxcore-cordova 0.1.0

### PR DESCRIPTION
**Pull request by vjrantal**
Fixes #435.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/439)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7bac5c9)

**Comment by ThaliTester** [comment]
Test (Success) 55897376 build is completed (7bac5c9)

See https://github.com/ThaliTester/TestResults/tree/558973767bac5c9_Update_to_jxcore-cordova_0_1_0__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 558973767bac5c9(7bac5c9) has failed

See https://github.com/ThaliTester/TestResults/tree/558973767bac5c9_Update_to_jxcore-cordova_0_1_0__vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
Will do the update in branch `vNext` instead.

**Pull request closed without merging**
