### PR TITLE
#1734 Fix race conditions in the pouchDBCheckpointsPlugin

### LINKED ISSUE #1734: Fix test "enqueue and run in order"
Logs:
S6 https://gist.github.com/enricogior/1a597fcac133a77020be85055b3627a5
S7 https://gist.github.com/enricogior/1501f3c9d2352b2ed991d2ce18ce0a55
6P https://gist.github.com/enricogior/e382b62be1177df8a0a4424a3c81e091
server https://gist.github.com/enricogior/b479162d1677ba1e6c4fdd38f5f94f31

Search for
```
ERROR pouchDBCheckpointsPlugin: 'Error while fetching db info: 'Error: ENOENT, lstat '/data/user/0/com.test.thalitest/files/pouchdb-test-directory/59ek57zqqf59ek96l05o/CURRENT'', stack: '@native:jxcore_js_object:3:12
```

branch: evabishchevich_1724
commit: https://github.com/thaliproject/Thali_CordovaPlugin/commit/a486bdc2327457fb7a6784632b1b157f1bbc2e3b

### PR DESCRIPTION
**Pull request by chapko**
Fixes #1734

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1741)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8b10a27)

**Comment by ThaliTester** [comment]
Test 102446911 (8b10a27) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 102446911 build is completed (8b10a27)

See https://github.com/ThaliTester/TestResults/tree/1024469118b10a27__1734_Fix_race_conditions_in_the_pouchDBCheckpointsPlugin_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cf31575)

**Comment by ThaliTester** [comment]
Test 102446911 (cf31575) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a6c1be7)

**Comment by ThaliTester** [comment]
Test 102446911 (a6c1be7) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 102446911 build is completed (cf31575)

See https://github.com/ThaliTester/TestResults/tree/102446911cf31575__1734_Fix_race_conditions_in_the_pouchDBCheckpointsPlugin_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 102446911 build is completed (a6c1be7)

See https://github.com/ThaliTester/TestResults/tree/102446911a6c1be7__1734_Fix_race_conditions_in_the_pouchDBCheckpointsPlugin_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 102446911a6c1be7(a6c1be7) has failed

See https://github.com/ThaliTester/TestResults/tree/102446911a6c1be7__1734_Fix_race_conditions_in_the_pouchDBCheckpointsPlugin_chapko/ for the fail logs

**Comment by yaronyg** [comment]
Please see comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 70 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCiV8sQHr-ysNi3FOu:-KbCiV8sQHr-ysNi3FOv:b12dnly) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L70)):*
> ```JavaScript
>     });
> 
>     var changes = db.changes({
> ```

How does this ever get cancelled? If we have stopped Thali isn't this going to just run forever? Seems like a memory leak.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 74 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCi_5rUtRVeJvUdg8T:-KbCiPe8aQnTwXyWFq9A:bwpp0t9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L74)):*
> ```JavaScript
>       since: 'now'
>     })
>       .on('error', function (error) {
> ```

Shouldn't we also grab the complete event? It is fired if a live change is cancelled which per my previous comment we should probably be doing. And when it happens shouldn't we call cancel on checkDBSizeThrottled?

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 79 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCi7bEaodfd3aDpTEi:-KbCi7bEaodfd3aDpTEj:bplanwu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L79)):*
> ```JavaScript
>           String(error), error.stack
>         );
>         changes.cancel();
> ```

Shouldn't we call cancel on checkDBSizeThrottled here as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-:-KbCisZ_Yxp9e8m-1DfS:bd72ecc)*

**Comment by czyzm** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741)*

**Comment by evabishchevich** [comment]
https://gist.github.com/evabishchevich/0417304547546ba6c410a30c1f3aa7db

**Comment by chapko** [comment]
I think the best course for this PR is to update plugin API a bit to make it possible to unsubscribe from 'checkpoint' events. See comments for details.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 70 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCiV8sQHr-ysNi3FOu:-KgOZ_xNUqdrro6TU7Vv:b-ntyyu1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L70)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

How does this ever get cancelled? If we have stopped Thali isn't this going to just run forever? Seems like a memory leak.
</blockquote></details>

There is no public API to cancel it manually. All we have is `onCheckpointReached` method to subscribe to the checkpoint event.

Original spec (#319) suggests `.on('...', handler)` syntax. This way it would be possible to unsubscribe and if there are no 'checkpoint' event listeners we could just cancel changes feed. But it was implemented differently.

My suggestion is to change the API and use `db.on()` and `db.removeListener()` to subscribe and unsubscribe respectively.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 74 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCi_5rUtRVeJvUdg8T:-KgObuhpmZxDOciEFos-:bvek1wh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L74)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Shouldn't we also grab the complete event? It is fired if a live change is cancelled which per my previous comment we should probably be doing. And when it happens shouldn't we call cancel on checkDBSizeThrottled?
</blockquote></details>

Yes, it makes sense. The only thing that bothers me is that 'complete' event might be emitted asynchronously after calling `cancel`. I think we should call `checkDBSizeThrottled.cancel()` together with `changes.cancel()`. Or we can also listen to 'cancel' event, but it is not documented, so I wouldn't recommend it if there are other solutions.

I suggest to manually cancel timer synchronously with `changes.cancel()` **and** cancel it in the complete event handler.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 79 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCi7bEaodfd3aDpTEi:-KgOu43uKNU29TcyAUMX:b-xistwh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L79)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Shouldn't we call cancel on checkDBSizeThrottled here as well?
</blockquote></details>

Yes, everything from previous comment applies here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-:-KgOv8ZZ8SO0UnRU3t4k:b-hp4vue)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 70 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCiV8sQHr-ysNi3FOu:-KgPtSYqZ7-iEUM3JeqD:b-qb4ldn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L70)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

There is no public API to cancel it manually. All we have is `onCheckpointReached` method to subscribe to the checkpoint event.

Original spec (#319) suggests `.on('...', handler)` syntax. This way it would be possible to unsubscribe and if there are no 'checkpoint' event listeners we could just cancel changes feed. But it was implemented differently.

My suggestion is to change the API and use `db.on()` and `db.removeListener()` to subscribe and unsubscribe respectively.
</blockquote></details>

It's just weird that this wasn't ever caught by the PouchDB folks. But I guess as long as you don't check changes very often you would probably never even notice the leak. How big a deal do we think this will be in practice for us? 

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 74 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCi_5rUtRVeJvUdg8T:-KgPtrgeRAe0271TcKxe:blmrh80) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L74)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

Yes, it makes sense. The only thing that bothers me is that 'complete' event might be emitted asynchronously after calling `cancel`. I think we should call `checkDBSizeThrottled.cancel()` together with `changes.cancel()`. Or we can also listen to 'cancel' event, but it is not documented, so I wouldn't recommend it if there are other solutions.

I suggest to manually cancel timer synchronously with `changes.cancel()` **and** cancel it in the complete event handler.
</blockquote></details>

Nuke it from orbit, it's the only way to be sure. Agreed, cancel everything.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 79 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCi7bEaodfd3aDpTEi:-KgPtwnei4hBZNZQzWnn:b-89a4l7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L79)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

Yes, everything from previous comment applies here.
</blockquote></details>

Ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741)*

**Comment by chapko** [comment]
pouchDBCheckpointsPlugin is not used anywhere in Thali, thats why this PR was put on hold for such a long time and we just disabled failing tests. See comments below.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 70 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCiV8sQHr-ysNi3FOu:-KgPuXgMlZgw_T7x_Z-I:bgol16e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L70)):*
I'm not sure what PouchDB folks has to do with it. It is our own plugin.

As far as I know this plugin should fix #499. The only problem is that it is not used anywhere in the Thali. I think it makes more sense to make it a separate module.

> How big a deal do we think this will be in practice for us?

Right now the only impact it has is 3 KB wasted to store its source code :) If someone is going to use it with default config, then it most likely will leak one change listener per database.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-:-KgQ1JaQo7uTfmnnUujE:bce20ls)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 70 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741#-KbCiV8sQHr-ysNi3FOu:-KgUpHmRFp5Ktv-dy0ya:b-wmav19) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a6c1be7db5f89c23a7982732174c2107e3d12d08/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L70)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

I'm not sure what PouchDB folks has to do with it. It is our own plugin.

As far as I know this plugin should fix #499. The only problem is that it is not used anywhere in the Thali. I think it makes more sense to make it a separate module.

> How big a deal do we think this will be in practice for us?

Right now the only impact it has is 3 KB wasted to store its source code :) If someone is going to use it with default config, then it most likely will leak one change listener per database.
</blockquote></details>

Sorry, as usual, I was confused. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1741)*

**Pull request closed without merging**
