### PR TITLE
Fixes from review

### PR DESCRIPTION
**Pull request by yaronyg**
testThaliNotificationBeacons - JSCS/JShint fixes as well as a new test
that showed that we weren't properly parsing the beacons.

hkdf - JSCS/JSHint fixes

thaliNotificationBeacons - JSCS/JShint fixes, factored out the function
to create public key hashes and some other random stuff.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/516)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c9ea290)

**Comment by ThaliTester** [comment]
Test (Success) 58497659 build is completed (c9ea290)

See https://github.com/ThaliTester/TestResults/tree/58497659c9ea290_Fixes_from_review_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 58497659c9ea290(c9ea290) has failed

See https://github.com/ThaliTester/TestResults/tree/58497659c9ea290_Fixes_from_review_yaronyg/ for the fail logs

**Comment by mpodwysocki** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/516)*

**Pull request merged**
