### PR TITLE
Simple skip test function

### LINKED ISSUE #1149: Simple skip test function
We need a dirt simple (DO NOT DO ANYTHING FANCY) function that we can use to mark a test as skipped. When a test is skipped the log should output a statement saying it was skipped and we should report back to the coordinator (for coordinated tests) that the test has been skipped. All the coordinator needs to know is that at least one test was skipped. We can read the logs to find out which.

Because we will have to re-run the tests multiple times in a single outing (e.g. once for wifi only then native only and then both) we can't just stick a function on test(). But what we could do is either:

test(name, [check function], test function). In other words we can add an extra optional second argument which is a function that takes 't' as an argument and return a boolean. If the boolean is false then the test will be skipped and the test handler will output a log statement stating that the test was skipped and mark a flag that will eventually go back to the coordinator (when we are using one) so it knows that at least one test was skipped.

Another option would be:
test(name, function(t) {
   t.skip(check function);
}
Where the check function is a function that returns a boolean that if false means the test should be skipped as given above.

Or whatever you like.

Just make it DIRT SIMPLE AND QUICK. We just need this because we are turning tests on and off for different reasons in different places and we need some dirt simple system to let us do this in an easy to track way so we know when a particular test was skipped on a particular platform/setting.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1149.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1160)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e849c33)

**Comment by ThaliTester** [comment]
Test (Success) 86743101 build is completed (e849c33)

See https://github.com/ThaliTester/TestResults/tree/86743101e849c33_Simple_skip_test_function_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 86743101e849c33(e849c33) has failed

See https://github.com/ThaliTester/TestResults/tree/86743101e849c33_Simple_skip_test_function_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
I think some scaffolding got left in SimpleTape. Also please edit UnitTestFramework, lines 61 and 68 to indicate if tests were skipped or not. A simple boolean says "test were skipped" or "tests weren't skipped" is fine. For now we can search the logs to see which tests were skipped. Once you fix those two then :lgtm: 

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/lib/SimpleTape.js, line 99 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSbmpIZL-lh7ScxiRGE:-KSbmpI_Yj09SuL84wbK:b866lhn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L99)):*
> ```JavaScript
> }
> 
> SimpleThaliTape.prototype._runTest = function (test) {
> ```

Isn't this whole function ignored because _runTest is redefined on line 116?

---

*[test/www/jxcore/lib/SimpleTape.js, line 102 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSbmboX4JWxc3jro36X:-KSbmboX4JWxc3jro36Y:b-r1jtu6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L102)):*
> ```JavaScript
>   var self = this;
> 
>   return Promise.try(function () {
> ```

Isn't this code redundant with the code below in tape()?

---

*[test/www/jxcore/lib/SimpleTape.js, line 104 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSblH7d8p18zebJuybt:-KSblH7e1OF-KLipHHPT:bk57qha) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L104)):*
> ```JavaScript
>   return Promise.try(function () {
>     if (test.canBeSkipped) {
>       return test.canBeSkipped();
> ```

NB: I don't think it's a good idea to depend on the default return value, I know it's null and I know the right thing would happen but I think it's much cleaner to be explicit. E.g. return test.canBeSkipped ? test.canBeSkipped() : false;

---

*[test/www/jxcore/lib/SimpleTape.js, line 109 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSbmCuaGLpsJ5Jmj-F9:-KSbmCuaGLpsJ5Jmj-FA:b-hw1sh8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L109)):*
> ```JavaScript
>   .then(function (canBeSkipped) {
>     if (canBeSkipped) {
>       return self._skipTest(test);
> ```

Where is this function defined?

---

*[test/www/jxcore/lib/SimpleTape.js, line 111 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSbmLQfM_ersMwyadps:-KSbmLQfM_ersMwyadpt:b-hw1sh8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L111)):*
> ```JavaScript
>       return self._skipTest(test);
>     } else {
>       return self._processTest(test);
> ```

Where is this function defined?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-:-KSbmxmQrg8CdZXh02ef:b5i0dgw)*

**Comment by andrew-aladev** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/lib/SimpleTape.js, line 99 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSbmpIZL-lh7ScxiRGE:-KSf7iD6r7-6I7pDkzS4:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L99)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Isn't this whole function ignored because _runTest is redefined on line 116?
</details>
Done.

---

*[test/www/jxcore/lib/SimpleTape.js, line 102 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSbmboX4JWxc3jro36X:-KSf7jCyMUv_5xPjxSob:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L102)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Isn't this code redundant with the code below in tape()?
</details>
Done.

---

*[test/www/jxcore/lib/SimpleTape.js, line 104 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSblH7d8p18zebJuybt:-KSf7jtqGRQPKjev9GuG:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L104)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: I don't think it's a good idea to depend on the default return value, I know it's null and I know the right thing would happen but I think it's much cleaner to be explicit. E.g. return test.canBeSkipped ? test.canBeSkipped() : false;
</details>
Done.

---

*[test/www/jxcore/lib/SimpleTape.js, line 109 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSbmCuaGLpsJ5Jmj-F9:-KSf7kYzqlKFPIuH2F--:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L109)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Where is this function defined?
</details>
Done.

---

*[test/www/jxcore/lib/SimpleTape.js, line 111 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160#-KSbmLQfM_ersMwyadps:-KSf7lBJ53awvSt2cX07:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e849c33e874ef71de3f80e8af1b043a6d9c295ab/test/www/jxcore/lib/SimpleTape.js#L111)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Where is this function defined?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1160)*

**Pull request merged**
