### PR TITLE
A lot of cleanup

### PR DESCRIPTION
**Pull request by yaronyg**
This is mostly just refactoring and cleanup, fixing minor bugs, throwing in some extra tests. Etc. I'm not done yet with this work but I'm running into a bug in #664 that I believe is actually caused the createPeerListener and so I need this code checked in so I don't end up having to layer PRs on PRs. Since this passes all tests it shouldn't make our situation any worse by checking it in.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/669)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f354bbf)

**Comment by ThaliTester** [comment]
Test (Fail) 63968542 build is completed (f354bbf)

See https://github.com/ThaliTester/TestResults/tree/63968542f354bbf_A_lot_of_cleanup_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9f2522f)

**Comment by ThaliTester** [comment]
Test (Fail) 63968542 build is completed (9f2522f)

See https://github.com/ThaliTester/TestResults/tree/639685429f2522f_A_lot_of_cleanup_yaronyg/ for the logs

**Comment by vjrantal** [comment]
For some reason, these changes cause `jx runTests.js` sometimes hang. Seems to happen always (3/3) in AppVeyor and sometimes in our CI and I have also reproduce this locally on a Mac.

The test that hangs is `# createPeerListener - pleaseConnect === true, connection resolves promise`.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testMakeIntoCloseAllServer.js, line 96 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/669#-KDbOARmI3OuaycJ0qL6:-KDbOARmI3OuaycJ0qL7:-1679683081) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9f2522fa886cafa5fd35ac44e35838fda2dbe52d/test/www/jxcore/bv_tests/testMakeIntoCloseAllServer.js#L96)):*
NB: Some extra whitespace above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/669#-:-KDbVWqH-JDb6VeV7B2q:499772639)*

**Comment by ThaliTester** [comment]
Test (Fail) 63968542 build is completed (9f2522f)

See https://github.com/ThaliTester/TestResults/tree/639685429f2522f_A_lot_of_cleanup_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e6bfc69)

**Comment by ThaliTester** [comment]
Test (Success) 63968542 build is completed (e6bfc69)

See https://github.com/ThaliTester/TestResults/tree/63968542e6bfc69_A_lot_of_cleanup_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 63968542e6bfc69(e6bfc69) has failed

See https://github.com/ThaliTester/TestResults/tree/63968542e6bfc69_A_lot_of_cleanup_yaronyg/ for the fail logs

**Pull request merged**
