### PR TITLE
Fix to issue #622: Network events are not always fired on Android

### PR DESCRIPTION
**Pull request by tompaana**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/624)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aa56850)

**Comment by vjrantal** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectivityMonitor.java, line 191 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/624#-KCtwS8Ky_yLHjM0lz-Y:-KCtwS8Ky_yLHjM0lz-Z:-1071322208) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/aa56850e4c213cc63aa1579cf0d7fec8ab230a0b/src/android/java/io/jxcore/node/ConnectivityMonitor.java#L191)):*
What would be a case where connectivity info updates, but we would not want to notify the node layer?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/624)*

**Comment by tompaana** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/android/java/io/jxcore/node/ConnectivityMonitor.java, line 191 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/624#-KCtwS8Ky_yLHjM0lz-Y:-KCtx-3WL_8yJgRMLGGI:-558678171) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/aa56850e4c213cc63aa1579cf0d7fec8ab230a0b/src/android/java/io/jxcore/node/ConnectivityMonitor.java#L191)):*
When it's an "unimportant" state change. Currently, one such event is when we start to connect to a wireless AP. However, we notify only after we have successfully connected, but the "starting to connect" event is unimportant.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/624)*

**Comment by ThaliTester** [comment]
Test (Success) 62885377 build is completed (aa56850)

See https://github.com/ThaliTester/TestResults/tree/62885377aa56850_Fix_to_issue__622__Network_events_are_not_always_fired_on_Android_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 62885377aa56850(aa56850) has failed

See https://github.com/ThaliTester/TestResults/tree/62885377aa56850_Fix_to_issue__622__Network_events_are_not_always_fired_on_Android_tompaana/ for the fail logs

**Pull request merged**
