### PR TITLE
New thali tape

### PR DESCRIPTION
**Pull request by andrew-aladev**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1062)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6e6b131)

**Comment by ThaliTester** [comment]
Test (Fail) 85606604 build is completed (6e6b131)

See https://github.com/ThaliTester/TestResults/tree/856066046e6b131_New_thali_tape_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (eee3408)

**Comment by ThaliTester** [comment]
Test (Success) 85606604 build is completed (eee3408)

See https://github.com/ThaliTester/TestResults/tree/85606604eee3408_New_thali_tape_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 85606604eee3408(eee3408) has failed

See https://github.com/ThaliTester/TestResults/tree/85606604eee3408_New_thali_tape_andrew-aladev/ for the fail logs

**Comment by artemjackson** [comment]
Reviewed 25 of 28 files at r2, 1 of 1 files at r3.
Review status: 26 of 29 files reviewed at latest revision, 14 unresolved discussions.

---

*[test/www/jxcore/runTests.js, line 46 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0QkU-JZZxZj6s2FTs:-KS0QkU-JZZxZj6s2FTt:bqfxo43) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/runTests.js#L46)):*
> ```JavaScript
> var platform;
> if (
>   typeof jxcore !== 'undefined' &&
> ```

NB: This check is redundant, the check belowe handles the case

---

*[test/www/jxcore/runTests.js, line 54 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0RVT8Gw0cvGDxETcw:-KS0RVT9W1JVVDVViXbR:bacfrsi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/runTests.js#L54)):*
> ```JavaScript
>   platform = 'android';
> } else {
>   platform = 'ios';
> ```

NB:  If there is no `jxcore` then the `platform` is `ios`? Is it desired behaviour?
It would be better to use `process.platform` to identify the real`platform`

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 25 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0UBMdypHIJxxrR9qE:-KS0UBMdypHIJxxrR9qF:b4ss8a1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L25)):*
> ```JavaScript
> function CoordinatedClient(tests, uuid, platform, version, hasRequiredHardware) {
>   asserts.isArray(tests);
>   tests.forEach(function (test) {
> ```

NB:  Shouldn't we create a function for `test` validation?

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 46 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0VR3EDeY9oNHDGXjh:-KS0VR3EDeY9oNHDGXji:b-8399s3) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L46)):*
> ```JavaScript
>   };
> 
>   this._tests = tests.slice(0);
> ```

You may use `slice()` without params to copy an array as well

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 129 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0WLb2goZKSPVw6n0u:-KS0WLb3XNGeGveEqYd5:bzi5mgg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L129)):*
> ```JavaScript
>     os: this._platform,
>     version: this._version,
>     supportedHardware: this._hasRequiredHardware,
> ```

NB:  I think that `supportedHardware` is an array of hardwares, but not a boolean value
So I would suggest rename it to `hasRequiredHardware` 

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 136 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0Yj5r6FY2-CVTKDUS:-KS0Yj5r6FY2-CVTKDUT:b-2f4d1g) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L136)):*
> ```JavaScript
>   var self = this;
> 
>   var testNamesString = CoordinatedClient.getData(data);
> ```

This method returns an array, isn't it? So why we need to `parse` it again?

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 147 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0ZFLTa1nKqPjL-dzW:-KS0ZFLTa1nKqPjL-dzX:b-ic5x13) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L147)):*
> ```JavaScript
>   Promise.all(promises);
> 
>   this._emit('schedule_confirmed', data);
> ```

NB:  Shouldn't we `emit` in `Promise.all(...).then` ?
`self._scheduleTest(test)` can also return rejected promise so we need `Promise.all(...).catch` as well

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 283 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0aGbUho4vOkr-MjM0:-KS0aGbUho4vOkr-MjM1:b7griy) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L283)):*
> ```JavaScript
>             event + '_finished',
>             JSON.stringify({
>               'success': success,
> ```

NB:  Why do we need this quotes?

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 326 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0b5GpQ47jFccEzRxb:-KS0b5GpQ47jFccEzRxc:b5wmpqf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L326)):*
> ```JavaScript
>   return new Promise(function (resolve, reject) {
>     tape('setup', function (tape) {
>       processEvent(tape, 'setup_' + test.name, test.options.setup, test.options.setupTimeout)
> ```

NB: What if a `setup` option is not defined? Is the `setup` option required?

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 327 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0arak4bKio9P_1Ft2:-KS0arak4bKio9P_1Ft3:b1n42k4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L327)):*
> ```JavaScript
>     tape('setup', function (tape) {
>       processEvent(tape, 'setup_' + test.name, test.options.setup, test.options.setupTimeout)
>       .catch(function (error) {
> ```

NB:  You can use `catch(reject)` as well

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 342 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0b_dO359dk0Eggkz8:-KS0b_dPh5kZWS2htILW:b25c31q) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedClient.js#L342)):*
> ```JavaScript
>     });
> 
>     tape('teardown', function (tape) {
> ```

NB:  The same question as for `setup`

---

*[test/www/jxcore/lib/CoordinatedTape.js, line 20 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0bv-GHmNZkfAHaCnS:-KS0bv-HW_gDMwr3-YKQ:b-b6j31s) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedTape.js#L20)):*
> ```JavaScript
> function CoordinatedThaliTape (options) {
>   // We are calling this function directly without 'new'.
>   if (!this) {
> ```

NB:  Shouldn't us force `CoordinatedThaliTape` users to use `new` before `constructor` function?

---

*[test/www/jxcore/lib/CoordinatedTape.js, line 39 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0cR7h3-d1WMUZBKp_:-KS0cR7iZIBSCzxdaCT3:b-g3qtc8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/CoordinatedTape.js#L39)):*
> ```JavaScript
>   CoordinatedThaliTape.prototype.defaults,
>   {
>     emitRetryCount:   20,
> ```

NB:  If it's hardcoded here, why not to move it into `defaults`?

---

*[test/www/jxcore/lib/SimpleTape.js, line 35 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0gUev6k7uhyFOZTG-:-KS0gUev6k7uhyFOZTG0:btpq5p) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/SimpleTape.js#L35)):*
> ```JavaScript
>   this._state = SimpleThaliTape.states.created;
> 
>   this._resolveInstance();
> ```

Shouldn't we use an unique `tape` instance for each `SimpleThaliTape` instance?
I mean to use [tape.testCreateHarness](https://github.com/substack/tape#var-htest--testcreateharness) for each `SimpleThalitape` instance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (33ca4f7)

**Comment by ThaliTester** [comment]
Test (Success) 85606604 build is completed (33ca4f7)

See https://github.com/ThaliTester/TestResults/tree/8560660433ca4f7_New_thali_tape_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
> CoordinatedThaliTape.prototype.defaults,
  {
    emitRetryCount:   20,

This is the default values for coordinated tape.

**Comment by andrew-aladev** [comment]
> NB: Shouldn't us force CoordinatedThaliTape users to use new before constructor function?

We need to replace `tape({ setup: ... })` with `new tape({ setup: ... })` and say to all users that they need to use `new tape`. I think we can leave this.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e7bc10e)

**Comment by ThaliTester** [comment]
Test (Fail) 85606604 build is completed (e7bc10e)

See https://github.com/ThaliTester/TestResults/tree/85606604e7bc10e_New_thali_tape_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
Review status: 18 of 50 files reviewed at latest revision, 14 unresolved discussions.

---

*[test/www/jxcore/lib/SimpleTape.js, line 35 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-KS0gUev6k7uhyFOZTG-:-KS5t9PAIDkRyd6ZQGyp:bfge495) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/eee340801a9a0939f50b13ebe3db11fdd9431a2e/test/www/jxcore/lib/SimpleTape.js#L35)):*
<details><summary><i>Previously, artemjackson (Artyom Stepanishchev) wrote…</i></summary>
> Shouldn't we use an unique `tape` instance for each `SimpleThaliTape` instance?
> I mean to use [tape.testCreateHarness](https://github.com/substack/tape#var-htest--testcreateharness) for each `SimpleThalitape` instance.
</details>
Yes, we can implement our tape wrapper like [createHarness](https://github.com/substack/tape/blob/master/index.js#L103]) in future. I will add a todo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (276cbc3)

**Comment by ThaliTester** [comment]
Test (Fail) 85606604 build is completed (276cbc3)

See https://github.com/ThaliTester/TestResults/tree/85606604276cbc3_New_thali_tape_andrew-aladev/ for the logs

**Comment by artemjackson** [comment]
:lgtm:

---

Review status: 18 of 50 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1062#-:-KS6Siz6U-Yd4RCDMKwz:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d42e563)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (8ca4f27)

**Comment by ThaliTester** [comment]
Test (Success) 85606604 build is completed (d42e563)

See https://github.com/ThaliTester/TestResults/tree/85606604d42e563_New_thali_tape_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 85606604 build is completed (8ca4f27)

See https://github.com/ThaliTester/TestResults/tree/856066048ca4f27_New_thali_tape_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 85606604d42e563(d42e563) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/85606604d42e563_New_thali_tape_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 856066048ca4f27(8ca4f27) has failed

See https://github.com/ThaliTester/TestResults/tree/856066048ca4f27_New_thali_tape_andrew-aladev/ for the fail logs

**Pull request merged**
