### PR TITLE
Fixed problems with peer availability announcements and recreated listeners

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1458)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d68feab)

**Comment by yaronyg** [comment]
@chapko This PR includes #1458. So I would suggest reviewing that first and if it's o.k. then checking it in to master and then reviewing this PR.

**Comment by ThaliTester** [comment]
Test (Success) 91479574 build is completed (d68feab)

See https://github.com/ThaliTester/TestResults/tree/91479574d68feab_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 91479574d68feab(d68feab) has failed

See https://github.com/ThaliTester/TestResults/tree/91479574d68feab_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6e6bc70)

**Comment by ThaliTester** [comment]
Test (Success) 91479574 build is completed (6e6bc70)

See https://github.com/ThaliTester/TestResults/tree/914795746e6bc70_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 914795746e6bc70(6e6bc70) has failed

See https://github.com/ThaliTester/TestResults/tree/914795746e6bc70_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (323a717)

**Comment by ThaliTester** [comment]
Test (Success) 91479574 build is completed (323a717)

See https://github.com/ThaliTester/TestResults/tree/91479574323a717_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 91479574323a717(323a717) has failed

See https://github.com/ThaliTester/TestResults/tree/91479574323a717_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the fail logs

**Comment by chapko** [comment]
Reviewed 6 of 7 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 165 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1458#-KVPIVWt8lrHGh2Sr171:-KVPIVWt8lrHGh2Sr172:bd7akp1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/323a717caeb47dcafdb740ea67f217e46eb9511f/test/www/jxcore/bv_tests/testThaliMobile.js#L165)):*
> ```JavaScript
>     })
>     .then(function () {
>       t.equal(Object.getOwnPropertyNames(
> ```

NB: Please, use `Object.keys`. `getOwnPropertyNames` and `keys` behaviors are the same for all our cases, but `keys` is shorter, cleaner, and more recognizable.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 842 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1458#-KVPWZiHCKzfjpiP9CX8:-KVPWZiHCKzfjpiP9CX9:b7la32n) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/323a717caeb47dcafdb740ea67f217e46eb9511f/thali/NextGeneration/thaliMobileNativeWrapper.js#L842)):*
> ```JavaScript
>                                          peer.pleaseConnect)
>       .then(function (portNumber) {
>         var notAvailableEvent = {
> ```

It is not "not available" event

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1458)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f31a697)

**Comment by ThaliTester** [comment]
Test (Fail) 91479574 build is completed (f31a697)

See https://github.com/ThaliTester/TestResults/tree/91479574f31a697_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (85479cd)

**Comment by ThaliTester** [comment]
Test (Fail) 91479574 build is completed (85479cd)

See https://github.com/ThaliTester/TestResults/tree/9147957485479cd_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a8a71ff)

**Comment by ThaliTester** [comment]
Test (Fail) 91479574 build is completed (a8a71ff)

See https://github.com/ThaliTester/TestResults/tree/91479574a8a71ff_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by evabishchevich** [comment]
I tried to work on 1375 and as @yaronyg had mentioned yesterday this PR contains all the fixes for tests. 
I couldn't build this PR.
https://gist.github.com/evabishchevich/d7e2553f6ed1d153a6b8a7baa3885c67

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4640251)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4264c94)

**Comment by ThaliTester** [comment]
Test (Fail) 91479574 build is completed (4264c94)

See https://github.com/ThaliTester/TestResults/tree/914795744264c94_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by yaronyg** [comment]
All tests in all modes pass on desktop. CI is currently broken. @chapko please review the changes. I won't do any more work on this branch other than to fix bugs.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e64d32d)

**Comment by ThaliTester** [comment]
Test (Success) 91479574 build is completed (e64d32d)

See https://github.com/ThaliTester/TestResults/tree/91479574e64d32d_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 91479574e64d32d(e64d32d) has failed

See https://github.com/ThaliTester/TestResults/tree/91479574e64d32d_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6db6186)

**Comment by ThaliTester** [comment]
Test (Success) 91479574 build is completed (6db6186)

See https://github.com/ThaliTester/TestResults/tree/914795746db6186_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (8cc43db)

**Comment by ThaliTester** [comment]
Test 914795746db6186(6db6186) has failed

See https://github.com/ThaliTester/TestResults/tree/914795746db6186_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 91479574 build is completed (8cc43db)

See https://github.com/ThaliTester/TestResults/tree/914795748cc43db_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 914795748cc43db(8cc43db) has failed

See https://github.com/ThaliTester/TestResults/tree/914795748cc43db_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f589d77)

**Comment by ThaliTester** [comment]
Test (Fail) 91479574 build is completed (f589d77)

See https://github.com/ThaliTester/TestResults/tree/91479574f589d77_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5, 4 of 7 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1458#-:-KVjGmwkULgBWc8y8faf:bnfp4nl)*

**Comment by yaronyg** [comment]
thaliproject/Thali_CordovaPlugin#1483 has all the changes from this PR so I'll close this PR in favor of that one.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dc6694e)

**Comment by ThaliTester** [comment]
Test (Fail) 91479574 build is completed (dc6694e)

See https://github.com/ThaliTester/TestResults/tree/91479574dc6694e_Fixed_problems_with_peer_availability_announcements_and_recreated_listeners_yaronyg/ for the logs

**Comment by yaronyg** [comment]
NOTE: THIS PR IS DONE. IT'S ONLY STILL OPEN SO THAT REVIEWABLE.IO CAN INSPECT A BUG RELATED TO IT.

**Pull request closed without merging**
