### PR TITLE
Localhost GetDocumentsPath method update in mockmobile.js - fixes #233

### LINKED ISSUE #233: Fix localhost version of Mobile.GetMobileDocumentsPath
Postcard app is now generating string error with Mobile.GetMobileDocumentsPath in 'mockmobile.js'

```
TypeError: Arguments to path.join must be strings
```

### PR DESCRIPTION
**Pull request by deadlyfingers**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/268)

### CODE REVIEW

**Comment by vjrantal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[test/www/jxcore/bv_tests/mockmobile.js, line 23 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/268#-K26Fj_8-GFCaZxsdi4s)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84611b89d1b52af78e1ca9393919d09b6625b9ff/test/www/jxcore/bv_tests/mockmobile.js#L23)):</sup>
I believe the way this function is used is by passing is a callback function that expects an error as the first argument and the path as the second.

So, I think the better way to mock this would be something like (code not tried out):
```
setImmediate(function () {
  cb(null, os.tmpdir());
});
```

If the passed callback is never called, it might be that the caller is left in a "waiting state".


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/268)

**Comment by deadlyfingers** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[test/www/jxcore/bv_tests/mockmobile.js, line 23 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/268#-K26Fj_8-GFCaZxsdi4s)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84611b89d1b52af78e1ca9393919d09b6625b9ff/test/www/jxcore/bv_tests/mockmobile.js#L23)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/268)

**Comment by vjrantal** [comment]
I think the code looks good now.

I did not understand what "location - r1" meant in the commit message, but you can judge yourself if that should be elaborated or left as is :)


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/268)

**Comment by vjrantal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/268)

**Comment by deadlyfingers** [comment]
Was closed but never merged?
This is a MockMobile GetDocumentsPath method fix for error: `'Arguments to path.join must be strings’` when running on localhost.

**Pull request merged**
