### PR TITLE
iOS swift 3.0 migration

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1819)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4fcb1a9)

**Comment by ThaliTester** [comment]
Test 109247054 (4fcb1a9) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (4fcb1a9)

See https://github.com/ThaliTester/TestResults/tree/1092470544fcb1a9_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by yaronyg** [comment]
Please resolve comments and then :LGTM:

---

Reviewed 52 of 52 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 184 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZtE_o4q2hjIiM4nZA:-KeZtE_o4q2hjIiM4nZB:bq25cpj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L184)):*
> ```Swift
>     let disposeTimeout =
>       DispatchTime.now() +
>       Double(Int64(self.disposeTimeout * Double(NSEC_PER_SEC))) / Double(NSEC_PER_SEC)
> ```

If we multiple disposeTimeout by NSEC_PER_SEC and then divide by NSEC_PER_SEC then haven't we defeated the point of multiplying the thing int he first place?

Also why make disposeTime into an INT and then turn it back into a double?

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 128 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZuFNUn_DcpaavqcqY:-KeZuFNVbVyJ-obmRW6j:bqq72od) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L128)):*
> ```Swift
>       let streamReceivedBackTimeout =
>         DispatchTime.now() +
>         Double(Int64(self.streamReceivedBackTimeout * Double(NSEC_PER_SEC))) / Double(NSEC_PER_SEC)
> ```

Same math issues as previous comment.

---

*[src/ios/Testing/AppContextTests.swift, line 171 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZvZMfHPvZ-F-Qu4On:-KeZvZMgumv8mP5QIiE2:bahcup9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/src/ios/Testing/AppContextTests.swift#L171)):*
> ```Swift
>   static var allTests = {
>     return [
>       ("test_willEnterBackground", testWillEnterBackground),
> ```

This makes me really sad. The chance that we will correctly maintain this list seems very low. Any hope we can automate pulling in these tests?

---

*[thali/install/package.json, line 18 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZvxW5Q-i4ZVlRsIfw:-KeZvq3XK2yojcfUu5tl:bwtw1i0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/package.json#L18)):*
> ```JSON
>     "request": "2.74.0",
>     "unzip": "0.1.11",
>     "xcode": "https://github.com/alunny/node-xcode.git#4cca2f6225c391b63324e6eb53421560649d4f98"
> ```

Do we have a bug tracking why we need a specific release of node-xcode so we know how to get off? I really wish JSON supported comments. :(

---

*[thali/install/setUpTests.sh, line 22 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZwGyMbHoHFMz_O1Km:-KeZw6nViC2d1RaRNiIC:b-pmg1gv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/setUpTests.sh#L22)):*
> ```Shell
> cd ../..
> REPO_ROOT_DIR=$(pwd)
> PROJECT_NAME=${TEST_PROJECT_NAME:-ThaliTest}
> ```

If we are going to allow this to be set externally to the file as an optional environment variable then shouldn't we use a name that is more Thali specific? E.g. THALI_TEST_PROJECT_NAME rather than TEST_PROJECT_NAME. Just to avoid accidental collisions?

---

*[thali/install/setUpTests.sh, line 24 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZwXRND-zUqkG9_ijv:-KeZwXRND-zUqkG9_ijw:bb5eszk) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/setUpTests.sh#L24)):*
> ```Shell
> PROJECT_NAME=${TEST_PROJECT_NAME:-ThaliTest}
> PROJECT_ROOT_DIR=${REPO_ROOT_DIR}/../${PROJECT_NAME}
> PROJECT_ID=${TEST_PROJECT_ID:-com.thaliproject.thalitest}
> ```

Same thing here. Wouldn't THALI_TEST_PROJECT_ID be more appropriate since the variable can now be potentially set external to the file?

---

*[thali/install/setUpTests.sh, line 184 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZwrTBArwLm0-E6TFK:-KeZwrTBArwLm0-E6TFL:b53tllu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/setUpTests.sh#L184)):*
> ```Shell
>   # cd $IOS_PROJECT_DIR && \
>   # cordova build --device -d \
>   #   --buildFlag="DEVELOPMENT_TEAM=${TEST_DEVELOPMENT_TEAM:-3648SALNRR}" \
> ```

Sorry to be boring, but um, THALI_TEST_DEVELOPMENT_TEAM?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-:-KeZx9r_CVQbIl1bw0gn:b-9bs0pt)*

**Comment by jareksl** [comment]
Please update `validateBuildEnvironment.js` to reflect current settings, beside of that the build fails with `xcodebuild: error: '/Users/thali/Github/ThaliTest/plugins/org.thaliproject.p2p/lib/ios/Carthage/Checkouts/thali-ios/ThaliCore.xcodeproj' does not exist.`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-:-KeiOr4beIZst30ce1vB:bq16hhr)*

**Comment by jareksl** [comment]
Reviewed 52 of 52 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8d5282c)

**Comment by ThaliTester** [comment]
Test 109247054 (8d5282c) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (8d5282c)

See https://github.com/ThaliTester/TestResults/tree/1092470548d5282c_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by evabishchevich** [comment]
Environment is not valid. This failure will be fixed soon

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8c14202)

**Comment by ThaliTester** [comment]
Test 109247054 (8c14202) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (8c14202)

See https://github.com/ThaliTester/TestResults/tree/1092470548c14202_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fe13df4)

**Comment by ThaliTester** [comment]
Test 109247054 (fe13df4) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (fe13df4)

See https://github.com/ThaliTester/TestResults/tree/109247054fe13df4_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (75b1ce0)

**Comment by ThaliTester** [comment]
Test 109247054 (75b1ce0) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (75b1ce0)

See https://github.com/ThaliTester/TestResults/tree/10924705475b1ce0_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (eb4d7ac)

**Comment by ThaliTester** [comment]
Test 109247054 (eb4d7ac) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (eb4d7ac)

See https://github.com/ThaliTester/TestResults/tree/109247054eb4d7ac_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c6c2364)

**Comment by ThaliTester** [comment]
Test 109247054 (c6c2364) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (c6c2364)

See https://github.com/ThaliTester/TestResults/tree/109247054c6c2364_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by jareksl** [comment]
Review status: 8 of 74 files reviewed at latest revision, 8 unresolved discussions.

---

*[thali/install/validateBuildEnvironment.js, line 209 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KfFl3nROrt1_bIUzCyl:-KfFl3nSRD1DEtcr6d6u:bdktjbf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88bc2ecd1c21276afad78a83d35dce43e76f76d1/thali/install/validateBuildEnvironment.js#L209)):*
> ```JavaScript
>       (result, version) => boolToPromise(version === result.trim())
>   },
>   carthage: {
> ```

The check here does not handle cases when there is a newer version of carthage available. If you call `carthage version` it may return also information "***Please update to the latest Carthage version ...". In such case the check here fails. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by jareksl** [comment]
Review status: 8 of 74 files reviewed at latest revision, 10 unresolved discussions.

---

*[thali/install/ios/nativeInstaller.js, line 221 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KfGgRnA6HbxJfOomXcN:-KfGgRnA6HbxJfOomXcO:b-pvizb0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88bc2ecd1c21276afad78a83d35dce43e76f76d1/thali/install/ios/nativeInstaller.js#L221)):*
> ```JavaScript
> }
> 
> function biuldCocoaAsyncSocket(checkoutDir, buildDir, buildWithTests) {
> ```

There is a a typo in the name of the function. use "build" instead of "biuld"  

---

*[thali/install/ios/nativeInstaller.js, line 250 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KfGgsB1SAOfdttNPVG9:-KfGgsB1SAOfdttNPVGA:b-9nz54o) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88bc2ecd1c21276afad78a83d35dce43e76f76d1/thali/install/ios/nativeInstaller.js#L250)):*
> ```JavaScript
> }
> 
> function biuldSwiftXCTest(checkoutDir, buildDir, buildWithTests) {
> ```

The same as in the line 221, build instead of biuld

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (69839bb)

**Comment by ThaliTester** [comment]
Test 109247054 (69839bb) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (69839bb)

See https://github.com/ThaliTester/TestResults/tree/10924705469839bb_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8a224d4)

**Comment by ThaliTester** [comment]
Test 109247054 (8a224d4) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (8a224d4)

See https://github.com/ThaliTester/TestResults/tree/1092470548a224d4_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ba6e0c6)

**Comment by ThaliTester** [comment]
Test 109247054 (ba6e0c6) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (ba6e0c6)

See https://github.com/ThaliTester/TestResults/tree/109247054ba6e0c6_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c2caefb)

**Comment by ThaliTester** [comment]
Test 109247054 (c2caefb) build started.

**Comment by ThaliTester** [comment]
Test (Success) 109247054 build is completed (c2caefb)

See https://github.com/ThaliTester/TestResults/tree/109247054c2caefb_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by evabishchevich** [comment]
Review status: 4 of 75 files reviewed at latest revision, 11 unresolved discussions.

---

*[thali/install/ios/nativeInstaller.js, line 169 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KfRFQcAYtmsKz-EXqwv:-KfRFQcAYtmsKz-EXqww:b-jat5gg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c2caefb6e70e0cd0aa088ad82e88e809db17ac50/thali/install/ios/nativeInstaller.js#L169)):*
> ```JavaScript
>   // This time they will have the code-sign option set
>   // so they get code signed when being deployed to devices.
>   // if (buildWithTests) {
> ```

Do we still need this code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by yaronyg** [comment]
Comments have still not been resolved. Please resolve them. Then :LGTM:

---

Reviewed 63 of 64 files at r6, 4 of 8 files at r7, 4 of 4 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 184 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZtE_o4q2hjIiM4nZA:-KfSvDhiumkX-TGWXVft:b-u1jc3e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L184)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

If we multiple disposeTimeout by NSEC_PER_SEC and then divide by NSEC_PER_SEC then haven't we defeated the point of multiplying the thing int he first place?

Also why make disposeTime into an INT and then turn it back into a double?
</blockquote></details>

I know this file is deleted but how was this issue resolved?

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 128 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZuFNUn_DcpaavqcqY:-KfSvLhtMRT1iSpEzITC:b-rm5iyj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L128)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Same math issues as previous comment.
</blockquote></details>

Also, how was this issue resolved?

---

*[src/ios/Testing/AppContextTests.swift, line 171 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZvZMfHPvZ-F-Qu4On:-KfSw1IypVUa6O-8N9yj:bxmb9be) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/src/ios/Testing/AppContextTests.swift#L171)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

This makes me really sad. The chance that we will correctly maintain this list seems very low. Any hope we can automate pulling in these tests?
</blockquote></details>

Please respond.

---

*[thali/install/setUpTests.sh, line 184 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZwrTBArwLm0-E6TFK:-KfSwHrC-8FjpId64wUU:b-8m6byf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/setUpTests.sh#L184)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Sorry to be boring, but um, THALI_TEST_DEVELOPMENT_TEAM?
</blockquote></details>

You fixed the previous two, why not this one? Is this a reserved value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-:-KfSwlRelsSI2KnJHK5Q:b-h8quqd)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d2009a0)

**Comment by ThaliTester** [comment]
Test 109247054 (d2009a0) build started.

**Comment by dersim-davaod** [comment]
Review status: 73 of 75 files reviewed at latest revision, 11 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 184 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZtE_o4q2hjIiM4nZA:-Kecle-d7T2moieGooxm:bw0v4gf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L184)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I know this file is deleted but how was this issue resolved?
</blockquote></details>

This code was a result of migration tool.
When code was updated, I've replaced type of local `disposeTimeout` from TimeInterval to DispatchTimeInterval.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 128 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZuFNUn_DcpaavqcqY:-Kecw1xDdhYOYQ8f_0jb:b-6vvgbo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L128)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Also, how was this issue resolved?
</blockquote></details>

Code was updated as well.

---

*[src/ios/Testing/AppContextTests.swift, line 171 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZvZMfHPvZ-F-Qu4On:-KffZL292TavfPH2PLB3:bahoia7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/src/ios/Testing/AppContextTests.swift#L171)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Please respond.
</blockquote></details>

Sure, will create a simple script to do this. (new issue #1834)https://github.com/thaliproject/Thali_CordovaPlugin/issues/1834

---

*[thali/install/package.json, line 18 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZvxW5Q-i4ZVlRsIfw:-KffYBIOvGJAgF0Skd_u:b-zecgwn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/package.json#L18)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Do we have a bug tracking why we need a specific release of node-xcode so we know how to get off? I really wish JSON supported comments. :(
</blockquote></details>

I've created #1833. Will investigate it today.

---

*[thali/install/setUpTests.sh, line 22 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZwGyMbHoHFMz_O1Km:-Kes-SgSiN-btQhyIexO:b8j4crn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/setUpTests.sh#L22)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

If we are going to allow this to be set externally to the file as an optional environment variable then shouldn't we use a name that is more Thali specific? E.g. THALI_TEST_PROJECT_NAME rather than TEST_PROJECT_NAME. Just to avoid accidental collisions?
</blockquote></details>

Absolutely agree, fixed.

---

*[thali/install/setUpTests.sh, line 24 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZwXRND-zUqkG9_ijv:-Kes-WW8IHOC1EgalktG:b8j4crn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/setUpTests.sh#L24)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Same thing here. Wouldn't THALI_TEST_PROJECT_ID be more appropriate since the variable can now be potentially set external to the file?
</blockquote></details>

Absolutely agree, fixed.

---

*[thali/install/setUpTests.sh, line 184 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KeZwrTBArwLm0-E6TFK:-Kes-dZOOeRzps5M7SST:bj3eoea) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fcb1a955423f16a1c3909c7ff3f89b3a062bc86/thali/install/setUpTests.sh#L184)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

You fixed the previous two, why not this one? Is this a reserved value?
</blockquote></details>

Fixed, thanks.

---

*[thali/install/validateBuildEnvironment.js, line 209 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KfFl3nROrt1_bIUzCyl:-KffWtCQTZlKeQlhWdWe:bt2vr1b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88bc2ecd1c21276afad78a83d35dce43e76f76d1/thali/install/validateBuildEnvironment.js#L209)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

The check here does not handle cases when there is a newer version of carthage available. If you call `carthage version` it may return also information "***Please update to the latest Carthage version ...". In such case the check here fails. 
</blockquote></details>

Fixed.

---

*[thali/install/ios/nativeInstaller.js, line 221 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KfGgRnA6HbxJfOomXcN:-KffWJYbgodhuk5YrXgp:bt2vr1b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88bc2ecd1c21276afad78a83d35dce43e76f76d1/thali/install/ios/nativeInstaller.js#L221)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

There is a a typo in the name of the function. use "build" instead of "biuld"  
</blockquote></details>

Fixed.

---

*[thali/install/ios/nativeInstaller.js, line 250 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KfGgsB1SAOfdttNPVG9:-KffWKQIpZWlt7-OfDAK:bt2vr1b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/88bc2ecd1c21276afad78a83d35dce43e76f76d1/thali/install/ios/nativeInstaller.js#L250)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

The same as in the line 221, build instead of biuld
</blockquote></details>

Fixed.

---

*[thali/install/ios/nativeInstaller.js, line 169 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-KfRFQcAYtmsKz-EXqwv:-KffVzrNzV4L4vgukCmI:byff8wh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c2caefb6e70e0cd0aa088ad82e88e809db17ac50/thali/install/ios/nativeInstaller.js#L169)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

Do we still need this code?
</blockquote></details>

Commented code was removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (14f1591)

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (d2009a0)

See https://github.com/ThaliTester/TestResults/tree/109247054d2009a0_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 109247054 (14f1591) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 109247054 build is completed (14f1591)

See https://github.com/ThaliTester/TestResults/tree/10924705414f1591_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 109247054c2caefb(c2caefb) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/109247054c2caefb_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-:-Kfg_4eY825gDw6RgvKN:bnfp4nl)*

**Comment by jareksl** [comment]
*[thali/install/setUpTests.sh, line 180 at r12](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-Kfjk5GoA_jasgHrE6ib:-Kfjk5GoA_jasgHrE6ic:bjrp0rv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/14f1591db5b6e5b9238cd4f828abea4976a0cea6/thali/install/setUpTests.sh#L180)):*
> ```Shell
>     cordova prepare ios --device
> 
>   # TODO: we need new cordova release to make it work
> ```

The commented code here is not needed and apart of that it contains wrong environment variables

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by jareksl** [comment]
Tests from the above finished successfully but there were no real devices connected. Now, as the build environment is adjusted to reflect the settings used in the build script and the real devices are connected, please rerun tests again.
:lgtm:  

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-:-KfjhZ67ARrJsbTNDR0M:b-usb409)*

**Comment by jareksl** [comment]
Reviewed 1 of 64 files at r6, 1 of 8 files at r7, 1 of 1 files at r10, 1 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a32d624)

**Comment by ThaliTester** [comment]
Test 109247054 (a32d624) build started.

**Comment by dersim-davaod** [comment]
Review status: 74 of 75 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/install/setUpTests.sh, line 180 at r12](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819#-Kfjk5GoA_jasgHrE6ib:-KfkVKNipo6blk-956_2:bt2vr1b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/14f1591db5b6e5b9238cd4f828abea4976a0cea6/thali/install/setUpTests.sh#L180)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

The commented code here is not needed and apart of that it contains wrong environment variables
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by jareksl** [comment]
Reviewed 61 of 64 files at r6, 3 of 8 files at r7, 3 of 4 files at r9, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by ThaliTester** [comment]
Test (Success) 109247054 build is completed (a32d624)

See https://github.com/ThaliTester/TestResults/tree/109247054a32d624_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 109247054a32d624(a32d624) has failed

See https://github.com/ThaliTester/TestResults/tree/109247054a32d624_iOS_swift_3_0_migration_dersim-davaod/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1819)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fc76087)

**Comment by ThaliTester** [comment]
Test 109247054 (fc76087) build started.

**Comment by ThaliTester** [comment]
Test (Success) 109247054 build is completed (fc76087)

See https://github.com/ThaliTester/TestResults/tree/109247054fc76087_iOS_swift_3_0_migration_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 109247054fc76087(fc76087) has failed

See https://github.com/ThaliTester/TestResults/tree/109247054fc76087_iOS_swift_3_0_migration_dersim-davaod/ for the fail logs

**Pull request merged**
