### PR TITLE
Fix an inaccuracy with data rate reporting

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/421)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a2306df)

**Comment by ThaliTester** [comment]
Test (Success) 55311151 build is completed (a2306df)

See https://github.com/ThaliTester/TestResults/tree/55311151a2306df_Fix_an_inaccuracy_with_data_rate_reporting_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 55311151a2306df(a2306df) has failed

See https://github.com/ThaliTester/TestResults/tree/55311151a2306df_Fix_an_inaccuracy_with_data_rate_reporting_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (18861c0)

**Comment by ThaliTester** [comment]
Test (Success) 55311151 build is completed (18861c0)

See https://github.com/ThaliTester/TestResults/tree/5531115118861c0_Fix_an_inaccuracy_with_data_rate_reporting_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5531115118861c0(18861c0) has failed

See https://github.com/ThaliTester/TestResults/tree/5531115118861c0_Fix_an_inaccuracy_with_data_rate_reporting_vjrantal/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/421)*

**Pull request merged**
