### PR TITLE
Update forever-agent to the newest version

### LINKED ISSUE #1771: testThaliMangerCoordinated randomly fails with timeout in wifi mode
Happens on both android and iOS devices.

Example of logs from iOS: https://gist.github.com/enricogior/656ade9ebc443a4248e2d4237abbb3e8
Branch: `iOS` (c52ce6d79d1ced9ada005967f9ef5edf3e0147d1)

### PR DESCRIPTION
**Pull request by chapko**
Forever agent with thaliproject/forever-agent#1 fix.
Fixes #1771 and #1744
See details in the [comments to #1744](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1744#issuecomment-277996480)

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1777)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b761218)

**Comment by ThaliTester** [comment]
Test 105054410 (b761218) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 105054410 build is completed (b761218)

See https://github.com/ThaliTester/TestResults/tree/105054410b761218_Update_forever-agent_to_the_newest_version_chapko/ for the logs

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1777#-:-KcRg6ht8UBqqlmK3T1w:bnfp4nl)*

**Pull request merged**
