### PR TITLE
Fixed typo: 'connect' -> 'multiConnect'

### PR DESCRIPTION
**Pull request by artemjackson**
Line 58, last word was `connect` but should be `multiConnect`.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1093)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (75a1490)

**Comment by artemjackson** [comment]
And by the way
> Node layer MUST NOT issue a `multiConnect` or `disconnect` for that peerID until it gets a response to the previous request. For example, if the Node layer fires off a `multiConnect` for a PeerID foo and then changes its mind and wants to fire off a `disconnect`, it cannot issue the `disconnect` for the peerID until the `multiConnect` for that peerID has returned.

Shouldn't the Native layer be responsible for queuing and handling requests from Node layer?

**Comment by ThaliTester** [comment]
Test (Success) 85967149 build is completed (75a1490)

See https://github.com/ThaliTester/TestResults/tree/8596714975a1490_Fixed_typo___connect__-___multiConnect__artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8596714975a1490(75a1490) has failed

See https://github.com/ThaliTester/TestResults/tree/8596714975a1490_Fixed_typo___connect__-___multiConnect__artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1093#-:-KS8clRlhdFioBS85kkf:bnfp4nl)*

**Pull request merged**
