### PR TITLE
ThaliTcpServersManager.terminateOutgoingConnection

### PR DESCRIPTION
**Pull request by yaronyg**
testCreatePeerListener - linting

testThaliTcpServersManager - Added test to make sure terminate outgoing
connection behaves itself

createPeerListener - Restructured so we can get to the closeServer method

thaliTcpServersManager - Added code for terminateOutgoingConnection

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1398)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d42d533)

**Comment by ThaliTester** [comment]
Test (Success) 90291773 build is completed (d42d533)

See https://github.com/ThaliTester/TestResults/tree/90291773d42d533_ThaliTcpServersManager_terminateOutgoingConnection_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 90291773d42d533(d42d533) has failed

See https://github.com/ThaliTester/TestResults/tree/90291773d42d533_ThaliTcpServersManager_terminateOutgoingConnection_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fa7550b)

**Comment by ThaliTester** [comment]
Test (Success) 90291773 build is completed (fa7550b)

See https://github.com/ThaliTester/TestResults/tree/90291773fa7550b_ThaliTcpServersManager_terminateOutgoingConnection_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 90291773fa7550b(fa7550b) has failed

See https://github.com/ThaliTester/TestResults/tree/90291773fa7550b_ThaliTcpServersManager_terminateOutgoingConnection_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7e367b4)

**Comment by ThaliTester** [comment]
Test (Success) 90291773 build is completed (7e367b4)

See https://github.com/ThaliTester/TestResults/tree/902917737e367b4_ThaliTcpServersManager_terminateOutgoingConnection_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 902917737e367b4(7e367b4) has failed

See https://github.com/ThaliTester/TestResults/tree/902917737e367b4_ThaliTcpServersManager_terminateOutgoingConnection_yaronyg/ for the fail logs

**Comment by chapko** [comment]
@yaronyg these changes are included in #1399 and has been already reviewed. I think this PR can be closed then.

**Pull request merged**
