### PR TITLE
Story 001 tompaana 354

### PR DESCRIPTION
**Pull request by tompaana**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/389)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9813e59)

**Comment by ThaliTester** [comment]
Test (Success) 53978663 build is completed (9813e59)

See https://github.com/ThaliTester/TestResults/tree/539786639813e59_Story_001_tompaana_354_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 539786639813e59(9813e59) has failed

See https://github.com/ThaliTester/TestResults/tree/539786639813e59_Story_001_tompaana_354_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7913587)

**Comment by ThaliTester** [comment]
Test (Success) 53978663 build is completed (7913587)

See https://github.com/ThaliTester/TestResults/tree/539786637913587_Story_001_tompaana_354_tompaana/ for the logs

**Comment by tobybrad** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 399 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/389#-K5p5sFcus7jDpskVzai:-K5p5sFcus7jDpskVzaj:-1860185196) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/791358709be798517160fa8f8083a54b2b257fab/src/android/java/io/jxcore/node/ConnectionHelper.java#L399)):*
INSECURE not INSERCURE

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/389)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3aa3ea0)

**Comment by tompaana** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 399 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/389#-K5p5sFcus7jDpskVzai:-K5p9aonh1qNGW8bMaJk:-497468049) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/791358709be798517160fa8f8083a54b2b257fab/src/android/java/io/jxcore/node/ConnectionHelper.java#L399)):*
Fixed

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/389)*

**Comment by ThaliTester** [comment]
Test (Success) 53978663 build is completed (3aa3ea0)

See https://github.com/ThaliTester/TestResults/tree/539786633aa3ea0_Story_001_tompaana_354_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 539786637913587(7913587) has failed

See https://github.com/ThaliTester/TestResults/tree/539786637913587_Story_001_tompaana_354_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
Test 539786633aa3ea0(3aa3ea0) has failed

See https://github.com/ThaliTester/TestResults/tree/539786633aa3ea0_Story_001_tompaana_354_tompaana/ for the fail logs

**Pull request merged**
