### PR TITLE
More Wifi infrastructure features

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/496)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (846ce9d)

**Comment by vjrantal** [comment]
@yaronyg: I was a little bit uncomfortable implementing the "skip queue" like this https://github.com/thaliproject/Thali_CordovaPlugin/commit/d128e9f3d4082d3b03ed0a4d0ca317096769f5f0#diff-18b3a87646f602a18d6c19ce0aa9c09dR262 but I didn't see another easy alternative how to implement a case where some public function needs call other public functions in this same file. The issue was that when all stop-related calls were using the global promise queue, the "sub-stops" never finished since they were put behind the "parent-stop" in the queue.

The way I did it might be good enough, but if you have ideas on a better pattern, please suggest. I think this case comes up in other files as well.

**Comment by ThaliTester** [comment]
Test (Success) 57348078 build is completed (846ce9d)

See https://github.com/ThaliTester/TestResults/tree/57348078846ce9d_More_Wifi_infrastructure_features_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 57348078846ce9d(846ce9d) has failed

See https://github.com/ThaliTester/TestResults/tree/57348078846ce9d_More_Wifi_infrastructure_features_vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
@yaronyg: We yesterday discussed that I'd check that sinon works on devices and from the CI run above, we can see that a test using sinon passed on Android. We didn't get a result on iOS, because the tests tend to get stuck for other reasons - see https://github.com/thaliproject/Thali_CordovaPlugin/issues/483.

**Comment by yaronyg** [comment]
In regards to skipPromiseQueue this is a posterchild for what private functions are about. We would have a "_" version of the various stop methods that can be called without being enqueued and a public version that is always enqueued. When someone calls a top level stop on a public interface that would then call the baby stops using the private interface. And of course the public version of the baby stop (that has the queue logic) would just call the private version when it got to its place in line.

In regards to Sinon if you got it working on Android then it should work everywhere and we can use it. Which is great, one less thing to invent! Thanks for pointing this out and experimenting with it.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9efee08)

**Comment by ThaliTester** [comment]
Test (Success) 57348078 build is completed (9efee08)

See https://github.com/ThaliTester/TestResults/tree/573480789efee08_More_Wifi_infrastructure_features_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 573480789efee08(9efee08) has failed

See https://github.com/ThaliTester/TestResults/tree/573480789efee08_More_Wifi_infrastructure_features_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4751f5c)

**Comment by ThaliTester** [comment]
Test (Success) 57348078 build is completed (4751f5c)

See https://github.com/ThaliTester/TestResults/tree/573480784751f5c_More_Wifi_infrastructure_features_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 573480784751f5c(4751f5c) has failed

See https://github.com/ThaliTester/TestResults/tree/573480784751f5c_More_Wifi_infrastructure_features_vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/496)*

**Pull request merged**
