### PR TITLE
New peer generation (894)

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1518)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (30f5d57)

**Comment by ThaliTester** [comment]
Test (Fail) 93572167 build is completed (30f5d57)

See https://github.com/ThaliTester/TestResults/tree/9357216730f5d57_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (30f5d57)

**Comment by ThaliTester** [comment]
Test (Fail) 93572167 build is completed (30f5d57)

See https://github.com/ThaliTester/TestResults/tree/9357216730f5d57_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (83aa1f1)

**Comment by ThaliTester** [comment]
Test (Fail) 93572167 build is completed (83aa1f1)

See https://github.com/ThaliTester/TestResults/tree/9357216783aa1f1_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (017e1b9)

**Comment by ThaliTester** [comment]
Test (Fail) 93572167 build is completed (017e1b9)

See https://github.com/ThaliTester/TestResults/tree/93572167017e1b9_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2ab3d11)

**Comment by ThaliTester** [comment]
Test (Fail) 93572167 build is completed (2ab3d11)

See https://github.com/ThaliTester/TestResults/tree/935721672ab3d11_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (fd0bc1d)

**Comment by ThaliTester** [comment]
Test (Success) 93572167 build is completed (fd0bc1d)

See https://github.com/ThaliTester/TestResults/tree/93572167fd0bc1d_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 93572167fd0bc1d(fd0bc1d) has failed

See https://github.com/ThaliTester/TestResults/tree/93572167fd0bc1d_New_peer_generation__894__evabishchevich/ for the fail logs

**Comment by larryonoff** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 734 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlalDtFwChZ4bpT0Qr:-KWlalDtFwChZ4bpT0Qs:b-jbvv9e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/src/android/java/io/jxcore/node/ConnectionHelper.java#L734)):*
> ```Java
>                     @Override
>                     public void onDisconnected(SocketThreadBase who, Exception exception) {
>                         //No need to implement
> ```

this comment confuses me. Please provide more details.

---

*[src/android/test/io/jxcore/node/ListenerMock.java, line 26 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlb-lMlAL2PRBevK-T:-KWlb-lMlAL2PRBevK-U:b-oub88y) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/src/android/test/io/jxcore/node/ListenerMock.java#L26)):*
> ```Java
> 
>     @Override
>     public void onDone(SocketThreadBase who, boolean threadDoneWasSending){
> ```

please add space between `){`.

---

*[thali/install/cordova-hooks/android/after_plugin_install.js, line 27 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlbNib-EbLLAuS5Qw-:-KWlbNib-EbLLAuS5Qw0:b-aw3ukc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/thali/install/cordova-hooks/android/after_plugin_install.js#L27)):*
> ```JavaScript
>  */
> 
> var updateAndroidSDKVersion = function (appRoot) {
> ```

do we need this? I thought it was removed since specific reason. I think @yarong knows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (29ac2d0)

**Comment by ThaliTester** [comment]
Test (Success) 93572167 build is completed (29ac2d0)

See https://github.com/ThaliTester/TestResults/tree/9357216729ac2d0_New_peer_generation__894__evabishchevich/ for the logs

**Comment by vasilevskayaem** [comment]
Reviewed 1 of 11 files at r1.
Review status: 1 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 631 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWm28bI7wfSstTN7pXM:-KWm28bI7wfSstTN7pXN:b3x1929) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/29ac2d06502176304c3de49e32bfb507446724b2/src/android/java/io/jxcore/node/ConnectionHelper.java#L631)):*
> ```Java
>                         && ((ErrnoException) exception.getCause()).errno == OsConstants.EMFILE) {
>                         callback.callOnConnectCallback(NO_AVAILABLE_PORTS, null);
>                         closeAndRemoveOutgoingThread(who.getPeerProperties().getId());
> ```

We call closeAndRemoveOutgoingThread in if and in else block (in onDisconnected call), can we just move call closeAndRemoveOutgoingThread after if check and remove else with onDisconnected call

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518)*

**Comment by ThaliTester** [comment]
Test 9357216729ac2d0(29ac2d0) has failed

See https://github.com/ThaliTester/TestResults/tree/9357216729ac2d0_New_peer_generation__894__evabishchevich/ for the fail logs

**Comment by vasilevskayaem** [comment]
Review status: 1 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 734 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlalDtFwChZ4bpT0Qr:-KWmA_KtUhX09JgP2DJ8:b-ep40v5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/src/android/java/io/jxcore/node/ConnectionHelper.java#L734)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> this comment confuses me. Please provide more details.
</details>
app never call this callback in IncomingSocketThread , but it's better to add onDisconnected(who, exception.getMessage()) as default implementation, just in case if someone decide to call it somewhere by mistake for example

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518)*

**Comment by larryonoff** [comment]
Review status: 1 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 734 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlalDtFwChZ4bpT0Qr:-KWmBtnFkU-UrLhm0XEx:by6wmst) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/src/android/java/io/jxcore/node/ConnectionHelper.java#L734)):*
<details><summary><i>Previously, vasilevskayaem wrote…</i></summary>
> app never call this callback in IncomingSocketThread , but it's better to add onDisconnected(who, exception.getMessage()) as default implementation, just in case if someone decide to call it somewhere by mistake for example
</details>
please just add better comment into the code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518)*

**Comment by evabishchevich** [comment]
Review status: 1 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[thali/install/cordova-hooks/android/after_plugin_install.js, line 27 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlbNib-EbLLAuS5Qw-:-KWmDX6APjB1WGfsT83m:btidjpj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/thali/install/cordova-hooks/android/after_plugin_install.js#L27)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> do we need this? I thought it was removed since specific reason. I think @yarong knows.
</details>
we have that in master. Without this function we get error while building the app about minSdkVersion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518)*

**Comment by larryonoff** [comment]
Review status: 1 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[thali/install/cordova-hooks/android/after_plugin_install.js, line 27 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlbNib-EbLLAuS5Qw-:-KWmFpPdgsGEGB6sWVvQ:b-u03553) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/thali/install/cordova-hooks/android/after_plugin_install.js#L27)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary>
> we have that in master. Without this function we get error while building the app about minSdkVersion
</details>
please talk to @yarong about this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518)*

**Comment by evabishchevich** [comment]
Review status: 1 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 734 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlalDtFwChZ4bpT0Qr:-KWmKqlV78T3ean9eAD8:bs7wumx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/src/android/java/io/jxcore/node/ConnectionHelper.java#L734)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> please just add better comment into the code
</details>
Done. 

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 631 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWm28bI7wfSstTN7pXM:-KWmJzh8XV49uXBR21FG:b2495bw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/29ac2d06502176304c3de49e32bfb507446724b2/src/android/java/io/jxcore/node/ConnectionHelper.java#L631)):*
<details><summary><i>Previously, vasilevskayaem wrote…</i></summary>
> We call closeAndRemoveOutgoingThread in if and in else block (in onDisconnected call), can we just move call closeAndRemoveOutgoingThread after if check and remove else with onDisconnected call
</details>
The idea was about processing only Errno exceptions and perform default implementation in other cases. We will have to change 2 methods if we want to change just default implementation. Don't think that it's good idea but I will implement it in a clearer way

---

*[src/android/test/io/jxcore/node/ListenerMock.java, line 26 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlb-lMlAL2PRBevK-T:-KWmGLw625Y9qsEkNeF0:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/src/android/test/io/jxcore/node/ListenerMock.java#L26)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> please add space between `){`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (2ca5349)

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-:-KWmOVAzjYHgTOahFlN3:bnfp4nl)*

**Comment by vasilevskayaem** [comment]
:lgtm:

---

Reviewed 9 of 11 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-:-KWmQW0Hp2UKNPESKELj:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 93572167 build is completed (2ca5349)

See https://github.com/ThaliTester/TestResults/tree/935721672ca5349_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 935721672ca5349(2ca5349) has failed

See https://github.com/ThaliTester/TestResults/tree/935721672ca5349_New_peer_generation__894__evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
Please fix the key problems identified below. Then :lgtm:

---

Reviewed 8 of 11 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 87 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq-t6ySGzpMR_1t8eV:-KWq-t6ySGzpMR_1t8eW:b-e2um9x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/src/android/java/io/jxcore/node/JXcoreExtension.java#L87)):*
> ```Java
> 
> 
>     private static String ERROR_PLATFORM_DOES_NOT_SUPPORT_CONNECT = "Platform does not support connect";
> ```

This is the wrong way around. Multiconnect is supported by iOS. It's Android that supports connect! But in any case you need two errors, one for multiconnect and a separate one for disconnect because they are required to return different strings.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 346 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq0jaw9_RuZgNVk4dW:-KWq0jaw9_RuZgNVk4dX:bovxnli) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/src/android/java/io/jxcore/node/JXcoreExtension.java#L346)):*
> ```Java
>                 ArrayList<Object> args = new ArrayList<Object>();
> 
>                 args.add(ERROR_PLATFORM_DOES_NOT_SUPPORT_CONNECT);
> ```

The spec in thaliMobileNative.js says that this must return the error 'Platform does not support multiConnect'

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 357 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq0OIPzmPp5FvdHIo6:-KWq0OIQaYh09xCDMOe1:bjejmga) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/src/android/java/io/jxcore/node/JXcoreExtension.java#L357)):*
> ```Java
>                 ArrayList<Object> args = new ArrayList<Object>();
> 
>                 args.add(ERROR_PLATFORM_DOES_NOT_SUPPORT_CONNECT);
> ```

The spec in thaliMobileNative.js says this should return 'Not multiConnect platform'

---

*[src/android/java/io/jxcore/node/OutgoingSocketThread.java, line 8 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq0up4y-D7902adt-5:-KWq0up5Z24jL1kqAPyj:b-cnnrfu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/src/android/java/io/jxcore/node/OutgoingSocketThread.java#L8)):*
> ```Java
> import android.bluetooth.BluetoothSocket;
> import android.system.Os;
> import android.system.OsConstants;
> ```

Is this or android.system.Os actually used in this file?

---

*[thali/install/cordova-hooks/android/after_plugin_install.js, line 27 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlbNib-EbLLAuS5Qw-:-KWq18qsHKvztbxt9YGT:b64p1a9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/thali/install/cordova-hooks/android/after_plugin_install.js#L27)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> please talk to @yarong about this.
</details>
This was removed because we now use the environment variables honored by Cordova. This is one of the things that validateBuildEnvironment.js checks for. It would have told you that your build environment was missing key environment variables. So this whole section must be removed.

---

*[thali/install/cordova-hooks/android/after_plugin_install.js, line 193 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq1O-WU-EOIEqg_YPk:-KWq1O-WU-EOIEqg_YPl:b-f854hy) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/thali/install/cordova-hooks/android/after_plugin_install.js#L193)):*
> ```JavaScript
> module.exports = function (context) {
>   var appRoot = context.opts.projectRoot;
>   updateAndroidSDKVersion(appRoot);
> ```

This call needs to be removed too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-:-KWq1V0Z3Gjv0cH-kBfA:b-pvedv3)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (3826bc6)

**Comment by evabishchevich** [comment]
Review status: 7 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 87 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq-t6ySGzpMR_1t8eV:-KX68HPg2qr3275vE5tj:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/src/android/java/io/jxcore/node/JXcoreExtension.java#L87)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> This is the wrong way around. Multiconnect is supported by iOS. It's Android that supports connect! But in any case you need two errors, one for multiconnect and a separate one for disconnect because they are required to return different strings.
</details>
Done.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 346 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq0jaw9_RuZgNVk4dW:-KX68EYH_J1UnxV0Rdj7:bvks5yd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/src/android/java/io/jxcore/node/JXcoreExtension.java#L346)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> The spec in thaliMobileNative.js says that this must return the error 'Platform does not support multiConnect'
</details>
Done. There was a different spec when I was implementing that =)

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 357 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq0OIPzmPp5FvdHIo6:-KX68tZVkneS-8JFmswo:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/src/android/java/io/jxcore/node/JXcoreExtension.java#L357)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> The spec in thaliMobileNative.js says this should return 'Not multiConnect platform'
</details>
Done.

---

*[src/android/java/io/jxcore/node/OutgoingSocketThread.java, line 8 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq0up4y-D7902adt-5:-KX69E4XIB8Jky6MvJt7:bhlgql8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/src/android/java/io/jxcore/node/OutgoingSocketThread.java#L8)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Is this or android.system.Os actually used in this file?
</details>
No, they don't.

---

*[thali/install/cordova-hooks/android/after_plugin_install.js, line 27 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWlbNib-EbLLAuS5Qw-:-KX6A_2N986N3-8q0DHJ:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fd0bc1d345180b9cadd30123da47edd7cc7ee7a5/thali/install/cordova-hooks/android/after_plugin_install.js#L27)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> This was removed because we now use the environment variables honored by Cordova. This is one of the things that validateBuildEnvironment.js checks for. It would have told you that your build environment was missing key environment variables. So this whole section must be removed.
</details>
Done.

---

*[thali/install/cordova-hooks/android/after_plugin_install.js, line 193 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518#-KWq1O-WU-EOIEqg_YPk:-KX6AXud7qsPQYyoguuI:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2ca534977e25bed5ad6350bce61518f8011fa0b4/thali/install/cordova-hooks/android/after_plugin_install.js#L193)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> This call needs to be removed too.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1518)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (2bafbe2)

**Comment by ThaliTester** [comment]
Test 93572167 (3826bc6) build started.

**Comment by ThaliTester** [comment]
Test 93572167 (2bafbe2) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93572167 build is completed (3826bc6)

See https://github.com/ThaliTester/TestResults/tree/935721673826bc6_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (9a8c53b)

**Comment by ThaliTester** [comment]
Test (Success) 93572167 build is completed (2bafbe2)

See https://github.com/ThaliTester/TestResults/tree/935721672bafbe2_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 93572167 (9a8c53b) build started.

**Comment by ThaliTester** [comment]
Test (Success) 93572167 build is completed (9a8c53b)

See https://github.com/ThaliTester/TestResults/tree/935721679a8c53b_New_peer_generation__894__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 935721672bafbe2(2bafbe2) has failed

See https://github.com/ThaliTester/TestResults/tree/935721672bafbe2_New_peer_generation__894__evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
Test 935721679a8c53b(9a8c53b) has failed

See https://github.com/ThaliTester/TestResults/tree/935721679a8c53b_New_peer_generation__894__evabishchevich/ for the fail logs

**Pull request merged**
