### PR TITLE
Story 00 tobybrad

### PR DESCRIPTION
**Pull request by tobybrad**
Put some in order into test regime, adapt existing tests to co-ordinator driven framework.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/132)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[test/www/jxcore/bv_tests/testThaliReplicationManager.js, line 102 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-JzkYYyhk3iTpBGf0orj)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7fca810f85041b97974eec86b3e9f08b5b0182cc/test/www/jxcore/bv_tests/testThaliReplicationManager.js#L102)):</sup>
nit: /sucesfully/successfully

---

<sup>**[test/www/jxcore/bv_tests/testThaliReplicationManager.js, line 110 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-JzkYmaU9cjYtP0x0hxH)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7fca810f85041b97974eec86b3e9f08b5b0182cc/test/www/jxcore/bv_tests/testThaliReplicationManager.js#L110)):</sup>
fyi: PouchDB actually supports promises which in general can be nicer but in this case would make absolutely no difference what so ever.

---

<sup>**[test/www/jxcore/bv_tests/testThaliReplicationManager.js, line 193 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-JzkZKq3KT9kAgp2vLnR)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7fca810f85041b97974eec86b3e9f08b5b0182cc/test/www/jxcore/bv_tests/testThaliReplicationManager.js#L193)):</sup>
nit: I think it's more idiomatic to use 'null' when you mean 'not truthy' in Javascript land. Also rather than doing all this fancy formatting you really can just stick "doc with error: " + err and get a similar result without the extra line of code. :)

---

<sup>**[test/www/jxcore/bv_tests/testThaliReplicationManager.js, line 204 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-Jzk_FDTIgRMFdhG82dD)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7fca810f85041b97974eec86b3e9f08b5b0182cc/test/www/jxcore/bv_tests/testThaliReplicationManager.js#L204)):</sup>
Is there any reason to have this line or the bodyParser lines? express-pouchcb includes everything it needs. I think these lines were just there because the postcard app was doing some additional stuff.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132)

**Comment by yaronyg** [comment]
Review status: 26 of 31 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[test/www/jxcore/bv_tests/testThaliReplicationManager.js, line 20 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K--jX0diabUbxJA-L9w)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/bv_tests/testThaliReplicationManager.js#L20)):</sup>
As near as I can tell tape is never actually defined!

---

<sup>**[test/www/jxcore/lib/thali-tape.js, line 25 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K--kR_MLEs4EhZlu_V3)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/lib/thali-tape.js#L25)):</sup>
How would this location work? Does it assume that the serveraddress.json file is in the lib folder? I thought it was supposed to be in the jxcore parent folder?

---

<sup>**[test/www/jxcore/lib/thali-tape.js, line 49 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K--mnHhkn4o4NjUGhz5)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/lib/thali-tape.js#L49)):</sup>
/runnign/running

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132)

**Comment by yaronyg** [comment]
Review status: 26 of 31 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[test/www/jxcore/bv_tests/testThaliReplicationManager.js, line 23 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K--tRAsafbS9vU0g7ul)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/bv_tests/testThaliReplicationManager.js#L23)):</sup>
Where is the require for mockMobile?

---

<sup>**[test/www/jxcore/lib/CoordinatorConnector.js, line 11 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K--oyS9582L9vDA4kSB)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/lib/CoordinatorConnector.js#L11)):</sup>
This isn't really idiomatic, although technically it is correct. If you look online you will generally find that all emitters follow the exact same pattern.

```Javascript
var EventEmitter = require('events').EventEmitter;
var inherits = require('util').inherits;

inherits(CoordinatorConnector, EventEmitter);

All of your code goes here

function CoordinatorConnect() {
    EventEmitter.call(this);
}
```

See, for example, [here](https://nodejs.org/docs/latest/api/events.html#events_inheriting_from_eventemitter). Note however that I've learned the hard way to put the inherits statement at the top, not the bottom as in the linked examples, because otherwise inherits will override the prototypes you define.

---

<sup>**[test/www/jxcore/UnitTest_app.js, line 78 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K--r5wWzBgmiYblj3Gi)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/UnitTest_app.js#L78)):</sup>
We really want to be able to run these tests on the desktop. So we need to wrap these calls with something like `typeof Mobile !== "undefined"` or `jxcore.utils.OSInfo().isMobile`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132)

**Comment by yaronyg** [comment]
Review status: 25 of 32 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[test/www/jxcore/bv_tests/testThaliReplicationManager.js, line 22 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K-0_aACsYqJ4LCyKPB6)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/bv_tests/testThaliReplicationManager.js#L22)):</sup>
Where is the fs import?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132)

**Comment by tobybrad** [comment]
Review status: 25 of 32 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[test/www/jxcore/lib/thali-tape.js, line 0 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K--kR_MLEs4EhZlu_V3)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/lib/thali-tape.js#L0)):</sup>
It's in the jxcore/ folder. Just needs to be in cwd which in this case is the same.

---

<sup>**[test/www/jxcore/UnitTest_app.js, line 78 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132#-K--r5wWzBgmiYblj3Gi)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/68ca724b7cd78dcec26433e1c409d6e22d38e45a/test/www/jxcore/UnitTest_app.js#L78)):</sup>
Agree.. but not now.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/132)

**Pull request merged**
