### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by vjrantal**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/673)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (be38304)

**Comment by ThaliTester** [comment]
Test (Success) 63998117 build is completed (be38304)

See https://github.com/ThaliTester/TestResults/tree/63998117be38304_More_tests_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 63998117be38304(be38304) has failed

See https://github.com/ThaliTester/TestResults/tree/63998117be38304_More_tests_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5e54a40)

**Comment by ThaliTester** [comment]
Test (Success) 63998117 build is completed (5e54a40)

See https://github.com/ThaliTester/TestResults/tree/639981175e54a40_More_tests_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 639981175e54a40(5e54a40) has failed

See https://github.com/ThaliTester/TestResults/tree/639981175e54a40_More_tests_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d1f6a2b)

**Comment by ThaliTester** [comment]
Test (Success) 63998117 build is completed (d1f6a2b)

See https://github.com/ThaliTester/TestResults/tree/63998117d1f6a2b_More_tests_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 63998117d1f6a2b(d1f6a2b) has failed

See https://github.com/ThaliTester/TestResults/tree/63998117d1f6a2b_More_tests_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (de3e24f)

**Comment by ThaliTester** [comment]
Test (Success) 63998117 build is completed (de3e24f)

See https://github.com/ThaliTester/TestResults/tree/63998117de3e24f_More_tests_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 63998117de3e24f(de3e24f) has failed

See https://github.com/ThaliTester/TestResults/tree/63998117de3e24f_More_tests_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/673#-:-KE2gGetMsbACqsnWyPM:1417088721)*

**Pull request merged**
