### PR TITLE
Review of thaliSendNotificationBasedOnReplication

### PR DESCRIPTION
**Pull request by yaronyg**
I moved a bunch of files around because our NextGeneration directory was getting unworkably large. I also cleaned up lint errors when I ran into them in random files.

thaliSendNotificationBasedOnReplication - This watches the local PouchDB instance, calculates who
needs to know about the changes and then asks the notification server to send them.

testThaliSendNotificationBasedOnReplication - Tests for the previous using  mock for the notification
server.

utilities - Just some minor utilities I needed for the previous.

testThaliReplicationUtilities - test for the utilities

Enhanced promiseQueue to support sticking items at the start of the queue

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/538)

### CODE REVIEW

**Comment by vjrantal** [comment]
@yaronyg: I seem to be able to reproduce locally on Windows the failure CI is getting:
```
# setup
# two peers with empty DB, update the doc
Uncaught Promise Rejection: {"name":"ExpectationError"}
Trace: { [ExpectationError: Expected start([ ����t�r�|섷�d1�Q۔V�3�T�#X+�x)��  �f��Zd��OM��%��JrrzE�f.Ǿ9���O(9�?(��E'˹d8oi�
N�h�F��'��7*'\��f6%�/ <�T�A=�p�B�,  a�����Q��8        P9�^I��ԕ�@z�T��W=f:�ۢ_
O�տ�֣+�g�����X��J� ��[���F���Y��E�v�Nn�|�    �@�oʠ�W�2#(Y���w�Θ����it���F��n�]) once (never called)
Expectation met: start([]) once
Expectation met: stop() once] name: 'ExpectationError' }
    at process.tests (C:\Users\vjrantal\Software\Thali\Thali_CordovaPlugin\test\www\jxcore\lib\thali-tape.js:39:11)
    at process.emit (events.js:98:20)
    at Array.0 (C:\Users\vjrantal\Software\Thali\Thali_CordovaPlugin\thali\node_modules\lie\lib\index.js:128:19)
    at nextTick (C:\Users\vjrantal\Software\Thali\Thali_CordovaPlugin\thali\node_modules\immediate\lib\index.js:61:18)
    at process._tickCallback (node.js:917:13)
****TEST TOOK:  ms ****
****TEST_LOGGER:[PROCESS_ON_EXIT_FAILED]****
```
If this is some Windows-only issue, I am fine ignoring, but if you have any ideas why this might occur, please have look.

**Comment by vjrantal** [comment]
Reviewed 45 of 45 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/bv_tests/testThaliReplicationUtilities.js, line 77 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZDkKC5ITgqeCrKyNn:-KAZDkKC5ITgqeCrKyNo:-1898072659) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/18cc95e18836f5f8422086891539b9780bed37dd/test/www/jxcore/bv_tests/testThaliReplicationUtilities.js#L77)):*
Marking this comment as "satisfied" in reviewable so feel free to ignore, but I was wondering could the API of RefreshTimerManager be refactored so that the getTimeWhenRun would not be overloaded with so many meanings? Now, it can be at least a positive number or -1 or -2 or null. Also, the naming first confused me in a way that I thought it means "time since the function was run", but that is not what it means.

---

*[test/www/jxcore/lib/testUtils.js, line 162 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZRj5b9Y13EC0-nLzJ:-KAZRj5b9Y13EC0-nLzK:1082525432) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/18cc95e18836f5f8422086891539b9780bed37dd/test/www/jxcore/lib/testUtils.js#L162)):*
Should this be something more generic and not contain the name of a single test (testThaliSendNotificationBasedOnReplication)?

---

*[thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js, line 71 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZTBkup4xn-mVP_sQJ:-KAZTBkup4xn-mVP_sQK:1576984174) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/18cc95e18836f5f8422086891539b9780bed37dd/thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js#L71)):*
I started collecting values like this to a file called `thaliConfig.js`. My thinking was that there would be a centralized place where one could see and tweak values such as these, for example, to create a build with better battery consumption characteristics.

If you think that is a good idea, the could be moved there.

---

*[thali/NextGeneration/thaliMobile.js, line 289 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZTgzeWC_SCUzYSiO0:-KAZTgzeWC_SCUzYSiO1:59895983) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/18cc95e18836f5f8422086891539b9780bed37dd/thali/NextGeneration/thaliMobile.js#L289)):*
When we assume bluetooth is only one work, BLUE_TOOTH should rather be BLUETOOTH.

---

*[thali/NextGeneration/thaliReplicationManager.js, line 32 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZVKEcBatJY4veFFu-:-KAZVKEcBatJY4veFFu0:179604364) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/db42a072a2376264b816df4c41f681fbb79bd324/thali/NextGeneration/thaliReplicationManager.js#L32)):*
Somehow it wasn't very clear where this argument was moved and the commit message or changeset didn't give me a clear hint (https://github.com/thaliproject/Thali_CordovaPlugin/commit/c356c354f5f7347739cdf0225a6d7a8216c86e79).

I am "satisfied" (in reviewable terms) for the change, but can you remind me where the router is now given or did the use case related to that go away?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538)*

**Comment by yaronyg** [comment]
I really don't like that test failure but I can't get it to repro on my mac. :( Did you get this to fail in appveyor as well? Which CI did you mean?

BTW I am still seeing failures in appveyor but now they say that we took more than 60 minutes to run! How did we do that? It looks like at some point the test just plain stopped running. But the area it failed in had to do with connectivity tests and I didn't do anything there.

---

Review status: 25 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 162 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZRj5b9Y13EC0-nLzJ:-KArA7QaXNAV21-L_m4q:134218989) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/18cc95e18836f5f8422086891539b9780bed37dd/test/www/jxcore/lib/testUtils.js#L162)):*
Yup. This is wrong. I gave it a more generic name.

---

*[thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js, line 71 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZTBkup4xn-mVP_sQJ:-KArB0-mXwvvHU09qSR2:-1959395738) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/18cc95e18836f5f8422086891539b9780bed37dd/thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js#L71)):*
I think that a config value should be as close as possible to where it will be used. That way devs have the best chance of finding it and understanding its intended context. Now if you have a bunch of config values that get re-used everywhere then by all means have a central config file. But when you have values that are used in exactly one place then shouldn't they live in that place?

For example, the values in thaliConfig are really only relevant to thaliWifiInfrastructure so personally I would have put them there.

---

*[thali/NextGeneration/thaliMobile.js, line 289 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZTgzeWC_SCUzYSiO0:-KArBjAmAZAiPL_9-3Wt:488869131) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/18cc95e18836f5f8422086891539b9780bed37dd/thali/NextGeneration/thaliMobile.js#L289)):*
I'm sorry but I don't understand. What does "When we assume bluetooth is only one work," mean?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-:-KAr7sIctrqdLZmlOREc:471376969)*

**Comment by vjrantal** [comment]
I think the failure I mentioned is the same what we see in AppVeyor, but for some reason, the AppVeyor console doesn't show it correctly. Here is again from my local Windows machine with current HEAD of your branch:

```
# two peers with empty DB, update the doc
ok 126 (unnamed assert)
ok 127 (unnamed assert)
# teardown
# setup
# add doc and make sure tokens refresh when they expire
Uncaught Promise Rejection: {"name":"ExpectationError"}
Trace: { [ExpectationError: Expected start([ �8M}&2M&����f%�լ*��3��34�wRt�D�K�9s�FJ8��j�M��
>����#K�jI
L z��8b.�4
��J�6�R�+��en��s��Y���G/8�z�"���U[�����S�2$α'��r��]) thrice (called twice)
Expectation met: stop() once] name: 'ExpectationError' }
    at process.tests (C:\Users\vjrantal\Software\Thali\Thali_CordovaPlugin\test\www\jxcore\lib\thali-tape.js:39:11)
    at process.emit (events.js:98:20)
    at Array.0 (C:\Users\vjrantal\Software\Thali\Thali_CordovaPlugin\thali\node_modules\lie\lib\index.js:128:19)
    at nextTick (C:\Users\vjrantal\Software\Thali\Thali_CordovaPlugin\thali\node_modules\immediate\lib\index.js:61:18)
    at process._tickCallback (node.js:917:13)
****TEST TOOK:  ms ****
****TEST_LOGGER:[PROCESS_ON_EXIT_FAILED]****
```

You can see that it is exactly the same test onto which AppVeyor fails.

Related to build taking more than 60 minutes .. that can happen with the current test framework if any test fails in a way that e.end() isn't called. We don't have any timeouts so the test hangs forever until a CI build timeout is hit. We have discussed with Toby that we should implement a configurable per test timeout, but that isn't done yet. Something like https://github.com/robert-chiniquy/timeout-tape.

---

Reviewed 7 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[thali/NextGeneration/thaliMobile.js, line 289 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KAZTgzeWC_SCUzYSiO0:-KAsS-xtGORrbLHhuILL:-1075548334) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/18cc95e18836f5f8422086891539b9780bed37dd/thali/NextGeneration/thaliMobile.js#L289)):*
Sorry, it was a typo and "work" should have been "word". What I am proposing is that you change BLUE_TOOTH -> BLUETOOTH.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-:-KAsPvgodRLK1q-kJonv:1108371310)*

**Comment by vjrantal** [comment]
For full transparency, I did not look at all the timing changes carefully enough so that I would fully understand why, for example, some millisecond value had to be changed from 1 to 0.

If such "deep review" is necessary, please assign back and I'll use more time for the review.

---

Reviewed 2 of 46 files at r1, 16 of 18 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/thali-tape.js, line 102 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KBRQEFKrePiDWOG6Lub:-KBRQEFL9KVJFLVmAgA-:1670114468) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f263110ba7f994512cb743ea665352f1d6feed61/test/www/jxcore/lib/thali-tape.js#L102)):*
I think these changes related to the setup/teardown test reporting fix that went into vNext separately, but for some reason reviewable shows them here as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-:-KBRQxASiLpuAc1o3Mc7:-21658782)*

**Comment by vjrantal** [comment]
The tests that fail for me locally with this branch are:
```
2016-02-26T07:29:33.993Z - info: 18. when network connection is lost a peer should be marked unavailable - fail
2016-02-26T07:29:33.993Z - info: 19. a peer should be found after #startListeningForAdvertisements is called - fail
```
However, it was offline discussed that the root cause might be elsewhere and the changes in this branch just makes the issues elsewhere appear.

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[thali/NextGeneration/promiseQueue.js, line 32 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538#-KBS7eEQf9FyRX80zAom:-KBS7eEQf9FyRX80zAon:-905727820) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f263110ba7f994512cb743ea665352f1d6feed61/thali/NextGeneration/promiseQueue.js#L32)):*
This array should be instance-specific. Please see https://github.com/thaliproject/Thali_CordovaPlugin/pull/581 that contains a fix proposal.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/538)*

**Pull request merged**
