### PR TITLE
fix: gradle.properties needs to be deleted after every compilation #1235

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1238)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6fc7002)

**Comment by ThaliTester** [comment]
Test (Success) 87748691 build is completed (6fc7002)

See https://github.com/ThaliTester/TestResults/tree/877486916fc7002_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 877486916fc7002(6fc7002) has failed

See https://github.com/ThaliTester/TestResults/tree/877486916fc7002_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (50754a8)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f3f3f0f)

**Comment by ThaliTester** [comment]
Test (Success) 87748691 build is completed (50754a8)

See https://github.com/ThaliTester/TestResults/tree/8774869150754a8_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 87748691 build is completed (f3f3f0f)

See https://github.com/ThaliTester/TestResults/tree/87748691f3f3f0f_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 8774869150754a8(50754a8) has failed

See https://github.com/ThaliTester/TestResults/tree/8774869150754a8_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f312443)

**Comment by ThaliTester** [comment]
Test (Success) 87748691 build is completed (f312443)

See https://github.com/ThaliTester/TestResults/tree/87748691f312443_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 87748691f312443(f312443) has failed

See https://github.com/ThaliTester/TestResults/tree/87748691f312443_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
@yaronyg just as a note. I want to finish with thaliproject/Thali_CordovaPlugin#1200 before this PR. Rebase it on updated master -> get approval after review -> only then merge this PR into master.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2f119d8)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (70e2b3b)

**Comment by ThaliTester** [comment]
Test (Success) 87748691 build is completed (2f119d8)

See https://github.com/ThaliTester/TestResults/tree/877486912f119d8_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 877486912f119d8(2f119d8) has failed

See https://github.com/ThaliTester/TestResults/tree/877486912f119d8_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87748691 build is completed (70e2b3b)

See https://github.com/ThaliTester/TestResults/tree/8774869170e2b3b_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (33360fe)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (ecdeb4e)

**Comment by ThaliTester** [comment]
Test 8774869170e2b3b(70e2b3b) has failed

See https://github.com/ThaliTester/TestResults/tree/8774869170e2b3b_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87748691 build is completed (33360fe)

See https://github.com/ThaliTester/TestResults/tree/8774869133360fe_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 87748691 build is completed (ecdeb4e)

See https://github.com/ThaliTester/TestResults/tree/87748691ecdeb4e_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 8774869133360fe(33360fe) has failed

See https://github.com/ThaliTester/TestResults/tree/8774869133360fe_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (d63ab45)

**Comment by ThaliTester** [comment]
Test 87748691ecdeb4e(ecdeb4e) has failed

See https://github.com/ThaliTester/TestResults/tree/87748691ecdeb4e_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Fail) 87748691 build is completed (d63ab45)

See https://github.com/ThaliTester/TestResults/tree/87748691d63ab45_fix__gradle_properties_needs_to_be_deleted_after_every_compilation__1235_larryonoff/ for the logs

**Pull request merged**
