### PR TITLE
Wifi-based mocks for the current version

### LINKED ISSUE #171: Implement the Wifi infrastructure for vNext
- [x] Test all the idempotent methods to make sure they really are idempotent.
- [x] Tests for all the events we are supposed to fire. (`wifiPeerAvailabilityChanged` was implemented in context of this issue and rest is under https://github.com/thaliproject/Thali_CordovaPlugin/issues/481)
- [x] Tests that when we stop advertising we actually issue a byebye.
- [x] Make sure when we change our USN that we both issue a byebye for the old USN and an alive for the new one.
- [x] Change "different USN after every invocation" test to use node-ssdp.
- [x] Test that after stopping, we don't get anymore advertisements and all open connections closed. (this is partly tested by the fact that the test runner exists cleanly, i.e., no open connections prevents a clean exit)
- [x] Implement the promise-queue.
- [x] Start using the SSDP NT value as specified.
- [x] Add node-ssdp API to remove USN and start using it.
- [x] Properly start the passed router object.
- [x] Start using winston logger.
- [x] Check that passed router object inherits from router (express does the checks when we use the router and we have a try-catch-handling for that).

### PR DESCRIPTION
**Pull request by vjrantal**
This does not close #171, but is just about merging the mocks that match the current version of the APIs to the branch they belong to.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/453)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5284bbb)

**Comment by ThaliTester** [comment]
Test (Fail) 56151093 build is completed (5284bbb)

See https://github.com/ThaliTester/TestResults/tree/561510935284bbb_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (fe31153)

**Comment by ThaliTester** [comment]
Test (Fail) 56151093 build is completed (5284bbb)

See https://github.com/ThaliTester/TestResults/tree/561510935284bbb_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (f300170)

**Comment by ThaliTester** [comment]
Test (Fail) 56151093 build is completed (fe31153)

See https://github.com/ThaliTester/TestResults/tree/56151093fe31153_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 56151093 build is completed (fe31153)

See https://github.com/ThaliTester/TestResults/tree/56151093fe31153_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 56151093 build is completed (f300170)

See https://github.com/ThaliTester/TestResults/tree/56151093f300170_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 56151093 build is completed (f300170)

See https://github.com/ThaliTester/TestResults/tree/56151093f300170_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8d3c4f5)

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (8d3c4f5)

See https://github.com/ThaliTester/TestResults/tree/561510938d3c4f5_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f3290d6)

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (f3290d6)

See https://github.com/ThaliTester/TestResults/tree/56151093f3290d6_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 561510938d3c4f5(8d3c4f5) has failed

See https://github.com/ThaliTester/TestResults/tree/561510938d3c4f5_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 56151093f3290d6(f3290d6) has failed

See https://github.com/ThaliTester/TestResults/tree/56151093f3290d6_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (89cecbd)

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (89cecbd)

See https://github.com/ThaliTester/TestResults/tree/5615109389cecbd_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5615109389cecbd(89cecbd) has failed

See https://github.com/ThaliTester/TestResults/tree/5615109389cecbd_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3390750)

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (3390750)

See https://github.com/ThaliTester/TestResults/tree/561510933390750_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c886730)

**Comment by ThaliTester** [comment]
Test 561510933390750(3390750) has failed

See https://github.com/ThaliTester/TestResults/tree/561510933390750_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (c886730)

See https://github.com/ThaliTester/TestResults/tree/56151093c886730_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 56151093c886730(c886730) has failed

See https://github.com/ThaliTester/TestResults/tree/56151093c886730_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (914d164)

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (914d164)

See https://github.com/ThaliTester/TestResults/tree/56151093914d164_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (19b4771)

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (19b4771)

See https://github.com/ThaliTester/TestResults/tree/5615109319b4771_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 56151093914d164(914d164) has failed

See https://github.com/ThaliTester/TestResults/tree/56151093914d164_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 5615109319b4771(19b4771) has failed

See https://github.com/ThaliTester/TestResults/tree/5615109319b4771_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b6ab50f)

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (b6ab50f)

See https://github.com/ThaliTester/TestResults/tree/56151093b6ab50f_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 56151093b6ab50f(b6ab50f) has failed

See https://github.com/ThaliTester/TestResults/tree/56151093b6ab50f_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
@tobybrad, @yaronyg: Could either of you do a code review for this one - it is ready to be merged from my perspective.

**Comment by tobybrad** [comment]
Reviewed 10 of 19 files at r1, 3 of 4 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 2 of 5 files at r5, 6 of 7 files at r6, 4 of 4 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/453)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f6e24ff)

**Comment by tobybrad** [comment]
Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/453)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (70bee58)

**Comment by tobybrad** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/453)*

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (f6e24ff)

See https://github.com/ThaliTester/TestResults/tree/56151093f6e24ff_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 56151093 build is completed (70bee58)

See https://github.com/ThaliTester/TestResults/tree/5615109370bee58_Wifi-based_mocks_for_the_current_version_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 56151093f6e24ff(f6e24ff) has failed

See https://github.com/ThaliTester/TestResults/tree/56151093f6e24ff_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 5615109370bee58(70bee58) has failed

See https://github.com/ThaliTester/TestResults/tree/5615109370bee58_Wifi-based_mocks_for_the_current_version_vjrantal/ for the fail logs

**Pull request merged**
