### PR TITLE
Story 00 juksilve

### PR DESCRIPTION
**Pull request by DrJukka**
changes made are described in comments
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/66%23issuecomment-130446070%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/66%23issuecomment-130724192%22%2C%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/66%23issuecomment-130728809%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/thaliproject/Thali_CordovaPlugin/pull/66%23issuecomment-130446070%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40DrJukka%20-%20It%20would%20appear%20that%20when%20you%20renamed%20the%20files%20you%20did%20it%20by%20delete%20and%20then%20rename%20%28as%20opposed%20to%20a%20GIT%20mv%29%20and%20this%20PR%20only%20seems%20to%20have%20the%20delete%2C%20not%20the%20rename%20part.%20Please%20update%20the%20commit%20with%20the%20renamed%20files.%22%2C%20%22created_at%22%3A%20%222015-08-12T20%3A57%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1480964%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/yaronyg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40DrJukka%20-%20I%20don%27t%20see%20an%20update%20to%20this.%20Can%20we%20close%20it%20for%20now%3F%22%2C%20%22created_at%22%3A%20%222015-08-13T15%3A09%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1480964%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/yaronyg%22%7D%7D%2C%20%7B%22body%22%3A%20%22from%20my%20point%20of%20view%2C%20surely%20we%20could%20close%20it%22%2C%20%22created_at%22%3A%20%222015-08-13T15%3A26%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5235141%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/DrJukka%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/thaliproject/Thali_CordovaPlugin/pull/66#issuecomment-130446070'>General Comment</a></b>
- <a href='https://github.com/yaronyg'></a> @DrJukka - It would appear that when you renamed the files you did it by delete and then rename (as opposed to a GIT mv) and this PR only seems to have the delete, not the rename part. Please update the commit with the renamed files.
- <a href='https://github.com/yaronyg'></a> @DrJukka - I don't see an update to this. Can we close it for now?
- <a href='https://github.com/DrJukka'></a> from my point of view, surely we could close it

<a href='https://www.codereviewhub.com/thaliproject/Thali_CordovaPlugin/pull/66?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/thaliproject/Thali_CordovaPlugin/pull/66?approve=1'></a>&nbsp;<a href='https://github.com/thaliproject/Thali_CordovaPlugin/pull/66'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by yaronyg** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/thaliproject/Thali_CordovaPlugin/pull/66'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by yaronyg** [comment]
@DrJukka - It would appear that when you renamed the files you did it by delete and then rename (as opposed to a GIT mv) and this PR only seems to have the delete, not the rename part. Please update the commit with the renamed files.

**Comment by yaronyg** [comment]
@DrJukka - I don't see an update to this. Can we close it for now?

**Comment by DrJukka** [comment]
from my point of view, surely we could close it

**Pull request closed without merging**
