### PR TITLE
disconnect

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1043)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (29a14d1)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (30c731c)

**Comment by ThaliTester** [comment]
Test (Success) 85263902 build is completed (29a14d1)

See https://github.com/ThaliTester/TestResults/tree/8526390229a14d1_V_next_aevsyuchenya_880_908_baydet/ for the logs

**Comment by baydet** [comment]
@yaronyg, we have a lot of dependencies with #880. So I've made vNext_aevsyuchenya_880 as base branch.

**Comment by ThaliTester** [comment]
Test (Success) 85263902 build is completed (30c731c)

See https://github.com/ThaliTester/TestResults/tree/8526390230c731c_V_next_aevsyuchenya_880_908_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 85263902 build is completed (3cb0bc0)

See https://github.com/ThaliTester/TestResults/tree/852639023cb0bc0_disconnect_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 8526390229a14d1(29a14d1) has failed

See https://github.com/ThaliTester/TestResults/tree/8526390229a14d1_V_next_aevsyuchenya_880_908_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
Test 8526390230c731c(30c731c) has failed

See https://github.com/ThaliTester/TestResults/tree/8526390230c731c_V_next_aevsyuchenya_880_908_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
Test 852639023cb0bc0(3cb0bc0) has failed

See https://github.com/ThaliTester/TestResults/tree/852639023cb0bc0_disconnect_baydet/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 7 of 8 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift, line 61 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReHrmS5a4HbFz70nAf:-KReHrmTC9lhO2OapngB:b-55pxl4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift#L61)):*
> ```Swift
>     func closeSocket(for session: Session) {
>         //todo remove close TCP listener
>         //https://github.com/thaliproject/Thali_CordovaPlugin/issues/881
> ```

Since 881 is closed and its PR 996 is closed then how is this issue to ever be resolved? 996 (the pr for 881) was put into vNext_aevsyuchenya_819. Doesn't that branch have to be merged with this branch before we can accept it?

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift, line 75 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReJ_76jjk78rr0taAS:-KReJ_77oPQfAleFHMFs:b-6t412e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift#L75)):*
> ```Swift
>             }
>             self?.handleDidReceive(socket: socket, for: session)
>             completion(nil, nil)
> ```

There is no return after this call to completion. Which means that completion will get called a second time in the addToDiscardQueue. But I believe this eventually calls multiConnectResolved and it is only supposed to be called a single time for any given multiConnect call. So isn't something not quite right here? 

---

*[src/ios/AppContextTests.swift, line 382 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReH-bihTByD_L0mgxa:-KReH-bjFiQKSnn8Pb1u:b5wdyn4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/src/ios/AppContextTests.swift#L382)):*
> ```Swift
>         do {
>             let notAString = 42
>             try context.disconnect([notAString])
> ```

Don't we need to check that we specifically got a bad parameters error? A failure test doesn't just test failure, it tests that it's the right failure.

---

*[src/ios/AppContextTests.swift, line 385 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReGuXyKvJBkdjSa1-u:-KReGuXyKvJBkdjSa1-v:b-bggndm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/src/ios/AppContextTests.swift#L385)):*
> ```Swift
>         } catch let err as AppContextError {
>             contextError = err
>         } catch _ {
> ```

Shouldn't the test automatically fail if it gets an unexpected exception? Not swallow it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (885abe0)

**Comment by baydet** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift, line 61 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReHrmS5a4HbFz70nAf:-KRiizVDZws3IIELPbeN:b-mx6o61) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift#L61)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Since 881 is closed and its PR 996 is closed then how is this issue to ever be resolved? 996 (the pr for 881) was put into vNext_aevsyuchenya_819. Doesn't that branch have to be merged with this branch before we can accept it?
</details>
There is no PR yet for this issue. We're expecting to have it in a short period of time after vNext_aevsyuchenya_880 will be merged.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift, line 75 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReJ_76jjk78rr0taAS:-KRijH9xLPMc1xOuQaVJ:b-lh7z0q) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift#L75)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> There is no return after this call to completion. Which means that completion will get called a second time in the addToDiscardQueue. But I believe this eventually calls multiConnectResolved and it is only supposed to be called a single time for any given multiConnect call. So isn't something not quite right here? 
</details>
Yep, my mistake. I've added todo with link to issue

---

*[src/ios/AppContextTests.swift, line 382 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReH-bihTByD_L0mgxa:-KRik7A8r6JE2HnK98Rc:b298ptv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/src/ios/AppContextTests.swift#L382)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Don't we need to check that we specifically got a bad parameters error? A failure test doesn't just test failure, it tests that it's the right failure.
</details>
yes, we're checking that we've received `.BadParameters` error. 

---

*[src/ios/AppContextTests.swift, line 385 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReGuXyKvJBkdjSa1-u:-KRikGFfMZhSYeS0Puf9:b-qssebl) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/src/ios/AppContextTests.swift#L385)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Shouldn't the test automatically fail if it gets an unexpected exception? Not swallow it?
</details>
fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043)*

**Comment by ThaliTester** [comment]
Test (Fail) 85263902 build is completed (885abe0)

See https://github.com/ThaliTester/TestResults/tree/85263902885abe0_disconnect_baydet/ for the logs

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift, line 61 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReHrmS5a4HbFz70nAf:-KRjSkpKfv_f-zp9Ochy:b-1rnkpb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift#L61)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> There is no PR yet for this issue. We're expecting to have it in a short period of time after vNext_aevsyuchenya_880 will be merged.
</details>
NB: But shouldn't there be a link to some issue that makes sure we don't forget to do this? 881 is closed so it is not an appropriate issue to link to. It either needs to be re-opened or a new issue created and linked to. The point is to make sure we don't leave anything behind.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift, line 75 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReJ_76jjk78rr0taAS:-KRjSz5f0RCAafP9rog2:b-posczm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift#L75)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> Yep, my mistake. I've added todo with link to issue
</details>
Besides the problem with pointing to a closed issue isn't this code just plain wrong? Not incomplete, but actually wrong. It is going to potentially fire two completion events. Isn't that always wrong? Let's discuss on stack tomorrow to make sure we get this resolved and done.

---

*[src/ios/AppContextTests.swift, line 382 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReH-bihTByD_L0mgxa:-KRjTAxctYN_Jy9utYYD:b-u3ome3) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/src/ios/AppContextTests.swift#L382)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> yes, we're checking that we've received `.BadParameters` error. 
</details>
Ahh I see! Sorry. My bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043)*

**Comment by baydet** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift, line 61 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReHrmS5a4HbFz70nAf:-KRlbwgwctbau5izhx-e:bc6qmhs) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift#L61)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: But shouldn't there be a link to some issue that makes sure we don't forget to do this? 881 is closed so it is not an appropriate issue to link to. It either needs to be re-opened or a new issue created and linked to. The point is to make sure we don't leave anything behind.
</details>
I think it's better to reopen 881 back. Because we even don't have the PR for 881. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043)*

**Comment by yaronyg** [comment]
:LGTM: As soon as you get it passing CI please check in.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift, line 75 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-KReJ_76jjk78rr0taAS:-KS52y098HE6GgwqvxIu:bk17sfj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3cb0bc0ee58962ea4b51d944171a81a82bd918f9/lib/ios/ThaliCore/ThaliCore/SocketConnection/SocketRelay.swift#L75)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Besides the problem with pointing to a closed issue isn't this code just plain wrong? Not incomplete, but actually wrong. It is going to potentially fire two completion events. Isn't that always wrong? Let's discuss on stack tomorrow to make sure we get this resolved and done.
</details>
This is now NB. I have opened #1090 to track it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-:-KS532X3HDefAFAP8hTy:boscqhw)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6fceb4a)

**Comment by ThaliTester** [comment]
Test (Fail) 85263902 build is completed (6fceb4a)

See https://github.com/ThaliTester/TestResults/tree/852639026fceb4a_disconnect_baydet/ for the logs

**Comment by dersim-davaod** [comment]
:lgtm: 

---

Reviewed 3 of 8 files at r1, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1043#-:-KS6JzgzdfCHP_qmkP0N:bg7igkv)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (6a23328)

**Comment by ThaliTester** [comment]
Test (Success) 85263902 build is completed (6a23328)

See https://github.com/ThaliTester/TestResults/tree/852639026a23328_disconnect_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 852639026a23328(6a23328) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/852639026a23328_disconnect_baydet/ for the logs

**Pull request merged**
