### PR TITLE
Replacer for hardcoded ids

### LINKED ISSUE #1070: Create setupThaliTestIds.js and configure setUpTests.sh to call it
See thaliproject/Thali_CordovaPlugin#1066 for context

Please create setupThaliTestIds.js in thali/install and have it go over to ThaliTest (fail out with process.exit(-1) if you can't find ThaliTest as a sibling to the current directory) and:

 * Edit thaliConfig.json using a regex to replace existing SSDP_NT value with a randomly generated string (use npm randomstring) of the same size. This is fine because this edited file is in ThaliTest and not the repo clone.
 * Edit ConnectionHelper.java (also with a regex) to replace service ID with a newly generated GUID and the manufactuer ID with a random number between 1100 and 65534.
 * Edit JXcoreExtension.m (make sure we do this AFTER the point where setUpTests replaces the default version of JXcoreExtension.m) to replace the serviceType with a same sized random string.

Remember, all the previous is happening inside of ThaliTest, not the clone of the repo.

Now please go to setUpTests.sh and add a call to 'node setupThaliTestIds.js' at the end of the Install_Thali function.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1070 

I will merge this PR into vNext and vNext_yarong_417_812 after LGTM. We shouldn't obtain any problems with such merge.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1115)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (de8bbbe)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d16c914)

**Comment by ThaliTester** [comment]
Test (Fail) 86214450 build is completed (de8bbbe)

See https://github.com/ThaliTester/TestResults/tree/86214450de8bbbe_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 86214450 build is completed (d16c914)

See https://github.com/ThaliTester/TestResults/tree/86214450d16c914_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
I will fix CI today.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bdfc087)

**Comment by ThaliTester** [comment]
Test (Fail) 86214450 build is completed (bdfc087)

See https://github.com/ThaliTester/TestResults/tree/86214450bdfc087_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (84c209e)

**Comment by ThaliTester** [comment]
Test (Fail) 86214450 build is completed (84c209e)

See https://github.com/ThaliTester/TestResults/tree/8621445084c209e_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4e2d579)

**Comment by ThaliTester** [comment]
Test (Success) 86214450 build is completed (4e2d579)

See https://github.com/ThaliTester/TestResults/tree/862144504e2d579_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (04dab41)

**Comment by ThaliTester** [comment]
Test 862144504e2d579(4e2d579) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/862144504e2d579_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86214450 build is completed (04dab41)

See https://github.com/ThaliTester/TestResults/tree/8621445004dab41_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 8621445004dab41(04dab41) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8621445004dab41_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
This should be going straight to vNext as vNext_aevsyuchenya_769 is already being merged into vNext. Please see https://github.com/thaliproject/Thali_CordovaPlugin/pull/1112.

There are a couple of blocking issues but you can resolve them without having to get another approval from me. So please fix the blocking issues, please review the non-blocking issues and then :LGTM:

---

Reviewed 4 of 6 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[thali/install/npm-shrinkwrap.json, line 53 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSDwkJQl2xsClF78NAZ:-KSDwkJQl2xsClF78NA_:byz6cqe) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/533f65dba44cfd8beca325099e2cad331d3f53f0/thali/install/npm-shrinkwrap.json#L53)):*
> ```JSON
>       "from": "bl@>=1.1.2 <1.2.0"
>     },
>     "bluebird": {
> ```

Removing Bluebird isn't, I believe, the right way to handle changing its version. If you are going to keep the shrinkwrap files then you need to re-run shrinkwrap so it upgrades to the latest versions for all of your dependencies.

---

*[thali/install/package.json, line 7 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSDws1WpH2ZhkaFKoh6:-KSDws1WpH2ZhkaFKoh7:b-mh9wiw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/package.json#L7)):*
> ```JSON
>   "main": "install.js",
>   "dependencies": {
>     "bluebird": "^3.4.6",
> ```

We don't use SEMVER modifiers, only hard coded versions. This is fixed in vNext_yarong_417_812. But please change these so it will make the eventual merge easier.

---

*[thali/install/setUpThaliTestIds.js, line 57 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSE04rPngviTwSB79Mx:-KSE04rPngviTwSB79My:bl9zp6a) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/setUpThaliTestIds.js#L57)):*
> ```JavaScript
> }
> 
> function readFile(path) {
> ```

NB: Why not just use readFileAsync provided by fs-extra-promise which is already included in install/package.json? No need to re-invent promise versions of FS when we already pay the price of installing a library (fs-extra-promise) that does exactly that.

---

*[thali/install/setUpThaliTestIds.js, line 70 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSE0d_75UFGtRUrbs0G:-KSE0d_75UFGtRUrbs0H:b-go5b4w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/setUpThaliTestIds.js#L70)):*
> ```JavaScript
> }
> 
> function writeFile(path, content) {
> ```

NB: Same issue as above, writeFileAsync is already provided by fs-extra-promise.

---

*[thali/install/setUpThaliTestIds.js, line 175 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSE5qoixUsiMr-s6OyK:-KSE5qoixUsiMr-s6OyL:bjpsmjy) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/setUpThaliTestIds.js#L175)):*
> ```JavaScript
>   var replacements = [];
> 
>   // Example: 'private static final String SERVICE_UUID_AS_STRING = "fa87c0d0-afac-11de-8a39-0800200c9a66";'
> ```

NB: Why did we need to change the service_uuid_as_string? I believe this sets the service ID used in Bluetooth (not BLE). So it would only apply after someone has found the MAC address via BLE. So this shouldn't have any affect on test collisions. It's the BLE ID (set below with BLE_SERVICE_UUID_AS_STRING) that would actually affect discovery. I don't think this change is harmful so I'm not blocking checkin because of it but please clarify with @evabishchevich as I'm pretty sure this isn't necessary.

---

*[thali/install/utils/polyfills.js, line 1 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSE6XhvgB_aCAK2OyQD:-KSE6XhvgB_aCAK2OyQE:bh7vaac) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/utils/polyfills.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

NB: NOT AGAIN!!! Please, this is nuts. We have to put these files in one place. I can't take all this duplication! It's making me nuts. Same with the next two files. Please just pick a location and have everyone point there. You can use relative paths.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-:-KSDwa1wfzlG4ajATj7K:b6jytec)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8b4e910)

**Comment by andrew-aladev** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[thali/install/npm-shrinkwrap.json, line 53 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSDwkJQl2xsClF78NAZ:-KSGTQLv49CLbjpxvYgu:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/533f65dba44cfd8beca325099e2cad331d3f53f0/thali/install/npm-shrinkwrap.json#L53)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Removing Bluebird isn't, I believe, the right way to handle changing its version. If you are going to keep the shrinkwrap files then you need to re-run shrinkwrap so it upgrades to the latest versions for all of your dependencies.
</details>
Done.

---

*[thali/install/package.json, line 7 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSDws1WpH2ZhkaFKoh6:-KSGTtwSba2QMfPAZfdp:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/package.json#L7)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> We don't use SEMVER modifiers, only hard coded versions. This is fixed in vNext_yarong_417_812. But please change these so it will make the eventual merge easier.
</details>
Done.

---

*[thali/install/setUpThaliTestIds.js, line 57 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSE04rPngviTwSB79Mx:-KSGcJI9Fct7VgguBM7z:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/setUpThaliTestIds.js#L57)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Why not just use readFileAsync provided by fs-extra-promise which is already included in install/package.json? No need to re-invent promise versions of FS when we already pay the price of installing a library (fs-extra-promise) that does exactly that.
</details>
Done.

---

*[thali/install/setUpThaliTestIds.js, line 70 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSE0d_75UFGtRUrbs0G:-KSGcLFapJv-ExPz_e1U:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/setUpThaliTestIds.js#L70)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Same issue as above, writeFileAsync is already provided by fs-extra-promise.
</details>
Done.

---

*[thali/install/utils/polyfills.js, line 1 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSE6XhvgB_aCAK2OyQD:-KSGgrT_6a-7D8P_UV5k:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/utils/polyfills.js#L1)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: NOT AGAIN!!! Please, this is nuts. We have to put these files in one place. I can't take all this duplication! It's making me nuts. Same with the next two files. Please just pick a location and have everyone point there. You can use relative paths.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115)*

**Comment by ThaliTester** [comment]
Test (Fail) 86214450 build is completed (8b4e910)

See https://github.com/ThaliTester/TestResults/tree/862144508b4e910_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (fcb5eda)

**Comment by andrew-aladev** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[thali/install/setUpThaliTestIds.js, line 175 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSE5qoixUsiMr-s6OyK:-KSGkafLvAG0MHYAQmYQ:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/04dab412325a05b88d0a4008e37e18d0370625eb/thali/install/setUpThaliTestIds.js#L175)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Why did we need to change the service_uuid_as_string? I believe this sets the service ID used in Bluetooth (not BLE). So it would only apply after someone has found the MAC address via BLE. So this shouldn't have any affect on test collisions. It's the BLE ID (set below with BLE_SERVICE_UUID_AS_STRING) that would actually affect discovery. I don't think this change is harmful so I'm not blocking checkin because of it but please clarify with @evabishchevich as I'm pretty sure this isn't necessary.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115)*

**Comment by ThaliTester** [comment]
Test (Fail) 86214450 build is completed (fcb5eda)

See https://github.com/ThaliTester/TestResults/tree/86214450fcb5eda_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (fceaaba)

**Comment by ThaliTester** [comment]
Test (Fail) 86214450 build is completed (fceaaba)

See https://github.com/ThaliTester/TestResults/tree/86214450fceaaba_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
:lgtm: (just please fix the alphabetic order issue)

---

Reviewed 2 of 4 files at r7, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/package.json, line 19 at r9](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-KSJ5xL-WTwJtgr-Q8Zy:-KSJ5xL-WTwJtgr-Q8Zz:b-utjmrz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fceaabae6b46f4ed77385d50b5e02b08b78a353e/thali/install/package.json#L19)):*
> ```JSON
>     "xcode": "^0.8.9",
> 
>     "array-from": "2.1.1",
> ```

Can you please put these in alphabetical order? It makes is so much easier to find and manage things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1115#-:-KSJ7939M6bpfm1cfNhn:b-27zt34)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (d568777)

**Comment by ThaliTester** [comment]
Test (Fail) 86214450 build is completed (d568777)

See https://github.com/ThaliTester/TestResults/tree/86214450d568777_Replacer_for_hardcoded_ids_andrew-aladev/ for the logs

**Pull request merged**
