### PR TITLE
#934 Fixed bunch of bugs from #928

### LINKED ISSUE #934: Please fix 'jx npm run test-meta' in vNext_yarong_417_812
We have a timer failure. I don't know why and I ran out of time today to investigate. Since this blocks everything please sync to the latest vNext_yarong_417_812, investigate and repair the issue.

### PR DESCRIPTION
**Pull request by artemjackson**
Closes #934.
Includes #954.
Needs for #941.

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/936)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (f6f0d7d)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (f3b5a80)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (b9d3848)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (8d30c13)

**Comment by ThaliTester** [comment]
Test (Fail) 82865362 build is completed (f6f0d7d)

See https://github.com/ThaliTester/TestResults/tree/82865362f6f0d7d_Fixed_a_Mobile_mock_logic_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 82865362 build is completed (f3b5a80)

See https://github.com/ThaliTester/TestResults/tree/82865362f3b5a80_Fixed_a_Mobile_mock_logic_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 82865362 build is completed (b9d3848)

See https://github.com/ThaliTester/TestResults/tree/82865362b9d3848_Fixed_the_Mobile_mock_logic_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 82865362 build is completed (8d30c13)

See https://github.com/ThaliTester/TestResults/tree/828653628d30c13_Fixed_the_Mobile_mock_logic_artemjackson/ for the logs

**Comment by artemjackson** [comment]
@yaronyg  the test that hanged passed after specified timeout (25 minutes)
```
# should run test with 5 peers
testSendData created {"timeout":1500000,"rounds":1,"dataTimeout":10000,"dataAmount":1000000,"conReTryTimeout":50,"conReTryCount":5,"peerCount":5}bt-address length : 5
daya1000000
check server
serverPort is 8889
StartBroadcasting returned error Error: device-identifier-me
// hangs here for 25 minutes
timeout now
weAreDoneNow, resultArray.length: 0
sendReportNow
ok 11 received a result to the done event
// other tests output
1..18
# tests 18
# pass  18

# ok
```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (44f8192)

**Comment by ThaliTester** [comment]
Test (Success) 82865362 build is completed (44f8192)

See https://github.com/ThaliTester/TestResults/tree/8286536244f8192__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the logs

**Comment by artemjackson** [comment]
@yaronyg well, I found out what was wrong with test and fixed it.

**Comment by ThaliTester** [comment]
Test 8286536244f8192(44f8192) has failed

See https://github.com/ThaliTester/TestResults/tree/8286536244f8192__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the fail logs

**Comment by artemjackson** [comment]
@yaronyg Why `vNext_yarong_417_812` that has been just updated with `vNext` doesn't contain #924?

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (163efc7)

**Comment by ThaliTester** [comment]
Test (Success) 82865362 build is completed (163efc7)

See https://github.com/ThaliTester/TestResults/tree/82865362163efc7__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 82865362163efc7(163efc7) has failed

See https://github.com/ThaliTester/TestResults/tree/82865362163efc7__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
It is a botched merge but alas it wasn't mine. If I'm reading the history correctly then I believe the mistake was introduced in the commit immediately after Ilya's, see https://github.com/thaliproject/Thali_CordovaPlugin/commit/d6c913da811ca5f25fbfa9a0f43d8fe099e28d1c

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/936#-:-KQ88AGTNjckFO-mdlPI:bnfp4nl)*

**Comment by artemjackson** [comment]
@yaronyg now this PR fails with another error while executing tests.
```
08-29 16:11:04.705  3836  3887 I jxcore-log: 
,08-29 16:11:04.734  3836  4308 D io.jxcore.node.StreamCopyingThread: Exiting thread (ID: 463, name: My test thread name), during the lifetime of the thread the total number of bytes read was 143 and the total number of bytes written 143
,08-29 16:11:05.132  3836  3887 W jxcore-log: !!! js_ReportOverRecursed called !!!
,08-29 16:11:05.206  4311  3887 W google-breakpad: -----BEGIN BREAKPAD MICRODUMP-----

....

--------- beginning of crash
08-29 16:11:05.331  3836  3887 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 3887 (Thread-333)
```
I've never seen such error before. Can this error be inherited from #928?

**Comment by yaronyg** [comment]
Can we increase the stack size for Android and iOS to whatever it is for Desktop because we don't see this bug on desktop.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (403aafb)

**Comment by ThaliTester** [comment]
Test (Success) 82865362 build is completed (403aafb)

See https://github.com/ThaliTester/TestResults/tree/82865362403aafb__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 82865362403aafb(403aafb) has failed

See https://github.com/ThaliTester/TestResults/tree/82865362403aafb__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c4ce6b4)

**Comment by ThaliTester** [comment]
Test (Success) 82865362 build is completed (c4ce6b4)

See https://github.com/ThaliTester/TestResults/tree/82865362c4ce6b4__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 82865362c4ce6b4(c4ce6b4) has failed

See https://github.com/ThaliTester/TestResults/tree/82865362c4ce6b4__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3f51f5b)

**Comment by ThaliTester** [comment]
Test (Success) 82865362 build is completed (3f51f5b)

See https://github.com/ThaliTester/TestResults/tree/828653623f51f5b__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 828653623f51f5b(3f51f5b) has failed

See https://github.com/ThaliTester/TestResults/tree/828653623f51f5b__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e858c08)

**Comment by ThaliTester** [comment]
Test (Success) 82865362 build is completed (e858c08)

See https://github.com/ThaliTester/TestResults/tree/82865362e858c08__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 82865362e858c08(e858c08) has failed

See https://github.com/ThaliTester/TestResults/tree/82865362e858c08__934_Fixed_the_Mobile_mock_logic_artemjackson/ for the fail logs

**Comment by artemjackson** [comment]
@yaronyg I made some investigations and what are results:
* all tests pass when using jxcore 0.3.1.4 with v8
* unpredictable tests behavior when using jxcore 0.3.1.4 with sm (let us discuss it during the call)

**Comment by yaronyg** [comment]
@artemjackson btw to simplify the SM issues I would suggest using the changes you made to let us just run in pure wifi only mode on the desktop. This would let us get the wifi based mock completely out of the way and would also make sure we aren't running both 'native' (via the mock) and 'wifi' code simultaneously. This would help us narrow down the number of players causing problems. I'd also suggest starting to run just one test file at a time to see if we can get a reasonable repo with a short run time.

**Comment by artemjackson** [comment]
@yaronyg This PR does not relate to #916 directly. It just fixes #928 bugs.
I think that once it passed CI then we will be able to work with #916 and choose desirable network type.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b4391eb)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (80ed803)

**Comment by ThaliTester** [comment]
Test (Fail) 82865362 build is completed (b4391eb)

See https://github.com/ThaliTester/TestResults/tree/82865362b4391eb__934_Fixed_bunch_of_bugs_from__928_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 82865362 build is completed (80ed803)

See https://github.com/ThaliTester/TestResults/tree/8286536280ed803__934_Fixed_bunch_of_bugs_from__928_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8286536280ed803(80ed803) has failed

See https://github.com/ThaliTester/TestResults/tree/8286536280ed803__934_Fixed_bunch_of_bugs_from__928_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 6 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/936)*

**Pull request merged**
