### PR TITLE
Update BtLib version

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1740)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5cb06d0)

**Comment by ThaliTester** [comment]
Test 102271039 (5cb06d0) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 102271039 build is completed (5cb06d0)

See https://github.com/ThaliTester/TestResults/tree/1022710395cb06d0_Update_BtLib_version_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8c29c0f)

**Comment by ThaliTester** [comment]
Test 102271039 (8c29c0f) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102271039 build is completed (8c29c0f)

See https://github.com/ThaliTester/TestResults/tree/1022710398c29c0f_Update_BtLib_version_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 1022710398c29c0f(8c29c0f) has failed

See https://github.com/ThaliTester/TestResults/tree/1022710398c29c0f_Update_BtLib_version_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (975da4b)

**Comment by ThaliTester** [comment]
Test 102271039 (975da4b) build started.

**Comment by ThaliTester** [comment]
Test 102271039975da4b(975da4b) has failed

See https://github.com/ThaliTester/TestResults/tree/102271039975da4b_Update_BtLib_version_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a5a4541)

**Comment by ThaliTester** [comment]
Test 102271039 (a5a4541) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102271039 build is completed (a5a4541)

See https://github.com/ThaliTester/TestResults/tree/102271039a5a4541_Update_BtLib_version_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 102271039a5a4541(a5a4541) has failed

See https://github.com/ThaliTester/TestResults/tree/102271039a5a4541_Update_BtLib_version_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e649845)

**Comment by ThaliTester** [comment]
Test 102271039 (e649845) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102271039 build is completed (e649845)

See https://github.com/ThaliTester/TestResults/tree/102271039e649845_Update_BtLib_version_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 102271039e649845(e649845) has failed

See https://github.com/ThaliTester/TestResults/tree/102271039e649845_Update_BtLib_version_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ce7339b)

**Comment by ThaliTester** [comment]
Test 102271039 (ce7339b) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 102271039 build is completed (ce7339b)

See https://github.com/ThaliTester/TestResults/tree/102271039ce7339b_Update_BtLib_version_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c997935)

**Comment by ThaliTester** [comment]
Test 102271039 (c997935) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102271039 build is completed (c997935)

See https://github.com/ThaliTester/TestResults/tree/102271039c997935_Update_BtLib_version_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 102271039c997935(c997935) has failed

See https://github.com/ThaliTester/TestResults/tree/102271039c997935_Update_BtLib_version_evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
Failed because of #1743

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1740#-:-KccKrM1YV2Ti0uhpXKQ:bg7igkv)*

**Pull request merged**
