### PR TITLE
Added leveldown mobile adapter

### LINKED ISSUE #1698: We need to add a custom adapter for pouchb generator instead of fixing doMigrationOne
https://github.com/pouchdb/pouchdb/issues/6065

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1698.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1703)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2fbe94a)

**Comment by ThaliTester** [comment]
Test 99572749 (2fbe94a) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 99572749 build is completed (2fbe94a)

See https://github.com/ThaliTester/TestResults/tree/995727492fbe94a_Added_leveldown_adapter_andrew-aladev/ for the logs

**Comment by chapko** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/utils/leveldownAdapter.js, line 22 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703#-K_A5At1Wps9SYinIAn3:-K_A5At1Wps9SYinIAn4:b-4n0rbv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2fbe94ae63c19e56fb5b17b5a3e0ba056fc81922/thali/NextGeneration/utils/leveldownAdapter.js#L22)):*
> ```JavaScript
>   // We need to replace current leveldown adapter if it exists.
>   var addPreferredAdapter = !PouchDB.adapters['leveldb'];
>   PouchDB.adapter('leveldb', LeveldownAdapter, addPreferredAdapter);
> ```

I don't think we have to replace existing adapter. We can just use unique name, e.g. leveldb-mobile or leveldb-jxcore and pass it to PouchDB constructor via `adapter` option

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9fee306)

**Comment by ThaliTester** [comment]
Test 99572749 (9fee306) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99572749 build is completed (9fee306)

See https://github.com/ThaliTester/TestResults/tree/995727499fee306_Added_leveldown_adapter_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 995727499fee306(9fee306) has failed

See https://github.com/ThaliTester/TestResults/tree/995727499fee306_Added_leveldown_adapter_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d8b6840)

**Comment by ThaliTester** [comment]
Test 99572749 (d8b6840) build started.

**Comment by andrew-aladev** [comment]
Reviewed 2 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/utils/leveldownMobileAdapter.js, line 22 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703#-K_A5At1Wps9SYinIAn3:-K_ZDCrjIyMMFzX-IAqF:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9fee30632143607b6a57aeea09881ca3cd816bee/thali/NextGeneration/utils/leveldownMobileAdapter.js#L22)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

I don't think we have to replace existing adapter. We can just use unique name, e.g. leveldb-mobile or leveldb-jxcore and pass it to PouchDB constructor via `adapter` option
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703)*

**Comment by andrew-aladev** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (eaf5166)

**Comment by ThaliTester** [comment]
Test 99572749 (eaf5166) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 99572749 build is completed (d8b6840)

See https://github.com/ThaliTester/TestResults/tree/99572749d8b6840_Added_leveldown_adapter_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 99572749eaf5166(eaf5166) has failed

See https://github.com/ThaliTester/TestResults/tree/99572749eaf5166_Added_leveldown_adapter_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (48e8cbe)

**Comment by ThaliTester** [comment]
Test 99572749 (48e8cbe) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99572749 build is completed (48e8cbe)

See https://github.com/ThaliTester/TestResults/tree/9957274948e8cbe_Added_leveldown_mobile_adapter_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 9957274948e8cbe(48e8cbe) has failed

See https://github.com/ThaliTester/TestResults/tree/9957274948e8cbe_Added_leveldown_mobile_adapter_andrew-aladev/ for the fail logs

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703#-:-Ka7oRF08QWarRaaa_mW:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/installCustomPouchDB.js, line 162 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703#-Ka9pDwr_MYzO9HiAt5g:-Ka9pDwsfgRe61tZqBKV:bgd4pn3) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/48e8cbe467cb83c6d70250bdad0def79e5962566/test/www/jxcore/installCustomPouchDB.js#L162)):*
> ```JavaScript
>   var gitUrl = 'https://github.com/pouchdb/pouchdb.git';
>   var branch = 'master';
>   var commitId = 'b363f7d2c9ed96e2d341e12446de79ccd8739177';
> ```

Why do we have this change? I thought we aren't using a custom version of PouchDB at this time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703#-:-Ka9pj1G2Hr6K3RgEnAK:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8cdcb4a)

**Comment by ThaliTester** [comment]
Test 99572749 (8cdcb4a) build started.

**Comment by andrew-aladev** [comment]
Reviewed 1 of 1 files at r3, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/installCustomPouchDB.js, line 162 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703#-Ka9pDwr_MYzO9HiAt5g:-KaCHFEJ3fy3pLWDNmdq:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/48e8cbe467cb83c6d70250bdad0def79e5962566/test/www/jxcore/installCustomPouchDB.js#L162)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why do we have this change? I thought we aren't using a custom version of PouchDB at this time?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703)*

**Comment by ThaliTester** [comment]
Test (Success) 99572749 build is completed (8cdcb4a)

See https://github.com/ThaliTester/TestResults/tree/995727498cdcb4a_Added_leveldown_mobile_adapter_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 995727498cdcb4a(8cdcb4a) has failed

See https://github.com/ThaliTester/TestResults/tree/995727498cdcb4a_Added_leveldown_mobile_adapter_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1703)*

**Pull request merged**
