### PR TITLE
#1560 Getting rid of environment variables for Android builds

### PR DESCRIPTION
**Pull request by yaronyg**
install.js - Generate gradle.properties file with the desired android
config values

validateBuildEnvironment - Changed checks for android build tools and
platform sdk to run off values in package.json. Also got rid of
btconnectorlib2 and jxcoreCordova checks because package.json already
controls that. Did some linting too.

package.json - Added new config

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1582)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (759ab65)

**Comment by ThaliTester** [comment]
Test 95813110 (759ab65) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95813110 build is completed (759ab65)

See https://github.com/ThaliTester/TestResults/tree/95813110759ab65__1560_Getting_rid_of_environment_variables_for_Android_builds_yaronyg/ for the logs

**Comment by evabishchevich** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/package.json, line 34 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1582#-KXoSlbXDl0Cgt3BCQau:-KXoSlbXDl0Cgt3BCQav:bxf3w60) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/759ab655a5e691235b34240d7c9edc63d974f461/thali/package.json#L34)):*
> ```JSON
>     },
>     "androidConfig": {
>       "minSdkVersion": "22",
> ```

It should be 21. Android L (5.0) - API 21. API 22 - LOLLIPOP_MR1 (5.1)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1582)*

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1582#-:-KXoZDqo8_7rHKlAXdJd:bnfp4nl)*

**Comment by larryonoff** [comment]
@yaronyg after reviewing this PR I think that we should move most of the versions from validateBuildEnvironment.js into thali/package.json. What do you think?

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1582#-:-KXpOn0bzd7WO4cuQ9WN:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (567bbc2)

**Comment by ThaliTester** [comment]
Test 95813110 (567bbc2) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (eafd18b)

**Comment by ThaliTester** [comment]
Test 95813110 (eafd18b) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95813110 build is completed (eafd18b)

See https://github.com/ThaliTester/TestResults/tree/95813110eafd18b__1560_Getting_rid_of_environment_variables_for_Android_builds_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 95813110567bbc2(567bbc2) has failed

See https://github.com/ThaliTester/TestResults/tree/95813110567bbc2__1560_Getting_rid_of_environment_variables_for_Android_builds_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
Test 95813110eafd18b(eafd18b) has failed

See https://github.com/ThaliTester/TestResults/tree/95813110eafd18b__1560_Getting_rid_of_environment_variables_for_Android_builds_yaronyg/ for the fail logs

**Pull request merged**
