### PR TITLE
Test the fix for failing replication with attachments

### PR DESCRIPTION
**Pull request by jareksl**
This is to check ThaliTest witch the fix for failing replication.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1967)

### CODE REVIEW

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d0aee2c)

**Comment by ThaliTester** [comment]
Test 145917619 (d0aee2c) build started.

**Comment by ThaliTester** [comment]
Test (Success) 145917619 build is completed (d0aee2c)

See https://github.com/ThaliTester/TestResults/tree/145917619d0aee2c_Test_the_fix_for_failing_replication_with_attachments_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 145917619d0aee2c(d0aee2c) has failed

See https://github.com/ThaliTester/TestResults/tree/145917619d0aee2c_Test_the_fix_for_failing_replication_with_attachments_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1a53731)

**Comment by ThaliTester** [comment]
Test 145917619 (1a53731) build started.

**Comment by ThaliTester** [comment]
Test (Success) 145917619 build is completed (1a53731)

See https://github.com/ThaliTester/TestResults/tree/1459176191a53731_Test_the_fix_for_failing_replication_with_attachments_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 1459176191a53731(1a53731) has failed

See https://github.com/ThaliTester/TestResults/tree/1459176191a53731_Test_the_fix_for_failing_replication_with_attachments_jareksl/ for the fail logs

**Comment by jareksl** [comment]
This was temporary solution, it is not needed anylonger

**Pull request closed without merging**
