### PR TITLE
Upgraded socket.io-client to the recent version

### LINKED ISSUE #1179: Upgrade socket.io-client with the latest version
@enricogior said that we have some problems with running `bufferutil` on `jx`. The only reason for us to use `bufferutil` is `socket.io-client 1.3.7`. I've upgraded `socket.io` to version `1.4.8` without problems. But any newer version of `socket.io-client` don't want to work with our current test server. 

We can upgrade `socket.io-client` to any version `>= 1.4.0` and `bufferutil` will disappear.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1179.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1204)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (48040b0)

**Comment by ThaliTester** [comment]
Test (Success) 87137063 build is completed (48040b0)

See https://github.com/ThaliTester/TestResults/tree/8713706348040b0_Upgraded_socket_io-client_to_the_recent_version_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 8713706348040b0(48040b0) has failed

See https://github.com/ThaliTester/TestResults/tree/8713706348040b0_Upgraded_socket_io-client_to_the_recent_version_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ea72b13)

**Comment by ThaliTester** [comment]
Test (Success) 87137063 build is completed (ea72b13)

See https://github.com/ThaliTester/TestResults/tree/87137063ea72b13_Upgraded_socket_io-client_to_the_recent_version_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f317f3a)

**Comment by ThaliTester** [comment]
Test 87137063ea72b13(ea72b13) has failed

See https://github.com/ThaliTester/TestResults/tree/87137063ea72b13_Upgraded_socket_io-client_to_the_recent_version_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87137063 build is completed (f317f3a)

See https://github.com/ThaliTester/TestResults/tree/87137063f317f3a_Upgraded_socket_io-client_to_the_recent_version_andrew-aladev/ for the logs

**Comment by artemjackson** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1204#-:-KSlsRE9OazhFbq-0EuN:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 87137063f317f3a(f317f3a) has failed

See https://github.com/ThaliTester/TestResults/tree/87137063f317f3a_Upgraded_socket_io-client_to_the_recent_version_andrew-aladev/ for the fail logs

**Pull request merged**
