### PR TITLE
#758 Added shrinkwrap files

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/853)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (de3a29b)

**Comment by ThaliTester** [comment]
Test (Fail) 80807573 build is completed (de3a29b)

See https://github.com/ThaliTester/TestResults/tree/80807573de3a29b__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by artemjackson** [comment]
@yaronyg build failed with `ECONNREFUSED` error.
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/jx" "/Users/thali/.jx/npm/bin/npm-cli.js" "--loglevel" "http" "--color" "true" "install" "--build-from-source"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.12
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
``` 
is it a CI issue?

**Comment by yaronyg** [comment]
What the hell is that testBuildOrg crap? Can you please track down where that is coming from? Please work with the Rockwell folks.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (27567ab)

**Comment by artemjackson** [comment]
@yaronyg I found out that the `testBuildOrg` is a directory to which the cloned repository is copied (it is cloned on the host and copied to the VM). The content is later copied to the `testBuild` directory in which the build is executed. 

And as @jareksl noticed: 
> we have seen this issue with "cp: testBuildOrg" before, it should not harm the build

But the actual reason of build failure is that `npm-shrinkwrap.json` has hardcoded npm registry in `resolve` section.
So npm tries to fetch package from `http://localhost:4873` and fails.

The last 27567ab461dd7583d352da03d27b24ebd1cae59d that removes hardcoded registry should solve the problem.

**Comment by ThaliTester** [comment]
Test (Success) 80807573 build is completed (27567ab)

See https://github.com/ThaliTester/TestResults/tree/8080757327567ab__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8080757327567ab(27567ab) has failed

See https://github.com/ThaliTester/TestResults/tree/8080757327567ab__758_Added_shrinkwrap_files_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

But we can only check this in once we get it passing CI.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/853#-:-KPFKWmE-HuBWMavnS4s:b-1ywjzg)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (6be4f0c)

**Comment by ThaliTester** [comment]
Test (Success) 80807573 build is completed (6be4f0c)

See https://github.com/ThaliTester/TestResults/tree/808075736be4f0c__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 808075736be4f0c(6be4f0c) has failed

See https://github.com/ThaliTester/TestResults/tree/808075736be4f0c__758_Added_shrinkwrap_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a62a5c7)

**Comment by ThaliTester** [comment]
Test (Success) 80807573 build is completed (a62a5c7)

See https://github.com/ThaliTester/TestResults/tree/80807573a62a5c7__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 80807573a62a5c7(a62a5c7) has failed

See https://github.com/ThaliTester/TestResults/tree/80807573a62a5c7__758_Added_shrinkwrap_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (0b836a0)

**Comment by ThaliTester** [comment]
Test (Success) 80807573 build is completed (0b836a0)

See https://github.com/ThaliTester/TestResults/tree/808075730b836a0__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 808075730b836a0(0b836a0) has failed

See https://github.com/ThaliTester/TestResults/tree/808075730b836a0__758_Added_shrinkwrap_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3dab9f4)

**Comment by ThaliTester** [comment]
Test (Success) 80807573 build is completed (3dab9f4)

See https://github.com/ThaliTester/TestResults/tree/808075733dab9f4__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 808075733dab9f4(3dab9f4) has failed

See https://github.com/ThaliTester/TestResults/tree/808075733dab9f4__758_Added_shrinkwrap_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (27f5c10)

**Comment by ThaliTester** [comment]
Test (Fail) 80807573 build is completed (27f5c10)

See https://github.com/ThaliTester/TestResults/tree/8080757327f5c10__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8e7a0be)

**Comment by ThaliTester** [comment]
Test (Success) 80807573 build is completed (8e7a0be)

See https://github.com/ThaliTester/TestResults/tree/808075738e7a0be__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 808075738e7a0be(8e7a0be) has failed

See https://github.com/ThaliTester/TestResults/tree/808075738e7a0be__758_Added_shrinkwrap_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a8c39da)

**Comment by ThaliTester** [comment]
Test 80807573a8c39da(a8c39da) has failed

See https://github.com/ThaliTester/TestResults/tree/80807573a8c39da__758_Added_shrinkwrap_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fdd3b64)

**Comment by ThaliTester** [comment]
Test (Success) 80807573 build is completed (fdd3b64)

See https://github.com/ThaliTester/TestResults/tree/80807573fdd3b64__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 80807573fdd3b64(fdd3b64) has failed

See https://github.com/ThaliTester/TestResults/tree/80807573fdd3b64__758_Added_shrinkwrap_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2f454a1)

**Comment by ThaliTester** [comment]
Test (Fail) 80807573 build is completed (2f454a1)

See https://github.com/ThaliTester/TestResults/tree/808075732f454a1__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bc92363)

**Comment by ThaliTester** [comment]
Test (Fail) 80807573 build is completed (bc92363)

See https://github.com/ThaliTester/TestResults/tree/80807573bc92363__758_Added_shrinkwrap_files_artemjackson/ for the logs

**Comment by artemjackson** [comment]
Closed in favour of #905.

**Pull request closed without merging**
