### PR TITLE
V next yarong 417 812 merge v next

### PR DESCRIPTION
**Pull request by yaronyg**
I merged vNext with vNext_yarong_417_812. I then tested both desktop (which passes with V8, not with SM, but those are known issues) as well as doing a full mobile build (which appears to have succeeded). But there are enough changes here that I wanted @larryonoff and @andrew-aladev to take a look before I checked it in.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1003)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8a10bf1)

**Comment by ThaliTester** [comment]
Test (Success) 84389264 build is completed (8a10bf1)

See https://github.com/ThaliTester/TestResults/tree/843892648a10bf1_V_next_yarong_417_812_merge_v_next_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 843892648a10bf1(8a10bf1) has failed

See https://github.com/ThaliTester/TestResults/tree/843892648a10bf1_V_next_yarong_417_812_merge_v_next_yaronyg/ for the fail logs

**Comment by artemjackson** [comment]
@yaronyg check please this [log](https://raw.githubusercontent.com/ThaliTester/TestResults/843892648a10bf1_V_next_yarong_417_812_merge_v_next_yaronyg/thali01_motorola-Nexus%206.md)  and search for `My device`.
You will see an error 
```
Error!: Error when loading file /data/data/com.test.thalitest/files/www/jxcore/bv_tests/testLocalSeqManagerCoordinated.js: Error: Cannot find module '../../thalilogger'
```
that (and some other bugs) I fixed in #936. I highly recommend to merge #936 into #928 and only after that work with `vNext`.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (11e1d40)

**Comment by larryonoff** [comment]
@yaronyg I check this branch and already fixed the post-merge issue that I've found. I'm not sure that @andrew-aladev needs to check it, because all merged changes are mine.

As far as I understand this branch won't build, because there should be changes that @artemjackson did in his branch that fixes #vNext_yarong_417_812 branch.

**Comment by ThaliTester** [comment]
Test (Fail) 84389264 build is completed (11e1d40)

See https://github.com/ThaliTester/TestResults/tree/8438926411e1d40_V_next_yarong_417_812_merge_v_next_yaronyg/ for the logs

**Comment by yaronyg** [comment]
We will try to do this merge later we first want to get #928 working

**Pull request closed without merging**
