### PR TITLE
Update to jxcore-cordova 0.1.0.

### LINKED ISSUE #435: Update to jxcore-cordova 0.1.0

### PR DESCRIPTION
**Pull request by vjrantal**
Fixes #435.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/463)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8793eb6)

**Comment by ThaliTester** [comment]
Test (Success) 56358378 build is completed (8793eb6)

See https://github.com/ThaliTester/TestResults/tree/563583788793eb6_Update_to_jxcore-cordova_0_1_0__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 563583788793eb6(8793eb6) has failed

See https://github.com/ThaliTester/TestResults/tree/563583788793eb6_Update_to_jxcore-cordova_0_1_0__vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
The ios test in CI got stuck in `multiplex can send data`-test, but this isn't due to jxcore-cordova update.

There is an issue somewhere in the test frameworks where sometimes tests don't proceed, but gets stuck.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/463#-:-K8NVBDSsju0AK93ypYl:-1141409038)*

**Comment by vjrantal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/463)*

**Pull request merged**
