### PR TITLE
Implemented forever agent's destroy, peer action's destroy and test

### LINKED ISSUE #1492: Who is eating our connections?
Someone is sitting on our connections and making us run out. Who is it?

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1492.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1496)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3bf7a05)

**Comment by ThaliTester** [comment]
Test (Fail) 92597374 build is completed (3bf7a05)

See https://github.com/ThaliTester/TestResults/tree/925973743bf7a05_Implemented_forever_agent_s_destroy__peer_action_s_destroy_and_test_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
:lgtm: Note however that tests failed. The failure was because the sequence update code couldn't get a TCP connection which really shouldn't have been possible. Note however that I re-ran *all* of build.sh on my local machine and all the tests passed. So this is something transient. Also note that in production this would just cause the replication action to fail and restart which is fine.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliPeerAction.js, line 115 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496#-KW-BCTtHyzSbf5SvVZc:-KW-BCTu_bzD59ilad8W:blvkwoo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3bf7a054291cdff3e3c921f25d0b46a522bf9e32/test/www/jxcore/bv_tests/testThaliPeerAction.js#L115)):*
> ```JavaScript
>     keepAliveMsecs: thaliConfig.TCP_TIMEOUT_WIFI/2,
>     maxSockets: Infinity,
>     maxFreeSockets: 256,
> ```

NB: keepAlive, keepAliveMsecs and maxFreeSockets are all ignored so we can remove them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496#-:-KW-BS48OTkpfJ7VChvm:bdrsudp)*

**Comment by larryonoff** [comment]
@andrew-aladev btw did we create PR for `forever-agent` main repo ?

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (d03a773)

**Comment by chapko** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/package.json, line 26 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496#-KW2HaK9B-eGNjopeLQs:-KW2HaK9B-eGNjopeLQt:b-bpqfpr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d03a7738345a555c2a3ce0d75608a69d6dd4f886/test/www/jxcore/package.json#L26)):*
> ```JSON
>     "express": "4.13.3",
>     "express-pouchdb": "1.0.6-thali",
>     "forever-agent": "https://github.com/thaliproject/forever-agent.git#master",
> ```

It is better to use specific commit SHA.

---

*[thali/package.json, line 10 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496#-KW2IIfJOgaIvQBl3ya9:-KW2IIfJOgaIvQBl3yaA:b-qs5qbo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d03a7738345a555c2a3ce0d75608a69d6dd4f886/thali/package.json#L10)):*
> ```JSON
>     "body-parser": "1.13.3",
>     "express": "4.13.3",
>     "forever-agent": "https://github.com/thaliproject/forever-agent.git#master",
> ```

And here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496)*

**Comment by ThaliTester** [comment]
Test (Fail) 92597374 build is completed (d03a773)

See https://github.com/ThaliTester/TestResults/tree/92597374d03a773_Implemented_forever_agent_s_destroy__peer_action_s_destroy_and_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ebb285d)

**Comment by andrew-aladev** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/package.json, line 26 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496#-KW2HaK9B-eGNjopeLQs:-KW2Wqu0EMPD9Pd1kqQp:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d03a7738345a555c2a3ce0d75608a69d6dd4f886/test/www/jxcore/package.json#L26)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> It is better to use specific commit SHA.
</details>
Done.

---

*[test/www/jxcore/bv_tests/testThaliPeerAction.js, line 115 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496#-KW-BCTtHyzSbf5SvVZc:-KW2WsEll5y54GHruZ0G:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3bf7a054291cdff3e3c921f25d0b46a522bf9e32/test/www/jxcore/bv_tests/testThaliPeerAction.js#L115)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: keepAlive, keepAliveMsecs and maxFreeSockets are all ignored so we can remove them.
</details>
Done.

---

*[thali/package.json, line 10 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496#-KW2IIfJOgaIvQBl3ya9:-KW2Wt4OAkq7OFHHh8E3:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d03a7738345a555c2a3ce0d75608a69d6dd4f886/thali/package.json#L10)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> And here too.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1496)*

**Comment by ThaliTester** [comment]
Test (Fail) 92597374 build is completed (ebb285d)

See https://github.com/ThaliTester/TestResults/tree/92597374ebb285d_Implemented_forever_agent_s_destroy__peer_action_s_destroy_and_test_andrew-aladev/ for the logs

**Pull request merged**
