### PR TITLE
fixing native code to pass thaliMobileNative.js

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1301)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (7ce2662)

**Comment by ThaliTester** [comment]
Test (Fail) 89013374 build is completed (7ce2662)

See https://github.com/ThaliTester/TestResults/tree/890133747ce2662_fixing_native_code_to_pass_thaliMobileNative_js_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b4841d4)

**Comment by ThaliTester** [comment]
Test (Fail) 89013374 build is completed (b4841d4)

See https://github.com/ThaliTester/TestResults/tree/89013374b4841d4_fixing_native_code_to_pass_thaliMobileNative_js_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3ddb6d0)

**Comment by ThaliTester** [comment]
Test (Success) 89013374 build is completed (3ddb6d0)

See https://github.com/ThaliTester/TestResults/tree/890133743ddb6d0_fixing_native_code_to_pass_thaliMobileNative_js_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 890133743ddb6d0(3ddb6d0) has failed

See https://github.com/ThaliTester/TestResults/tree/890133743ddb6d0_fixing_native_code_to_pass_thaliMobileNative_js_baydet/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1301#-:-KU4R1viGmL2MeHm1z_1:bnfp4nl)*

**Comment by dersim-davaod** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1301#-:-KUHwGe2i6Gd7l9kQGR2:bnfp4nl)*

**Comment by baydet** [comment]
will be merged right after #1339 with fixes for failing unit tests

**Pull request merged**
