### PR TITLE
#902 Updated wifiBasedNativeMock for Android

### LINKED ISSUE #902: Updating wifiBasedNativeMock for Android
These changes should update wifiBasedNativeMock so it will work again with the new Android native infrastructure.

- [x] Update our desktop tests so that they run both unit tests and coordinator tests TWICE, once as Android and once as iOS
- [x] Finally implement the code that honors the platform passed into the constructor for wifiBasedNativeMock so that process.platform is overridden and returns the right value when we are on desktop
- [x] The wifiPeerAvailabilityChanged event we will get from the underlying thaliWifiInfrastructure code is now going to return generation and peerID, we need to be ready for that when we process it.
- [x] Update peerAvailabilityChanged to the new syntax (the previous work item will help)

### PR DESCRIPTION
**Pull request by artemjackson**
Closes #902.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1084)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (2e11b7f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (3089a7b)

**Comment by ThaliTester** [comment]
Test (Fail) 85808714 build is completed (3089a7b)

See https://github.com/ThaliTester/TestResults/tree/858087143089a7b__902_Updated_wifiBasedNativeMock_for_Android_artemjackson/ for the logs

**Comment by artemjackson** [comment]
Blocked by #1072. Resubmit when get unblocked.

**Pull request closed without merging**
