### PR TITLE
update ThaliCore.framework logging

### PR DESCRIPTION
**Pull request by larryonoff**
small change related to the issue #1001

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1004)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d97ea8a)

**Comment by ThaliTester** [comment]
Test (Fail) 84473913 build is completed (d97ea8a)

See https://github.com/ThaliTester/TestResults/tree/84473913d97ea8a_update_ThaliCore_framework_logging_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (57c4cea)

**Comment by ThaliTester** [comment]
Test (Fail) 84473913 build is completed (57c4cea)

See https://github.com/ThaliTester/TestResults/tree/8447391357c4cea_update_ThaliCore_framework_logging_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a75cca2)

**Comment by ThaliTester** [comment]
Test (Fail) 84473913 build is completed (a75cca2)

See https://github.com/ThaliTester/TestResults/tree/84473913a75cca2_update_ThaliCore_framework_logging_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (50927cf)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (690e0a5)

**Comment by ThaliTester** [comment]
Test (Fail) 84473913 build is completed (50927cf)

See https://github.com/ThaliTester/TestResults/tree/8447391350927cf_update_ThaliCore_framework_logging_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 84473913 build is completed (690e0a5)

See https://github.com/ThaliTester/TestResults/tree/84473913690e0a5_update_ThaliCore_framework_logging_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (63141ba)

**Comment by ThaliTester** [comment]
Test (Fail) 84473913 build is completed (63141ba)

See https://github.com/ThaliTester/TestResults/tree/8447391363141ba_update_ThaliCore_framework_logging_larryonoff/ for the logs

**Comment by larryonoff** [comment]
Closing this PR due to inactivity. We can work on this later.

**Pull request closed without merging**
