### PR TITLE
fix iOS build that was broken by validateBuildEnvironment.js

### PR DESCRIPTION
**Pull request by larryonoff**
- add ANDROID_HOME check
- update validateBuildEnvironment.js to handle crashes better

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1436)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0805991)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (d664ac4)

**Comment by ThaliTester** [comment]
Test (Fail) 91175308 build is completed (0805991)

See https://github.com/ThaliTester/TestResults/tree/911753080805991_fix_iOS_build_that_was_broken_by_validateBuildEnvironment_js_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 91175308 build is completed (d664ac4)

See https://github.com/ThaliTester/TestResults/tree/91175308d664ac4_fix_iOS_build_that_was_broken_by_validateBuildEnvironment_js_larryonoff/ for the logs

**Comment by larryonoff** [comment]
@yaronyg please review.

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1436#-:-KVR6ShhNijn5KhFcofR:bnfp4nl)*

**Pull request merged**
