### PR TITLE
fix: Wrong calculation of succeed tests in TestRunner #923

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/955)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (21d0a60)

**Comment by larryonoff** [comment]
@baydet please review

**Comment by baydet** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift, line 31 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQSaMz6A3pLB2Gx0Fp:-KQQSaMz6A3pLB2Gx0Fq:b-7qvm91) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift#L31)):*
> ```Swift
>         succeededCount: left.succeededCount + right.succeededCount,
>         totalDuration: left.totalDuration + right.totalDuration,
>         executed: left.executed && right.executed
> ```

I'm not sure if it's a correct case to display `executed: false` for the whole TestRunnerResult if we have for example only one test not executed. Maybe it's  better to replace Bool with Int for now?

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift, line 50 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQTYaj6i8G5-UcJMIi:-KQQTYaj6i8G5-UcJMIj:b5ugqb4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift#L50)):*
> ```Swift
>         do {
>             let jsonData = try NSJSONSerialization.dataWithJSONObject(jsonDictionary, options: [])
>             
> ```

empty trailing spaces. Linter don't like it :)

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift, line 12 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQTibDKP27ECH0YY2f:-KQQTibDKP27ECH0YY2g:bz2nkw3) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift#L12)):*
> ```Swift
> import XCTest
> 
> extension XCTest {
> ```

We have to have tests to be sure this logic works correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955)*

**Comment by ThaliTester** [comment]
Test (Success) 83261120 build is completed (21d0a60)

See https://github.com/ThaliTester/TestResults/tree/8326112021d0a60_fix__Wrong_calculation_of_succeed_tests_in_TestRunner__923_larryonoff/ for the logs

**Comment by larryonoff** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift, line 31 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQSaMz6A3pLB2Gx0Fp:-KQQUtulskg4dgL6dD5V:b-ur00yq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift#L31)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> I'm not sure if it's a correct case to display `executed: false` for the whole TestRunnerResult if we have for example only one test not executed. Maybe it's  better to replace Bool with Int for now?
</details>
Very good catch. What do you think about using operator `+` ?

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift, line 50 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQTYaj6i8G5-UcJMIi:-KQQVLRd5iGdNm-XumMn:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift#L50)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> empty trailing spaces. Linter don't like it :)
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift, line 12 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQTibDKP27ECH0YY2f:-KQQVNEecHpkWSbmqHdm:bkls500) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift#L12)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> We have to have tests to be sure this logic works correctly.
</details>
I agree. I think we need separate task for this. I also think that we should expand test runner into separate library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955)*

**Comment by baydet** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift, line 31 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQSaMz6A3pLB2Gx0Fp:-KQQVxAWn9QmGCmmk9cT:b-b5ewl6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift#L31)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> Very good catch. What do you think about using operator `+` ?
</details>
I don't see anything illegible to have it

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift, line 12 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQTibDKP27ECH0YY2f:-KQQVmkKOWP9NuzCqavm:bnqsc5b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift#L12)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I agree. I think we need separate task for this. I also think that we should expand test runner into separate library.
</details>
No, we should have tests in this PR. Because without tests we cannot be sure that we have correct test results for our ThaliCore library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955)*

**Comment by ThaliTester** [comment]
Test 8326112021d0a60(21d0a60) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8326112021d0a60_fix__Wrong_calculation_of_succeed_tests_in_TestRunner__923_larryonoff/ for the logs

**Comment by larryonoff** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift, line 31 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQSaMz6A3pLB2Gx0Fp:-KQQXLwhxeg2i-RMqPpl:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunnerResult.swift#L31)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> I don't see anything illegible to have it
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (3a07957)

**Comment by ThaliTester** [comment]
Test (Success) 83261120 build is completed (3a07957)

See https://github.com/ThaliTester/TestResults/tree/832611203a07957_fix__Wrong_calculation_of_succeed_tests_in_TestRunner__923_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 832611203a07957(3a07957) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/832611203a07957_fix__Wrong_calculation_of_succeed_tests_in_TestRunner__923_larryonoff/ for the logs

**Comment by yaronyg** [comment]
Per @baydet 's comment. Please add tests to make sure that calculations are correct.

---

Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift, line 12 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQQTibDKP27ECH0YY2f:-KQS8GN75fS5HmPD5LIY:bqm57eh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/21d0a607719aefa89b0ae6d3d277533a7389e21b/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift#L12)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> No, we should have tests in this PR. Because without tests we cannot be sure that we have correct test results for our ThaliCore library.
</details>
What @baydet  said! :)

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift, line 6 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQS8inf8_x8qi5FZUjr:-KQS8ingNsopIBd3mSLm:b-9o4v64) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3a07957934f737374c131c66172f50d647f2d6f8/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift#L6)):*
> ```Swift
> //
> //  Created by Ilya Laryionau on 30/08/16.
> //  Copyright © 2016 Thali. All rights reserved.
> ```

BTW, this needs the Microsoft header. There is no 'thali'. Just Microsoft.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-:-KQSAd8nS8AwqZ7pRO0n:b4uajyb)*

**Comment by larryonoff** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift, line 6 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955#-KQS8inf8_x8qi5FZUjr:-KQUxledvCQbgGDHcUgL:b-mkjyf4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3a07957934f737374c131c66172f50d647f2d6f8/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/XCTest+TestRunnerResult.swift#L6)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> BTW, this needs the Microsoft header. There is no 'thali'. Just Microsoft.
</details>
Xcode templates are weird. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/955)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (b3e784a)

**Comment by ThaliTester** [comment]
Test (Success) 83261120 build is completed (b3e784a)

See https://github.com/ThaliTester/TestResults/tree/83261120b3e784a_fix__Wrong_calculation_of_succeed_tests_in_TestRunner__923_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 83261120b3e784a(b3e784a) has failed

See https://github.com/ThaliTester/TestResults/tree/83261120b3e784a_fix__Wrong_calculation_of_succeed_tests_in_TestRunner__923_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
See the details in #923.

**Pull request closed without merging**
