### PR TITLE
Added emitting  of the incomingConnectionToPortNumberFail event

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1541)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e3bb7ec)

**Comment by ThaliTester** [comment]
Test 94585790 (e3bb7ec) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 94585790 build is completed (e3bb7ec)

See https://github.com/ThaliTester/TestResults/tree/94585790e3bb7ec_Added_emitting__of_the_incomingConnectionToPortNumberFail_event_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
The reason of the failed build is 'Make sure docs replicate' test. It's failed

**Comment by vasilevskayaem** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1541#-:-KX6Y0XEX-L60qHZdO4R:bnfp4nl)*

**Comment by larryonoff** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 615 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1541#-KX6_JzmX1wFqddcJnCj:-KX6_JzmX1wFqddcJnCk:bu76f94) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e3bb7ece847b4b4fb6f20bef29052daa5be3f385/src/android/java/io/jxcore/node/ConnectionHelper.java#L615)):*
> ```Java
>                         final String peerId = who.getPeerProperties().getId();
>                         boolean closed  = mConnectionModel.closeAndRemoveIncomingConnectionThread(incomingSocketThread.getId());
>                         if (! closed){
> ```

NB: fix spaces :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1541)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (7a7b43b)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (bde0874)

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1541#-:-KX6asoQCLgsNT0yFZ2W:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 94585790 (7a7b43b) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 94585790 build is completed (7a7b43b)

See https://github.com/ThaliTester/TestResults/tree/945857907a7b43b_Added_emitting__of_the_incomingConnectionToPortNumberFail_event_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 94585790 (bde0874) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 94585790 build is completed (bde0874)

See https://github.com/ThaliTester/TestResults/tree/94585790bde0874_Added_emitting__of_the_incomingConnectionToPortNumberFail_event_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 615 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1541#-KX6_JzmX1wFqddcJnCj:-KX750IAGA_whhzh55Pw:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e3bb7ece847b4b4fb6f20bef29052daa5be3f385/src/android/java/io/jxcore/node/ConnectionHelper.java#L615)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> NB: fix spaces :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1541)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1541#-:-KX8ZfvvSp_QSV53sDE4:bnfp4nl)*

**Comment by yaronyg** [comment]
Oh and please get this to pass CI first.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1541#-:-KX8Zi803QxbF8yMSSru:bowrts1)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (a9b3b31)

**Comment by ThaliTester** [comment]
Test 94585790 (a9b3b31) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 94585790 build is completed (a9b3b31)

See https://github.com/ThaliTester/TestResults/tree/94585790a9b3b31_Added_emitting__of_the_incomingConnectionToPortNumberFail_event_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (9181791)

**Comment by ThaliTester** [comment]
Test 94585790 (9181791) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 94585790 build is completed (9181791)

See https://github.com/ThaliTester/TestResults/tree/945857909181791_Added_emitting__of_the_incomingConnectionToPortNumberFail_event_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
We couldn't pass CI because tests failed even in master

**Pull request merged**
