### PR TITLE
Disable wifi only tests for non-wifi-only network type

### PR DESCRIPTION
**Pull request by chapko**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1400)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ceb91b2)

**Comment by ThaliTester** [comment]
Test (Success) 90350722 build is completed (ceb91b2)

See https://github.com/ThaliTester/TestResults/tree/90350722ceb91b2_Disable_wifi_only_tests_for_non-wifi-only_network_type_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 90350722ceb91b2(ceb91b2) has failed

See https://github.com/ThaliTester/TestResults/tree/90350722ceb91b2_Disable_wifi_only_tests_for_non-wifi-only_network_type_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1400#-:-KUsvjnTxKu8KSiIDVsk:bg7igkv)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2a91229)

**Comment by chapko** [comment]
Well, after merging with master this PR doesn't contain any changes :)

**Comment by ThaliTester** [comment]
Test (Success) 90350722 build is completed (2a91229)

See https://github.com/ThaliTester/TestResults/tree/903507222a91229_Disable_wifi_only_tests_for_non-wifi-only_network_type_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 903507222a91229(2a91229) has failed

See https://github.com/ThaliTester/TestResults/tree/903507222a91229_Disable_wifi_only_tests_for_non-wifi-only_network_type_chapko/ for the fail logs

**Pull request closed without merging**
