### PR TITLE
Fixes coordinated test colors

### PR DESCRIPTION
**Pull request by juhanak**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/690)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (aaa3c62)

**Comment by vjrantal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/690)*

**Comment by ThaliTester** [comment]
Test (Success) 64746945 build is completed (aaa3c62)

See https://github.com/ThaliTester/TestResults/tree/64746945aaa3c62_Fixes_coordinated_test_colors_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 64746945aaa3c62(aaa3c62) has failed

See https://github.com/ThaliTester/TestResults/tree/64746945aaa3c62_Fixes_coordinated_test_colors_juhanak/ for the fail logs

**Pull request merged**
