### PR TITLE
Move off JXcore where we can

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1200)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (bd3eefa)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (f514987)

**Comment by ThaliTester** [comment]
Test (Fail) 87119404 build is completed (bd3eefa)

See https://github.com/ThaliTester/TestResults/tree/87119404bd3eefa_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (f514987)

See https://github.com/ThaliTester/TestResults/tree/87119404f514987_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 87119404f514987(f514987) has failed

See https://github.com/ThaliTester/TestResults/tree/87119404f514987_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1fa6a20)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (1fa6a20)

See https://github.com/ThaliTester/TestResults/tree/871194041fa6a20_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 871194041fa6a20(1fa6a20) has failed

See https://github.com/ThaliTester/TestResults/tree/871194041fa6a20_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f33de82)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (f33de82)

See https://github.com/ThaliTester/TestResults/tree/87119404f33de82_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 87119404f33de82(f33de82) has failed

See https://github.com/ThaliTester/TestResults/tree/87119404f33de82_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1e88130)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c2545ff)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (76d75bd)

**Comment by ThaliTester** [comment]
Test (Fail) 87119404 build is completed (1e88130)

See https://github.com/ThaliTester/TestResults/tree/871194041e88130_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 87119404 build is completed (c2545ff)

See https://github.com/ThaliTester/TestResults/tree/87119404c2545ff_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (1577438)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (76d75bd)

See https://github.com/ThaliTester/TestResults/tree/8711940476d75bd_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 8711940476d75bd(76d75bd) has failed

See https://github.com/ThaliTester/TestResults/tree/8711940476d75bd_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (1577438)

See https://github.com/ThaliTester/TestResults/tree/871194041577438_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 871194041577438(1577438) has failed

See https://github.com/ThaliTester/TestResults/tree/871194041577438_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3d55d96)

**Comment by ThaliTester** [comment]
Test (Fail) 87119404 build is completed (3d55d96)

See https://github.com/ThaliTester/TestResults/tree/871194043d55d96_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (41b1e30)

**Comment by ThaliTester** [comment]
Test (Fail) 87119404 build is completed (41b1e30)

See https://github.com/ThaliTester/TestResults/tree/8711940441b1e30_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d8677d0)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (d8677d0)

See https://github.com/ThaliTester/TestResults/tree/87119404d8677d0_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 87119404d8677d0(d8677d0) has failed

See https://github.com/ThaliTester/TestResults/tree/87119404d8677d0_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
@yaronyg please review it. I believe that we're close on merging it into master.

**Comment by yaronyg** [comment]
Please just resolve the two issues (both are the same problem in two different places) I raised and then :lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/installCordovaPlugin.js, line 25 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1200#-KTozCEtuN8XsTXJ32yp:-KTozCEtuN8XsTXJ32yq:b-9jifdu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d8677d0108a73345a07a0eb8c2e828d2992b11ee/thali/installCordovaPlugin.js#L25)):*
> ```JavaScript
>   }
>   var installDirectory = path.join(__dirname, 'install');
>   exec('npm install --no-optional --production & find . -name "*.gz" -delete',
> ```

I'm concerned that if the npm install fails then the & will cause the failure to be swallowed and the find will be run. Please either confirm that a failure on the part of the npm install is guaranteed to make the exec fail with an error or please split this into two serial calls to exec.

---

*[thali/install/install.js, line 388 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1200#-KTozX_-q8yRrxpt2SfN:-KTozX_-q8yRrxpt2SfO:bqgs2gs) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d8677d0108a73345a07a0eb8c2e828d2992b11ee/thali/install/install.js#L388)):*
> ```JavaScript
>             console.log('Running npm install in: ' + appScriptsFolder);
>             return childProcessExecPromise(
>               'npm install --no-optional --production & find . -name "*.gz" -delete',
> ```

Same issue as above. We have to be sure that if the npm install fails that childProcessExecPromise will fail. But I suspect the '&' will cause the failure to be swallowed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1200#-:-KTozlejJfSoGq1ymoyZ:b8geixb)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ba2fff0)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (ba2fff0)

See https://github.com/ThaliTester/TestResults/tree/87119404ba2fff0_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 87119404ba2fff0(ba2fff0) has failed

See https://github.com/ThaliTester/TestResults/tree/87119404ba2fff0_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (96e8238)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6935740)

**Comment by ThaliTester** [comment]
Test (Fail) 87119404 build is completed (96e8238)

See https://github.com/ThaliTester/TestResults/tree/8711940496e8238_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a2adb60)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (0e26dea)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (6935740)

See https://github.com/ThaliTester/TestResults/tree/871194046935740_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 87119404 build is completed (a2adb60)

See https://github.com/ThaliTester/TestResults/tree/87119404a2adb60_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 871194046935740(6935740) has failed

See https://github.com/ThaliTester/TestResults/tree/871194046935740_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (0e26dea)

See https://github.com/ThaliTester/TestResults/tree/871194040e26dea_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 871194040e26dea(0e26dea) has failed

See https://github.com/ThaliTester/TestResults/tree/871194040e26dea_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (40dbe46)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (74d511d)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (40dbe46)

See https://github.com/ThaliTester/TestResults/tree/8711940440dbe46_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (74d511d)

See https://github.com/ThaliTester/TestResults/tree/8711940474d511d_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 8711940440dbe46(40dbe46) has failed

See https://github.com/ThaliTester/TestResults/tree/8711940440dbe46_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test 8711940474d511d(74d511d) has failed

See https://github.com/ThaliTester/TestResults/tree/8711940474d511d_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
@yaronyg could you please review this PR again. Since I've added new file `thali/install/utils/child_process.js`.

**Comment by larryonoff** [comment]
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/installCordovaPlugin.js, line 25 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1200#-KTozCEtuN8XsTXJ32yp:-KTt56inMM749-ifNQXu:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ba2fff022aa8dbff52bdf6b6d38d4f8a3e2a1fca/thali/installCordovaPlugin.js#L25)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> I'm concerned that if the npm install fails then the & will cause the failure to be swallowed and the find will be run. Please either confirm that a failure on the part of the npm install is guaranteed to make the exec fail with an error or please split this into two serial calls to exec.
</details>
Done.

---

*[thali/install/install.js, line 388 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1200#-KTozX_-q8yRrxpt2SfN:-KTt57u8ByvG8W0FWWnE:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ba2fff022aa8dbff52bdf6b6d38d4f8a3e2a1fca/thali/install/install.js#L388)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Same issue as above. We have to be sure that if the npm install fails that childProcessExecPromise will fail. But I suspect the '&' will cause the failure to be swallowed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1200)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (282d012)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (282d012)

See https://github.com/ThaliTester/TestResults/tree/87119404282d012_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 87119404282d012(282d012) has failed

See https://github.com/ThaliTester/TestResults/tree/87119404282d012_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1200#-:-KU-1NWWCi6Nu8QvCumx:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (34e5bd3)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0d915df)

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (34e5bd3)

See https://github.com/ThaliTester/TestResults/tree/8711940434e5bd3_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 8711940434e5bd3(34e5bd3) has failed

See https://github.com/ThaliTester/TestResults/tree/8711940434e5bd3_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87119404 build is completed (0d915df)

See https://github.com/ThaliTester/TestResults/tree/871194040d915df_Move_off_JXcore_where_we_can_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 871194040d915df(0d915df) has failed

See https://github.com/ThaliTester/TestResults/tree/871194040d915df_Move_off_JXcore_where_we_can_larryonoff/ for the fail logs

**Pull request merged**
