### PR TITLE
Update jxcore-cordova to 0.1.14 version, update readme.md

### PR DESCRIPTION
**Pull request by jareksl**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1959)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8f8a044)

**Comment by ThaliTester** [comment]
Test 137464031 (8f8a044) build started.

**Comment by ThaliTester** [comment]
Test (Success) 137464031 build is completed (8f8a044)

See https://github.com/ThaliTester/TestResults/tree/1374640318f8a044_Update_jxcore-cordova_to_0_1_14_version__update_readme_md_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 1374640318f8a044(8f8a044) has failed

See https://github.com/ThaliTester/TestResults/tree/1374640318f8a044_Update_jxcore-cordova_to_0_1_14_version__update_readme_md_jareksl/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1959)*

**Comment by mlesnic** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1959#-:-KsN-rO08uNAd03Rlg11:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1959#-:-KsOs6zfVtJ9uqm-NkFC:bnfp4nl)*

**Pull request merged**
