### PR TITLE
Added nodessdp restart test

### LINKED ISSUE #1345: Need to enhance node logic to turn off Wifi based advertising and listening when we don't have a SSID

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1345.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1571)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (894c132)

**Comment by ThaliTester** [comment]
Test 95190072 (894c132) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95190072 build is completed (894c132)

See https://github.com/ThaliTester/TestResults/tree/95190072894c132_Added_nodessdp_restart_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 95190072894c132(894c132) has failed

See https://github.com/ThaliTester/TestResults/tree/95190072894c132_Added_nodessdp_restart_test_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1571#-:-KXgJrQKmNCIr8jPOA-z:bnfp4nl)*

**Pull request merged**
