### PR TITLE
Fixed missing closing parenthesis.

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1865)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (000941d)

**Comment by ThaliTester** [comment]
Test 120541759 (000941d) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 120541759 build is completed (000941d)

See https://github.com/ThaliTester/TestResults/tree/120541759000941d_Fixed_missing_closing_parenthesis__dersim-davaod/ for the logs

**Comment by jareksl** [comment]
:lgtm: I have created  a separate issue #1864 for two failing tests `Single coordinated request ios native` and `Multiple coordinated request ios native`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1865#-:-KkACzGH9xzmDGF6KKdq:bkabhyc)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1865#-:-KkBzZJ-r3DpKEhfEUtK:bnfp4nl)*

**Pull request merged**
