### PR TITLE
Get native tests working in coordinator

### PR DESCRIPTION
**Pull request by yaronyg**
This assumes that we will take #561 to vNext. Once we do then this would be the next one to review and merge.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/606)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5dc9f88)

**Comment by ThaliTester** [comment]
Test (Success) 62328822 build is completed (5dc9f88)

See https://github.com/ThaliTester/TestResults/tree/623288225dc9f88_Get_native_tests_working_in_coordinator_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 623288225dc9f88(5dc9f88) has failed

See https://github.com/ThaliTester/TestResults/tree/623288225dc9f88_Get_native_tests_working_in_coordinator_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
@vjrantal It passed appveyor

**Comment by ThaliTester** [comment]
Test 62328822054c831(054c831) has failed

See https://github.com/ThaliTester/TestResults/tree/62328822054c831_Get_native_tests_working_in_coordinator_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/606)*

**Pull request merged**
