### PR TITLE
Handshake implementation

### PR DESCRIPTION
**Pull request by tompaana**
Tested/verified to work.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/577)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 90 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBP_-nWCSnXdSms62GJ:-KBP_-nWCSnXdSms62GK:-273371082) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L90)):*
(Note: NB stands for Non-Blocking, meaning you can respond or not, it's cool)
NB: I don't suppose I could convince you to sneak in a 'return false' here rather than putting in a big if statement below?

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 162 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPaRr5wtLVQ2nkIPFa:-KBPaRr5wtLVQ2nkIPFb:-763372116) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L162)):*
Isn't it at least in theory possible that we got fewer bytes than the handshake message and it might require two or more calls to onBytesRead before we get the entire message?

Also couldn't the 'garbage at the end' be actual real data triggered by our own handshake working on the other side? In which case are we throwing away real data? How do we make sure that only the handshake bytes are consumed and the rest of the data is sent along?

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 230 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPb4IGm7zpl_RcdstS:-KBPb4IHsBs6RnWI1Wyd:-2048160425) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L230)):*
Seriously, do you hate for loops or something? Why not just use for (HandshakeConnection connection : mHandshakConnections) {} or equivalent?

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 253 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPbkzTSjMTOdcA72Y-:-KBPbkzTSjMTOdcA72Y0:-29604730) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L253)):*
Shouldn't this be mIsShuttingDown since it's only a failure if we aren't shutting down?

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 293 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPc1-33Mf1ZhwjReVZ:-KBPc1-33Mf1ZhwjReV_:-1243259329) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L293)):*
For.... right?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577)*

**Comment by tompaana** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 90 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBP_-nWCSnXdSms62GJ:-KBRXmxVrqYZbwINEXAt:-1380357924) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L90)):*
A 'return false' snuck in.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 162 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPaRr5wtLVQ2nkIPFa:-KBRZTRHP2GIsJvv1U0l:166237359) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L162)):*
In theory it is possible. But my gut says we are in deep shit already, if we can't get 15 bytes (the length of the handshake message) through with one attempt. I can shorter the message to one byte (as in spec) if you think that would be better.

The garbage could be real data - again in theory. Would it help if I set the buffer size to match the handshake message length? It's now 256.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 230 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPb4IGm7zpl_RcdstS:-KBRWNVRutWlXD_ijAQf:-1933160963) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L230)):*
No, for loops are fun. Fixed.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 253 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPbkzTSjMTOdcA72Y-:-KBRV1haUKBSO4UVELhk:1899284406) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L253)):*
Good catch! Fixed.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 293 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPc1-33Mf1ZhwjReVZ:-KBRWRtVaeMewsqBC1cP:56131508) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L293)):*
This I'm not sure about. It's tested. It works. Altering the content of a container in for loop just seems unsafe - even if it weren't in this case. Iterator provides the snapshot. It's two lines of more code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577)*

**Comment by yaronyg** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 162 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPaRr5wtLVQ2nkIPFa:-KBVQ7QbxHZdlwIGBG5_:186397304) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L162)):*
Nope, your guess that we can get at least 15 bytes across sounds exactly right. I found docs claiming that the minimum guaranteed MTU for L2CAP is 48 bytes and the default is 672 bytes and then I found a random doc from Microsoft claiming that the RFCOMM MTU Is somehow driven by the LC2CAP MTU so we should be peachy. Sorry for the false alarm.

But the real data is really scary. This is how you get impossible to debug errors. We have to be super careful with the data we get from the byte stream. We have to have some management mechanism that recognizes that the first 15 bytes only goes to handshake and everything else goes to the application level. Please walk me through exactly how we make this happen. This is too important to screw around with.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577)*

**Comment by tompaana** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 162 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPaRr5wtLVQ2nkIPFa:-KBXInN8RzKZVeXjAfYU:-1166661955) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L162)):*
How'bout we set the buffer size to match the handshake message length? We have the method for setting the buffer size already in place. That said, it is very unlikely that the other peer would be fast enough to handle its part of the handshake and start sending data.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 162 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577#-KBPaRr5wtLVQ2nkIPFa:-KBiLLrBY1VN_s5f-BT_:-941280207) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b050ccfa57f526faed043e30588e5fc992d57f49/src/android/java/io/jxcore/node/HandshakeHelper.java#L162)):*
Let's be paranoid and change the buffer to be the exact size and then close this PR. tomorrow you can walk me through the code so I understand how we are sure that no extra data will be lost or duplicated.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/577)*

**Comment by tompaana** [comment]
The last fix for this issue is in a separate branch for issue #576.

**Pull request merged**
