### PR TITLE
Disable tests failing on iOS

### PR DESCRIPTION
**Pull request by chapko**
Related issues:
- #1531
- #1613
- #1618

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1623)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (23bc6d7)

**Comment by ThaliTester** [comment]
Test 97288533 (23bc6d7) build started.

**Comment by ThaliTester** [comment]
Test (Success) 97288533 build is completed (23bc6d7)

See https://github.com/ThaliTester/TestResults/tree/9728853323bc6d7_Disable_tests_failing_on_iOS_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 9728853323bc6d7(23bc6d7) has failed

See https://github.com/ThaliTester/TestResults/tree/9728853323bc6d7_Disable_tests_failing_on_iOS_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1623#-:-KYtZJeJFQzn-732ayi4:bnfp4nl)*

**Pull request merged**
