### PR TITLE
Slightly less bad

### PR DESCRIPTION
**Pull request by yaronyg**
There is an enormous amount of work to do in order to clean up the mux layer's outgoing connection support. I have 12 issues in my personal list and that is without having done a proper audit of all the connections. But we have already checked in a bunch of this code and this version should (famous last words) be better than what we have now.

See the comments on the commits for a summary of the changes

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/628)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (92b8613)

**Comment by ThaliTester** [comment]
Test (Fail) 63008475 build is completed (92b8613)

See https://github.com/ThaliTester/TestResults/tree/6300847592b8613_Slightly_less_bad_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dba4423)

**Comment by ThaliTester** [comment]
Test (Fail) 63008475 build is completed (dba4423)

See https://github.com/ThaliTester/TestResults/tree/63008475dba4423_Slightly_less_bad_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d624ed8)

**Comment by ThaliTester** [comment]
Test (Success) 63008475 build is completed (d624ed8)

See https://github.com/ThaliTester/TestResults/tree/63008475d624ed8_Slightly_less_bad_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 63008475d624ed8(d624ed8) has failed

See https://github.com/ThaliTester/TestResults/tree/63008475d624ed8_Slightly_less_bad_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
@yaronyg: The CI build failure yesterday was not due to the changes in the PR. I today made some improvements to the build machine and hopefully we wouldn't see the same error again - will keep monitoring the situation.

I pushed a small linting commit onto this branch to retrigger and this time all tests passed on both platforms so from that perspective this commit it good to go in.

I did not do a full code review, because fully understanding all the muxing code would require spending some amount of time with the review. If you absolutely want a full review before merging this, please assign back. Otherwise, from my perspective, this can be merged since there is anyways some amount of todo-tests and such that needs to be written.

**Pull request merged**
