### PR TITLE
Use a custom build of jxcore-cordova

### PR DESCRIPTION
**Pull request by vjrantal**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/630)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3a3bebd)

**Comment by vjrantal** [comment]
@cicorias: Can you do a code review for this? A thing to note is that if this gets in, there must always be a valid binary behind `https://jxcore.azureedge.net/0312/debug/io.jxcore.node.jx` or otherwise builds start failing in CI. I would have wanted to use something like `https://jxcore.azureedge.net/0312/release/io.jxcore.node.jx` instead, but I could not find any other working URL than the one I put to the code in this PR.

**Comment by ThaliTester** [comment]
Test (Success) 63036995 build is completed (3a3bebd)

See https://github.com/ThaliTester/TestResults/tree/630369953a3bebd_Use_a_custom_build_of_jxcore-cordova_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 630369953a3bebd(3a3bebd) has failed

See https://github.com/ThaliTester/TestResults/tree/630369953a3bebd_Use_a_custom_build_of_jxcore-cordova_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d8239c5)

**Comment by ThaliTester** [comment]
Test (Fail) 63036995 build is completed (d8239c5)

See https://github.com/ThaliTester/TestResults/tree/63036995d8239c5_Use_a_custom_build_of_jxcore-cordova_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6c4182b)

**Comment by cicorias** [comment]
i modified the path and pushed another commit to your branch...  

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/630#-:-KD-FjzidodW8WGjGpIu:1235429637)*

**Comment by ThaliTester** [comment]
Test (Fail) 63036995 build is completed (6c4182b)

See https://github.com/ThaliTester/TestResults/tree/630369956c4182b_Use_a_custom_build_of_jxcore-cordova_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 63036995 build is completed (6c4182b)

See https://github.com/ThaliTester/TestResults/tree/630369956c4182b_Use_a_custom_build_of_jxcore-cordova_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (fb62ea7)

**Comment by ThaliTester** [comment]
Test (Success) 63036995 build is completed (fb62ea7)

See https://github.com/ThaliTester/TestResults/tree/63036995fb62ea7_Use_a_custom_build_of_jxcore-cordova_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 63036995fb62ea7(fb62ea7) has failed

See https://github.com/ThaliTester/TestResults/tree/63036995fb62ea7_Use_a_custom_build_of_jxcore-cordova_vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/630)*

**Pull request merged**
