### PR TITLE
#823 DO_NOT_MERGE CI issue with new networkChanged function

### PR DESCRIPTION
**Pull request by dersim-davaod**
This PR is temporary and it won't be merged.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/999)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e3ffea4)

**Comment by ThaliTester** [comment]
Test (Success) 84265062 build is completed (e3ffea4)

See https://github.com/ThaliTester/TestResults/tree/84265062e3ffea4__823_CI_issue_with_new_networkChanged_function_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 84265062e3ffea4(e3ffea4) has failed

See https://github.com/ThaliTester/TestResults/tree/84265062e3ffea4__823_CI_issue_with_new_networkChanged_function_dersim-davaod/ for the fail logs

**Comment by dersim-davaod** [comment]
I found out the reason of issue so I'm moving this ticket into Done.
Results are in https://zube.io/projects/3188/cards/173462613

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bba4ad4)

**Comment by ThaliTester** [comment]
Test (Success) 84265062 build is completed (bba4ad4)

See https://github.com/ThaliTester/TestResults/tree/84265062bba4ad4__823_DO_NOT_MERGE_CI_issue_with_new_networkChanged_function_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 84265062bba4ad4(bba4ad4) has failed

See https://github.com/ThaliTester/TestResults/tree/84265062bba4ad4__823_DO_NOT_MERGE_CI_issue_with_new_networkChanged_function_dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d118465)

**Comment by ThaliTester** [comment]
Test 84265062d118465(d118465) has failed

See https://github.com/ThaliTester/TestResults/tree/84265062d118465__823_DO_NOT_MERGE_CI_issue_with_new_networkChanged_function_dersim-davaod/ for the fail logs

**Pull request closed without merging**
