### PR TITLE
Update Cordova only in CI

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/518)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9949e65)

**Comment by ThaliTester** [comment]
Test (Fail) 58608551 build is completed (9949e65)

See https://github.com/ThaliTester/TestResults/tree/586085519949e65_Update_Cordova_only_in_CI_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a5e7595)

**Comment by ThaliTester** [comment]
Test (Fail) 58608551 build is completed (a5e7595)

See https://github.com/ThaliTester/TestResults/tree/58608551a5e7595_Update_Cordova_only_in_CI_vjrantal/ for the logs

**Comment by juhanak** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/518)*

**Pull request merged**
