### PR TITLE
#899 ThaliMobile.disconnect implementation

### PR DESCRIPTION
**Pull request by chapko**
Part of #899 issue

*Note*: It should be merged only after LGTM on #1512 PR.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1513)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (2b1de9f)

**Comment by ThaliTester** [comment]
Test (Fail) 93371675 build is completed (2b1de9f)

See https://github.com/ThaliTester/TestResults/tree/933716752b1de9f_ThaliMobile_disconnect_implementation_chapko/ for the logs

**Comment by yaronyg** [comment]
Please get to pass build in CI and then :lgtm: 

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1513#-:-KW_5JGBwxF11F2J2iF_:btdirzk)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (01c216f)

**Comment by ThaliTester** [comment]
Test 93371675 (01c216f) build started.

**Comment by ThaliTester** [comment]
Test 93371675 (01c216f) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93371675 build is completed (01c216f)

See https://github.com/ThaliTester/TestResults/tree/9337167501c216f_ThaliMobile_disconnect_implementation_chapko/ for the logs

**Pull request closed without merging**
