### PR TITLE
fix API docs for Replication Manager

### PR DESCRIPTION
**Pull request by mohlsen**
ThaliReplicationManager.start was incorrectly documented.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/433)

### CODE REVIEW

**Comment by yaronyg** [comment]
Note that in the future this file will be gone. We are switching to using jsdoc so that errors like this will automatically be detected by the linter. Now if we could just change to typescript....

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/433)*

**Comment by mohlsen** [comment]
@yaronyg gotta start with contributions somewhere!

**Comment by yaronyg** [comment]
:) Welcome to the party!

**Pull request merged**
