### PR TITLE
Fixed the state error and updated the Bluetooth connector library version

### PR DESCRIPTION
**Pull request by tompaana**
This change is [Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/615)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e7cbba2)

**Comment by ThaliTester** [comment]
Test (Success) 62560673 build is completed (e7cbba2)

See https://github.com/ThaliTester/TestResults/tree/62560673e7cbba2_Fixed_the_state_error_and_updated_the_Bluetooth_connector_library_version_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 62560673e7cbba2(e7cbba2) has failed

See https://github.com/ThaliTester/TestResults/tree/62560673e7cbba2_Fixed_the_state_error_and_updated_the_Bluetooth_connector_library_version_tompaana/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 86 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/615#-KCawfJ35MjXBFLE_2s4:-KCawfJ35MjXBFLE_2s5:-1772783358) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e7cbba2da5be2dd2daa207fce2414582049eb181/src/android/java/io/jxcore/node/ConnectionHelper.java#L86)):*
We have a connection helper that can't really help because we don't have Bluetooth. It seems to me that an exception is appropriate and that we should just catch that exception and report the problem back up to Node?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/615)*

**Comment by tompaana** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 86 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/615#-KCawfJ35MjXBFLE_2s4:-KCeTPNxoX_ryj3QksxL:-1933808706) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e7cbba2da5be2dd2daa207fce2414582049eb181/src/android/java/io/jxcore/node/ConnectionHelper.java#L86)):*
When we threw errors, I think Ville wasn't able to catch them - probably because JXcoreExtensions.LoadExtensions() fails since that is the place where we construct ConnectionHelper. However, even when we don't throw an exception, there is that Android specific node code to check if BLE is supported and start method return the expected error code (radios not supported).

OK?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/615)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a3c76e9)

**Comment by ThaliTester** [comment]
Test (Success) 62560673 build is completed (a3c76e9)

See https://github.com/ThaliTester/TestResults/tree/62560673a3c76e9_Fixed_the_state_error_and_updated_the_Bluetooth_connector_library_version_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 62560673a3c76e9(a3c76e9) has failed

See https://github.com/ThaliTester/TestResults/tree/62560673a3c76e9_Fixed_the_state_error_and_updated_the_Bluetooth_connector_library_version_tompaana/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/615)*

**Pull request merged**
