### PR TITLE
BT and WiFi always turned on before running tests. #953

### PR DESCRIPTION
**Pull request by mlesnic**
BT and WiFi are now always turned on before running any tests.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/958)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (0c49e11)

**Comment by ThaliTester** [comment]
Test (Fail) 83276082 build is completed (0c49e11)

See https://github.com/ThaliTester/TestResults/tree/832760820c49e11_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (953d005)

**Comment by ThaliTester** [comment]
Test (Success) 83276082 build is completed (953d005)

See https://github.com/ThaliTester/TestResults/tree/83276082953d005_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 83276082953d005(953d005) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/83276082953d005_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/UnitTest_app.js, line 15 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958#-KQSNUWutXmVsuT1UEKv:-KQSNUWvvvKdvD8yuo_i:b3gwfn1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/953d005a430c01c6aa97e68b3fdb0e506973efff/test/www/jxcore/UnitTest_app.js#L15)):*
> ```JavaScript
> var testUtils = require('./lib/testUtils');
> var ThaliMobile = require('thali/NextGeneration/thaliMobile');
> var Promise = require('lie');
> ```

Please run this file with any ide that supports JSHint and JSCS because the current file fails a bunch of linter rules. Webstorm, VSCode, Atom, etc. all have support. Although Atom's support kind of sucks.

---

*[test/www/jxcore/UnitTest_app.js, line 28 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958#-KQSN8_DITR65FjGL5QP:-KQSN8_DITR65FjGL5QQ:b-ycxcwo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/953d005a430c01c6aa97e68b3fdb0e506973efff/test/www/jxcore/UnitTest_app.js#L28)):*
> ```JavaScript
>         }
>       
>         Promise.all(promiseList)
> ```

Where is the catch for this so that if there is a problem turning things on we can catch the error and fail the test with an appropriate error message?

---

*[test/www/jxcore/UnitTest_app.js, line 30 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958#-KQSN2np0UAmScLcDNCW:-KQSN2nq5zqwOqYBHzlB:b-wd7pck) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/953d005a430c01c6aa97e68b3fdb0e506973efff/test/www/jxcore/UnitTest_app.js#L30)):*
> ```JavaScript
>         Promise.all(promiseList)
>             .then(function () {
>             Mobile('executeNativeTests').callNative(function (result) {
> ```

Please indent this line beyond the '.then' so it's clear that it is contained within the then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958)*

**Comment by mlesnic** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/UnitTest_app.js, line 28 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958#-KQSN8_DITR65FjGL5QP:-KQUaIGrqb2cgaXSADdK:b-2ue666) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/953d005a430c01c6aa97e68b3fdb0e506973efff/test/www/jxcore/UnitTest_app.js#L28)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Where is the catch for this so that if there is a problem turning things on we can catch the error and fail the test with an appropriate error message?
</details>
Will be added.

---

*[test/www/jxcore/UnitTest_app.js, line 30 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958#-KQSN2np0UAmScLcDNCW:-KQUaK0K6t5ZZdeQzsig:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/953d005a430c01c6aa97e68b3fdb0e506973efff/test/www/jxcore/UnitTest_app.js#L30)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Please indent this line beyond the '.then' so it's clear that it is contained within the then.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3d6df89)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (8839a22)

**Comment by ThaliTester** [comment]
Test (Success) 83276082 build is completed (3d6df89)

See https://github.com/ThaliTester/TestResults/tree/832760823d6df89_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 832760823d6df89(3d6df89) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/832760823d6df89_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 83276082 build is completed (8839a22)

See https://github.com/ThaliTester/TestResults/tree/832760828839a22_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 832760828839a22(8839a22) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/832760828839a22_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by yaronyg** [comment]
Please fix the issue with the promise name and catch, make sure the change passes CI and then :LGTM:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/UnitTest_app.js, line 15 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958#-KReEzBOX9R6UcmZDWNK:-KReEzBOX9R6UcmZDWNL:b-cszfg0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8839a22b9b9855be009991336964c12c2e201fec/test/www/jxcore/UnitTest_app.js#L15)):*
> ```JavaScript
> var testUtils = require('./lib/testUtils');
> var ThaliMobile = require('thali/NextGeneration/thaliMobile');
> var radiosPromise = require('lie');
> ```

Please just call this Promise as it is our standard Promise library and future developers will know what to expect.

---

*[test/www/jxcore/UnitTest_app.js, line 68 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958#-KReF81PSIsUZ5b9HiOS:-KReF81Q9146lP_3e6P6:b-y4bfvx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8839a22b9b9855be009991336964c12c2e201fec/test/www/jxcore/UnitTest_app.js#L68)):*
> ```JavaScript
>       });
>     });
>   }, function (err) {
> ```

Please use .catch and do not use the second function call to handle errors. We want to keep a consistent style in the project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/958#-:-KReFOXMMrKHZqkuB_sW:b-4u1bvy)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (2fa00ad)

**Comment by ThaliTester** [comment]
Test (Fail) 83276082 build is completed (2fa00ad)

See https://github.com/ThaliTester/TestResults/tree/832760822fa00ad_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (be030e3)

**Comment by ThaliTester** [comment]
Test (Success) 83276082 build is completed (be030e3)

See https://github.com/ThaliTester/TestResults/tree/83276082be030e3_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 83276082be030e3(be030e3) has failed

See https://github.com/ThaliTester/TestResults/tree/83276082be030e3_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (d331142)

**Comment by ThaliTester** [comment]
Test (Success) 83276082 build is completed (d331142)

See https://github.com/ThaliTester/TestResults/tree/83276082d331142_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 83276082d331142(d331142) has failed

See https://github.com/ThaliTester/TestResults/tree/83276082d331142_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the fail logs

**Comment by mlesnic** [comment]
It passed on all android devices.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e94149a)

**Comment by ThaliTester** [comment]
Test (Success) 83276082 build is completed (e94149a)

See https://github.com/ThaliTester/TestResults/tree/83276082e94149a_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 83276082e94149a(e94149a) has failed

See https://github.com/ThaliTester/TestResults/tree/83276082e94149a_BT_and_WiFi_always_turned_on_before_running_tests___953_mlesnic/ for the fail logs

**Pull request closed without merging**
