### PR TITLE
Master yarong 1446 retries fix

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1483)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7d7ee3f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (a6fea97)

**Comment by ThaliTester** [comment]
Test (Fail) 92249550 build is completed (7d7ee3f)

See https://github.com/ThaliTester/TestResults/tree/922495507d7ee3f_Master_yarong_1446_retries_fix_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 92249550 build is completed (a6fea97)

See https://github.com/ThaliTester/TestResults/tree/92249550a6fea97_Master_yarong_1446_retries_fix_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c9056e1)

**Comment by ThaliTester** [comment]
Test (Success) 92249550 build is completed (c9056e1)

See https://github.com/ThaliTester/TestResults/tree/92249550c9056e1_Master_yarong_1446_retries_fix_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 92249550c9056e1(c9056e1) has failed

See https://github.com/ThaliTester/TestResults/tree/92249550c9056e1_Master_yarong_1446_retries_fix_yaronyg/ for the fail logs

**Comment by chapko** [comment]
Reviewed 1 of 4 files at r1, 9 of 12 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/mux/thaliTcpServersManager.js, line 314 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1483#-KViypsyGSAUGwjPEXKz:-KViypsyGSAUGwjPEXL-:b6csq14) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c9056e187877090f41178d54431008ff72471ccf/thali/NextGeneration/mux/thaliTcpServersManager.js#L314)):*
> ```JavaScript
>     var peerServer = this._peerServers[peerIdentifier];
>     if (peerServer && peerServer.server.address().port === port) {
>       createPeerListener.closeServer(this, peerServer.server, error, true);
> ```

It is possible that caller won't pass any `error` to the `recreatePeerListener`. In this case peerAvailabilityChanged event won't be fired with `peerAvailable:false`

---

*[thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js, line 199 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1483#-KVizDjms4okLDtFCnyp:-KVizDjms4okLDtFCnyq:b-f98c04) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c9056e187877090f41178d54431008ff72471ccf/thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js#L199)):*
> ```JavaScript
>             thaliMobileNativeWrapper._getServersManager()
>               .recreatePeerListener(
>                 peerId,
> ```

`peerId` does not exist anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1483)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (abf9100)

**Comment by chapko** [comment]
@yaronyg I added some fixes during code reviewing (one of them fixes my own implementation faults), all other changes are LGTM, so if my fixes are OK, feel free to merge everything into master.

**Comment by ThaliTester** [comment]
Test (Success) 92249550 build is completed (abf9100)

See https://github.com/ThaliTester/TestResults/tree/92249550abf9100_Master_yarong_1446_retries_fix_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 92249550abf9100(abf9100) has failed

See https://github.com/ThaliTester/TestResults/tree/92249550abf9100_Master_yarong_1446_retries_fix_yaronyg/ for the fail logs

**Pull request merged**
