### PR TITLE
Disable node tests for iOS

### PR DESCRIPTION
**Pull request by dersim-davaod**
Main issue is #1353.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1354)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a9cd264)

**Comment by ThaliTester** [comment]
Test (Success) 89786516 build is completed (a9cd264)

See https://github.com/ThaliTester/TestResults/tree/89786516a9cd264_Disable_node_tests_for_iOS_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 89786516a9cd264(a9cd264) has failed

See https://github.com/ThaliTester/TestResults/tree/89786516a9cd264_Disable_node_tests_for_iOS_dersim-davaod/ for the fail logs

**Comment by baydet** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1354#-:-KUMXsNG29mpZlEKVjw6:bnfp4nl)*

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1354#-:-KUMXxB9boPjkfHWYk05:bnfp4nl)*

**Pull request merged**
