### PR TITLE
#696 Recreate listeners

### PR DESCRIPTION
**Pull request by yaronyg**
If we get a local failure in a listener then the top layers have no way to reconnect to the remote peer
until another peer availability event is fired. That is supremely unreliable so now when we get a listener
failure, if it's recoverable, we will just create a new listener that the code can connect to. Also fixed bugs
in our connection clean up code that I found while testing this feature.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/703)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (73f7970)

**Comment by ThaliTester** [comment]
Test (Success) 65394839 build is completed (73f7970)

See https://github.com/ThaliTester/TestResults/tree/6539483973f7970__696_Recreate_listeners_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 6539483973f7970(73f7970) has failed

See https://github.com/ThaliTester/TestResults/tree/6539483973f7970__696_Recreate_listeners_yaronyg/ for the fail logs

**Comment by cicorias** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[thali/NextGeneration/mux/createPeerListener.js, line 86 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/703#-KEhy1ui7OefBAOWVRGO:-KEhy1uj3EbMIQ0tpilm:536886833) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/73f79709c7009da97f8004843c66a2a18281a3e3/thali/NextGeneration/mux/createPeerListener.js#L86)):*
are any of these cpu / io blocking? - the destroy's ?  should these be nextick?

---

*[thali/NextGeneration/mux/createPeerListener.js, line 137 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/703#-KEhyDhsP0pg-5G7Fbnz:-KEhyDhtS7KoarMdq08e:83098491) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/73f79709c7009da97f8004843c66a2a18281a3e3/thali/NextGeneration/mux/createPeerListener.js#L137)):*
is logger IO bound? does it handle next tick?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/703)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[thali/NextGeneration/mux/createPeerListener.js, line 86 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/703#-KEhy1ui7OefBAOWVRGO:-KEhz-RAH9bEuga8O-Dc:1203178071) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/73f79709c7009da97f8004843c66a2a18281a3e3/thali/NextGeneration/mux/createPeerListener.js#L86)):*
My understanding is that destroy is non-blocking.

---

*[thali/NextGeneration/mux/createPeerListener.js, line 137 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/703#-KEhyDhsP0pg-5G7Fbnz:-KEhzwwuP4tEZcSz4jhk:1105111495) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/73f79709c7009da97f8004843c66a2a18281a3e3/thali/NextGeneration/mux/createPeerListener.js#L137)):*
IN a sense it shouldn't matter only because if logging isn't set to debug then the call should fail out as soon as it tests state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/703)*

**Pull request merged**
