### PR TITLE
#899 ThaliMobile.getPeerHostInfo implementation

### PR DESCRIPTION
**Pull request by chapko**
Part of #899 issue

*Note*: It should be merged only after LGTM on #1487 PR.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1512)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (76958ec)

**Comment by ThaliTester** [comment]
Test (Fail) 93371269 build is completed (76958ec)

See https://github.com/ThaliTester/TestResults/tree/9337126976958ec_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the logs

**Comment by yaronyg** [comment]
Once you clean up the comments and get the build to pass in CI then :lgtm:

---

Reviewed 1 of 5 files at r1, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotificationAction.js, line 102 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_25xFDwrcKs99NiF4:-KW_25xFDwrcKs99NiF5:b-z9080e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/test/www/jxcore/bv_tests/testThaliNotificationAction.js#L102)):*
> ```JavaScript
> 
> var stubs = [];
> function stub() {
> ```

NB: This just makes me want to cry. Isn't this what sandboxes were invented for? Oh well....

---

*[test/www/jxcore/bv_tests/testThaliPullReplicationFromNotificationCoordinated.js, line 11 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_38-M8EAjANPX7F89:-KW_38-M8EAjANPX7F8A:byfy0hg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/test/www/jxcore/bv_tests/testThaliPullReplicationFromNotificationCoordinated.js#L11)):*
> ```JavaScript
> var tape      = require('../lib/thaliTape');
> 
> var platform                             = require('thali/NextGeneration/utils/platform');
> ```

Why is platform being added when it isn't used anywhere?

---

*[test/www/jxcore/lib/testUtils.js, line 747 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_3PnUAI2KcFkvroKI:-KW_3PnUAI2KcFkvroKJ:bamkrkv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/test/www/jxcore/lib/testUtils.js#L747)):*
> ```JavaScript
> };
> 
> module.exports.poll = function (predicate, options) {
> ```

It doesn't seem like anyone actually calls this function

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 12 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_-rODUruqEfKQo789:-KW_-rODUruqEfKQo78A:b-1g7dwp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/thaliMobileNativeWrapper.js#L12)):*
> ```JavaScript
> var https = require('https');
> var thaliConfig = require('./thaliConfig');
> var guid = require('./utils/guid');
> ```

Per my previous comment please change this to UUID (remember, UUID === GUID)

---

*[thali/NextGeneration/notification/thaliNotificationAction.js, line 114 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_-PN8DNCLRLJvTTiK:-KW_-PN9sLIpbKB-W4Yf:bt1nut6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/notification/thaliNotificationAction.js#L114)):*
> ```JavaScript
>   return p
>     .then(function () {
>       return ThaliMobile.getPeerHostInfo(
> ```

If getPeerHostInfo fails for some reason we will never call self._complete() and thus never update the statue of the event. So the events state won't be marked as failed. How did this get past testing? Don't we need a test that shows that if getPeerHostInfo fails that we will properly clean up?

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 228 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWZzHzKvAyMa3f8UMWg:-KWZzHzLgpshn6NHLNJ7:b-xutx5g) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/notification/thaliNotificationClient.js#L228)):*
> ```JavaScript
>     }
> 
>     if (!peerStatus.peerAvailable) {
> ```

NB: The old IF statement was there to make sure we had a properly formatted peerStatus. The check really should have been an assert though.

---

*[thali/NextGeneration/utils/guid.js, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWZyzybimmNeQZwibNl:-KWZyzycRpdg4JQL9ZSh:b-5081v7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/utils/guid.js#L1)):*
> ```JavaScript
> /**
> ```

We already support a UUID library called UUID so we shouldn't need this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-:-KW_3cjyDX8CrtnOYd2-:b-f5hc6w)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (bf5abdc)

**Comment by ThaliTester** [comment]
Test (Fail) 93371269 build is completed (bf5abdc)

See https://github.com/ThaliTester/TestResults/tree/93371269bf5abdc_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the logs

**Comment by chapko** [comment]
Review status: 11 of 13 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/bv_tests/testThaliNotificationAction.js, line 102 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_25xFDwrcKs99NiF4:-KWbs98CRgP46DY25k5t:b-jjd5co) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/test/www/jxcore/bv_tests/testThaliNotificationAction.js#L102)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: This just makes me want to cry. Isn't this what sandboxes were invented for? Oh well....
</details>
Yes, sandbox makes it look a bit cleaner, but it definitely should be done at the test framework level (I'm talking about #1347)

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 12 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_-rODUruqEfKQo789:-KWbsYM_LowxjU1WDhrT:bvbw69s) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/thaliMobileNativeWrapper.js#L12)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Per my previous comment please change this to UUID (remember, UUID === GUID)
</details>
I removed `multiConnect` implementation entirely, it has been already implemented by Igor in #897.

---

*[thali/NextGeneration/notification/thaliNotificationAction.js, line 114 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_-PN8DNCLRLJvTTiK:-KWbvEMz75YjEXn681c-:b-r8gb20) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/notification/thaliNotificationAction.js#L114)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> If getPeerHostInfo fails for some reason we will never call self._complete() and thus never update the statue of the event. So the events state won't be marked as failed. How did this get past testing? Don't we need a test that shows that if getPeerHostInfo fails that we will properly clean up?
</details>
Tests didn't fail because it was managed by peer pool manager, if action.start fails, peer pool manager just kills it.

`getPeerHostInfo` may fail for different reasons. If it fails because peer is not in availability cache then notification client has already got 'peerAvailabilityChanged' event and killed this action completely and we don't need to do it manually. But if it fails because of `multiConnect` failures it is not clear for me what resolution this action should have. Depending on resolution `notificationClient` can schedule retry for this action or just ignore it.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 228 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWZzHzKvAyMa3f8UMWg:-KWcOMLGOZ_vcDGla5ak:b-pu6bpb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/notification/thaliNotificationClient.js#L228)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: The old IF statement was there to make sure we had a properly formatted peerStatus. The check really should have been an assert though.
</details>
I think I don't understand this comment completely. Old `if (peerStatus.hostAddress && peerStatus.portNumber)` is an equivalent of the new `if (peerStatus.peerAvailable)`. Do you suggest to add asserts for `connectionType` and `suggestedTCPTimeout` fields?

---

*[test/www/jxcore/bv_tests/testThaliPullReplicationFromNotificationCoordinated.js, line 11 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_38-M8EAjANPX7F89:-KWcPhXQmhOtrHNfuONU:b-r4ieq6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/test/www/jxcore/bv_tests/testThaliPullReplicationFromNotificationCoordinated.js#L11)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Why is platform being added when it isn't used anywhere?
</details>
I used it in skip function but then forgot to remove.
Fixed.

---

*[test/www/jxcore/lib/testUtils.js, line 747 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_3PnUAI2KcFkvroKI:-KWcPrHZBgeYwV2nrC7q:b-av023g) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/test/www/jxcore/lib/testUtils.js#L747)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> It doesn't seem like anyone actually calls this function
</details>
Yes, removed.

---

*[thali/NextGeneration/utils/guid.js, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWZyzybimmNeQZwibNl:-KWcQJWflTMOWgpIhuud:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/utils/guid.js#L1)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> We already support a UUID library called UUID so we shouldn't need this file.
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d9d2d87)

**Comment by ThaliTester** [comment]
Test (Success) 93371269 build is completed (d9d2d87)

See https://github.com/ThaliTester/TestResults/tree/93371269d9d2d87_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 93371269d9d2d87(d9d2d87) has failed

See https://github.com/ThaliTester/TestResults/tree/93371269d9d2d87_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 4 of 5 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliNotificationAction.js, line 114 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_-PN8DNCLRLJvTTiK:-KWe5Tv55OStAoGHAjy_:b-yodzko) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/notification/thaliNotificationAction.js#L114)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> Tests didn't fail because it was managed by peer pool manager, if action.start fails, peer pool manager just kills it.
> 
> `getPeerHostInfo` may fail for different reasons. If it fails because peer is not in availability cache then notification client has already got 'peerAvailabilityChanged' event and killed this action completely and we don't need to do it manually. But if it fails because of `multiConnect` failures it is not clear for me what resolution this action should have. Depending on resolution `notificationClient` can schedule retry for this action or just ignore it.
</details>
I think in all cases we need to call _complete. It is designed to be idempotent so calling it multiple times shouldn't hurt and it makes sure we clean up after we have failed. The real question is - do we need to return a resolution that will trigger a retry or not? Issue #1526 is meant to answer that question for us.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 228 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWZzHzKvAyMa3f8UMWg:-KWe9Osj0ivmBbnzVzNV:b-aitjlr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/notification/thaliNotificationClient.js#L228)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> I think I don't understand this comment completely. Old `if (peerStatus.hostAddress && peerStatus.portNumber)` is an equivalent of the new `if (peerStatus.peerAvailable)`. Do you suggest to add asserts for `connectionType` and `suggestedTCPTimeout` fields?
</details>
Yup... that was what I was musing on.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 12 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_-rODUruqEfKQo789:-KWe9e-1lbi8rAHLqUGj:b-m4zq84) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/thaliMobileNativeWrapper.js#L12)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> I removed `multiConnect` implementation entirely, it has been already implemented by Igor in #897.
</details>
So does that mean that we can't check this in until #1479 is checked in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0a22074)

**Comment by chapko** [comment]
Review status: 7 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 228 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWZzHzKvAyMa3f8UMWg:-KWh0oWncfNZDPTEH7C9:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/notification/thaliNotificationClient.js#L228)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Yup... that was what I was musing on.
</details>
Done.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 12 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KW_-rODUruqEfKQo789:-KWgjEweWsVCeWpC7_QO:b-7ni7h7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76958ec084d0168970a1166f9bfd72bf4fb9aa80/thali/NextGeneration/thaliMobileNativeWrapper.js#L12)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> So does that mean that we can't check this in until #1479 is checked in?
</details>
No, we can check it in without `multiConnect`, this branch is not related to iOS thaliMobileNativeWrapper changes, but I just realized I don't have a test for iOS behavior so I added one more test in testThaliMobile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512)*

**Comment by ThaliTester** [comment]
Test (Success) 93371269 build is completed (0a22074)

See https://github.com/ThaliTester/TestResults/tree/933712690a22074_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 933712690a22074(0a22074) has failed

See https://github.com/ThaliTester/TestResults/tree/933712690a22074_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6ecca49)

**Comment by ThaliTester** [comment]
Test (Success) 93371269 build is completed (6ecca49)

See https://github.com/ThaliTester/TestResults/tree/933712696ecca49_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 933712696ecca49(6ecca49) has failed

See https://github.com/ThaliTester/TestResults/tree/933712696ecca49_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the fail logs

**Comment by yaronyg** [comment]
Please fix the throw in particular and then :lgtm:

---

Reviewed 1 of 4 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliNotificationAction.js, line 120 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWjKqIz2hnyXZEUNnSI:-KWjKqIz2hnyXZEUNnSJ:b-hpj2q8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6ecca49247b7a67cc9e2b01def12691efc7c7ce2/thali/NextGeneration/notification/thaliNotificationAction.js#L120)):*
> ```JavaScript
>         self.getPeerIdentifier(),
>         self.getConnectionType()
>       ).catch(function (error) {
> ```

NB: For style consistency the '.catch' is usually on the next line and indented out. Think of it as a poor person's await. :)

---

*[thali/NextGeneration/notification/thaliNotificationAction.js, line 122 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWjKzKElPYg_R1f_Suy:-KWjKzKElPYg_R1f_Suz:by8mvpw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6ecca49247b7a67cc9e2b01def12691efc7c7ce2/thali/NextGeneration/notification/thaliNotificationAction.js#L122)):*
> ```JavaScript
>       ).catch(function (error) {
>         self._complete(ThaliNotificationAction.ActionResolution.BAD_PEER);
>         throw error;
> ```

Let's not throw. We should stay consistent. Promises return promises. Not exceptions. So how about 'return Promise.reject(error);'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-:-KWjOV4AQ9Bn4VWYqH6Q:bbb11td)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c81e6ec)

**Comment by ThaliTester** [comment]
Test 93371269 (c81e6ec) build started.

**Comment by chapko** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliNotificationAction.js, line 120 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWjKqIz2hnyXZEUNnSI:-KWscrOkQ2VsVlsv8Ela:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6ecca49247b7a67cc9e2b01def12691efc7c7ce2/thali/NextGeneration/notification/thaliNotificationAction.js#L120)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: For style consistency the '.catch' is usually on the next line and indented out. Think of it as a poor person's await. :)
</details>
Fixed

---

*[thali/NextGeneration/notification/thaliNotificationAction.js, line 122 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-KWjKzKElPYg_R1f_Suy:-KWsdrEV_weexgCjXz_i:bfjkiii) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6ecca49247b7a67cc9e2b01def12691efc7c7ce2/thali/NextGeneration/notification/thaliNotificationAction.js#L122)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Let's not throw. We should stay consistent. Promises return promises. Not exceptions. So how about 'return Promise.reject(error);'?
</details>
I used `throw` just because it is shorter. But I totally agree to be consistent here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512)*

**Comment by ThaliTester** [comment]
Test (Success) 93371269 build is completed (c81e6ec)

See https://github.com/ThaliTester/TestResults/tree/93371269c81e6ec_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 93371269c81e6ec(c81e6ec) has failed

See https://github.com/ThaliTester/TestResults/tree/93371269c81e6ec_ThaliMobile_getPeerHostInfo_implementation_chapko/ for the fail logs

**Comment by yaronyg** [comment]
Still :lgtm: Note that I didn't need to do a second review on this because I already cleared you with a :lgtm: once you fixed the issues. So you could have just fixed them and then submitted.

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1512#-:-KWtzSYFEsysGu9__AvH:bxnyezm)*

**Pull request closed without merging**
