### PR TITLE
#916 Set-up node tests for Android and iOS

### PR DESCRIPTION
**Pull request by artemjackson**
Started from the PR #936. Closes the issue #916.

PR aims:

- [x] Merge vNext_yarong_417_812 with #913/#914

- [x] Make sure UnitTest_App.js will run node tests (this really should have been fixed in vNext_yarong_417_812 but just in case be sure)

- [ ] Re-apply shrinkwrap

Currently this implementation works only when `networkTypes` list ( see `UnitTest_app.js`) contains single network type. Android and iOS tests run for `NATIVE` and `WIFI` network type respectively. 

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/941)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (e824c1c)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (e824c1c)

See https://github.com/ThaliTester/TestResults/tree/82912030e824c1c__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (fcfeca2)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (fcfeca2)

See https://github.com/ThaliTester/TestResults/tree/82912030fcfeca2__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4eb3be2)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (4eb3be2)

See https://github.com/ThaliTester/TestResults/tree/829120304eb3be2__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (629aac4)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (629aac4)

See https://github.com/ThaliTester/TestResults/tree/82912030629aac4__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d0e406f)

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (d0e406f)

See https://github.com/ThaliTester/TestResults/tree/82912030d0e406f__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 82912030d0e406f(d0e406f) has failed

See https://github.com/ThaliTester/TestResults/tree/82912030d0e406f__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bdacf14)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (bdacf14)

See https://github.com/ThaliTester/TestResults/tree/82912030bdacf14__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (aa3e545)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (aa3e545)

See https://github.com/ThaliTester/TestResults/tree/82912030aa3e545__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (4df63d9)

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (4df63d9)

See https://github.com/ThaliTester/TestResults/tree/829120304df63d9__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 829120304df63d9(4df63d9) has failed

See https://github.com/ThaliTester/TestResults/tree/829120304df63d9__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fa224b6)

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (fa224b6)

See https://github.com/ThaliTester/TestResults/tree/82912030fa224b6__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 82912030fa224b6(fa224b6) has failed

See https://github.com/ThaliTester/TestResults/tree/82912030fa224b6__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9a78d5a)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4bed7b1)

**Comment by artemjackson** [comment]
@yaronyg, @evabishchevich and I ran this PR on three Android devices and got success.
See the [log](https://gist.github.com/evabishchevich/4dd359bf7ed0d5082f35c0b8e12277fc) for more details.

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (9a78d5a)

See https://github.com/ThaliTester/TestResults/tree/829120309a78d5a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (4bed7b1)

See https://github.com/ThaliTester/TestResults/tree/829120304bed7b1__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 829120309a78d5a(9a78d5a) has failed

See https://github.com/ThaliTester/TestResults/tree/829120309a78d5a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test 829120304bed7b1(4bed7b1) has failed

See https://github.com/ThaliTester/TestResults/tree/829120304bed7b1__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cdf6f6e)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (cdf6f6e)

See https://github.com/ThaliTester/TestResults/tree/82912030cdf6f6e__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d4c3c3e)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (d4c3c3e)

See https://github.com/ThaliTester/TestResults/tree/82912030d4c3c3e__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8800f9e)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (8800f9e)

See https://github.com/ThaliTester/TestResults/tree/829120308800f9e__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (2824559)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (2824559)

See https://github.com/ThaliTester/TestResults/tree/829120302824559__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c36b21a)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (64a8f9d)

**Comment by ThaliTester** [comment]
Test 82912030c36b21a(c36b21a) has failed

See https://github.com/ThaliTester/TestResults/tree/82912030c36b21a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (64a8f9d)

See https://github.com/ThaliTester/TestResults/tree/8291203064a8f9d__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (351196c)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (aff0b78)

**Comment by ThaliTester** [comment]
Test (Fail) 82912030 build is completed (351196c)

See https://github.com/ThaliTester/TestResults/tree/82912030351196c__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8291203064a8f9d(64a8f9d) has failed

See https://github.com/ThaliTester/TestResults/tree/8291203064a8f9d__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (aff0b78)

See https://github.com/ThaliTester/TestResults/tree/82912030aff0b78__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f17cf99)

**Comment by ThaliTester** [comment]
Test 82912030aff0b78(aff0b78) has failed

See https://github.com/ThaliTester/TestResults/tree/82912030aff0b78__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (f17cf99)

See https://github.com/ThaliTester/TestResults/tree/82912030f17cf99__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (648592a)

**Comment by ThaliTester** [comment]
Test 82912030f17cf99(f17cf99) has failed

See https://github.com/ThaliTester/TestResults/tree/82912030f17cf99__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (648592a)

See https://github.com/ThaliTester/TestResults/tree/82912030648592a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 82912030648592a(648592a) has failed

See https://github.com/ThaliTester/TestResults/tree/82912030648592a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5478790)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c90465a)

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (5478790)

See https://github.com/ThaliTester/TestResults/tree/829120305478790__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (c90465a)

See https://github.com/ThaliTester/TestResults/tree/82912030c90465a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 829120305478790(5478790) has failed

See https://github.com/ThaliTester/TestResults/tree/829120305478790__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (9e2869a)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (be204d2)

**Comment by ThaliTester** [comment]
Test 82912030c90465a(c90465a) has failed

See https://github.com/ThaliTester/TestResults/tree/82912030c90465a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (9e2869a)

See https://github.com/ThaliTester/TestResults/tree/829120309e2869a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (be204d2)

See https://github.com/ThaliTester/TestResults/tree/82912030be204d2__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 829120309e2869a(9e2869a) has failed

See https://github.com/ThaliTester/TestResults/tree/829120309e2869a__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test 82912030be204d2(be204d2) has failed

See https://github.com/ThaliTester/TestResults/tree/82912030be204d2__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (02d4a60)

**Comment by yaronyg** [comment]
Reviewed 17 of 17 files at r1.
Review status: 15 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/941)*

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/941)*

**Comment by ThaliTester** [comment]
Test (Success) 82912030 build is completed (02d4a60)

See https://github.com/ThaliTester/TestResults/tree/8291203002d4a60__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8291203002d4a60(02d4a60) has failed

See https://github.com/ThaliTester/TestResults/tree/8291203002d4a60__916_Set-up_node_tests_for_Android_and_iOS_artemjackson/ for the fail logs

**Pull request merged**
