### PR TITLE
Revert disconnect changes

### PR DESCRIPTION
**Pull request by chapko**
I have no idea how I missed it during code review.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1842)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ad55a3e)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (cda3355)

**Comment by ThaliTester** [comment]
Test 112066071 (ad55a3e) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 112066071 build is completed (ad55a3e)

See https://github.com/ThaliTester/TestResults/tree/112066071ad55a3e_Revert_disconnect_changes_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 112066071 (cda3355) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 112066071 build is completed (cda3355)

See https://github.com/ThaliTester/TestResults/tree/112066071cda3355_Revert_disconnect_changes_chapko/ for the logs

**Comment by jareksl** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1842#-:-KfuadY8eOASioCqrXj-:bg7igkv)*

**Comment by jareksl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1842)*

**Pull request merged**
