### PR TITLE
#899_1 Implemented 'disconnect'

### PR DESCRIPTION
**Pull request by artemjackson**
Includes #1118. So the [diff between this and #1118](https://github.com/thaliproject/Thali_CordovaPlugin/compare/vNext_yarong_417_812_artemjackson_899_0...vNext_yarong_417_812_artemjackson_899_1) may be useful.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1120)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (15fd190)

**Comment by ThaliTester** [comment]
Test (Fail) 86330306 build is completed (15fd190)

See https://github.com/ThaliTester/TestResults/tree/8633030615fd190__899_1_Implemented__disconnect__artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c7a531c)

**Comment by ThaliTester** [comment]
Test (Success) 86330306 build is completed (c7a531c)

See https://github.com/ThaliTester/TestResults/tree/86330306c7a531c__899_1_Implemented__disconnect__artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86330306c7a531c(c7a531c) has failed

See https://github.com/ThaliTester/TestResults/tree/86330306c7a531c__899_1_Implemented__disconnect__artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
Isn't this overridden by #1129?

---

Reviewed 11 of 14 files at r1.
Review status: 11 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1120#-:-KSJ5IVbgPVCuUI-dMmo:b-6jvtc0)*

**Comment by artemjackson** [comment]
@yaronyg Yes, it is overridden by #1129.

**Comment by yaronyg** [comment]
@artemjackson Can then please close this?

**Pull request closed without merging**
