### PR TITLE
Story001 fix muxserverbridgetest

### PR DESCRIPTION
**Pull request by tobybrad**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/440)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (75263c8)

**Comment by ThaliTester** [comment]
Test (Success) 55902202 build is completed (75263c8)

See https://github.com/ThaliTester/TestResults/tree/5590220275263c8_Story001_fix_muxserverbridgetest_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 5590220275263c8(75263c8) has failed

See https://github.com/ThaliTester/TestResults/tree/5590220275263c8_Story001_fix_muxserverbridgetest_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f27eba5)

**Comment by ThaliTester** [comment]
Test (Success) 55902202 build is completed (f27eba5)

See https://github.com/ThaliTester/TestResults/tree/55902202f27eba5_Story001_fix_muxserverbridgetest_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 55902202f27eba5(f27eba5) has failed

See https://github.com/ThaliTester/TestResults/tree/55902202f27eba5_Story001_fix_muxserverbridgetest_tobybrad/ for the fail logs

**Comment by yaronyg** [comment]
@tobybrad Any update on this PR?

**Comment by tobybrad** [comment]
This should have been fixed with the recent improvement to test server coordination.

**Pull request closed without merging**
