### PR TITLE
fixing AppContext discovering itself.

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1241)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2c267bc)

**Comment by ThaliTester** [comment]
Test (Success) 87859799 build is completed (2c267bc)

See https://github.com/ThaliTester/TestResults/tree/878597992c267bc_fixing_AppContext_discovering_itself__baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 878597992c267bc(2c267bc) has failed

See https://github.com/ThaliTester/TestResults/tree/878597992c267bc_fixing_AppContext_discovering_itself__baydet/ for the fail logs

**Comment by larryonoff** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 16 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1241#-KTE5w8l4nUw4TJtk1if:-KTE5w8l4nUw4TJtk1ig:bqkcm0v) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2c267bc2a3de80edb3aaf8b77684fe09fedb2ca3/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L16)):*
> ```Swift
>     private let disposeAdvertiserTimeout: NSTimeInterval
>     private let serviceType: String
>     internal private(set) var advertiserIdentifiers: [PeerIdentifier] = []
> ```

NB: should it be `Atomic<[PeerIdentifier]>` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1241)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1241#-:-KTGq5x39MgvgmzKmC9C:bnfp4nl)*

**Comment by baydet** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 16 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1241#-KTE5w8l4nUw4TJtk1if:-KTJbF9Zs0GcQWnyPUZF:b6u35rr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2c267bc2a3de80edb3aaf8b77684fe09fedb2ca3/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L16)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> NB: should it be `Atomic<[PeerIdentifier]>` ?
</details>
Not necessary since all Cordova calls to native are going on single thread. It means we will haven't race conditions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1241)*

**Comment by larryonoff** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1241#-:-KTJgw9BOf-z2jpbR_us:bnfp4nl)*

**Pull request merged**
