### PR TITLE
#973 Added thaliPromise

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/980)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8934fe4)

**Comment by ThaliTester** [comment]
Test (Fail) 83625713 build is completed (8934fe4)

See https://github.com/ThaliTester/TestResults/tree/836257138934fe4_Added_thaliPromise_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e686769)

**Comment by ThaliTester** [comment]
Test (Fail) 83625713 build is completed (e686769)

See https://github.com/ThaliTester/TestResults/tree/83625713e686769_Added_thaliPromise_artemjackson/ for the logs

**Comment by artemjackson** [comment]
How did this PR fail when parent branch passes?!

**Comment by artemjackson** [comment]
Closed in favour of #980

**Comment by artemjackson** [comment]
favour

**Comment by artemjackson** [comment]
Please submitt this PR to vNext_yarong_417_812

**Comment by yaronyg** [comment]
@artemjackson I would run one more check for any wild 'lie' usages that might have snuck into super branch since this was created but if you don't find any then if this passes build (not device test) then please check in. :lgtm: 

---

Reviewed 49 of 49 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/980#-:-KS9EyZxRyt8JeG4kwLX:b-5a68j7)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (330e177)

**Comment by artemjackson** [comment]
@yaronyg 
@chapko @andrew-aladev and I decided to use [Bluebird](https://github.com/petkaantonov/bluebird) as `Promise` library because in fact it's the [fastest](https://github.com/petkaantonov/bluebird/tree/master/benchmark) and featured `Promise` library that we have for today. We already decided not to use any wrappers like `ThaliPromise` for it because we are using some of 'bluebird' extra functionality that is not described in [Promise/A+](https://promisesaplus.com/) spec (e.g. `finaly`, `timeout`, etc).

**Comment by ThaliTester** [comment]
Test (Fail) 83625713 build is completed (330e177)

See https://github.com/ThaliTester/TestResults/tree/83625713330e177__973_Added_thaliPromise_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (65361c0)

**Comment by ThaliTester** [comment]
Test (Fail) 83625713 build is completed (65361c0)

See https://github.com/ThaliTester/TestResults/tree/8362571365361c0__973_Added_thaliPromise_artemjackson/ for the logs

**Comment by artemjackson** [comment]
Build failed with the issue #1113. I'll work on it tomorrow so this build passed ASAP.

**Comment by yaronyg** [comment]
@artemjackson I have to admit that I'm extremely nervous at the idea that we are using Bluebird specific features. It means we are now married to Bluebird forever. But I suppose that will have to be a problem to be solved in the future. So I'm closing this for now.

**Pull request closed without merging**
