### PR TITLE
Run one test file through the coordinator at a time

### PR DESCRIPTION
**Pull request by yaronyg**
This adds a --filter argument that lets one specify a single file for the coordinator to run instead of all of them.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/627)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e430ee9)

**Comment by ThaliTester** [comment]
Test (Success) 62947189 build is completed (e430ee9)

See https://github.com/ThaliTester/TestResults/tree/62947189e430ee9_Run_one_test_file_through_the_coordinator_at_a_time_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 62947189e430ee9(e430ee9) has failed

See https://github.com/ThaliTester/TestResults/tree/62947189e430ee9_Run_one_test_file_through_the_coordinator_at_a_time_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
@yaronyg: By the way, for example this test run in CI was all passing:

```
2016-03-15T18:15:58.631Z - info: PLATFORM: android
2016-03-15T18:15:58.632Z - info: RESULT: PASS
2016-03-15T18:15:58.633Z - info: 107 of 107 tests completed
2016-03-15T18:15:58.634Z - info: 107/107 passed (0 failures)
```
```
2016-03-15T18:16:10.333Z - info: PLATFORM: ios
2016-03-15T18:16:10.334Z - info: RESULT: PASS
2016-03-15T18:16:10.335Z - info: 107 of 107 tests completed
2016-03-15T18:16:10.336Z - info: 107/107 passed (0 failures)
```

However, the end result is still reported as a failure, because we get the "app failed to load" on some other devices (that are not part of the two that participate to the unit test run). I left it this way so that we don't forget to fix the issue, but on the other hand, we could change the "app failed to load" to be reported as success since we have an issue open about it and then we'd actually start getting CI to report passes in case all all tests pass.

**Comment by vjrantal** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/627#-:-KCy6wS56cMRYmxoNuqk:1417088721)*

**Comment by yaronyg** [comment]
@vjrantal So long as we have an open issue on 'app failed to load' then we are good to not record those as failures during a test run

**Pull request merged**
