### PR TITLE
Ensure native tests failure is correctly reported

### PR DESCRIPTION
**Pull request by czyzm**
See discussion in: https://github.com/thaliproject/CI/issues/80

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1133)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (7cfe9e7)

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1133#-:-KSKPgL790bppqF-ZtBd:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 86453613 build is completed (7cfe9e7)

See https://github.com/ThaliTester/TestResults/tree/864536137cfe9e7_Ensure_native_tests_failure_is_correctly_reported_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 864536137cfe9e7(7cfe9e7) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/864536137cfe9e7_Ensure_native_tests_failure_is_correctly_reported_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e903f38)

**Comment by ThaliTester** [comment]
Test (Success) 86453613 build is completed (e903f38)

See https://github.com/ThaliTester/TestResults/tree/86453613e903f38_Ensure_native_tests_failure_is_correctly_reported_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 86453613e903f38(e903f38) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/86453613e903f38_Ensure_native_tests_failure_is_correctly_reported_czyzm/ for the logs

**Pull request merged**
