### PR TITLE
PeerDictionary and minor changes to thaliNotificationAction

### PR DESCRIPTION
**Pull request by juhanak**
PeerDictionary implementation and just small changes to thaliNotificationAction.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/596)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (123161a)

**Comment by ThaliTester** [comment]
Test 61432979123161a(123161a) has failed

See https://github.com/ThaliTester/TestResults/tree/61432979123161a_PeerDictionary_and_minor_changes_to_thaliNotificationAction_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliPeerDictionary.js, line 145 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtw-79H_KOIjodzNr6:-KBtw-79H_KOIjodzNr7:-1174956711) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/test/www/jxcore/bv_tests/testThaliPeerDictionary.js#L145)):*
For these and others we really need to check that the full contents of the dictionary to make sure the results are correct. Just testing one value isn't enough.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 126 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtefFV1eBgGIKfe1J2:-KBtefFV1eBgGIKfe1J3:113280034) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L126)):*
Did you check if the jsDoc generation system will generate the right link if we leave out the ~NotificationAction?

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 135 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBteH8gYkbpzzsELNPa:-KBteH8htBtqPUNaEIj7:-507335032) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L135)):*
It's probably nicer to just wrap the immediate text where the issue is. Otherwise we end up exempting a bunch of text that shouldn't really be exempted. So this might mean using disable/enable twice but that is o.k.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 165 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBteu7H-1udC4NVPVFP:-KBteu7H-1udC4NVPVFQ:-461715157) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L165)):*
/dictionary/a dictionary/

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 202 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtfITgCbQPYaOaDZqD:-KBtfIThFBa1__Z5fwIC:1698575710) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L202)):*
This is correct but the idiomatic way to write this in Javascript is !this._dictionary[peerId]

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 218 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBti2pg9ZOzjqT6Jp1j:-KBti2pg9ZOzjqT6Jp1k:694283121) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L218)):*
You don't have to check if the item exists. It's always fine to issue delete this._dictionary[peerId] even if there is no entry matching peerId.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 244 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtkP4oOPPre4RYo9WF:-KBtivtQODJOvD4tXtgP:-1882999323) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L244)):*
I would probably suggest:
var entryObject = this._dictionary[peerId];
return entryObject ? entryObject.entry : null;

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 256 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtkyUCCM04nklvhsTe:-KBtkyUDVof6hzrkFl5J:-783088939) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L256)):*
Isn't this just remove?

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 273 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtmX2YALQKhresMPY5:-KBtmX2Z2iUC4hMss4Ow:1631880112) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L273)):*
/full removes/full this function removes/

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 283 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtnGqJG2G3kpeprxGC:-KBtnGqJG2G3kpeprxGD:-900928877) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L283)):*
I think the code is more readable if you had written:
if (this.size() < PeerDictionary.MAXSIZE) { return; } 
Then you can un-indent the rest of the code.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 285 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBturqJNDPmcrltxJKo:-KBturqJNDPmcrltxJKp:1305185024) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L285)):*
I think you want to use MAX_SAFE_INTEGER

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 301 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtq1mByT57cTY_75OY:-KBtq1mCHWfdaxa-lt0Q:485429819) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L301)):*
Why did you need to pass this into String?

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 309 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBts6qdQZlUsMcIofgM:-KBtqY0m3I7c6PA4OJ70:-1538292996) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L309)):*
How is the timer managed? If an entry is waiting then somewhere there is a timer. Who owns it? How do we make sure it isn't missing this entry?

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 317 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtsTNeuJ8a3GgRhuGk:-KBtsTNf-qrELGeF5JEy:1237100244) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L317)):*
If we get an entry that is controlled by the pool but doesn't have a notification action then aren't we in serious trouble?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (9926788)

**Comment by juhanak** [comment]
Review status: 1 of 3 files reviewed at latest revision, 14 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliPeerDictionary.js, line 145 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtw-79H_KOIjodzNr6:-KBwfNfReIb390uqmIRI:-1511528373) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/test/www/jxcore/bv_tests/testThaliPeerDictionary.js#L145)):*
Added more testing:
-assert.deepEqual to some places to ensure that entries don't change inside dictionary
-more size checking to ensure dictionary size is behaving properly
-unique tags to objects inside dictionary to ensure objects don't change

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 126 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtefFV1eBgGIKfe1J2:-KBwhf_borAM7dpl19Ew:479642424) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L126)):*
No, I haven't tested. WebStorm just highlights it and says 'Unversolved variable or type' if I have NotificationAction/ThaliNotificationAction there. But it's not the only type that it can't resolve so I'll put it back. 

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 135 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBteH8gYkbpzzsELNPa:-KBvGwY1rchEx5RNsuBW:58580498) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L135)):*
Ok changed to have two disable/enable.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 165 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBteu7H-1udC4NVPVFP:-KBvHKtoMM9-efYREFFg:-467915377) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L165)):*
fixed

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 202 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtfITgCbQPYaOaDZqD:-KBvKs_PruN3ZAAdFAbB:-1290661914) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L202)):*
Changed it to "if(this._dictionary[peerId])" and changed the order. 

NOTE: Updating entry now refreshes the 'entry.entryNumber' value. Isn't it logical that updated entries are considered newer than non-updated when we run _removeOldIfOverflow? 

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 218 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBti2pg9ZOzjqT6Jp1j:-KBvMZtxLcsGYelp-gcM:-1567195139) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L218)):*
Right. fixed. 

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 244 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtkP4oOPPre4RYo9WF:-KBwib9is5D4-7TTJ9M2:-1732764578) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L244)):*
Changed as you suggested. It looks cleaner. 

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 256 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtkyUCCM04nklvhsTe:-KBvNH0gCBQ2Uaa9TG72:2026654191) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L256)):*
Ups. I'll remove this. 

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 273 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtmX2YALQKhresMPY5:-KBwjxObIy98JPfzuz6w:-1620474753) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L273)):*
fixed.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 283 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtnGqJG2G3kpeprxGC:-KBvPCR8sT35dgDc21Yp:1473459647) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L283)):*
Good idea. Changed. 

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 285 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBturqJNDPmcrltxJKo:-KBvYRNtWfnLHKKk2akd:-312145051) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L285)):*
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER seems to be available from ES6 onwards. 
I just replaced it with: 
var smallestEntryNumber = self._entryCounter;

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 301 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtq1mByT57cTY_75OY:-KBva1LN11cvhPEeVfo8:-1054482086) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L301)):*
No good reason for them to exists anymore I'll remove them. I was first thinking that keys need to be forced to be strings but turns out it is not needed. So this is just something from the old implementation. 

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 309 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBts6qdQZlUsMcIofgM:-KBw7qjFCHtoBnoRnIO-:744010836) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L309)):*
I added timer object:
NotificationPeerDictionaryEntry.prototype.waitingTimeout

It is cleared here: 

  if (oldestPeerId) {
    clearTimeout(self._dictionary[oldestPeerId].entry.timeout);
    self.remove(oldestPeerId);
    return;
  }
 

I'm not exactly sure yet if there is need to add some extra logic into NotificationPeerDictionaryEntry or PeerDictionary classes or is everything else happening in the ThalinotificationsClass.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 317 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtsTNeuJ8a3GgRhuGk:-KBw9F0pery4RfhGXCnB:-314873098) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L317)):*
Right. So testing it at this point maybe is not that useful because something else would be broken already. Removed it. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596)*

**Comment by ThaliTester** [comment]
Test (Success) 61432979 build is completed (9926788)

See https://github.com/ThaliTester/TestResults/tree/614329799926788_PeerDictionary_and_minor_changes_to_thaliNotificationAction_juhanak/ for the logs

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 126 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtefFV1eBgGIKfe1J2:-KBxo5HuI9oDvB0Xqh9A:-1898096077) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L126)):*
NB: Yeah WebStorm's JSdoc support explicitly doesn't support cross document links. It's a bummer actually. I just filed a bug on it - https://youtrack.jetbrains.com/issue/IDEA-152548

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 202 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtfITgCbQPYaOaDZqD:-KBxpaWcoJtvXCWW7Cj5:1687142081) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L202)):*
NB: Yup, it is logical. "active" entries should get preference.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 285 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBturqJNDPmcrltxJKo:-KBxpwemhDCsLrVaSLTh:1717510822) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L285)):*
NB: Good idea!

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 301 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtq1mByT57cTY_75OY:-KBxq-k6_iUfgvRh3owi:-183036279) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L301)):*
NB: Yes one of the many awful things about javascript is automatic type coercion that can lead to surprising results but it means that generally you don't need to type cast or convert. Javascript will do it for you (even if you didn't want it to).

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 309 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBts6qdQZlUsMcIofgM:-KBxqIA_QihZgnCbZ5Fd:1018154366) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L309)):*
The problem is that there are two places where that timer needs to be killed. One is here. But the other one is in remove. The scenario is:
Time 0 - The notification client hears about a new peer and creates a notification action to find out its beacons. That peer and the notification action are both added to the peer dictionary as well as having the notification action added to the thali peer pool interface.
Time 1 - The notification action is run by the peer pool and it gets a failure which is emitted as an event that the thali notification client is listening to.
Time 2 - The thali notification client updates the thali peer dictionary for that peer, it needs to delete the current notification action (since it has already completed and notification actions can only be used once) and set a timeout. When that timeout expires the code in the timeout will create a new notification action, enqueue it with the peer pool interface and update the notification in the entry of the dictionary.
Time 3 - The thali notification client gets a notification that the peer is no longer available. So the thali notification client calls remove expecting that if the timer hasn't fired then it will be stopped and if it has been tired then kill will be called.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 317 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtsTNeuJ8a3GgRhuGk:-KBxsy7XxTWwBEMvcMCI:630991473) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L317)):*
NB: Actually this is a great place for an assert.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596)*

**Comment by juhanak** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 309 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBts6qdQZlUsMcIofgM:-KBy3Gs0CysWrd9CvrR6:-659521206) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L309)):*
Right. I'll move timer killing to remove function. I assume I could move a line 'self._dictionary[oldestPeerId].entry.notificationAction.kill();' when the entry is CONTROLLED_BY_POOL state to remove function as well?

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 317 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBtsTNeuJ8a3GgRhuGk:-KBy88VK_bWg0cKKJMdk:-851356988) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L317)):*
I moved the whole kill action to remove function. I didn't pu there assert yet but I can add it there once I get a little bit better picture of different scenarios when  remove is called. Or actually once ThaliNotificationClient & NotificationAction classes are ready I need to take a better look at what functions should be asserted and where we should just try to cover from errors. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f791f6f)

**Comment by yaronyg** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 244 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBz93QEwfh5jSMiv1RG:-KBz93QEwfh5jSMiv1RH:74274976) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f791f6f4ce365f30b4a28902078edd960399253c/thali/NextGeneration/notification/thaliPeerDictionary.js#L244)):*
I screwed up! delete on an entry in an array will set the entry to undefined but it's key is still there. This will screw up iterators. This will leak memory. It's bad and I'm sorry. I didn't realize this was delete's behavior on arrays. The proper way to handle this is with splice. That will actually make the entry go away for real.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596)*

**Comment by juhanak** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 244 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBz93QEwfh5jSMiv1RG:-KC-FepR2psSBGKiUspG:2009630236) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f791f6f4ce365f30b4a28902078edd960399253c/thali/NextGeneration/notification/thaliPeerDictionary.js#L244)):*
I don't think that it is a problem with current dictionary implementation. Associative arrays behave a bit differently with JS compared to normal arrays. http://stackoverflow.com/questions/8173210/delete-vs-splice-on-associative-array
So _dictionary is not a real array at all but an object whose members I'm adding and removing. That's why its length is always 0 and I need in size function calculate number of keys in following way: 
return Object.keys(this._dictionary).length;

Actually my mistake is that I'm initializing it as an array: 
this._dictionary = [] and I should be doing: this._dictionary = {}.. 

It didn't cause error because an array is also an object too. I'll push that fix now. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596)*

**Comment by ThaliTester** [comment]
Test (Success) 61432979 build is completed (f791f6f)

See https://github.com/ThaliTester/TestResults/tree/61432979f791f6f_PeerDictionary_and_minor_changes_to_thaliNotificationAction_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 614329799926788(9926788) has failed

See https://github.com/ThaliTester/TestResults/tree/614329799926788_PeerDictionary_and_minor_changes_to_thaliNotificationAction_juhanak/ for the fail logs

**Comment by ThaliTester** [comment]
Test 61432979f791f6f(f791f6f) has failed

See https://github.com/ThaliTester/TestResults/tree/61432979f791f6f_PeerDictionary_and_minor_changes_to_thaliNotificationAction_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 309 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KBts6qdQZlUsMcIofgM:-KC1iK_UkMlLbSndVL4u:-966393796) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/123161adea01c2f0fd48702eb28b4304203e5f4b/thali/NextGeneration/notification/thaliPeerDictionary.js#L309)):*
NB: Yup. In fact it's ALWAYS safe to call kill no matter what so if there is a notificationAction object then in a case like this I would call kill on it.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 242 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KC1ig7S1KbgCpx6XOpM:-KC1ig7S1KbgCpx6XOpN:893074287) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/77e23d911923d4d80d763509ae3299748bc0faf9/thali/NextGeneration/notification/thaliPeerDictionary.js#L242)):*
Don't you need to check if the peerID is available? Otherwise you are going to cause an exception when you try to get to .entry on an undefined value. Please add a test for removing an entry that isn't there.

Also you don't need the if/else/if logic. I think it would be simpler and more robust to instead execute:

var entry = this._dictionary[peerId];
entry.waitingTimeout && clearTimeout(entry.waitingTimeout);
entry.notificationAction && entry.notificationAction.kill();

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (dd0fe92)

**Comment by juhanak** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 242 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-KC1ig7S1KbgCpx6XOpM:-KCUx1LooT7u4n2A093K:-74471798) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/77e23d911923d4d80d763509ae3299748bc0faf9/thali/NextGeneration/notification/thaliPeerDictionary.js#L242)):*
Fixed. The remove function throws an assert error if the peerID is not found. And test added for it. 
Timeout & notification killing uses uses your proposal: 
entry.waitingTimeout && clearTimeout(entry.waitingTimeout);
entry.notificationAction && entry.notificationAction.kill();

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596)*

**Comment by ThaliTester** [comment]
Test (Success) 61432979 build is completed (dd0fe92)

See https://github.com/ThaliTester/TestResults/tree/61432979dd0fe92_PeerDictionary_and_minor_changes_to_thaliNotificationAction_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 61432979dd0fe92(dd0fe92) has failed

See https://github.com/ThaliTester/TestResults/tree/61432979dd0fe92_PeerDictionary_and_minor_changes_to_thaliNotificationAction_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
We must not check this in until it is passing tests in CI.  Which means you are now blocked on me because your check in is failing due to an issue that isn't your fault. So once I check in 561 then please do a touch on this to update in github and so trigger another CI run and make sure it passes.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/596#-:-KCWr8P7XgDOFDJlR7vO:1559436666)*

**Comment by yaronyg** [comment]
@juhanak We changed our minds. For now as long as appveyor is passing (and in your case it is) you can check in.

**Pull request merged**
