### PR TITLE
Reverted test runner

### LINKED ISSUE #1288: Please move master to the version of the coordination framework from Friday
This was the version that did not use child_process and that @vasilevskayaem successfully ran the Android wifi tests on

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1288

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1293)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2aa92e4)

**Comment by ThaliTester** [comment]
Test (Success) 88911693 build is completed (2aa92e4)

See https://github.com/ThaliTester/TestResults/tree/889116932aa92e4_Reverted_test_runner_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 889116932aa92e4(2aa92e4) has failed

See https://github.com/ThaliTester/TestResults/tree/889116932aa92e4_Reverted_test_runner_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
@vasilevskayaem Please use this branch to re-run the Android WiFi Only tests and make sure they pass. Please respond to this PR with the results. If they pass as they did before then :lgtm: 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1293#-:-KTppN8ji_cepU66NQYC:b-7igc5s)*

**Comment by vasilevskayaem** [comment]
fails "Make sure docs replicate", but it seems to be old test that was recommented. The other tests works fine

**Comment by yaronyg** [comment]
@yaronyg Open a separate bug with the logs and the test failure.

**Pull request merged**
