### PR TITLE
Clarifying ACL table

### PR DESCRIPTION
**Pull request by yaronyg**
Fixed a bug that Shawn pointed out in the ACL table and explained why we have both _local/:id and _local/thali_:id

---
This change is [Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/605)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (84ac8ae)

**Comment by ThaliTester** [comment]
Test (Success) 62167425 build is completed (84ac8ae)

See https://github.com/ThaliTester/TestResults/tree/6216742584ac8ae_Clarifying_ACL_table_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 6216742584ac8ae(84ac8ae) has failed

See https://github.com/ThaliTester/TestResults/tree/6216742584ac8ae_Clarifying_ACL_table_yaronyg/ for the fail logs

**Comment by cicorias** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/605)*

**Pull request merged**
