### PR TITLE
Small fixes to test results reporting

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/339)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (59f447b)

**Comment by ThaliTester** [comment]
Test (Success) 51053261 build is completed (59f447b)

See https://github.com/ThaliTester/TestResults/tree/5105326159f447b_Small_fixes_to_test_results_reporting_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5105326159f447b(59f447b) has failed

See https://github.com/ThaliTester/TestResults/tree/5105326159f447b_Small_fixes_to_test_results_reporting_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (92ae435)

**Comment by ThaliTester** [comment]
Test (Success) 51053261 build is completed (92ae435)

See https://github.com/ThaliTester/TestResults/tree/5105326192ae435_Small_fixes_to_test_results_reporting_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c9004a4)

**Comment by ThaliTester** [comment]
Test (Success) 51053261 build is completed (c9004a4)

See https://github.com/ThaliTester/TestResults/tree/51053261c9004a4_Small_fixes_to_test_results_reporting_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5105326192ae435(92ae435) has failed

See https://github.com/ThaliTester/TestResults/tree/5105326192ae435_Small_fixes_to_test_results_reporting_vjrantal/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/339)_

**Pull request merged**
