### PR TITLE
Removed test timeout

### LINKED ISSUE #1603: Do we still need testUtils.testTimeout?
Now that the test framework has a time out mechanism built into it, is there any need for the testUtils.testTimeout method?

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1603.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1606)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9a343fb)

**Comment by ThaliTester** [comment]
Test 96505409 (9a343fb) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96505409 build is completed (9a343fb)

See https://github.com/ThaliTester/TestResults/tree/965054099a343fb_Removed_test_timeout_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 965054099a343fb(9a343fb) has failed

See https://github.com/ThaliTester/TestResults/tree/965054099a343fb_Removed_test_timeout_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1606#-:-KYKaQx73Ue2R4ywKMyV:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bcb1655)

**Comment by ThaliTester** [comment]
Test 96505409 (bcb1655) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96505409 build is completed (bcb1655)

See https://github.com/ThaliTester/TestResults/tree/96505409bcb1655_Removed_test_timeout_andrew-aladev/ for the logs

**Pull request merged**
