### PR TITLE
#1749 Update multiConnect invalid syncValue handling

### LINKED ISSUE #1749: We should update logic on node side to be able to receive badParameters error after MultiConnect call.
We should pass `badParameters` error directly from `multiConnect` call.

This is because of requested parameters in `multiConnectResolved`/`multiConnectFailure` callbacks. For instance we can try to pass `badParameters` error in `multiConnectResolved` callback. But in this case this callback has three parameters: `syncValue`, `error`, `port`. Node.js should be able to receive correct parameters back. The obvious problem here is we have bad parameters (sic!). It can contain illegal `syncValue`, thus we won't be able to send correct `syncValue` back to node.

The same thoughts about `multiConnectFailure` callback.

So we should update business logic in node and corresponding tests as well.

### PR DESCRIPTION
**Pull request by chapko**
Fixes #1749.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1756)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (17d2aad)

**Comment by ThaliTester** [comment]
Test 103072090 (17d2aad) build started.

**Comment by ThaliTester** [comment]
Test (Success) 103072090 build is completed (17d2aad)

See https://github.com/ThaliTester/TestResults/tree/10307209017d2aad__1749_Update_multiConnect_invalid_syncValue_handling_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 10307209017d2aad(17d2aad) has failed

See https://github.com/ThaliTester/TestResults/tree/10307209017d2aad__1749_Update_multiConnect_invalid_syncValue_handling_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1756#-:-KbLKI7JFeyjjLv4oRfN:bnfp4nl)*

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1756#-:-KbUDgQL0Ok9OrTLvyg4:bnfp4nl)*

**Pull request merged**
