### PR TITLE
Updated BtLib version

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1442)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7357579)

**Comment by evabishchevich** [comment]
It's one line PR. I'm merging it after it will have builded on CI

**Comment by ThaliTester** [comment]
Test (Success) 91200976 build is completed (7357579)

See https://github.com/ThaliTester/TestResults/tree/912009767357579_Updated_BtLib_version_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 912009767357579(7357579) has failed

See https://github.com/ThaliTester/TestResults/tree/912009767357579_Updated_BtLib_version_evabishchevich/ for the fail logs

**Pull request merged**
