### PR TITLE
Make server address a proper node module.

### PR DESCRIPTION
**Pull request by vjrantal**
This was done to fix compatibility with `jx package` which doesn't work with
.json files.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/360)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d5a0cb8)

**Comment by ThaliTester** [comment]
Test (Success) 52383621 build is completed (d5a0cb8)

See https://github.com/ThaliTester/TestResults/tree/52383621d5a0cb8_Make_server_address_a_proper_node_module__vjrantal/ for the logs

**Comment by tobybrad** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/generateServerAddress.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/360#-K4XWjfcTjO3KrHIlg5n:-K4XWjfcTjO3KrHIlg5o:1729623605) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/27727fb5f6984a24d491d080236c52b014cdb7dc/test/TestServer/generateServerAddress.js#L3)):*
?? Not a lot of point to this, surely ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/360)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/generateServerAddress.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/360#-K4XWjfcTjO3KrHIlg5n:-K4XXZdrffHZlKmXS8Pa:-1139750839) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/27727fb5f6984a24d491d080236c52b014cdb7dc/test/TestServer/generateServerAddress.js#L3)):*
You are right - no functional change.

It was just to adapt to the coding conventions that are upcoming at https://github.com/thaliproject/Thali_CordovaPlugin/pull/332 .

I can revert this if we prefer doing the coding convention changes separately from actual code changes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/360)*

**Comment by ThaliTester** [comment]
Test 52383621d5a0cb8(d5a0cb8) has failed

See https://github.com/ThaliTester/TestResults/tree/52383621d5a0cb8_Make_server_address_a_proper_node_module__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (712b264)

**Comment by tobybrad** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/360)*

**Comment by ThaliTester** [comment]
Test (Success) 52383621 build is completed (712b264)

See https://github.com/ThaliTester/TestResults/tree/52383621712b264_Make_server_address_a_proper_node_module__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 52383621712b264(712b264) has failed

See https://github.com/ThaliTester/TestResults/tree/52383621712b264_Make_server_address_a_proper_node_module__vjrantal/ for the fail logs

**Pull request merged**
