### PR TITLE
Fixing testStopListeningForConnectionsReleasesPort

### PR DESCRIPTION
**Pull request by dersim-davaod**
Main issue is #1355.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1357)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ab206e8)

**Comment by baydet** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/AdvertiserRelay.swift, line 125 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1357#-KUMsi-_t7aDT-FRV6ss:-KUMsi-_t7aDT-FRV6st:b1xxny0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ab206e889f0eb66d2a7678bb9f0c5b8a8ddcbc8a/lib/ios/ThaliCore/ThaliCore/SocketConnection/AdvertiserRelay.swift#L125)):*
> ```Swift
> 
>     private func didDisconnectHandler(socket: GCDAsyncSocket) {
>         virtualSockets.modify {
> ```

We need to add tests for this function
Please, put TODO please with number of corresponding issue

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPListener.swift, line 31 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1357#-KUMrbm0dnW6KOwrnREh:-KUMrbm0dnW6KOwrnREi:b-ld5vl9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ab206e889f0eb66d2a7678bb9f0c5b8a8ddcbc8a/lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPListener.swift#L31)):*
> ```Swift
>     private var didReadDataFromSocketHandler: ((GCDAsyncSocket, NSData) -> Void)
>     private var didSocketDisconnectHandler: ((GCDAsyncSocket) -> Void)
>     private var didStoppedListeningHandler: () -> Void
> ```

We can replace it with let. Btw the same for the the listed above properties

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1357)*

**Comment by ThaliTester** [comment]
Test (Success) 89808901 build is completed (ab206e8)

See https://github.com/ThaliTester/TestResults/tree/89808901ab206e8_Fixing_testStopListeningForConnectionsReleasesPort_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (b248d65)

**Comment by dersim-davaod** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/AdvertiserRelay.swift, line 125 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1357#-KUMsi-_t7aDT-FRV6ss:-KUMvkCuMWgTynkjez1B:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ab206e889f0eb66d2a7678bb9f0c5b8a8ddcbc8a/lib/ios/ThaliCore/ThaliCore/SocketConnection/AdvertiserRelay.swift#L125)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> We need to add tests for this function
> Please, put TODO please with number of corresponding issue
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPListener.swift, line 31 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1357#-KUMrbm0dnW6KOwrnREh:-KUMvlUiTZG13dz5eXtD:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ab206e889f0eb66d2a7678bb9f0c5b8a8ddcbc8a/lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPListener.swift#L31)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> We can replace it with let. Btw the same for the the listed above properties
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1357)*

**Comment by baydet** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1357#-:-KUMxaboXM1kg8Sd0uj2:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 89808901ab206e8(ab206e8) has failed

See https://github.com/ThaliTester/TestResults/tree/89808901ab206e8_Fixing_testStopListeningForConnectionsReleasesPort_dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 89808901 build is completed (b248d65)

See https://github.com/ThaliTester/TestResults/tree/89808901b248d65_Fixing_testStopListeningForConnectionsReleasesPort_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 89808901b248d65(b248d65) has failed

See https://github.com/ThaliTester/TestResults/tree/89808901b248d65_Fixing_testStopListeningForConnectionsReleasesPort_dersim-davaod/ for the fail logs

**Pull request merged**
