### PR TITLE
App context test fix

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1420)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8d41448)

**Comment by ThaliTester** [comment]
Test (Fail) 90782398 build is completed (8d41448)

See https://github.com/ThaliTester/TestResults/tree/907823988d41448_App_context_test_fix_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fd1c6e1)

**Comment by dersim-davaod** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1420)*

**Comment by dersim-davaod** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1420#-:-KUvYAhcEG2ATyWWqRwf:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Fail) 90782398 build is completed (fd1c6e1)

See https://github.com/ThaliTester/TestResults/tree/90782398fd1c6e1_App_context_test_fix_baydet/ for the logs

**Pull request merged**
