### PR TITLE
Fix onPeerLost test

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1726)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fa77f24)

**Comment by ThaliTester** [comment]
Test 101466302 (fa77f24) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 101466302 build is completed (fa77f24)

See https://github.com/ThaliTester/TestResults/tree/101466302fa77f24_Fix_onPeerLost_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (14b0470)

**Comment by ThaliTester** [comment]
Test 101466302 (14b0470) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ad481fb)

**Comment by ThaliTester** [comment]
Test 101466302 (ad481fb) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 101466302 build is completed (14b0470)

See https://github.com/ThaliTester/TestResults/tree/10146630214b0470_Fix_onPeerLost_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 101466302 build is completed (ad481fb)

See https://github.com/ThaliTester/TestResults/tree/101466302ad481fb_Fix_onPeerLost_test_evabishchevich/ for the logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726#-:-KaNYwHuSCM2_mTkDQHU:bnfp4nl)*

**Comment by yaronyg** [comment]
Please see comment.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 553 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726#-KaNoSujA-TmFIjBlO19:-KaNoSuk-GQhjp6pIhrX:bexzri4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ad481fb0bfe6c5a774ec673a63df618607758350/src/android/java/io/jxcore/node/JXcoreExtension.java#L553)):*
> ```Java
>                     null : peerProperties.getExtraInformation();
>             }
>             jsonObject.put(EVENT_VALUE_PEER_GENERATION, gen);
> ```

Why would we return a generation value set to anything but null when specifying that the peer isn't available? Isn't the decision around unavailability based not on generation but rather on not hearing any announcements with the peer's Bluetooth address?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726#-:-KaNoplMbtLVkJ121Xky:b-vni0hf)*

**Comment by yaronyg** [comment]
Oh and when you fix it just merge. You don't have to wait another day for me to lgtm. I will review whatever you do and if I'm unhappy I'll complain retrospectively. :)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726#-:-KaNot2PbpkzDzP3EChy:b-2x8jer)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fc03971)

**Comment by ThaliTester** [comment]
Test 101466302 (fc03971) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 101466302 build is completed (fc03971)

See https://github.com/ThaliTester/TestResults/tree/101466302fc03971_Fix_onPeerLost_test_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a486bdc)

**Comment by ThaliTester** [comment]
Test 101466302 (a486bdc) build started.

**Comment by evabishchevich** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 553 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726#-KaNoSujA-TmFIjBlO19:-KaarJ4F8TBtFSKU2Tq2:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ad481fb0bfe6c5a774ec673a63df618607758350/src/android/java/io/jxcore/node/JXcoreExtension.java#L553)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why would we return a generation value set to anything but null when specifying that the peer isn't available? Isn't the decision around unavailability based not on generation but rather on not hearing any announcements with the peer's Bluetooth address?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726)*

**Comment by evabishchevich** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 553 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726#-KaNoSujA-TmFIjBlO19:-KaarLw7WK5rXziwQnKa:b-rguzhc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ad481fb0bfe6c5a774ec673a63df618607758350/src/android/java/io/jxcore/node/JXcoreExtension.java#L553)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, our decision is based on not hearing any announcements with the peer's Bluetooth address

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726)*

**Comment by ThaliTester** [comment]
Test (Fail) 101466302 build is completed (a486bdc)

See https://github.com/ThaliTester/TestResults/tree/101466302a486bdc_Fix_onPeerLost_test_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
Failed test is fixed in #1721

**Comment by mlesnic** [comment]
:lgtm:

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726#-:-KabWAaQ-C-Gjm7gSdAz:bnfp4nl)*

**Comment by evabishchevich** [comment]
I'm going to merge that right after we get tests fixed on the desktop

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1726#-:-Kag1uMPUYqIPqEc0_80:bg7igkv)*

**Comment by evabishchevich** [comment]
There is need for this PR, I will merge it.

**Pull request merged**
