### PR TITLE
#697 Fixed setInterval battery abuse

### PR DESCRIPTION
**Pull request by artemjackson**
I had to start from [vNext_yarong_780](https://github.com/thaliproject/Thali_CordovaPlugin/tree/vNext_yarong_780) because Coordinated Tests failed on [vNext](https://github.com/thaliproject/Thali_CordovaPlugin/tree/vNext).

What actually was done:
* Removed PeerWatcher that checks peers availability every second 
* Implemented dynamic addition of PeerWatcher for peer with proper check interval based on connection type

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/851)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (3b560df)

**Comment by ThaliTester** [comment]
Test (Fail) 80768856 build is completed (3b560df)

See https://github.com/ThaliTester/TestResults/tree/807688563b560df_V_next_artemjackson_697_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b4e5040)

**Comment by ThaliTester** [comment]
Test (Fail) 80768856 build is completed (b4e5040)

See https://github.com/ThaliTester/TestResults/tree/80768856b4e5040__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by yaronyg** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/851#-:-KOqKuAGQ5YMCGTlIPQq:bg7igkv)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ffd4d9b)

**Comment by ThaliTester** [comment]
Test (Success) 80768856 build is completed (ffd4d9b)

See https://github.com/ThaliTester/TestResults/tree/80768856ffd4d9b__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 80768856ffd4d9b(ffd4d9b) has failed

See https://github.com/ThaliTester/TestResults/tree/80768856ffd4d9b__697_Fixed_setInterval_battery_abuse_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
@artemjackson it's still not passing CI. It builds but it doesn't pass the device tests. Please work with the Rockwell folks and Genia to get this passing.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (589afaf)

**Comment by ThaliTester** [comment]
Test (Fail) 80768856 build is completed (589afaf)

See https://github.com/ThaliTester/TestResults/tree/80768856589afaf__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5400c1f)

**Comment by ThaliTester** [comment]
Test (Fail) 80768856 build is completed (5400c1f)

See https://github.com/ThaliTester/TestResults/tree/807688565400c1f__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4f75085)

**Comment by ThaliTester** [comment]
Test (Success) 80768856 build is completed (4f75085)

See https://github.com/ThaliTester/TestResults/tree/807688564f75085__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 807688564f75085(4f75085) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/807688564f75085__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by artemjackson** [comment]
@yaronyg could you please review changes of this PR so I can finish with it.

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/851#-:-KPOxYmlZwgKioIZnBOe:bnfp4nl)*

**Comment by artemjackson** [comment]
Please, resubmit this to `vNext_yarong_417_812`

**Pull request closed without merging**
