### PR TITLE
Fixes and hardening

### LINKED ISSUE #642: 10 connection retries was not enough for two Android devices connected
Reproduced locally when running unit test app with two Android devices.

Logs zipped here:
[1458287264.zip](https://github.com/thaliproject/Thali_CordovaPlugin/files/179239/1458287264.zip)

### LINKED ISSUE #657: The discoveryAdvertisingStateUpdate test fails on Android

### LINKED ISSUE #659: Android always returns the same peerID
The Android code always returns the same peer ID (the bluetooth address) which is a bug since every time the BLE address changes the peer ID sent to node is required to change in order to notify node that there is new data available. There is an easy fix which is to add a counter or a UUID or something to the peerID on the way out to node and strip it on the way back. That way all the android code still sees the bluetooth address as the peer ID but the node code gets different values.

### PR DESCRIPTION
**Pull request by tompaana**
* Set a custom manufacturer ID for BLE advertisements
* Fixed #659
* Fixed #657 
* Fixed #642

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/720)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (efa6102)

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (efa6102)

See https://github.com/ThaliTester/TestResults/tree/68102130efa6102_Fixes_and_hardening_tompaana/ for the logs

**Comment by yaronyg** [comment]
I'm out of time for tonight and I want to take my time with Streamcopyingthread and socketthreadbase per our previously conversation. So I'll review them tomorrow.

---

Reviewed 9 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 221 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGQN8oxXPy15BNb38sD:-KGQN8oxXPy15BNb38sE:1554651161) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efa61024c5e2090c7c92f74cc2e200f0d3a8f214/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L221)):*
Shouldn't overflow go to 0 not 1?

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 714 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGQKo5zUPpoEP5gXS_7:-KGQKo5zUPpoEP5gXS_8:-822467183) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efa61024c5e2090c7c92f74cc2e200f0d3a8f214/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L714)):*
/ran/run

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 716 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGQLGODEz5xdEsONgwd:-KGQLGODEz5xdEsONgwe:-1352000044) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efa61024c5e2090c7c92f74cc2e200f0d3a8f214/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L716)):*
This shouldn't be possible. listenerRecreatedAfterFailure is what triggers us to fire the new nonTCPPeerAvailabilityChangedEvent. Go look at the function listenerRecreatedAfterFailureHandler in thaliMobileNativeWrapper. So something else isn't going right here. We need to understand what.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-:-KGQNKRxNpgnrScAPHJO:-2017226926)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b92179b)

**Comment by ThaliTester** [comment]
Test (Success) 68102130 build is completed (b92179b)

See https://github.com/ThaliTester/TestResults/tree/68102130b92179b_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 68102130b92179b(b92179b) has failed

See https://github.com/ThaliTester/TestResults/tree/68102130b92179b_Fixes_and_hardening_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aff19f4)

**Comment by ThaliTester** [comment]
Test (Success) 68102130 build is completed (aff19f4)

See https://github.com/ThaliTester/TestResults/tree/68102130aff19f4_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 68102130aff19f4(aff19f4) has failed

See https://github.com/ThaliTester/TestResults/tree/68102130aff19f4_Fixes_and_hardening_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7227906)

**Comment by ThaliTester** [comment]
Test (Success) 68102130 build is completed (7227906)

See https://github.com/ThaliTester/TestResults/tree/681021307227906_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 681021307227906(7227906) has failed

See https://github.com/ThaliTester/TestResults/tree/681021307227906_Fixes_and_hardening_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f73255a)

**Comment by ThaliTester** [comment]
Test (Success) 68102130 build is completed (f73255a)

See https://github.com/ThaliTester/TestResults/tree/68102130f73255a_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 68102130f73255a(f73255a) has failed

See https://github.com/ThaliTester/TestResults/tree/68102130f73255a_Fixes_and_hardening_tompaana/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r2, 1 of 3 files at r3, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/SocketThreadBase.java, line 173 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGxggKvm2cTT5oyu_Hb:-KGxggKwqCQcf3mZwsL9:-1445933013) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f73255ae63e3c76960d1ca734a3e2bff24d1be2d/src/android/java/io/jxcore/node/SocketThreadBase.java#L173)):*
This just makes me sad. The model is wrong. Fundamentally the two separate stream copying instances have their own separate life cycles (unless the parent socket is closed). They each are closed separately. :( This binds them together and prays hard that 1 second is enough to clean up a mess. Sigh...

I also wonder if the same delay shouldn't apply to onStreamCopyError? I honestly am not sure if there is a scenario where we would get an error on one stream (e.g. an exception, not a -1) and the other stream would still be viable.

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 120 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGx2-OzgPhkw2y3_ZF-:-KGx2-P-JUam2V4xKYgb:1275756073) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f73255ae63e3c76960d1ca734a3e2bff24d1be2d/src/android/java/io/jxcore/node/StreamCopyingThread.java#L120)):*
Shouldn't both totalNumberOfBytesRead and totalNumberOfbytesWritten be commented out when we aren't using the associated logging statements? No need to put arithmetic operations in a tight loop?

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 136 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGxNHwkrXujyQ--c0is:-KGxNHwl4GAlnep0uGJ8:-273445608) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f73255ae63e3c76960d1ca734a3e2bff24d1be2d/src/android/java/io/jxcore/node/StreamCopyingThread.java#L136)):*
Why is the if statement inside of the try/catch?

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 145 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGwwe_tCdfQRTw4yWvu:-KGwwe_uW9nEYhBXg8Ul:-956427813) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f73255ae63e3c76960d1ca734a3e2bff24d1be2d/src/android/java/io/jxcore/node/StreamCopyingThread.java#L145)):*
This condition can't happen. If numberOfBytesRead is set in the while loop and if -1 the loop exits. If there was an exception from the read this condition still couldn't happen because numberOfBytesRead would not have been set. I think you can just remove this case since getting a -1 is anyway not an error and is handled properly by the if statement after the while

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 161 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGxSl9ay9BqSmAD_Jzl:-KGxSl9bzc1XY3WT9SA3:-1320528650) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f73255ae63e3c76960d1ca734a3e2bff24d1be2d/src/android/java/io/jxcore/node/StreamCopyingThread.java#L161)):*
Wouldn't it be safer to put this call inside of the catch?

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 174 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGxNh5DMjm891s01qZM:-KGxNh5DMjm891s01qZN:1346446177) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f73255ae63e3c76960d1ca734a3e2bff24d1be2d/src/android/java/io/jxcore/node/StreamCopyingThread.java#L174)):*
If close is called while a read request is outstanding then onStreamCopyingThreadDone will never get called because isDone will never be set to true. Is that intended?

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 183 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGxOSaSYgjZ7nuKwuN5:-KGxOSaSYgjZ7nuKwuN6:-668255536) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f73255ae63e3c76960d1ca734a3e2bff24d1be2d/src/android/java/io/jxcore/node/StreamCopyingThread.java#L183)):*
Why is this public? Testing? Because the production code only calls this from close() and calling closeStreams() without calling close (and hence setting mDoStop to true) seems bad. In fact, why aren't close and closeStreams just collapsed into a single method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4c54f50)

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (4c54f50)

See https://github.com/ThaliTester/TestResults/tree/681021304c54f50_Fixes_and_hardening_tompaana/ for the logs

**Comment by yaronyg** [comment]
@tompaana I see the build failed in CI but I don't see an actual failure, just warnings. Any ideas?

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (4c54f50)

See https://github.com/ThaliTester/TestResults/tree/681021304c54f50_Fixes_and_hardening_tompaana/ for the logs

**Comment by yaronyg** [comment]
Sigh... so this is the same type of problem I was seeing. I want to get you finished up @tompaana so when you think the code is ready to go just ping me and if it passes on my HTC M9 and Nexus 6 then I'll call it good and check it in.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (08b7140)

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (08b7140)

See https://github.com/ThaliTester/TestResults/tree/6810213008b7140_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (08b7140)

See https://github.com/ThaliTester/TestResults/tree/6810213008b7140_Fixes_and_hardening_tompaana/ for the logs

**Comment by yaronyg** [comment]
Reviewed 3 of 4 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 34 \[r7\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KJBRuJKaR4mbgCO-BkD:-KJBRuJLUlcuVNwgyP9R:2092743792) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/08b7140ee4b9037485cb85fe8a8e48298f94f0d9/src/android/java/io/jxcore/node/ConnectionHelper.java#L34)):*
> ```Java
>     public static final int NO_PORT_NUMBER = 0;
>     private static final String SERVICE_TYPE = "Cordovap2p._tcp";
>     private static final String SERVICE_UUID_AS_STRING = "fa87c0d0-afac-11de-8a39-0800200c9a66"; // "b6a44ad1-d319-4b3a-815d-8b805a47fb51";
> ```

What is the commented out value?

---

*[src/android/java/io/jxcore/node/OutgoingSocketThread.java, line 81 \[r7\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KJBS0JN8WM0t7ZWRBz5:-KJBS0JOUw9UgeeT1x4g:-903427339) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/08b7140ee4b9037485cb85fe8a8e48298f94f0d9/src/android/java/io/jxcore/node/OutgoingSocketThread.java#L81)):*
> ```Java
>                     mListener.onDisconnected(this, errorMessage);
>                 }
>             } catch (NullPointerException e) {
> ```

How exactly would we end up with a null pointer exception?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (589603b)

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (589603b)

See https://github.com/ThaliTester/TestResults/tree/68102130589603b_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (22b2585)

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (22b2585)

See https://github.com/ThaliTester/TestResults/tree/6810213022b2585_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (388457c)

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (388457c)

See https://github.com/ThaliTester/TestResults/tree/68102130388457c_Fixes_and_hardening_tompaana/ for the logs

**Comment by yaronyg** [comment]
Working through the comments now.

**Comment by yaronyg** [comment]
@evabishchevich So there are literally two comments left that need to be addressed. :) However the real work item is to help @jareksl and @mlesnic get #555 checked in and passing CI. As part of that they are going to have to disable the node tests for now. Once they are checked in then you need to merge their changes into this PR and get this PR passing with their new tests. Once that is done then it's on to #721 which I think might actually be a non-issue since I think @tompaana might have already fixed it. Please also make sure to review the testing coverage in #555 for both this project as well as for BTLib and confirm you are happy with it. It would be good to take some of the work for #777 as way to get yourself into the code.

---

Reviewed 1 of 2 files at r8, 7 of 7 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 221 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGQN8oxXPy15BNb38sD:-KNKD_Rd65qq89zhBMIS:980690878) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efa61024c5e2090c7c92f74cc2e200f0d3a8f214/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L221)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Shouldn't overflow go to 0 not 1?
</details>
This comment still applies I believe, shouldn't extraInformation = 0 when overflowing? Otherwise aren't we losing one of our change values? E.g. we will only use 1..255 instead of 0.255?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-:-KNKGOxMEqPIzOP_cWDX:-1740135530)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 221 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGQN8oxXPy15BNb38sD:-KNWywqEQ-5sUqwbH5uN:1209389180) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efa61024c5e2090c7c92f74cc2e200f0d3a8f214/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L221)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> This comment still applies I believe, shouldn't extraInformation = 0 when overflowing? Otherwise aren't we losing one of our change values? E.g. we will only use 1..255 instead of 0.255?
</details>
Tomi used 1 instead of 0 because there is the constant  NO_EXTRA_INFORMATION = 0  in PeerProperties in BtLibrary. 0 looks like reserved value 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720)*

**Comment by yaronyg** [comment]
@evabishchevich Make sure you merge this with #762

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3e34e91)

**Comment by ThaliTester** [comment]
Test (Fail) 68102130 build is completed (3e34e91)

See https://github.com/ThaliTester/TestResults/tree/681021303e34e91_Fixes_and_hardening_tompaana/ for the logs

**Comment by evabishchevich** [comment]
Review status: 11 of 50 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/OutgoingSocketThread.java, line 81 \[r7\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KJBS0JN8WM0t7ZWRBz5:-KNgQiQFKTkRxYW3Cku9:579193035) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/08b7140ee4b9037485cb85fe8a8e48298f94f0d9/src/android/java/io/jxcore/node/OutgoingSocketThread.java#L81)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> How exactly would we end up with a null pointer exception?
</details>
There is no possibility to get NPE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720)*

**Comment by yaronyg** [comment]
@evabishchevich I'm going to hold off on reviewing this until 555 is checked in. Most of the diffs here are caused by your merge with 555 and so I would just be reviewing the same changes twice. Instead we'll wait for 555 to go into vNext and then this should only show changes post 555.

---

Reviewed 1 of 39 files at r11.
Review status: 12 of 50 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 221 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGQN8oxXPy15BNb38sD:-KNi4N28aPOieSvCcxCl:1525212303) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efa61024c5e2090c7c92f74cc2e200f0d3a8f214/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L221)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary>
> Tomi used 1 instead of 0 because there is the constant  NO_EXTRA_INFORMATION = 0  in PeerProperties in BtLibrary. 0 looks like reserved value 
</details>
Reserved for what purpose? Also, how can we just delete this code? How do we deal with state roll over?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-:-KNi4btrHZ2pKa3uwEIc:-1853049344)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (40493cb)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (ea857b4)

**Comment by ThaliTester** [comment]
Test (Success) 68102130 build is completed (40493cb)

See https://github.com/ThaliTester/TestResults/tree/6810213040493cb_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 6810213040493cb(40493cb) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/6810213040493cb_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 68102130 build is completed (ea857b4)

See https://github.com/ThaliTester/TestResults/tree/68102130ea857b4_Fixes_and_hardening_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 68102130ea857b4(ea857b4) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/68102130ea857b4_Fixes_and_hardening_tompaana/ for the logs

**Comment by yaronyg** [comment]
@evabishchevich There is just one open issue left and it's really a question. Once we have settled that question then consider this good to check in.

---

Reviewed 23 of 39 files at r11, 4 of 27 files at r12, 22 of 23 files at r13, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 221 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-KGQN8oxXPy15BNb38sD:-KNruVZETSznyGTXQ-WT:-1959283112) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efa61024c5e2090c7c92f74cc2e200f0d3a8f214/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L221)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Reserved for what purpose? Also, how can we just delete this code? How do we deal with state roll over?
</details>
I still need to understand what purpose Tomi was using the 0 for and why he couldn't set extraInformation to 0. Please don't check in until we have this fully clarified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/720#-:-KNsOiwiTNaiIpb90o5n:-126289879)*

**Pull request merged**
