### PR TITLE
Issue 263

### PR DESCRIPTION
**Pull request by tobybrad**
This PR also resolves issue 262.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/272)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r1, 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[scripts/androidAfterPrepare.js, line 50 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K289eJF7OK9N4df68Dy)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/scripts/androidAfterPrepare.js#L50)):</sup>
If any of these commands fail how do we signal that to build system? I'm not sure if a throw necessarily translates to a process.exit(1). Shouldn't we just wrap this in a try catch to be sure? And in the case that everything does work it's good hygiene to exit with a process.exit(0). 


---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerClientSession.m, line 131 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K28AazvXDdBa2Gc6MK1)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/src/ios/MultipeerConnectivity/THEMultipeerClientSession.m#L131)):</sup>
It would be good to have the moral equivalent of a default clause here so we have a final else that throws an exception and logs. And yes, I realize that it shouldn't happen but it could and having the exception and having a log would help us diagnose. 


---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerPeerSession.m, line 56 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K28BGxb3OS5rZ93YvwU)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/src/ios/MultipeerConnectivity/THEMultipeerPeerSession.m#L56)):</sup>
NON BLOCKING - There exist dedicated libraries for Objective-C that let you define the state machine and its transitions directly. I'm using the equivalent in Javascript. I think it makes the code cleaner and easier to follow. Just food for though.


---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerServer.m, line 135 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K28EzHhBuEBcQENUoGK)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/src/ios/MultipeerConnectivity/THEMultipeerServer.m#L135)):</sup>
NON BLOCKING - Is this running on the same thread as JXcore or on a different thread?


---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerSession.m, line 127 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K28F9lQzhkjR7drBkUk)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/src/ios/MultipeerConnectivity/THEMultipeerSession.m#L127)):</sup>
NON-BLOCKING - I'm sorry to make you give me a tutorial in iOS logic but do we really want this on the main thread? Why can't it be on a different thread? We just have so much going on the main thread that it worries me.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272)

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[scripts/androidAfterPrepare.js, line 50 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K289eJF7OK9N4df68Dy)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/scripts/androidAfterPrepare.js#L50)):</sup>
Wanted to point out that we shouldn't process.exit from Cordova hooks. That is the issue the previously prevented `cordova android run` to work since our hook would just exit the cordova process.

I believe the way to make this work better in error scenarios would be to return a promise and resolve/reject it based on what happens within the hook. Here is an example from http://cordova.apache.org/docs/en/edge/guide/appdev/hooks/index.html :
```
module.exports = function(context) {
    var Q = context.requireCordovaModule('q');
    var deferral = new Q.defer();

    setTimeout(function(){
      console.log('hook.js>> end');
    deferral.resolve();
    }, 1000);

    return deferral.promise;
}
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272)

**Comment by tobybrad** [comment]
Review status: 20 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerPeerSession.m, line 56 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K28BGxb3OS5rZ93YvwU)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/src/ios/MultipeerConnectivity/THEMultipeerPeerSession.m#L56)):</sup>
Next time.


---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerServer.m, line 135 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K28EzHhBuEBcQENUoGK)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/src/ios/MultipeerConnectivity/THEMultipeerServer.m#L135)):</sup>
Main thread. Always. Because of the way timers work.


---

<sup>**[src/ios/MultipeerConnectivity/THEMultipeerSession.m, line 127 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272#-K28F9lQzhkjR7drBkUk)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2dbd2c1e0b75db1630d64e2ce6da4326d3b6c266/src/ios/MultipeerConnectivity/THEMultipeerSession.m#L127)):</sup>
Because main thread has a run loop on which timers are scheduled and the jxcore thread, on which this code is executed, does not. Except when you run on simulator. When it magically does. That took a while to spot. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272)

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/272)

**Comment by tobybrad** [comment]
Merged, released, closed.

**Pull request merged**
