### PR TITLE
Updated BtLib version

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1402)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (45e8407)

**Comment by ThaliTester** [comment]
Test (Success) 90362384 build is completed (45e8407)

See https://github.com/ThaliTester/TestResults/tree/9036238445e8407_Updated_BtLib_version_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 9036238445e8407(45e8407) has failed

See https://github.com/ThaliTester/TestResults/tree/9036238445e8407_Updated_BtLib_version_evabishchevich/ for the fail logs

**Comment by larryonoff** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1402)*

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1402#-:-KUbK7O30iyAjoWwlYxo:bnfp4nl)*

**Pull request merged**
