### PR TITLE
Improve data buffer in VirtualSocket.

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1312)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0dc636a)

**Comment by ThaliTester** [comment]
Test (Fail) 89213516 build is completed (0dc636a)

See https://github.com/ThaliTester/TestResults/tree/892135160dc636a_Improve_data_buffer_in_VirtualSocket__dersim-davaod/ for the logs

**Comment by baydet** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 78 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1312#-KUMnMOLEGpub93xaK-c:-KUMnMOLEGpub93xaK-d:b-bx2qvf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0dc636a2a2d7d45efef4d391ef757974bafb17f2/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L78)):*
> ```Swift
> 
>     func writeDataToOutputStream(data: NSData) {
>         bufferToWrite.modify {
> ```

We should add tests to be sure that this buffering logic works as we expect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1312)*

**Comment by yaronyg** [comment]
Subject to fixing @baydet's comment :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1312#-:-KUspIqKpTye-qFDiUCY:b7e6kvl)*

**Comment by dersim-davaod** [comment]
These changes are included in #1429.

**Pull request closed without merging**
