### PR TITLE
Run coordinated desktop tests in CI

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/525)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4d3a10e)

**Comment by ThaliTester** [comment]
Test (Success) 58752353 build is completed (4d3a10e)

See https://github.com/ThaliTester/TestResults/tree/587523534d3a10e_Run_coordinated_desktop_tests_in_CI_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 587523534d3a10e(4d3a10e) has failed

See https://github.com/ThaliTester/TestResults/tree/587523534d3a10e_Run_coordinated_desktop_tests_in_CI_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dc32d9f)

**Comment by tobybrad** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/525)*

**Comment by ThaliTester** [comment]
Test 58752353dc32d9f(dc32d9f) has failed

See https://github.com/ThaliTester/TestResults/tree/58752353dc32d9f_Run_coordinated_desktop_tests_in_CI_vjrantal/ for the fail logs

**Pull request merged**
