### PR TITLE
416 Notification final

### PR DESCRIPTION
**Pull request by juhanak**
Major changes/new files:
testThaliNotification.js: coordinated end to end test
testThaliNotificationLocal.js: local end to end test
testThaliNotificationServer.js: added pskMapCache tests
testThaliPeedDictionary.js: removed assert.deepEquals. 
httpTester.js: Moved agent and https server creation from individual notification tests to here
thaliNotificationClient.js: psk support & cleaning
thaliNotificationServer.js: psk support
thaliPskMapCache.js: psk cache implementation

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/692)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9ce4518)

**Comment by ThaliTester** [comment]
Test (Success) 64809936 build is completed (9ce4518)

See https://github.com/ThaliTester/TestResults/tree/648099369ce4518_416_Notification_final_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 648099369ce4518(9ce4518) has failed

See https://github.com/ThaliTester/TestResults/tree/648099369ce4518_416_Notification_final_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 5 of 16 files at r4, 15 of 15 files at r5.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 60 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDuG41H7sY5bVZhMaa:-KEDuG42PLjNeN6HJwuQ:1535504626) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L60)):*
I think you do need to hook the error event and set things up to retry the request a certain number of times before giving up.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 100 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDsbiidRT-I7gXDwHI:-KEDsbiidRT-I7gXDwHJ:-1190490385) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L100)):*
NB:/we listen this/we listen to this/

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 144 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDt8SO6APF9XKADhUE:-KEDt8SPN-n30nnf94S8:2014748864) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L144)):*
NB: What is this comment for?

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 181 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDt_lhT9z5emsj10wN:-KEDt_lhT9z5emsj10wO:2079208016) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L181)):*
I would set this timer to more like 2 minutes. Things can take a while sometimes.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 191 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDuAjqzVZmnfs35oyd:-KEDuAjqzVZmnfs35oye:508960146) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L191)):*
NB:/http/https

---

*[test/www/jxcore/bv_tests/testThaliNotificationServer.js, line 231 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDc6IvOXrz4VBWAoV0:-KEDc6IvOXrz4VBWAoV1:-135697996) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotificationServer.js#L231)):*
For bonus points in both this and the previous test you should make sure the right entries are still there. :)

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 208 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KECj5KV5GdqiSr0WPRV:-KECj5KV5GdqiSr0WPRW:845793424) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationClient.js#L208)):*
We shouldn't have any console.logs in production code. Everything should go through the logger.

---

*[thali/NextGeneration/notification/thaliNotificationServer.js, line 190 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDVabNQyBS228wSKbR:-KEDVabNQyBS228wSKbS:815869148) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationServer.js#L190)):*
NB: 'PSK key' not a 'private key' that means something else.

---

*[thali/NextGeneration/notification/thaliNotificationServer.js, line 248 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KED_6fZhvIKjbzfTFED:-KED_6f__6_5DCbH3fFZ:-1925340032) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationServer.js#L248)):*
No console.log in production code please and we shouldn't be logging this either.

---

*[thali/NextGeneration/notification/thaliNotificationServer.js, line 249 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KED_C9xSKZm9eag9zQe:-KED_C9xSKZm9eag9zQf:19529015) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationServer.js#L249)):*
NB: Because of the security sensitive nature of this code this is one time where I think it would be worth it to create a common function that just returns the secrets (object if any) and then in the individual functions have them call either getSecret or getPublic if the value isn't null.

---

*[thali/NextGeneration/notification/thaliPskMapCache.js, line 7 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDTF4leud2J1ocgFXc:-KEDTF4leud2J1ocgFXd:-166189873) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliPskMapCache.js#L7)):*
NB: /An/a

---

*[thali/NextGeneration/notification/thaliPskMapCache.js, line 87 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDUbHIh2d5DMfvhLa0:-KEDUbHJg1nYGaW8Zgmd:-1384817706) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliPskMapCache.js#L87)):*
NB: Everywhere else you start from the end and move to the beginning. Why not here as well? As soon as you hit the first dictionary with an expired time you can break and delete everything from that dictionary back to 0. This is a nit pick though and is not blocking you checking in.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6fd8e87)

**Comment by ThaliTester** [comment]
Test (Success) 64809936 build is completed (6fd8e87)

See https://github.com/ThaliTester/TestResults/tree/648099366fd8e87_416_Notification_final_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 648099366fd8e87(6fd8e87) has failed

See https://github.com/ThaliTester/TestResults/tree/648099366fd8e87_416_Notification_final_juhanak/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b717dd3)

**Comment by juhanak** [comment]
Review status: 15 of 21 files reviewed at latest revision, 12 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 60 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDuG41H7sY5bVZhMaa:-KEI4wUET869UvqhH9Z-:563952430) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L60)):*
Added 3 retries to each https request. Also improved test to use public key dictionaries to verify that the peer makes successful request to all peers and that it receives successful request from all peers. 

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 100 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDsbiidRT-I7gXDwHI:-KEFRfuzWESXlMxQgxdR:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L100)):*
Done.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 144 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDt8SO6APF9XKADhUE:-KEI5OaAJl1got5WSc9z:-595887258) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L144)):*
It was reminder (which I forgot existed) to do something with the pskIdentity. This is now implemented. 

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 181 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDt_lhT9z5emsj10wN:-KEIB5BbePbVfwyvRYEi:-997971257) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L181)):*
Ok. It is just painfully long time to wait tests to finish on the desktop. I changed test a little bit so that it is now fixed 2 minutes that it takes to complete it. Previously this timer started when the test got PeerAdvertisesDataForUs from notificationClient for all peers. However I think it made the test too complicated. I mean if some peer didn't send us event then we would be waiting that event forever and test would not finish. This fixed time limit seems cleaner approach. 

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 191 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDuAjqzVZmnfs35oyd:-KEFSlNG5idXd6XJC90k:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotification.js#L191)):*
Done.

---

*[test/www/jxcore/bv_tests/testThaliNotificationServer.js, line 231 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDc6IvOXrz4VBWAoV0:-KEGPMrmnRrNIne2N_oa:-307889184) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/test/www/jxcore/bv_tests/testThaliNotificationServer.js#L231)):*
Sure, added test

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 208 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KECj5KV5GdqiSr0WPRV:-KEGWxPbKpiw57UY1VXP:-189413810) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationClient.js#L208)):*
Removed logging from here.

---

*[thali/NextGeneration/notification/thaliNotificationServer.js, line 190 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDVabNQyBS228wSKbR:-KEFVP1jAwB-xFiBohW4:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationServer.js#L190)):*
Done.

---

*[thali/NextGeneration/notification/thaliNotificationServer.js, line 248 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KED_6fZhvIKjbzfTFED:-KEFVYycPhPN8oOUthg-:-833565123) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationServer.js#L248)):*
Done. It was accidentally left there.

---

*[thali/NextGeneration/notification/thaliNotificationServer.js, line 249 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KED_C9xSKZm9eag9zQe:-KEIAPTlrc5mfJDTy2NT:196228262) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationServer.js#L249)):*
Ok added function _getSecrets altough I quite don't see how it adds security. 

---

*[thali/NextGeneration/notification/thaliPskMapCache.js, line 7 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDTF4leud2J1ocgFXc:-KEFWUB8p44cc5vXJaPk:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliPskMapCache.js#L7)):*
Done.

---

*[thali/NextGeneration/notification/thaliPskMapCache.js, line 87 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEDUbHIh2d5DMfvhLa0:-KEFXlLHfCWvT8hUvrM6:198303947) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliPskMapCache.js#L87)):*
I was trying to follow this spec for removal:
"Note that since the dictionaries MUST be in LIFO order if we start from the
back of the queue then we only need to check expiration's until we hit the
first unexpired dictionary."

In  ThaliPskMapCache._queue object items are from the oldest to newest because I push() them there. Have to admit that queue is a little confusing here. I guess instead of pushing I should use unshift which puts the latest item in the front of the array. I'm not sure would it have any performance hit. 

And then for reading 'specs' said: 
Once we know we have a good set of dictionaries then we take the ID and
starting with the top of the stack we see if any of the dictionaries have
a response.

So that's why these different directions of looping. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692)*

**Comment by ThaliTester** [comment]
Test (Success) 64809936 build is completed (b717dd3)

See https://github.com/ThaliTester/TestResults/tree/64809936b717dd3_416_Notification_final_juhanak/ for the logs

**Comment by yaronyg** [comment]
Reviewed 1 of 4 files at r6, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 137 \[r7\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEIJNs1mscIiaQkMZy0:-KEIJNs1mscIiaQkMZy1:1475345700) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b717dd3b52ea3aaae01313f200c3304f65880627/test/www/jxcore/bv_tests/testThaliNotification.js#L137)):*
What happens if a request gets an 'end' event but didn't get any data? It's also possible in certain connection refusal scenarios for a connection to terminate with neither end nor error being called. So I would suggest that you hook the 'close' event which seems to always get called and figure out there if the data was received and if not then retry.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 240 \[r7\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEIK6foGW-_HAvIWRLj:-KEIK6foGW-_HAvIWRLk:1122448394) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b717dd3b52ea3aaae01313f200c3304f65880627/test/www/jxcore/bv_tests/testThaliNotification.js#L240)):*
If I'm reading this correctly then the test ALWAYS takes 2 minutes. That isn't workable. Our tests are too long as it is. What we need is a way to exit as soon as the test passes or, after 2 minutes, we then exit with a failure.

The way you can do this pretty easily is that you create the setTimeout and remember the returned value. Then you create a 'success' function that is called anywhere you set peerRepliedToUs or peerRequestUs. If the exit conditions are met then you exit and cancel setTimeout and call end. If not, then you let things continue. You would also have a failure function that you would set if failedPskIdentityCount is greater than 0 which would also cancel the setTimeout and call end. Otherwise setTimeout will eventually run and it needs to set a flag saying we have failed (which will cause all calls to the success function and failure function to become NOOPs) and then calls end.

---

*[thali/NextGeneration/notification/thaliNotificationServer.js, line 249 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KED_C9xSKZm9eag9zQe:-KEIIPPyQA32Y3D6bNTo:-1553519458) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ce4518abd6afd9ef2fc38acec1742edc4331af5/thali/NextGeneration/notification/thaliNotificationServer.js#L249)):*
The reason it improves security is that if we find a problem then we fix it in one place and both places the code is used get it. Where as if we used the original version which repeated essentially the same code in two places then any time we find a bug we have to remember to fix that bug in two places.

---

*[thali/NextGeneration/notification/thaliNotificationServer.js, line 194 \[r7\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-KEILQanUnmd8_96Vonp:-KEILQanUnmd8_96Vonq:1552992627) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b717dd3b52ea3aaae01313f200c3304f65880627/thali/NextGeneration/notification/thaliNotificationServer.js#L194)):*
How is the line above any different than 'return this._secrets;'? And given that and given that it is a private function then why do we need it at all? Why not just replace calls to _getSecrets() with this._secrets?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692)*

**Comment by ThaliTester** [comment]
Test 64809936b717dd3(b717dd3) has failed

See https://github.com/ThaliTester/TestResults/tree/64809936b717dd3_416_Notification_final_juhanak/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (29f6128)

**Comment by ThaliTester** [comment]
Test 6480993629f6128(29f6128) has failed

See https://github.com/ThaliTester/TestResults/tree/6480993629f6128_416_Notification_final_juhanak/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3e35f29)

**Comment by ThaliTester** [comment]
Test (Fail) 64809936 build is completed (3e35f29)

See https://github.com/ThaliTester/TestResults/tree/648099363e35f29_416_Notification_final_juhanak/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0fea224)

**Comment by ThaliTester** [comment]
Test (Fail) 64809936 build is completed (0fea224)

See https://github.com/ThaliTester/TestResults/tree/648099360fea224_416_Notification_final_juhanak/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c7914f3)

**Comment by ThaliTester** [comment]
Test (Fail) 64809936 build is completed (c7914f3)

See https://github.com/ThaliTester/TestResults/tree/64809936c7914f3_416_Notification_final_juhanak/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d936b9e)

**Comment by ThaliTester** [comment]
Test (Success) 64809936 build is completed (d936b9e)

See https://github.com/ThaliTester/TestResults/tree/64809936d936b9e_416_Notification_final_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 64809936d936b9e(d936b9e) has failed

See https://github.com/ThaliTester/TestResults/tree/64809936d936b9e_416_Notification_final_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r8, 1 of 1 files at r10, 8 of 8 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/692#-:-KEXUpRMu3696cM0klzf:1417088721)*

**Pull request merged**
