### PR TITLE
#420 Trivial testThaliPeerPoolDefault

### PR DESCRIPTION
**Pull request by yaronyg**
thaliPeerPoolDefault - Created a trivial default pool that just runs all
actions it is given immediately. This should get us unblocked for basic
end to end testing. We'll enhance once we fix the mux layer to send us
the events we need to do more sophisticated management.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/601)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (74f8189)

**Comment by ThaliTester** [comment]
Test (Success) 61776888 build is completed (74f8189)

See https://github.com/ThaliTester/TestResults/tree/6177688874f8189__420_Trivial_testThaliPeerPoolDefault_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 6177688874f8189(74f8189) has failed

See https://github.com/ThaliTester/TestResults/tree/6177688874f8189__420_Trivial_testThaliPeerPoolDefault_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testthaliPeerPoolDefault.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/601#-KCFFmiaxr-9rpOX81z7:-KCFFmiaxr-9rpOX81z8:-472185745) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/74f8189ed5a5e4a58786d7d982b4f0777fad8c87/test/www/jxcore/bv_tests/testthaliPeerPoolDefault.js#L1)):*
Filename seems to have testthali whereas in other cases, we used a format like testThali.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/601)*

**Pull request merged**
