### PR TITLE
First bits of thaliMobile

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/517)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8176cca)

**Comment by ThaliTester** [comment]
Test (Success) 58602427 build is completed (8176cca)

See https://github.com/ThaliTester/TestResults/tree/586024278176cca_First_bits_of_thaliMobile_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 586024278176cca(8176cca) has failed

See https://github.com/ThaliTester/TestResults/tree/586024278176cca_First_bits_of_thaliMobile_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
@vjrantal I'm assuming this is supposed to be assigned to me?

**Comment by yaronyg** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/517)*

**Pull request merged**
