### PR TITLE
removed deprecated specs

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1289)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3a9a644)

**Comment by ThaliTester** [comment]
Test (Success) 88856587 build is completed (3a9a644)

See https://github.com/ThaliTester/TestResults/tree/888565873a9a644_removed_deprecated_specs_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 888565873a9a644(3a9a644) has failed

See https://github.com/ThaliTester/TestResults/tree/888565873a9a644_removed_deprecated_specs_baydet/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1289#-:-KTowjEGXhFJeuVHJrEK:bnfp4nl)*

**Pull request merged**
