### PR TITLE
In Android 6.0 adds a location permission request dialog for test apps

### PR DESCRIPTION
**Pull request by juhanak**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/537)

### CODE REVIEW

**Comment by vjrantal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/js/thali_main.js, line 38 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAKJfbJk_7T3Bmrk46Z:-KAKJfbJk_7T3Bmrk46_:2080397091) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8ffd16ee4b9a5c308ac95a804b9f5b366d14a6be/test/www/js/thali_main.js#L38)):*
Is the status argument meaningful? Should it be at least logged so that in our tests (for example in CI) we could debug what has been returned?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537)*

**Comment by juhanak** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/js/thali_main.js, line 38 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAKJfbJk_7T3Bmrk46Z:-KAKKz6uuJFW_hXwkye1:-2093632065) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8ffd16ee4b9a5c308ac95a804b9f5b366d14a6be/test/www/js/thali_main.js#L38)):*
When request is successful, it always returns a string PERMISSION_GRANTED. Should I add it to logs?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537)*

**Comment by vjrantal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/js/thali_main.js, line 38 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAKJfbJk_7T3Bmrk46Z:-KAKOOMW5nxwRnwSoosp:1453148006) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8ffd16ee4b9a5c308ac95a804b9f5b366d14a6be/test/www/js/thali_main.js#L38)):*
Or, should we get rid of that argument entirely from the API if we don't expect we or someone else has any use for it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537)*

**Comment by juhanak** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/js/thali_main.js, line 38 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAKJfbJk_7T3Bmrk46Z:-KAL7IVK39kmUv1F2aeh:-1935837805) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8ffd16ee4b9a5c308ac95a804b9f5b366d14a6be/test/www/js/thali_main.js#L38)):*
Yes, it makes sense to get rid of that argument. I'll do that change. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537)*

**Comment by vjrantal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/js/thali_main.js, line 42 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAZWXa--dy0ovBKkZV9:-KAZWXa--dy0ovBKkZVA:124700350) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2f45daaa6c4969decf092d89b77279aacd253697/test/www/js/thali_main.js#L42)):*
Sorry to bother you with one more comment, but I guess the error can be at least two different things? Should that be logged here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537)*

**Comment by juhanak** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/js/thali_main.js, line 42 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAZWXa--dy0ovBKkZV9:-KAZXeKTM4H6I35AGqTn:-698535449) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2f45daaa6c4969decf092d89b77279aacd253697/test/www/js/thali_main.js#L42)):*
Yes, I'll add that logging. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537)*

**Comment by vjrantal** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537)*

**Comment by yaronyg** [comment]
I realize this code review is finished but there are some pretty serious issues here that I'm surprised were missed. I would ask that both @vjrantal and @juhanak take a look at my comments below and tat @juhanak please fix.

Also, where is the test to make sure this all works?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[www/android/thaliPermissions.js, line 1 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAlTI-olyoDGa9jVpKE:-KAlTI-olyoDGa9jVpKF:-843493624) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a5e5d3476890c34e401a74660ece0dc1def3cf06/www/android/thaliPermissions.js#L1)):*
This file does not pass JSCS/JSHINT validation. Please fix.

---

*[www/android/thaliPermissions.js, line 29 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAlTWPS9SwxEB8r3S1U:-KAlTWPS9SwxEB8r3S1V:-1957738774) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a5e5d3476890c34e401a74660ece0dc1def3cf06/www/android/thaliPermissions.js#L29)):*
We are defining a class here (which I don't think we should do, btw, but see my comments below on that). To do that properly we could stick in a jsdoc /** at the start which would then include a @classdesc variable to describe what the class is doing followed by the params followed by @constructor with anything specific to the  constructor. You can look at any of the modern NextGeneration files for examples.

---

*[www/android/thaliPermissions.js, line 33 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAlTLPfCzk0iTs-Ws1k:-KAlTLPfCzk0iTs-Ws1l:1015108836) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a5e5d3476890c34e401a74660ece0dc1def3cf06/www/android/thaliPermissions.js#L33)):*
Why would we define a function inside of a parenthesis anyway? That is only needed if we were going to define and immediately call the function with arguments but we aren't so please lose that parenthesis. E.g. it should be function() not (function()

---

*[www/android/thaliPermissions.js, line 42 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAlU7Pi6Ce7UZwGfOiX:-KAlU7Pi6Ce7UZwGfOiY:62966661) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a5e5d3476890c34e401a74660ece0dc1def3cf06/www/android/thaliPermissions.js#L42)):*
This should be defined as an @enum. See the jsdoc site for details.

---

*[www/android/thaliPermissions.js, line 51 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAlUQ5rZk9acXbjhYKk:-KAlUQ5suO6c07j4SwOs:1298265773) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a5e5d3476890c34e401a74660ece0dc1def3cf06/www/android/thaliPermissions.js#L51)):*
There is no such thing as 'function'. There is @callback though. Please create the @callback and then refer to the @callback definition in the param types.

---

*[www/android/thaliPermissions.js, line 54 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-KAlUCO514l19FK-j1P9:-KAlUCO514l19FK-j1PA:-146653096) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a5e5d3476890c34e401a74660ece0dc1def3cf06/www/android/thaliPermissions.js#L54)):*
Why do we need a class here at all? It seems to me that what we really want is to define two static values. There would be module.exports.responseCodes and module.exports.requestLocationPermission.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-:-KAlSyJlPFjP6dSna7Tn:-1433576202)*

**Comment by vjrantal** [comment]
All great and valid comments that I bet @juhanak fixes.

As a side note, "serious issues" might feel a bit extreme wording since these were all non-functional and more about coding convention and docs - still - they could have been caught during the review so I'll take the bullet on that.

As a code reviewer, I did not mandate an automated test since we didn't have a CI with Marshmallow devices and I did not want to block this commit until we do have that. I now created an issue (https://github.com/thaliproject/Thali_CordovaPlugin/issues/547) so that we remember to do that once possible (I should have created this issue already back when I accepted the code review).

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-:-KAnAUuaIoCQi2MHgBVJ:1834600081)*

**Comment by yaronyg** [comment]
My point was just that helping folks new to Node learn how to write proper node is a big deal and code reviews are the time to do it. So when we see code that is functionally correct but not idiomatic we need to point it out so the folks can learn how to 'node'.

In regards to tests, we should still require the tests and until CI is back we expect them to be run locally. Not ideal but better than not having tests. My bigger concern is if this functionality really can be tested in CI since I think it involves a user dialog.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/537#-:-KApBWnvcEQsJ9jiVunM:-733734880)*

**Pull request merged**
