### PR TITLE
skipped no peer discovery for iOS #1323

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1378)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d4625bb)

**Comment by ThaliTester** [comment]
Test (Success) 90041481 build is completed (d4625bb)

See https://github.com/ThaliTester/TestResults/tree/90041481d4625bb_skipped_no_peer_discovery_for_iOS__1323_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 90041481d4625bb(d4625bb) has failed

See https://github.com/ThaliTester/TestResults/tree/90041481d4625bb_skipped_no_peer_discovery_for_iOS__1323_baydet/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1378#-:-KUTfAf8QQxRv4Gl4_S4:bnfp4nl)*

**Pull request merged**
