### PR TITLE
10 attempts run socket tests #1229 and branch vNext_yarong_417_812_1205

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1602)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (150ee9f)

**Comment by ThaliTester** [comment]
Test 96293062 (150ee9f) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96293062 build is completed (150ee9f)

See https://github.com/ThaliTester/TestResults/tree/96293062150ee9f_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 96293062150ee9f(150ee9f) has failed

See https://github.com/ThaliTester/TestResults/tree/96293062150ee9f_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the fail logs

**Comment by evabishchevich** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadMockWithLatch.java, line 25 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEVt7iT_O-Gr4zFh92:-KYEVt7iT_O-Gr4zFh93:b-xfwts7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/IncomingSocketThreadMockWithLatch.java#L25)):*
> ```Java
>     @Override
>     public void onStreamCopyingThreadDone(StreamCopyingThread who) {
>         Log.e("!!", "countdown!");
> ```

I don't think that we need this log

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 142 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEW-xMwWESFewOsqLY:-KYEW-xMwWESFewOsqLZ:bqucotc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L142)):*
> ```Java
> 
>     @Test
>     public void testConstructor() throws Exception {
> ```

Useless test. We are testing that operator new works fine

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 148 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEW8G1wfpvo3Fmoajb:-KYEW8G1wfpvo3Fmoajc:b-cmmnqb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L148)):*
> ```Java
> 
>     @Test
>     public void testGetTcpPortNumber() throws Exception {
> ```

Useless test. I don't think that testing getter via reflection is good idea

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 179 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEWepf8rt3RwgWwFmS:-KYEWepf8rt3RwgWwFmT:b-ac3vex) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L179)):*
> ```Java
>                     mIncomingSocketThread.getLocalHostPort(), is(0));
>         } else {
>             assertThat("getLocalHostPort should return null if mLocalhostSocket is null",
> ```

We will never fall into that branch. Also assert naming lies to us. Comparing primitive type to null is bad idea. The whole idea of this test is to test default value via getter. I don't think that we still need this test

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, line 141 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEY8RrlbcIbRKlPEue:-KYEY8RsUByRbejR2EHL:b-h9433w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java#L141)):*
> ```Java
> 
>     @Test
>     public void testConstructor() throws Exception {
> ```

We don't need that. See comments above

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, line 147 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEYWtXMOcyNQAiBp7J:-KYEYWtXMOcyNQAiBp7K:biavhn5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java#L147)):*
> ```Java
> 
>     @Test
>     public void testGetListeningOnPortNumber() throws Exception {
> ```

Test for default value. It's a disputable  test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (7a5cd25)

**Comment by vasilevskayaem** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadMockWithLatch.java, line 25 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEVt7iT_O-Gr4zFh92:-KYIi6ei44eLfygGUfwe:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/IncomingSocketThreadMockWithLatch.java#L25)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

I don't think that we need this log
</blockquote></details>

Done.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 142 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEW-xMwWESFewOsqLY:-KYIiB-q-iddQzfKFyRa:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L142)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

Useless test. We are testing that operator new works fine
</blockquote></details>

Done.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 148 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEW8G1wfpvo3Fmoajb:-KYIiNY_1w3hbF0cGXOx:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L148)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

Useless test. I don't think that testing getter via reflection is good idea
</blockquote></details>

Done.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 179 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEWepf8rt3RwgWwFmS:-KYIiRi4Dq0x3MXJV0Oe:bvjk3ya) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L179)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

We will never fall into that branch. Also assert naming lies to us. Comparing primitive type to null is bad idea. The whole idea of this test is to test default value via getter. I don't think that we still need this test
</blockquote></details>

removed only unreached part code. let's leave default value check

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, line 141 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEY8RrlbcIbRKlPEue:-KYIigjs62XNt5Qv32SO:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java#L141)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

We don't need that. See comments above
</blockquote></details>

Done.

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, line 147 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEYWtXMOcyNQAiBp7J:-KYIii4dAvKNzyxjlvzl:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java#L147)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

Test for default value. It's a disputable  test
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by ThaliTester** [comment]
Test 96293062 (7a5cd25) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96293062 build is completed (7a5cd25)

See https://github.com/ThaliTester/TestResults/tree/962930627a5cd25_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the logs

**Comment by evabishchevich** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 138 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYJ5bcA2EYJfGSGN8Oi:-KYJ5bcA-KpN9l35vxat:b-1xptlc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7a5cd25da94a9c18905bcaeb28182465ad04b8c9/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L138)):*
> ```Java
> 
>     @Test
>     public void testSetTcpPortNumber() throws Exception {
> ```

Is there any reason for setter and getter test?

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, line 147 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEYWtXMOcyNQAiBp7J:-KYJ5w0x6j8lO9-id7tH:b-7vxwgt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java#L147)):*
<details><summary><i>Previously, vasilevskayaem wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@vasilevskayaem Why did you agreed to delete this test but didn't agree to remove testGetLocalHostPort? They look similar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (71be26a)

**Comment by ThaliTester** [comment]
Test 96293062 (71be26a) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96293062 build is completed (71be26a)

See https://github.com/ThaliTester/TestResults/tree/9629306271be26a_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 9629306271be26a(71be26a) has failed

See https://github.com/ThaliTester/TestResults/tree/9629306271be26a_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6a8dc4e)

**Comment by ThaliTester** [comment]
Test 96293062 (6a8dc4e) build started.

**Comment by vasilevskayaem** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 138 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYJ5bcA2EYJfGSGN8Oi:-KYJt92R6_zsQ2GKCbvX:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7a5cd25da94a9c18905bcaeb28182465ad04b8c9/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L138)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

Is there any reason for setter and getter test?
</blockquote></details>

Done.

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, line 147 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYEYWtXMOcyNQAiBp7J:-KYJtDA4DFSHt3e4so35:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/150ee9f6886114e68892ccefdcda5a9a63d938bb/src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java#L147)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

@vasilevskayaem Why did you agreed to delete this test but didn't agree to remove testGetLocalHostPort? They look similar
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by evabishchevich** [comment]
@yaronyg Please, look at my comments in this PR. They can clarify our concerns about the tests.

**Comment by ThaliTester** [comment]
Test (Success) 96293062 build is completed (6a8dc4e)

See https://github.com/ThaliTester/TestResults/tree/962930626a8dc4e_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 962930626a8dc4e(6a8dc4e) has failed

See https://github.com/ThaliTester/TestResults/tree/962930626a8dc4e_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the fail logs

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-:-KYNTzd5EQzt7tkAAjRo:bg7igk9)*

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 189 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYNlzir9olVFGr-xvBc:-KYNlzirCCPXibyqINw-:bxg54qa) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6a8dc4e4690fe176e336de49f27bd1c670b11971/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L189)):*
> ```Java
>                 attempts--;
>                 closeSockets();
>                 setUp();
> ```

I'm scary about calling setUp manually. Please at least expand some logic into another method and use it in setup too.

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, line 214 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYNmB-J5QlBy-lXrahZ:-KYNmB-J3ox11ydG17mI:b-clb3na) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6a8dc4e4690fe176e336de49f27bd1c670b11971/src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java#L214)):*
> ```Java
>                 attempts--;
>                 closeSockets();
>                 setUp();
> ```

see my comment about setup above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by evabishchevich** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 210 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYNozhCDcyOgdbkNmZr:-KYNozhC-ima5GPNgq_K:b-9mmhbu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6a8dc4e4690fe176e336de49f27bd1c670b11971/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L210)):*
> ```Java
>     }
> 
>     private Future runningOutgoingSocketThread() throws Exception {
> ```

NB: strange naming. Run instead of running is better option as for me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (5c465b9)

**Comment by ThaliTester** [comment]
Test 96293062 (5c465b9) build started.

**Comment by ThaliTester** [comment]
Test 96293062 (5c465b9) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (9a6bd77)

**Comment by vasilevskayaem** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 189 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYNlzir9olVFGr-xvBc:-KYOiipiA1dr01A0uyHr:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6a8dc4e4690fe176e336de49f27bd1c670b11971/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L189)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary><blockquote>

I'm scary about calling setUp manually. Please at least expand some logic into another method and use it in setup too.
</blockquote></details>

Done.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 210 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYNozhCDcyOgdbkNmZr:-KYOik5d2qfzddwj90la:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6a8dc4e4690fe176e336de49f27bd1c670b11971/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L210)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

NB: strange naming. Run instead of running is better option as for me
</blockquote></details>

Done.

---

*[src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java, line 214 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYNmB-J5QlBy-lXrahZ:-KYOipaD6I1osTdbHsKd:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6a8dc4e4690fe176e336de49f27bd1c670b11971/src/android/test/io/jxcore/node/OutgoingSocketThreadTest.java#L214)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary><blockquote>

see my comment about setup above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 72 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYOjaaY30rPAFpK8nHw:-KYOjaaY3YZCUH8peAs9:bqugm6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9a6bd777cd41fdbd284a081e72761b3da3034c7d/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L72)):*
> ```Java
>     }
> 
>     private void init() throws Exception {
> ```

I think initDependencies better name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (c9b8e19)

**Comment by vasilevskayaem** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/test/io/jxcore/node/IncomingSocketThreadTest.java, line 72 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-KYOjaaY30rPAFpK8nHw:-KYOlCERED3ll4tLOaxM:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9a6bd777cd41fdbd284a081e72761b3da3034c7d/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L72)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary><blockquote>

I think initDependencies better name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602)*

**Comment by ThaliTester** [comment]
Test (Fail) 96293062 build is completed (5c465b9)

See https://github.com/ThaliTester/TestResults/tree/962930625c465b9_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 96293062 (9a6bd77) build started.

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1602#-:-KYOmhqw68-0sJR_i86l:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 96293062 build is completed (9a6bd77)

See https://github.com/ThaliTester/TestResults/tree/962930629a6bd77_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 96293062 (c9b8e19) build started.

**Comment by ThaliTester** [comment]
Test 962930629a6bd77(9a6bd77) has failed

See https://github.com/ThaliTester/TestResults/tree/962930629a6bd77_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 96293062 build is completed (c9b8e19)

See https://github.com/ThaliTester/TestResults/tree/96293062c9b8e19_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 96293062c9b8e19(c9b8e19) has failed

See https://github.com/ThaliTester/TestResults/tree/96293062c9b8e19_10_attempts_run_socket_tests__1229_and_branch_vNext_yarong_417_812_1205_vasilevskayaem/ for the fail logs

**Pull request merged**
