### PR TITLE
Not able to build ThaliTestApp for iOS

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1711)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (17fe266)

**Comment by ThaliTester** [comment]
Test 100452811 (17fe266) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100452811 build is completed (17fe266)

See https://github.com/ThaliTester/TestResults/tree/10045281117fe266_Not_able_to_build_ThaliTestApp_for_iOS_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 10045281117fe266(17fe266) has failed

See https://github.com/ThaliTester/TestResults/tree/10045281117fe266_Not_able_to_build_ThaliTestApp_for_iOS_dersim-davaod/ for the fail logs

**Comment by larryonoff** [comment]
@dersim-davaod I have investigate the issue thaliproject/Thali_CordovaPlugin#1709, so this PR doesn't solve the issue. So I'm closing it.

**Pull request closed without merging**
