### PR TITLE
Testing and CI-related changes.

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/208)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[test/TestServer/index.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FnVVyhSuFsTt3Rh3n)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/801faa643790a81ceeae2beedbdb66363164bfc1/test/TestServer/index.js#L1)):</sup>
Please put 'use strict'; back. All of our JS files without exception should have it.


---

<sup>**[test/TestServer/index.js, line 9 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1Fnc47IKc6CIwGunPQ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/TestServer/index.js#L9)):</sup>
Can we just delete this line?


---

<sup>**[test/TestServer/index.js, line 29 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1Fo0lABQgtWst-NWoU)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/TestServer/index.js#L29)):</sup>
I really don't like how much repeated code we have. The code inside start_performance_testing is pretty much identical to setup_unit_test, the code in disconnect (from perf) is pretty much identical to disconnect in unit testing and so on. This isn't good. We need to have this code extracted into functions and then called once. The rule of thumb is - developers never do the same thing twice. so if we have the same code in more than one place it's time to do some refactoring.


---

<sup>**[test/TestServer/index.js, line 94 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FoM6p8xXEnqGtLON7)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/TestServer/index.js#L94)):</sup>
I think we need to register for the error handler for the http server so if we can't get the port we want or something else goes wrong we make sure to log it. Otherwise we can have silent failures and no clue why.


---

<sup>**[test/www/jxcore/lib/CoordinatorConnector.js, line 55 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FpkF21sun5N2jOH4g)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/lib/CoordinatorConnector.js#L55)):</sup>
The identify function here and the initUnitTest function below are identical except for a single string. So why do they have two completely different names? Shouldn't these be factored into a single function that takes the string as an argument?


---

<sup>**[test/www/jxcore/lib/thali-tape.js, line 36 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FqHzK4IeagPMk2XW-)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/lib/thali-tape.js#L36)):</sup>
Why would we do a synchronous file read on a static file every time we create Thali_Tape? Shouldn't this line be put back up into the header where it came from?


---

<sup>**[test/www/jxcore/perf_tests/PerfTestFramework.js, line 71 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1Frr_xtIdJqFSaiPIe)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/perf_tests/PerfTestFramework.js#L71)):</sup>
How can we be sure that end will be called? I realize that this call is supposed to come in from the coordinator but what happens if the app fails due to an unhandled exception and exits out before the coordinator sends exit? In that case there will be nobody on the device running to get the end and shut things down. I remember @DrJukka saying that we were also hooked into the process.on 'uncaughtException' and 'unhandledRejection' in thali-tape but I just went to look and I don't the hooks being used there nor do I see them able to turn off the radios.


---

<sup>**[test/www/jxcore/perf_tests/testFindPeers.js, line 37 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FsV20F8N5ZmIYEFo5)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/perf_tests/testFindPeers.js#L37)):</sup>
Shouldn't we be using peers.forEach() here?


---

<sup>**[test/www/jxcore/UnitTest_app.js, line 57 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1Fsq4ikv8AX5TbhjBF)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/UnitTest_app.js#L57)):</sup>
This is the same issue as I raised with the Performance Unit Test. How can we be sure that in a failure scenario the app is still running on the device in order to get the end message and so shut down the radios? Also what happens if the coordination server is the one who fails? How do we make sure that the radios get turned off in that case on the devices?


---

<sup>**[thali/install/install.js, line 287 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FtigbxvBarjgDBTmr)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/thali/install/install.js#L287)):</sup>
Why did you wrap this in a promise? Why not just do:

```Javascript
return fs.unlink(jxCoreFileLocation)
   .then(function() {
      return Promise.reject();
  });
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208)

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[test/www/jxcore/lib/thali-tape.js, line 36 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FqHzK4IeagPMk2XW-)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/lib/thali-tape.js#L36)):</sup>
The reason the line was moved was that this file gets loaded also in case we are testing on desktop and there, we don't currently run the coordination server that this line relates to.

Since you brought up a performance concern, I refactored so that the file is always present (also when run on desktop) and the require is moved "back up into the header".


---

<sup>**[thali/install/install.js, line 287 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FtigbxvBarjgDBTmr)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/thali/install/install.js#L287)):</sup>
The one you propose is shorter and cleaner so will refactor to use that format instead.

If I am not mistaken, the end result in both should be the same or is it?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208)

**Comment by vjrantal** [comment]
Review status: 32 of 35 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[test/www/jxcore/lib/thali-tape.js, line 36 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FqHzK4IeagPMk2XW-)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/lib/thali-tape.js#L36)):</sup>
Done.


---

<sup>**[thali/install/install.js, line 287 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FtigbxvBarjgDBTmr)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/thali/install/install.js#L287)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208)

**Comment by DrJukka** [comment]
Review status: 32 of 35 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[test/TestServer/index.js, line 9 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1Fnc47IKc6CIwGunPQ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/TestServer/index.js#L9)):</sup>
its useful on testing, I uncomment it often to quickly check which IP address I should be using with tests


---

<sup>**[test/TestServer/index.js, line 29 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1Fo0lABQgtWst-NWoU)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/TestServer/index.js#L29)):</sup>
Will look into that. BTW, did you notice that the two instances are using different classes, so we would need to have both codes in the one function anyway.


---

<sup>**[test/TestServer/index.js, line 94 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FoM6p8xXEnqGtLON7)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/TestServer/index.js#L94)):</sup>
I added the 'uncaughtException' and 'unhandledRejection' for the process to the index.js file 


---

<sup>**[test/www/jxcore/lib/CoordinatorConnector.js, line 55 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FpkF21sun5N2jOH4g)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/lib/CoordinatorConnector.js#L55)):</sup>
This is changed in later versions to use the 'present' event, as described in specs


---

<sup>**[test/www/jxcore/perf_tests/PerfTestFramework.js, line 71 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1Frr_xtIdJqFSaiPIe)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/perf_tests/PerfTestFramework.js#L71)):</sup>
With latest versions, the end will simply log the success and close emit 'end' event, which will cause Coordinator closing.
There are also additional 'uncaughtException' and 'unhandledRejection'handlers, which also will cause Coordinator closing.

Coordinator closing, will endup causing disconnect event to happen, and with disconnect we will then turn off radios.


---

<sup>**[test/www/jxcore/UnitTest_app.js, line 57 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1Fsq4ikv8AX5TbhjBF)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/UnitTest_app.js#L57)):</sup>
changed in later versions similarly as with perf tests. Any exception will cause Coordinator closing, which will cause disconnection to happen. Disconnection will always turn off radios.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208)

**Comment by DrJukka** [comment]
Review status: 32 of 35 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[test/TestServer/index.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FnVVyhSuFsTt3Rh3n)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/801faa643790a81ceeae2beedbdb66363164bfc1/test/TestServer/index.js#L1)):</sup>
done


---

<sup>**[test/www/jxcore/perf_tests/testFindPeers.js, line 37 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FsV20F8N5ZmIYEFo5)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/test/www/jxcore/perf_tests/testFindPeers.js#L37)):</sup>
likely, will try getting it finally changed :)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (df04122)

**Comment by ThaliTester** [comment]
Test Server build has failed. (48458086df04122) See error details below; 
```Error: Command failed: npm WARN package.json socket-chat-example@0.0.1 No repository field.
npm WARN package.json socket-chat-example@0.0.1 No README data
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/fs-extra-promise
npm http GET https://registry.npmjs.org/lie
npm http GET https://registry.npmjs.org/socket.io
npm http 200 https://registry.npmjs.org/fs-extra-promise
npm http GET https://registry.npmjs.org/fs-extra-promise/-/fs-extra-promise-0.2.1.tgz
npm http 200 https://registry.npmjs.org/lie
npm http GET https://registry.npmjs.org/lie/-/lie-3.0.1.tgz
npm http 200 https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/socket.io/-/socket.io-1.3.7.tgz
npm http 200 https://registry.npmjs.org/express
npm http 200 https://registry.npmjs.org/fs-extra-promise/-/fs-extra-promise-0.2.1.tgz
npm http 200 https://registry.npmjs.org/lie/-/lie-3.0.1.tgz
npm http GET https://registry.npmjs.org/express/-/express-4.13.3.tgz
npm http 200 https://registry.npmjs.org/socket.io/-/socket.io-1.3.7.tgz
npm http 200 https://registry.npmjs.org/express/-/express-4.13.3.tgz
npm http GET https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/engine.io
npm http GET https://registry.npmjs.org/socket.io-parser
npm http GET https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/socket.io-adapter
npm http GET https://registry.npmjs.org/has-binary-data
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/es3ify
npm http GET https://registry.npmjs.org/immediate
npm http GET https://registry.npmjs.org/inline-process-browser
npm http GET https://registry.npmjs.org/unreachable-branch-transform
npm http GET https://registry.npmjs.org/content-type
npm http 200 https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/cookie
npm http GET https://registry.npmjs.org/cookie-signature
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/depd
npm http GET https://registry.npmjs.org/escape-html
npm http GET https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/finalhandler
npm http GET https://registry.npmjs.org/fresh
npm http GET https://registry.npmjs.org/merge-descriptors
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/path-to-regexp
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/send
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/utils-merge
npm http GET https://registry.npmjs.org/vary
npm http GET https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/array-flatten
npm http 200 https://registry.npmjs.org/socket.io-adapter
npm http GET https://registry.npmjs.org/content-disposition
npm http 200 https://registry.npmjs.org/socket.io-parser
npm http GET https://registry.npmjs.org/qs
npm http 200 https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/fs-extra/-/fs-extra-0.24.0.tgz
npm http GET https://registry.npmjs.org/socket.io-adapter/-/socket.io-adapter-0.3.1.tgz
npm http GET https://registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.2.4.tgz
npm http 200 https://registry.npmjs.org/has-binary-data
npm http GET https://registry.npmjs.org/bluebird/-/bluebird-2.10.2.tgz
npm http GET https://registry.npmjs.org/has-binary-data/-/has-binary-data-0.1.3.tgz
npm http 200 https://registry.npmjs.org/es3ify
npm http 200 https://registry.npmjs.org/socket.io-client
npm http GET https://registry.npmjs.org/es3ify/-/es3ify-0.1.4.tgz
npm http GET https://registry.npmjs.org/socket.io-client/-/socket.io-client-1.3.7.tgz
npm http 200 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/immediate
npm http GET https://registry.npmjs.org/debug/-/debug-2.1.0.tgz
npm http 200 https://registry.npmjs.org/engine.io
npm http 200 https://registry.npmjs.org/inline-process-browser
npm http 200 https://registry.npmjs.org/unreachable-branch-transform
npm http 200 https://registry.npmjs.org/content-type
npm http 200 https://registry.npmjs.org/cookie
npm http GET https://registry.npmjs.org/engine.io/-/engine.io-1.5.4.tgz
npm http GET https://registry.npmjs.org/immediate/-/immediate-3.0.5.tgz
npm http 200 https://registry.npmjs.org/cookie-signature
npm http GET https://registry.npmjs.org/inline-process-browser/-/inline-process-browser-1.0.0.tgz
npm http 200 https://registry.npmjs.org/depd
npm http 200 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/unreachable-branch-transform/-/unreachable-branch-transform-0.3.0.tgz
npm http 200 https://registry.npmjs.org/escape-html
npm http GET https://registry.npmjs.org/content-type/-/content-type-1.0.1.tgz
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.1.3.tgz
npm http 200 https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz
npm http GET https://registry.npmjs.org/debug/-/debug-2.2.0.tgz
npm http GET https://registry.npmjs.org/escape-html/-/escape-html-1.0.2.tgz
npm http GET https://registry.npmjs.org/depd/-/depd-1.0.1.tgz
npm http 200 https://registry.npmjs.org/finalhandler
npm http 200 https://registry.npmjs.org/fresh
npm http 200 https://registry.npmjs.org/merge-descriptors
npm http 200 https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/etag/-/etag-1.7.0.tgz
npm http GET https://registry.npmjs.org/finalhandler/-/finalhandler-0.4.0.tgz
npm http GET https://registry.npmjs.org/fresh/-/fresh-0.3.0.tgz
npm http GET https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.0.tgz
npm http GET https://registry.npmjs.org/methods/-/methods-1.1.1.tgz
npm http 200 https://registry.npmjs.org/socket.io-adapter/-/socket.io-adapter-0.3.1.tgz
npm http 200 https://registry.npmjs.org/parseurl
npm http 2
...
_typed_array.h:25:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/commons.h:34:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/btree_map.h:31:
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:918:10: warning: class 'btree_internal_locate_plain_compare' was previously declared as a struct [-Wmismatched-tags]
  friend class btree_internal_locate_plain_compare;
         ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:893:8: note: previous use is here
struct btree_internal_locate_plain_compare {
       ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:918:10: note: did you mean struct here?
  friend class btree_internal_locate_plain_compare;
         ^~~~~
         struct
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:919:10: warning: class 'btree_internal_locate_compare_to' was previously declared as a struct [-Wmismatched-tags]
  friend class btree_internal_locate_compare_to;
         ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:901:8: note: previous use is here
struct btree_internal_locate_compare_to {
       ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:919:10: note: did you mean struct here?
  friend class btree_internal_locate_compare_to;
         ^~~~~
         struct
2 warnings generated.
npm http 200 https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 200 https://registry.npmjs.org/balanced-match/-/balanced-match-0.2.1.tgz
npm http 200 https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http GET https://github.com/component/global/archive/v2.0.1.tar.gz
npm http 200 https://github.com/component/global/archive/v2.0.1.tar.gz
In file included from ../src/bufferutil.cc:8:
In file included from /Users/thali/.node-gyp/jxb304/src/node.h:45:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/Proxy/JSEngine.h:21:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/Proxy/V8/v8_typed_array.h:25:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/commons.h:34:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/btree_map.h:31:
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:918:10: warning: class 'btree_internal_locate_plain_compare' was previously declared as a struct [-Wmismatched-tags]
  friend class btree_internal_locate_plain_compare;
         ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:893:8: note: previous use is here
struct btree_internal_locate_plain_compare {
       ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:918:10: note: did you mean struct here?
  friend class btree_internal_locate_plain_compare;
         ^~~~~
         struct
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:919:10: warning: class 'btree_internal_locate_compare_to' was previously declared as a struct [-Wmismatched-tags]
  friend class btree_internal_locate_compare_to;
         ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:901:8: note: previous use is here
struct btree_internal_locate_compare_to {
       ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:919:10: note: did you mean struct here?
  friend class btree_internal_locate_compare_to;
         ^~~~~
         struct
2 warnings generated.
In file included from ../src/validation.cc:8:
In file included from /Users/thali/.node-gyp/jxb304/src/node.h:45:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/Proxy/JSEngine.h:21:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/Proxy/V8/v8_typed_array.h:25:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/commons.h:34:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/btree_map.h:31:
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:918:10: warning: class 'btree_internal_locate_plain_compare' was previously declared as a struct [-Wmismatched-tags]
  friend class btree_internal_locate_plain_compare;
         ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:893:8: note: previous use is here
struct btree_internal_locate_plain_compare {
       ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:918:10: note: did you mean struct here?
  friend class btree_internal_locate_plain_compare;
         ^~~~~
         struct
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:919:10: warning: class 'btree_internal_locate_compare_to' was previously declared as a struct [-Wmismatched-tags]
  friend class btree_internal_locate_compare_to;
         ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:901:8: note: previous use is here
struct btree_internal_locate_compare_to {
       ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:919:10: note: did you mean struct here?
  friend class btree_internal_locate_compare_to;
         ^~~~~
         struct
2 warnings generated.
In file included from ../src/bufferutil.cc:8:
In file included from /Users/thali/.node-gyp/jxb304/src/node.h:45:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/Proxy/JSEngine.h:21:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/Proxy/V8/v8_typed_array.h:25:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/commons.h:34:
In file included from /Users/thali/.node-gyp/jxb304/src/jx/btree_map.h:31:
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:918:10: warning: class 'btree_internal_locate_plain_compare' was previously declared as a struct [-Wmismatched-tags]
  friend class btree_internal_locate_plain_compare;
         ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:893:8: note: previous use is here
struct btree_internal_locate_plain_compare {
       ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:918:10: note: did you mean struct here?
  friend class btree_internal_locate_plain_compare;
         ^~~~~
         struct
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:919:10: warning: class 'btree_internal_locate_compare_to' was previously declared as a struct [-Wmismatched-tags]
  friend class btree_internal_locate_compare_to;
         ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:901:8: note: previous use is here
struct btree_internal_locate_compare_to {
       ^
/Users/thali/.node-gyp/jxb304/src/jx/btree.h:919:10: note: did you mean struct here?
  friend class btree_internal_locate_compare_to;
         ^~~~~
         struct
2 warnings generated.
cp: Thali_CordovaPlugin/test/www/: No such file or directory

```

**Comment by vjrantal** [comment]
Closing this pull request and continuing at https://github.com/thaliproject/Thali_CordovaPlugin/pull/216. All comments so far have been taken into account by myself and @DrJukka.

**Comment by vjrantal** [comment]
<sup>**[thali/install/install.js, line 287 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208#-K1FtigbxvBarjgDBTmr)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/efb0fff3089a401ad074e74d3f6b7d76a80727d0/thali/install/install.js#L287)):</sup>
Now I actually remembered why I went with the promise-wrap. That was because fs.unlink doesn't return a promise so you would end up with an error like:

Failed with - TypeError: Cannot call method 'then' of undefined

I think the right way to handle this is to use the async versions from fs-extra-promise and that is what I now do at https://github.com/thaliproject/Thali_CordovaPlugin/commit/2133d0854468a3e64a5996f4d93aca6c9737a3cf (which also fixes this same issue in another place in this file).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208)

**Comment by yaronyg** [comment]
Reviewed 2 of 3 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/208)

**Pull request closed without merging**
