### PR TITLE
Replacer for hardcoded ids for vNext

### LINKED ISSUE #1141: vNext_aaladev_1070 -> vNext

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1141

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1142)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (5d9b52d)

**Comment by andrew-aladev** [comment]
This merge requires LGTM. Related PR is [here](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1115).

**Comment by ThaliTester** [comment]
Test (Fail) 86522102 build is completed (5d9b52d)

See https://github.com/ThaliTester/TestResults/tree/865221025d9b52d_Replacer_for_hardcoded_ids_for_vNext_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/npm-shrinkwrap.json, line 2 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142#-KSNvXIcynpWajcLh4WI:-KSNvXIcynpWajcLh4WJ:b-tyxcs7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5d9b52d455f2d0cbaeaaec470d118a51fdb05792/thali/install/npm-shrinkwrap.json#L2)):*
> ```JSON
> {
>   "name": "install",
> ```

Please just remove this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142#-:-KSNvnJnnMj4U2mYBGiW:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (39a4b7e)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (0889ce9)

**Comment by andrew-aladev** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/npm-shrinkwrap.json, line 2 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142#-KSNvXIcynpWajcLh4WI:-KSaiQnpmmuf1yaVhJEr:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/39a4b7e6aee13296778939497680e1635dcf0d12/thali/install/npm-shrinkwrap.json#L2)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Please just remove this file.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142)*

**Comment by andrew-aladev** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142)*

**Comment by andrew-aladev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/npm-shrinkwrap.json, line 2 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142#-KSNvXIcynpWajcLh4WI:-KSajxqgV-_4x8CysKrH:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/39a4b7e6aee13296778939497680e1635dcf0d12/thali/install/npm-shrinkwrap.json#L2)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142)*

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142#-:-KSalQoWRafRMOr0Zr2m:bnfp4nl)*

**Comment by larryonoff** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1142)*

**Comment by ThaliTester** [comment]
Test (Success) 86522102 build is completed (39a4b7e)

See https://github.com/ThaliTester/TestResults/tree/8652210239a4b7e_Replacer_for_hardcoded_ids_for_vNext_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 8652210239a4b7e(39a4b7e) has failed

See https://github.com/ThaliTester/TestResults/tree/8652210239a4b7e_Replacer_for_hardcoded_ids_for_vNext_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86522102 build is completed (0889ce9)

See https://github.com/ThaliTester/TestResults/tree/865221020889ce9_Replacer_for_hardcoded_ids_for_vNext_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 865221020889ce9(0889ce9) has failed

See https://github.com/ThaliTester/TestResults/tree/865221020889ce9_Replacer_for_hardcoded_ids_for_vNext_andrew-aladev/ for the fail logs

**Pull request merged**
