### PR TITLE
testing iOS branch

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1467)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dfd0d4e)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (dfd0d4e)

See https://github.com/ThaliTester/TestResults/tree/91818238dfd0d4e_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (93c399b)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (93c399b)

See https://github.com/ThaliTester/TestResults/tree/9181823893c399b_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (182cff4)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (182cff4)

See https://github.com/ThaliTester/TestResults/tree/91818238182cff4_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4955a5a)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (4955a5a)

See https://github.com/ThaliTester/TestResults/tree/918182384955a5a_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (43b5654)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (43b5654)

See https://github.com/ThaliTester/TestResults/tree/9181823843b5654_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4ce0733)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (4ce0733)

See https://github.com/ThaliTester/TestResults/tree/918182384ce0733_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (46088c3)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (46088c3)

See https://github.com/ThaliTester/TestResults/tree/9181823846088c3_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9146540)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (9146540)

See https://github.com/ThaliTester/TestResults/tree/918182389146540_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6b89e3d)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (6b89e3d)

See https://github.com/ThaliTester/TestResults/tree/918182386b89e3d_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d9295d0)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (d9295d0)

See https://github.com/ThaliTester/TestResults/tree/91818238d9295d0_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (31fd0ba)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (31fd0ba)

See https://github.com/ThaliTester/TestResults/tree/9181823831fd0ba_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (29647fd)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (29647fd)

See https://github.com/ThaliTester/TestResults/tree/9181823829647fd_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3a9cc49)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (3a9cc49)

See https://github.com/ThaliTester/TestResults/tree/918182383a9cc49_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8c4a80c)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (8c4a80c)

See https://github.com/ThaliTester/TestResults/tree/918182388c4a80c_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (231efc7)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (231efc7)

See https://github.com/ThaliTester/TestResults/tree/91818238231efc7_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (18e0397)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (18e0397)

See https://github.com/ThaliTester/TestResults/tree/9181823818e0397_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5214ebd)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (5214ebd)

See https://github.com/ThaliTester/TestResults/tree/918182385214ebd_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d12ca48)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (d12ca48)

See https://github.com/ThaliTester/TestResults/tree/91818238d12ca48_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (22c6f76)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (22c6f76)

See https://github.com/ThaliTester/TestResults/tree/9181823822c6f76_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f0efcac)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (f0efcac)

See https://github.com/ThaliTester/TestResults/tree/91818238f0efcac_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c6cfe9d)

**Comment by ThaliTester** [comment]
Test (Fail) 91818238 build is completed (c6cfe9d)

See https://github.com/ThaliTester/TestResults/tree/91818238c6cfe9d_testing_iOS_branch_larryonoff/ for the logs

**Comment by larryonoff** [comment]
test comment

**Comment by larryonoff** [comment]
test comment

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ff180c4)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (c75484c)

**Comment by larryonoff** [comment]
test comment

**Comment by ThaliTester** [comment]
Test (Success) 91818238 build is completed (ff180c4)

See https://github.com/ThaliTester/TestResults/tree/91818238ff180c4_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 91818238ff180c4(ff180c4) has failed

See https://github.com/ThaliTester/TestResults/tree/91818238ff180c4_testing_iOS_branch_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 91818238 build is completed (c75484c)

See https://github.com/ThaliTester/TestResults/tree/91818238c75484c_testing_iOS_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 91818238c75484c(c75484c) has failed

See https://github.com/ThaliTester/TestResults/tree/91818238c75484c_testing_iOS_branch_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
comment

**Comment by larryonoff** [comment]
1

**Pull request closed without merging**
