### PR TITLE
Update to jxcore-cordova 0.1.0

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/454)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3567b2a)

**Comment by ThaliTester** [comment]
Test (Success) 56151780 build is completed (3567b2a)

See https://github.com/ThaliTester/TestResults/tree/561517803567b2a_Update_to_jxcore-cordova_0_1_0_vjrantal/ for the logs

**Comment by tobybrad** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/454)*

**Comment by ThaliTester** [comment]
Test 561517803567b2a(3567b2a) has failed

See https://github.com/ThaliTester/TestResults/tree/561517803567b2a_Update_to_jxcore-cordova_0_1_0_vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
I'll close this to do the forward-integration of `story_001` and jxcore-cordova update with separate PRs. This is to get CI results from these two independently.

**Pull request closed without merging**
