### PR TITLE
Convert space indentation in the project and clean up the code

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1524)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (23c6126)

**Comment by ThaliTester** [comment]
Test (Fail) 93780272 build is completed (23c6126)

See https://github.com/ThaliTester/TestResults/tree/9378027223c6126_Convert_space_indentation_in_the_project_and_clean_up_the_code_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6e5f10e)

**Comment by ThaliTester** [comment]
Test (Fail) 93780272 build is completed (6e5f10e)

See https://github.com/ThaliTester/TestResults/tree/937802726e5f10e_Convert_space_indentation_in_the_project_and_clean_up_the_code_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (836a139)

**Comment by ThaliTester** [comment]
Test (Fail) 93780272 build is completed (836a139)

See https://github.com/ThaliTester/TestResults/tree/93780272836a139_Convert_space_indentation_in_the_project_and_clean_up_the_code_dersim-davaod/ for the logs

**Comment by drinkius** [comment]
Reviewed 41 of 41 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 39 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhiJ1gtFBu_QYeLVSs:-KWhiJ1hXDt8UwjI17N1:b-qnrgmx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L39)):*
> ```Swift
>    Handle disposing advertiser after timeout.
>    */
>   internal var didDisposeAdvertiserForPeerHandler: ((Peer) -> Void)?
> ```

NB - rename:

didDisposeOfAdvertiserForPeerHandler

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 54 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhhRjQfW6Wfl2vCilE:-KWhhP6_jQOL_19z0KtR:bxnwuxi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L54)):*
> ```Swift
> 
>   /**
>    Timeout after which advertiser disposes.
> ```

NB - rewrite:

Timeout after which advertiser gets disposed of

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 68 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhiwPKwgxY951Vk07p:-KWhiwPKwgxY951Vk07q:bg5l6ul) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L68)):*
> ```Swift
> 
>      - disposeAdvertiserTimeout:
>        Timeout after which advertiser disposes.
> ```

NB - rewrite:

Timeout after which advertiser get disposed of.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 140 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhj3VwG3SguIczom2w:-KWhj3VwG3SguIczom2x:bwps9id) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L140)):*
> ```Swift
> 
>   /**
>    Dispose all advertisers.
> ```

NB - rewrite:

Dispose of all advertisers.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 168 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhjB3BzUQQGck-tIf_:-KWhjB3BzUQQGck-tIfa:b-jtwl8f) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L168)):*
> ```Swift
> 
>   /**
>    Disposes advertiser after timeout.
> ```

NB - rewrite:

Disposes of advertiser after timeout.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 175 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhjLNqyV0feu_pzm4M:-KWhjLNqyV0feu_pzm4N:b-6zli98) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L175)):*
> ```Swift
>    After *disposeTimeout* the old `MCNearbyServiceAdvertiser` objects MUST be closed.
>    */
>   private func disposeAdvertiserAfterTimeoutToFinishInvites(
> ```

NB - rename:

func disposeOfAdvertiserAfterTimeoutToFinishInvites(advertiserToBeDisposedOf: Advertiser) {

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/Browser.swift, line 38 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhlquj-cCNR_GAnOpN:-KWhlquj-cCNR_GAnOpO:bqn58mi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/Browser.swift#L38)):*
> ```Swift
> 
>   /**
>    Represents peers that can be invited into MCSession.
> ```

NB - rewrite: 

Represents peers who can be invited into MCSession.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 71 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhnEjgUbiICn-eHeST:-KWhnEjgUbiICn-eHeSU:b2a1ne0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L71)):*
> ```Swift
> 
>   /**
>    Called when creating of `VirtualSocket` is completed.
> ```

NB - rewrite:

Called when creation of `VirtualSocket` is completed.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 173 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhniML6w8tfEIFYHCW:-KWhniML6w8tfEIFYHCX:b2a1ne0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L173)):*
> ```Swift
> 
>   /**
>    Called when creating of `VirtualSocket` is completed.
> ```

NB - rewrite:

Called when creation of `VirtualSocket` is completed.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 192 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhnzk_KEQJgKZOTWEU:-KWhnzk_KEQJgKZOTWEV:b2a1ne0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L192)):*
> ```Swift
> 
>      - completion:
>        Called when creating of `VirtualSocket` is completed.
> ```

NB - rewrite:

Called when creation of `VirtualSocket` is completed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (01b8727)

**Comment by dersim-davaod** [comment]
Review status: 39 of 43 files reviewed at latest revision, 10 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 39 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhiJ1gtFBu_QYeLVSs:-KWl7i4rtBUanfChgwn0:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L39)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rename:
> 
> didDisposeOfAdvertiserForPeerHandler
> 
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 54 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhhRjQfW6Wfl2vCilE:-KWl7sU-U6G6PNKG8ivu:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L54)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rewrite:
> 
> Timeout after which advertiser gets disposed of
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 68 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhiwPKwgxY951Vk07p:-KWl7swQuNZ7Hg48KLCp:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L68)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rewrite:
> 
> Timeout after which advertiser get disposed of.
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 140 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhj3VwG3SguIczom2w:-KWl7wV9P7wELxOzmLn0:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L140)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rewrite:
> 
> Dispose of all advertisers.
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 168 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhjB3BzUQQGck-tIf_:-KWl80Ohm7MouwokEXfB:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L168)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rewrite:
> 
> Disposes of advertiser after timeout.
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift, line 175 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhjLNqyV0feu_pzm4M:-KWlKvjauNBWukKlWvgV:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/AdvertiserManager.swift#L175)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rename:
> 
> func disposeOfAdvertiserAfterTimeoutToFinishInvites(advertiserToBeDisposedOf: Advertiser) {
> 
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/Browser.swift, line 38 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhlquj-cCNR_GAnOpN:-KWl9WEJuxr2dnpIeHEn:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/MultipeerConnectivity/Browser.swift#L38)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rewrite: 
> 
> Represents peers who can be invited into MCSession.
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 71 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhnEjgUbiICn-eHeST:-KWl9cngp6hYIBC_IGZp:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L71)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rewrite:
> 
> Called when creation of `VirtualSocket` is completed.
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 173 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhniML6w8tfEIFYHCW:-KWl9db8Ak9cYwu4ZwQH:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L173)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rewrite:
> 
> Called when creation of `VirtualSocket` is completed.
</details>
Done.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift, line 192 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-KWhnzk_KEQJgKZOTWEU:-KWl9eDJt_xL-mkbKasH:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/836a139cf5d0934bb0bddcd1c5227c4eb52593ed/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocketBuilder.swift#L192)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> NB - rewrite:
> 
> Called when creation of `VirtualSocket` is completed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524)*

**Comment by ThaliTester** [comment]
Test (Success) 93780272 build is completed (01b8727)

See https://github.com/ThaliTester/TestResults/tree/9378027201b8727_Convert_space_indentation_in_the_project_and_clean_up_the_code_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 9378027201b8727(01b8727) has failed

See https://github.com/ThaliTester/TestResults/tree/9378027201b8727_Convert_space_indentation_in_the_project_and_clean_up_the_code_dersim-davaod/ for the fail logs

**Comment by drinkius** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1524#-:-KWrjgDFtKP0URLYLi4U:bnfp4nl)*

**Pull request merged**
