### PR TITLE
Update with latest vNext_yarong_417_812 and put in proper test skips

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1193)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (26f5e3f)

**Comment by ThaliTester** [comment]
Test (Success) 87054988 build is completed (26f5e3f)

See https://github.com/ThaliTester/TestResults/tree/8705498826f5e3f_Update_with_latest_vNext_yarong_417_812_and_put_in_proper_test_skips_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 8705498826f5e3f(26f5e3f) has failed

See https://github.com/ThaliTester/TestResults/tree/8705498826f5e3f_Update_with_latest_vNext_yarong_417_812_and_put_in_proper_test_skips_yaronyg/ for the fail logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 22 of 23 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1193#-:-KSk-_XmU-mrbjrRPMcZ:bnfp4nl)*

**Pull request merged**
