### PR TITLE
#866 Updated jxcore-cordova version to 0.1.2b

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/886)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (79477ac)

**Comment by ThaliTester** [comment]
Test (Success) 81493562 build is completed (79477ac)

See https://github.com/ThaliTester/TestResults/tree/8149356279477ac_Updated_jxcore-cordova_version_to_0_1_2b_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8149356279477ac(79477ac) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8149356279477ac_Updated_jxcore-cordova_version_to_0_1_2b_artemjackson/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/886#-:-KPOKUFiJF3sQV6zE5Wk:bnfp4nl)*

**Comment by yaronyg** [comment]
@artemjackson please make sure that the CI tests are up to date against the latest vNext. In other words try to merge with vnext to see if you are at the latest and if not then do the merge and push a change to run another CI run and if it passes then check in. The trick here is that you are going to have to submit your PRs one at a time.

**Comment by artemjackson** [comment]
@yaronyg this branch is already up to date with `vNext`.
So no checks are needed.

**Comment by yaronyg** [comment]
@artemjackson THANK YOU!!!!!!!!!!!!!

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/886#-:-KPTB85LsQPf9oqvnan6:bnfp4nl)*

**Pull request merged**
