### PR TITLE
Run iOS branch again in CI and confirm that it passes on devices 1654

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1658)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (40205b4)

**Comment by ThaliTester** [comment]
Test 98563774 (40205b4) build started.

**Comment by ThaliTester** [comment]
Test (Success) 98563774 build is completed (40205b4)

See https://github.com/ThaliTester/TestResults/tree/9856377440205b4_Run_iOS_branch_again_in_CI_and_confirm_that_it_passes_on_devices_1654_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (93d976a)

**Comment by ThaliTester** [comment]
Test 9856377440205b4(40205b4) has failed

See https://github.com/ThaliTester/TestResults/tree/9856377440205b4_Run_iOS_branch_again_in_CI_and_confirm_that_it_passes_on_devices_1654_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test 98563774 (93d976a) build started.

**Comment by ThaliTester** [comment]
Test (Success) 98563774 build is completed (93d976a)

See https://github.com/ThaliTester/TestResults/tree/9856377493d976a_Run_iOS_branch_again_in_CI_and_confirm_that_it_passes_on_devices_1654_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 9856377493d976a(93d976a) has failed

See https://github.com/ThaliTester/TestResults/tree/9856377493d976a_Run_iOS_branch_again_in_CI_and_confirm_that_it_passes_on_devices_1654_larryonoff/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1658#-:-KZT02ieNABVQIZZEkJd:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (2f8b159)

**Comment by ThaliTester** [comment]
Test (Fail) 98563774 build is completed (2f8b159)

See https://github.com/ThaliTester/TestResults/tree/985637742f8b159_Run_iOS_branch_again_in_CI_and_confirm_that_it_passes_on_devices_1654_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (732ad98)

**Comment by ThaliTester** [comment]
Test 98563774 (732ad98) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 98563774 build is completed (732ad98)

See https://github.com/ThaliTester/TestResults/tree/98563774732ad98_Run_iOS_branch_again_in_CI_and_confirm_that_it_passes_on_devices_1654_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (13b1ea0)

**Comment by ThaliTester** [comment]
Test 98563774 (13b1ea0) build started.

**Comment by ThaliTester** [comment]
Test (Success) 98563774 build is completed (13b1ea0)

See https://github.com/ThaliTester/TestResults/tree/9856377413b1ea0_Run_iOS_branch_again_in_CI_and_confirm_that_it_passes_on_devices_1654_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 9856377413b1ea0(13b1ea0) has failed

See https://github.com/ThaliTester/TestResults/tree/9856377413b1ea0_Run_iOS_branch_again_in_CI_and_confirm_that_it_passes_on_devices_1654_larryonoff/ for the fail logs

**Comment by evabishchevich** [comment]
@yaronyg Looks like non actual PR for now. We still have known issues with CI

**Pull request closed without merging**
