### PR TITLE
added ssid name parameter to node call

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1320)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (ea76302)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (e01367f)

**Comment by ThaliTester** [comment]
Test (Success) 89361553 build is completed (ea76302)

See https://github.com/ThaliTester/TestResults/tree/89361553ea76302_added_ssid_name_parameter_to_node_call_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 89361553 build is completed (e01367f)

See https://github.com/ThaliTester/TestResults/tree/89361553e01367f_added_ssid_name_parameter_to_node_call_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 89361553ea76302(ea76302) has failed

See https://github.com/ThaliTester/TestResults/tree/89361553ea76302_added_ssid_name_parameter_to_node_call_vasilevskayaem/ for the fail logs

**Comment by ThaliTester** [comment]
Test 89361553e01367f(e01367f) has failed

See https://github.com/ThaliTester/TestResults/tree/89361553e01367f_added_ssid_name_parameter_to_node_call_vasilevskayaem/ for the fail logs

**Comment by larryonoff** [comment]
@evabishchevich please review

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1320#-:-KW2pCym7tlGIlRToHHN:bnfp4nl)*

**Comment by larryonoff** [comment]
@yaronyg please review

**Pull request merged**
