### PR TITLE
#86

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/979)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (42466a2)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (3a9a586)

**Comment by ThaliTester** [comment]
Test (Success) 83591764 build is completed (42466a2)

See https://github.com/ThaliTester/TestResults/tree/8359176442466a2__86_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 8359176442466a2(42466a2) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8359176442466a2__86_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 83591764 build is completed (3a9a586)

See https://github.com/ThaliTester/TestResults/tree/835917643a9a586__86_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 835917643a9a586(3a9a586) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/835917643a9a586__86_vasilevskayaem/ for the logs

**Comment by evabishchevich** [comment]
When https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/pull/87 get LGTM, I'll review this one

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/979#-:-KQ_BhmydC0EB2q6Ula_:bqjbayd)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (b77310c)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (f116baa)

**Comment by ThaliTester** [comment]
Test (Fail) 83591764 build is completed (b77310c)

See https://github.com/ThaliTester/TestResults/tree/83591764b77310c__86_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 8. task. (81a80d7)

**Comment by ThaliTester** [comment]
Test (Success) 83591764 build is completed (f116baa)

See https://github.com/ThaliTester/TestResults/tree/83591764f116baa__86_vasilevskayaem/ for the logs

**Comment by vasilevskayaem** [comment]
work started in vNext_vasilevskayaem_86, after changes appears next core test fails, continue working

--- Failed tests ---
2016-09-09T10:28:32.191Z - warn: 64. #startUpdateAdvertisingAndListening - destroying remote peers connection kills the local connection - fail
2016-09-09T10:28:32.191Z - warn: 67. We do not emit peerAvailabilityChanged events until one of the start methods is called - fail
2016-09-09T10:28:32.191Z - warn: 68. Test updating advertising and parallel data transfer - fail
2016-09-09T10:28:32.191Z - warn: 69. initial peer discovery - fail
2016-09-09T10:28:32.191Z - warn: 70. update peer discovery 1 - fail
2016-09-09T10:28:32.191Z - warn: 71. update peer discovery 2 - fail
2016-09-09T10:28:32.191Z - warn: 72. check latest peer discovery - fail
2016-09-09T10:28:32.191Z - warn: 73. no peer discovery - fail
2016-09-09T10:28:32.191Z - warn: 107. Action fails because of a bad hostname. - fail
2016-09-09T10:28:32.192Z - info:
2016-09-09T11:12:23.860Z - info: Running on android test: 59. Can connect to a remote peer
2016-09-09T11:13:48.396Z - warn: Failed on android test: 59. Can connect to a remote peer

**Comment by ThaliTester** [comment]
Test 83591764f116baa(f116baa) has failed

See https://github.com/ThaliTester/TestResults/tree/83591764f116baa__86_vasilevskayaem/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 83591764 build is completed (81a80d7)

See https://github.com/ThaliTester/TestResults/tree/8359176481a80d7__86_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 8359176481a80d7(81a80d7) has failed

See https://github.com/ThaliTester/TestResults/tree/8359176481a80d7__86_vasilevskayaem/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (1a423dc)

**Comment by ThaliTester** [comment]
Test (Fail) 83591764 build is completed (1a423dc)

See https://github.com/ThaliTester/TestResults/tree/835917641a423dc__86_vasilevskayaem/ for the logs

**Comment by yaronyg** [comment]
@vasilevskayaem I think we should just close this PR and make a note in issue thaliproject/Thali_CordovaPlugin_BtLibrary#86 of which branch you put the fix code into. What do you think?

**Pull request closed without merging**
