### PR TITLE
chore(identityExchange): make all base64 URL safe

### PR DESCRIPTION
**Pull request by mpodwysocki**
This change set is to fix the issue with base64 encoding of buffers which included URL unsafe characters.  

Closes Issues #326 #297

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/369)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b0394d0)

**Comment by ThaliTester** [comment]
Build is completed (Success) but couldn't commit the log file. (b0394d0)


/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `cd /Users/thali/Github/CI/reporting;chmod +x ./push_logs.sh;./push_logs.sh 52599842b0394d0_chore(identityExchange)__make_all_base64_URL_safe_mpodwysocki'


Error: Command failed: /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `cd /Users/thali/Github/CI/reporting;chmod +x ./push_logs.sh;./push_logs.sh 52599842b0394d0_chore(identityExchange)__make_all_base64_URL_safe_mpodwysocki'


null

**Comment by yaronyg** [comment]
Reviewed 1 of 2 files at r1, 11 of 12 files at r3.
Review status: 12 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[.jscsrc, line 1 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hpfZEMHDVySWUt3RO:-K4hpfZEMHDVySWUt3RP:1393285719) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/.jscsrc#L1)):*
Please talk to the team and make sure everyone is o.k. with us turning this on right now. Please make it clear to people that they can exempt existing node.js files and that this only applies to next generation files.

---

*[.jscsrc, line 17 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hq9UAn38bVP1CPPPc:-K4hq9UAn38bVP1CPPPd:2014481300) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/.jscsrc#L17)):*
There is a change to this line in the jscsrc in master. Can you please RI from master to here so we have the same version of this file in both places?

---

*[.jshintrc, line 2 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hqGEVSuVYz8rF0Sdr:-K4hqGEVSuVYz8rF0Sds:423360521) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/.jshintrc#L2)):*
Please RI the changes we made in master to jshintrc to here as well. 

---

*[test/www/jxcore/bv_tests/testIdentityExchange.js, line 13 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hqQ4E2EXVCYfZ0b_E:-K4hqQ4E2EXVCYfZ0b_F:1419417044) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/test/www/jxcore/bv_tests/testIdentityExchange.js#L13)):*
What the heck are our rules regarding capitalization? For example both EventEmitter and urlSafeBase64 both represent 'static' objects we call methods on but one is capitalized and the other is not.

---

*[test/www/jxcore/bv_tests/testSmallerHashStateMachine.js, line 8 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hr8De5oGpx20YnfKq:-K4hr8DfgAprtXZKTrE0:-1874392824) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/test/www/jxcore/bv_tests/testSmallerHashStateMachine.js#L8)):*
Same capitalization issue, I'm not sure what the right answer is but some consistency seems reasonable.

---

*[test/www/jxcore/package.json, line 38 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hrbhvTmF35YEfYWtS:-K4hrbhvTmF35YEfYWtT:329800216) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/93b632f224a3be3a1809322bbdbcf110a28860da/test/www/jxcore/package.json#L38)):*
If we have gotten rid of tape-catch then how are we handling exceptions?

---

*[thali/identityExchange/identityExchangeUtils.js, line 76 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hzOU3x588We_jmDko:-K4hywz_ywaoAeJW079L:126553216) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/thali/identityExchange/identityExchangeUtils.js#L76)):*
FYI this is a nice catch. I just went with a generic design when I put this together that I knew would work but the reality is that the callback on then takes exactly one argument so we can tighten it up the way you did here. Nice.

---

*[thali/identityExchange/identityExchangeUtils.js, line 115 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hzr4VZzoGbJHnGwpP:-K4hzr4VZzoGbJHnGwpQ:-182351441) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/thali/identityExchange/identityExchangeUtils.js#L115)):*
BTW this is yet another nice catch. I still don't really write idiomatic Javascript mostly because the fact that what you did here works is just plain evil. :) But I do agree that it is clearly better Javascript.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ca8be2e)

**Comment by ThaliTester** [comment]
Build is completed (Success) but couldn't commit the log file. (ca8be2e)


/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `cd /Users/thali/Github/CI/reporting;chmod +x ./push_logs.sh;./push_logs.sh 52599842ca8be2e_chore(identityExchange)__make_all_base64_URL_safe_mpodwysocki'


Error: Command failed: /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `cd /Users/thali/Github/CI/reporting;chmod +x ./push_logs.sh;./push_logs.sh 52599842ca8be2e_chore(identityExchange)__make_all_base64_URL_safe_mpodwysocki'


null

**Comment by mpodwysocki** [comment]
*[test/www/jxcore/bv_tests/testIdentityExchange.js, line 13 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hqQ4E2EXVCYfZ0b_E:-K4iFVgJhfP1ekNOv7cO:-362110878) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/test/www/jxcore/bv_tests/testIdentityExchange.js#L13)):*
The way we set it up in JSHint and JSCS is the following:
1. If it is a class and newable, then it must start with a capital letter.
2. If it is just a plain object that is not newable, then normal camelCase applies
3. Constants such as hard numbers should be SCREAMING_SNAKE_CASE

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369)*

**Comment by mpodwysocki** [comment]
*[test/www/jxcore/bv_tests/testSmallerHashStateMachine.js, line 8 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hr8De5oGpx20YnfKq:-K4iGLZ9TqmJb6UkhjJ-:1995197299) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/test/www/jxcore/bv_tests/testSmallerHashStateMachine.js#L8)):*
See above answer

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369)*

**Comment by mpodwysocki** [comment]
*[test/www/jxcore/package.json, line 38 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hrbhvTmF35YEfYWtS:-K4iGOrdveNZRtHbgWtU:-819363943) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/93b632f224a3be3a1809322bbdbcf110a28860da/test/www/jxcore/package.json#L38)):*
oh crap, somehow the merge screwed that up...  Let me add it back in.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369)*

**Comment by mpodwysocki** [comment]
*[thali/identityExchange/identityExchangeUtils.js, line 76 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hzOU3x588We_jmDko:-K4iHaHgdPeN4okCAxU3:366002526) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/thali/identityExchange/identityExchangeUtils.js#L76)):*
Yes, apply(this, arguments) isn't necessary if we know that Promises can only emit a single value.  Makes it clearer to the user as well

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369)*

**Comment by mpodwysocki** [comment]
*[thali/identityExchange/identityExchangeUtils.js, line 115 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hzr4VZzoGbJHnGwpP:-K4iHnIByuUMBPaRGN7K:-818306690) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/thali/identityExchange/identityExchangeUtils.js#L115)):*
Yeah, the beauty of falsey-ness is always a fun topic in JS but it makes a good point of using the error as it stands or the newly created error

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369)*

**Comment by mpodwysocki** [comment]
*[test/www/jxcore/bv_tests/testIdentityExchange.js, line 13 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369#-K4hqQ4E2EXVCYfZ0b_E:-K4iIXCkyHiSQOnZYuZN:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b0394d036476e9be750ae35cdd1d49e7b433956a/test/www/jxcore/bv_tests/testIdentityExchange.js#L13)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369)*

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/369)*

**Pull request merged**
