### PR TITLE
Fix #539, get rid of magic values and increase perf

### LINKED ISSUE #539: Test in testThaliNotificationBeacons.js sometimes fails
To reproduce:
```
$ git checkout vNext
$ ./thali/install/setUpDesktop.sh
$ cd test/www/jxcore
$ jx bv_tests/testThaliNotificationBeacons.js
```
The issue happens only rarely, but when it does, there is what it looks like:
```
# setup
# #parseBeacons addressBookCallback returns public key
not ok 19 should be equal
  ---
    operator: equal
    expected: 1
    actual:   2
    at: Test.<anonymous> (/Users/vjrantal/Software/Thali/Thali_CordovaPlugin/test/www/jxcore/bv_tests/testThaliNotificationBeacons.js:404:5)
  ...
```
The easiest way to reproduce that I have found is just to loop the test as long as the error occurs. This can be done with a bash script like:
```
#!/bin/bash

set -e

COUNTER=0
while [  $COUNTER -lt 1000 ]; do
    jx bv_tests/testThaliNotificationBeacons.js
    let COUNTER=COUNTER+1
done
```

### PR DESCRIPTION
**Pull request by yaronyg**
We had a spurious match during decryption that would occasionally cause
our counts to be off.

testThaliNotificationBeacons - Removed or at least better explained
magic values

thaliNotificationBeacons - Got rid of magic values and also pulled
calculating sey out of parse beacons so we only perform the ECDH
operation once per beacon string instead of once per beacon! Did the same
for the HKDF hkey value.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/560)

### CODE REVIEW

**Comment by cicorias** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliNotificationBeacons.js, line 305 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560#-KAvJVlk8kGTx873lPyo:-KAvJVllgSuNIjhH3jsZ:292297544) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/41263e197898e565407538037bd385b5f04c86a7/thali/NextGeneration/thaliNotificationBeacons.js#L305)):*
is this intentional?  if at this point, wouldn't it all fail from here forward on the continue? also, which failed ,the createDecipher, or buffer.concat.?  

should something happen with e.message?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560)*

**Comment by yaronyg** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliNotificationBeacons.js, line 305 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560#-KAvJVlk8kGTx873lPyo:-KAvKafs46G_3dXiVq1o:-357466210) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/41263e197898e565407538037bd385b5f04c86a7/thali/NextGeneration/thaliNotificationBeacons.js#L305)):*
Yes, the continue is expected. If the decrypt fails that means that the beacon we are examining isn't for us and we move on. The more awful case is that because JXcore doesn't support GCM it's possible to get a false positive where it looks like decryption did work when it didn't. But we are hardened against tat.

The real reason I don't check the exception is because exception handling in Javascript is a disaster. Pretty much nobody (including us) bothers to do anything even remotely sensible. For example, Node.js's decrypt API doesn't return an error object of some sub-type so we could detect by type what it is. All you can do is look at the exception value and if you look at the string you will see that it is so specific that any change in Node will cause the check to fail. :( But it's the best we can do for the moment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560)*

**Comment by cicorias** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliNotificationBeacons.js, line 305 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560#-KAvJVlk8kGTx873lPyo:-KB8GQHtZpc3FOGU_hOl:417842772) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/41263e197898e565407538037bd385b5f04c86a7/thali/NextGeneration/thaliNotificationBeacons.js#L305)):*
OK - and there was that "continue" - is that supposed to continue the for loop of perhaps a break out of it?

---

*[thali/NextGeneration/thaliNotificationBeacons.js, line 309 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560#-KB8GawJU7mrJDyRjuVF:-KB8GawJU7mrJDyRjuVG:2020542818) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/cc4a0ad1fae9f051a9433f0b974368c1f63fc130/thali/NextGeneration/thaliNotificationBeacons.js#L309)):*
should this be a break or continue? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560)*

**Comment by cicorias** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliNotificationBeacons.js, line 305 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560#-KAvJVlk8kGTx873lPyo:-KB9MN7rk6t18Vxar2Xa:114579362) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/41263e197898e565407538037bd385b5f04c86a7/thali/NextGeneration/thaliNotificationBeacons.js#L305)):*
It's continue because if we do get a decryption error that just tells us that this specific token isn't for us. It doesn't tell us anything about the next token. So the best we can do is a continue so we can see that next token.

---

*[thali/NextGeneration/thaliNotificationBeacons.js, line 309 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560#-KB8GawJU7mrJDyRjuVF:-KB9MuMAtGRTU1Ju9-tS:1116083657) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/cc4a0ad1fae9f051a9433f0b974368c1f63fc130/thali/NextGeneration/thaliNotificationBeacons.js#L309)):*
See previous

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/560)*

**Pull request merged**
