### PR TITLE
Fixed cast exception. Implemented proper logic for 1507 issue

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1559)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4e01fb7)

**Comment by ThaliTester** [comment]
Test 95006592 (4e01fb7) build started.

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1559#-:-KXGbjX_YYCZPApFK_y5:bnfp4nl)*

**Comment by vasilevskayaem** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1559#-:-KXGiViweaHJNdI7wsIU:bnfp4nl)*

**Comment by evabishchevich** [comment]
@yaronyg Tested locally with ThaliTest and ThaliTestApps. LGTM's are based on these results. 
I'm going to merge after CI will be back and the build will be completed

**Comment by ThaliTester** [comment]
Test 95006592 (4e01fb7) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95006592 build is completed (4e01fb7)

See https://github.com/ThaliTester/TestResults/tree/950065924e01fb7_Fixed_cast_exception__Implemented_proper_logic_for_1507_issue_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 950065924e01fb7(4e01fb7) has failed

See https://github.com/ThaliTester/TestResults/tree/950065924e01fb7_Fixed_cast_exception__Implemented_proper_logic_for_1507_issue_evabishchevich/ for the fail logs

**Pull request merged**
