### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by yaronyg**
Please give me a LGTM if this fixes the issue.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1049)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9fe681f)

**Comment by chapko** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 458 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049#-KRijjxiUa-GIMSQmoO2:-KRijjxiUa-GIMSQmoO3:b-sr6ie) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9fe681f65b0e567c1780f8fbd93ff9a703859cfc/thali/NextGeneration/thaliMobileNativeWrapper.js#L458)):*
> will pass the **port** from {@link module:TCPServersManager.start}

Native layer connects to this port to bridge non-tcp transport over tcp connection. Am I correct?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 467 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049#-KRikdPqOS_xTHpT8RCf:-KRikdPqOS_xTHpT8RCg:b-to5tcm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9fe681f65b0e567c1780f8fbd93ff9a703859cfc/thali/NextGeneration/thaliMobileNativeWrapper.js#L467)):*
> ```JavaScript
>  * On `multiConnect` platforms all incoming TCP connections are sent directly to
>  * the router started by {@link module:thaliMobileNativeWrapper.start} since we 
>  * have no need for {@link module:TCPServersManager} on these platforms.
> ```

What port should we use for `multiConnect` devices? I think it should be specified here too as for `connect` devices.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049)*

**Comment by ThaliTester** [comment]
Test 854387469fe681f(9fe681f) has failed

See https://github.com/ThaliTester/TestResults/tree/854387469fe681f_Fixed_a_typo_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
Back to you @chapko 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 458 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049#-KRijjxiUa-GIMSQmoO2:-KRjiKgPIsQr99rGyvDF:bxbyta) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9fe681f65b0e567c1780f8fbd93ff9a703859cfc/thali/NextGeneration/thaliMobileNativeWrapper.js#L458)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> > will pass the **port** from {@link module:TCPServersManager.start}
> 
> Native layer connects to this port to bridge non-tcp transport over tcp connection. Am I correct?
</details>
Yup.

Native talks to the TCPServersManager listener's port and the TCPServersManager's listener then de-muxes the in coming connection and creates as many individual TCP client connections as necessary to the 'real' HTTPS router.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 467 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049#-KRikdPqOS_xTHpT8RCf:-KRjibFEvwazueSu3E9k:bhxpsbw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9fe681f65b0e567c1780f8fbd93ff9a703859cfc/thali/NextGeneration/thaliMobileNativeWrapper.js#L467)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> What port should we use for `multiConnect` devices? I think it should be specified here too as for `connect` devices.
</details>
It's actually specified in thaliMobileNative.js in the definition for startUpdateAdvertisingAndListening as the first argument, portNumber. If you look at the code below you can see it when we callNative and the first argument is gServersManagerLocalPort. gServersManagerLocalPort is actually created in the start method to thaliMobileNativeWrapper which is why it isn't passed in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049#-:-KRjj_V06xYLGX7P20Cq:bov46wq)*

**Comment by chapko** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 467 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049#-KRikdPqOS_xTHpT8RCf:-KRmuMADm2XhNp7R7REl:bn124ts) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9fe681f65b0e567c1780f8fbd93ff9a703859cfc/thali/NextGeneration/thaliMobileNativeWrapper.js#L467)):*
Now it becomes really confusing. Spec says

> we have no need for `TCPServersManager` on these platforms

but then we use port provided by `TCPServersManager`.

As I understand it we don't need to create `TCPServersManager` in start method of thaliMobileNativeWrapper module on multiconnect platforms. My guess is that we pass `gRouterServerPort` so native tcp socket talks directly to our https server.

Am I missing something here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 467 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049#-KRikdPqOS_xTHpT8RCf:-KRoChnFCjnOV0P3Ucj6:b-5i3cb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9fe681f65b0e567c1780f8fbd93ff9a703859cfc/thali/NextGeneration/thaliMobileNativeWrapper.js#L467)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> Now it becomes really confusing. Spec says
> 
> > we have no need for `TCPServersManager` on these platforms
> 
> but then we use port provided by `TCPServersManager`.
> 
> As I understand it we don't need to create `TCPServersManager` in start method of thaliMobileNativeWrapper module on multiconnect platforms. My guess is that we pass `gRouterServerPort` so native tcp socket talks directly to our https server.
> 
> Am I missing something here?
</details>
I think thaliMobileNative and thaliMobileNativeWrapper are getting confused here.

1. In thaliMobile we call start, if the network type is native or both then this will cause us to call start on thaliMobileNativeWrapper
2. In thaliMobileNativeWrapper.start we create the router object and the server that will host it. That server is listening on gRouterServerPort. 
3. Then we call stopCreateAndStartServersManager. THAT is the code that is only supposed to run when we are on Android because it is the code that creates the mux listener (on gServersManagerLocalPort) that we will pass to connect. So at that point the native code calls gServersManagerLocalPort and the mux eventually then calls gRouterServerPort.

So when we are on iOS we have to not call stopCreateAndStartServersManager since it has no role. And instead we need to just pass gRouterServerPort to the native startUpdateAdvertisingAndListening rather than gServersManagerLocalPort. So on iOS the native code will call gRouterServerPort directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049)*

**Comment by chapko** [comment]
:LGTM:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1049#-:-KS0hktSAryxlop69ZWN:bmxilld)*

**Pull request merged**
