### PR TITLE
Fixed default adapter and test of pouchdb generator

### PR DESCRIPTION
**Pull request by andrew-aladev**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/795)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (75e6d2e)

**Comment by ThaliTester** [comment]
Test (Fail) 78838688 build is completed (75e6d2e)

See https://github.com/ThaliTester/TestResults/tree/7883868875e6d2e_Fixed_default_adapter_and_test_of_pouchdb_generator_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (18f64ad)

**Comment by ThaliTester** [comment]
Test (Fail) 78838688 build is completed (18f64ad)

See https://github.com/ThaliTester/TestResults/tree/7883868818f64ad_Fixed_default_adapter_and_test_of_pouchdb_generator_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b2c39a0)

**Comment by ThaliTester** [comment]
Test (Fail) 78838688 build is completed (b2c39a0)

See https://github.com/ThaliTester/TestResults/tree/78838688b2c39a0_Fixed_default_adapter_and_test_of_pouchdb_generator_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
Reviewed 3 of 4 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/bv_tests/testPouchDBGenerator.js, line 25 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/795#-KNnlBABHpIEBaVOmVc2:-KNnlBACpad3dHcSvfm-:994223317) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b2c39a00567c2e53d9d6f132787bc1b1c068873f/test/www/jxcore/bv_tests/testPouchDBGenerator.js#L25)):*
> ```JavaScript
>   teardown: function (t) {
>     if (fs.existsSync(defaultDirectory)) {
>       del(defaultDirectory).then(function () {
> ```

Why introduce a whole new dependency when we already support fs-extra-promise which has remove dir capability via fs and fs-extra?

---

*[test/www/jxcore/bv_tests/testPouchDBGenerator.js, line 26 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/795#-KNnlLYDBprwTi-vsvEO:-KNnlLYDBprwTi-vsvEP:-1879262977) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b2c39a00567c2e53d9d6f132787bc1b1c068873f/test/www/jxcore/bv_tests/testPouchDBGenerator.js#L26)):*
> ```JavaScript
>     if (fs.existsSync(defaultDirectory)) {
>       del(defaultDirectory).then(function () {
>         t.end();
> ```

Why do you need the t.end() here and the else below? Why not just remove this t.end() and the else and just stick a t.end() at the bottom?

---

*[thali/NextGeneration/utils/pouchDBGenerator.js, line 4 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/795#-KNsPgl0mZ0VsX6GalMs:-KNsPgl0mZ0VsX6GalMt:-1284980579) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b2c39a00567c2e53d9d6f132787bc1b1c068873f/thali/NextGeneration/utils/pouchDBGenerator.js#L4)):*
> ```JavaScript
> 
> var inherits = require('inherits');
> var objectAssign = require('object-assign');
> ```

NB: I'm curious, why did you change from js-extend to object-assign?

---

*[thali/NextGeneration/utils/pouchDBGenerator.js, line 79 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/795#-KNsPudw5CisCew4IwUg:-KNsPudw5CisCew4IwUh:-637824032) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b2c39a00567c2e53d9d6f132787bc1b1c068873f/thali/NextGeneration/utils/pouchDBGenerator.js#L79)):*
> ```JavaScript
> }
> 
> PouchDBGenerator.defaults = {
> ```

Is there really any point in even having this anymore since we don't have any defaults?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/795)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (67d86c3)

**Comment by ThaliTester** [comment]
Test (Fail) 78838688 build is completed (67d86c3)

See https://github.com/ThaliTester/TestResults/tree/7883868867d86c3_Fixed_default_adapter_and_test_of_pouchdb_generator_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[thali/NextGeneration/utils/pouchDBGenerator.js, line 4 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/795#-KNsPgl0mZ0VsX6GalMs:-KOCZdYRzMWo47zTAFra:-1262335989) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b2c39a00567c2e53d9d6f132787bc1b1c068873f/thali/NextGeneration/utils/pouchDBGenerator.js#L4)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: I'm curious, why did you change from js-extend to object-assign?
</details>
NB: Curious didn't meant the decision was wrong. I was just curious. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/795#-:-KOC_1n9B02g34RVWZbb:1417088721)*

**Comment by andrew-aladev** [comment]
`Object.assign` is available in ES6. I was using it later with babel. It is a habit.

**Pull request merged**
