### PR TITLE
Request and Check Permissions in Android #412

### PR DESCRIPTION
**Pull request by juhanak**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/515)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a63240e)

**Comment by ThaliTester** [comment]
Test (Fail) 58416448 build is completed (a63240e)

See https://github.com/ThaliTester/TestResults/tree/58416448a63240e_Request_and_Check_Permissions_in_Android__412_juhanak/ for the logs

**Comment by yaronyg** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 58 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mdlQLcvmaiJH0zWqE:-K9mdlQLcvmaiJH0zWqF:574042820) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L58)):*
Isn't your init code already here? :)

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 64 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mlz3RmP6FCdXY3amH:-K9mlz3Sh9sZ1cHjfCXs:215537892) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L64)):*
These params are wrong. There is no args param.

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 80 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mgxtwUPNSw68iG7Zl:-K9mgxtwUPNSw68iG7Zm:-269891306) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L80)):*
What happens if the data isn't a string?

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 81 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mmPA7Pg-2aL4o_YCE:-K9mmPA88grF88rmKGbI:2103611964) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L81)):*
Can't we make this simpler by just hard coding what permission we are asking for? Let's not be general when we don't need to be. The more restricted we are the less code we write, the fewer tests we write and the fewer bugs we have to fix. So I would hardcode this to ask for course location and that is it.

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 95 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mmhrXrekGl6-B3JEV:-K9mmhrXrekGl6-B3JEW:1174495411) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L95)):*
You use this method exactly once and it is tiny. I would consider just inlining it.

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 122 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mnanXwxZs8YOKSA8q:-K9mnanXwxZs8YOKSA8r:472436207) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L122)):*
Shouldn't this be marked @override?

---

*[www/android/thaliPermissions.js, line 40 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mnrgwH-66jJTbHJdE:-K9mnrgwH-66jJTbHJdF:-678971620) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/www/android/thaliPermissions.js#L40)):*
Again I would just ignore this at this level. Simplify! This extension should ask for exactly one and only one permission. If we eventually need more we can write code to do it. But simplicity is our friend. Less is more.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5af892a)

**Comment by juhanak** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 58 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mdlQLcvmaiJH0zWqE:-K9zxcI-eCzr81EyHasy:836238913) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L58)):*
Actually the whole function can be removed. I'll do that. 

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 64 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mlz3RmP6FCdXY3amH:-K9zz4wGrHlabV8iIEMW:814360301) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L64)):*
Ok. I'll fix that.

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 80 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mgxtwUPNSw68iG7Zl:-KA-Bnm-nSdM7VW0adl3:1749849629) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L80)):*
Fixed. Removed getString call and hard coded permission request. 

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 81 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mmPA7Pg-2aL4o_YCE:-KA-Bl9LdOhUsUhXq35p:-1903949189) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L81)):*
Ok. Hard coded permission request. 

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 95 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mmhrXrekGl6-B3JEV:-KA-Bzpc1aD3EvUPnLAi:-160339328) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L95)):*
I'll combine this method with checkPermissionStatus function.

---

*[src/android/java/org/thaliproject/p2p/ThaliPermissions.java, line 122 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mnanXwxZs8YOKSA8q:-KA-CNIo2g0bA5KQ0JM_:1733779937) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/src/android/java/org/thaliproject/p2p/ThaliPermissions.java#L122)):*
yep, fixed

---

*[www/android/thaliPermissions.js, line 40 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-K9mnrgwH-66jJTbHJdE:-KA-4VHUoCRqLvSJVFq0:539433560) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a63240e293e7f20043008da009253bc1ad61270b/www/android/thaliPermissions.js#L40)):*
Ok. I'll simplify this. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515)*

**Comment by ThaliTester** [comment]
Test (Fail) 58416448 build is completed (5af892a)

See https://github.com/ThaliTester/TestResults/tree/584164485af892a_Request_and_Check_Permissions_in_Android__412_juhanak/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (059acd4)

**Comment by ThaliTester** [comment]
Test (Fail) 58416448 build is completed (059acd4)

See https://github.com/ThaliTester/TestResults/tree/58416448059acd4_Request_and_Check_Permissions_in_Android__412_juhanak/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (134b800)

**Comment by ThaliTester** [comment]
Test (Fail) 58416448 build is completed (134b800)

See https://github.com/ThaliTester/TestResults/tree/58416448134b800_Request_and_Check_Permissions_in_Android__412_juhanak/ for the logs

**Comment by yaronyg** [comment]
:shipit: 

---

Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/515#-:-KA1Z7gjoA2ZabdC-SZA:1148172450)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9c56086)

**Comment by ThaliTester** [comment]
Test (Success) 58416448 build is completed (9c56086)

See https://github.com/ThaliTester/TestResults/tree/584164489c56086_Request_and_Check_Permissions_in_Android__412_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 584164489c56086(9c56086) has failed

See https://github.com/ThaliTester/TestResults/tree/584164489c56086_Request_and_Check_Permissions_in_Android__412_juhanak/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (66d9c0e)

**Comment by ThaliTester** [comment]
Test (Success) 58416448 build is completed (66d9c0e)

See https://github.com/ThaliTester/TestResults/tree/5841644866d9c0e_Request_and_Check_Permissions_in_Android__412_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 5841644866d9c0e(66d9c0e) has failed

See https://github.com/ThaliTester/TestResults/tree/5841644866d9c0e_Request_and_Check_Permissions_in_Android__412_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
:shipit:

**Pull request merged**
