### PR TITLE
Adds a typedef for peerAvailabilityChanged event's object

### PR DESCRIPTION
**Pull request by juhanak**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/650)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7ae73fc)

**Comment by ThaliTester** [comment]
Test (Success) 63525393 build is completed (7ae73fc)

See https://github.com/ThaliTester/TestResults/tree/635253937ae73fc_Adds_a_typedef_for_peerAvailabilityChanged_event_s_object_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 635253937ae73fc(7ae73fc) has failed

See https://github.com/ThaliTester/TestResults/tree/635253937ae73fc_Adds_a_typedef_for_peerAvailabilityChanged_event_s_object_juhanak/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/650)*

**Pull request merged**
