### PR TITLE
Story 03 yarong 249

### PR DESCRIPTION
**Pull request by yaronyg**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/333)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cae1769)

**Comment by yaronyg** [comment]
@vjrantal This is the proposal for the wifi based mock of the native layer. Please review when you have time. Thanks!

**Comment by ThaliTester** [comment]
Test (Success) 50907297 build is completed (cae1769)

See https://github.com/ThaliTester/TestResults/tree/50907297cae1769_Story_03_yarong_249_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 50907297cae1769(cae1769) has failed

See https://github.com/ThaliTester/TestResults/tree/50907297cae1769_Story_03_yarong_249_yaronyg/ for the fail logs

**Pull request merged**
