### PR TITLE
Cleanup and linting

### PR DESCRIPTION
**Pull request by yaronyg**
The only 'functional' change is that I hooked up logging in Node-SSDP and set it to 'silly'.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1635)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (77f4746)

**Comment by ThaliTester** [comment]
Test 97816899 (77f4746) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5f39c24)

**Comment by ThaliTester** [comment]
Test (Success) 97816899 build is completed (77f4746)

See https://github.com/ThaliTester/TestResults/tree/9781689977f4746_Cleanup_and_linting_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 97816899 (5f39c24) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 97816899 build is completed (5f39c24)

See https://github.com/ThaliTester/TestResults/tree/978168995f39c24_Cleanup_and_linting_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 9781689977f4746(77f4746) has failed

See https://github.com/ThaliTester/TestResults/tree/9781689977f4746_Cleanup_and_linting_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
The second build failed because of a problem downloading the JX tarball. But since the second checkin only updated a README and the first passed I think we are o.k.

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 100 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1635#-KYx8qhj7FpcmpUNW4E-:-KYx8qhj7FpcmpUNW4E0:b-4356mz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5f39c2420cbabc22fd6f4a7ac1570ee5115c02ad/thali/NextGeneration/thaliWifiInfrastructure.js#L100)):*
> ```JavaScript
> 
>   var clientOptions = {
>     thaliLogger: require('../ThaliLogger')('nodeSSDPClientLogger')
> ```

NB: 'Logger' in 'nodeSSDPClientLogger' seems a bit redundant here 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1635#-:-KYx9dxYdxNucbITs-G_:bnfp4nl)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1635#-:-KYyEdnb_cwKNT80HgPO:bnfp4nl)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 100 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1635#-KYx8qhj7FpcmpUNW4E-:-KYyUX1O8X2j0VoCmPuh:b-wrtazy) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5f39c2420cbabc22fd6f4a7ac1570ee5115c02ad/thali/NextGeneration/thaliWifiInfrastructure.js#L100)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

NB: 'Logger' in 'nodeSSDPClientLogger' seems a bit redundant here 
</blockquote></details>

It's actually not because there is a completely separate nodeSSDPServerLogger as well. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1635)*

**Pull request merged**
