### PR TITLE
#419 Added PouchDB database size checkpoints

### PR DESCRIPTION
**Pull request by artemjackson**
This is #876 re-submitted to `vNext_yarong_417_812`

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1109)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (7abfc13)

**Comment by ThaliTester** [comment]
Test (Success) 86172525 build is completed (7abfc13)

See https://github.com/ThaliTester/TestResults/tree/861725257abfc13__419_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 861725257abfc13(7abfc13) has failed

See https://github.com/ThaliTester/TestResults/tree/861725257abfc13__419_Added_PouchDB_database_size_checkpoints_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
Alas there are two test related blockers.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 22 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1109#-KSJ9BTGYWpQY9C-nYOZ:-KSJ9BTGYWpQY9C-nYO_:bshh6z5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7abfc13f9e79a45c6048c3d27b5e38a4ed084f6f/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L22)):*
> ```JavaScript
> };
> var DEFAULT_DELAY = 200;
> var CALCULATING_DEALY = 100;
> ```

NB: /DEALY/DELAY

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 56 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1109#-KSJ9RccX7gb-A236qME:-KSJ9Rcdk0GGefKS32CK:b-95xoq8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7abfc13f9e79a45c6048c3d27b5e38a4ed084f6f/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L56)):*
> ```JavaScript
>         t.ok(spy.calledOnce, 'checkpointReached handler should be called once. Called ' + spy.callCount + ' time(s)');
>         t.end();
>       }, DEFAULT_DELAY + CALCULATING_DEALY);
> ```

This is not reliable because all sorts of things can delay writes on devices as well as reads. So instead what we need to do, I believe, is introduce a poll. We need to check the spy ever X milliseconds for a call to the spy and after Y milliseconds if we haven't received the call then we say the test failed.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 85 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1109#-KSJD-9vS0-tiIsYOs6i:-KSJD-9wdesa8beSfuj5:b-t1sprr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7abfc13f9e79a45c6048c3d27b5e38a4ed084f6f/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L85)):*
> ```JavaScript
> 
> test('Call of onCheckpointReached handler on multiple db changes' +
> 'that are in the checkpoints plugin delay interval', function (t) {
> ```

We should also probably have a test that shows that we will fire the size event again after the delay is over. E.g. make 2 changes, show we get one size event, wait, make another change and so that the size event fires again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1109#-:-KSJDG0xFg61DN4DG43_:bs4xqk)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (1533884)

**Comment by artemjackson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 56 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1109#-KSJ9RccX7gb-A236qME:-KSLxLpfv1806BOhn1dX:bfms62m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7abfc13f9e79a45c6048c3d27b5e38a4ed084f6f/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L56)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> This is not reliable because all sorts of things can delay writes on devices as well as reads. So instead what we need to do, I believe, is introduce a poll. We need to check the spy ever X milliseconds for a call to the spy and after Y milliseconds if we haven't received the call then we say the test failed.
</details>
I improved the tests so they don't depend on system I/O operations time.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 85 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1109#-KSJD-9vS0-tiIsYOs6i:-KSLxueQVWVEiGiTHC7D:b3h3l3z) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7abfc13f9e79a45c6048c3d27b5e38a4ed084f6f/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L85)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> We should also probably have a test that shows that we will fire the size event again after the delay is over. E.g. make 2 changes, show we get one size event, wait, make another change and so that the size event fires again.
</details>
I added such test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1109)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 9. task. (3aa3a32)

**Comment by ThaliTester** [comment]
Test (Fail) 86172525 build is completed (1533884)

See https://github.com/ThaliTester/TestResults/tree/861725251533884__419_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86172525 build is completed (3aa3a32)

See https://github.com/ThaliTester/TestResults/tree/861725253aa3a32__419_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 861725253aa3a32(3aa3a32) has failed

See https://github.com/ThaliTester/TestResults/tree/861725253aa3a32__419_Added_PouchDB_database_size_checkpoints_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1109#-:-KSNuemAa6ANbGPKVpSa:bnfp4nl)*

**Pull request merged**
