### PR TITLE
MPCF TCP/IP binding

### PR DESCRIPTION
**Pull request by dersim-davaod**
This is updated version of #1199.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1286)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b87f795)

**Comment by ThaliTester** [comment]
Test (Fail) 88838102 build is completed (b87f795)

See https://github.com/ThaliTester/TestResults/tree/88838102b87f795_MPCF_TCP/IP_binding_dersim-davaod/ for the logs

**Comment by dersim-davaod** [comment]
For now we have following high-level issues:
1. Need to fix interface with `AppContext.swift`. Also need to make `ThaliCore` more independent from `Thali_CordovaPlugin`.
2. Nice to have improved tests in `VirtualSocket.swift`, `VirtualSocketBuilder.swift`, `Relay.swift`. (detailed list will be provided after discussing with @baydet)
There are two options. The first one is we can have many complex mocks to test our objects. The second one is we can open implementation details (which are private now). Both are not very good, but we should test our code. So I think we should choose the first one and test our code via its public/internal API.
3. Also we need to discuss some implementations details with js folks.
4. Need to fix issues mentioned in unresolved comments in #1199 (detailed list will be provided after updating and discussing issues with @baydet)

**Comment by baydet** [comment]
Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/Core/Dictionary+KeyForValue.swift, line 13 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-KTsPoXLlpAghWT80K49:-KTsPoXLlpAghWT80K4A:b-jmzqku) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b87f79588f38a77ed903073f49c37e9fdfb3724b/lib/ios/ThaliCore/ThaliCore/Core/Dictionary+KeyForValue.swift#L13)):*
> ```Swift
> extension Dictionary where Value: Equatable {
> 
>     func key(for value: Value) -> Key? {
> ```

NB

I always afraid of code like that. If we use it maybe Dictionary wasn't right choice as data structure? 

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPClient.swift, line 14 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-KTs9xj9gz1rTTq8HucK:-KTs9xj9gz1rTTq8HucL:b-1d8e54) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b87f79588f38a77ed903073f49c37e9fdfb3724b/lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPClient.swift#L14)):*
> ```Swift
>     // MARK: - Internal state
>     internal var localPort: UInt16 {
> //        return socket.localPort
> ```

NB 
remove commented code

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 56 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-KTsMspDsa-_dpmp--L5:-KTsMspDsa-_dpmp--L6:b-x4wgx1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b87f79588f38a77ed903073f49c37e9fdfb3724b/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L56)):*
> ```Swift
>                 self.outputStream.open()
> 
>                 NSRunLoop.currentRunLoop().runUntilDate(NSDate.distantFuture())
> ```

I'm a little bit afraid of this code. How can you have guarantee that underlying thread and runLoop attached to this thread will be alive as much as we want? What if at some point in future GCD will decide to sleep selected nsthread? We cannot control its state with GCD at all.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 78 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-KTsg6IcC91ckJ_FT_1T:-KTsg6IcC91ckJ_FT_1U:bgd1qes) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b87f79588f38a77ed903073f49c37e9fdfb3724b/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L78)):*
> ```Swift
> 
>         if !outputStream.hasSpaceAvailable {
>             pendingDataToWrite?.appendData(data)
> ```

Does it mean that we can have a situation when we could try to write some big piece of data? (more than 4Kb) It could lead us to errors when NSInputStream on other end just silently stops receive data. Did you have on these guides

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Streams/Articles/WritingOutputStreams.html#//apple_ref/doc/uid/20002274-BAJCABBC
```There is no firm guideline on how many bytes to write at one time. Although it may be possible to write all the data to the stream in one event, this depends on external factors, such as the behavior of the kernel and device and socket characteristics. The best approach is to use some reasonable buffer size, such as 512 bytes, one kilobyte (as in the example above), or a page size (four kilobytes).```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (571b7ae)

**Comment by ThaliTester** [comment]
Test (Success) 88838102 build is completed (571b7ae)

See https://github.com/ThaliTester/TestResults/tree/88838102571b7ae_MPCF_TCP/IP_binding_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (43c6d6d)

**Comment by dersim-davaod** [comment]
Review status: 39 of 48 files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPClient.swift, line 14 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-KTs9xj9gz1rTTq8HucK:-KTt7_JTIZ5f6amt5jKZ:b-4lafzg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b87f79588f38a77ed903073f49c37e9fdfb3724b/lib/ios/ThaliCore/ThaliCore/SocketConnection/TCPClient.swift#L14)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> NB 
> remove commented code
</details>
`localPort` property is unnecessary code for now. I've removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286)*

**Comment by ThaliTester** [comment]
Test 88838102571b7ae(571b7ae) has failed

See https://github.com/ThaliTester/TestResults/tree/88838102571b7ae_MPCF_TCP/IP_binding_dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 88838102 build is completed (43c6d6d)

See https://github.com/ThaliTester/TestResults/tree/8883810243c6d6d_MPCF_TCP/IP_binding_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 8883810243c6d6d(43c6d6d) has failed

See https://github.com/ThaliTester/TestResults/tree/8883810243c6d6d_MPCF_TCP/IP_binding_dersim-davaod/ for the fail logs

**Comment by baydet** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 56 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-KTsMspDsa-_dpmp--L5:-KTxxvaQTeiqiFVB6mvF:bmmt5gu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b87f79588f38a77ed903073f49c37e9fdfb3724b/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L56)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> I'm a little bit afraid of this code. How can you have guarantee that underlying thread and runLoop attached to this thread will be alive as much as we want? What if at some point in future GCD will decide to sleep selected nsthread? We cannot control its state with GCD at all.
</details>
moved to #1300 

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 78 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-KTsg6IcC91ckJ_FT_1T:-KTxyB13LGyXvv8un9Af:bmmspbl) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b87f79588f38a77ed903073f49c37e9fdfb3724b/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L78)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> Does it mean that we can have a situation when we could try to write some big piece of data? (more than 4Kb) It could lead us to errors when NSInputStream on other end just silently stops receive data. Did you have on these guides
> 
> https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Streams/Articles/WritingOutputStreams.html#//apple_ref/doc/uid/20002274-BAJCABBC
> ```There is no firm guideline on how many bytes to write at one time. Although it may be possible to write all the data to the stream in one event, this depends on external factors, such as the behavior of the kernel and device and socket characteristics. The best approach is to use some reasonable buffer size, such as 512 bytes, one kilobyte (as in the example above), or a page size (four kilobytes).```
> 
> 
</details>
moved to #1297 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-:-KTxyJ9WOgpsNrQmcsld:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (10757f6)

**Comment by ThaliTester** [comment]
Test (Fail) 88838102 build is completed (10757f6)

See https://github.com/ThaliTester/TestResults/tree/8883810210757f6_MPCF_TCP/IP_binding_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3d83748)

**Comment by ThaliTester** [comment]
Test (Fail) 88838102 build is completed (3d83748)

See https://github.com/ThaliTester/TestResults/tree/888381023d83748_MPCF_TCP/IP_binding_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5b93203)

**Comment by ThaliTester** [comment]
Test (Success) 88838102 build is completed (5b93203)

See https://github.com/ThaliTester/TestResults/tree/888381025b93203_MPCF_TCP/IP_binding_dersim-davaod/ for the logs

**Comment by dersim-davaod** [comment]
Review status: 47 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCore/Core/Dictionary+KeyForValue.swift, line 13 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286#-KTsPoXLlpAghWT80K49:-KTyKcQ-AWEaTcbo9olN:bmmspcg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b87f79588f38a77ed903073f49c37e9fdfb3724b/lib/ios/ThaliCore/ThaliCore/Core/Dictionary+KeyForValue.swift#L13)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> NB
> 
> I always afraid of code like that. If we use it maybe Dictionary wasn't right choice as data structure? 
</details>
moved to #1298 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286)*

**Comment by baydet** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1286)*

**Comment by ThaliTester** [comment]
Test 888381025b93203(5b93203) has failed

See https://github.com/ThaliTester/TestResults/tree/888381025b93203_MPCF_TCP/IP_binding_dersim-davaod/ for the fail logs

**Pull request merged**
