### PR TITLE
Fixed desktop platform name and commented replacing ios header

### LINKED ISSUE #1144: We should force runTests to use desktop instead of platform name if isMobile is false

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1144

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1147)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8390c5f)

**Comment by ThaliTester** [comment]
Test (Success) 86542121 build is completed (8390c5f)

See https://github.com/ThaliTester/TestResults/tree/865421218390c5f_Fixed_desktop_platform_name_and_commented_replacing_ios_header_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 865421218390c5f(8390c5f) has failed

See https://github.com/ThaliTester/TestResults/tree/865421218390c5f_Fixed_desktop_platform_name_and_commented_replacing_ios_header_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1147#-:-KSN0S-nTCuG_HV4_pXH:bnfp4nl)*

**Pull request merged**
