### PR TITLE
Fixed stopping default pool

### LINKED ISSUE #952: Something is very screwy with thaliPeerPoolManager or maybe thaliReplicationPeerAction
See https://raw.githubusercontent.com/ThaliTester/TestResults/826421844c75f89_The_replacement_for_vNext_yarong_417_1__vNext_yarong_780___vNext_yarong_812_yaronyg/build.md for the output of my latest build on vNext_yarong_417_812.

Do a search for "****TEST_LOGGER:[PROCESS_ON_EXIT_FAILED]****"

We have an uncaught exception from thaliPeerPoolDefault on line 78. This exception was thrown while running 'Coordinated pull replication from notification test'. And from looking at the log it looks like one of the two nodes in the coordinator test successfully completed the test but at least one of the others threw.

So looking at the logs it looks like everybody starts advertising and the first thing to go wrong is that we get a document update conflict. That really shouldn't be possible. All the IDs are unique. But I'm going to focus for the moment on the actual unhandled exception.

There is a race condition possible here where we call thaliPeerPoolDefault.stop() and then thaliPullReplicationFromNotification is still going and tries to enqueue something after we stopped and that would be 'bad'. Right now our exit function stops the peer pool but it doesn't stop thaliPullReplicationFromNotification. That doesn't happen until teardown. So we'll just do it in exit so we can stop that particular exception.

But now I'm getting hangs when I try to run the coordinated tests, with or without the change I made to call thaliPullReplicationFromNotification.stop. I just had tests hang on '#ThaliPeerPoolInterface - make sure that stop removes all actions" I actually got an undefined error. But I don't know where or from whom.

Then I got an error from testThaliReplicationPeerAction."Do something and make sure we time out". I get a bunch of document conflicts including a replication resume and got paused with - log messages and an undefined!

Something is seriously wrong here with thaliPeerPoolInterface and/or the replication peer pool action.

Here is the log:
# 186. Do something and make sure we time out

# 186. Do something and make sure we time out

# 186. Do something and make sure we time out

{ [conflict: Document update conflict]
  status: 409,
  name: 'conflict',
  message: 'Document update conflict',
  error: true }

{ [conflict: Document update conflict]
  status: 409,
  name: 'conflict',
  message: 'Document update conflict',
  error: true }

{ [conflict: Document update conflict]
  status: 409,
  name: 'conflict',
  message: 'Document update conflict',
  error: true }

undefined
2016-08-30T00:22:24.479Z - info: Socket to device 7f71e235-4637-4acd-9e22-e38aafc5ce53 disconnected: transport close

DEBUG thaliReplicationPeerAction: Replication resumed

DEBUG thaliReplicationPeerAction: Replication resumed

DEBUG thaliReplicationPeerAction: Got paused with -  

ok 792 should be equal

DEBUG thaliReplicationPeerAction: Got paused with -  

ok 795 should be equal

ok 793 action should be killed

ok 794 Error should be timed out

# teardown

ok 796 action should be killed

ok 797 Error should be timed out

# teardown

Note that there are just two teardowns.

My guess is that the undefined is the key to all of this.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #952

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/954)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (e1001da)

**Comment by ThaliTester** [comment]
Test (Success) 83243049 build is completed (e1001da)

See https://github.com/ThaliTester/TestResults/tree/83243049e1001da_Fixed_stopping_default_pool_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 83243049e1001da(e1001da) has failed

See https://github.com/ThaliTester/TestResults/tree/83243049e1001da_Fixed_stopping_default_pool_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/954#-:-KQS5kqeFVOTaepPVbK3:bnfp4nl)*

**Pull request merged**
