### PR TITLE
Do not merge, CI test

### LINKED ISSUE #1006: "Coordinated replication action test" in testThaliReplicationPeerActionCoordinated.js does the  work even after it's finished

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1006

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1032)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bd1c5d7)

**Comment by ThaliTester** [comment]
Test (Fail) 85067679 build is completed (bd1c5d7)

See https://github.com/ThaliTester/TestResults/tree/85067679bd1c5d7_Do_not_merge__CI_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (65eb647)

**Comment by ThaliTester** [comment]
Test (Success) 85067679 build is completed (65eb647)

See https://github.com/ThaliTester/TestResults/tree/8506767965eb647_Do_not_merge__CI_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 8506767965eb647(65eb647) has failed

See https://github.com/ThaliTester/TestResults/tree/8506767965eb647_Do_not_merge__CI_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (198230b)

**Comment by ThaliTester** [comment]
Test (Success) 85067679 build is completed (198230b)

See https://github.com/ThaliTester/TestResults/tree/85067679198230b_Do_not_merge__CI_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 85067679198230b(198230b) has failed

See https://github.com/ThaliTester/TestResults/tree/85067679198230b_Do_not_merge__CI_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b83ffc4)

**Comment by ThaliTester** [comment]
Test (Success) 85067679 build is completed (b83ffc4)

See https://github.com/ThaliTester/TestResults/tree/85067679b83ffc4_Do_not_merge__CI_test_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
Done. I will provide a new good pull request.

**Comment by ThaliTester** [comment]
Test 85067679b83ffc4(b83ffc4) has failed

See https://github.com/ThaliTester/TestResults/tree/85067679b83ffc4_Do_not_merge__CI_test_andrew-aladev/ for the fail logs

**Pull request closed without merging**
