### PR TITLE
Fix running tests when `userConfig` isn't given.

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/436)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c0db81b)

**Comment by ThaliTester** [comment]
Test (Success) 55864105 build is completed (c0db81b)

See https://github.com/ThaliTester/TestResults/tree/55864105c0db81b_Fix_running_tests_when_`userConfig`_isn_t_given__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 55864105c0db81b(c0db81b) has failed

See https://github.com/ThaliTester/TestResults/tree/55864105c0db81b_Fix_running_tests_when_`userConfig`_isn_t_given__vjrantal/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/436)*

**Pull request merged**
