### PR TITLE
#419 Added PouchDB database size checkpoints

### PR DESCRIPTION
**Pull request by artemjackson**
Implemented notification when database size reached checkpoint.
Also tests are added.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/876)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (cfb0966)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (19cba29)

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (cfb0966)

See https://github.com/ThaliTester/TestResults/tree/81351277cfb0966__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (19cba29)

See https://github.com/ThaliTester/TestResults/tree/8135127719cba29__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by yaronyg** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 1 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPF24VzFu0h0dHTquyw:-KPF24W-shHoRUDmtRf9:bcl0zj8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L1)):*
> ```JavaScript
> 'use strict';
> ```

I'm surprised to see this code given that I didn't get responses to my questions in https://github.com/thaliproject/Thali_CordovaPlugin/issues/319#issuecomment-239486533

Can you please first go resolve those questions and then deal with the code?

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 38 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPF1HrVzZYw3BUFPCgf:-KPF1HrVzZYw3BUFPCgg:bwf7xfy) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L38)):*
> ```JavaScript
> };
> 
> test('onCheckpointReached callback calling', function (t) {
> ```

Shouldn't we also have a test that once we have fired the even if the database shrinks and then we increase its size again that we will get a call? In other words if we fire at 100 once we shouldn't keep firing on every future change. That just isn't useful. We should stop firing after we have fired once and not fire again until we get below the threshold. In other words if we fire at 100 then we should fire once and not fire again until the DB has shrunk below 100.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 3 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPExAwVprTxaebav4yf:-KPExAwVprTxaebav4yg:b-lgeg7r) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L3)):*
> ```JavaScript
> 'use strict';
> 
> module.exports = {
> ```

NB: Just to keep style consistent can you please define this as module.exports.onCheckpointReached = function (handler) ...?

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 5 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPF2KVJI7ORH9uN50FS:-KPF2KVJI7ORH9uN50FT:bedvkmy) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L5)):*
> ```JavaScript
> module.exports = {
>   onCheckpointReached: function (handler) {
>     checkpoints = this.__opts.checkpoints || [];
> ```

In order to simplify the code and the tests I'm fine with having just a single checkpoint instead of an array of them. The less we do the more likely we are to ship.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 17 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPExN4pe3KrK1UoeeDz:-KPExN4pe3KrK1UoeeE-:bpgrb1m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L17)):*
> ```JavaScript
> var addEventHandlerForCheckpointReached = function (handler) {
>   if (!events) {
>     initializeDBEvents.bind(this)();
> ```

I'm surprised this passed linting. You should have gotten a function used before being defined error.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 42 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPEyxQW7LQ44RYCJaYh:-KPEyxQW7LQ44RYCJaYi:b-kdh31a) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L42)):*
> ```JavaScript
>       })
>       .catch(function (error) {
>         console.log('Error while fetching db info: ', error);
> ```

Logging is lovely but don't we have to somehow communicate this data outside of ourselves? This actually seems like a reasonable use of throw or perhaps hooking into PouchDB's error event handler?

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 46 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPF1iIWSUJIM2i2Bv7H:-KPF1iIWSUJIM2i2Bv7I:b-y94lv6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L46)):*
> ```JavaScript
>   }
> 
>   events.on('change', checkDBSize);
> ```

I'm confused. In my review of the spec (e.g. [here](https://github.com/thaliproject/Thali_CordovaPlugin/issues/319#issuecomment-239486533)) I explicitly said to not do this. That having to run a bunch of lstats on every change could kill us from a perf perspective. Did you do testing to show this is wrong? If not why didn't you adopt something like I described in my comments? Please see those comments.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 65 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPEygEDe_usS9kGsHAG:-KPEygEDe_usS9kGsHAH:bjuz4wv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L65)):*
> ```JavaScript
>   }
> 
>   this.installSizeWrapper();
> ```

This is a promise isn't it? Don't we need to have a then and a catch and then set sizeWrapperInitialized to true only in the then? Also how do we communicate an error outside of ourselves?  My guess is that we need to have a reject call with no handler and expect whomever called us to deal with it but I could be wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 1 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPF24VzFu0h0dHTquyw:-KPHYzO2H399VXUeNed-:b-uegjlb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L1)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> I'm surprised to see this code given that I didn't get responses to my questions in https://github.com/thaliproject/Thali_CordovaPlugin/issues/319#issuecomment-239486533
> 
> Can you please first go resolve those questions and then deal with the code?
</details>
I'm sorry, I've wrote [answers](https://github.com/thaliproject/Thali_CordovaPlugin/issues/319#issuecomment-240039109) for questions you provided in #319.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 38 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPF1HrVzZYw3BUFPCgf:-KPHhNEy4c9svI8eVjgp:b-koqryq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L38)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Shouldn't we also have a test that once we have fired the even if the database shrinks and then we increase its size again that we will get a call? In other words if we fire at 100 once we shouldn't keep firing on every future change. That just isn't useful. We should stop firing after we have fired once and not fire again until we get below the threshold. In other words if we fire at 100 then we should fire once and not fire again until the DB has shrunk below 100.
</details>
It's reasonable, I'm going to implement it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 3 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPExAwVprTxaebav4yf:-KPHiRwN9wikrIE3IhRb:b-79izkh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L3)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Just to keep style consistent can you please define this as module.exports.onCheckpointReached = function (handler) ...?
</details>
It's exported as a [pouchdb plugin](https://pouchdb.com/api.html#plugins) so one can simply require that like [there](https://pouchdb.com/api.html#plugins)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 3 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPExAwVprTxaebav4yf:-KPHlPfDJuqL2WSs9b80:b-ebpvna) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L3)):*
<details><summary><i>Previously, artemjackson (Artem Jackson) wrote…</i></summary>
> It's exported as a [pouchdb plugin](https://pouchdb.com/api.html#plugins) so one can simply require that like [there](https://pouchdb.com/api.html#plugins)
</details>
But I can define it as `module.exports.onCheckpointReached = ...` for keeping code style

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 65 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPEygEDe_usS9kGsHAG:-KPHno24xqBYmhrlWRiM:b-hp604n) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L65)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> This is a promise isn't it? Don't we need to have a then and a catch and then set sizeWrapperInitialized to true only in the then? Also how do we communicate an error outside of ourselves?  My guess is that we need to have a reject call with no handler and expect whomever called us to deal with it but I could be wrong.
</details>
No, it's not a promise. `this.installSizeWrapper()` returns `undefined`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 65 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPEygEDe_usS9kGsHAG:-KPHoFjnXKNih689Pz7h:b-d78bso) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L65)):*
<details><summary><i>Previously, artemjackson (Artem Jackson) wrote…</i></summary>
> No, it's not a promise. `this.installSizeWrapper()` returns `undefined`
</details>
For more details see [here](https://github.com/pouchdb/pouchdb-size/blob/master/index.js#L24)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 17 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPExN4pe3KrK1UoeeDz:-KPHwvzY6Q-vwo28vmZS:bdvegsz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L17)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> I'm surprised this passed linting. You should have gotten a function used before being defined error.
</details>
Sorry, would you mind explaining this sentence to me. I'm afraid I don't seem to get the meaning

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (81cd762)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (db0d2b7)

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (81cd762)

See https://github.com/ThaliTester/TestResults/tree/8135127781cd762__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (b171700)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (c040288)

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (db0d2b7)

See https://github.com/ThaliTester/TestResults/tree/81351277db0d2b7__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (b171700)

See https://github.com/ThaliTester/TestResults/tree/81351277b171700__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (c040288)

See https://github.com/ThaliTester/TestResults/tree/81351277c040288__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by artemjackson** [comment]
@yaronyg 
Build fails and build logs don't provide any useful information.
Are there problems with CI? This PR should not affect on a build process.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9ec8231)

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (9ec8231)

See https://github.com/ThaliTester/TestResults/tree/813512779ec8231__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5226598)

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (5226598)

See https://github.com/ThaliTester/TestResults/tree/813512775226598__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (32cb2b8)

**Comment by ThaliTester** [comment]
Test (Success) 81351277 build is completed (32cb2b8)

See https://github.com/ThaliTester/TestResults/tree/8135127732cb2b8__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8135127732cb2b8(32cb2b8) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8135127732cb2b8__319_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (b4947e7)

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (b4947e7)

See https://github.com/ThaliTester/TestResults/tree/81351277b4947e7__419_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by yaronyg** [comment]
This has to be tested on actual devices (both iOS and Android) to make sure that lstat will work right on both platforms.

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 17 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogRTTZWvUpq-WD2MX:-KPogRTTZWvUpq-WD2MY:bvtdmjp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L17)):*
> ```JavaScript
> // This is especially required for tape.coordinated.
> var db;
> var dbName = 'pouchdb-uuid:' + Math.random();
> ```

There actually is a function to do this in utilities. I think it also includes code to clean up after itself when the tests are done.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 56 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogt7uOOH16qGzPQeM:-KPogt7v8bUZhhCyt-nh:bspp6f4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L56)):*
> ```JavaScript
>         t.ok(spy.calledOnce, 'checkpointReached handler should be called once. Called ' + spy.callCount + ' time(s)');
>         t.end();
>       }, DEFAULT_DELAY + CALCULATING_DEALY);
> ```

NB:DEALY/DELAY

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 111 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPohaLgV_Ui1rOCmkgS:-KPohaLgV_Ui1rOCmkgT:bynjvtx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L111)):*
> ```JavaScript
> 
> //  TODO Investigate how to force PouchDB to shrink database size
> //  Atfer that test can be enabled
> ```

Did you experiment to see how long you have to wait after you call compact before the DB is shrunk? Level DB is a generational DB with an expensive cleanup process. So I suspect once you call compact it will take some time before the actual clean up is run.

The other trick if that doesn't work is to take advantage of how change actually works in PouchDB. You can put a big file into the directory where the DB is. Then you can force a change. The lstat will pick up your file even though it's not in the DB (it just blindly checks the directory) and will trigger the checkpoint alert. Then delete the file and add another doc (to trigger a change) and now lstat should show the DB is suddenly smaller.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 17 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPExN4pe3KrK1UoeeDz:-KPod8MLM9_mr3kee82j:b-6amu0i) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19cba29a7bab5ed1f099676f8800f7f5809a7388/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L17)):*
<details><summary><i>Previously, artemjackson (Artem Jackson) wrote…</i></summary>
> Sorry, would you mind explaining this sentence to me. I'm afraid I don't seem to get the meaning
</details>
We use a JS linter (JSCS and JSHINT) and normally they flag situations where a function is called (in this case initializeDBEvents) before it is defined. This isn't illegal in JS but it's not considered good style as generally you want to read the definition of a function before you see it used.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 63 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogAyPQ_qRKiMEzdL-:-KPogAyPQ_qRKiMEzdL0:b-s05j5m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L63)):*
> ```JavaScript
>               // It might be better for performance
>               // to execute handlers asynchronously
>               executeAsync(handler)(checkpoint);
> ```

There is an edge case I'm worried about here. Imagine that we are very close to a checkpoint size. We cross it and disable that checkpoint. The system then immediately cleans things up except we are in the middle of a replication so now more data is coming in which will again trigger the checkpoint which then causes us to alert and disable except then we get more data and so on. This would cause a constant stream of alerts. Don't we have to make sure we never send alerts across all checkpoints more often than the configured delay? This has to apply to checkpoints that had been previously disabled too.

So I wonder if we can't just shove these events into executeOnce() and call it a day? Wouldn't that sole the problem?

(Of course given how often compact runs perhaps this is a non issue)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js, line 56 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogt7uOOH16qGzPQeM:-KPqOMWh86fLdiGqcvl5:bpmztbu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/test/www/jxcore/bv_tests/testPouchDBCheckpointPlugin.js#L56)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB:DEALY/DELAY
</details>
Oh, a horrible typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 63 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogAyPQ_qRKiMEzdL-:-KPrStymENGlW2bT49Cb:b-dl0wu2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L63)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> There is an edge case I'm worried about here. Imagine that we are very close to a checkpoint size. We cross it and disable that checkpoint. The system then immediately cleans things up except we are in the middle of a replication so now more data is coming in which will again trigger the checkpoint which then causes us to alert and disable except then we get more data and so on. This would cause a constant stream of alerts. Don't we have to make sure we never send alerts across all checkpoints more often than the configured delay? This has to apply to checkpoints that had been previously disabled too.
> 
> So I wonder if we can't just shove these events into executeOnce() and call it a day? Wouldn't that sole the problem?
> 
> (Of course given how often compact runs perhaps this is a non issue)
</details>
If I understood you right this is what you need https://github.com/thaliproject/Thali_CordovaPlugin/pull/876/files#diff-bad34c170c42b91b542babde61cebe58R40
Isn't it?

`pouchdb-size` will not be called more than once per specified `delay`
Therefore checkpoint alert will not be send more than once per specified `delay` as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by yaronyg** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 63 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogAyPQ_qRKiMEzdL-:-KPsCDz8IPMQbd5vxpo5:beg7qtj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L63)):*
<details><summary><i>Previously, artemjackson (Artem Jackson) wrote…</i></summary>
> If I understood you right this is what you need https://github.com/thaliproject/Thali_CordovaPlugin/pull/876/files#diff-bad34c170c42b91b542babde61cebe58R40
> Isn't it?
> 
> `pouchdb-size` will not be called more than once per specified `delay`
> Therefore checkpoint alert will not be send more than once per specified `delay` as well
</details>
But I thought executeAsync overrides the logic in the line you pointed at and instead just runs after a set timeout once per executeAsync call?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 63 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogAyPQ_qRKiMEzdL-:-KPvhAU4AeZMmrJLkbq4:b7ns6so) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L63)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> But I thought executeAsync overrides the logic in the line you pointed at and instead just runs after a set timeout once per executeAsync call?
</details>
No, it doesn't. Let me explain.
At the [40th line](https://github.com/thaliproject/Thali_CordovaPlugin/pull/876/files#diff-bad34c170c42b91b542babde61cebe58R40)`executeOnce(checkDBSize.bind(this)` will call `pouchdb-size` once after specified `delay`. And after getting info from `pouchdb-size` all handlers that subscribed to checkpoint reached event will be executed asynchronously.

The main idea is that all handlers will be executed **after** specified delay. 
`executeAsync` is used in order not to block javascript thread by handlers execution.
It could be useful  when handler is doing some heavy work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by yaronyg** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 63 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogAyPQ_qRKiMEzdL-:-KPxicCSC81JzAB666AI:b-z9ro2u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L63)):*
<details><summary><i>Previously, artemjackson (Artem Jackson) wrote…</i></summary>
> No, it doesn't. Let me explain.
> At the [40th line](https://github.com/thaliproject/Thali_CordovaPlugin/pull/876/files#diff-bad34c170c42b91b542babde61cebe58R40)`executeOnce(checkDBSize.bind(this)` will call `pouchdb-size` once after specified `delay`. And after getting info from `pouchdb-size` all handlers that subscribed to checkpoint reached event will be executed asynchronously.
> 
> The main idea is that all handlers will be executed **after** specified delay. 
> `executeAsync` is used in order not to block javascript thread by handlers execution.
> It could be useful  when handler is doing some heavy work.
</details>
O.k. I see. So the point is that we get a checkpoint alert and rather than just running all the handlers at once serially instead we run them one by one asynchronously. But shouldn't you use setImmediate instead of setTimeout for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by artemjackson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js, line 63 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876#-KPogAyPQ_qRKiMEzdL-:-KQ03YvkNxlBgtuwB5c_:begbrjt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b4947e7cdf2fa6c9d46621344985527ee9f1669c/thali/NextGeneration/utils/pouchDBCheckpointsPlugin.js#L63)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> O.k. I see. So the point is that we get a checkpoint alert and rather than just running all the handlers at once serially instead we run them one by one asynchronously. But shouldn't you use setImmediate instead of setTimeout for this?
</details>
I've made some investigations and now I fully agree with you. I'll fix `setTimeout` to `setImmediate`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/876)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6cbb9f4)

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (6cbb9f4)

See https://github.com/ThaliTester/TestResults/tree/813512776cbb9f4__419_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3aaf572)

**Comment by ThaliTester** [comment]
Test (Fail) 81351277 build is completed (3aaf572)

See https://github.com/ThaliTester/TestResults/tree/813512773aaf572__419_Added_PouchDB_database_size_checkpoints_artemjackson/ for the logs

**Comment by yaronyg** [comment]
@artemjackson - Please point this at vNext_yarong_417_812, resolve the comments and let's get this checked in.

**Comment by artemjackson** [comment]
Closed in favour of #889

**Pull request closed without merging**
