### PR TITLE
Simplify and improve build process for iOS

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1839)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3313880)

**Comment by ThaliTester** [comment]
Test 111993869 (3313880) build started.

**Comment by ThaliTester** [comment]
Test (Success) 111993869 build is completed (3313880)

See https://github.com/ThaliTester/TestResults/tree/1119938693313880_Simplify_and_improve_build_process_for_iOS_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 1119938693313880(3313880) has failed

See https://github.com/ThaliTester/TestResults/tree/1119938693313880_Simplify_and_improve_build_process_for_iOS_dersim-davaod/ for the fail logs

**Comment by asuhodolov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1839)*

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1839#-:-Kfua5aw3gA6GRheMoVY:bg7igkv)*

**Comment by asuhodolov** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1839#-:-Kfvm5AwCpL_yF8t39xt:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1839#-:-Kfvs3bXL857k0RUr92C:bnfp4nl)*

**Pull request merged**
