### PR TITLE
#906 Choose Swift codestyle guide for ThaliCore

### PR DESCRIPTION
**Pull request by dersim-davaod**
Uploading changes in linter config.
Fixing current linter issues as well.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/965)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (13e13cf)

**Comment by ThaliTester** [comment]
Test (Success) 83444050 build is completed (13e13cf)

See https://github.com/ThaliTester/TestResults/tree/8344405013e13cf__906_Choose_Swift_codestyle_guide_for_ThaliCore_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 8344405013e13cf(13e13cf) has failed

See https://github.com/ThaliTester/TestResults/tree/8344405013e13cf__906_Choose_Swift_codestyle_guide_for_ThaliCore_dersim-davaod/ for the fail logs

**Comment by baydet** [comment]
Reviewed 13 of 14 files at r1.
Review status: 13 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 37 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVjtYbJ5KYCquygaOP:-KQVjtYc7KtyrKu_TgCi:by8itev) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L37)):*
> ```YAML
>   error: 150
> function_parameter_count:
>   warning: 5
> ```

Isn't it too little? I'm just afraid of situation when you need to create some abstraction just for hiding function parameters into one structure just to make linter happy. But it doesn't mean that this code will be easier to understand because now I should guess for what reasons we have this structure. Every new abstraction makes harder to understand code. So I'm not sure if our current code will pass this requirement but I'm sure that it have enough level of abstractions.

What do you think about it?

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 78 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVleKQbEtwekF3_lIi:-KQVleKQbEtwekF3_lIj:b-a22lbp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L78)):*
> ```YAML
> variable_name:
>   min_length:
>     warning: 4
> ```

The similar question I've mentioned above. For example we have now property `uuid` in PeerIdentifier. I don't think we should add some additional explanation like uuidString, because it already have String type.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 87 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVnGtkta86otFfGz6I:-KQVnGtkta86otFfGz6J:bgdimom) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L87)):*
> ```YAML
>      - rhs
>      - url
>      - app
> ```

Don't you think it's kind of tricky to have name-exceptions? ... Besides lhs and rhs for sure... But if we have lhs and rhs therefore we have all the rights to have `url` and `app` :) 
Could you specify cases where it's enough to use `app` but not the `application` variable name? I think we should have here only swift-generated variables names like lhs and rhs. Because when I see `app` name in excluded list I want to see there `ext`, `str` and `tmp` as well :)

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 103 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVhTHnXq_RZBezD4qH:-KQVhTHnXq_RZBezD4qI:bupm0o0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L103)):*
> ```YAML
>   empty_first_line:
>     name: "Empty First Line"
>     regex: "(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\{\n *\S+)"
> ```

I'm a little bit confused because I didn't find a rule like that in ray wenderlich (from now our guide). To avoid this confusion I suggest to remove this rule because when I look into guide I see one style and when I look on real code - I see different style. I suppose we should avoid this situations :)

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 106 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVnJhd4rG2pun9Yv0j:-KQVnJhd4rG2pun9Yv0k:bdzdbjp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L106)):*
> ```YAML
>     message: "There should be an empty line after a declaration"
>     severity: error
>   empty_line_after_guard:
> ```

The same question as for protocol/class/struct empty line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965)*

**Comment by baydet** [comment]
Reviewed 1 of 14 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965)*

**Comment by larryonoff** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 6 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQ_XmWP6ubd1sjtdH9N:-KQ_XX1AkmgV8S4AdLCc:bjv5iky) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L6)):*
> ```YAML
>   - conditional_returns_on_newline
>   - cyclomatic_complexity
>   - empty_count
> ```

Maybe lets threat `empty_count` as a warning?

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 37 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVjtYbJ5KYCquygaOP:-KQ_YQ5FDAB-Hw4wtWa-:b8j70py) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L37)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> Isn't it too little? I'm just afraid of situation when you need to create some abstraction just for hiding function parameters into one structure just to make linter happy. But it doesn't mean that this code will be easier to understand because now I should guess for what reasons we have this structure. Every new abstraction makes harder to understand code. So I'm not sure if our current code will pass this requirement but I'm sure that it have enough level of abstractions.
> 
> What do you think about it?
</details>
I think that we should remove this rule or increase limit, since we may have a lot of `init` parameters when we're initialising object with all its dependencies and there're many dependencies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ceb1988)

**Comment by dersim-davaod** [comment]
Review status: 13 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 6 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQ_XmWP6ubd1sjtdH9N:-KQfAh_m07e5-gQlR9Rf:byyk3p1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L6)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> Maybe lets threat `empty_count` as a warning?
</details>
Agree, we can do it.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 37 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVjtYbJ5KYCquygaOP:-KQVpcQUjfkNrL7kutCd:b6bxphc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L37)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I think that we should remove this rule or increase limit, since we may have a lot of `init` parameters when we're initialising object with all its dependencies and there're many dependencies.
</details>
Ok, let's disable function_parameter_count rule.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 78 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVleKQbEtwekF3_lIi:-KQfRhRhfG_JxAFqPRFf:b-370wpq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L78)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> The similar question I've mentioned above. For example we have now property `uuid` in PeerIdentifier. I don't think we should add some additional explanation like uuidString, because it already have String type.
</details>
I think that in case with variable_name we can try different values. For example we can throw warning if length <= 3. It allows us to use short names during implementation. At the same time, since every developer must treat warnings as errors, I hope this rule can help us not to forget rename such common things like "vc", "nc", "app" etc, before pushing PR.

I agree that we should be able to use variables like "uuid" or swift-generated "lhr"/"rhs". And this is the case for excluded list. But we should add exceptions only when we faced with the need to do it. We have an opportunity to tune configuration in the future. So I suggest to remove all names from exception lists except "lhs", "rhs" and "uuid", because we use them in production-ready code.

Anyway, remember, SwiftLint is not a silver bullet and we have to use our brains, guys :)

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 87 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVnGtkta86otFfGz6I:-KQfSm9so75_wkCTC6XZ:bvbuiq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L87)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> Don't you think it's kind of tricky to have name-exceptions? ... Besides lhs and rhs for sure... But if we have lhs and rhs therefore we have all the rights to have `url` and `app` :) 
> Could you specify cases where it's enough to use `app` but not the `application` variable name? I think we should have here only swift-generated variables names like lhs and rhs. Because when I see `app` name in excluded list I want to see there `ext`, `str` and `tmp` as well :)
</details>
Agree, please see my comment above. 

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 103 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVhTHnXq_RZBezD4qH:-KQfSvDrRxRQOqXfShsJ:b-wlnj8w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L103)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> I'm a little bit confused because I didn't find a rule like that in ray wenderlich (from now our guide). To avoid this confusion I suggest to remove this rule because when I look into guide I see one style and when I look on real code - I see different style. I suppose we should avoid this situations :)
</details>
Yeah, there is not this rule in code style guide.

But I like it, because I saw many type declarations and usually for unknown reasons some of them use empty line and some of them not. So I just want to bring uniqueness. BTW, you can see that many famous libraries follow this rule.

Does it all make sense?

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 106 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVnJhd4rG2pun9Yv0j:-KQfmHizzYSrADZZT5ex:blvst96) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L106)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> The same question as for protocol/class/struct empty line
</details>
Please see previous comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965)*

**Comment by ThaliTester** [comment]
Test (Success) 83444050 build is completed (ceb1988)

See https://github.com/ThaliTester/TestResults/tree/83444050ceb1988__906_Choose_Swift_codestyle_guide_for_ThaliCore_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 83444050ceb1988(ceb1988) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/83444050ceb1988__906_Choose_Swift_codestyle_guide_for_ThaliCore_dersim-davaod/ for the logs

**Comment by larryonoff** [comment]
Please add warning rule for `closures` that forces developer to declare closures when `Void` in the following way:
1. ```(A, B, C) -> Void``` in case of empty result.
1. ```() -> Void``` in case of empty parameters.

---

Review status: 13 of 14 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-:-KQywEti3y0Sr0ZyzuKZ:bdquwy8)*

**Comment by baydet** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 103 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVhTHnXq_RZBezD4qH:-KQz-mPlW6OXtI0hj2ue:b-z71zrq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L103)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary>
> Yeah, there is not this rule in code style guide.
> 
> But I like it, because I saw many type declarations and usually for unknown reasons some of them use empty line and some of them not. So I just want to bring uniqueness. BTW, you can see that many famous libraries follow this rule.
> 
> Does it all make sense?
</details>
Sounds reasonable. Shouldn't be there `enum` as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965)*

**Comment by dersim-davaod** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 103 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVhTHnXq_RZBezD4qH:-KQzQNl8-tuHD0RF0FP2:btelgzf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L103)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> Sounds reasonable. Shouldn't be there `enum` as well?
</details>
Yeah, we can add <code>enum</code>.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (adbb179)

**Comment by dersim-davaod** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/.swiftlint.yml, line 103 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-KQVhTHnXq_RZBezD4qH:-KR-Ap2WzOEw_YEwIcyJ:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/13e13cf9c27189a2a672fdc052b51cef1ed432ed/lib/ios/ThaliCore/.swiftlint.yml#L103)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary>
> Yeah, we can add <code>enum</code>.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965)*

**Comment by baydet** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-:-KR-CK-OThnUTH3B7E3-:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 83444050 build is completed (adbb179)

See https://github.com/ThaliTester/TestResults/tree/83444050adbb179__906_Choose_Swift_codestyle_guide_for_ThaliCore_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 83444050adbb179(adbb179) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/83444050adbb179__906_Choose_Swift_codestyle_guide_for_ThaliCore_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0e39eda)

**Comment by dersim-davaod** [comment]
@larryonoff, done.

---

Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-:-KR2i84gOW4pb_aplOci:b-id15b)*

**Comment by ThaliTester** [comment]
Test (Success) 83444050 build is completed (0e39eda)

See https://github.com/ThaliTester/TestResults/tree/834440500e39eda__906_Choose_Swift_codestyle_guide_for_ThaliCore_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 834440500e39eda(0e39eda) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/834440500e39eda__906_Choose_Swift_codestyle_guide_for_ThaliCore_dersim-davaod/ for the logs

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-:-KR2mAVg9ZHWEN00VFVH:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 12 of 14 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/965#-:-KR5c-pZXbU-Vsl4R5pz:bnfp4nl)*

**Pull request merged**
