### PR TITLE
Create "Useful commands to run Android apps via command line" guide

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1311)

### CODE REVIEW

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1311#-:-KTyR-OJlfWOUsO9S3Ql:bnfp4nl)*

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1311#-:-KU-1w9STn3BK41F5uIV:bnfp4nl)*

**Pull request merged**
