### PR TITLE
#842 Removed the app.js work around

### PR DESCRIPTION
**Pull request by artemjackson**
Removed success log on `app.js` loading failure.
Added failure log on `app.js` loading failure.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/845)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (be6cebf)

**Comment by artemjackson** [comment]
@yaronyg is failure expected?

```
Test 80598264be6cebf(be6cebf) has failed

See https://github.com/ThaliTester/TestResults/tree/80598264be6cebf__842_Removed_the_app_js_work_around_artemjackson/ for the fail logs
```

**Comment by ThaliTester** [comment]
Test (Success) 80598852 build is completed (be6cebf)

See https://github.com/ThaliTester/TestResults/tree/80598852be6cebf__842_Removed_the_app_js_work_around_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 80598852be6cebf(be6cebf) has failed

See https://github.com/ThaliTester/TestResults/tree/80598852be6cebf__842_Removed_the_app_js_work_around_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
This is also blocked on CI

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b8a90be)

**Comment by ThaliTester** [comment]
Test (Success) 80598852 build is completed (b8a90be)

See https://github.com/ThaliTester/TestResults/tree/80598852b8a90be__842_Removed_the_app_js_work_around_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 80598852b8a90be(b8a90be) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/80598852b8a90be__842_Removed_the_app_js_work_around_artemjackson/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/845#-:-KPOxv3GhxUNWgNFgxH_:bnfp4nl)*

**Pull request merged**
