### PR TITLE
Socket hang up and connection refused

### LINKED ISSUE #1138: socket hang up
I've modified `thaliReplicationPeerAction` a bit.

```
ThaliReplicationPeerAction.prototype.start = function (httpAgentPool) {
  var self = this;

  var stackTrace = '';
  try {
    throw new Error("something");
  } catch (e) {
    stackTrace = e.stack;
  }
  ...

.on('error', function (err) {
  ...
  err.toString = function () {
    return util.format(
      'Got error on replication!, error: \'%s\', trace: \'%s\'',
      err.message, stackTrace
    );
  }
  self._complete([err]);
 ...
```

And I've found the problem in coordinated test `testThaliReplicationPeerActionCoordinated.js`.

```
2016-09-23 10:26:15 - DEBUG testUtils: 'Got an err - Got error on replication!, error: 'socket hang up -1', trace: 'Error: something
    at ThaliReplicationPeerAction.start (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/thali/NextGeneration/replication/thaliReplicationPeerAction.js:186:11)
    at /root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/bv_tests/testThaliReplicationPeerActionCoordinated.js:138:40
```

When I was checking this bug I've found another one:

```
2016-09-23 09:59:53 - ERROR TestsProcess: 'uncaught promise rejection, error: 'Error: read ECONNRESET', stack: 'Error: read ECONNRESET
    at errnoException (net.js:837:11)
    at TCP.onread (net.js:519:19)
---------------------------------------------
    at CleartextStream.Readable.on (_stream_readable.js:657:33)
    at http.js:1383:12
    at process._tickCallback (node.js:924:13)
---------------------------------------------
    at ClientRequest.onSocket (http.js:1359:11)
    at ForeverAgentSSL.Agent.addRequest [as addRequestNoreuse] (http.js:895:9)
    at ForeverAgentSSL.ForeverAgent.addRequest (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/thali/node_modules/forever-agent/index.js:77:10)
    at new ClientRequest (http.js:1044:16)
    at Object.exports.request (https.js:100:10)
    at Request.start (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:753:32)
    at Request.end (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:1418:10)
    at end (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:580:14)
    at Object._onImmediate (/root/workspace/vNext_aaladev_1123/Thali_CordovaPlugin/test/www/jxcore/node_modules/pouchdb/node_modules/request/request.js:594:7)
    at processImmediate [as _immediateCallback] (timers.js:370:15)''
```

All these problems are related to `testThaliPullReplicationFromNotificationCoordinated.js` and `testThaliReplicationPeerActionCoordinated.js`. These problems is related to `pouchdb.replication` and `action.start` and now we definitely know what we need to fix.

We should catch socket hang ups and connection refused like errors properly.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1138.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1192)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (86f37d8)

**Comment by andrew-aladev** [comment]
This issue is blocking, I am merging it.

**Comment by andrew-aladev** [comment]
We can still do a review and fix issues.

**Comment by ThaliTester** [comment]
Test (Fail) 87011676 build is completed (86f37d8)

See https://github.com/ThaliTester/TestResults/tree/8701167686f37d8_Socket_hang_up_and_connection_refused_andrew-aladev/ for the logs

**Pull request merged**
