### PR TITLE
#1146 remove shrinkwrap

### LINKED ISSUE #1146: Kill shrinkwrap in both vNext and vNext_yarong_417_812
It is causing us too many problems with JX and we just don't have the time to resolve this right now.

### PR DESCRIPTION
**Pull request by chapko**
Closes #1146

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1155)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (55de81a)

**Comment by ThaliTester** [comment]
Test (Success) 86708518 build is completed (55de81a)

See https://github.com/ThaliTester/TestResults/tree/8670851855de81a__1146_remove_shrinkwrap_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 8670851855de81a(55de81a) has failed

See https://github.com/ThaliTester/TestResults/tree/8670851855de81a__1146_remove_shrinkwrap_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1155#-:-KSbprj-q-sl3oe6tK2m:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5d3628e)

**Comment by ThaliTester** [comment]
Test (Success) 86708518 build is completed (5d3628e)

See https://github.com/ThaliTester/TestResults/tree/867085185d3628e__1146_remove_shrinkwrap_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 867085185d3628e(5d3628e) has failed

See https://github.com/ThaliTester/TestResults/tree/867085185d3628e__1146_remove_shrinkwrap_chapko/ for the fail logs

**Pull request merged**
