### PR TITLE
Fixing thaliWifiInfrastructure.startUpdateAdvertisingAndListening sho…

### PR DESCRIPTION
**Pull request by opetkevich**
…uld not restart the SSDP server

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1817)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b040692)

**Comment by ThaliTester** [comment]
Test 108992652 (b040692) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 108992652 build is completed (b040692)

See https://github.com/ThaliTester/TestResults/tree/108992652b040692_Fixing_thaliWifiInfrastructure_startUpdateAdvertisingAndListening_sho…_opetkevich/ for the logs

**Comment by chapko** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 833 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-KeYFhKy-4kZcmyGlIcH:-KeYFhKy-4kZcmyGlIcI:b567bmp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b04069281aa4bf21c6d59512e822dce0707aa72a/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L833)):*
> ```JavaScript
>   function (t) {
>     var advertisingEndSpy =
>       sinon.spy(wifiInfrastructure.advertiser, 'stop');
> ```

This test should check that ssdp server itself is not stopped. So you should spy on `wifiInfrastructure.advertiser._server`.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 836 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-KeYFxKadvRpAa_cl-uD:-KeYFxKadvRpAa_cl-uE:b-j1zetr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b04069281aa4bf21c6d59512e822dce0707aa72a/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L836)):*
> ```JavaScript
>     wifiInfrastructure.startListeningForAdvertisements()
>       .then(function () {
>         return wifiInfrastructure.startUpdateAdvertisingAndListening();
> ```

`startUpdateAdvertising` should be called at least twice before checking spy callCount. SSDP server was restarting on update, not on the first start.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 370 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-KeYEnEmUH9NOIv8f7vE:-KeYEnEnPjYdN3rcHgmb:b-2kye76) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b04069281aa4bf21c6d59512e822dce0707aa72a/thali/NextGeneration/thaliWifiInfrastructure.js#L370)):*
> ```JavaScript
>   self.peer.generation++; 
>   var usn = USN.stringify(self.peer);
>   self._server.setUSN(usn);
> ```

NB: I think we can reuse `_startPeerAdvertising` method here. Or we can just get rid of that method since it doesn't do much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817)*

**Comment by chapko** [comment]
Aslo I think we need a test to check that ssdp client receives correct USN after we call `startUpdateAdvertisingAndListening()`

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (941266d)

**Comment by ThaliTester** [comment]
Test 108992652 (941266d) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 108992652 build is completed (941266d)

See https://github.com/ThaliTester/TestResults/tree/108992652941266d_Fixing_thaliWifiInfrastructure_startUpdateAdvertisingAndListening_sho…_opetkevich/ for the logs

**Comment by chapko** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 853 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-KecjUd-UHO52Wy5Yd6r:-KecjUd0-n6v6rxiEQCh:bdzkb8m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/941266d0e3b57f79a78c73b8e0650272abe4c79c/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L853)):*
> ```JavaScript
> );
> 
> test('SSDP client receives correct USN after #startUpdateAdvertisingAndListening called', function (t) {
> ```

This test should call `startUpdateAdvertisingAndListening` at least twice and check that:
1. SSDP client does not receive advertise-bye events on generation update
2. SSDP client receives correct USN (generation must be increased after every `startUpdateAdvertisingAndListening` call.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 356 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-KeckCieSHLdBSk33Q6d:-KeckCieSHLdBSk33Q6e:b-1h30c4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/941266d0e3b57f79a78c73b8e0650272abe4c79c/thali/NextGeneration/thaliWifiInfrastructure.js#L356)):*
> ```JavaScript
>   if (startPeerAdvertising) {
>     return this._server.startAsync();
>   }
> ```

Now this function does not always return Promise, which is a bad idea, even if it a private method. I would suggest to simply move `this._server.startAsync()` to where it should be called. And probably just replace every `_setUsn` call with
```JavaScript
this._server.setUSN(USN.stringify(this.peer));
```
I don't think this line deserves its own method :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f0bb72c)

**Comment by ThaliTester** [comment]
Test 108992652 (f0bb72c) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 108992652 build is completed (f0bb72c)

See https://github.com/ThaliTester/TestResults/tree/108992652f0bb72c_Fixing_thaliWifiInfrastructure_startUpdateAdvertisingAndListening_sho…_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c449fe4)

**Comment by ThaliTester** [comment]
Test 108992652 (c449fe4) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 108992652 build is completed (c449fe4)

See https://github.com/ThaliTester/TestResults/tree/108992652c449fe4_Fixing_thaliWifiInfrastructure_startUpdateAdvertisingAndListening_sho…_opetkevich/ for the logs

**Comment by chapko** [comment]
Please fix comment below and then :lgtm:
-@chapko  +@opetkevich 

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 833 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-Kern_xKVWJFXnRoeUh7:-Kern_xKVWJFXnRoeUh8:bfnz44l) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c449fe45b1cca2ea9640735e773bbdca6d48e846/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L833)):*
> ```JavaScript
> test('SSDP server should not restart after Wifi Client changed generation',
>   function (t) {
>     var advertisingEndSpy =
> ```

This spy should be restored after test ends.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 886 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-KernjuzC3TYJJ0aGlGK:-KernjuzC3TYJJ0aGlGL:b-gkmdvd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c449fe45b1cca2ea9640735e773bbdca6d48e846/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L886)):*
> ```JavaScript
>     }
> 
>     if (aliveCalled) {
> ```

NB: I think its better to switch if and else bodies (use `if (!aliveCalled)`) so they will run in a natural order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-:-KeroBaX-aXX2115bGci:b-71qm2a)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1817#-:-KetI1L42t-fYVrEoTrf:bnfp4nl)*

**Pull request merged**
