### PR TITLE
Fix for #711 - added jxcore url to configuration file

### PR DESCRIPTION
**Pull request by czyzm**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/713)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7f6295f)

**Comment by ThaliTester** [comment]
Test (Success) 67299656 build is completed (7f6295f)

See https://github.com/ThaliTester/TestResults/tree/672996567f6295f_Fix_for__711_-_added_jxcore_url_to_configuration_file_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 672996567f6295f(7f6295f) has failed

See https://github.com/ThaliTester/TestResults/tree/672996567f6295f_Fix_for__711_-_added_jxcore_url_to_configuration_file_czyzm/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/713#-:-KFufYJqgmG7BFH39WvU:1417088721)*

**Pull request merged**
