### PR TITLE
Add null sending in JSON between Android and Node

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1747)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (579949a)

**Comment by ThaliTester** [comment]
Test 102585911 (579949a) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102585911 build is completed (579949a)

See https://github.com/ThaliTester/TestResults/tree/102585911579949a_Add_null_sending_in_JSON_between_Android_and_Node_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 102585911579949a(579949a) has failed

See https://github.com/ThaliTester/TestResults/tree/102585911579949a_Add_null_sending_in_JSON_between_Android_and_Node_evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
Test failure is the same like in #1738

**Comment by czyzm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 578 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-KbAGpoYd8GzfjGN2OlP:-KbAGpoYd8GzfjGN2OlQ:bu905y0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/579949a5815932eea8e83fb3ffd58fc6793acb06/src/android/java/io/jxcore/node/JXcoreExtension.java#L578)):*
> ```Java
> 
>         try {
>             jsonObject.put(EVENT_VALUE_DISCOVERY_ACTIVE, isDiscoveryActive);
> ```

Use putValueInJson also here.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 731 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-KbAGgcfGY_YJC38LDmG:-KbAGgcfGY_YJC38LDmH:bu905y0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/579949a5815932eea8e83fb3ffd58fc6793acb06/src/android/java/io/jxcore/node/JXcoreExtension.java#L731)):*
> ```Java
> 
>             try {
>                 jsonObject.put(EVENT_VALUE_PORT_NUMBER, portNumber);
> ```

Use putValueInJson also here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747)*

**Comment by czyzm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 649 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-KbATTnlK3_E4RGkcDMt:-KbATTnlK3_E4RGkcDMu:btd27ad) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/579949a5815932eea8e83fb3ffd58fc6793acb06/src/android/java/io/jxcore/node/JXcoreExtension.java#L649)):*
> ```Java
>             putValueInJson(jsonObject, EVENT_VALUE_CELLULAR,
>                 radioStateEnumValueToString(cellularRadioState));
>             if (wifiRadioState != RadioState.NOT_HERE) {
> ```

I think that instead of omitting BSSID and SSID in this case it would be more consistent to keep it in object but set to NULL. Is there some specific reason for this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747)*

**Comment by czyzm** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 578 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-KbAGpoYd8GzfjGN2OlP:-KbA_c4GEsf4OsvX-tIY:b-42jkhc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/579949a5815932eea8e83fb3ffd58fc6793acb06/src/android/java/io/jxcore/node/JXcoreExtension.java#L578)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

Use putValueInJson also here.
</blockquote></details>

It works fine for primitive type. We can process primitives like reference types

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 649 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-KbATTnlK3_E4RGkcDMt:-KbAaX0sSC-WLuYSZuJ1:bpe1bmc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/579949a5815932eea8e83fb3ffd58fc6793acb06/src/android/java/io/jxcore/node/JXcoreExtension.java#L649)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

I think that instead of omitting BSSID and SSID in this case it would be more consistent to keep it in object but set to NULL. Is there some specific reason for this change?
</blockquote></details>

https://github.com/thaliproject/Thali_CordovaPlugin/blob/iOS/thali/NextGeneration/thaliMobileNative.js#L678-L679
If we don't have wifi radio, we shouldn't provide BSSID & SSID

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 731 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-KbAGgcfGY_YJC38LDmG:-KbA_w1So-gsRx4BevQr:b-q64pkt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/579949a5815932eea8e83fb3ffd58fc6793acb06/src/android/java/io/jxcore/node/JXcoreExtension.java#L731)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

Use putValueInJson also here.
</blockquote></details>

See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d0c1950)

**Comment by ThaliTester** [comment]
Test 102585911 (d0c1950) build started.

**Comment by ThaliTester** [comment]
Test (Success) 102585911 build is completed (d0c1950)

See https://github.com/ThaliTester/TestResults/tree/102585911d0c1950_Add_null_sending_in_JSON_between_Android_and_Node_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 102585911d0c1950(d0c1950) has failed

See https://github.com/ThaliTester/TestResults/tree/102585911d0c1950_Add_null_sending_in_JSON_between_Android_and_Node_evabishchevich/ for the fail logs

**Comment by czyzm** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 578 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-KbAGpoYd8GzfjGN2OlP:-KbE4rdi6VDaeytzJyoH:b-xdfvvx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/579949a5815932eea8e83fb3ffd58fc6793acb06/src/android/java/io/jxcore/node/JXcoreExtension.java#L578)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

It works fine for primitive type. We can process primitives like reference types
</blockquote></details>

I was thinking more about consistency. Above you are also using putValueInJson for primitive (isAvailable) so when reading this code someone may wonder why the same thing is done differently.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 649 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-KbATTnlK3_E4RGkcDMt:-KbE3Hc-8P1xY3fbMuOn:b32wtd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/579949a5815932eea8e83fb3ffd58fc6793acb06/src/android/java/io/jxcore/node/JXcoreExtension.java#L649)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

https://github.com/thaliproject/Thali_CordovaPlugin/blob/iOS/thali/NextGeneration/thaliMobileNative.js#L678-L679
If we don't have wifi radio, we shouldn't provide BSSID & SSID
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747)*

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-:-KbE5eJzYt4zt3-DuACe:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1747#-:-KbH1UpzK6VVdBFP5pcJ:bnfp4nl)*

**Pull request merged**
