### PR TITLE
Fix event name

### PR DESCRIPTION
**Pull request by chapko**
ThaliMobile was listening to the non existing event

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1396)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bddca33)

**Comment by ThaliTester** [comment]
Test (Fail) 90213620 build is completed (bddca33)

See https://github.com/ThaliTester/TestResults/tree/90213620bddca33_Fix_event_name_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a1cae7b)

**Comment by ThaliTester** [comment]
Test (Fail) 90213620 build is completed (a1cae7b)

See https://github.com/ThaliTester/TestResults/tree/90213620a1cae7b_Fix_event_name_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (405009f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7252bec)

**Comment by ThaliTester** [comment]
Test (Fail) 90213620 build is completed (405009f)

See https://github.com/ThaliTester/TestResults/tree/90213620405009f_Fix_event_name_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 90213620 build is completed (7252bec)

See https://github.com/ThaliTester/TestResults/tree/902136207252bec_Fix_event_name_chapko/ for the logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396#-:-KUr3j_rUPOJK9Vxxml6:bnfp4nl)*

**Comment by yaronyg** [comment]
I do have a blocking comment. Sorry. :( See below.

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 594 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396#-KUsw6LcetHBRSi28rjD:-KUsw6LdihD2Dq8lkcwq:bn9ygmr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7252bec5e96cbc2c482a22f30411611fed4539e8/test/www/jxcore/bv_tests/testThaliMobile.js#L594)):*
> ```JavaScript
> 
>     var originalThreshold = thaliConfig.NON_TCP_PEER_UNAVAILABILITY_THRESHOLD;
>     thaliConfig.NON_TCP_PEER_UNAVAILABILITY_THRESHOLD = 500;
> ```

I think we need to go back to the proxyquire approach or at least use a sinon sandbox or something. Because if this test goes sidewise then all future tests will have the wrong value for NON_TCP_PEER_UNAVAILABILITY_THRESHOLD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396#-:-KUswNJZO0CF1ZnUvFhI:b6yhkhd)*

**Comment by chapko** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 594 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396#-KUsw6LcetHBRSi28rjD:-KV-gpi-UrGDrKKv-lMO:b-tbk3tm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7252bec5e96cbc2c482a22f30411611fed4539e8/test/www/jxcore/bv_tests/testThaliMobile.js#L594)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> I think we need to go back to the proxyquire approach or at least use a sinon sandbox or something. Because if this test goes sidewise then all future tests will have the wrong value for NON_TCP_PEER_UNAVAILABILITY_THRESHOLD
</details>
@yaronyg I removed proxyquire because it caused test failures. With proxyquire we have 2 different instances of thaliMobile module each of which has its own state and produces it s own logs. I didn't investigate this problem because after I removed proxyquire all tests are magically passed several times in a row.

I don't think it is a good idea to override this constant for every test in this file (see #1403). And sinon sandbox doesn't help it either because sandbox has to be restored manually. The best solution is to prevent this on the test framework level (#1347)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396)*

**Comment by chapko** [comment]
I suggest to leave it as is until #1347 is implemented.

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 594 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396#-KUsw6LcetHBRSi28rjD:-KV1e6hOCq3XEPkO9C71:bayv1hi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7252bec5e96cbc2c482a22f30411611fed4539e8/test/www/jxcore/bv_tests/testThaliMobile.js#L594)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> @yaronyg I removed proxyquire because it caused test failures. With proxyquire we have 2 different instances of thaliMobile module each of which has its own state and produces it s own logs. I didn't investigate this problem because after I removed proxyquire all tests are magically passed several times in a row.
> 
> I don't think it is a good idea to override this constant for every test in this file (see #1403). And sinon sandbox doesn't help it either because sandbox has to be restored manually. The best solution is to prevent this on the test framework level (#1347)
</details>
I don't understand what you mean about the sandbox having to be restored manually. Why can't we just wrap this single function in sinon.test? It even appears to support returning promises and won't disable the sandbox until the promise has returned, see https://github.com/sinonjs/sinon-test/commit/c93063c18e33fe064d619f3d9b1d2603cd2c0157

Do make sure to turn off fake timers and such.

Alternatively (since we do have day jobs) just please stick a .catch() and a .then() after it and restore the value there. Because right now if start returns anything but success the original value will never be restore. But if we put a .catch followed by a .then and put the restore in the .then then we know we will always be restored.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c548c1b)

**Comment by chapko** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 594 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396#-KUsw6LcetHBRSi28rjD:-KV4sWdvOqMJUod4H-Lp:b-19gyg8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7252bec5e96cbc2c482a22f30411611fed4539e8/test/www/jxcore/bv_tests/testThaliMobile.js#L594)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> I don't understand what you mean about the sandbox having to be restored manually. Why can't we just wrap this single function in sinon.test? It even appears to support returning promises and won't disable the sandbox until the promise has returned, see https://github.com/sinonjs/sinon-test/commit/c93063c18e33fe064d619f3d9b1d2603cd2c0157
> 
> Do make sure to turn off fake timers and such.
> 
> Alternatively (since we do have day jobs) just please stick a .catch() and a .then() after it and restore the value there. Because right now if start returns anything but success the original value will never be restore. But if we put a .catch followed by a .then and put the restore in the .then then we know we will always be restored.
</details>
Oh yes, I totally forgot to add `catch` at the end.

Sinon's `sinon.test` has support for async tests, but it is not compatible with our tape.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396)*

**Comment by ThaliTester** [comment]
Test (Success) 90213620 build is completed (c548c1b)

See https://github.com/ThaliTester/TestResults/tree/90213620c548c1b_Fix_event_name_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 90213620c548c1b(c548c1b) has failed

See https://github.com/ThaliTester/TestResults/tree/90213620c548c1b_Fix_event_name_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1396#-:-KVBE-KS7LcdwqcowY9L:bnfp4nl)*

**Pull request merged**
