### PR TITLE
New WiFi functionality (getting SSID)

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1324)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5849728)

**Comment by ThaliTester** [comment]
Test (Success) 89378607 build is completed (5849728)

See https://github.com/ThaliTester/TestResults/tree/893786075849728_New_WiFi_functionality__getting_SSID__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 893786075849728(5849728) has failed

See https://github.com/ThaliTester/TestResults/tree/893786075849728_New_WiFi_functionality__getting_SSID__dersim-davaod/ for the fail logs

**Comment by baydet** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1324#-:-KUICexTXBZEQZwlZeMF:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1324#-:-KUTSemMIBavXkkADYHY:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8e42e33)

**Comment by ThaliTester** [comment]
Test (Fail) 89378607 build is completed (8e42e33)

See https://github.com/ThaliTester/TestResults/tree/893786078e42e33_New_WiFi_functionality__getting_SSID__dersim-davaod/ for the logs

**Pull request merged**
