### PR TITLE
Fixed test server custom error

### LINKED ISSUE #1614: The coordination server doesn't appear to handle time outs in teardown very well
Something is really not right here when it comes to the coordination client.

HTC 9 - https://gist.github.com/yaronyg/d67e4a22b07662020f5f007b47b8e426
Nexus 6 - https://gist.github.com/yaronyg/fcce53ff519ef102fa482ad0c7b6c5a1
Test Server Log - https://gist.github.com/yaronyg/efd320ec60e715ad3d9426b090cbd2d4

If you look at the logs you will see that the HTC 9 successfully completed the test and entered teardown. But the Nexus 6 never completed the test. However at some point the coordination server tripped _complete and then tripped _disconnect which caused the system to think it was done but if you search for 'not ok' in the Nexus 6 log above you will see that the test had not finished!

So how did _complete get fired?

Now I can see that the HTC 9 (in the server log) disconnected. This appears to have happened because the timeout expired on the HTC One. Which makes sense as the HTC One was waiting in tear down and the Nexus 6 never got to tear down.

So my guess is that what is happening is that for some reason (which is bug thaliproject/Thali_CordovaPlugin#1596 ) the Nexus 6 didn't finish the test. Meanwhile the HTC 9 had finished and was waiting in tear down. The tear down timed out and this somehow tripped bad behavior by the coordination server who told the Nexus 6 that everything had completed (which it hadn't) and caused the various errors we see in the log.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1614.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1716)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6975e49)

**Comment by ThaliTester** [comment]
Test 100908158 (6975e49) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 100908158 build is completed (6975e49)

See https://github.com/ThaliTester/TestResults/tree/1009081586975e49_Fixed_test_server_custom_error_andrew-aladev/ for the logs

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1716#-:-KaCNtdD9dyzIG2Vgi8E:bg7igkv)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1716#-:-KaDYC-rGyHQWEG08-yP:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (85b9312)

**Comment by ThaliTester** [comment]
Test 100908158 (85b9312) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 100908158 build is completed (85b9312)

See https://github.com/ThaliTester/TestResults/tree/10090815885b9312_Fixed_test_server_custom_error_andrew-aladev/ for the logs

**Pull request merged**
