### PR TITLE
added script for configuring import

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1202)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a66927d)

**Comment by ThaliTester** [comment]
Test (Success) 87126746 build is completed (a66927d)

See https://github.com/ThaliTester/TestResults/tree/87126746a66927d_added_script_for_configuring_import_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 87126746a66927d(a66927d) has failed

See https://github.com/ThaliTester/TestResults/tree/87126746a66927d_added_script_for_configuring_import_baydet/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/before_plugin_install.js, line 14 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1202#-KSn4sOmb4jKMuuDBAnn:-KSn4sOnhyyGl4ovm2rK:b-1a1756) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a66927d54060b9f6c1f9436c7c06ddea4a4aeec0/scripts/before_plugin_install.js#L14)):*
> ```JavaScript
> 
> function updateJXcoreExtensionImport(context) {
>   var cordova_util = context.requireCordovaModule('cordova-lib/src/cordova/util'),
> ```

NB: We generally don't use the ',' based variable declaration format. We need to define each variable on its own line. It's just easier to read and edit. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1202#-:-KSn6QZOk8LGQk1Z0Bck:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (71a25ec)

**Comment by baydet** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/before_plugin_install.js, line 14 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1202#-KSn4sOmb4jKMuuDBAnn:-KSopFQenilse_5zdetu:b-7ql1td) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a66927d54060b9f6c1f9436c7c06ddea4a4aeec0/scripts/before_plugin_install.js#L14)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: We generally don't use the ',' based variable declaration format. We need to define each variable on its own line. It's just easier to read and edit. 
</details>
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1202)*

**Comment by ThaliTester** [comment]
Test (Success) 87126746 build is completed (71a25ec)

See https://github.com/ThaliTester/TestResults/tree/8712674671a25ec_added_script_for_configuring_import_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 8712674671a25ec(71a25ec) has failed

See https://github.com/ThaliTester/TestResults/tree/8712674671a25ec_added_script_for_configuring_import_baydet/ for the fail logs

**Comment by baydet** [comment]
We're having 2 failing tests for iPad2Air that is not related to code I've written here. These failing tests already've rewritten in #1199. So I'm merging this PR.

**Pull request merged**
