### PR TITLE
Make CI build and unit tests pass

### PR DESCRIPTION
**Pull request by vjrantal**
This change is [Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/611)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c54517a)

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (c54517a)

See https://github.com/ThaliTester/TestResults/tree/62509094c54517a_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aba5909)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (aba5909)

See https://github.com/ThaliTester/TestResults/tree/62509094aba5909_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094aba5909(aba5909) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094aba5909_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ffd3875)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (ffd3875)

See https://github.com/ThaliTester/TestResults/tree/62509094ffd3875_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094ffd3875(ffd3875) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094ffd3875_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e6af764)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (e6af764)

See https://github.com/ThaliTester/TestResults/tree/62509094e6af764_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094e6af764(e6af764) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094e6af764_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ea6fb60)

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (ea6fb60)

See https://github.com/ThaliTester/TestResults/tree/62509094ea6fb60_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (ea6fb60)

See https://github.com/ThaliTester/TestResults/tree/62509094ea6fb60_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a319d1d)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (a319d1d)

See https://github.com/ThaliTester/TestResults/tree/62509094a319d1d_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094a319d1d(a319d1d) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094a319d1d_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (2f85e77)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (2f85e77)

See https://github.com/ThaliTester/TestResults/tree/625090942f85e77_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625090942f85e77(2f85e77) has failed

See https://github.com/ThaliTester/TestResults/tree/625090942f85e77_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 86 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611#-KCb3wKYwaiJmfFruXx2:-KCb3wKYwaiJmfFruXx3:939353458) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2f85e77b9f938cfffd25963ab2f774fae5607f64/src/android/java/io/jxcore/node/ConnectionHelper.java#L86)):*
I said the same thing to @tompaana in my review of his similar code. If we have a discovery manager that can't work the right answer can't be to just pretend it can work and let the code go on. We need to throw but we need to catch that throw some place and report it to Node.js. Don't we?

---

*[test/www/jxcore/lib/testUtils.js, line 172 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611#-KCb4rQazx5CykiEvrQK:-KCb4rQazx5CykiEvrQL:531531787) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2f85e77b9f938cfffd25963ab2f774fae5607f64/test/www/jxcore/lib/testUtils.js#L172)):*
NB: Please be kind to future devs and just stick in a if (!jxcore.utils.OSInfo().isAndroid) { return resolve(true) } and then unindent the code above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c3227b2)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (c3227b2)

See https://github.com/ThaliTester/TestResults/tree/62509094c3227b2_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094c3227b2(c3227b2) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094c3227b2_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (42642cd)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (42642cd)

See https://github.com/ThaliTester/TestResults/tree/6250909442642cd_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 6250909442642cd(42642cd) has failed

See https://github.com/ThaliTester/TestResults/tree/6250909442642cd_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4a5472b)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (51f9b2c)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (4a5472b)

See https://github.com/ThaliTester/TestResults/tree/625090944a5472b_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (51f9b2c)

See https://github.com/ThaliTester/TestResults/tree/6250909451f9b2c_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625090944a5472b(4a5472b) has failed

See https://github.com/ThaliTester/TestResults/tree/625090944a5472b_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cfda267)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (cfda267)

See https://github.com/ThaliTester/TestResults/tree/62509094cfda267_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094cfda267(cfda267) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094cfda267_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (588eeb1)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (588eeb1)

See https://github.com/ThaliTester/TestResults/tree/62509094588eeb1_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094588eeb1(588eeb1) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094588eeb1_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (62db1e6)

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (62db1e6)

See https://github.com/ThaliTester/TestResults/tree/6250909462db1e6_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3f585e4)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (3f585e4)

See https://github.com/ThaliTester/TestResults/tree/625090943f585e4_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625090943f585e4(3f585e4) has failed

See https://github.com/ThaliTester/TestResults/tree/625090943f585e4_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c453ee6)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (c453ee6)

See https://github.com/ThaliTester/TestResults/tree/62509094c453ee6_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094c453ee6(c453ee6) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094c453ee6_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (058a2d4)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (058a2d4)

See https://github.com/ThaliTester/TestResults/tree/62509094058a2d4_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094058a2d4(058a2d4) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094058a2d4_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b76d10c)

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (b76d10c)

See https://github.com/ThaliTester/TestResults/tree/62509094b76d10c_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c147163)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (c147163)

See https://github.com/ThaliTester/TestResults/tree/62509094c147163_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094c147163(c147163) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094c147163_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9f80778)

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (9f80778)

See https://github.com/ThaliTester/TestResults/tree/625090949f80778_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c3ee53f)

**Comment by ThaliTester** [comment]
Test 62509094c3ee53f(c3ee53f) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094c3ee53f_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (df6cf37)

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (df6cf37)

See https://github.com/ThaliTester/TestResults/tree/62509094df6cf37_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (df6cf37)

See https://github.com/ThaliTester/TestResults/tree/62509094df6cf37_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (764c200)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (764c200)

See https://github.com/ThaliTester/TestResults/tree/62509094764c200_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094764c200(764c200) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094764c200_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1eef958)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (1eef958)

See https://github.com/ThaliTester/TestResults/tree/625090941eef958_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625090941eef958(1eef958) has failed

See https://github.com/ThaliTester/TestResults/tree/625090941eef958_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (141ff10)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5eea5d7)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (141ff10)

See https://github.com/ThaliTester/TestResults/tree/62509094141ff10_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094141ff10(141ff10) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094141ff10_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (5eea5d7)

See https://github.com/ThaliTester/TestResults/tree/625090945eea5d7_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 62509094 build is completed (5eea5d7)

See https://github.com/ThaliTester/TestResults/tree/625090945eea5d7_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b685d58)

**Comment by ThaliTester** [comment]
Test (Success) 62509094 build is completed (b685d58)

See https://github.com/ThaliTester/TestResults/tree/62509094b685d58_Make_CI_build_and_unit_tests_pass_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62509094b685d58(b685d58) has failed

See https://github.com/ThaliTester/TestResults/tree/62509094b685d58_Make_CI_build_and_unit_tests_pass_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 7 of 8 files at r13, 6 of 8 files at r22, 2 of 2 files at r23.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 86 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611#-KCb3wKYwaiJmfFruXx2:-KD4nZfP18v3VIRQIcwT:2137855176) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4a5472b4d33190c4c767db321221f389834142d4/src/android/java/io/jxcore/node/ConnectionHelper.java#L86)):*
@vjrantal I still think this is an issue

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611)*

**Comment by yaronyg** [comment]
Reviewed 1 of 3 files at r14.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 86 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611#-KCb3wKYwaiJmfFruXx2:-KD7KgrI37NBOPT-ABfm:838438181) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4a5472b4d33190c4c767db321221f389834142d4/src/android/java/io/jxcore/node/ConnectionHelper.java#L86)):*
We had to remove the throw from the function that gets called in the construction phase, because that prevented JXcore from loading our Java code. We have a function separately that is called from Node side that to check if device has required capabilities.

If I am not mistaken, we might still be missing how we report this in the "public API" and I created a separate issue to solve that https://github.com/thaliproject/Thali_CordovaPlugin/issues/641. Let's follow-up there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 86 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611#-KCb3wKYwaiJmfFruXx2:-KD7LlTW4u-UDIXIFIOT:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4a5472b4d33190c4c767db321221f389834142d4/src/android/java/io/jxcore/node/ConnectionHelper.java#L86)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/611)*

**Pull request merged**
