### PR TITLE
switch jxcore-cordova plugin into v8 version

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1222)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ef5c251)

**Comment by ThaliTester** [comment]
Test (Success) 87460634 build is completed (ef5c251)

See https://github.com/ThaliTester/TestResults/tree/87460634ef5c251_switch_jxcore-cordova_plugin_into_v8_version_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 87460634ef5c251(ef5c251) has failed

See https://github.com/ThaliTester/TestResults/tree/87460634ef5c251_switch_jxcore-cordova_plugin_into_v8_version_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c450c37)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (dcd9480)

**Comment by ThaliTester** [comment]
Test (Success) 87460634 build is completed (c450c37)

See https://github.com/ThaliTester/TestResults/tree/87460634c450c37_switch_jxcore-cordova_plugin_into_v8_version_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 87460634 build is completed (dcd9480)

See https://github.com/ThaliTester/TestResults/tree/87460634dcd9480_switch_jxcore-cordova_plugin_into_v8_version_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d91a0a5)

**Comment by ThaliTester** [comment]
Test 87460634c450c37(c450c37) has failed

See https://github.com/ThaliTester/TestResults/tree/87460634c450c37_switch_jxcore-cordova_plugin_into_v8_version_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (3ffc5f3)

**Comment by ThaliTester** [comment]
Test 87460634d91a0a5(d91a0a5) has failed

See https://github.com/ThaliTester/TestResults/tree/87460634d91a0a5_switch_jxcore-cordova_plugin_into_v8_version_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87460634 build is completed (3ffc5f3)

See https://github.com/ThaliTester/TestResults/tree/874606343ffc5f3_switch_jxcore-cordova_plugin_into_v8_version_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 874606343ffc5f3(3ffc5f3) has failed

See https://github.com/ThaliTester/TestResults/tree/874606343ffc5f3_switch_jxcore-cordova_plugin_into_v8_version_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
we agreed with @yaronyg to abandon this v8 on mobiles, since we're having new issues with v8 that we didn't have with SM. So I'm closing this PR.

**Pull request closed without merging**
