### PR TITLE
416 ThaliNotificationClient

### PR DESCRIPTION
**Pull request by juhanak**
ThaliNotificationClient and tests are mostly new. 

Smaller changes in ThaliNotificationAction.js and ThaliPeerDictionary.js and their tests to reflect new simpler design. 

Small fix to runCoordinatedTests.js that allows one to set number of instances for coordinated test run.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/666)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6bb5f66)

**Comment by ThaliTester** [comment]
Test (Success) 63910704 build is completed (6bb5f66)

See https://github.com/ThaliTester/TestResults/tree/639107046bb5f66_416_ThaliNotificationClient_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 639107046bb5f66(6bb5f66) has failed

See https://github.com/ThaliTester/TestResults/tree/639107046bb5f66_416_ThaliNotificationClient_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 9 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZiJ4Ss6Oc0I8yuhXH:-KDZiJ4TyB5xYNQ-fxKL:-1365297480) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L9)):*
NB: Typically all the requires are bunched together without spaces at the top of the file just so that the eye can quickly skip over it. When you put in spaces you are saying "something interesting is happening here" and it causes the reader to stop and look to see what that interesting thing is. But in this case, with the exception of proxyquire which maybe you should put a space before, nothing interesting is going on so I would suggest removing the spaces between the lines.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 26 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZjBDYaAIVF6vbUH1U:-KDZjBDYaAIVF6vbUH1V:-1911969169) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L26)):*
This should not be capitalized. A capital variable name means it is a factory that constructs new instances and should only be used with new. But this is just a function and so should be named makeIntoCloseAllServer

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 62 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZiwxZmpM4AQxcMB2m:-KDZiwx_QZQ4oYCPDKdJ:429711511) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L62)):*
Please set this to 0 just so that if we don't actually use a random port we will eventually get an error.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 64 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZihuKhpM9kHczRghL:-KDZidFAbAKLtwKw9NYh:388544225) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L64)):*
That seems like way too long a time out to be using for BVTs, I can see 10 seconds, but not 100!

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 81 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZjW-oig8tvQrnyUOD:-KDZjW-oig8tvQrnyUOE:1257290324) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L81)):*
NB: This will work as written but it would be polite to specify self.expressServer = makeIntoCloseAllServer(self.expressServer) as it makes it clear that a transformation is going on.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 81 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZ_c--h3hM1w_WConU:-KDZ_c--h3hM1w_WConV:1925479584) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L81)):*
Please do my paranoia a favor and put in an instance of check that unencryptedKeyId is a Buffer. If it is not then return null and log a warning.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 126 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZaO6APdy8tegI0qvv:-KDZaO6APdy8tegI0qvw:1210773790) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L126)):*
NB: From a style perspective I would get rid of the else statement and instead just initialize both _publicKeysToListen and _publisKeyToListenHashes to [] before you call the if statement.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 193 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZauP7cS505XjjLbMs:-KDZauP7cS505XjjLbMt:560280302) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L193)):*
Since logging this data does constitute a security hole please file a bug to remind us to make sure to remove this.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 197 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZb3tsqns5naIgEnCW:-KDZb3ttGhY_N_hrx7x7:277029638) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L197)):*
NB: We should probably at least log at the warning level that we are getting what are, in effect, bogus peer availability changed events.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 209 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZbHpkA6wPZDIJH62z:-KDZbHpkA6wPZDIJH63-:-350108937) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L209)):*
NB: It is very tempting to elevate this to an assert. This is bad and indicates something has gone wrong somewhere in thaliMobile.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 214 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZbQruOHwPSZkgel9k:-KDZbQruOHwPSZkgel9l:173349037) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L214)):*
Why do you need to check exists? If remove is written correctly then nothing should break if you try to remove an entry that isn't there. In other words if you need the if then it means remove is broken. :)

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 231 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZc2BTH_fzDytBd-Zf:-KDZc2BUbTT8xkjRYAuc:640803376) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L231)):*
These tiny functions make the code harder to read, not easier because they require the reader to jump around. So unless you desperately need _addPeer for testing purposes please get rid of it.

BTW, a good counter point is _createNewAction. That is a function you need in two places so it makes sense to break it out even though it is also quite small.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 272 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZcmZnIota1LVAE5UL:-KDZcmZnIota1LVAE5UM:-191393620) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L272)):*
If there is a problem with enqueue it will be returned as an error response. So you need to check if the response is null or an Error. It doesn't throw.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 275 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZcZDR9awIz26HVnOX:-KDZcZDSY3AAwPltkI2i:-1654702051) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L275)):*
I don't believe you need a try catch since neither enqueue nor addUpdateEntry throws.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 299 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZddfPdLqh3aSvwCMY:-KDZddfPdLqh3aSvwCMZ:81091739) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L299)):*
NB: This isn't a useful comment as it states the obvious

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 305 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZdgdH1z5ZIMwCTKT7:-KDZdgdH1z5ZIMwCTKT8:457197841) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L305)):*
NB: See my previous comment :)

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 309 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZdto9REKx6bFgjXHc:-KDZdto9REKx6bFgjXHd:1624100167) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L309)):*
You should really use a switch statement and not nested if/else/if statements.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 384 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZgCB31jN-X4_Ilx49:-KDZgCB46xxRzULVNWmr:1211193305) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L384)):*
I recognize my writing so I assume you copied and pasted the above comment from one of my descriptions and I'm pretty sure now I'm wrong.

The scenario is as follows: Let's say that the android phone has detected a ton of devices and so scheduled a bunch of notification actions to find out who those devices are. One of the notification actions resolves to the identity of a peer that the Android device really wants to replicate with. But right now there are no open slots to do the replication with because all the Bluetooth connection slots are filled up with activate notification actions.

At this point the pool manager has two choices. It can wait for one of the notification actions to finish and then use that slot for replication. Or, more likely, it can decide that since people are always moving around there is no time to lose and therefore it will just nuke one of the notification actions in order to open a slot for a replication action.

There is another scenario where we dump a ton of notification actions into the peer pool's queue and we add so many that the peer pool has to kill them to pull them out. But that really shouldn't happen and if it did it should result in an error from enqueue not a kill.

So I think for now we should treat a KILLED as being the equivalent of a bad network connection and retry.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 397 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZh__Pbqy9-vBL_UZJ:-KDZh__Pbqy9-vBL_UZK:-928677669) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L397)):*
It turns out that it can be very useful to add in a tiny randomly generated delta to keep everyone from retrying in lock step (which really does a number on network utilization). So in the code that calls RETRY_TIMEOUTs you should add a small random generated delay of say between 0 and 100 ms just to keep folks out of synch.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 104 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZZXM02pKz4vXBZ8is:-KDZZXM02pKz4vXBZ8it:1560579970) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliPeerDictionary.js#L104)):*
NB: /defied/defined/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4b9b71d)

**Comment by ThaliTester** [comment]
Test (Fail) 63910704 build is completed (4b9b71d)

See https://github.com/ThaliTester/TestResults/tree/639107044b9b71d_416_ThaliNotificationClient_juhanak/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (05f2a33)

**Comment by ThaliTester** [comment]
Test (Success) 63910704 build is completed (05f2a33)

See https://github.com/ThaliTester/TestResults/tree/6391070405f2a33_416_ThaliNotificationClient_juhanak/ for the logs

**Comment by juhanak** [comment]
Review status: 3 of 7 files reviewed at latest revision, 20 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 26 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZjBDYaAIVF6vbUH1U:-KDbE0w98jlGp00s9ZCU:-1620474753) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L26)):*
fixed.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 62 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZiwxZmpM4AQxcMB2m:-KDbEFdL0v40K0uxwfnm:-1620474753) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L62)):*
fixed.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 64 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZihuKhpM9kHczRghL:-KDbEWAkIFtiTKV4bdbD:1690890792) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L64)):*
Ups, Good catch. It was supposed to be 10 seconds. 

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 81 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZjW-oig8tvQrnyUOD:-KDbF-p4OW6kYVx3KEp6:-1246010335) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L81)):*
Ok. fixed

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 81 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZ_c--h3hM1w_WConU:-KDbIRI5b6w-fqQv9vMn:-1855288814) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L81)):*
Ok. I added Buffer.isBuffer check.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 126 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZaO6APdy8tegI0qvv:-KDbJc5Dn-cszsl2cJaq:1159688552) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L126)):*
Thanks. Indeed it makes it cleaner. 

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 193 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZauP7cS505XjjLbMs:-KDbaByM-5J6697NgZC0:-1166366002) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L193)):*
https://github.com/thaliproject/Thali_CordovaPlugin/issues/674

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 197 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZb3tsqns5naIgEnCW:-KDbbv8gxXANMdCXaB5A:-1323338950) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L197)):*
Added logging

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 209 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZbHpkA6wPZDIJH62z:-KDbjK9NFyUdWphHBaON:1162671005) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L209)):*
Ok, asserted it.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 214 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZbQruOHwPSZkgel9k:-KDbLBsw9mB84slV-VV7:-35657579) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L214)):*
There was an assert inside the remove function that checked if the entry exists or not. I removed it so remove doesn't throw errors even if the entry doesn't exists.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 231 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZc2BTH_fzDytBd-Zf:-KDbMn1oYH4cdzt_ruoS:1412876780) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L231)):*
Thanks for pointing this out again. Fixing it

(short irrelevant history: _addPeer and _createNewAction were one function first. They were split apart when I realized I need _createNewAction functionality in two places. And well then I didn't notice that _addPeer became quite useless)

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 272 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZcmZnIota1LVAE5UL:-KDbjQ6zx0V2SYncIfJ8:1758359711) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L272)):*
Fixed.

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 275 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZcZDR9awIz26HVnOX:-KDbPwPIS23cI4x5k1hi:-1669787541) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L275)):*
Ups. Right. Fixed it so that if the enqueue returns an error we don't add the peer to the dictionary.  

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 309 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZdto9REKx6bFgjXHc:-KDbT6OtIWgrHzsdaQlq:1497398058) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L309)):*
Fixed. Indeed the switch statement made it cleaner. 

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 384 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZgCB31jN-X4_Ilx49:-KDbV1A657CmD-5cOROo:273605399) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L384)):*
Ok, moved KILLED to the same switch path with network problems. However I wonder should we have a less aggressive retry timeout for this case. I mean if the peer pool is under heave pressure waiting 100 ms and trying again may not help it..

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 397 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZh__Pbqy9-vBL_UZJ:-KDbYaNReKqPmglBlURa:283100293) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L397)):*
Sure, I added 0-100 ms random component to the timeout timer.

---

*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 104 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZZXM02pKz4vXBZ8is:-KDb_caXAPMK7a_2d3KV:-1620474753) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliPeerDictionary.js#L104)):*
fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666)*

**Comment by ThaliTester** [comment]
Test 6391070405f2a33(05f2a33) has failed

See https://github.com/ThaliTester/TestResults/tree/6391070405f2a33_416_ThaliNotificationClient_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 64 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZihuKhpM9kHczRghL:-KDd8n1ibUwQ_fa4SBsy:-1915808780) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L64)):*
It's still 100 seconds

---

*[thali/NextGeneration/notification/thaliNotificationClient.js, line 384 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666#-KDZgCB31jN-X4_Ilx49:-KDd9JM1FiaMughvRfR3:67574579) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6bb5f6675719e7b55dfcb6705eb690cb0125ff57/thali/NextGeneration/notification/thaliNotificationClient.js#L384)):*
The retry will only happen if the pool actually schedules the action. If it's under pressure then the action's start won't be called anyway.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6ed3de5)

**Comment by ThaliTester** [comment]
Test (Success) 63910704 build is completed (6ed3de5)

See https://github.com/ThaliTester/TestResults/tree/639107046ed3de5_416_ThaliNotificationClient_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 639107046ed3de5(6ed3de5) has failed

See https://github.com/ThaliTester/TestResults/tree/639107046ed3de5_416_ThaliNotificationClient_juhanak/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8b8fbc2)

**Comment by ThaliTester** [comment]
Test (Success) 63910704 build is completed (8b8fbc2)

See https://github.com/ThaliTester/TestResults/tree/639107048b8fbc2_416_ThaliNotificationClient_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 639107048b8fbc2(8b8fbc2) has failed

See https://github.com/ThaliTester/TestResults/tree/639107048b8fbc2_416_ThaliNotificationClient_juhanak/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0172e2e)

**Comment by ThaliTester** [comment]
Test (Success) 63910704 build is completed (0172e2e)

See https://github.com/ThaliTester/TestResults/tree/639107040172e2e_416_ThaliNotificationClient_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 639107040172e2e(0172e2e) has failed

See https://github.com/ThaliTester/TestResults/tree/639107040172e2e_416_ThaliNotificationClient_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/666)*

**Pull request merged**
