### PR TITLE
Rollback to java 1.6 version

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1807)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b9e18a9)

**Comment by ThaliTester** [comment]
Test 107004850 (b9e18a9) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 107004850 build is completed (b9e18a9)

See https://github.com/ThaliTester/TestResults/tree/107004850b9e18a9_Rollback_to_java_1_6_version_evabishchevich/ for the logs

**Comment by jareksl** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1807#-:-KdaE-ljBWlEymZnMDAa:bg7igkv)*

**Pull request merged**
