### PR TITLE
Is thaliMobile's peerAvailabilityWatchers now just a plain bug? #1457

### PR DESCRIPTION
**Pull request by opetkevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1825)

### CODE REVIEW

**Comment by chapko** [comment]
Reviewed 3 of 6 files at r1, 1 of 2 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2042 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfGEFgut3_tfPauvNl4:-KfGEFgut3_tfPauvNl5:bd028ym) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/42da021f894cbaa8951553c282f57ac2ac14dd88/test/www/jxcore/bv_tests/testThaliMobile.js#L2042)):*
> ```JavaScript
> );
> 
> test('#stop should change peers', function (t) {
> ```

This test uses only native functionality. If there is no similar test for wifi peers we should change it to check both native and wifi peers. Otherwise we can just disable it for wifi.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2043 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfGPvAob0begUNfQ5Vg:-KfGPvApHc5RRYdu_OlD:b9hkb5j) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/42da021f894cbaa8951553c282f57ac2ac14dd88/test/www/jxcore/bv_tests/testThaliMobile.js#L2043)):*
> ```JavaScript
> 
> test('#stop should change peers', function (t) {
>   var somePeerIdentifier = 'urn:uuid:' + uuid.v4();
> ```

that's an old test, peerIdentifier has a new format which is just `uuid.v4()`. There are also several places below with such identifiers.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 723 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfGJX0apS_PNC8Xt7QJ:-KfGJX0apS_PNC8Xt7QK:bxqrod) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/42da021f894cbaa8951553c282f57ac2ac14dd88/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L723)):*
> ```JavaScript
>   'were received during availability timeout',
>   function () {
>     return !platform.isAndroid
> ```

this test is not android-only anymore

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 754 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfGH8020jM8kuTx50gx:-KfGH80396sChytf4Iul:bwgfgad) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/42da021f894cbaa8951553c282f57ac2ac14dd88/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L754)):*
> ```JavaScript
>           }
> 
>           t.notOk((peer.portNumber === null && peer.hostAddress === null), 'Peer should not be available');
> ```

Shouldn't it be `t.ok` instead?

NB: I prefer to check values as explicit as possible, like
```JavaScript
t.equal(peer.portNumber, null, 'port is null');
t.equal(peer.hostAddress, null, 'host is null');
```
In this case when test fails you can see invalid values itself reported by tape instead of usually useless "expected: true, got: false".

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 859 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfGMIqmtsmliYOKRvVh:-KfGMIqnZTgPfG33vHKC:bsgah1e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/42da021f894cbaa8951553c282f57ac2ac14dd88/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L859)):*
> ```JavaScript
>       if (spy.calledOnce) {
>         t.equal(peerAvailable, true, 'peer should be available');
>         testServer.stop();
> ```

`testServer` should not be stopped here, because stop makes it emit ssdp:byebye message which in turn makes listener emit wifiPeerAvailabilityChanged event. We're testing a different scenario here, when our wifi listener does not receive advertisement messages from some peer in a TCP_PEER_UNAVAILABILITY_THRESHOLD amount of time (it happens when peer moves out of access point range and can't send any notifications). `testServer` simulates such peer by emitting advertisements with adInterval much larger than our threshold. In this case after TCP_PEER_UNAVAILABILITY_THRESHOLD passes we should get artificial peerAvailabilityChanged event with host and port set to null.

Instead it receives an event caused by `testServer`'s  "byebye" notification.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 763 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfGPEVzOIBEsW_Q9F3y:-KfGPEW-PeJ7nAFld9xQ:bmbkvm6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/42da021f894cbaa8951553c282f57ac2ac14dd88/thali/NextGeneration/thaliWifiInfrastructure.js#L763)):*
> ```JavaScript
> ThaliWifiInfrastructure.prototype._hadlePeerAvailabilityWatchers =
> function (peer) {
>   if (peer.peerAvailable) {
> ```

wifi peers don't have `peerAvailable` field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (04701a2)

**Comment by ThaliTester** [comment]
Test 110366195 (04701a2) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 110366195 build is completed (04701a2)

See https://github.com/ThaliTester/TestResults/tree/11036619504701a2_Is_thaliMobile_s_peerAvailabilityWatchers_now_just_a_plain_bug___1457_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d1b7cb9)

**Comment by ThaliTester** [comment]
Test 110366195 (d1b7cb9) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 110366195 build is completed (d1b7cb9)

See https://github.com/ThaliTester/TestResults/tree/110366195d1b7cb9_Is_thaliMobile_s_peerAvailabilityWatchers_now_just_a_plain_bug___1457_opetkevich/ for the logs

**Comment by chapko** [comment]
-@chapko +@opetkevich 

---

Reviewed 1 of 6 files at r1, 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2058 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfRDb-jzzBhT5y45lvj:-KfRDb-k_pnuZ_175rY-:b-zbwvke) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d1b7cb9a7c5426e1dad1f1daa843e8434fe321db/test/www/jxcore/bv_tests/testThaliMobile.js#L2058)):*
> ```JavaScript
>         if(spy.callCount === 2) {
>           t.equal(Object.getOwnPropertyNames(
>             ThaliMobile._peerAvailabilities[peer.connectionType]).length, 1,
> ```

It tests only latest peer. Ideally we need to check wifi peers storage and native peers storage. `connectionType` of native peers depends on platform, wifi peers have its own conection type.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 859 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfGMIqmtsmliYOKRvVh:-KfREOMIyKGjFskSmHhN:bijku1w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/42da021f894cbaa8951553c282f57ac2ac14dd88/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L859)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

`testServer` should not be stopped here, because stop makes it emit ssdp:byebye message which in turn makes listener emit wifiPeerAvailabilityChanged event. We're testing a different scenario here, when our wifi listener does not receive advertisement messages from some peer in a TCP_PEER_UNAVAILABILITY_THRESHOLD amount of time (it happens when peer moves out of access point range and can't send any notifications). `testServer` simulates such peer by emitting advertisements with adInterval much larger than our threshold. In this case after TCP_PEER_UNAVAILABILITY_THRESHOLD passes we should get artificial peerAvailabilityChanged event with host and port set to null.

Instead it receives an event caused by `testServer`'s  "byebye" notification.
</blockquote></details>

testServer still should be stopped at the end of the test.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 773 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfROPglJ5XpGxJ58Ayg:-KfROPglJ5XpGxJ58Ayh:bjepn7b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d1b7cb9a7c5426e1dad1f1daa843e8434fe321db/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L773)):*
> ```JavaScript
>           portNumber: portNumber,
>           hostAddress: '127.0.0.1',
>           availableSince: Date.now()
> ```

Why this field is required? Original WifiListener does not emit it.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 763 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfREwEeVtW-gcWEYi-g:-KfREwEeVtW-gcWEYi-h:b9ex7at) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d1b7cb9a7c5426e1dad1f1daa843e8434fe321db/thali/NextGeneration/thaliWifiInfrastructure.js#L763)):*
> ```JavaScript
> ThaliWifiInfrastructure.prototype._hadlePeerAvailabilityWatchers =
> function (peer) {
>   if (Boolean(peer.hostAddress && peer.portNumber)) {
> ```

There is no need for extra boolean cast inside of `if` statement.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 787 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfRliSk7klalDU6p4p9:-KfRliSk7klalDU6p4pA:bv7m77e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d1b7cb9a7c5426e1dad1f1daa843e8434fe321db/thali/NextGeneration/thaliWifiInfrastructure.js#L787)):*
> ```JavaScript
>   // If the time from the latest availability advertisement doesn't
>   // exceed the threshold, no need to do anything.
>   if (peer.availableSince + unavailabilityThreshold > now) {
> ```

Wifi peers do not have `availableSince` property. Right now it exists only in the ThaliMobile's cached peers.

ThaliWifiInfrastructure should have its own cache.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-:-KfRp1w2YSw8UgVszXL2:byjtkux)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (570cc5a)

**Comment by ThaliTester** [comment]
Test 110366195 (570cc5a) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 110366195 build is completed (570cc5a)

See https://github.com/ThaliTester/TestResults/tree/110366195570cc5a_Is_thaliMobile_s_peerAvailabilityWatchers_now_just_a_plain_bug___1457_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (130407f)

**Comment by ThaliTester** [comment]
Test 110366195 (130407f) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 110366195 build is completed (130407f)

See https://github.com/ThaliTester/TestResults/tree/110366195130407f_Is_thaliMobile_s_peerAvailabilityWatchers_now_just_a_plain_bug___1457_opetkevich/ for the logs

**Comment by chapko** [comment]
Reviewed 1 of 2 files at r5, 3 of 4 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2084 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfzeNeCcFLUKqpsZekv:-KfzeNeCcFLUKqpsZekw:b2n2jb4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/130407f97e0e67de65fbe0b2730c074661e89b61/test/www/jxcore/bv_tests/testThaliMobile.js#L2084)):*
> ```JavaScript
>       };
> 
>       ThaliMobile.emitter.on('peerAvailabilityChanged', availabilityHandler);
> ```

We need to unsubscribe from this event after the test.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 856 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-KfzgB9JfaKdHmakYXn1:-KfzgB9JfaKdHmakYXn2:b-w8kw0m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/130407f97e0e67de65fbe0b2730c074661e89b61/thali/NextGeneration/thaliWifiInfrastructure.js#L856)):*
> ```JavaScript
>       var assumingPeer = {
>         peerIdentifier: peerIdentifier
>       };
> ```

NB: `_isAvailabilityWatcherForPeerExist`, `_watchForPeerAvailability`, `_addAvailabilityWatcherToPeerIfNotExist`, and `_removeAvailabilityWatcherFromPeerIfExists` accept `peer` as an argument but use only `peerIdentifier` property. Changing its signature to accept only identifier would simplify it a bit and we can get rid of the dummy `assumingPeer` object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7c2daf7)

**Comment by ThaliTester** [comment]
Test 110366195 (7c2daf7) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 110366195 build is completed (7c2daf7)

See https://github.com/ThaliTester/TestResults/tree/1103661957c2daf7_Is_thaliMobile_s_peerAvailabilityWatchers_now_just_a_plain_bug___1457_opetkevich/ for the logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-:-Kg04ct_lUnR6SK3G1Xw:bnfp4nl)*

**Comment by yaronyg** [comment]
Please fix my comments (nothing earth shattering) and then :lgtm: 

---

Reviewed 1 of 6 files at r1, 1 of 2 files at r5, 2 of 4 files at r6, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 26 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-Kg0D5HDZCoRuqxTxM9a:-Kg0D5HEX1JIunzN1_Zm:bejbf2g) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7c2daf7921994e30cf014e0e178b69b5430824ae/thali/NextGeneration/thaliWifiInfrastructure.js#L26)):*
> ```JavaScript
> var enqueuedAtTop = common.enqueuedAtTopMethod;
> 
> var thaliMobileNativeWrapper = require('./thaliMobileNativeWrapper');
> ```

NB: It's good style for requires to all be together.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 774 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-Kg0DD5RXc3AaMsf3rHa:-Kg0DD5RXc3AaMsf3rHb:b-qa3xh5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7c2daf7921994e30cf014e0e178b69b5430824ae/thali/NextGeneration/thaliWifiInfrastructure.js#L774)):*
> ```JavaScript
> };
> 
> ThaliWifiInfrastructure.prototype._hadlePeerAvailabilityWatchers =
> ```

/_hadle/_handle

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 784 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-Kg0DfPsEBR7LF9UmCiW:-Kg0DfPsEBR7LF9UmCiX:b-vgv36h) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7c2daf7921994e30cf014e0e178b69b5430824ae/thali/NextGeneration/thaliWifiInfrastructure.js#L784)):*
> ```JavaScript
> };
> 
> ThaliWifiInfrastructure.prototype._isAvailabilityWatcherForPeerExist =
> ```

/_is/_does/

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 814 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-Kg0DWHEGes4Tdkphhr_:-Kg0DWHEGes4Tdkphhra:b3s9wie) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7c2daf7921994e30cf014e0e178b69b5430824ae/thali/NextGeneration/thaliWifiInfrastructure.js#L814)):*
> ```JavaScript
> 
> 
> ThaliWifiInfrastructure.prototype._addAvailabilityWatcherToPeerIfNotExist =
> ```

It's best to define functions before using them. So please hoist this method and _removeAvailabilityWatcherFromPeerIfExists before they are called in the lines above.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 817 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-Kg0HgN5Za0CP_fYom_o:-Kg0HgN6iHloMNq6WnwK:b-mchf2m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7c2daf7921994e30cf014e0e178b69b5430824ae/thali/NextGeneration/thaliWifiInfrastructure.js#L817)):*
> ```JavaScript
> function (peerIdentifier) {
>   var self = this;
>   this.peerAvailabilities.timers[peerIdentifier] = Date.now();
> ```

Please follow the rule that once self is defined it is used everywhere in the function, not just in closures. So please change the 'this' to 'self'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-:-Kg0K_KmS7_ZI1MHjDpN:b-ne4bop)*

**Comment by jareksl** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 1 of 2 files at r5, 2 of 4 files at r6, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1825#-:-KgDa7yhQkmlKBv9rr7z:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (657239b)

**Comment by ThaliTester** [comment]
Test 110366195 (657239b) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 110366195 build is completed (657239b)

See https://github.com/ThaliTester/TestResults/tree/110366195657239b_Is_thaliMobile_s_peerAvailabilityWatchers_now_just_a_plain_bug___1457_opetkevich/ for the logs

**Pull request merged**
