### PR TITLE
#697 Fixed setInterval battery abuse

### PR DESCRIPTION
**Pull request by artemjackson**
This is #851 re-submitted to `vNext_yarong_417_812`

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1108)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (c184704)

**Comment by ThaliTester** [comment]
Test (Success) 86171191 build is completed (c184704)

See https://github.com/ThaliTester/TestResults/tree/86171191c184704__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86171191c184704(c184704) has failed

See https://github.com/ThaliTester/TestResults/tree/86171191c184704__697_Fixed_setInterval_battery_abuse_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
We need tests to show that the logic works as advertised. Please see my comments.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliMobile.js, line 866 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1108#-KSJDq-XfIviHJmS4wMq:-KSJDq-XfIviHJmS4wMr:blhsbrd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c18470443f596b24855ab595f433bcbdb9a6c7c9/thali/NextGeneration/thaliMobile.js#L866)):*
> ```JavaScript
> 
> var changeCachedPeerUnavailable = function (peer) {
>   var watcherExists = isAvailabilityWatcherForPeerExist(peer);
> ```

NB: If it were me I would have defined 'addAvailabilityWatcherToPeerIfNotExist' and 'removeAvailabilityWatcherFromPeerIfExists'. That way no one can forget to check for the existence of a water before trying to add/remove.

---

*[thali/NextGeneration/thaliMobile.js, line 966 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1108#-KSJEWeLAsoYlqVErkLv:-KSJEWeMsKxxmq_Ezlbc:bk4ryuz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c18470443f596b24855ab595f433bcbdb9a6c7c9/thali/NextGeneration/thaliMobile.js#L966)):*
> ```JavaScript
> peerAvailabilityWatchers[connectionTypes.TCP_NATIVE] = {};
> 
> var addAvailabilityWatcherToPeer = function (peer) {
> ```

Don't you think it would make sense to extract the watcher code into its own object so we can easily test it?

But in any case, we really need tests to show that all of this interval logic actually works. We have to show that when we discover a peer we will eventually remove them if we don't get any more updates about their availability. We also have to show that we won't issue updates faster than we should. This can all be done with mocks to make it simpler. And you can also use the mocks to temporarily override the thresholds so the tests don't take forever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1108#-:-KSJH4_yuA1h63NduX5m:bx5r04a)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 9. task. (f99c547)

**Comment by artemjackson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliMobile.js, line 966 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1108#-KSJEWeLAsoYlqVErkLv:-KSM3yO3GZvgmHrMKEzR:b-ue72ls) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c18470443f596b24855ab595f433bcbdb9a6c7c9/thali/NextGeneration/thaliMobile.js#L966)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Don't you think it would make sense to extract the watcher code into its own object so we can easily test it?
> 
> But in any case, we really need tests to show that all of this interval logic actually works. We have to show that when we discover a peer we will eventually remove them if we don't get any more updates about their availability. We also have to show that we won't issue updates faster than we should. This can all be done with mocks to make it simpler. And you can also use the mocks to temporarily override the thresholds so the tests don't take forever.
</details>
I think it would really make sense to have a `Peer` object that should have an event like `expired`(or `unavailable`). And once `Peer`'s `expired` event is emitted one can decide what to do(e.g. remove the `Peer` from cache and emit `peerAvailabilityChanged`).
If you enjoy my idea, please, fill a new issue for that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1108)*

**Comment by ThaliTester** [comment]
Test (Fail) 86171191 build is completed (f99c547)

See https://github.com/ThaliTester/TestResults/tree/86171191f99c547__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by yaronyg** [comment]
Where are the tests to show that we properly handle peer availability?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1108#-:-KSNvHpNeFMr4ySF1elh:b-h96zpy)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (871dace)

**Comment by ThaliTester** [comment]
Test (Fail) 86171191 build is completed (871dace)

See https://github.com/ThaliTester/TestResults/tree/86171191871dace__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (806d371)

**Comment by ThaliTester** [comment]
Test (Fail) 86171191 build is completed (806d371)

See https://github.com/ThaliTester/TestResults/tree/86171191806d371__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (bdc2de2)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (96d355f)

**Comment by artemjackson** [comment]
@yaronyg Added test for peer unavailability
BTW, please leave me a feedback on the https://github.com/thaliproject/Thali_CordovaPlugin/pull/1108#issuecomment-249185925

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (508789d)

**Comment by ThaliTester** [comment]
Test (Success) 86171191 build is completed (bdc2de2)

See https://github.com/ThaliTester/TestResults/tree/86171191bdc2de2__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86171191bdc2de2(bdc2de2) has failed

See https://github.com/ThaliTester/TestResults/tree/86171191bdc2de2__697_Fixed_setInterval_battery_abuse_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86171191 build is completed (96d355f)

See https://github.com/ThaliTester/TestResults/tree/8617119196d355f__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8617119196d355f(96d355f) has failed

See https://github.com/ThaliTester/TestResults/tree/8617119196d355f__697_Fixed_setInterval_battery_abuse_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86171191 build is completed (508789d)

See https://github.com/ThaliTester/TestResults/tree/86171191508789d__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86171191508789d(508789d) has failed

See https://github.com/ThaliTester/TestResults/tree/86171191508789d__697_Fixed_setInterval_battery_abuse_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a3d4bea)

**Comment by ThaliTester** [comment]
Test (Success) 86171191 build is completed (a3d4bea)

See https://github.com/ThaliTester/TestResults/tree/86171191a3d4bea__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86171191a3d4bea(a3d4bea) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/86171191a3d4bea__697_Fixed_setInterval_battery_abuse_artemjackson/ for the logs

**Pull request merged**
