### PR TITLE
Test with new library, reconnection fix for AP & 20 minutes reconnect…

### PR DESCRIPTION
**Pull request by DrJukka**
perf testing with new library

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/322)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (165972b)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (165972b)

See https://github.com/ThaliTester/TestResults/tree/50614892165972b_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 50614892165972b(165972b) has failed

See https://github.com/ThaliTester/TestResults/tree/50614892165972b_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4ad9b7a)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (4ad9b7a)

See https://github.com/ThaliTester/TestResults/tree/506148924ad9b7a_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 506148924ad9b7a(4ad9b7a) has failed

See https://github.com/ThaliTester/TestResults/tree/506148924ad9b7a_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7461cef)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (7461cef)

See https://github.com/ThaliTester/TestResults/tree/506148927461cef_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 506148927461cef(7461cef) has failed

See https://github.com/ThaliTester/TestResults/tree/506148927461cef_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d85699e)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (d85699e)

See https://github.com/ThaliTester/TestResults/tree/50614892d85699e_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 50614892d85699e(d85699e) has failed

See https://github.com/ThaliTester/TestResults/tree/50614892d85699e_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (89c4b6e)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (89c4b6e)

See https://github.com/ThaliTester/TestResults/tree/5061489289c4b6e_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 5061489289c4b6e(89c4b6e) has failed

See https://github.com/ThaliTester/TestResults/tree/5061489289c4b6e_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (36dde33)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (36dde33)

See https://github.com/ThaliTester/TestResults/tree/5061489236dde33_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 5061489236dde33(36dde33) has failed

See https://github.com/ThaliTester/TestResults/tree/5061489236dde33_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bcf258d)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (bcf258d)

See https://github.com/ThaliTester/TestResults/tree/50614892bcf258d_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 50614892bcf258d(bcf258d) has failed

See https://github.com/ThaliTester/TestResults/tree/50614892bcf258d_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8d9a21a)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (8d9a21a)

See https://github.com/ThaliTester/TestResults/tree/506148928d9a21a_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 506148928d9a21a(8d9a21a) has failed

See https://github.com/ThaliTester/TestResults/tree/506148928d9a21a_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (574ee7b)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (574ee7b)

See https://github.com/ThaliTester/TestResults/tree/50614892574ee7b_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 50614892574ee7b(574ee7b) has failed

See https://github.com/ThaliTester/TestResults/tree/50614892574ee7b_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e3531a7)

**Comment by ThaliTester** [comment]
Test (Success) 50614892 build is completed (e3531a7)

See https://github.com/ThaliTester/TestResults/tree/50614892e3531a7_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 50614892e3531a7(e3531a7) has failed

See https://github.com/ThaliTester/TestResults/tree/50614892e3531a7_Test_with_new_library__reconnection_fix_for_AP___20_minutes_reconnect…_DrJukka/ for the fail logs

**Comment by vjrantal** [comment]
Closing this PR since these commits should be on their way to `story_001`.

**Pull request closed without merging**
