### PR TITLE
Fix race conditions in networkChanged event handling

### PR DESCRIPTION
**Pull request by chapko**
This PR fixes only part of the #1500.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1707)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (11caee1)

**Comment by ThaliTester** [comment]
Test 99674848 (11caee1) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99674848 build is completed (11caee1)

See https://github.com/ThaliTester/TestResults/tree/9967484811caee1_Fix_race_conditions_in_networkChanged_event_handling_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 9967484811caee1(11caee1) has failed

See https://github.com/ThaliTester/TestResults/tree/9967484811caee1_Fix_race_conditions_in_networkChanged_event_handling_chapko/ for the fail logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-:-K_Yjym4zfG5oz9Gg6gX:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2e8b0eb)

**Comment by ThaliTester** [comment]
Test 99674848 (2e8b0eb) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 99674848 build is completed (2e8b0eb)

See https://github.com/ThaliTester/TestResults/tree/996748482e8b0eb_Fix_race_conditions_in_networkChanged_event_handling_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8b0f149)

**Comment by ThaliTester** [comment]
Test 99674848 (8b0f149) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99674848 build is completed (8b0f149)

See https://github.com/ThaliTester/TestResults/tree/996748488b0f149_Fix_race_conditions_in_networkChanged_event_handling_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 996748488b0f149(8b0f149) has failed

See https://github.com/ThaliTester/TestResults/tree/996748488b0f149_Fix_race_conditions_in_networkChanged_event_handling_chapko/ for the fail logs

**Comment by jareksl** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[thali/NextGeneration/thaliMobile.js, line 68 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaBg7qg9Bp4a2e_eXAa:-KaBg7qg9Bp4a2e_eXAb:bnz9ogw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8b0f14976c7195b6fa52094eb3a43cd83a037420/thali/NextGeneration/thaliMobile.js#L68)):*
> ```JavaScript
>     return promiseResultSuccessOrFailure(target[method].apply(target, args));
>   };
> };
> ```

NB: The semicolon at the end of the function declaration is unnecessary. The same applies to all places where you changed function expression to function declaration.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 921 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaBlsfI2oRAayZo-OEu:-KaBlsfI2oRAayZo-OEv:b-ede7zd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8b0f14976c7195b6fa52094eb3a43cd83a037420/thali/NextGeneration/thaliMobileNativeWrapper.js#L921)):*
> ```JavaScript
> /* eslint-enable max-len */
> var peerAvailabilityChangedQueue = new PromiseQueue();
> function handlePeerAvailabilityChanged (peer) {
> ```

NB: Not needed semicolon at the end of the function declaration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707)*

**Comment by jareksl** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-:-KaBmgcPAW6Ht-SYGSfm:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (918451e)

**Comment by ThaliTester** [comment]
Test 99674848 (918451e) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 99674848 build is completed (918451e)

See https://github.com/ThaliTester/TestResults/tree/99674848918451e_Fix_race_conditions_in_networkChanged_event_handling_chapko/ for the logs

**Comment by jareksl** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f767ddb)

**Comment by ThaliTester** [comment]
Test 99674848 (f767ddb) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 99674848 build is completed (f767ddb)

See https://github.com/ThaliTester/TestResults/tree/99674848f767ddb_Fix_race_conditions_in_networkChanged_event_handling_chapko/ for the logs

**Comment by yaronyg** [comment]
Please review and fix comments.

---

Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 249 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaDsrFbyGPtiLBUdYqF:-KaDsrFbyGPtiLBUdYqG:ben2smh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f767ddb60e3d7175dff894e9cbda0becafd9b334/test/www/jxcore/bv_tests/testThaliMobile.js#L249)):*
> ```JavaScript
>     ].sort();
> 
>     var router = express.Router();
> ```

Shouldn't we have a test that proves that the race condition doesn't exist? E.g. a test that would have failed before this change but would now pass?

---

*[thali/NextGeneration/thaliMobile.js, line 126 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaDqSSMtKkdU5wL0Rxo:-KaDqSSMtKkdU5wL0Rxp:b-kfbt0t) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f767ddb60e3d7175dff894e9cbda0becafd9b334/thali/NextGeneration/thaliMobile.js#L126)):*
> ```JavaScript
> };
> 
> function resetThaliMobileState () {
> ```

NB: It's generally considered less than ideal to have functions with side effects like this. It's usually better to have a more explicit output like "thaliMobileStates = resetThaliMobileState()". That way the reader can see what's going on when the function is called. Although in this case I would probably do something like thaliMObileStates = resetThaliMobileState(thaliMobileStates.startArguments.networkType) or even resetThaliMobileState(thaliMobileStates) since you will at least need the networkType when you restart.

---

*[thali/NextGeneration/thaliMobile.js, line 126 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaDqpzALVIEs5dejotm:-KaDqpzALVIEs5dejotn:brd3xox) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f767ddb60e3d7175dff894e9cbda0becafd9b334/thali/NextGeneration/thaliMobile.js#L126)):*
> ```JavaScript
> };
> 
> function resetThaliMobileState () {
> ```

The function name should be resetThaliMobileStates in order to match the variable name.

---

*[thali/NextGeneration/thaliMobile.js, line 130 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaDpBiyNFbPiSoaTqWu:-KaDpBiz5Ith6DfAjP5f:bz3gvbw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f767ddb60e3d7175dff894e9cbda0becafd9b334/thali/NextGeneration/thaliMobile.js#L130)):*
> ```JavaScript
>   thaliMobileStates.listening = false;
>   thaliMobileStates.advertising = false;
>   thaliMobileStates.networkType = networkTypes.BOTH;
> ```

Since we depend on this being set in the start call shouldn't we set networkType to null?

---

*[thali/NextGeneration/thaliMobile.js, line 235 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaDsbcggKXJRV2McPAc:-KaDsbcggKXJRV2McPAd:ba6wk8b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f767ddb60e3d7175dff894e9cbda0becafd9b334/thali/NextGeneration/thaliMobile.js#L235)):*
> ```JavaScript
>     thaliMobileStates.startArguments.router = router;
>     thaliMobileStates.startArguments.pskIdToSecret = pskIdToSecret;
>     thaliMobileStates.startArguments.networkType = networkType;
> ```

It probably wouldn't be a bad idea to make sure that actual values were passed in. E.g. that the args aren't null.

---

*[thali/NextGeneration/thaliMobile.js, line 1374 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaDrkpoqrkPGSIReLZP:-KaDrkpoqrkPGSIReLZQ:b-cw8usl) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f767ddb60e3d7175dff894e9cbda0becafd9b334/thali/NextGeneration/thaliMobile.js#L1374)):*
> ```JavaScript
>   var androidNativeDisabled =
>     networkChangedValue.bluetooth === 'off' &&
>     networkChangedValue.bluetoothLowEnergy === 'off';
> ```

This has to be an 'or' not an 'and' because if either is turned off then we can't work properly. Note that as far as I'm aware it's literally impossible in Android for these values to have different settings but still, it should be an OR.

---

*[thali/NextGeneration/thaliMobile.js, line 1377 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-KaDrdQA_CbuJ_xXFq4W:-KaDrdQA_CbuJ_xXFq4X:b-jvv5aa) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f767ddb60e3d7175dff894e9cbda0becafd9b334/thali/NextGeneration/thaliMobile.js#L1377)):*
> ```JavaScript
>   var iOSNativeDisabled =
>     networkChangedValue.wifi === 'off' &&
>     networkChangedValue.bluetooth === 'off';
> ```

Strictly speaking we require both wifi and bluetooth to be on (we should work with only one but we don't test that) so I wonder if this shouldn't be an or rather than an and.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1707#-:-KaDt1S_npihEl9uu9k0:be9pn7z)*

**Comment by yaronyg** [comment]
I'm confused. This bug was even assigned to me. How did it get merged without my LGTM?

**Pull request merged**
