### PR TITLE
Wifi Managing

### PR DESCRIPTION
**Pull request by yaronyg**
thaliMobileNative - Defining that network state must also check for SSID
and adding a method to turn WiFi on and off.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1315)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (054bc21)

**Comment by ThaliTester** [comment]
Test (Success) 89303851 build is completed (054bc21)

See https://github.com/ThaliTester/TestResults/tree/89303851054bc21_Wifi_Managing_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 89303851054bc21(054bc21) has failed

See https://github.com/ThaliTester/TestResults/tree/89303851054bc21_Wifi_Managing_yaronyg/ for the fail logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1315#-:-KU2iHBXp5GV1JrKgsXx:bnfp4nl)*

**Pull request merged**
