### PR TITLE
Fixed test server reconnection

### LINKED ISSUE #1530: Change tests like "network changes emitted correctly", "network changes not emitted in started state" and "calls correct starts when network changes" in thaliMobileTest
The logic we use to talk to the coordination server doesn't seem to handle the case where we turn off and then turn wifi back on. The reconnection logic doesn't figure out that wifi is back. So we have to fix that before we can run these tests.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1530. Related to https://github.com/thaliproject/CI/issues/97.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1712)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1ba0a10)

**Comment by ThaliTester** [comment]
Test 100494657 (1ba0a10) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 100494657 build is completed (1ba0a10)

See https://github.com/ThaliTester/TestResults/tree/1004946571ba0a10_Fixed_test_server_reconnection_andrew-aladev/ for the logs

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1712#-:-Ka7OMnjQmSG2_EACuG0:bg7igkv)*

**Comment by mlesnic** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1712#-:-Ka7cQ5kODJ5l3dP7MYd:bnfp4nl)*

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1712)*

**Pull request merged**
