### PR TITLE
Fix wrong test report results for native and node tests

### PR DESCRIPTION
**Pull request by czyzm**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1223)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (a0b8240)

**Comment by ThaliTester** [comment]
Test (Fail) 87463757 build is completed (a0b8240)

See https://github.com/ThaliTester/TestResults/tree/87463757a0b8240_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (dc979f8)

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (dc979f8)

See https://github.com/ThaliTester/TestResults/tree/87463757dc979f8_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 87463757dc979f8(dc979f8) has failed

See https://github.com/ThaliTester/TestResults/tree/87463757dc979f8_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (544e7bf)

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (544e7bf)

See https://github.com/ThaliTester/TestResults/tree/87463757544e7bf_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 87463757544e7bf(544e7bf) has failed

See https://github.com/ThaliTester/TestResults/tree/87463757544e7bf_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ce3bfc1)

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (ce3bfc1)

See https://github.com/ThaliTester/TestResults/tree/87463757ce3bfc1_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 87463757ce3bfc1(ce3bfc1) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/87463757ce3bfc1_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (be36154)

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (be36154)

See https://github.com/ThaliTester/TestResults/tree/87463757be36154_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 87463757be36154(be36154) has failed

See https://github.com/ThaliTester/TestResults/tree/87463757be36154_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (97cf15f)

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (97cf15f)

See https://github.com/ThaliTester/TestResults/tree/8746375797cf15f_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 8746375797cf15f(97cf15f) has failed

See https://github.com/ThaliTester/TestResults/tree/8746375797cf15f_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the fail logs

**Comment by andrew-aladev** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/TestServer/UnitTestFramework.js, line 90 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSvT20MBQtKof5LmH3L:-KSvT20MBQtKof5LmH3M:b-3w48i7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/TestServer/UnitTestFramework.js#L90)):*
> ```JavaScript
>       devices.map(function (device) {
>         return device.error(error)
>           .catch(function (error) {
> ```

log 'unexpected error' wants to be here.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 181 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSvUtInS_X3MOA6Y8tL:-KSvUtInS_X3MOA6Y8tM:b-omwvjg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/www/jxcore/lib/CoordinatedClient.js#L181)):*
> ```JavaScript
>   this._emit('disqualify_confirmed', data)
>   .then(function () {
>     if (data) {
> ```

'data.content' will be an error

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 200 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSvUD1MD2xu1qpTNSxd:-KSvUD1MD2xu1qpTNSxe:bmuu37m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/www/jxcore/lib/CoordinatedClient.js#L200)):*
> ```JavaScript
>   });
> 
>   if (!data) {
> ```

Device will be disconnected anyway, we can wait for 'disconnect'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 6 of 7 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-:-KSvV6P4oSjRPwW7rMt5:bnfp4nl)*

**Comment by yaronyg** [comment]
Please fix Andrew's comments and my NB but otherwise :lgtm: 

---

Reviewed 1 of 1 files at r3, 6 of 7 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/lib/SimpleTape.js, line 236 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSwkuzx7CuibvShyInQ:-KSwkuzygW6HsRvDkKzr:bmi09bs) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/www/jxcore/lib/SimpleTape.js#L236)):*
> ```JavaScript
> }
> 
> SimpleThaliTape.begin = function (platform, version, hasRequiredHardware, nativeUTFailed) {
> ```

NB: What's the point of submitting an argument that isn't ever used?

Since we presumably don't ever use this argument since SimpleTape is, I believe, only run on the desktop then shouldn't we at least have some kind of assert that requires the value to be null or at least false?

We have to at least put in a comment so that future devs won't be confused why we have a useless argument.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-:-KSwm7KSYQ-7iktYzYWc:b-i0tovt)*

**Comment by czyzm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 200 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSvUD1MD2xu1qpTNSxd:-KT80BhoaHaDz4pXi03U:bendlnz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/www/jxcore/lib/CoordinatedClient.js#L200)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary>
> Device will be disconnected anyway, we can wait for 'disconnect'.
</details>
Yes, but we cannot set state to completed because if disconnect comes earlier than we fail the test (log EXIT_FAILED) it is possible that we will log EXIT_SUCCESS earlier (in disconnect we are checking the state).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d089d64)

**Comment by czyzm** [comment]
Review status: 5 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/TestServer/UnitTestFramework.js, line 90 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSvT20MBQtKof5LmH3L:-KT85zvJzHu5Nv2QzV-q:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/TestServer/UnitTestFramework.js#L90)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary>
> log 'unexpected error' wants to be here.
</details>
Done.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 181 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSvUtInS_X3MOA6Y8tL:-KT85z9cTXqSPldCvwyT:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/www/jxcore/lib/CoordinatedClient.js#L181)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary>
> 'data.content' will be an error
</details>
Done.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 200 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSvUD1MD2xu1qpTNSxd:-KT85yYD3u3dksrVko4e:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/www/jxcore/lib/CoordinatedClient.js#L200)):*
<details><summary><i>Previously, czyzm wrote…</i></summary>
> Yes, but we cannot set state to completed because if disconnect comes earlier than we fail the test (log EXIT_FAILED) it is possible that we will log EXIT_SUCCESS earlier (in disconnect we are checking the state).
</details>
Done.

---

*[test/www/jxcore/lib/SimpleTape.js, line 236 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-KSwkuzx7CuibvShyInQ:-KT85vlAKEvO-8NDjxDI:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/97cf15f6d39b5a8d88cb5992e21a1805ee9d715d/test/www/jxcore/lib/SimpleTape.js#L236)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: What's the point of submitting an argument that isn't ever used?
> 
> Since we presumably don't ever use this argument since SimpleTape is, I believe, only run on the desktop then shouldn't we at least have some kind of assert that requires the value to be null or at least false?
> 
> We have to at least put in a comment so that future devs won't be confused why we have a useless argument.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223)*

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (d089d64)

See https://github.com/ThaliTester/TestResults/tree/87463757d089d64_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e83b1c3)

**Comment by ThaliTester** [comment]
Test 87463757d089d64(d089d64) has failed

See https://github.com/ThaliTester/TestResults/tree/87463757d089d64_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (e83b1c3)

See https://github.com/ThaliTester/TestResults/tree/87463757e83b1c3_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 87463757e83b1c3(e83b1c3) has failed

See https://github.com/ThaliTester/TestResults/tree/87463757e83b1c3_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d4cf5de)

**Comment by ThaliTester** [comment]
Test (Fail) 87463757 build is completed (d4cf5de)

See https://github.com/ThaliTester/TestResults/tree/87463757d4cf5de_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b7a6f39)

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (b7a6f39)

See https://github.com/ThaliTester/TestResults/tree/87463757b7a6f39_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 87463757b7a6f39(b7a6f39) has failed

See https://github.com/ThaliTester/TestResults/tree/87463757b7a6f39_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (58c0eee)

**Comment by ThaliTester** [comment]
Test (Success) 87463757 build is completed (58c0eee)

See https://github.com/ThaliTester/TestResults/tree/8746375758c0eee_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 8746375758c0eee(58c0eee) has failed

See https://github.com/ThaliTester/TestResults/tree/8746375758c0eee_Fix_wrong_test_report_results_for_native_and_node_tests_czyzm/ for the fail logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r7, 1 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1223#-:-KT8v55BwcY9a3KoNkZw:bnfp4nl)*

**Pull request merged**
