### PR TITLE
added an ssdp ip option

### LINKED ISSUE #1631: Need to change our SSDP address
Once thaliproject/Thali_CordovaPlugin#1620 is fixed then we need to change the port we use in UDP for SSDP to take advantage of it.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1631.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1669)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f5a8923)

**Comment by ThaliTester** [comment]
Test 98934583 (f5a8923) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 98934583 build is completed (f5a8923)

See https://github.com/ThaliTester/TestResults/tree/98934583f5a8923_added_an_ssdp_ip_option_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1669#-:-KZXVJncxTbXtJQhirXi:bnfp4nl)*

**Comment by chapko** [comment]
:lgtm:
-@chapko

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1669#-:-KZXa_drwFltBspIssR-:bbzl9c4)*

**Pull request merged**
