### PR TITLE
Updated express version and commit id

### LINKED ISSUE #1480: Update express-pouchdb version and commit id

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1480.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1481)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a7da9b2)

**Comment by ThaliTester** [comment]
Test (Success) 92192157 build is completed (a7da9b2)

See https://github.com/ThaliTester/TestResults/tree/92192157a7da9b2_Updated_express_version_and_commit_id_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 92192157a7da9b2(a7da9b2) has failed

See https://github.com/ThaliTester/TestResults/tree/92192157a7da9b2_Updated_express_version_and_commit_id_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1481#-:-KVgDZj8twZnUZhueY6X:bnfp4nl)*

**Pull request merged**
