### PR TITLE
Story 001 tompaana 387

### PR DESCRIPTION
**Pull request by tompaana**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/388)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (66a890e)

**Comment by ThaliTester** [comment]
Test (Success) 53574507 build is completed (66a890e)

See https://github.com/ThaliTester/TestResults/tree/5357450766a890e_Story_001_tompaana_387_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 5357450766a890e(66a890e) has failed

See https://github.com/ThaliTester/TestResults/tree/5357450766a890e_Story_001_tompaana_387_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 53574507 has failed

See https://gist.github.com/19ce8236feb537f323b3 for the fail logs

**Comment by ThaliTester** [comment]
Test 53574507 build process is completed

See https://gist.github.com/94c290dd8f9d1ad54ac7 for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3fd4dd1)

**Comment by ThaliTester** [comment]
Test (Success) 53574507 build is completed (3fd4dd1)

See https://github.com/ThaliTester/TestResults/tree/535745073fd4dd1_Story_001_tompaana_387_tompaana/ for the logs

**Comment by tobybrad** [comment]
Reviewed 9 of 9 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/388)*

**Pull request merged**
