### PR TITLE
Update mobile_test.json

### PR DESCRIPTION
**Pull request by jareksl**
Update mobile_test.json to reflect changes done on CI

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1887)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (50351fa)

**Comment by ThaliTester** [comment]
Test 123041334 (50351fa) build started.

**Comment by ThaliTester** [comment]
Test (Success) 123041334 build is completed (50351fa)

See https://github.com/ThaliTester/TestResults/tree/12304133450351fa_Update_mobile_test_json_jareksl/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1887#-:-KlUWKjBG7Zh4005Rho0:bnfp4nl)*

**Pull request merged**
