### PR TITLE
#1665 Fix "Test 'update peer discovery 1' fails on desktop and phones in iOS branch"

### PR DESCRIPTION
**Pull request by chapko**
I have just reverted test to the [`217da85`](https://github.com/thaliproject/Thali_CordovaPlugin/blob/217da85a30ece5133725f208c83e9e0b1ce3c46d/test/www/jxcore/bv_tests/testThaliMobileNativeDiscoveryCoordinated.js) commit and removed test timeout

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1667)

### CODE REVIEW

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1667#-:-KZWZJgbUu-o9wIAu26S:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeDiscoveryCoordinated.js, line 13 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1667#-KZXTNMMvUpJHn8zrx5B:-KZXTNMNP5nY9yTZipu3:b-asvobj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8d355026ddd9613984706ccf4ec8cbcddd7c7678/test/www/jxcore/bv_tests/testThaliMobileNativeDiscoveryCoordinated.js#L13)):*
> ```JavaScript
> }
> 
> // var platform = require('thali/NextGeneration/utils/platform');
> ```

NB: Why comment out this line? Why not just delete it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1667#-:-KZXTdjW8_dz-A5P4lCG:bg7igkv)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a6d9d3f)

**Comment by ThaliTester** [comment]
Test 98912682 (a6d9d3f) build started.

**Comment by chapko** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeDiscoveryCoordinated.js, line 13 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1667#-KZXTNMMvUpJHn8zrx5B:-KZXX9ocdH3-2yN0_X8e:bz59pcn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8d355026ddd9613984706ccf4ec8cbcddd7c7678/test/www/jxcore/bv_tests/testThaliMobileNativeDiscoveryCoordinated.js#L13)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

NB: Why comment out this line? Why not just delete it?
</blockquote></details>

I initially commented it out to suppress linter warnings but then forgot to remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1667)*

**Comment by ThaliTester** [comment]
Test (Success) 98912682 build is completed (a6d9d3f)

See https://github.com/ThaliTester/TestResults/tree/98912682a6d9d3f__1665_Fix__Test__update_peer_discovery_1__fails_on_desktop_and_phones_in_iOS_branch__chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 98912682a6d9d3f(a6d9d3f) has failed

See https://github.com/ThaliTester/TestResults/tree/98912682a6d9d3f__1665_Fix__Test__update_peer_discovery_1__fails_on_desktop_and_phones_in_iOS_branch__chapko/ for the fail logs

**Pull request merged**
