### PR TITLE
Updated BtLib to 0.3.5

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1478)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e76fa0e)

**Comment by ThaliTester** [comment]
Test (Success) 92126221 build is completed (e76fa0e)

See https://github.com/ThaliTester/TestResults/tree/92126221e76fa0e_Updated_BtLib_to_0_3_5_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 92126221e76fa0e(e76fa0e) has failed

See https://github.com/ThaliTester/TestResults/tree/92126221e76fa0e_Updated_BtLib_to_0_3_5_evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
@yaronyg fyi, I merged this into master

**Pull request merged**
