### PR TITLE
DO_NOT_MERGE A new ThaliTestRunner

### PR DESCRIPTION
**Pull request by artemjackson**
This could be a cleaner implementation of ThaliTestRunner.

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1014)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (b22d743)

**Comment by ThaliTester** [comment]
Test (Success) 84656631 build is completed (b22d743)

See https://github.com/ThaliTester/TestResults/tree/84656631b22d743_DO_NOT_MERGE_A_new_ThaliTestRunenr_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 84656631b22d743(b22d743) has failed

See https://github.com/ThaliTester/TestResults/tree/84656631b22d743_DO_NOT_MERGE_A_new_ThaliTestRunenr_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2816b3f)

**Comment by ThaliTester** [comment]
Test (Fail) 84656631 build is completed (2816b3f)

See https://github.com/ThaliTester/TestResults/tree/846566312816b3f_DO_NOT_MERGE_A_new_ThaliTestRunner_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (8ce6636)

**Comment by ThaliTester** [comment]
Test (Success) 84656631 build is completed (8ce6636)

See https://github.com/ThaliTester/TestResults/tree/846566318ce6636_DO_NOT_MERGE_A_new_ThaliTestRunner_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 846566318ce6636(8ce6636) has failed

See https://github.com/ThaliTester/TestResults/tree/846566318ce6636_DO_NOT_MERGE_A_new_ThaliTestRunner_artemjackson/ for the fail logs

**Comment by artemjackson** [comment]
Keep it for a better time.

**Pull request closed without merging**
