### PR TITLE
V next avsyuchenya 946 test

### PR DESCRIPTION
**Pull request by baydet**
DO NOT MERGE

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1110)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (fb2e98f)

**Comment by ThaliTester** [comment]
Test (Fail) 86174379 build is completed (fb2e98f)

See https://github.com/ThaliTester/TestResults/tree/86174379fb2e98f_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (025e6ea)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (abea55c)

**Comment by ThaliTester** [comment]
Test (Fail) 86174379 build is completed (025e6ea)

See https://github.com/ThaliTester/TestResults/tree/86174379025e6ea_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86174379 build is completed (abea55c)

See https://github.com/ThaliTester/TestResults/tree/86174379abea55c_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 86174379abea55c(abea55c) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/86174379abea55c_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (72ae596)

**Comment by ThaliTester** [comment]
Test (Success) 86174379 build is completed (72ae596)

See https://github.com/ThaliTester/TestResults/tree/8617437972ae596_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 8617437972ae596(72ae596) has failed

See https://github.com/ThaliTester/TestResults/tree/8617437972ae596_V_next_avsyuchenya_946_test_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0af7a74)

**Comment by ThaliTester** [comment]
Test (Success) 86174379 build is completed (0af7a74)

See https://github.com/ThaliTester/TestResults/tree/861743790af7a74_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 861743790af7a74(0af7a74) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/861743790af7a74_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (51c5913)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (d95f7ab)

**Comment by ThaliTester** [comment]
Test (Success) 86174379 build is completed (51c5913)

See https://github.com/ThaliTester/TestResults/tree/8617437951c5913_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 8617437951c5913(51c5913) has failed

See https://github.com/ThaliTester/TestResults/tree/8617437951c5913_V_next_avsyuchenya_946_test_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86174379 build is completed (d95f7ab)

See https://github.com/ThaliTester/TestResults/tree/86174379d95f7ab_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 86174379d95f7ab(d95f7ab) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/86174379d95f7ab_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (6628be0)

**Comment by baydet** [comment]
in #1136 required logging is added. No need for this PR now

**Comment by ThaliTester** [comment]
Test (Success) 86174379 build is completed (6628be0)

See https://github.com/ThaliTester/TestResults/tree/861743796628be0_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 861743796628be0(6628be0) has failed

See https://github.com/ThaliTester/TestResults/tree/861743796628be0_V_next_avsyuchenya_946_test_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (2a210c8)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (64e1086)

**Comment by ThaliTester** [comment]
Test (Success) 86174379 build is completed (2a210c8)

See https://github.com/ThaliTester/TestResults/tree/861743792a210c8_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 861743792a210c8(2a210c8) has failed

See https://github.com/ThaliTester/TestResults/tree/861743792a210c8_V_next_avsyuchenya_946_test_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86174379 build is completed (64e1086)

See https://github.com/ThaliTester/TestResults/tree/8617437964e1086_V_next_avsyuchenya_946_test_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 8617437964e1086(64e1086) has failed

See https://github.com/ThaliTester/TestResults/tree/8617437964e1086_V_next_avsyuchenya_946_test_baydet/ for the fail logs

**Pull request closed without merging**
