### PR TITLE
Fixed typos and cases in js files

### LINKED ISSUE #817: Fix casing issue in GIT
- [x] Use MV to fix the casing of thalilogger to be thaliLogger
- [x] Fix the calls in require in node for thaliLogger to be properly cased (just to be clean)
- [x] Update the [dev handbook](https://github.com/thaliproject/thali/blob/gh-pages/pages/documentation/DeveloperHandbook.md) to tell people to set core.ignorecase in Git to false

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/825)

Fixed #817

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4e41806)

**Comment by ThaliTester** [comment]
Test (Success) 79880594 build is completed (4e41806)

See https://github.com/ThaliTester/TestResults/tree/798805944e41806_Fixed_typos_and_cases_in_js_files_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 798805944e41806(4e41806) has failed

See https://github.com/ThaliTester/TestResults/tree/798805944e41806_Fixed_typos_and_cases_in_js_files_evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

NOTE: I am assuming that you have run jx npm test, jx npm run test-meta, and jx npm run test-coordinated successfully on your desktop. If not please don't merge until you do.

---

Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/README.md, line 53 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/825#-KOIW8DPm6r4ukmxIa8i:-KOIW8DPm6r4ukmxIa8j:-1501572996) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4e4180622d224560128ca2cfe76c5c9fea1b52bb/test/README.md#L53)):*
> ```Markdown
> to stage our custom releases. This requires the following manual steps:
> 
> 1. `npm install -g sinopia`. If you get some errors, try to install via
> ```

NB: /some errors/errors/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/825#-:-KOIWYHxxmiY4eyRlAVy:-1649491890)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (4404966)

**Comment by ThaliTester** [comment]
Test (Fail) 79880594 build is completed (4404966)

See https://github.com/ThaliTester/TestResults/tree/798805944404966_Fixed_typos_and_cases_in_js_files_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9e36f59)

**Comment by ThaliTester** [comment]
Test (Success) 79880594 build is completed (9e36f59)

See https://github.com/ThaliTester/TestResults/tree/798805949e36f59_Fixed_typos_and_cases_in_js_files_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 798805949e36f59(9e36f59) has failed

See https://github.com/ThaliTester/TestResults/tree/798805949e36f59_Fixed_typos_and_cases_in_js_files_evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
Review status: 23 of 26 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/README.md, line 53 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/825#-KOIW8DPm6r4ukmxIa8i:-KOKJGcVnx9s8AZcl1MX:1758359675) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4e4180622d224560128ca2cfe76c5c9fea1b52bb/test/README.md#L53)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: /some errors/errors/
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/825)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/825#-:-KOMLARc2BrD3pUdayRh:1417088721)*

**Pull request merged**
