### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by vjrantal**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/694)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b7d3db0)

**Comment by ThaliTester** [comment]
Test (Success) 64941069 build is completed (b7d3db0)

See https://github.com/ThaliTester/TestResults/tree/64941069b7d3db0_Minor_fixes_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 64941069b7d3db0(b7d3db0) has failed

See https://github.com/ThaliTester/TestResults/tree/64941069b7d3db0_Minor_fixes_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/694#-:-KEI0l9BTqOru3UTVTkU:1417088721)*

**Pull request merged**
