### PR TITLE
Revert custom NSRunLoop implementation to fix EXC_BAD_ACCESS in VirtualSocket.swift

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1808)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7bc6633)

**Comment by ThaliTester** [comment]
Test 107215755 (7bc6633) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 107215755 build is completed (7bc6633)

See https://github.com/ThaliTester/TestResults/tree/1072157557bc6633_Revert_custom_NSRunLoop_implementation_to_fix_EXC_BAD_ACCESS_in_VirtualSocket_swift_dersim-davaod/ for the logs

**Comment by chapko** [comment]
Native tests are failing on iOS 10 devices. Logs:
- [1.log](https://gist.github.com/chapko/ef515c2ec52729dcd7239307057f8bfa/raw/3f8b6e35e1a42eeeaa07eb5404998d29272c0a55/1.log)
- [2.log](https://gist.github.com/chapko/ef515c2ec52729dcd7239307057f8bfa/raw/3f8b6e35e1a42eeeaa07eb5404998d29272c0a55/2.log)
- [3.log](https://gist.github.com/chapko/ef515c2ec52729dcd7239307057f8bfa/raw/3f8b6e35e1a42eeeaa07eb5404998d29272c0a55/3.log)

**Comment by dersim-davaod** [comment]
This PR is the one among others that fix issues in iOS native layer.

**Comment by yaronyg** [comment]
@dersim-davaod Please see comments.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 78 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1808#-Ke04GDukkpbGWTGM-S8:-Ke04GDukkpbGWTGM-S9:b-qkvpyr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7bc6633a39ef9f356b550985e085836e76da8422/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L78)):*
> ```Swift
> 
>     if !outputStream.hasSpaceAvailable {
>       pendingDataToWrite?.appendData(data)
> ```

What happens if pendingDataToWrite is null? It will look like we wrote the data when we didn't.

---

*[lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift, line 90 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1808#-Ke05VFmFlObKH7J90kD:-Ke05VFmFlObKH7J90kE:b-9qef0e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7bc6633a39ef9f356b550985e085836e76da8422/lib/ios/ThaliCore/ThaliCore/SocketConnection/VirtualSocket.swift#L90)):*
> ```Swift
>     let bytesWritten = outputStream.write(buffer, maxLength: dataLength)
>     if bytesWritten < 0 {
>       closeStreams()
> ```

Shouldn't there be some kind of error handling here? We are after all dealing with a write failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1808#-:-Ke05f5-iK0M5Wz0SgLp:b8pciry)*

**Pull request merged**
