### PR TITLE
Avoid emitting peer unavailable from self

### PR DESCRIPTION
**Pull request by vjrantal**
Relates to #678.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/680)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d6e7601)

**Comment by ThaliTester** [comment]
Test (Success) 64423763 build is completed (d6e7601)

See https://github.com/ThaliTester/TestResults/tree/64423763d6e7601_Avoid_emitting_peer_unavailable_from_self_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 64423763d6e7601(d6e7601) has failed

See https://github.com/ThaliTester/TestResults/tree/64423763d6e7601_Avoid_emitting_peer_unavailable_from_self_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 217 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/680#-KE2gRvTIKrq5nMoNrTK:-KE2gRvTIKrq5nMoNrTL:-248609114) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d6e7601dbbb0c7e7a43a2c458771cfc364332171/thali/NextGeneration/thaliWifiInfrastructure.js#L217)):*
Imagine we have a done of simultaneous replications. We would be changing the beacon at the limit of the time window (ever couple hundred MS). My best is that we easily can end up with way more than one old USN floating in the air.

An alternative approach could be look at the location in the announcement. If it is pointing to the current IP and port we are using and isn't using our current USN then shouldn't we assume it is old and ignore it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/680)*

**Comment by yaronyg** [comment]
Per filing the bug as discussed on slack :lgtm:

**Comment by yaronyg** [comment]
:+1:

**Comment by yaronyg** [comment]
:shipit: 

I thought :lgtm: was a github think but I guess it's just reviewable

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 217 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/680#-KE2gRvTIKrq5nMoNrTK:-KE58WQZABCcgdS9ckHm:1953755948) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d6e7601dbbb0c7e7a43a2c458771cfc364332171/thali/NextGeneration/thaliWifiInfrastructure.js#L217)):*
Done.

Agreed to handle this offline from this PR under this issue https://github.com/thaliproject/Thali_CordovaPlugin/issues/684.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/680)*

**Pull request merged**
