### PR TITLE
Story 001 tompaana 371

### PR DESCRIPTION
**Pull request by tompaana**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/374)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c7b67a5)

**Comment by ThaliTester** [comment]
Test (Success) 52971095 build is completed (c7b67a5)

See https://github.com/ThaliTester/TestResults/tree/52971095c7b67a5_Story_001_tompaana_371_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 52971095c7b67a5(c7b67a5) has failed

See https://github.com/ThaliTester/TestResults/tree/52971095c7b67a5_Story_001_tompaana_371_tompaana/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/OutgoingSocketThread.java, line 17 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374#-K50gAZ9m5rSpqn9sMDG:-K50gAZ9m5rSpqn9sMDH:-1954229268) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c7b67a5f8fc329c871f36619cca009ebc09be6d9/src/android/java/io/jxcore/node/OutgoingSocketThread.java#L17)):*
Would it be possible to refactor the code so that the notification is done after the blocking accept-call returns?

---

*[thali/install/setUpTests.sh, line 35 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374#-K50h2-glI9Jz05nSlEN:-K50h2-hRJj8rG3PdRB4:-1425382190) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c7b67a5f8fc329c871f36619cca009ebc09be6d9/thali/install/setUpTests.sh#L35)):*
I was wondering about why the behavior differs on Windows and why is the build process aborted - do you know?

---

*[thali/install/setUpTests.sh, line 59 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374#-K50gsd1E87QPkq1TobS:-K50gsd1E87QPkq1TobT:-1749215069) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c7b67a5f8fc329c871f36619cca009ebc09be6d9/thali/install/setUpTests.sh#L59)):*
The result of this check could be assigned to a variable in the beginning of the script to avoid repetition.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374)*

**Comment by tompaana** [comment]
*[src/android/java/io/jxcore/node/OutgoingSocketThread.java, line 17 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374#-K50gAZ9m5rSpqn9sMDG:-K511EMCbUmd7PRUB2oR:-1470121834) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c7b67a5f8fc329c871f36619cca009ebc09be6d9/src/android/java/io/jxcore/node/OutgoingSocketThread.java#L17)):*
No, because the notification is for the Node layer to know when to connect.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374)*

**Comment by tompaana** [comment]
*[thali/install/setUpTests.sh, line 59 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374#-K50gsd1E87QPkq1TobS:-K511fW1p5AfL8xEhNP9:-484273573) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c7b67a5f8fc329c871f36619cca009ebc09be6d9/thali/install/setUpTests.sh#L59)):*
True.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374)*

**Comment by tompaana** [comment]
*[thali/install/setUpTests.sh, line 35 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374#-K50h2-glI9Jz05nSlEN:-K511hhsNmfryH0YD0df:1915522035) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c7b67a5f8fc329c871f36619cca009ebc09be6d9/thali/install/setUpTests.sh#L35)):*
The original copy command on Windows leads to path www/www/jxcore. On MinGW '-delete' is not valid.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (ef317fc)

**Comment by ThaliTester** [comment]
Test (Success) 52971095 build is completed (ef317fc)

See https://github.com/ThaliTester/TestResults/tree/52971095ef317fc_Story_001_tompaana_371_tompaana/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (c1e9930)

**Comment by ThaliTester** [comment]
Test (Success) 52971095 build is completed (c1e9930)

See https://github.com/ThaliTester/TestResults/tree/52971095c1e9930_Story_001_tompaana_371_tompaana/ for the logs

**Comment by vjrantal** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/374)*

**Comment by ThaliTester** [comment]
Test 52971095ef317fc(ef317fc) has failed

See https://github.com/ThaliTester/TestResults/tree/52971095ef317fc_Story_001_tompaana_371_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
Test 52971095c1e9930(c1e9930) has failed

See https://github.com/ThaliTester/TestResults/tree/52971095c1e9930_Story_001_tompaana_371_tompaana/ for the fail logs

**Pull request merged**
