### PR TITLE
Story 001 juksilve

### PR DESCRIPTION
**Pull request by DrJukka**
Got successfull CI rounds with unit & perf tests, thus this branch would be ready for merge.

perftest: https://github.com/ThaliTester/TestResults/tree/4860079788277ed_Story_001_juksilve_DrJukka/

unittest: https://github.com/ThaliTester/TestResults/tree/48600797fb45cde_Story_001_juksilve_DrJukka/

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/292)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (88277ed)

**Comment by ThaliTester** [comment]
Test (Success) 49863886 build is completed (88277ed)

See https://github.com/ThaliTester/TestResults/tree/4986388688277ed_Story_001_juksilve_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 4986388688277ed(88277ed) has failed

See https://github.com/ThaliTester/TestResults/tree/4986388688277ed_Story_001_juksilve_DrJukka/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4147f5a)

**Comment by ThaliTester** [comment]
Test (Fail) 49863886 build is completed (4147f5a)

See https://github.com/ThaliTester/TestResults/tree/498638864147f5a_Story_001_juksilve_DrJukka/ for the logs

**Comment by tobybrad** [comment]
Reviewed 29 of 31 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[test/www/jxcore/package.json, line 38 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292#-K2mQexiX0uVcSGOAoLO)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4147f5aaae16062607c72758621d03d214219fc9/test/www/jxcore/package.json#L38)):</sup>
Looks like some building work that didn't get cleaned up.


---

<sup>**[test/www/jxcore/perf_tests/PerfTestFramework.js, line 34 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292#-K2mQouDf9jZR-rFHbgQ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4147f5aaae16062607c72758621d03d214219fc9/test/www/jxcore/perf_tests/PerfTestFramework.js#L34)):</sup>
Are you absolutely sure this './' shouldn't be __dirname (which is always absolute) ??


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292)

**Comment by tobybrad** [comment]
Reviewed. just the leaked DOS path I think to fix.

**Comment by tobybrad** [comment]
Oh.. one overall comment.. all the 'test' commits'. If they're just to trigger CI then can we please have  commit message to reflect that. If they're something else.. *please* try and call them something meaningful.

**Comment by DrJukka** [comment]
I suppose should go with two branch strategy, with the branch there was loads of CI testing included, including re-tries when CI build failed. I think those commits should have just had one word 'test' as a comment.


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[test/www/jxcore/package.json, line 38 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292#-K2mQexiX0uVcSGOAoLO)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4147f5aaae16062607c72758621d03d214219fc9/test/www/jxcore/package.json#L38)):</sup>
That happens with Windows builds, right after the "jx npm install C:/a/test/Thali_CordovaPlugin/thali --save --autoremove "*.gz" line, generally scripts are not working with Windows.

So how does that look with MAC, and should we actually open a bug for fixing it ?


---

<sup>**[test/www/jxcore/perf_tests/PerfTestFramework.js, line 34 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292#-K2mQouDf9jZR-rFHbgQ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4147f5aaae16062607c72758621d03d214219fc9/test/www/jxcore/perf_tests/PerfTestFramework.js#L34)):</sup>
As far as I understand it, the readdirSync requires the __dirname to locate the folder with full path

But, in this line we have the require, and it works with './', since it just needs to know where the files are related to the folder this file is.

With Android at least this works exactly as expected, do we have other kind of behavior with iOS ?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292)

**Comment by DrJukka** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[test/www/jxcore/package.json, line 38 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292#-K2mQexiX0uVcSGOAoLO)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4147f5aaae16062607c72758621d03d214219fc9/test/www/jxcore/package.json#L38)):</sup>
That happens with Windows builds, right after the "jx npm install C:/a/test/Thali_CordovaPlugin/thali --save --autoremove "*.gz" line, generally scripts are not working with Windows.

So how does that look with MAC, and should we actually open a bug for fixing it ?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292)

**Comment by DrJukka** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[test/www/jxcore/perf_tests/PerfTestFramework.js, line 34 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292#-K2mQouDf9jZR-rFHbgQ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4147f5aaae16062607c72758621d03d214219fc9/test/www/jxcore/perf_tests/PerfTestFramework.js#L34)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292)

**Comment by DrJukka** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[test/www/jxcore/package.json, line 38 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292#-K2mQexiX0uVcSGOAoLO)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4147f5aaae16062607c72758621d03d214219fc9/test/www/jxcore/package.json#L38)):</sup>
Done. (Why this tool still says that this is unresolved ?)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (413438c)

**Comment by ThaliTester** [comment]
Test (Fail) 49863886 build is completed (413438c)

See https://github.com/ThaliTester/TestResults/tree/49863886413438c_Story_001_juksilve_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ab9fb6b)

**Comment by ThaliTester** [comment]
Test (Fail) 49863886 build is completed (ab9fb6b)

See https://github.com/ThaliTester/TestResults/tree/49863886ab9fb6b_Story_001_juksilve_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (85a4553)

**Comment by ThaliTester** [comment]
Test (Fail) 49863886 build is completed (85a4553)

See https://github.com/ThaliTester/TestResults/tree/4986388685a4553_Story_001_juksilve_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (af81f3c)

**Comment by tobybrad** [comment]
Reviewed 4 of 31 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: 27 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[test/www/jxcore/perf_tests/PerfTestFramework.js, line 34 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292#-K2mQouDf9jZR-rFHbgQ)** ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4147f5aaae16062607c72758621d03d214219fc9/test/www/jxcore/perf_tests/PerfTestFramework.js#L34)):</sup>
It's Node. Platform shouldn't matter.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292)

**Comment by tobybrad** [comment]
Reviewed 1 of 1 files at r5.
Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292)

**Comment by tobybrad** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/292)

**Comment by ThaliTester** [comment]
Test (Success) 49863886 build is completed (af81f3c)

See https://github.com/ThaliTester/TestResults/tree/49863886af81f3c_Story_001_juksilve_DrJukka/ for the logs

**Comment by ThaliTester** [comment]
Test 49863886af81f3c(af81f3c) has failed

See https://github.com/ThaliTester/TestResults/tree/49863886af81f3c_Story_001_juksilve_DrJukka/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed and ready to merge

**Pull request merged**
