### PR TITLE
Issue 275

### PR DESCRIPTION
**Pull request by tobybrad**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/303)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0962aa2)

**Comment by ThaliTester** [comment]
Test (Fail) 50285395 build is completed (0962aa2)

See https://github.com/ThaliTester/TestResults/tree/502853950962aa2_Issue_275_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (19fc3a6)

**Comment by ThaliTester** [comment]
Test (Fail) 50285395 build is completed (19fc3a6)

See https://github.com/ThaliTester/TestResults/tree/5028539519fc3a6_Issue_275_tobybrad/ for the logs

**Comment by yaronyg** [comment]
@tobybrad Once the test is passing will you be assigned to me for code review?

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d8c7d8a)

**Comment by ThaliTester** [comment]
Test (Fail) 50285395 build is completed (d8c7d8a)

See https://github.com/ThaliTester/TestResults/tree/50285395d8c7d8a_Issue_275_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6cdc61c)

**Comment by ThaliTester** [comment]
Test (Fail) 50285395 build is completed (6cdc61c)

See https://github.com/ThaliTester/TestResults/tree/502853956cdc61c_Issue_275_tobybrad/ for the logs

**Pull request closed without merging**
