### PR TITLE
Provide remote db name for ThaliReplicationPeerAction during runtime #1873

### PR DESCRIPTION
**Pull request by mlesnic**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1876)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e186250)

**Comment by ThaliTester** [comment]
Test 122449695 (e186250) build started.

**Comment by ThaliTester** [comment]
Test (Success) 122449695 build is completed (e186250)

See https://github.com/ThaliTester/TestResults/tree/122449695e186250_Provide_remote_db_name_for_ThaliReplicationPeerAction_during_runtime__1873_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 122449695e186250(e186250) has failed

See https://github.com/ThaliTester/TestResults/tree/122449695e186250_Provide_remote_db_name_for_ThaliReplicationPeerAction_during_runtime__1873_mlesnic/ for the fail logs

**Comment by yaronyg** [comment]
We really need new tests added for thaliReplicationPeerAction.start where we prove that we can replicate both with a default name and with an explicit name for a database that isn't the localDbName.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-:-Kl13BtGDtVBpz0N1evW:b-fbxkoq)*

**Comment by jareksl** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 193 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-Kl2ti3rqXgbJhlhBUiB:-Kl2ti3rqXgbJhlhBUiC:b-49275y) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e18625077037626d3ae0f7f7512c7829978128e9/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L193)):*
> ```JavaScript
>  * when creating HTTP requests related to this action. Note that this is where
>  * the PSK related settings are specified.
>  * @param {string} remoteDbName The name of remote DB that we will try to replicate
> ```

You should state here, that this is optional parameter e.g: @param {string} [remoteDbName] An optional string specifying the name of the remote DB ... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (31d3bc8)

**Comment by ThaliTester** [comment]
Test 122449695 (31d3bc8) build started.

**Comment by mlesnic** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 193 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-Kl2ti3rqXgbJhlhBUiB:-Kl3z1teKQi3nDf3QAX6:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e18625077037626d3ae0f7f7512c7829978128e9/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L193)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

You should state here, that this is optional parameter e.g: @param {string} [remoteDbName] An optional string specifying the name of the remote DB ... 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876)*

**Comment by ThaliTester** [comment]
Test (Success) 122449695 build is completed (31d3bc8)

See https://github.com/ThaliTester/TestResults/tree/12244969531d3bc8_Provide_remote_db_name_for_ThaliReplicationPeerAction_during_runtime__1873_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 12244969531d3bc8(31d3bc8) has failed

See https://github.com/ThaliTester/TestResults/tree/12244969531d3bc8_Provide_remote_db_name_for_ThaliReplicationPeerAction_during_runtime__1873_mlesnic/ for the fail logs

**Comment by yaronyg** [comment]
Please answer the question about why the remoteDbName is on start and not on the constructor. Because if it's supposed to be on the constructor (and I would think it should be) then all the tests have to change.

---

Reviewed 2 of 4 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 193 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-Kl4rqH6Ia3euIEXckYd:-Kl4rqH6Ia3euIEXckYe:bffuofp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31d3bc8f937ec37239d3e500943325b79f9dbd28/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L193)):*
> ```JavaScript
>  * when creating HTTP requests related to this action. Note that this is where
>  * the PSK related settings are specified.
>  * @param {string} [remoteDbName] Optional parameter that specifies name of remote
> ```

I'm confused. Why is remoteDbName here and not on the constructor? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-:-Kl4sA7OEJTgeepUieND:b-fvjznr)*

**Comment by mlesnic** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 193 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-Kl4rqH6Ia3euIEXckYd:-KlIJWkRcdRuDqd6pG10:b37jza1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31d3bc8f937ec37239d3e500943325b79f9dbd28/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L193)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I'm confused. Why is remoteDbName here and not on the constructor? 
</blockquote></details>

The idea was that the customer of thali, with his own peer pool manager implementation, will be able to determine the remote db name, inside his peer pool manager. This allows customer to name his dbs in any way he wants to, for example, with some custom prefix or anything else. In peer pool manager, we can only manage already created PeerAction, we do not have control over creating it. 
In case we wanted to pass remoteDbName in ThaliReplicationPeerAction constructor, we would have to strictly lock the way remote db name should be resolved, for example based on peer's public key.
In my opinion, we should be more flexible and allow thali customer to name his dbs in any way he likes to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876)*

**Comment by mlesnic** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 193 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-Kl4rqH6Ia3euIEXckYd:-KlILqSR16UFaZsF_1DZ:bwp3dw6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31d3bc8f937ec37239d3e500943325b79f9dbd28/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L193)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary><blockquote>

The idea was that the customer of thali, with his own peer pool manager implementation, will be able to determine the remote db name, inside his peer pool manager. This allows customer to name his dbs in any way he wants to, for example, with some custom prefix or anything else. In peer pool manager, we can only manage already created PeerAction, we do not have control over creating it. 
In case we wanted to pass remoteDbName in ThaliReplicationPeerAction constructor, we would have to strictly lock the way remote db name should be resolved, for example based on peer's public key.
In my opinion, we should be more flexible and allow thali customer to name his dbs in any way he likes to.
</blockquote></details>

Also, in that case, we can resolve remote db name during runtime. In case every user have db named in different way, if we wanted to pass this in constructor, we would have to literally restart thali every time new user occurs, with different remote db name parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876)*

**Comment by yaronyg** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliReplicationPeerAction.js, line 274 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-KlULtoc7Dm1gelLPs9h:-KlULtoc7Dm1gelLPs9i:b951rd7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31d3bc8f937ec37239d3e500943325b79f9dbd28/test/www/jxcore/bv_tests/testThaliReplicationPeerAction.js#L274)):*
> ```JavaScript
>   });
> 
> test('Make sure docs replicate with remote db with different name than local db',
> ```

We need just one more test. What happens when we have the wrong remote name? We need to make sure we fail gracefully.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (60d457d)

**Comment by ThaliTester** [comment]
Test 122449695 (60d457d) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f36eb0f)

**Comment by ThaliTester** [comment]
Test (Success) 122449695 build is completed (60d457d)

See https://github.com/ThaliTester/TestResults/tree/12244969560d457d_Provide_remote_db_name_for_ThaliReplicationPeerAction_during_runtime__1873_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 122449695 (f36eb0f) build started.

**Comment by ThaliTester** [comment]
Test 12244969560d457d(60d457d) has failed

See https://github.com/ThaliTester/TestResults/tree/12244969560d457d_Provide_remote_db_name_for_ThaliReplicationPeerAction_during_runtime__1873_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 122449695 build is completed (f36eb0f)

See https://github.com/ThaliTester/TestResults/tree/122449695f36eb0f_Provide_remote_db_name_for_ThaliReplicationPeerAction_during_runtime__1873_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 122449695f36eb0f(f36eb0f) has failed

See https://github.com/ThaliTester/TestResults/tree/122449695f36eb0f_Provide_remote_db_name_for_ThaliReplicationPeerAction_during_runtime__1873_mlesnic/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 193 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-Kl4rqH6Ia3euIEXckYd:-KlZUDdRgbfJzbrX_qJs:bbunwkp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31d3bc8f937ec37239d3e500943325b79f9dbd28/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L193)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary><blockquote>

Also, in that case, we can resolve remote db name during runtime. In case every user have db named in different way, if we wanted to pass this in constructor, we would have to literally restart thali every time new user occurs, with different remote db name parameter.
</blockquote></details>

Yup. You're right and I'm wrong. The replication action is created by the Thali infrastructure in thaliPullReplicationFromNotification so if the peer policy is going to set the DB name then it has to happen in start.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-:-Kl_4oPxfVdKw41BCjEO:bnfp4nl)*

**Comment by jareksl** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876#-:-KlcbDMIihvnqcCzmqhg:bg7igkv)*

**Comment by jareksl** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1876)*

**Pull request merged**
