### PR TITLE
Readme about iOS installer

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1704)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (73b1372)

**Comment by ThaliTester** [comment]
Test 99638695 (73b1372) build started.

**Comment by yaronyg** [comment]
Please fix comments but otherwise :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/install/README.md, line 5 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1704#-K_ANflGTxijjy-Ez-44:-K_ANflHWHS5MayE8cyy:b-8m22qi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/73b1372c862efdc638ed5fcf25f71b39e6868b25/thali/install/README.md#L5)):*
> ```Markdown
> ## About iOS Install for Developers
> 
> Thali is intended to be installer via npm.
> ```

/installer/installed/

---

*[thali/install/README.md, line 8 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1704#-K_ANn0SthF74LwG-5Dw:-K_ANn0TYZn7f9ctgtuq:b-v2u29d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/73b1372c862efdc638ed5fcf25f71b39e6868b25/thali/install/README.md#L8)):*
> ```Markdown
> 
> There're several steps that Thali installer does. We're not going to cover
> all the steps, but to cover the most complicated steps.
> ```

/but to cover/just/

---

*[thali/install/README.md, line 26 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1704#-K_ANzD1A7docVI9Bk-A:-K_ANzD1A7docVI9Bk-B:b-nq70ib) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/73b1372c862efdc638ed5fcf25f71b39e6868b25/thali/install/README.md#L26)):*
> ```Markdown
>   implemented in _thali/install/ios/nativeInstaller.js_
> 
> Note that iOS native code is in separate [repo](https://github.com/thaliproject/thali-ios).
> ```

/in separate/in a separate/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1704#-:-K_AO7Zm687FcZ2rTW-L:bn7ppix)*

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Pull request merged**
