### PR TITLE
Update to jxcore-cordova 0.1.1

### LINKED ISSUE #522: Update to jxcore-cordova 0.1.1

### PR DESCRIPTION
**Pull request by vjrantal**
Fixes #522.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/524)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ee11130)

**Comment by tobybrad** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/524)*

**Comment by ThaliTester** [comment]
Test (Success) 58751238 build is completed (ee11130)

See https://github.com/ThaliTester/TestResults/tree/58751238ee11130_Update_to_jxcore-cordova_0_1_1_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 58751238ee11130(ee11130) has failed

See https://github.com/ThaliTester/TestResults/tree/58751238ee11130_Update_to_jxcore-cordova_0_1_1_vjrantal/ for the fail logs

**Pull request merged**
