### PR TITLE
README - Added a note

### PR DESCRIPTION
**Pull request by yaronyg**
testThaliMobile - Hardened data corruption test so it can handle zombie
availability announcements

thaliTcpServersManager - Making sure we can see when someone has
intentionally terminated an outgoing connection.

All other files are just linting

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1434)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (91ca3b4)

**Comment by ThaliTester** [comment]
Test (Success) 91113359 build is completed (91ca3b4)

See https://github.com/ThaliTester/TestResults/tree/9111335991ca3b4_README_-_Added_a_note_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 9111335991ca3b4(91ca3b4) has failed

See https://github.com/ThaliTester/TestResults/tree/9111335991ca3b4_README_-_Added_a_note_yaronyg/ for the fail logs

**Comment by chapko** [comment]
@yaronyg just remove 'only' flag and then it is :lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 693 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1434#-KV4ZzNryWb-eOmfOZQ_:-KV4ZzNsRuhefhYmDKZo:b5ul48u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/91ca3b41a8b6157d19fdcf68cce9104918bc665e/test/www/jxcore/bv_tests/testThaliMobile.js#L693)):*
> ```JavaScript
> }
> 
> test.only('test for data corruption', function () {
> ```

I don't think it should be in master branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1434#-:-KV4g1DSHVfqeA1udAa1:b-t3780d)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (19205dc)

**Comment by ThaliTester** [comment]
Test (Success) 91113359 build is completed (19205dc)

See https://github.com/ThaliTester/TestResults/tree/9111335919205dc_README_-_Added_a_note_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 9111335919205dc(19205dc) has failed

See https://github.com/ThaliTester/TestResults/tree/9111335919205dc_README_-_Added_a_note_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c81eeba)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e1acbe7)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (58f7725)

**Comment by ThaliTester** [comment]
Test (Fail) 91113359 build is completed (c81eeba)

See https://github.com/ThaliTester/TestResults/tree/91113359c81eeba_README_-_Added_a_note_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 91113359 build is completed (e1acbe7)

See https://github.com/ThaliTester/TestResults/tree/91113359e1acbe7_README_-_Added_a_note_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 91113359 build is completed (58f7725)

See https://github.com/ThaliTester/TestResults/tree/9111335958f7725_README_-_Added_a_note_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (25dbdbf)

**Comment by ThaliTester** [comment]
Test (Fail) 91113359 build is completed (25dbdbf)

See https://github.com/ThaliTester/TestResults/tree/9111335925dbdbf_README_-_Added_a_note_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (612863d)

**Comment by ThaliTester** [comment]
Test (Fail) 91113359 build is completed (612863d)

See https://github.com/ThaliTester/TestResults/tree/91113359612863d_README_-_Added_a_note_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (15e2b86)

**Comment by ThaliTester** [comment]
Test (Success) 91113359 build is completed (15e2b86)

See https://github.com/ThaliTester/TestResults/tree/9111335915e2b86_README_-_Added_a_note_yaronyg/ for the logs

**Comment by yaronyg** [comment]
Review status: 4 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 693 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1434#-KV4ZzNryWb-eOmfOZQ_:-KV6OBIqnIxHafJwMXyD:b190k2a) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/91ca3b41a8b6157d19fdcf68cce9104918bc665e/test/www/jxcore/bv_tests/testThaliMobile.js#L693)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> I don't think it should be in master branch.
</details>
And you would be right! Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1434)*

**Comment by ThaliTester** [comment]
Test 9111335915e2b86(15e2b86) has failed

See https://github.com/ThaliTester/TestResults/tree/9111335915e2b86_README_-_Added_a_note_yaronyg/ for the fail logs

**Pull request merged**
