### PR TITLE
IOS native can't handle parallel connection from node #1845 node

### PR DESCRIPTION
**Pull request by opetkevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1854)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2b86221)

**Comment by ThaliTester** [comment]
Test 114843042 (2b86221) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 114843042 build is completed (2b86221)

See https://github.com/ThaliTester/TestResults/tree/1148430422b86221_IOS_native_can_t_handle_parallel_connection_from_node__1845_node_opetkevich/ for the logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 131 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-Kh8Jeatzcq8kvD2zLqL:-Kh8Jeatzcq8kvD2zLqM:b-9yerlw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2b8622197900a0e35c1bb19ea52795d78cfa1cf6/test/www/jxcore/bv_tests/testThaliMobileNative.js#L131)):*
> ```JavaScript
> });
> 
> function findPeerAndConnect(advertisingPort) {
> ```

I thought we already had a utility function that did exactly this?

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 183 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-Kh8KDQbyYvs88p4vr4I:-Kh8KDQbyYvs88p4vr4J:b-3yfge5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2b8622197900a0e35c1bb19ea52795d78cfa1cf6/test/www/jxcore/bv_tests/testThaliMobileNative.js#L183)):*
> ```JavaScript
> 
> test('Can shift data via parallel connections', function (t) {
>   var dataLength = 22;
> ```

This is a really small value. It's the kind of things that gets through in the first packet but no other packets would have made it. I would personally not feel comfortable moving less than say 10k. That is going to blow all the packet lengths and prove things are actually moving.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 232 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-Kh8KW6q0wPnlbmElfic:-Kh8KW6rEMZStYZUABmJ:b-5qw9fu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2b8622197900a0e35c1bb19ea52795d78cfa1cf6/test/www/jxcore/bv_tests/testThaliMobileNative.js#L232)):*
> ```JavaScript
>   server.listen(0, function () {
>     var port = server.address().port;
>     findPeerAndConnect(port).then(function (info) {
> ```

Connections often fail for totally random reasons. But findPeerAndConnect has no retry logic nor does this function. That just seems to beg for constantly failing tests. Realistically don't we need to set a timer and keep trying to successfully send three requests in parallel until we either succeed or time out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (624ceb0)

**Comment by ThaliTester** [comment]
Test 114843042 (624ceb0) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 114843042 build is completed (624ceb0)

See https://github.com/ThaliTester/TestResults/tree/114843042624ceb0_IOS_native_can_t_handle_parallel_connection_from_node__1845_node_opetkevich/ for the logs

**Comment by dersim-davaod** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 324 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-KhgiJp34VwkBW2e4oyf:-KhgiJp34VwkBW2e4oyg:b-u04g73) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/624ceb0478415607a7331a7a8c8496a0376addf9/test/www/jxcore/bv_tests/testThaliMobileNative.js#L324)):*
> ```JavaScript
> }
> 
> function wairForEvent(emitter, event) {
> ```

NB:
Fix typo wairForEvent -> waitForEvent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854)*

**Comment by evabishchevich** [comment]
@opetkevich Please, fix the typo mentioned above

**Comment by yaronyg** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 324 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-KhgiJp34VwkBW2e4oyf:-KhwteiPdLOGDXYGVRdN:b32v57) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/624ceb0478415607a7331a7a8c8496a0376addf9/test/www/jxcore/bv_tests/testThaliMobileNative.js#L324)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary><blockquote>

NB:
Fix typo wairForEvent -> waitForEvent
</blockquote></details>

+1

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 474 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-KhwubNeGeVPtumZi0PN:-KhwubNeGeVPtumZi0PO:b-9ki1kp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/624ceb0478415607a7331a7a8c8496a0376addf9/test/www/jxcore/bv_tests/testThaliMobileNative.js#L474)):*
> ```JavaScript
> 
>   var uuids = t.participants.map(function (p) { return p.uuid; });
>   assert(uuids.length === 2, 'This test requires exactly 2 devices');
> ```

How are we guaranteeing this? In general the iOS tests can be run with more than 2 devices. If we use more than 2 devices then won't this test always fail? That doesn't seem right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854)*

**Comment by yaronyg** [comment]
Please respond to comments. Thanks!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-:-KhxG7I5jy3MVTqOUoJw:b-m5vgd3)*

**Comment by chapko** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 474 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-KhwubNeGeVPtumZi0PN:-Khzz5MgFZYfGNr4dH0x:b3h5i6p) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/624ceb0478415607a7331a7a8c8496a0376addf9/test/www/jxcore/bv_tests/testThaliMobileNative.js#L474)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

How are we guaranteeing this? In general the iOS tests can be run with more than 2 devices. If we use more than 2 devices then won't this test always fail? That doesn't seem right.
</blockquote></details>

Originally it was written for any number of devices, but then I changed it for Enrico to make debugging easier (so devices do not connect to each other simultaneously). @opetkevich take a look at the commit history in `master_chapko_minidatashifttest` branch, I think it will be clear when these changes were introduced. And feel free to ask any questions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ececf88)

**Comment by ThaliTester** [comment]
Test 114843042 (ececf88) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 114843042 build is completed (ececf88)

See https://github.com/ThaliTester/TestResults/tree/114843042ececf88_IOS_native_can_t_handle_parallel_connection_from_node__1845_node_opetkevich/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1854#-:-Ki68LQojSJb2cVNiVnO:bnfp4nl)*

**Pull request merged**
