### PR TITLE
Fix issues with native unit tests on iOS.

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1339)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e90776b)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (e90776b)

See https://github.com/ThaliTester/TestResults/tree/89624796e90776b_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 89624796e90776b(e90776b) has failed

See https://github.com/ThaliTester/TestResults/tree/89624796e90776b_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by baydet** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPServerMock.swift, line 110 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339#-KUICA6XTOBT0P_2gD1r:-KUICA6XTOBT0P_2gD1s:bqfn4s4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e90776b2dda1ad84a841f3019f345c08b5c744f5/lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPServerMock.swift#L110)):*
> ```Swift
>             }
>         }
>         didDisconnectHandler(sock)
> ```

NB
sock->socket typo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339#-:-KUICORRXMsS4rTIDmRo:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9f429ca)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (9f429ca)

See https://github.com/ThaliTester/TestResults/tree/896247969f429ca_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 896247969f429ca(9f429ca) has failed

See https://github.com/ThaliTester/TestResults/tree/896247969f429ca_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (0a9c9d6)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (0a9c9d6)

See https://github.com/ThaliTester/TestResults/tree/896247960a9c9d6_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 896247960a9c9d6(0a9c9d6) has failed

See https://github.com/ThaliTester/TestResults/tree/896247960a9c9d6_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d2d5448)

**Comment by ThaliTester** [comment]
Test (Fail) 89624796 build is completed (d2d5448)

See https://github.com/ThaliTester/TestResults/tree/89624796d2d5448_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c0befbd)

**Comment by ThaliTester** [comment]
Test (Fail) 89624796 build is completed (c0befbd)

See https://github.com/ThaliTester/TestResults/tree/89624796c0befbd_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (53c8680)

**Comment by ThaliTester** [comment]
Test (Fail) 89624796 build is completed (53c8680)

See https://github.com/ThaliTester/TestResults/tree/8962479653c8680_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (1d81153)

**Comment by dersim-davaod** [comment]
Review status: 3 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPServerMock.swift, line 110 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339#-KUICA6XTOBT0P_2gD1r:-KVPpJ2sOBdZzXkHDqSE:bundkbh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9f429ca984e36c7726b98ca3662cdf03a505caa8/lib/ios/ThaliCore/ThaliCoreTests/SocketConnectionTests/TCPServerMock.swift#L110)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> NB
> sock->socket typo?
</details>
No, this is the default name provided by autocompletion for GCDAsyncSocketDelegate's methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339)*

**Comment by ThaliTester** [comment]
Test (Fail) 89624796 build is completed (1d81153)

See https://github.com/ThaliTester/TestResults/tree/896247961d81153_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by baydet** [comment]
Reviewed 2 of 3 files at r2, 8 of 11 files at r3, 3 of 4 files at r5.
Review status: 16 of 21 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339)*

**Comment by baydet** [comment]
Reviewed 1 of 11 files at r3, 3 of 3 files at r4, 1 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (71c5ab8)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (71c5ab8)

See https://github.com/ThaliTester/TestResults/tree/8962479671c5ab8_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 8962479671c5ab8(71c5ab8) has failed

See https://github.com/ThaliTester/TestResults/tree/8962479671c5ab8_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0fcbde9)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (0fcbde9)

See https://github.com/ThaliTester/TestResults/tree/896247960fcbde9_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 896247960fcbde9(0fcbde9) has failed

See https://github.com/ThaliTester/TestResults/tree/896247960fcbde9_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by drinkius** [comment]
NB: naming issues:

AdvertiserManagerTests.swift, lines 85-140:
expectedAmountOfAdvertisersBeforeStartMethod -> expectedNumberOfAdvertisersBeforeStartMethod
expectedAmountOfAdvertisersAfterFirstStartMethod -> expectedNumberOfAdvertisersAfterFirstStartMethod
expectedAmountOfAdvertisersAfterSecondStartMethod -> expectedNumberOfAdvertisersAfterSecondStartMethod
testStartStopAdvertisingChangesInternalAmountOfAdvertisers -> testStartStopAdvertisingChangesInternalNumberOfAdvertisers
testStartStopStartAdvertisingChangesInternalAmountOfAdvertisers -> testStartStopStartAdvertisingChangesInternalNumberOfAdvertisers

RelayTests.swift, lines 71, 72, 87, 89:
totalMessagesAmount -> totalMessagesNumber
receivedMessagesAmount -> totalMessagesNumber

---

Reviewed 3 of 11 files at r1, 2 of 3 files at r2, 8 of 11 files at r3, 3 of 3 files at r4, 4 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/AdvertiserManagerTests.swift, line 114 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339#-KW3MAmmR4sSIcBscH9J:-KW3MAmmR4sSIcBscH9K:bb6p6kf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0fcbde9d87427b5f7368169400d46c5efe984df8/lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/AdvertiserManagerTests.swift#L114)):*
> r

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339#-:-KW3LbUKH5cIamswVrOE:bso5i7z)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1682436)

**Comment by dersim-davaod** [comment]
Review status: 19 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/AdvertiserManagerTests.swift, line 114 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339#-KW3MAmmR4sSIcBscH9J:-KW3cEv1C7onAZQ3yEDA:b-nvyhhv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0fcbde9d87427b5f7368169400d46c5efe984df8/lib/ios/ThaliCore/ThaliCoreTests/MultipeerConnectivityTests/AdvertiserManagerTests.swift#L114)):*
<details><summary><i>Previously, drinkius (Alexander Telegin) wrote…</i></summary>
> > r
</details>
Fixed naming issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339)*

**Comment by drinkius** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339#-:-KW3d3d8ib9LIhzVUvYi:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (1682436)

See https://github.com/ThaliTester/TestResults/tree/896247961682436_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 896247961682436(1682436) has failed

See https://github.com/ThaliTester/TestResults/tree/896247961682436_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (70bc939)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (70bc939)

See https://github.com/ThaliTester/TestResults/tree/8962479670bc939_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 8962479670bc939(70bc939) has failed

See https://github.com/ThaliTester/TestResults/tree/8962479670bc939_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (76fe425)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (76fe425)

See https://github.com/ThaliTester/TestResults/tree/8962479676fe425_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 8962479676fe425(76fe425) has failed

See https://github.com/ThaliTester/TestResults/tree/8962479676fe425_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d0595a7)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (d0595a7)

See https://github.com/ThaliTester/TestResults/tree/89624796d0595a7_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 89624796d0595a7(d0595a7) has failed

See https://github.com/ThaliTester/TestResults/tree/89624796d0595a7_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5a92e74)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ae60baf)

**Comment by ThaliTester** [comment]
Test 896247965a92e74(5a92e74) has failed

See https://github.com/ThaliTester/TestResults/tree/896247965a92e74_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (ae60baf)

See https://github.com/ThaliTester/TestResults/tree/89624796ae60baf_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1c3697b)

**Comment by ThaliTester** [comment]
Test (Fail) 89624796 build is completed (1c3697b)

See https://github.com/ThaliTester/TestResults/tree/896247961c3697b_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9cd5996)

**Comment by ThaliTester** [comment]
Test (Success) 89624796 build is completed (9cd5996)

See https://github.com/ThaliTester/TestResults/tree/896247969cd5996_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 896247969cd5996(9cd5996) has failed

See https://github.com/ThaliTester/TestResults/tree/896247969cd5996_Fix_issues_with_native_unit_tests_on_iOS__dersim-davaod/ for the fail logs

**Comment by drinkius** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1339)*

**Pull request merged**
