### PR TITLE
More thaliMobileNativeWrapper

### PR DESCRIPTION
**Pull request by vjrantal**
This change is [Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/612)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7756efd)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (7756efd)

See https://github.com/ThaliTester/TestResults/tree/625481247756efd_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625481247756efd(7756efd) has failed

See https://github.com/ThaliTester/TestResults/tree/625481247756efd_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 3 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCcINbSVA_GDZ0CoODN:-KCcINbSVA_GDZ0CoODO:1901187419) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L3)):*
Is there any way that isn't a mountain of work to set up a test, it could be just with the wifi mock, that would let us test with multiple peers at the same time? This is a huge stress test for us to pass to be sure our code actually works. And yes, I realize that first we have to get it working with one peer.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 15 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbGYGod7Iz7UA77Zv-:-KCbGYGp4XRlC1awbjbB:1429023702) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L15)):*
This variable is set but it's then never actually used. Since it's not exported it can't be used for debugging. So why is it here?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 16 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbGmlHM9xpx6kCcgwc:-KCbGmlHM9xpx6kCcgwd:-1205245250) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L16)):*
This variable is only used in the start function and also isn't exported. So why does it need to be global?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 411 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbDTcK12zRgs6HObpN:-KCbDTcK12zRgs6HObpO:-1845964965) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L411)):*
I was surprised this wasn't implemented. Is there a complexity I missed? Seems like a straight forward native call.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 491 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbsN3gd60O-eRPFJOz:-KCbsN3h7O1ve8bHZoE0:-1509266234) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L491)):*
Actually I would argue, no.

Once we have stated that the peer is not available then if the listener is still hanging around and someone connects to it either it will work (because we were wrong, the peer was available) or it won't, which could happen at any time anyway. We only support a limited number of listeners so it really doesn't matter if a listener sticks around. The only entity that is likely to actually care is the peer pool manager because in the case of Bluetooth we have a fixed number of connections so we are well motivated to recycle quickly. But I'm already adding in interfaces to let the peer pool manager kill connections itself.

The real question is - what about heuristics? For example, if we get a notification that a peer is not available but we have an active connection with the peer should we really be sending a peer not available notification?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 619 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbzn4Z21_AUjOIclbE:-KCbzn4Z21_AUjOIclbF:-1265671629) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L619)):*
I'm worried about the logic of how we handle this. The error we are getting here says that the native layer tried to connect to the tcpServersManager listening port and it didn't work. This is pretty much a catastrophic error. Something seriously bad has happened and all current active listeners are going to go bad. This should not happen. So if it does it means we are in the moral equivalent of an exception. I don't think we should try to recover. I think we should just shut down, with no restart and emit the event letting the listener know that fit hit the shan. I have submitted this in my PR for your review.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 622 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbHrSCGz3a2-UG-JMR:-KCbHrSCGz3a2-UG-JMS:373703579) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L622)):*
Shouldn't you check to see if we have stopped? Otherwise serversManager could be null and that would be bad. :( But in any case see my newly proposed code

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612)*

**Comment by yaronyg** [comment]
Reviewed 4 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6b04bc0)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (6b04bc0)

See https://github.com/ThaliTester/TestResults/tree/625481246b04bc0_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625481246b04bc0(6b04bc0) has failed

See https://github.com/ThaliTester/TestResults/tree/625481246b04bc0_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7d7767b)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (7d7767b)

See https://github.com/ThaliTester/TestResults/tree/625481247d7767b_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by vjrantal** [comment]
Review status: 4 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCcINbSVA_GDZ0CoODN:-KCtxrReXSqhwO8GkKeQ:1421512735) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L3)):*
Would it make sense to write a multi-peer test on top of the replication layer?

I think overall, multi-peer tests might require coordination server to distribute the participants so that parties would know what kind of data to expect. Then, on top of thaliMobileNativeWrapper, there could be a test that expects to discover everyone and connect to them.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 15 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbGYGod7Iz7UA77Zv-:-KCu8LRQ0DXZFUXiacmo:-558123344) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L15)):*
It was there in case in some error scenarios we would also want to restart the router server (currently we only restart the TCP servers manager).

Will remove unless I actually take into use.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 16 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbGmlHM9xpx6kCcgwc:-KCu8U31GduyBezaGztf:1825643046) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L16)):*
See previous comment.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 411 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbDTcK12zRgs6HObpN:-KCu8W8_YgOtabDkku2l:-963940236) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L411)):*
On iOS, this was implemented with a different name than on Android so the iOS code should be fixed to match specification. Is it okay to just add the call or how should I test calling it in testThaliMobileNativeWrapper.js and what all should the iOS implementation do when called?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 491 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbsN3gd60O-eRPFJOz:-KCuXrG5lDY_zH_4-tw9:-1444709839) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L491)):*
Is it possible that iOS or Android would shoot a peer unavailable event in case there is an active connection?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612)*

**Comment by ThaliTester** [comment]
Test 625481247d7767b(7d7767b) has failed

See https://github.com/ThaliTester/TestResults/tree/625481247d7767b_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (56b2960)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (56b2960)

See https://github.com/ThaliTester/TestResults/tree/6254812456b2960_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (56b2960)

See https://github.com/ThaliTester/TestResults/tree/6254812456b2960_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bf1e918)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (bf1e918)

See https://github.com/ThaliTester/TestResults/tree/62548124bf1e918_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (dff6a17)

**Comment by ThaliTester** [comment]
Test 62548124bf1e918(bf1e918) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/62548124bf1e918_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (dff6a17)

See https://github.com/ThaliTester/TestResults/tree/62548124dff6a17_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62548124dff6a17(dff6a17) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/62548124dff6a17_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b1759ae)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (b1759ae)

See https://github.com/ThaliTester/TestResults/tree/62548124b1759ae_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62548124b1759ae(b1759ae) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/62548124b1759ae_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (797bacc)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (797bacc)

See https://github.com/ThaliTester/TestResults/tree/62548124797bacc_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7f44100)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (7f44100)

See https://github.com/ThaliTester/TestResults/tree/625481247f44100_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (35e75eb)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (7f44100)

See https://github.com/ThaliTester/TestResults/tree/625481247f44100_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (35e75eb)

See https://github.com/ThaliTester/TestResults/tree/6254812435e75eb_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9632eda)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (9632eda)

See https://github.com/ThaliTester/TestResults/tree/625481249632eda_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b8ccb9f)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (b8ccb9f)

See https://github.com/ThaliTester/TestResults/tree/62548124b8ccb9f_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62548124b8ccb9f(b8ccb9f) has failed

See https://github.com/ThaliTester/TestResults/tree/62548124b8ccb9f_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 3 of 6 files at r3, 2 of 5 files at r4, 2 of 3 files at r5, 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[build.sh, line 67 \[r10\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KD9TL8qr6f_viJ0rUEF:-KD9TL8qr6f_viJ0rUEG:963015110) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b8ccb9f7bfa8f766ea53a0374995f1cd91de805c/build.sh#L67)):*
NB: If this really improves things I'm o.k. checking it in but at least please file a bug so we remember to undo this at some point when we have time to investigate.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCcINbSVA_GDZ0CoODN:-KD9Xwx0cPdhuMFY8PNt:-1715013670) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L3)):*
I think we should do the first multi-peer test here because otherwise we will introduce too many complications. I expect to do multi-peer tests at all layers of the stack but this is the bottom. I was thinking of something super simple. I forget, does the distribution server today tell each device how many devices are in the test? But please open this as a separate issue and let's not block this check in.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 411 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbDTcK12zRgs6HObpN:-KD9UOFr6kuUGnRVlXTx:-1324095162) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L411)):*
The first person to need it has to implement it. :) Otherwise let's move on.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 491 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCbsN3gd60O-eRPFJOz:-KD9XLrE2osrESe8zwNj:1027688875) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/thali/NextGeneration/thaliMobileNativeWrapper.js#L491)):*
In the case of iOS it shouldn't happen but I'm not sure about Android. @tompaana does the native code check before it fires an unavailable event to see if there is an active Bluetooth connection or is the Bluetooth and BLE code completely separate? I'm kind of hoping that they are separate because I'd rather handle this at the node layer. But please let us know.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[build.sh, line 67 \[r10\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KD9TL8qr6f_viJ0rUEF:-KDClOEubZB4CkQ5q-dz:1647180886) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b8ccb9f7bfa8f766ea53a0374995f1cd91de805c/build.sh#L67)):*
Done.

https://github.com/thaliproject/Thali_CordovaPlugin/issues/647

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KCcINbSVA_GDZ0CoODN:-KDCliA8MrSPvNLrYH7Q:1647180887) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7756efd754fdb65774042d33d9733b93a0a996e0/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L3)):*
Done.

https://github.com/thaliproject/Thali_CordovaPlugin/issues/648

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (edbd5b2)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (edbd5b2)

See https://github.com/ThaliTester/TestResults/tree/62548124edbd5b2_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (641cd0d)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (641cd0d)

See https://github.com/ThaliTester/TestResults/tree/62548124641cd0d_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ab360f0)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (ab360f0)

See https://github.com/ThaliTester/TestResults/tree/62548124ab360f0_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (00d9b2d)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (00d9b2d)

See https://github.com/ThaliTester/TestResults/tree/6254812400d9b2d_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8519c70)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (8519c70)

See https://github.com/ThaliTester/TestResults/tree/625481248519c70_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ca582f4)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (ca582f4)

See https://github.com/ThaliTester/TestResults/tree/62548124ca582f4_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62548124ca582f4(ca582f4) has failed

See https://github.com/ThaliTester/TestResults/tree/62548124ca582f4_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d9c0fd9)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (d9c0fd9)

See https://github.com/ThaliTester/TestResults/tree/62548124d9c0fd9_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62548124d9c0fd9(d9c0fd9) has failed

See https://github.com/ThaliTester/TestResults/tree/62548124d9c0fd9_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5382a4d)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (5382a4d)

See https://github.com/ThaliTester/TestResults/tree/625481245382a4d_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625481245382a4d(5382a4d) has failed

See https://github.com/ThaliTester/TestResults/tree/625481245382a4d_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4351862)

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (4351862)

See https://github.com/ThaliTester/TestResults/tree/625481244351862_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 62548124 build is completed (4351862)

See https://github.com/ThaliTester/TestResults/tree/625481244351862_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ece3ba0)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (ece3ba0)

See https://github.com/ThaliTester/TestResults/tree/62548124ece3ba0_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62548124ece3ba0(ece3ba0) has failed

See https://github.com/ThaliTester/TestResults/tree/62548124ece3ba0_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bd1cdb6)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (bd1cdb6)

See https://github.com/ThaliTester/TestResults/tree/62548124bd1cdb6_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62548124bd1cdb6(bd1cdb6) has failed

See https://github.com/ThaliTester/TestResults/tree/62548124bd1cdb6_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6894564)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (6894564)

See https://github.com/ThaliTester/TestResults/tree/625481246894564_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625481246894564(6894564) has failed

See https://github.com/ThaliTester/TestResults/tree/625481246894564_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e8057a0)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (e8057a0)

See https://github.com/ThaliTester/TestResults/tree/62548124e8057a0_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 62548124e8057a0(e8057a0) has failed

See https://github.com/ThaliTester/TestResults/tree/62548124e8057a0_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6a7d362)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (6a7d362)

See https://github.com/ThaliTester/TestResults/tree/625481246a7d362_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625481246a7d362(6a7d362) has failed

See https://github.com/ThaliTester/TestResults/tree/625481246a7d362_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0f1d9b8)

**Comment by ThaliTester** [comment]
Test (Success) 62548124 build is completed (0f1d9b8)

See https://github.com/ThaliTester/TestResults/tree/625481240f1d9b8_More_thaliMobileNativeWrapper_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 625481240f1d9b8(0f1d9b8) has failed

See https://github.com/ThaliTester/TestResults/tree/625481240f1d9b8_More_thaliMobileNativeWrapper_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r12, 1 of 1 files at r14, 1 of 3 files at r16, 7 of 8 files at r18, 2 of 3 files at r20, 1 of 1 files at r21.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/UnitTest_app.js, line 48 \[r21\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KDOu14flbURqmBXbqnZ:-KDOu14flbURqmBXbqn_:1208935012) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0f1d9b87fd1766be166ede48b14dec25de2fcf5d/test/www/jxcore/UnitTest_app.js#L48)):*
NB: I think you are potentially playing a dangerous game here. in the case of Android this check is true. But in the case of iOS it is not. On iOS we only require Bluetooth and WiFi but not BLE. However I believe that iOS (like Android actually) bundles the Bluetooth and BLE permissions together so we either have both or none (which if you think about it is odd given that they have different usages). But have you confirmed with @tobybrad that iOS will always return bluetoothLowEnergy === 'on' even though we don't need BLE on iOS?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/UnitTest_app.js, line 48 \[r21\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612#-KDOu14flbURqmBXbqnZ:-KDRvqClYCKT-7uhrdUz:450995105) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0f1d9b87fd1766be166ede48b14dec25de2fcf5d/test/www/jxcore/UnitTest_app.js#L48)):*
I had checked the code and the BLE flag on iOS reflects CBCentralManagerStatePoweredOn, which in Apple's documentation is documented like this:

```
indicated by the CBCentralManagerStatePoweredOn constant. This state indicates that the central device (your iPhone or iPad, for instance) supports Bluetooth low energy and that Bluetooth is on and available to use.
```

I'll merge the code as is, because we don't actually end up to this code path ever on iOS, because `testUtils.hasRequiredHardware()` will always resolve to true.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/612)*

**Pull request merged**
