### PR TITLE
Just adding a bunch of logging

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1416)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (16f340e)

**Comment by ThaliTester** [comment]
Test (Success) 90721499 build is completed (16f340e)

See https://github.com/ThaliTester/TestResults/tree/9072149916f340e_Just_adding_a_bunch_of_logging_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 9072149916f340e(16f340e) has failed

See https://github.com/ThaliTester/TestResults/tree/9072149916f340e_Just_adding_a_bunch_of_logging_yaronyg/ for the fail logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1416#-:-KV5xyV5yvsYPF7UC2iv:bnfp4nl)*

**Comment by yaronyg** [comment]
Closed, changes will come in via thaliproject/Thali_CordovaPlugin#1458

**Pull request closed without merging**
