### PR TITLE
iOS 1572

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1626)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (bbfd026)

**Comment by ThaliTester** [comment]
Test 97333091 (bbfd026) build started.

**Comment by ThaliTester** [comment]
Test (Success) 97333091 build is completed (bbfd026)

See https://github.com/ThaliTester/TestResults/tree/97333091bbfd026_iOS_1572_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 97333091bbfd026(bbfd026) has failed

See https://github.com/ThaliTester/TestResults/tree/97333091bbfd026_iOS_1572_vasilevskayaem/ for the fail logs

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1626#-:-KYmX87VLDOvJ_TrboYr:bnfp4nl)*

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1626#-:-KYn-By3zsEigEI5FRN_:bnfp4nl)*

**Pull request merged**
