### PR TITLE
Run desktop tests in CI.

### LINKED ISSUE #386: Run desktop tests in CI
Run the tests that work on desktop in the CI.

This makes sense as a normal quality practice, but also helps protect the real device resources in CI from unintended broken code. Running the desktop tests would act as first quality gate to to check that syntax errors / typos and such don't end up creating builds that potentially consume the full CI timeout of device resources since we don't have a capability currently to cancel ongoing test runs.

### PR DESCRIPTION
**Pull request by vjrantal**
Commented out one test that must be fixed separately, because that one hangs
forever and thus prevents the build from proceeding.

Fixes #386.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/438)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (82079f9)

**Comment by ThaliTester** [comment]
Test (Fail) 55887758 build is completed (82079f9)

See https://github.com/ThaliTester/TestResults/tree/5588775882079f9_Run_desktop_tests_in_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (fbf20fd)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ffca2e4)

**Comment by ThaliTester** [comment]
Test (Fail) 55887758 build is completed (fbf20fd)

See https://github.com/ThaliTester/TestResults/tree/55887758fbf20fd_Run_desktop_tests_in_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 55887758 build is completed (ffca2e4)

See https://github.com/ThaliTester/TestResults/tree/55887758ffca2e4_Run_desktop_tests_in_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8826def)

**Comment by ThaliTester** [comment]
Test (Success) 55887758 build is completed (8826def)

See https://github.com/ThaliTester/TestResults/tree/558877588826def_Run_desktop_tests_in_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 558877588826def(8826def) has failed

See https://github.com/ThaliTester/TestResults/tree/558877588826def_Run_desktop_tests_in_CI__vjrantal/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/438)*

**Comment by tobybrad** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/438)*

**Pull request merged**
