### PR TITLE
Increased timeouts for test write

### PR DESCRIPTION
**Pull request by andrew-aladev**
Related to #1687.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1694)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2387919)

**Comment by ThaliTester** [comment]
Test 99446918 (2387919) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99446918 build is completed (2387919)

See https://github.com/ThaliTester/TestResults/tree/994469182387919_Increased_timeouts_for_test_write_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 994469182387919(2387919) has failed

See https://github.com/ThaliTester/TestResults/tree/994469182387919_Increased_timeouts_for_test_write_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
Please put in the requested comment and then :LGTM:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliManagerCoordinated.js, line 49 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1694#-K_70OJN_ygyYmHJy9TM:-K_70OJOIR16E1b09Mtq:bbiuo58) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/2387919e4c18e31f71d23b4a515c12f0338a6e90/test/www/jxcore/bv_tests/testThaliManagerCoordinated.js#L49)):*
> ```JavaScript
>     });
>   },
>   setupTimeout:     3 * 60 * 1000,
> ```

Please link to an issue to explain why we have to set these numbers so high.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1694#-:-K_70RQ9GMpdNDIKCOst:br4a6nf)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ca12220)

**Comment by ThaliTester** [comment]
Test 99446918 (ca12220) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (543443a)

**Comment by ThaliTester** [comment]
Test 99446918 (543443a) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 99446918 build is completed (543443a)

See https://github.com/ThaliTester/TestResults/tree/99446918543443a_Increased_timeouts_for_test_write_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 99446918ca12220(ca12220) has failed

See https://github.com/ThaliTester/TestResults/tree/99446918ca12220_Increased_timeouts_for_test_write_andrew-aladev/ for the fail logs

**Pull request merged**
