### PR TITLE
Primarily adding killSuperseded with a few other minor features

### PR DESCRIPTION
**Pull request by yaronyg**
testThaliManagerCoordinated, testThaliReplicationPeerAction, asserts
thaliPullReplicationFromNotification,
thaliSendNotificationBasedOnReplication, thaliConfig, thaliManager,
thaliMobile, thaliPeerPoolInterface - Linting

testThaliMobile - Minor bug fix

testThaliMobileNativeWrapper - Fixed test

testThaliNotificationClient - Added test for killSuperseded

thaliNotificationAction - Added killSuperseded

thaliNotificationClient - Support for handling killSuperseded

thaliReplicationPeerAction - Mostly linting but added a function to get
peerAdvertisesDataForUs

thaliMobileNativeWrapper - Fixed the fact that we were calling the wrong
function! (That anyway hasn't been implemented)

platform - Reverse integrated some functionality from iOS that I needed

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1387)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3902dfa)

**Comment by ThaliTester** [comment]
Test 901236693902dfa(3902dfa) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/901236693902dfa_Primarily_adding_killSuperseded_with_a_few_other_minor_features_yaronyg/ for the logs

**Comment by chapko** [comment]
@yaronyg please, see my comments

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 280 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWdH8BqiGgex7_-5a0:-KUWdH8ChHn58ZIhwufn:bq3e70u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L280)):*
> ```JavaScript
>   var enqueue = function (action) {
>     ++callCounter;
>     console.log("GOT CALLED: " + callCounter);
> ```

I assume you used it for debugging. Either it should be removed together with `callCounter` or there should be some check for the number of `enqueue` calls.

---

*[thali/NextGeneration/replication/thaliPullReplicationFromNotification.js, line 253 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWX8zw6TUKnLkHIB2W:-KUWX8zxy6BoIfhtHj4Y:b-t6gqr9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/thali/NextGeneration/replication/thaliPullReplicationFromNotification.js#L253)):*
> ```JavaScript
>   self._thaliNotificationClient.stop();
> 
>   Object.getOwnPropertyNames(self._peerDictionary)
> ```

NB: `Object.keys` is more straightforward in this case.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 86 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWfyEJtpQdcnwnAupW:-KUWfyEJtpQdcnwnAupX:b-3z5izr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L86)):*
> ```JavaScript
>  * @type {number}
>  */
> ThaliReplicationPeerAction.MAX_IDLE_PERIOD_SECONDS = 3;
> ```

NB: Just wondering why did you reduced it from 30 to 3?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-:-KUWhOC2VAF-pGWP8p0x:b5za33t)*

**Comment by chapko** [comment]
Since you're going to just remove this `console.log` then when you remove it, it will :lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-:-KUXuokpXF9kG4XmXwvW:bd3phpi)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1db083c)

**Comment by ThaliTester** [comment]
Test (Success) 90123669 build is completed (1db083c)

See https://github.com/ThaliTester/TestResults/tree/901236691db083c_Primarily_adding_killSuperseded_with_a_few_other_minor_features_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 901236691db083c(1db083c) has failed

See https://github.com/ThaliTester/TestResults/tree/901236691db083c_Primarily_adding_killSuperseded_with_a_few_other_minor_features_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
Review status: 16 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 280 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWdH8BqiGgex7_-5a0:-KUYPVZhqMCGZIc-UjY0:b-qjodfh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L280)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> I assume you used it for debugging. Either it should be removed together with `callCounter` or there should be some check for the number of `enqueue` calls.
</details>
Yup. This is a screw up. That's why I use full quotes and not single quotes so when I forget things like this at least at some point the linter will yell at me. :)

Fixed

---

*[thali/NextGeneration/replication/thaliPullReplicationFromNotification.js, line 253 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWX8zw6TUKnLkHIB2W:-KUYPs5dWHqBFENm9hD9:b1e9o56) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/thali/NextGeneration/replication/thaliPullReplicationFromNotification.js#L253)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> NB: `Object.keys` is more straightforward in this case.
</details>
I tend to be really paranoid about object.keys. The reason is that it won't just enumerate the properties set directly on the object but also all the properties the object has inherited. Now in this case that really shouldn't matter but I tend to exercise defensive programming and use getOwnPropertyNames all the time so I don't have to try and remember who needs it and who doesn't.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 86 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWfyEJtpQdcnwnAupW:-KUYQ5jMYGA9cdmp1_B5:b-siv1ok) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L86)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> NB: Just wondering why did you reduced it from 30 to 3?
</details>
Honestly I want to get rid of it all together but I figure now isn't the time.

The motivation for this feature was:
1. Bluetooth connections are hard to set up and can often take quite a bit of time, anywhere from 500 ms to 30 seconds. So once we have a Bluetooth connection we really want to keep it.
2. For demos we usually show some kind of chat app and so not losing our replication connection is useful for better looking demos

But the problem is that based on some of the perf results we are seeing in Bluetooth we seem to have an enormous fall off in bandwidth when we open more than one connection. In particular when a S7 talks to a 6P 1:1 the connection bandwidth is o.k. But if a S7 has two simultaneous connections open, one with another S7 and a second with a 6P for some reason the 6P will get allocated almost 0 bandwidth! The point being that for Bluetooth we may have to degenerate to only allowing a single Bluetooth socket at a time. In that case we need replications to finish up quick and get out of the way so we can talk to someone else.

For now I'm trying to make things a bit easier by reducing the wait to 3 seconds so that someone else will get a chance to talk to the device. In the long term we are going to switch from live replication to static replication and then let the peer policy manager decide if it wants to do another round of replication or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387)*

**Comment by chapko** [comment]
Review status: 16 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 280 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWdH8BqiGgex7_-5a0:-KUad4T1SRT2B-nLInHL:bjep3ij) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L280)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Yup. This is a screw up. That's why I use full quotes and not single quotes so when I forget things like this at least at some point the linter will yell at me. :)
> 
> Fixed
</details>
Interesting idea :)

---

*[thali/NextGeneration/replication/thaliPullReplicationFromNotification.js, line 253 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWX8zw6TUKnLkHIB2W:-KUa_5Z6vmDTHkwrffyc:b-ui1djf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/thali/NextGeneration/replication/thaliPullReplicationFromNotification.js#L253)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> I tend to be really paranoid about object.keys. The reason is that it won't just enumerate the properties set directly on the object but also all the properties the object has inherited. Now in this case that really shouldn't matter but I tend to exercise defensive programming and use getOwnPropertyNames all the time so I don't have to try and remember who needs it and who doesn't.
</details>
`Object.keys` enumerates only own properties, it ignores keys from the prototypes. You probably confused it with `for-in` loop.

Difference between `Object.getOwnPropertyNames` and `Object.keys` is  that the former will also include non-enumerable properties. In this case it doesn't matter since `_peerDictionary` is a plain object with simple properties, but it just  looks a bit weird.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 86 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387#-KUWfyEJtpQdcnwnAupW:-KUac3jpvFFhq-bnvhix:bxcixbi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/3902dfa0e0c8daadcb5e8aa0448f79833fd9748c/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L86)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Honestly I want to get rid of it all together but I figure now isn't the time.
> 
> The motivation for this feature was:
> 1. Bluetooth connections are hard to set up and can often take quite a bit of time, anywhere from 500 ms to 30 seconds. So once we have a Bluetooth connection we really want to keep it.
> 2. For demos we usually show some kind of chat app and so not losing our replication connection is useful for better looking demos
> 
> But the problem is that based on some of the perf results we are seeing in Bluetooth we seem to have an enormous fall off in bandwidth when we open more than one connection. In particular when a S7 talks to a 6P 1:1 the connection bandwidth is o.k. But if a S7 has two simultaneous connections open, one with another S7 and a second with a 6P for some reason the 6P will get allocated almost 0 bandwidth! The point being that for Bluetooth we may have to degenerate to only allowing a single Bluetooth socket at a time. In that case we need replications to finish up quick and get out of the way so we can talk to someone else.
> 
> For now I'm trying to make things a bit easier by reducing the wait to 3 seconds so that someone else will get a chance to talk to the device. In the long term we are going to switch from live replication to static replication and then let the peer policy manager decide if it wants to do another round of replication or not.
</details>
OK, thanks for explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1387)*

**Pull request merged**
