### PR TITLE
#897 implemented 1, 3, 4, 5 tasks

### PR DESCRIPTION
**Pull request by squid48**
Implemented new start and stop methods separated by platforms
nonTCPPeerAvailabilityChanged return null for iOS platform
startUpdateAdvertisingAndListening get router port on iOS platform
Added skipOnIOS and skipOnAndroid methods to testUtils
Some changes at getSamePeerWithRetry in testUtils
Have been written tests for new features.
Implemented incomingConnectionToPortNumberFailed for iOS platform	

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1505)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ff07d87)

**Comment by ThaliTester** [comment]
Test (Success) 93142442 build is completed (ff07d87)

See https://github.com/ThaliTester/TestResults/tree/93142442ff07d87__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 93142442ff07d87(ff07d87) has failed

See https://github.com/ThaliTester/TestResults/tree/93142442ff07d87__897_implemented_1__3__4__5_tasks_squid48/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d59ab6f)

**Comment by ThaliTester** [comment]
Test (Success) 93142442 build is completed (d59ab6f)

See https://github.com/ThaliTester/TestResults/tree/93142442d59ab6f__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 93142442d59ab6f(d59ab6f) has failed

See https://github.com/ThaliTester/TestResults/tree/93142442d59ab6f__897_implemented_1__3__4__5_tasks_squid48/ for the fail logs

**Comment by chapko** [comment]
Reviewed 3 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 427 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWIAATgRm5NlOj7wibf:-KWIAATgRm5NlOj7wibg:bpz8jd1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d59ab6fd7782f7bc1db54b3f9b47e1e4c44406cb/test/www/jxcore/lib/testUtils.js#L427)):*
> ```JavaScript
>           })
>         } else {
>           callTryAgain(peerID);
> ```

`callTryAgain` expects port, not `peerID`.

---

*[test/www/jxcore/lib/testUtils.js, line 430 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWICik0bu4h1rClEOQz:-KWICik0bu4h1rClEOR-:bfhewd9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d59ab6fd7782f7bc1db54b3f9b47e1e4c44406cb/test/www/jxcore/lib/testUtils.js#L430)):*
> ```JavaScript
>         }
>       } else {
>         callTryAgain(record.portNumber);
> ```

If this is the second `nonTCPPeerAvailabilityChangedEvent` event for the same peerID on iOS, then `record.portNumber` will be `null`.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 372 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWIDrY_IJ-ULtyJiogj:-KWIDrY_IJ-ULtyJiogk:b4lp3er) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d59ab6fd7782f7bc1db54b3f9b47e1e4c44406cb/thali/NextGeneration/thaliMobileNativeWrapper.js#L372)):*
> ```JavaScript
>        if (error) {
>          errorDescriptions.stopAdvertisingError = new Error(error);
>          reject(errorDescriptions);
> ```

You have changed logic here. Previously if both `stopAdvertisingAndListening` and `stopListeningForAdvertisements` native calls have failed, then errorDescriptions would contain all errors. But here you reject promise instantly. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c2cfc52)

**Comment by ThaliTester** [comment]
Test (Fail) 93142442 build is completed (c2cfc52)

See https://github.com/ThaliTester/TestResults/tree/93142442c2cfc52__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (6aa0649)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (15a2319)

**Comment by ThaliTester** [comment]
Test 93142442 (6aa0649) build started.

**Comment by ThaliTester** [comment]
Test 93142442 (15a2319) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93142442 build is completed (15a2319)

See https://github.com/ThaliTester/TestResults/tree/9314244215a2319__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by chapko** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/www/jxcore/lib/testUtils.js, line 403 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWrYHraPudGu1U7-Fqx:-KWrYHraPudGu1U7-Fqy:b-rc7kc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15a2319d12e3a385b7592adcd3d64d06fe47505d/test/www/jxcore/lib/testUtils.js#L403)):*
> ```JavaScript
> 
>     function getPort(peerID) {
>       return new Promise(function(resolve, reject) {
> ```

There is no need to wrap it into Promise constructor, `_multiConnect` already returns a promise.

---

*[test/www/jxcore/lib/testUtils.js, line 408 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWrZ9UkYwgreerFnfc_:-KWrZ9UkYwgreerFnfca:blp91n8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15a2319d12e3a385b7592adcd3d64d06fe47505d/test/www/jxcore/lib/testUtils.js#L408)):*
> ```JavaScript
>           .then(function(portNumber){
>             resolve(portNumber);
>           });
> ```

`_multiConnect` might fail and it is not handled anywhere.

---

*[test/www/jxcore/lib/testUtils.js, line 435 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWrZaqpwKHzFofRstsm:-KWrZaqpwKHzFofRstsn:b-g0lzak) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15a2319d12e3a385b7592adcd3d64d06fe47505d/test/www/jxcore/lib/testUtils.js#L435)):*
> ```JavaScript
>       .then(function(port) {
>         (port) ? callTryAgain(port) : callTryAgain(record.portNumber);
>       });
> ```

`getPort` might fail. I believe it should be handled the same way as request error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (641277d)

**Comment by ThaliTester** [comment]
Test 93142442 (641277d) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93142442 build is completed (641277d)

See https://github.com/ThaliTester/TestResults/tree/93142442641277d__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4b20274)

**Comment by ThaliTester** [comment]
Test 93142442 (4b20274) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93142442 build is completed (4b20274)

See https://github.com/ThaliTester/TestResults/tree/931424424b20274__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0cf4179)

**Comment by ThaliTester** [comment]
Test 93142442 (0cf4179) build started.

**Comment by ThaliTester** [comment]
Test (Success) 93142442 build is completed (0cf4179)

See https://github.com/ThaliTester/TestResults/tree/931424420cf4179__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 931424420cf4179(0cf4179) has failed

See https://github.com/ThaliTester/TestResults/tree/931424420cf4179__897_implemented_1__3__4__5_tasks_squid48/ for the fail logs

**Comment by chapko** [comment]
1. move cleanup code to the `exitCall` function
2. :lgtm:

---

Reviewed 3 of 3 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/testUtils.js, line 410 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX68UsBcjnNuuuajFUU:-KX68UsBcjnNuuuajFUV:br1a2xr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0cf41796004b0948e2dae4f2cf70524bc3acc6dc/test/www/jxcore/lib/testUtils.js#L410)):*
> ```JavaScript
> 
>     var timeoutId = setTimeout(function () {
>       clearTimeout(cancelGetPortTimeout);
> ```

I would move it to the `exitCall` function which contains final cleanup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-:-KX6DJJLn4N4DOfJSLv_:b5klwrw)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (9bf0021)

**Comment by ThaliTester** [comment]
Test 93142442 (9bf0021) build started.

**Comment by ThaliTester** [comment]
Test (Success) 93142442 build is completed (9bf0021)

See https://github.com/ThaliTester/TestResults/tree/931424429bf0021__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 931424429bf0021(9bf0021) has failed

See https://github.com/ThaliTester/TestResults/tree/931424429bf0021__897_implemented_1__3__4__5_tasks_squid48/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 5 files at r2, 2 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 428 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8YyMOvy1DQIae8blc:-KX8YbZqr1mUxc8LKEvH:b-xls5r5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L428)):*
> ```JavaScript
> test('thaliMobileNativeWrapper is stopped when routerPortConnectionFailed ' +
>   'is received',
>   testUtils.skipOnIOS,
> ```

But iOS is also required to return incomingConnectionToPortNumberFailed so why is this test disabled for iOS?

---

*[test/www/jxcore/lib/testUtils.js, line 430 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWICik0bu4h1rClEOQz:-KX8UY7RUdw0axMKZO3V:bn82lrh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d59ab6fd7782f7bc1db54b3f9b47e1e4c44406cb/test/www/jxcore/lib/testUtils.js#L430)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> If this is the second `nonTCPPeerAvailabilityChangedEvent` event for the same peerID on iOS, then `record.portNumber` will be `null`.
</details>
Which anyway should have been checked above since this function explicitly ignores unavailability events. See my note above.

---

*[test/www/jxcore/lib/testUtils.js, line 408 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWrZ9UkYwgreerFnfc_:-KX8VMt-JgBKBN7FL-k4:b32v57) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15a2319d12e3a385b7592adcd3d64d06fe47505d/test/www/jxcore/lib/testUtils.js#L408)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> `_multiConnect` might fail and it is not handled anywhere.
</details>
+1

---

*[test/www/jxcore/lib/testUtils.js, line 383 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8SffXPs8BwLm9VfUZ:-KX8SffXPs8BwLm9VfU_:b-icz0l8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L383)):*
> ```JavaScript
>   // We don't load thaliMobileNativeWrapper until after the tests have started
>   // running so we pick up the right version of mobile
>   var thaliMobileNativeWrapper = require('thali/NextGeneration/thaliMobileNativeWrapper');
> ```

Please lint this file. It takes a few minutes and makes everything so much nicer.

---

*[test/www/jxcore/lib/testUtils.js, line 469 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8TGWjnst8kSl0IR1M:-KX8TGWkZs-hipPcncrC:b-6nkf8o) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L469)):*
> ```JavaScript
>     function nonTCPAvailableHandler(record) {
>       // Ignore peer unavailable events
>       if (peerID && record.peerIdentifier === peerID) {
> ```

This code was supposed to ignore peer unavailable events. That was checked via the record.portNumber === null check that was deleted. How did we get any tests passing with this bug?

---

*[test/www/jxcore/lib/testUtils.js, line 484 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8UasiMZL8htY_Hh6z:-KX8UasiMZL8htY_Hh7-:b-u59gxm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L484)):*
> ```JavaScript
>       }
> 
>       getPort(peerID)
> ```

I think you need to change the getPort function design. It is surprising. First, it says 'getPort' which is true IFF we are dealing with iOS. As a result it sometimes returns a port and sometimes returns null except null isn't an error. That just smells wrong. Please change getPort so it does what it says, gets the port, it should be able to work with both iOS and Android. It just means moving the inline if below into the getPort function.

---

*[test/www/jxcore/lib/testUtils.js, line 776 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8R8jXehOoqEJQ5UVx:-KX8R8jXehOoqEJQ5UVy:b-9dixju) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L776)):*
> ```JavaScript
> };
> 
> module.exports.skipOnIOS = function () {
> ```

I'm worried about these names because the mock will make isIOS or isAndroid true. So are these functions intended to work with the mock and real systems? The name should somehow indicate this. Also shouldn't this be in the platform.js file not here?

---

*[test/www/jxcore/lib/testUtils.js, line 780 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8RJlJNr53bCKCCHYp:-KX8RJlJNr53bCKCCHYq:b9hn9fc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L780)):*
> ```JavaScript
> };
> 
> module.exports.skipOnAndroid = function () {
> ```

See my comments on skipOnIOS

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 368 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX7LyUecM9hNVtTfCMi:-KX7LyUfssKWywQPxeGG:b-el3r0o) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8c5a726f1a67834844e1ea0252f03b3c1448d890/thali/NextGeneration/thaliMobileNativeWrapper.js#L368)):*
> ```JavaScript
>  *
>  * @returns {Promise<?Error>}
>  */
> ```

Why was the method description moved from the export to the private method? Don't we want the description on the export so it is easily visible and discoverable to those using documentation to understand the system?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0ae5e52)

**Comment by ThaliTester** [comment]
Test 93142442 (0ae5e52) build started.

**Comment by squid48** [comment]
Review status: 2 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 428 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8YyMOvy1DQIae8blc:-KXAjgmv1Km8CqF-y8TP:b-6yivy1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L428)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> But iOS is also required to return incomingConnectionToPortNumberFailed so why is this test disabled for iOS?
</details>
This test is only for tcpServersManager
There is another test for this functionality
Fixed in the test for native incomingConnectionToPortNumberFailed.

---

*[test/www/jxcore/lib/testUtils.js, line 430 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWICik0bu4h1rClEOQz:-KXAjTlW8ZNAm5XEnA0j:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d59ab6fd7782f7bc1db54b3f9b47e1e4c44406cb/test/www/jxcore/lib/testUtils.js#L430)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Which anyway should have been checked above since this function explicitly ignores unavailability events. See my note above.
</details>
Done.

---

*[test/www/jxcore/lib/testUtils.js, line 408 at r7](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KWrZ9UkYwgreerFnfc_:-KXAiNzWY67tMu2bGNP7:b-5wryjg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15a2319d12e3a385b7592adcd3d64d06fe47505d/test/www/jxcore/lib/testUtils.js#L408)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> +1
</details>
It's already done in getPort function.

---

*[test/www/jxcore/lib/testUtils.js, line 410 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX68UsBcjnNuuuajFUU:-KXAjcJDWJfRWb10O-wg:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0cf41796004b0948e2dae4f2cf70524bc3acc6dc/test/www/jxcore/lib/testUtils.js#L410)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> I would move it to the `exitCall` function which contains final cleanup.
</details>
Done.

---

*[test/www/jxcore/lib/testUtils.js, line 383 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8SffXPs8BwLm9VfUZ:-KXAjd44asoIRD0NjoZt:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L383)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Please lint this file. It takes a few minutes and makes everything so much nicer.
</details>
Done.

---

*[test/www/jxcore/lib/testUtils.js, line 469 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8TGWjnst8kSl0IR1M:-KXAjWvTDVwHX29HuQPJ:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L469)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> This code was supposed to ignore peer unavailable events. That was checked via the record.portNumber === null check that was deleted. How did we get any tests passing with this bug?
</details>
Done.

---

*[test/www/jxcore/lib/testUtils.js, line 484 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8UasiMZL8htY_Hh6z:-KXAjVcbGIbZ45hpJnTN:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L484)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> I think you need to change the getPort function design. It is surprising. First, it says 'getPort' which is true IFF we are dealing with iOS. As a result it sometimes returns a port and sometimes returns null except null isn't an error. That just smells wrong. Please change getPort so it does what it says, gets the port, it should be able to work with both iOS and Android. It just means moving the inline if below into the getPort function.
</details>
Done.

---

*[test/www/jxcore/lib/testUtils.js, line 776 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8R8jXehOoqEJQ5UVx:-KXAkDgIyfzeAtVR9Vng:b-kn5mc2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L776)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> I'm worried about these names because the mock will make isIOS or isAndroid true. So are these functions intended to work with the mock and real systems? The name should somehow indicate this. Also shouldn't this be in the platform.js file not here?
</details>
I think these names are ok, because we have the similar names in the platform.js.
It's should be in this file, because it's only used for the tests.

---

*[test/www/jxcore/lib/testUtils.js, line 780 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8RJlJNr53bCKCCHYp:-KXAn9_7DpjPE7PKPn4w:b-apayz0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L780)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> See my comments on skipOnIOS
</details>
See my comment above.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 368 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX7LyUecM9hNVtTfCMi:-KXAj9in90qXDF106et5:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8c5a726f1a67834844e1ea0252f03b3c1448d890/thali/NextGeneration/thaliMobileNativeWrapper.js#L368)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Why was the method description moved from the export to the private method? Don't we want the description on the export so it is easily visible and discoverable to those using documentation to understand the system?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505)*

**Comment by ThaliTester** [comment]
Test (Success) 93142442 build is completed (0ae5e52)

See https://github.com/ThaliTester/TestResults/tree/931424420ae5e52__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 931424420ae5e52(0ae5e52) has failed

See https://github.com/ThaliTester/TestResults/tree/931424420ae5e52__897_implemented_1__3__4__5_tasks_squid48/ for the fail logs

**Comment by larryonoff** [comment]
Review status: 2 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[test/www/jxcore/UnitTest_app.js, line 68 at r12](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KXBOA8Jp5hJSGWsYHY_:-KXBOA8Jp5hJSGWsYHYa:b5ujn7i) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0ae5e520005051dd87558f55ae03ecc3b5c3d384/test/www/jxcore/UnitTest_app.js#L68)):*
> ```JavaScript
> }
> //
> // if (platform.isIOS) {
> ```

why this is just commented? There should be explanation of commenting this or just remove this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505)*

**Comment by chapko** [comment]
Reviewed 3 of 3 files at r12.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 776 at r11](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KX8R8jXehOoqEJQ5UVx:-KXApdCBmlVlH4mcO0jt:b-mpsqd8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9bf00211910c051756b6d9fec94776020f847d96/test/www/jxcore/lib/testUtils.js#L776)):*
> So are these functions intended to work with the mock and real systems?

These skip functions are just shortcuts to be used in tests. It doesn't matter if this is a mock or a real device, because thali code depends only on `platform.isIOS` and `platform.isAndroid` values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dc3417b)

**Comment by ThaliTester** [comment]
Test 93142442 (dc3417b) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93142442 build is completed (dc3417b)

See https://github.com/ThaliTester/TestResults/tree/93142442dc3417b__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Comment by yaronyg** [comment]
Subject to:
1. Existing comments being resolved and marked approved by their originators (e.g. the comments from @chapko and @larryonoff)
2. Build actually passing in CI
then :lgtm: 

---

Reviewed 3 of 3 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-:-KXgNvOv9ve8rA8RCMnC:b-eg9e46)*

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-:-KXjO5A_3vHuIUAQnm6t:bnfp4nl)*

**Comment by chapko** [comment]
I think we don't need tests skipping on devices anymore. Let's remove it, and then :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/UnitTest_app.js, line 68 at r12](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-KXBOA8Jp5hJSGWsYHY_:-KXjm0lj9kI8w5SaHuwi:b7yarse) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0ae5e520005051dd87558f55ae03ecc3b5c3d384/test/www/jxcore/UnitTest_app.js#L68)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary><blockquote>

why this is just commented? There should be explanation of commenting this or just remove this line.
</blockquote></details>

Since we have already started testing on actual devices, I suggest to just remove these lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1505#-:-KXjmTs_x6Hc0dbR4nxz:b99vbj)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (644c47b)

**Comment by ThaliTester** [comment]
Test 93142442 (644c47b) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93142442 build is completed (644c47b)

See https://github.com/ThaliTester/TestResults/tree/93142442644c47b__897_implemented_1__3__4__5_tasks_squid48/ for the logs

**Pull request closed without merging**
