### PR TITLE
Adding a bunch more logging

### PR DESCRIPTION
**Pull request by yaronyg**
This PR should not have any functional changes. Just additional logging.

One thing to be aware of is that I have found that %j formatting in logger.debug is very finicky. In some cases where I passed in Javascript objects it printed nothing, not even undefined. I'm not sure if this is something to do with Winston or whatever but I don't have time to investigate so when I ran into this issue I replaced the %j with a %s and did the JSON.stringify() myself.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1456)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4e53433)

**Comment by ThaliTester** [comment]
Test (Success) 91437709 build is completed (4e53433)

See https://github.com/ThaliTester/TestResults/tree/914377094e53433_Adding_a_bunch_more_logging_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 914377094e53433(4e53433) has failed

See https://github.com/ThaliTester/TestResults/tree/914377094e53433_Adding_a_bunch_more_logging_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
Changes will come in via #1458

**Pull request closed without merging**
