### PR TITLE
[Android] Make unit tests run

### PR DESCRIPTION
**Pull request by tompaana**
Contains major fixes to make the unit tests run on Android.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/595)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9e08672)

**Comment by ThaliTester** [comment]
Build is completed (Success) but couldn't commit the log file. (9e08672)


warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Everything up-to-date
Switched to branch 'master'
fatal: '614093909e08672_[Android]_Make_unit_tests_run_tompaana' is not a valid branch name.
error: pathspec '614093909e08672_[Android]_Make_unit_tests_run_tompaana' did not match any file(s) known to git.


Error: Command failed: warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Everything up-to-date
Switched to branch 'master'
fatal: '614093909e08672_[Android]_Make_unit_tests_run_tompaana' is not a valid branch name.
error: pathspec '614093909e08672_[Android]_Make_unit_tests_run_tompaana' did not match any file(s) known to git.


null

**Comment by yaronyg** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 176 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595#-KBt-L2epGVBXLDSychQ:-KBt-L2epGVBXLDSychR:-1675098819) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e08672d2e4b43b8ca62932d15e65c9603e3f2d0/src/android/java/io/jxcore/node/HandshakeHelper.java#L176)):*
Be nice to remove the commented out code :)

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 602 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595#-KBsu5KClnZSrF9JXyY7:-KBsu5KClnZSrF9JXyY8:80219642) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e08672d2e4b43b8ca62932d15e65c9603e3f2d0/src/android/java/io/jxcore/node/JXcoreExtension.java#L602)):*
I think there may be a fairly subtle misunderstanding of the spec. When we call startListeningForAdvertisements this translates in Android land to setting up a BLE central (e.g. listen for BLE peripherals). If an interesting peer is discovered then a connect call will be sent down to open a bluetooth socket.

When we call startUpdateAdvertisingAndListening this translates in Android land to setting up a BLE peripheral (e.g. advertise to BLE centrals) as well as a Bluetooth Server.

So this means that if we call startListeningForAdvertisements and not startUpdateAdvertisingAndListening then we would have a BLE central running, but nothing else. If I'm reading the code right then anytime start is called on the ConnectionManager we will kick off a Bluetooth listener. And in StartStopOperationQueue it looks like all start operations (e.g. both startLIsteningForAdvertisements and startUpdateAdvertisingAndListening) always call connection manager's start method. So this means we would have a Bluetooth server listening for connections when we call startListeningForAdvertisements and that isn't the idea.

Did I read the code right?

---

*[src/android/java/io/jxcore/node/StartStopOperationQueue.java, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595#-KBsptdZhgPJobD-69F-:-KBsptdZhgPJobD-69F0:-1302836618) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e08672d2e4b43b8ca62932d15e65c9603e3f2d0/src/android/java/io/jxcore/node/StartStopOperationQueue.java#L1)):*
Why do we need queuing logic? We promise you in the contract at the Node.js layer that with the exception of connect calls we will not call any other API on native in parallel. In other words, we already build and maintain this queue up stream. So having it in two places is just an extra source of bugs.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6d6b12e)

**Comment by tompaana** [comment]
Review status: 8 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/HandshakeHelper.java, line 176 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595#-KBt-L2epGVBXLDSychQ:-KBt3ZANiifpEiixdVPr:1398484727) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e08672d2e4b43b8ca62932d15e65c9603e3f2d0/src/android/java/io/jxcore/node/HandshakeHelper.java#L176)):*
Oops. My bad. Fixed.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 602 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595#-KBsu5KClnZSrF9JXyY7:-KBvlQRjvNxKjr_VOZja:1664072819) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e08672d2e4b43b8ca62932d15e65c9603e3f2d0/src/android/java/io/jxcore/node/JXcoreExtension.java#L602)):*
You did read it right. Fixed the code, but: Should we be able to connect (establish outgoing connection) when we have no Bluetooth listener? If yes, I need to make a minor change to the library since currently you can connect only if ConnectionManager is started.

---

*[src/android/java/io/jxcore/node/StartStopOperationQueue.java, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595#-KBsptdZhgPJobD-69F-:-KBvl3ZKtb-63xRjszMC:396559444) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e08672d2e4b43b8ca62932d15e65c9603e3f2d0/src/android/java/io/jxcore/node/StartStopOperationQueue.java#L1)):*
Goes to show I don't know the node layer too well. Removed the queue. Now if it gets a new start/stop operation, the previous is cancelled.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595)*

**Comment by ThaliTester** [comment]
Build is completed (Success) but couldn't commit the log file. (6d6b12e)


warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Everything up-to-date
Switched to branch 'master'
fatal: '614093906d6b12e_[Android]_Make_unit_tests_run_tompaana' is not a valid branch name.
error: pathspec '614093906d6b12e_[Android]_Make_unit_tests_run_tompaana' did not match any file(s) known to git.


Error: Command failed: warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Everything up-to-date
Switched to branch 'master'
fatal: '614093906d6b12e_[Android]_Make_unit_tests_run_tompaana' is not a valid branch name.
error: pathspec '614093906d6b12e_[Android]_Make_unit_tests_run_tompaana' did not match any file(s) known to git.


null

**Comment by yaronyg** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 602 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595#-KBsu5KClnZSrF9JXyY7:-KBxbAQ4v4jiv__b3FX6:-1867921618) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e08672d2e4b43b8ca62932d15e65c9603e3f2d0/src/android/java/io/jxcore/node/JXcoreExtension.java#L602)):*
We should be able to make outgoing connections when there is no bluetooth server. The scenario is that a device has no new information to advertise. So it isn't listening for incoming connections because it isn't advertising anything. But it is interested to see if other folks have something for it, so it is listening for BLE peripherals. If it finds an interesting BLE peripheral then it needs to be able to connect to the device's Bluetooth server to pull down the beacons and data. So it would need to connect even though it isn't running a bluetooth server itself.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595)*

**Comment by tompaana** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 602 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595#-KBsu5KClnZSrF9JXyY7:-KC-aclbqa8Twqlg6EKI:1956855973) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e08672d2e4b43b8ca62932d15e65c9603e3f2d0/src/android/java/io/jxcore/node/JXcoreExtension.java#L602)):*
ACK. I'll implement the change in the library.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/595)*

**Pull request merged**
