### PR TITLE
Clean ups and refactoring

### PR DESCRIPTION
**Pull request by yaronyg**
Mostly just linting and refactoring

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/597)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1d889bb)

**Comment by ThaliTester** [comment]
Test (Success) 61658198 build is completed (1d889bb)

See https://github.com/ThaliTester/TestResults/tree/616581981d889bb_Clean_ups_and_refactoring_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 616581981d889bb(1d889bb) has failed

See https://github.com/ThaliTester/TestResults/tree/616581981d889bb_Clean_ups_and_refactoring_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (76c87fb)

**Comment by ThaliTester** [comment]
Test (Success) 61658198 build is completed (76c87fb)

See https://github.com/ThaliTester/TestResults/tree/6165819876c87fb_Clean_ups_and_refactoring_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 6165819876c87fb(76c87fb) has failed

See https://github.com/ThaliTester/TestResults/tree/6165819876c87fb_Clean_ups_and_refactoring_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 14 of 19 files at r3, 5 of 9 files at r4, 3 of 3 files at r5.
Review status: 22 of 24 files reviewed at latest revision, 6 unresolved discussions.

---

*[thali/NextGeneration/mux/createNativeListener.js, line 135 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/597#-KCFBOyTJ9a4Wn3rBqAb:-KCFBOyUQJxdUPpkEQIB:-1155044050) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76c87fbc22c143f6b96e80f2bc21e21ab130e811/thali/NextGeneration/mux/createNativeListener.js#L135)):*
NB: It might be better to call the argument something like "tcpServersManager" instead of "self" now that this is a separate module.

---

*[thali/NextGeneration/mux/createNativeListener.js, line 137 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/597#-KCFBiDmCqgDI1TPScos:-KCFBiDmCqgDI1TPScot:473860605) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76c87fbc22c143f6b96e80f2bc21e21ab130e811/thali/NextGeneration/mux/createNativeListener.js#L137)):*
Instead of throwing, should we return a promise with the correct error?

---

*[thali/NextGeneration/mux/createNativeListener.js, line 142 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/597#-KCFBrIGiDGKlmP3GqpH:-KCFBrIGiDGKlmP3GqpI:1825643046) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76c87fbc22c143f6b96e80f2bc21e21ab130e811/thali/NextGeneration/mux/createNativeListener.js#L142)):*
See previous comment.

---

*[thali/NextGeneration/mux/thaliTcpServersManager.js, line 183 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/597#-KCFDaVZ2RV2p_Giikda:-KCFDaVZ2RV2p_Giikdb:2031597913) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76c87fbc22c143f6b96e80f2bc21e21ab130e811/thali/NextGeneration/mux/thaliTcpServersManager.js#L183)):*
Should this return a promise?

---

*[thali/NextGeneration/mux/thaliTcpServersManager.js, line 227 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/597#-KCFDibXOeoFcmZv21jd:-KCFDibXOeoFcmZv21je:-781736385) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76c87fbc22c143f6b96e80f2bc21e21ab130e811/thali/NextGeneration/mux/thaliTcpServersManager.js#L227)):*
Same as previous comment.

---

*[thali/NextGeneration/mux/thaliTcpServersManager.js, line 653 \[r5\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/597#-KCFEP3KV0jUCvqgWGxf:-KCFEP3KV0jUCvqgWGxg:1936886653) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/76c87fbc22c143f6b96e80f2bc21e21ab130e811/thali/NextGeneration/mux/thaliTcpServersManager.js#L653)):*
Mobile('connect') returns connection as string so JSON parsing is required before referring to the properties.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/597)*

**Comment by vjrantal** [comment]
@yaronyg: I started doing a code review for this but it was tricky to determine which lines are considered "final" and which work in progress, because due to file name changes, pretty much all lines are shown as changed. I propose you self-review this and just merge to `vNext_tobe_issue358`. I'll do the code review for everything once you are ready to merge `vNext_tobe_issue358` into `vNext` since then, there shouldn't much work in progress left anymore.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (17b6ba8)

**Comment by ThaliTester** [comment]
Test (Fail) 61658198 build is completed (17b6ba8)

See https://github.com/ThaliTester/TestResults/tree/6165819817b6ba8_Clean_ups_and_refactoring_yaronyg/ for the logs

**Pull request merged**
