### PR TITLE
Remove old code from MUX

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1495)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1287328)

**Comment by ThaliTester** [comment]
Test (Success) 92434721 build is completed (1287328)

See https://github.com/ThaliTester/TestResults/tree/924347211287328_Master_901_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 924347211287328(1287328) has failed

See https://github.com/ThaliTester/TestResults/tree/924347211287328_Master_901_yaronyg/ for the fail logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 368 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1495#-KW2P-j3tJe2DCMQwKJN:-KW2P-j3tJe2DCMQwKJO:b-dyvdlc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/1287328d570205a280397c761bc14cc22e5282f3/test/www/jxcore/bv_tests/testThaliMobileNative.js#L368)):*
> ```JavaScript
>     logger.info(connection);
> 
>     logger.error('foo ' + JSON.stringify(connection));
> ```

NB: Looks like it shouldn't be here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1495#-:-KW2TKh5WMkRnQdV9TNx:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3a23a0d)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (4c5b967)

**Comment by yaronyg** [comment]
Review status: 11 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 368 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1495#-KW2P-j3tJe2DCMQwKJN:-KWZOoaZzAsSZ1VrEhwx:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/1287328d570205a280397c761bc14cc22e5282f3/test/www/jxcore/bv_tests/testThaliMobileNative.js#L368)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> NB: Looks like it shouldn't be here.
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1495)*

**Comment by ThaliTester** [comment]
Test (Success) 92434721 build is completed (3a23a0d)

See https://github.com/ThaliTester/TestResults/tree/924347213a23a0d_Remove_old_code_from_MUX_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 924347213a23a0d(3a23a0d) has failed

See https://github.com/ThaliTester/TestResults/tree/924347213a23a0d_Remove_old_code_from_MUX_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Fail) 92434721 build is completed (4c5b967)

See https://github.com/ThaliTester/TestResults/tree/924347214c5b967_Remove_old_code_from_MUX_yaronyg/ for the logs

**Pull request merged**
