### PR TITLE
Fixed race condition from tearDown in StartStopOperationTest

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1026)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (88ca170)

**Comment by ThaliTester** [comment]
Test (Fail) 85009927 build is completed (88ca170)

See https://github.com/ThaliTester/TestResults/tree/8500992788ca170_Fixed_race_condition_from_tearDown_in_StartStopOperationTest_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (e02c5f0)

**Comment by ThaliTester** [comment]
Test (Success) 85009927 build is completed (e02c5f0)

See https://github.com/ThaliTester/TestResults/tree/85009927e02c5f0_Fixed_race_condition_from_tearDown_in_StartStopOperationTest_evabishchevich/ for the logs

**Comment by larryonoff** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 85 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026#-KRYDoahLI6EMooKZUQN:-KRYDoahLI6EMooKZUQO:bglmq2r) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e02c5f04a2e91d2f3dfff747859b347b34a872b6/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L85)):*
> ```Java
>      * outcome) and if so, calls its callback.
>      */
>     public synchronized void checkCurrentOperationStatus() {
> ```

I understand that this isn't scope of this PR, but the signature of this method lies. It doesn't just check, it also sets current operation to `null` if operation is successful. So I thin this method should be renamed in something like `handleCurrentSuccessfulOperation`.

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 179 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026#-KRYEPgWM3Qo9R2MbgBr:-KRYEPgWM3Qo9R2MbgBs:b-abwlfg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e02c5f04a2e91d2f3dfff747859b347b34a872b6/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L179)):*
> ```Java
>     }
> 
>     private void cancelTimer() {
> ```

I think this method should be renamed in `cancelOperationTimeoutTimer` just to be clear. So in this case we won't even need documenting this method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026)*

**Comment by ThaliTester** [comment]
Test 85009927e02c5f0(e02c5f0) has failed

See https://github.com/ThaliTester/TestResults/tree/85009927e02c5f0_Fixed_race_condition_from_tearDown_in_StartStopOperationTest_evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
There are the same failed tests that were in parent branch. 
I'm going to review Ilya's comments if I have time for that tomorrow

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (f6c88da)

**Comment by ThaliTester** [comment]
Test (Fail) 85009927 build is completed (f6c88da)

See https://github.com/ThaliTester/TestResults/tree/85009927f6c88da_Fixed_race_condition_from_tearDown_in_StartStopOperationTest_evabishchevich/ for the logs

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026#-:-KS0trFU7SdnWplLvx65:bnfp4nl)*

**Comment by larryonoff** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 85 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026#-KRYDoahLI6EMooKZUQN:-KS0ttQHHbSgUZqPSU_K:b32w0x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e02c5f04a2e91d2f3dfff747859b347b34a872b6/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L85)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I understand that this isn't scope of this PR, but the signature of this method lies. It doesn't just check, it also sets current operation to `null` if operation is successful. So I thin this method should be renamed in something like `handleCurrentSuccessfulOperation`.
</details>
OK

---

*[src/android/java/io/jxcore/node/StartStopOperationHandler.java, line 179 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026#-KRYEPgWM3Qo9R2MbgBr:-KS0twv7p6VPhhNNfWe6:b32w0x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e02c5f04a2e91d2f3dfff747859b347b34a872b6/src/android/java/io/jxcore/node/StartStopOperationHandler.java#L179)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I think this method should be renamed in `cancelOperationTimeoutTimer` just to be clear. So in this case we won't even need documenting this method.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026)*

**Comment by larryonoff** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026)*

**Comment by yaronyg** [comment]
I have one non-blocking comment so you are :lgtm: . Please check in once we get it passing in CI. And who broke testUtils?

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java, line 199 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026#-KS2z2zzz5ObrlT80USm:-KS2z3--ArWzfrUQu6hN:baan5lc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f6c88da02361f35b67a1a11ee6364f3eba4dc372/src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java#L199)):*
> ```Java
> 
>             mStartStopOperationHandler.processCurrentOperationStatus();
>             Thread.sleep(3000);
> ```

NB: why do we have a magic sleep here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026#-:-KS2zC_9-T_NIJjJwNTb:brmk8hi)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java, line 199 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026#-KS2z2zzz5ObrlT80USm:-KS5qV1BO44xmDgT82Ux:b-kx4mj9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/f6c88da02361f35b67a1a11ee6364f3eba4dc372/src/android/test/io/jxcore/node/StartStopOperationHandlerTest.java#L199)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: why do we have a magic sleep here?
</details>
Marcin has already changed it in 1054. We'll get these changes when we merge with vNext.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1026)*

**Pull request merged**
