### PR TITLE
Merge wifiBasedNativeMock into iOS branch

### PR DESCRIPTION
**Pull request by chapko**
This is `superbranch_android` branch which contains only #1185 PR and fix for #1255. Since we are submitting all the android node changes into iOS branch instead of android branch I suggest to simply merge it into iOS.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1256)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d30a103)

**Comment by ThaliTester** [comment]
Test (Success) 88123934 build is completed (d30a103)

See https://github.com/ThaliTester/TestResults/tree/88123934d30a103_Merge_wifiBasedNativeMock_into_iOS_branch_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 88123934d30a103(d30a103) has failed

See https://github.com/ThaliTester/TestResults/tree/88123934d30a103_Merge_wifiBasedNativeMock_into_iOS_branch_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm: I'm merging this now so I can use it for my own work.

---

Reviewed 1 of 9 files at r1, 8 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1256#-:-KTLWielajz0LSTy1qXz:bf1cuxk)*

**Pull request merged**
