### PR TITLE
There is no unit tests for discoveryAdvertisingStateUpdateNonTCP of thaliMobileNative.js #868

### PR DESCRIPTION
**Pull request by opetkevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1838)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aab4ee7)

**Comment by ThaliTester** [comment]
Test 111941151 (aab4ee7) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 111941151 build is completed (aab4ee7)

See https://github.com/ThaliTester/TestResults/tree/111941151aab4ee7_There_is_no_unit_tests_for_discoveryAdvertisingStateUpdateNonTCP_of_thaliMobileNative_js__868_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3ed0d6e)

**Comment by ThaliTester** [comment]
Test 111941151 (3ed0d6e) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 111941151 build is completed (3ed0d6e)

See https://github.com/ThaliTester/TestResults/tree/1119411513ed0d6e_There_is_no_unit_tests_for_discoveryAdvertisingStateUpdateNonTCP_of_thaliMobileNative_js__868_opetkevich/ for the logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1838#-:-Kfq0usGhupTGLRI2Bir:bnfp4nl)*

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1838)*

**Comment by jareksl** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1838#-:-Kfub0YRm7yaKx3_ZOPI:bg7igkv)*

**Comment by jareksl** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1838)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1838#-:-KfvrZNulzWFDnFLgwlj:bnfp4nl)*

**Pull request merged**
