### PR TITLE
Fixed thali manager stop method

### PR DESCRIPTION
**Pull request by andrew-aladev**
Related to #1596.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1645)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (61e9bd5)

**Comment by ThaliTester** [comment]
Test 97990244 (61e9bd5) build started.

**Comment by ThaliTester** [comment]
Test (Success) 97990244 build is completed (61e9bd5)

See https://github.com/ThaliTester/TestResults/tree/9799024461e9bd5_Fixed_thali_manager_stop_method_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 9799024461e9bd5(61e9bd5) has failed

See https://github.com/ThaliTester/TestResults/tree/9799024461e9bd5_Fixed_thali_manager_stop_method_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 5 of 10 files at r7, 5 of 5 files at r8, 7 of 7 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1645#-:-KYyUA2EHlvGROt2ye9b:bnfp4nl)*

**Pull request merged**
