### PR TITLE
Fixed thaliTestMobileNative

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/867)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (665e562)

**Comment by ThaliTester** [comment]
Test (Success) 81321942 build is completed (665e562)

See https://github.com/ThaliTester/TestResults/tree/81321942665e562_Fixed_thaliTestMobileNative_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 81321942665e562(665e562) has failed

See https://github.com/ThaliTester/TestResults/tree/81321942665e562_Fixed_thaliTestMobileNative_evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

Obviously we can't check it in though until it passes CI

@evabishchevich you need to drive investigating problems with this issue. So you need to look through the logs to see what failed and then ask for help from various people (node, CI, etc.) as you need it. But you are the leader of making sure this PR gets in.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/867#-KPF3Zv76wCOYRC8_9SN:-KPF3Zv86Lx9Mqulprs8:b-hazk67) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/665e562d1119ac20ba18179c8bb3f87cfcaa1435/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L1)):*
> ```JavaScript
> //'use strict';
> ```

NB: Please open a bug telling us we need to re-enable this test.

---

*[test/www/jxcore/bv_tests/testThaliSendNotificationBasedOnReplication.js, line 423 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/867#-KPF3iK833qs-VYbwmrp:-KPF3iK833qs-VYbwmrq:buzorpo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/665e562d1119ac20ba18179c8bb3f87cfcaa1435/test/www/jxcore/bv_tests/testThaliSendNotificationBasedOnReplication.js#L423)):*
> ```JavaScript
> });
> 
> //test('add doc and make sure tokens refresh when they expire', function (t) {
> ```

NB: Please add to the previous bug that we need to re-enable this test as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/867#-:-KPF3ova6ZX-dbu9zrtf:bcotsci)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 1 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/867#-KPF3Zv76wCOYRC8_9SN:-KPHXcuXiLj8JpwGnkCS:b-i72n76) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/665e562d1119ac20ba18179c8bb3f87cfcaa1435/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L1)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Please open a bug telling us we need to re-enable this test.
</details>
Done in #883 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/867)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliSendNotificationBasedOnReplication.js, line 423 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/867#-KPF3iK833qs-VYbwmrp:-KPHXjkK5ob9_BGT3yDE:b-i72n76) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/665e562d1119ac20ba18179c8bb3f87cfcaa1435/test/www/jxcore/bv_tests/testThaliSendNotificationBasedOnReplication.js#L423)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Please add to the previous bug that we need to re-enable this test as well.
</details>
Done in #883 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/867)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7e676a1)

**Comment by ThaliTester** [comment]
Test 813219427e676a1(7e676a1) has failed

See https://github.com/ThaliTester/TestResults/tree/813219427e676a1_Fixed_thaliTestMobileNative_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (ed45dd3)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (83357ce)

**Comment by ThaliTester** [comment]
Test (Fail) 81321942 build is completed (ed45dd3)

See https://github.com/ThaliTester/TestResults/tree/81321942ed45dd3_Fixed_thaliTestMobileNative_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 81321942 build is completed (83357ce)

See https://github.com/ThaliTester/TestResults/tree/8132194283357ce_Fixed_thaliTestMobileNative_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b5f2850)

**Comment by ThaliTester** [comment]
Test (Fail) 81321942 build is completed (b5f2850)

See https://github.com/ThaliTester/TestResults/tree/81321942b5f2850_Fixed_thaliTestMobileNative_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1985513)

**Comment by ThaliTester** [comment]
Test (Fail) 81321942 build is completed (1985513)

See https://github.com/ThaliTester/TestResults/tree/813219421985513_Fixed_thaliTestMobileNative_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e882373)

**Comment by ThaliTester** [comment]
Test (Fail) 81321942 build is completed (e882373)

See https://github.com/ThaliTester/TestResults/tree/81321942e882373_Fixed_thaliTestMobileNative_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a4a918a)

**Comment by ThaliTester** [comment]
Test (Fail) 81321942 build is completed (a4a918a)

See https://github.com/ThaliTester/TestResults/tree/81321942a4a918a_Fixed_thaliTestMobileNative_evabishchevich/ for the logs

**Pull request closed without merging**
