### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by cicorias**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/704)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4cf5745)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (46f0d89)

**Comment by ThaliTester** [comment]
Test (Success) 65681676 build is completed (4cf5745)

See https://github.com/ThaliTester/TestResults/tree/656816764cf5745_fix_build_cicorias/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 65681676 build is completed (46f0d89)

See https://github.com/ThaliTester/TestResults/tree/6568167646f0d89_fix_build_cicorias/ for the logs

**Comment by ThaliTester** [comment]
Test 656816764cf5745(4cf5745) has failed

See https://github.com/ThaliTester/TestResults/tree/656816764cf5745_fix_build_cicorias/ for the fail logs

**Comment by ThaliTester** [comment]
Test 6568167646f0d89(46f0d89) has failed

See https://github.com/ThaliTester/TestResults/tree/6568167646f0d89_fix_build_cicorias/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/704)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/704#-:-KEmNkCLvPerfMIGxbhv:1417088721)*

**Pull request merged**
