### PR TITLE
Implemented iOS native-mode functionality #900, #1585, #1611

### PR DESCRIPTION
**Pull request by squid48**
Implemented iOS native-mode functionality #900, #1585, #1611

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1616)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (66ea5e0)

**Comment by ThaliTester** [comment]
Test 96918947 (66ea5e0) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96918947 build is completed (66ea5e0)

See https://github.com/ThaliTester/TestResults/tree/9691894766ea5e0_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 9691894766ea5e0(66ea5e0) has failed

See https://github.com/ThaliTester/TestResults/tree/9691894766ea5e0_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the fail logs

**Comment by chapko** [comment]
-@chapko +@squid48 

---

Reviewed 2 of 7 files at r1, 5 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1273 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KZax-j0KMAjr8U-KXHu:-KZax-j0KMAjr8U-KXHv:b-u8yv64) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11ccdf7ee8bfbe132fc8245cb7d16b14b55119ff/test/www/jxcore/bv_tests/testThaliMobile.js#L1273)):*
> ```JavaScript
>     ThaliMobile.emitter.on('peerAvailabilityChanged', availabilityHandler);
> 
>     emitNativePeerAvailability(nativePeer);
> ```

It should test that when we have peer in the thaliMobile cache and we got multiConnectConnectionFailure from native layer for this peer it should fire peerAvailabilityChanged event(s). But it does completely different thing.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js, line 182 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KZay7CzH5uLsGUJdoaJ:-KZay7CzH5uLsGUJdoaK:b-60di24) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11ccdf7ee8bfbe132fc8245cb7d16b14b55119ff/test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js#L182)):*
> ```JavaScript
> test('Get same port when trying to connect multiple times on iOS',
>   function () {
>     // FIXME: #1609
> ```

It looks like this issue has been already fixed.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 668 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KZb4N5TUuvbdYWB295r:-KZb4N5TUuvbdYWB295s:bqz3krk) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11ccdf7ee8bfbe132fc8245cb7d16b14b55119ff/thali/NextGeneration/thaliMobileNativeWrapper.js#L668)):*
> ```JavaScript
> 
>           if (error) {
>             handleFailedNativeConnectionMPCF(peerIdentifier);
> ```

It should not happen after every error. Only after "Connection could not be established"

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 1021 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KZb5_HebMLCXB3qgqQb:-KZb5_HebMLCXB3qgqQc:b-gekgah) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11ccdf7ee8bfbe132fc8245cb7d16b14b55119ff/thali/NextGeneration/thaliMobileNativeWrapper.js#L1021)):*
> ```JavaScript
> }
> 
> var handleFailedNativeConnectionMPCF = function (peerIdentifier) {
> ```

I think it's better to rename it to something more meaningful

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-:-KZb669l7XjUmgRUGsiw:bojzvv3)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c32a898)

**Comment by ThaliTester** [comment]
Test 96918947 (c32a898) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96918947 build is completed (c32a898)

See https://github.com/ThaliTester/TestResults/tree/96918947c32a898_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f6e0261)

**Comment by ThaliTester** [comment]
Test 96918947 (f6e0261) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96918947 build is completed (f6e0261)

See https://github.com/ThaliTester/TestResults/tree/96918947f6e0261_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (783aa36)

**Comment by ThaliTester** [comment]
Test 96918947 (783aa36) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96918947 build is completed (783aa36)

See https://github.com/ThaliTester/TestResults/tree/96918947783aa36_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2b6b593)

**Comment by ThaliTester** [comment]
Test 96918947 (2b6b593) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96918947 build is completed (2b6b593)

See https://github.com/ThaliTester/TestResults/tree/969189472b6b593_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3645b2d)

**Comment by ThaliTester** [comment]
Test 96918947 (3645b2d) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96918947 build is completed (3645b2d)

See https://github.com/ThaliTester/TestResults/tree/969189473645b2d_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 969189473645b2d(3645b2d) has failed

See https://github.com/ThaliTester/TestResults/tree/969189473645b2d_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (377cdc2)

**Comment by ThaliTester** [comment]
Test 96918947 (377cdc2) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96918947 build is completed (377cdc2)

See https://github.com/ThaliTester/TestResults/tree/96918947377cdc2_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by chapko** [comment]
Reviewed 1 of 7 files at r5, 1 of 4 files at r6, 8 of 8 files at r10.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 896 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KahcRth55uxDOkVdwc0:-KahcRth55uxDOkVdwc1:b2boa7w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/test/www/jxcore/bv_tests/testThaliMobile.js#L896)):*
> ```JavaScript
>     emitNativePeerAvailability(nativePeer);
> 
>     end();
> ```

It is a bad idea to assume that events are processed synchronously.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1256 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-Kahe31Kpa91_ShIzFdm:-Kahe31LPLfO23-wsnJX:bnult8t) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/test/www/jxcore/bv_tests/testThaliMobile.js#L1256)):*
> ```JavaScript
> );
> 
> test('multiconnect failure - new peer is ignored (MPCF)',
> ```

This test does not make sense now, because nobody listens to 'failedNativeConnection' events in the thali code.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 2023 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KahiKTPDrrCKBQ2zk-8:-KahiKTQTEWoOuWWSI1N:b-xlg69h) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/test/www/jxcore/bv_tests/testThaliMobile.js#L2023)):*
> ```JavaScript
> 
>   var cleanUpCalled = false;
>   // jshint latedef:false
> ```

we moved to the eslint

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 204 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KalKFLIGf46DyIbcv34:-KalKFLJ6X0dJdeegX_R:b-r8csty) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L204)):*
> ```JavaScript
>     var connection = net.createConnection(port, function () {
>       connection.destroy();
>       reversed ? reject() : resolve();
> ```

Reject should provide some meaningful error.

---

*[test/www/jxcore/lib/testUtils.js, line 470 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-Kalno5mwSfVBqG8Ef5X:-Kalno5mwSfVBqG8Ef5Y:bu5iuby) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/test/www/jxcore/lib/testUtils.js#L470)):*
> ```JavaScript
>  * @returns {Promise<Error | peerAndBody>}
>  */
> module.exports.getSamePeerWithRetry = function (path, pskIdentity, pskKey,
> ```

NB: This function looks too complex and does several unrelated things simultaneously.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 152 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KalfJfp4Q8ezoe6jHVR:-KalfJfp4Q8ezoe6jHVS:b-wjea5x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L152)):*
> ```JavaScript
> inherits(MultiConnectEmitter, EventEmitter);
> 
> module.exports.multiConnectEmitter = new MultiConnectEmitter();
> ```

It looks like it wasn't merged properly

---

*[thali/NextGeneration/thaliMobile.js, line 1062 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KalfiHMGL1c1gZETmEb:-KalfiHMGL1c1gZETmEc:bfahrsc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/thali/NextGeneration/thaliMobile.js#L1062)):*
> ```JavaScript
> }
> 
> var handleRecreatedPeer = function (nativePeer) {
> ```

Again, merge issue.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 346 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-Kalg-a6ngdd7ls5-JqB:-Kalg-a7eU5vnRPiPJQ_:b-77rmxv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/thali/NextGeneration/thaliMobileNativeWrapper.js#L346)):*
> ```JavaScript
>       return stopServersManager();
>     }
>     return Promise.resolve();
> ```

You can just use `return`, creating new promise is not required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (91f4f8d)

**Comment by ThaliTester** [comment]
Test 96918947 (91f4f8d) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96918947 build is completed (91f4f8d)

See https://github.com/ThaliTester/TestResults/tree/9691894791f4f8d_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0e54424)

**Comment by ThaliTester** [comment]
Test 96918947 (0e54424) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96918947 build is completed (0e54424)

See https://github.com/ThaliTester/TestResults/tree/969189470e54424_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (801caae)

**Comment by ThaliTester** [comment]
Test 96918947 (801caae) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96918947 build is completed (801caae)

See https://github.com/ThaliTester/TestResults/tree/96918947801caae_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 96918947801caae(801caae) has failed

See https://github.com/ThaliTester/TestResults/tree/96918947801caae_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (48f509f)

**Comment by ThaliTester** [comment]
Test 96918947 (48f509f) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96918947 build is completed (48f509f)

See https://github.com/ThaliTester/TestResults/tree/9691894748f509f_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 9691894748f509f(48f509f) has failed

See https://github.com/ThaliTester/TestResults/tree/9691894748f509f_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the fail logs

**Comment by yaronyg** [comment]
I am embarrassingly excited to see this finally ready for submission! I have one minor NIT that can be completely ignored. Once @chapko's comments are resolved (and they look resolved) then :lgtm:

---

Reviewed 1 of 7 files at r5, 1 of 4 files at r6, 2 of 8 files at r10, 3 of 3 files at r13, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 1063 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KbR-c7llcjPJYV1PBwC:-KbR-c7m8QNWcfpOvG_-:b-3n6kqi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/48f509fe0c7ac56f0b787b3c529ab7afbd5fbc15/thali/NextGeneration/thaliMobileNativeWrapper.js#L1063)):*
> ```JavaScript
> module.exports._handlePeerAvailabilityChanged = handlePeerAvailabilityChanged;
> 
> function getPeerPort(peer) {
> ```

NB: return gServersManager ? gServersManager.createPeerListener(peer.peerIdentifier, peer.pleaseconnect) : Promise.resolve(null);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-:-KbR2IbHDwS1JfCalQyC:b7ejouj)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (00c7de5)

**Comment by ThaliTester** [comment]
Test 96918947 (00c7de5) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96918947 build is completed (00c7de5)

See https://github.com/ThaliTester/TestResults/tree/9691894700c7de5_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 9691894700c7de5(00c7de5) has failed

See https://github.com/ThaliTester/TestResults/tree/9691894700c7de5_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the fail logs

**Comment by czyzm** [comment]
One NB, other than that :lgtm: 

---

Reviewed 1 of 7 files at r5, 2 of 8 files at r10, 2 of 3 files at r13, 2 of 3 files at r14, 3 of 3 files at r15.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1835 at r15](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KbV-CXjQkYxrA3fFGZf:-KbV-CXjQkYxrA3fFGZg:b-g8gp8p) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/00c7de53d92ec12f9db1e76580c6785e2e557377/test/www/jxcore/bv_tests/testThaliMobile.js#L1835)):*
> ```JavaScript
> 
> test('calls correct starts when network changes',
>   function () {
> ```

NB: You can use testUtils.skipOnIOS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-:-KbV-QKXZmmrgYd8uYZc:bh7uwar)*

**Comment by chapko** [comment]
I've fixed some comments and cleaned some pieces of code in the last commit, but there are no any significant changes. Also I tested this PR locally on android phones and it does not break anything there.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 204 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KalKFLIGf46DyIbcv34:-KbV-35q0jqQafyne9aF:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L204)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

Reject should provide some meaningful error.
</blockquote></details>

Done.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 346 at r10](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-Kalg-a6ngdd7ls5-JqB:-KbUztAbKevK4oroDahM:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/377cdc27b09f44a728aa105e48eeb2eb59d8c151/thali/NextGeneration/thaliMobileNativeWrapper.js#L346)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary><blockquote>

You can just use `return`, creating new promise is not required.
</blockquote></details>

Done.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 1063 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KbR-c7llcjPJYV1PBwC:-KbV-6hLgA4Fekc6vaUf:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/48f509fe0c7ac56f0b787b3c529ab7afbd5fbc15/thali/NextGeneration/thaliMobileNativeWrapper.js#L1063)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

NB: return gServersManager ? gServersManager.createPeerListener(peer.peerIdentifier, peer.pleaseconnect) : Promise.resolve(null);
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-:-KbV-U61W1FpdJmCQJls:b24ocns)*

**Comment by chapko** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1835 at r15](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-KbV-CXjQkYxrA3fFGZf:-KbV0IxcIwJJRxEMTDM5:bsmovx8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/00c7de53d92ec12f9db1e76580c6785e2e557377/test/www/jxcore/bv_tests/testThaliMobile.js#L1835)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

NB: You can use testUtils.skipOnIOS
</blockquote></details>

Yes, I forgot about that function. I'm going to change it in the #1760 RP.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5a60225)

**Comment by ThaliTester** [comment]
Test 96918947 (5a60225) build started.

**Comment by chapko** [comment]
<blockquote>
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

NB: You can use testUtils.skipOnIOS
</blockquote></details>

Yes, I forgot about that function. I'm going to change it in the #1760 RP.
</blockquote>

But then I decided to fix it just by resolving conflicts.

**Comment by ThaliTester** [comment]
Test (Success) 96918947 build is completed (5a60225)

See https://github.com/ThaliTester/TestResults/tree/969189475a60225_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 969189475a60225(5a60225) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/969189475a60225_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by evabishchevich** [comment]
@yaronyg We are waiting for merge of the https://github.com/thaliproject/Thali_CordovaPlugin/pull/1759 first.

**Comment by czyzm** [comment]
Reviewed 2 of 2 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616)*

**Comment by czyzm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-:-KbsK5PD0WRYD0Y48CmL:bnfp4nl)*

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r15, 2 of 2 files at r16.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a106de9)

**Comment by ThaliTester** [comment]
Test 96918947 (a106de9) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96918947 build is completed (a106de9)

See https://github.com/ThaliTester/TestResults/tree/96918947a106de9_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 96918947a106de9(a106de9) has failed

See https://github.com/ThaliTester/TestResults/tree/96918947a106de9_Implemented_iOS_native-mode_functionality__900___1585___1611_squid48/ for the fail logs

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 5 of 9 files at r17, 4 of 4 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1616#-:-KcRgykD5c6S2lsIW6QH:bnfp4nl)*

**Pull request merged**
