### PR TITLE
#899_2 Added 'discoveryDos' event

### PR DESCRIPTION
**Pull request by artemjackson**
Includes #1120. So the [diff between this and #1120](https://github.com/thaliproject/Thali_CordovaPlugin/compare/vNext_yarong_417_812_artemjackson_899_1...vNext_yarong_417_812_artemjackson_899_2) may be useful.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1129)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (fb3c60d)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (72f4ed6)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (a269043)

**Comment by ThaliTester** [comment]
Test (Fail) 86373152 build is completed (fb3c60d)

See https://github.com/ThaliTester/TestResults/tree/86373152fb3c60d__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 86373152 build is completed (72f4ed6)

See https://github.com/ThaliTester/TestResults/tree/8637315272f4ed6__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 86373152 build is completed (a269043)

See https://github.com/ThaliTester/TestResults/tree/86373152a269043__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (2d3fc2c)

**Comment by ThaliTester** [comment]
Test (Fail) 86373152 build is completed (2d3fc2c)

See https://github.com/ThaliTester/TestResults/tree/863731522d3fc2c__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Comment by yaronyg** [comment]
Um... what happened?
2016-09-22 17:39:35 - ERROR TestsProcess: 'uncaught exception, error: 'Error: Error when loading file /Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/bv_tests/testLocalSeqManager.js: SyntaxError: Unexpected token }', stack: 'Error: Error when loading file /Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/bv_tests/testLocalSeqManager.js: SyntaxError: Unexpected token }
    at loadFile (/Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/runTests.js:27:11)
    at currentPlatform (/Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/runTests.js:40:7)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/thali/Github/Thali_CordovaPlugin/test/www/jxcore/runTests.js:36:52)
    at Module._compile (module.js:619:26)
    at Object.Module._extensions..js (module.js:649:10)
    at Module.load (module.js:440:36)
    at Function.Module._load (module.js:405:12)
    at Function.Module.runMain (module.js:878:12)
    at startup (node.js:485:18)
    at node.js:1604:3''
2016-09-22 17:39:35 - ERROR TestsProcess: '****TEST_LOGGER:[PROCESS_ON_EXIT_FAILED]****'

That file wasn't even changed here! I also noticed that there was a failure in downloading a dependency. I think CI is unhappy again. But once this passes CI then :lgtm: 

---

Reviewed 13 of 14 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1129#-:-KSJ2RKIpxxMEW4O8iIA:b-t3z2c0)*

**Comment by yaronyg** [comment]
Unfortunately I have to issue a :lgtm_cancel: because there is no testing to show that discoveryDOS works properly.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1129#-:-KSJ3m-plnniydZPoHGR:b-d2xr5z)*

**Comment by yaronyg** [comment]
Also there are no tests for disconnect. :(

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (83ea125)

**Comment by ThaliTester** [comment]
Test (Fail) 86373152 build is completed (83ea125)

See https://github.com/ThaliTester/TestResults/tree/8637315283ea125__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (291968c)

**Comment by ThaliTester** [comment]
Test (Success) 86373152 build is completed (291968c)

See https://github.com/ThaliTester/TestResults/tree/86373152291968c__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86373152291968c(291968c) has failed

See https://github.com/ThaliTester/TestResults/tree/86373152291968c__899_2_Added__discoveryDos__event_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (31ae023)

**Comment by ThaliTester** [comment]
Test (Fail) 86373152 build is completed (31ae023)

See https://github.com/ThaliTester/TestResults/tree/8637315231ae023__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Comment by artemjackson** [comment]
@yaronyg The test for `discoveryDOS` event is added.
But currently I can not implement test for `disconnect` because #903 (`wifiBaseNativeMock.discconnect` method should be implemented) blocks it

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0a9f9e4)

**Comment by ThaliTester** [comment]
Test (Success) 86373152 build is completed (0a9f9e4)

See https://github.com/ThaliTester/TestResults/tree/863731520a9f9e4__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Comment by yaronyg** [comment]
Blocked until we have the updated wifi based native mock

**Comment by yaronyg** [comment]
We'll open a new PR when the code is ready.

**Comment by ThaliTester** [comment]
Test 863731520a9f9e4(0a9f9e4) has failed

See https://github.com/ThaliTester/TestResults/tree/863731520a9f9e4__899_2_Added__discoveryDos__event_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0a9f9e4)

**Comment by ThaliTester** [comment]
Test (Fail) 86373152 build is completed (0a9f9e4)

See https://github.com/ThaliTester/TestResults/tree/863731520a9f9e4__899_2_Added__discoveryDos__event_artemjackson/ for the logs

**Pull request closed without merging**
