### PR TITLE
Reduced maxSockets

### PR DESCRIPTION
**Pull request by yaronyg**
See https://github.com/thaliproject/Thali_CordovaPlugin/issues/1493 for
details

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1494)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1a8d3a7)

**Comment by ThaliTester** [comment]
Test (Success) 92415795 build is completed (1a8d3a7)

See https://github.com/ThaliTester/TestResults/tree/924157951a8d3a7_Reduced_maxSockets_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 924157951a8d3a7(1a8d3a7) has failed

See https://github.com/ThaliTester/TestResults/tree/924157951a8d3a7_Reduced_maxSockets_yaronyg/ for the fail logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1494#-:-KW2W12ft0UiWs1xoRLU:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1f1b7f8)

**Comment by yaronyg** [comment]
Closing as I rolled these changes into master_901

**Comment by ThaliTester** [comment]
Test (Fail) 92415795 build is completed (1f1b7f8)

See https://github.com/ThaliTester/TestResults/tree/924157951f1b7f8_Reduced_maxSockets_yaronyg/ for the logs

**Pull request closed without merging**
