### PR TITLE
Improve ThaliCore project structure and managing dependencies.

### PR DESCRIPTION
**Pull request by dersim-davaod**
This PR MUST be merged with [this PR in thali-ios](https://github.com/thaliproject/thali-ios/pull/9).

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1861)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (aa8aed2)

**Comment by ThaliTester** [comment]
Test 119487456 (aa8aed2) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (be3f9ce)

**Comment by ThaliTester** [comment]
Test (Fail) 119487456 build is completed (aa8aed2)

See https://github.com/ThaliTester/TestResults/tree/119487456aa8aed2_Improve_ThaliCore_project_structure_and_managing_dependencies__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 119487456 (be3f9ce) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (56b2e74)

**Comment by ThaliTester** [comment]
Test 119487456 (56b2e74) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 119487456 build is completed (be3f9ce)

See https://github.com/ThaliTester/TestResults/tree/119487456be3f9ce_Improve_ThaliCore_project_structure_and_managing_dependencies__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 119487456 build is completed (56b2e74)

See https://github.com/ThaliTester/TestResults/tree/11948745656b2e74_Improve_ThaliCore_project_structure_and_managing_dependencies__dersim-davaod/ for the logs

**Comment by yaronyg** [comment]
Why do we need to disable the tests? :lgtm: 

---

Reviewed 4 of 8 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-:-KjdA1biRe1UeKZHHKjZ:b-sdergy)*

**Comment by jareksl** [comment]
Reviewed 4 of 8 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[lib/ios/Cartfile, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-KjfvupD9Qc61Rz8PI2v:-KjfvupD9Qc61Rz8PI2w:bjcgoxt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56b2e742aaaf3d3ec2fc93615969ecc6a6a21d30/lib/ios/Cartfile#L1)):*
> ```
> github "thaliproject/thali-ios" "master_dersim_preliminary_verification_fix"
> ```

NB: W should remember to restore this to point a master branch (create a separate issue) or use master and wait until it contain proper changes

---

*[thali/install/ios/nativeInstaller.js, line 212 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-KjfxjXvtok8-_ZyDKy3:-KjfxjXw5vd198VWLhhI:bm1rajg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56b2e742aaaf3d3ec2fc93615969ecc6a6a21d30/thali/install/ios/nativeInstaller.js#L212)):*
> ```JavaScript
>         frameworkProjectDir, frameworkOutputDir, buildWithTests)
>         .then(function () {
>           console.log('Building framework is done.');
> ```

NB: I'd prefer to use one console.log and format the message using \n, like you did below

---

*[thali/install/ios/nativeInstaller.js, line 345 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-KjfzedGwLPXAkipG8jN:-KjfzedGwLPXAkipG8jO:b-wlom25) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56b2e742aaaf3d3ec2fc93615969ecc6a6a21d30/thali/install/ios/nativeInstaller.js#L345)):*
> ```JavaScript
>     .then(function () {
>       if (!buildWithTests) {
>         // Don't cope SwiftXCTest framework
> ```

NB: typo in the comment cope -> copy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861)*

**Comment by jareksl** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-:-Kjg424luD1CaPMeX_pm:bg7igkv)*

**Comment by dersim-davaod** [comment]
@yaronyg, I was disabling desktop tests on my local machine in order to speed up building. Then I've commit it by mistake.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/ios/Cartfile, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-KjfvupD9Qc61Rz8PI2v:-Kjld_YZ-5CaiEOkdh7f:b-7namqs) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56b2e742aaaf3d3ec2fc93615969ecc6a6a21d30/lib/ios/Cartfile#L1)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

NB: W should remember to restore this to point a master branch (create a separate issue) or use master and wait until it contain proper changes
</blockquote></details>

Absolutely!
The corresponding PR in thali-ios (https://github.com/thaliproject/thali-ios/pull/9) was just merged, so I'm changing the target branch to `master`.

---

*[thali/install/ios/nativeInstaller.js, line 212 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-KjfxjXvtok8-_ZyDKy3:-Kjlff7GYir87Rq4PZpY:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56b2e742aaaf3d3ec2fc93615969ecc6a6a21d30/thali/install/ios/nativeInstaller.js#L212)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

NB: I'd prefer to use one console.log and format the message using \n, like you did below
</blockquote></details>

Done.

---

*[thali/install/ios/nativeInstaller.js, line 345 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-KjfzedGwLPXAkipG8jN:-KjlfOQqjSLe8a_KCphK:bt2vr1b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/56b2e742aaaf3d3ec2fc93615969ecc6a6a21d30/thali/install/ios/nativeInstaller.js#L345)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

NB: typo in the comment cope -> copy
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1861#-:-KjldK05BbivuV_WBcaM:b-w0w7y8)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6f89b98)

**Comment by ThaliTester** [comment]
Test 119487456 (6f89b98) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 119487456 build is completed (6f89b98)

See https://github.com/ThaliTester/TestResults/tree/1194874566f89b98_Improve_ThaliCore_project_structure_and_managing_dependencies__dersim-davaod/ for the logs

**Pull request merged**
