### PR TITLE
#1031 DO_NOT_MERGE Excluded 'bad' test files

### PR DESCRIPTION
**Pull request by artemjackson**
I need to identify all 'bad' tests that 'superbranch' brought for us and disable them temporarily.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1033)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (3f6a479)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (3f6a479)

See https://github.com/ThaliTester/TestResults/tree/852025183f6a479__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 852025183f6a479(3f6a479) has failed

See https://github.com/ThaliTester/TestResults/tree/852025183f6a479__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7630bd4)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (7630bd4)

See https://github.com/ThaliTester/TestResults/tree/852025187630bd4__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 852025187630bd4(7630bd4) has failed

See https://github.com/ThaliTester/TestResults/tree/852025187630bd4__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (4f78031)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (4f78031)

See https://github.com/ThaliTester/TestResults/tree/852025184f78031__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 852025184f78031(4f78031) has failed

See https://github.com/ThaliTester/TestResults/tree/852025184f78031__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (52c2848)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (52c2848)

See https://github.com/ThaliTester/TestResults/tree/8520251852c2848__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8520251852c2848(52c2848) has failed

See https://github.com/ThaliTester/TestResults/tree/8520251852c2848__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (56d1c3c)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (56d1c3c)

See https://github.com/ThaliTester/TestResults/tree/8520251856d1c3c__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8520251856d1c3c(56d1c3c) has failed

See https://github.com/ThaliTester/TestResults/tree/8520251856d1c3c__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (44c728f)

**Comment by ThaliTester** [comment]
Test 8520251844c728f(44c728f) has failed

See https://github.com/ThaliTester/TestResults/tree/8520251844c728f__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (dd4c7ab)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (dd4c7ab)

See https://github.com/ThaliTester/TestResults/tree/85202518dd4c7ab__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 85202518dd4c7ab(dd4c7ab) has failed

See https://github.com/ThaliTester/TestResults/tree/85202518dd4c7ab__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (082e18e)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (082e18e)

See https://github.com/ThaliTester/TestResults/tree/85202518082e18e__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 85202518082e18e(082e18e) has failed

See https://github.com/ThaliTester/TestResults/tree/85202518082e18e__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7f589dc)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (7f589dc)

See https://github.com/ThaliTester/TestResults/tree/852025187f589dc__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 852025187f589dc(7f589dc) has failed

See https://github.com/ThaliTester/TestResults/tree/852025187f589dc__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (dd4c7ab)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (dd4c7ab)

See https://github.com/ThaliTester/TestResults/tree/85202518dd4c7ab__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 85202518dd4c7ab(dd4c7ab) has failed

See https://github.com/ThaliTester/TestResults/tree/85202518dd4c7ab__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ae3d7e8)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (ae3d7e8)

See https://github.com/ThaliTester/TestResults/tree/85202518ae3d7e8__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 85202518ae3d7e8(ae3d7e8) has failed

See https://github.com/ThaliTester/TestResults/tree/85202518ae3d7e8__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5ed7d1b)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (5ed7d1b)

See https://github.com/ThaliTester/TestResults/tree/852025185ed7d1b__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 852025185ed7d1b(5ed7d1b) has failed

See https://github.com/ThaliTester/TestResults/tree/852025185ed7d1b__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fdcd556)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (fdcd556)

See https://github.com/ThaliTester/TestResults/tree/85202518fdcd556__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 85202518fdcd556(fdcd556) has failed

See https://github.com/ThaliTester/TestResults/tree/85202518fdcd556__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d111121)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (d111121)

See https://github.com/ThaliTester/TestResults/tree/85202518d111121__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 85202518d111121(d111121) has failed

See https://github.com/ThaliTester/TestResults/tree/85202518d111121__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d195ad1)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (d195ad1)

See https://github.com/ThaliTester/TestResults/tree/85202518d195ad1__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 85202518d195ad1(d195ad1) has failed

See https://github.com/ThaliTester/TestResults/tree/85202518d195ad1__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (54cf06b)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a9487e3)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (a9487e3)

See https://github.com/ThaliTester/TestResults/tree/85202518a9487e3__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (3d04d1f)

**Comment by ThaliTester** [comment]
Test (Success) 85202518 build is completed (3d04d1f)

See https://github.com/ThaliTester/TestResults/tree/852025183d04d1f__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8520251854cf06b(54cf06b) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8520251854cf06b__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 85202518a9487e3(a9487e3) has failed

See https://github.com/ThaliTester/TestResults/tree/85202518a9487e3__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test 852025183d04d1f(3d04d1f) has failed

See https://github.com/ThaliTester/TestResults/tree/852025183d04d1f__1031_DO_NOT_MERGE_Excluded__bad__test_files_artemjackson/ for the fail logs

**Comment by artemjackson** [comment]
We don't need this anymore.

**Pull request closed without merging**
