### PR TITLE
Implemented ThaliMobileNativeWrapper multiConnect method

### PR DESCRIPTION
**Pull request by squid48**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1479)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8df5d75)

**Comment by ThaliTester** [comment]
Test (Fail) 92152286 build is completed (8df5d75)

See https://github.com/ThaliTester/TestResults/tree/921522868df5d75_Implemented_ThaliMobileNativeWrapper_multiConnect_method_squid48/ for the logs

**Comment by chapko** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 611 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1479#-KW9heBqmX3gBz6qGn0Y:-KW9heBqmX3gBz6qGn0Z:b-kl1t7u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8df5d75ccaa46433b3bfd6e8b7cbf83b8b5a408e/thali/NextGeneration/thaliMobileNativeWrapper.js#L611)):*
> ```JavaScript
> 
>          module.exports.emitter.on('_multiConnectResolved',
>           function (syncValue, error, portNumber) {
> ```

This listener must be removed after (or before) promise is resolved or rejected. Otherwise emitter will keep reference for this function forever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1479)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8c3974a)

**Comment by ThaliTester** [comment]
Test (Success) 92152286 build is completed (8c3974a)

See https://github.com/ThaliTester/TestResults/tree/921522868c3974a_Implemented_ThaliMobileNativeWrapper_multiConnect_method_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 921522868c3974a(8c3974a) has failed

See https://github.com/ThaliTester/TestResults/tree/921522868c3974a_Implemented_ThaliMobileNativeWrapper_multiConnect_method_squid48/ for the fail logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1479#-:-KWI5HfB7r-t9JJteuRR:bnfp4nl)*

**Comment by yaronyg** [comment]
Please discuss the counter issue with @chapko and then resolve as you two decide. Otherwise :lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 602 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1479#-KWZYPiNWJDKfMAJ8kEr:-KWZYPiNWJDKfMAJ8kEs:bpg6wc2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8c3974ac5d45c43047168338f47af6d4dbbc4bab/thali/NextGeneration/thaliMobileNativeWrapper.js#L602)):*
> ```JavaScript
>  module.exports._multiConnect = function (peerIdentifier) {
>    return gPromiseQueue.enqueue(function (resolve, reject) {
>      var originalSyncValue = uuid.v4();
> ```

Wouldn't it be a lot easier to just use a counter instead of requiring a full UUID be generated?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 612 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1479#-KWZYb2gFXgMYvA0_7ms:-KWZYb2gFXgMYvA0_7mt:bc10j9d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8c3974ac5d45c43047168338f47af6d4dbbc4bab/thali/NextGeneration/thaliMobileNativeWrapper.js#L612)):*
> ```JavaScript
>          module.exports.emitter.on('_multiConnectResolved',
>           function callback (syncValue, error, portNumber) {
>              if(originalSyncValue !== syncValue) {
> ```

Please run linter it will catch things like not having a space after the if

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1479#-:-KWZYojeXuoRVb_CA81o:bwgjzia)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (16bd023)

**Comment by ThaliTester** [comment]
Test 92152286 (16bd023) build started.

**Comment by ThaliTester** [comment]
Test 9215228616bd023(16bd023) has failed

See https://github.com/ThaliTester/TestResults/tree/9215228616bd023_Implemented_ThaliMobileNativeWrapper_multiConnect_method_squid48/ for the fail logs

**Comment by chapko** [comment]
@squid48 just declare counter before `multiConnect` jsdoc and then it is :lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 600 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1479#-KWrU0YDX38CxSeowjLa:-KWrU0YDX38CxSeowjLb:b1apwo6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/16bd023921d7ef921534f31950e01e4ca310d8ba/thali/NextGeneration/thaliMobileNativeWrapper.js#L600)):*
> ```JavaScript
>  */
> 
> var multiConnectCounter = 0;
> ```

Move this declaration before jsdoc comment. Otherwise generated documentation would describe `multiConnectCounter` instead of  `_multiConnect`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1479#-:-KWrUvXFXpXqZpTcrzsq:b-awxcdf)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4f1c710)

**Comment by ThaliTester** [comment]
Test 92152286 (4f1c710) build started.

**Comment by ThaliTester** [comment]
Test (Success) 92152286 build is completed (4f1c710)

See https://github.com/ThaliTester/TestResults/tree/921522864f1c710_Implemented_ThaliMobileNativeWrapper_multiConnect_method_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 921522864f1c710(4f1c710) has failed

See https://github.com/ThaliTester/TestResults/tree/921522864f1c710_Implemented_ThaliMobileNativeWrapper_multiConnect_method_squid48/ for the fail logs

**Pull request closed without merging**
