### PR TITLE
#1161 and #1178 Fixed PouchDB test directory

### LINKED ISSUE #1161: Test 'Call of onCheckpointReached handler on a single db change' failed on Android in WIFI mode

### PR DESCRIPTION
**Pull request by artemjackson**
Closes #1161 and #1178

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1181)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (0b0275f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (4658a9f)

**Comment by ThaliTester** [comment]
Test (Fail) 86920370 build is completed (0b0275f)

See https://github.com/ThaliTester/TestResults/tree/869203700b0275f_Fixed_PouchDB_test_directory_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86920370 build is completed (4658a9f)

See https://github.com/ThaliTester/TestResults/tree/869203704658a9f_Fixed_PouchDB_test_directory_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (4183bfc)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (ca4434e)

**Comment by artemjackson** [comment]
This fixes #1161 and #1178. Verified locally by @vasilevskayaem

**Comment by ThaliTester** [comment]
Test 869203704658a9f(4658a9f) has failed

See https://github.com/ThaliTester/TestResults/tree/869203704658a9f_Fixed_PouchDB_test_directory_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Fail) 86920370 build is completed (4183bfc)

See https://github.com/ThaliTester/TestResults/tree/869203704183bfc__1161_and__1178_Fixed_PouchDB_test_directory_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86920370 build is completed (ca4434e)

See https://github.com/ThaliTester/TestResults/tree/86920370ca4434e__1161_and__1178_Fixed_PouchDB_test_directory_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 86920370ca4434e(ca4434e) has failed

See https://github.com/ThaliTester/TestResults/tree/86920370ca4434e__1161_and__1178_Fixed_PouchDB_test_directory_artemjackson/ for the fail logs

**Pull request merged**
