### PR TITLE
Add iOS functionality

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1797)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (61e1479)

**Comment by ThaliTester** [comment]
Test 105878026 (61e1479) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 105878026 build is completed (61e1479)

See https://github.com/ThaliTester/TestResults/tree/10587802661e1479_Add_iOS_functionality_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8c33877)

**Comment by ThaliTester** [comment]
Test 105878026 (8c33877) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 105878026 build is completed (8c33877)

See https://github.com/ThaliTester/TestResults/tree/1058780268c33877_Add_iOS_functionality_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (50af886)

**Comment by ThaliTester** [comment]
Test 105878026 (50af886) build started.

**Comment by yaronyg** [comment]
My assumption is that all of this code has been reviewed in the iOS branch and this is just a merge so no further review is needed. Is that assumption correct?

---

Review status: 0 of 270 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1797#-:-KcxY-TM-7HEvjJOIlMn:b-i2rvlh)*

**Comment by evabishchevich** [comment]
@yaronyg Yes, you're correct. It is a notification that we're going to merge it

**Pull request merged**
