### PR TITLE
More native level testing

### PR DESCRIPTION
**Pull request by yaronyg**
Moved a bunch of files to disabled

testThaliMobileNative - Added tests and a lot of infrastructure

wifiBasedNativeMock - Put in protection to check if any of the native methods are called more than once at a time (a validity check). Fixed a bunch of minor stuff like not allowing more than one incoming connection to the 'native listener' at a time. Cleaning up some of the socket code. Making sure multiple simultaneous calls to connect for the same peer will get the same answer, etc.

testTestSendData - Linting

testSendData - Linting

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/683)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5a28313)

**Comment by ThaliTester** [comment]
Test (Fail) 64531254 build is completed (5a28313)

See https://github.com/ThaliTester/TestResults/tree/645312545a28313_More_native_level_testing_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (841497d)

**Comment by ThaliTester** [comment]
Test (Success) 64531254 build is completed (841497d)

See https://github.com/ThaliTester/TestResults/tree/64531254841497d_More_native_level_testing_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 64531254841497d(841497d) has failed

See https://github.com/ThaliTester/TestResults/tree/64531254841497d_More_native_level_testing_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 13 of 15 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683#-KE5EU92yOgW95bKQZxc:-KE5EU92yOgW95bKQZxd:1182667240) (no related file):*
With 3 peers, the newly added tests passed on my machine, but when I added one more peer and run with `jx runCoordinatedTests.js --filter bv_tests/testThaliMobileNative.js --instanceCount 4` I started getting issues with the last test which was `Test updating advertising and parallel data transfer`. One connect to a peer started failing like `INFO testThaliMobileNative: Connect returned an error: Server was either closed or is not yet listening` and seemed like the test went into a retry-loop.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 606 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683#-KE59yvZJ2tO5VpzY3QP:-KE59yvZJ2tO5VpzY3QQ:895325124) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/841497d3d5198b0862fddb2d7eb59078999768ae/test/www/jxcore/bv_tests/testThaliMobileNative.js#L606)):*
Should there also be a return after this line so that the rest of the function isn't getting executed?

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 790 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683#-KE5BkqcgRhRRRFIyuN7:-KE5BkqcgRhRRRFIyuN8:-848636707) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/841497d3d5198b0862fddb2d7eb59078999768ae/test/www/jxcore/bv_tests/testThaliMobileNative.js#L790)):*
What does this iOS-specific comment mean?

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 875 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683#-KE5HCZxAsOLcY3exJ59:-KE5HCZxAsOLcY3exJ5A:1073943842) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/841497d3d5198b0862fddb2d7eb59078999768ae/test/www/jxcore/bv_tests/testThaliMobileNative.js#L875)):*
t.participants.forEach instead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9bcf247)

**Comment by yaronyg** [comment]
Review status: 8 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683#-KE5EU92yOgW95bKQZxc:-KE8emXvn4AcPvhGnWI_:-224287242) (no related file):*
Yup. I had a race condition or two. Just for fun I ran the test with 10 instances just to see what would happen. It passed. :)

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 606 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683#-KE59yvZJ2tO5VpzY3QP:-KE7_uXc90YAcPTUvey1:-439259448) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/841497d3d5198b0862fddb2d7eb59078999768ae/test/www/jxcore/bv_tests/testThaliMobileNative.js#L606)):*
Yup! Good catch.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 790 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683#-KE5BkqcgRhRRRFIyuN7:-KE7a0GtnLDS8b7kmvpR:1418588889) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/841497d3d5198b0862fddb2d7eb59078999768ae/test/www/jxcore/bv_tests/testThaliMobileNative.js#L790)):*
In theory one can start advertising without listening and listening without advertising but due to issues with working around problems in iOS those two aren't separate there. They both have to be on or nothing works.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 875 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683#-KE5HCZxAsOLcY3exJ59:-KE7a6RUZQHeg7ZGAIPG:1028815045) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/841497d3d5198b0862fddb2d7eb59078999768ae/test/www/jxcore/bv_tests/testThaliMobileNative.js#L875)):*
Unfortunately I can't. This loop exits early when it finds a match. With forEach there is no way to exit early short of throwing an exception which seems worse than just using for.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683)*

**Comment by ThaliTester** [comment]
Test (Success) 64531254 build is completed (9bcf247)

See https://github.com/ThaliTester/TestResults/tree/645312549bcf247_More_native_level_testing_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 645312549bcf247(9bcf247) has failed

See https://github.com/ThaliTester/TestResults/tree/645312549bcf247_More_native_level_testing_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/683)*

**Pull request merged**
