### PR TITLE
Issue 275 - Crash in testSendData.js

### PR DESCRIPTION
**Pull request by tobybrad**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/324)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (19fea12)

**Comment by ThaliTester** [comment]
Test (Success) 50648605 build is completed (19fea12)

See https://github.com/ThaliTester/TestResults/tree/5064860519fea12_Issue_275_-_Crash_in_testSendData_js_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 5064860519fea12(19fea12) has failed

See https://github.com/ThaliTester/TestResults/tree/5064860519fea12_Issue_275_-_Crash_in_testSendData_js_tobybrad/ for the fail logs

**Comment by tobybrad** [comment]
No longer an issue on ios9.

**Pull request closed without merging**
