### PR TITLE
Implement thaliMobile "discoveryDOS" event #1546

### PR DESCRIPTION
**Pull request by opetkevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1828)

### CODE REVIEW

**Comment by chapko** [comment]
-@chapko +@opetkevich 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 768 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1828#-KfGawr4rWVU7_2fVjVc:-KfGawr5M4fK95ZiChha:b-2h8lg0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0dae79c821876735480f950422102a8ff5657574/thali/NextGeneration/thaliMobileNativeWrapper.js#L768)):*
> ```JavaScript
>             resolve();
>           });
>       }
> ```

Theres no need for these changes. They were originally introduced when `disconnect`hasn't been implemented yet. Now platform is checked in the public `disconnect` and in the android native layer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1828#-:-KfGdGZGddWGrRxxNEQV:byjtkux)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (50788d3)

**Comment by ThaliTester** [comment]
Test 110631962 (50788d3) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 110631962 build is completed (50788d3)

See https://github.com/ThaliTester/TestResults/tree/11063196250788d3_Implement_thaliMobile__discoveryDOS__event__1546_opetkevich/ for the logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1828#-:-KfMd2HfNtPJpmkx54co:bnfp4nl)*

**Comment by yaronyg** [comment]
Please fix the two minor issues I identified and then :LGTM:

---

Reviewed 2 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[thali/NextGeneration/thaliMobile.js, line 1499 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1828#-KfSDLCgK7bTH3BnScVP:-KfSDLChXM4wgtz4Cd35:b-gniuy4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50788d384ef48f98824533301c324d9867d8d503/thali/NextGeneration/thaliMobile.js#L1499)):*
> ```JavaScript
>   thaliConfig.TCP_NATIVE_PEERS_LIMIT;
> 
> module.exports.connectionTypePeersLimits = connectionTypePeersLimits;
> ```

This appears to be exported for testing purposes. As such we should call it _connectionTypePeersLimit to make it clear that this isn't intended as an externally supported interface. It's internal only.

---

*[thali/NextGeneration/thaliMobile.js, line 1507 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1828#-KfSE1evkbbgeec2h74x:-KfSE1evkbbgeec2h74y:b94mlg8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50788d384ef48f98824533301c324d9867d8d503/thali/NextGeneration/thaliMobile.js#L1507)):*
> ```JavaScript
>   if (connectionTypePeersCount > peersLimit) {
>     module.exports.emitter
>       .emit(connectionType + 'PeersLimitReached', {
> ```

It would be nice to stick in a delimiter here just to make it easier to read. In other words '-PeersLimitReached'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1828#-:-KfSErIcY99verc1JDbc:b-ctwcq2)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c420e15)

**Comment by ThaliTester** [comment]
Test 110631962 (c420e15) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 110631962 build is completed (c420e15)

See https://github.com/ThaliTester/TestResults/tree/110631962c420e15_Implement_thaliMobile__discoveryDOS__event__1546_opetkevich/ for the logs

**Pull request merged**
