### PR TITLE
Remove old getPort function

### PR DESCRIPTION
**Pull request by yaronyg**
thaliMobile - Linting

thaliMobileNativeWrapper - This was originally going to be a 'universal'
function to hide the differences between Connect and MultiConnect but in
the end we decided to just have thaliMobile call directly to Connect and
MultiConnect since anyway they had different behaviors that we didn't think
were worth papering over.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1164)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f1f0fb5)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (a3b8872)

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1164#-:-KSbOGexUgtYhKbfGMUK:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 86776290 build is completed (f1f0fb5)

See https://github.com/ThaliTester/TestResults/tree/86776290f1f0fb5_Remove_old_getPort_function_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 86776290f1f0fb5(f1f0fb5) has failed

See https://github.com/ThaliTester/TestResults/tree/86776290f1f0fb5_Remove_old_getPort_function_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86776290 build is completed (a3b8872)

See https://github.com/ThaliTester/TestResults/tree/86776290a3b8872_Remove_old_getPort_function_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 86776290a3b8872(a3b8872) has failed

See https://github.com/ThaliTester/TestResults/tree/86776290a3b8872_Remove_old_getPort_function_yaronyg/ for the fail logs

**Pull request merged**
