### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1461)

### CODE REVIEW

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by larryonoff** [comment]
@yaronyg please review

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1461)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1461#-:-KVR6kdW-V8UvkKkbNbK:bnfp4nl)*

**Pull request merged**
