### PR TITLE
Fix CI build in vNext_aevsyuchenya_819 branch

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/930)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (3e10cd0)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (ebd9a7c)

**Comment by ThaliTester** [comment]
Test (Success) 82728424 build is completed (3e10cd0)

See https://github.com/ThaliTester/TestResults/tree/827284243e10cd0_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 827284243e10cd0(3e10cd0) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/827284243e10cd0_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 82728424 build is completed (ebd9a7c)

See https://github.com/ThaliTester/TestResults/tree/82728424ebd9a7c_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 82728424ebd9a7c(ebd9a7c) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/82728424ebd9a7c_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d2195a9)

**Comment by ThaliTester** [comment]
Test (Success) 82728424 build is completed (d2195a9)

See https://github.com/ThaliTester/TestResults/tree/82728424d2195a9_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 82728424d2195a9(d2195a9) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/82728424d2195a9_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cc1b7f1)

**Comment by ThaliTester** [comment]
Test (Success) 82728424 build is completed (cc1b7f1)

See https://github.com/ThaliTester/TestResults/tree/82728424cc1b7f1_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 82728424cc1b7f1(cc1b7f1) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/82728424cc1b7f1_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by yaronyg** [comment]
@larryonoff I'm assuming this is for me to review but it wasn't actually assigned to me.

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/UnitTest_app.js, line 28 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/930#-KQ2iEdUpi_1ZEFO0mPV:-KQ2iEdUpi_1ZEFO0mPW:b-ix884w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/cc1b7f1e1a28318e41d7f8423fced232d21fa5e1/test/www/jxcore/UnitTest_app.js#L28)):*
> ```JavaScript
>         console.log('*Native tests were executed*');
> 
>         if (result.failed > 0) {
> ```

NB: utResult = result.failed <= 0;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/930#-:-KQ2id_vh76pN3_0Xl86:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c383411)

**Comment by larryonoff** [comment]
Reviewed 1 of 2 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/UnitTest_app.js, line 28 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/930#-KQ2iEdUpi_1ZEFO0mPV:-KQ4yzfFAhCT-snzo_fI:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/cc1b7f1e1a28318e41d7f8423fced232d21fa5e1/test/www/jxcore/UnitTest_app.js#L28)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: utResult = result.failed <= 0;
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/930)*

**Comment by ThaliTester** [comment]
Test (Success) 82728424 build is completed (c383411)

See https://github.com/ThaliTester/TestResults/tree/82728424c383411_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the logs

**Comment by larryonoff** [comment]
@yaronyg I expected assigning it to you today, but thanks for reviewing it earlier :)

**Comment by ThaliTester** [comment]
Test 82728424c383411(c383411) has failed

See https://github.com/ThaliTester/TestResults/tree/82728424c383411_Fix_CI_build_in_vNext_aevsyuchenya_819_branch_larryonoff/ for the fail logs

**Pull request closed without merging**
