### PR TITLE
Merge remote-tracking branch 'origin/master' into iOS

### PR DESCRIPTION
**Pull request by yaronyg**
# Conflicts:
#	src/android/java/io/jxcore/node/SocketThreadBase.java
#	src/android/test/io/jxcore/node/ListenerMock.java
#	test/www/jxcore/bv_tests/testThaliMobile.js
#	test/www/jxcore/bv_tests/testThaliMobileNative.js
#	test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js
#	test/www/jxcore/lib/wifiBasedNativeMock.js
#	thali/package.json

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1568)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d240795)

**Comment by ThaliTester** [comment]
Test 95104064 (d240795) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95104064 build is completed (d240795)

See https://github.com/ThaliTester/TestResults/tree/95104064d240795_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the logs

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1568#-:-KXK_Wm3aDMj5aJxKvAi:bnfp4nl)*

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1568#-:-KXKpZSxT3rlYx3gm9bD:bnfp4nl)*

**Comment by larryonoff** [comment]
see issue thaliproject/Thali_CordovaPlugin#1572. Some tests fail.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b52d871)

**Comment by ThaliTester** [comment]
Test 95104064 (b52d871) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95104064 build is completed (b52d871)

See https://github.com/ThaliTester/TestResults/tree/95104064b52d871_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (790d871)

**Comment by ThaliTester** [comment]
Test 95104064 (790d871) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d8684ed)

**Comment by ThaliTester** [comment]
Test 95104064 (d8684ed) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95104064 build is completed (790d871)

See https://github.com/ThaliTester/TestResults/tree/95104064790d871_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 95104064 build is completed (d8684ed)

See https://github.com/ThaliTester/TestResults/tree/95104064d8684ed_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8ee02aa)

**Comment by ThaliTester** [comment]
Test 95104064 (8ee02aa) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95104064 build is completed (8ee02aa)

See https://github.com/ThaliTester/TestResults/tree/951040648ee02aa_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3966298)

**Comment by ThaliTester** [comment]
Test 95104064 (3966298) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95104064 build is completed (3966298)

See https://github.com/ThaliTester/TestResults/tree/951040643966298_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the logs

**Comment by evabishchevich** [comment]
There is no obvious reason why tests failed

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4e42f59)

**Comment by ThaliTester** [comment]
Test 95104064 (4e42f59) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95104064 build is completed (4e42f59)

See https://github.com/ThaliTester/TestResults/tree/951040644e42f59_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 951040644e42f59(4e42f59) has failed

See https://github.com/ThaliTester/TestResults/tree/951040644e42f59_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (83d1755)

**Comment by ThaliTester** [comment]
Test 95104064 (83d1755) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95104064 build is completed (83d1755)

See https://github.com/ThaliTester/TestResults/tree/9510406483d1755_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 9510406483d1755(83d1755) has failed

See https://github.com/ThaliTester/TestResults/tree/9510406483d1755_Merge_remote-tracking_branch__origin/master__into_iOS_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
This was already merged into the 899 branch that @chapko is developing on so we are going to close this PR and get the changes from the 899 branch when it is merged back into iOS.

**Pull request closed without merging**
