### PR TITLE
Put NSNull instead of nil to didResolveMultiConnectWithSyncValue method #1843

### PR DESCRIPTION
**Pull request by asuhodolov**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1846)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (82d90ee)

**Comment by ThaliTester** [comment]
Test 112750453 (82d90ee) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 112750453 build is completed (82d90ee)

See https://github.com/ThaliTester/TestResults/tree/11275045382d90ee_Put_NSNull_instead_of_nil_to_didResolveMultiConnectWithSyncValue_method__1843_asuhodolov/ for the logs

**Comment by asuhodolov** [comment]
This fix depends on PR https://github.com/thaliproject/thali-ios/pull/1
Need to merge PR in ThaliCore repo first

**Comment by dersim-davaod** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1846#-:-KgUPp1vqdxlKKGUoXDT:bnfp4nl)*

**Comment by dersim-davaod** [comment]
Merging branch as we've merged thaliproject/thali-ios#1.

**Pull request merged**
