### PR TITLE
Changed wifiPeerAvailabilityChanged in wifiBasedNativeMock

### PR DESCRIPTION
**Pull request by squid48**
thaliproject/Thali_CordovaPlugin#1489

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1696)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (97797f9)

**Comment by ThaliTester** [comment]
Test 99451854 (97797f9) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99451854 build is completed (97797f9)

See https://github.com/ThaliTester/TestResults/tree/9945185497797f9_Changed_wifiPeerAvailabilityChanged_in_wifiBasedNativeMock_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 9945185497797f9(97797f9) has failed

See https://github.com/ThaliTester/TestResults/tree/9945185497797f9_Changed_wifiPeerAvailabilityChanged_in_wifiBasedNativeMock_squid48/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1696#-:-K_1i9XAH818uX2YAjFs:bnfp4nl)*

**Pull request merged**
