### PR TITLE
Add listening to connectivity events when app starts

### PR DESCRIPTION
**Pull request by evabishchevich**
(cherry picked from commit 424d9f5)

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1700)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (46c88db)

**Comment by ThaliTester** [comment]
Test 99530606 (46c88db) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99530606 build is completed (46c88db)

See https://github.com/ThaliTester/TestResults/tree/9953060646c88db_Add_listening_to_connectivity_events_when_app_starts_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 9953060646c88db(46c88db) has failed

See https://github.com/ThaliTester/TestResults/tree/9953060646c88db_Add_listening_to_connectivity_events_when_app_starts_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d5b5815)

**Comment by ThaliTester** [comment]
Test 99530606 (d5b5815) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99530606 build is completed (d5b5815)

See https://github.com/ThaliTester/TestResults/tree/99530606d5b5815_Add_listening_to_connectivity_events_when_app_starts_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 99530606d5b5815(d5b5815) has failed

See https://github.com/ThaliTester/TestResults/tree/99530606d5b5815_Add_listening_to_connectivity_events_when_app_starts_evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
Don't we need some kind of testing to make sure that we are actually getting the events and that things are properly started?

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-:-K_AK_tKeGo-bBve2hUJ:b-2t4278)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (94b7c78)

**Comment by ThaliTester** [comment]
Test 99530606 (94b7c78) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 99530606 build is completed (94b7c78)

See https://github.com/ThaliTester/TestResults/tree/9953060694b7c78_Add_listening_to_connectivity_events_when_app_starts_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e7215e5)

**Comment by ThaliTester** [comment]
Test 99530606 (e7215e5) build started.

**Comment by evabishchevich** [comment]
@yaronyg Added small test. Static method calls replaced on interface method calls to have opportunity to write the test.

**Comment by ThaliTester** [comment]
Test (Success) 99530606 build is completed (e7215e5)

See https://github.com/ThaliTester/TestResults/tree/99530606e7215e5_Add_listening_to_connectivity_events_when_app_starts_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 99530606e7215e5(e7215e5) has failed

See https://github.com/ThaliTester/TestResults/tree/99530606e7215e5_Add_listening_to_connectivity_events_when_app_starts_evabishchevich/ for the fail logs

**Comment by czyzm** [comment]
Reviewed 1 of 9 files at r3.
Review status: 1 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 12 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka1NPsYjwCEyXMABpp7:-Ka1NPsYjwCEyXMABpp8:b-r4fztw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e7215e56fb9913fb00bdfde68747155e6cd19f45/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L12)):*
> ```Java
> 
> 
>     void notifyPeerAvailabilityChanged(PeerProperties peerProperties, boolean isAvailable);
> ```

NB: Add documentation

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 14 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka1NU97XhsauPpt3qoD:-Ka1NU97XhsauPpt3qoE:bbjkt02) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e7215e56fb9913fb00bdfde68747155e6cd19f45/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L14)):*
> ```Java
>     void notifyPeerAvailabilityChanged(PeerProperties peerProperties, boolean isAvailable);
> 
>     void notifyDiscoveryAdvertisingStateUpdateNonTcp(boolean isDiscoveryActive, boolean isAdvertisingActive);
> ```

NB: Add documentation.

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 24 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka1NIpHpvZjPsrqBqL0:-Ka1NIpHpvZjPsrqBqL1:b-wf1rct) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e7215e56fb9913fb00bdfde68747155e6cd19f45/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L24)):*
> ```Java
>      *                           is connected to.
>      */
>     void notifyNetworkChanged(boolean isBluetoothEnabled, boolean isWifiEnabled, String bssidName, String ssidName);
> ```

NB: Add also documentation for ssidName param.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by czyzm** [comment]
Reviewed 1 of 3 files at r4.
Review status: 2 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by czyzm** [comment]
Reviewed 1 of 9 files at r3, 1 of 3 files at r4.
Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by czyzm** [comment]
Reviewed 1 of 9 files at r3.
Review status: 5 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by czyzm** [comment]
Reviewed 3 of 9 files at r3, 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by czyzm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-:-Ka1X_NnVDgZf7mAqiBY:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (84fcb1f)

**Comment by ThaliTester** [comment]
Test 99530606 (84fcb1f) build started.

**Comment by evabishchevich** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 12 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka1NPsYjwCEyXMABpp7:-Ka1fQzTabKmFx1ePbe9:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e7215e56fb9913fb00bdfde68747155e6cd19f45/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L12)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

NB: Add documentation
</blockquote></details>

Done.

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 14 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka1NU97XhsauPpt3qoD:-Ka1fRMJeKnz9bhsUN9d:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e7215e56fb9913fb00bdfde68747155e6cd19f45/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L14)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

NB: Add documentation.
</blockquote></details>

Done.

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 24 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka1NIpHpvZjPsrqBqL0:-Ka1fRhiozXlbcR5oT8o:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e7215e56fb9913fb00bdfde68747155e6cd19f45/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L24)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

NB: Add also documentation for ssidName param.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by ThaliTester** [comment]
Test (Fail) 99530606 build is completed (84fcb1f)

See https://github.com/ThaliTester/TestResults/tree/9953060684fcb1f_Add_listening_to_connectivity_events_when_app_starts_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
@czyzm Adding documentation can't change any behavior. I'm going to merge this PR. I discussed with @andrew-aladev the problem with the failed test and he thinks that it will be fixed when we have merged other PRs.

**Comment by yaronyg** [comment]
Reviewed 5 of 9 files at r3, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 100 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka9_e42zSqY71CCIqqo:-Ka9_e43BdClpECY_UJC:b-czf10k) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84fcb1f694bcfc57402313c6a505e291dc20a170/src/android/java/io/jxcore/node/JXcoreExtension.java#L100)):*
> ```Java
> 
>     public static void LoadExtensions() {
>         getInstance();
> ```

What's the point of calling getInstance when we are just going to ignore what it returns? The function itself has no side effects.

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 1 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka9eTZsvHsM0vBDyQbD:-Ka9eTZtCwUTz06Y7erF:b-ft7qcs) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84fcb1f694bcfc57402313c6a505e291dc20a170/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L1)):*
> ```Java
> package io.jxcore.node;
> ```

Why did we need this interface? What was wrong with calling JXcore directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 100 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka9_e42zSqY71CCIqqo:-KaBdJoouAdE3sujSMhB:b-90j5xr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84fcb1f694bcfc57402313c6a505e291dc20a170/src/android/java/io/jxcore/node/JXcoreExtension.java#L100)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

What's the point of calling getInstance when we are just going to ignore what it returns? The function itself has no side effects.
</blockquote></details>

We don't need this call here.

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 1 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka9eTZsvHsM0vBDyQbD:-KaBbYLajEFAAO7G-O2G:b-kxa26p) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84fcb1f694bcfc57402313c6a505e291dc20a170/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L1)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why did we need this interface? What was wrong with calling JXcore directly?
</blockquote></details>

JXcoreExtension.java is the point to communicate with node layer. This interface gives us flexibility to test  that we send correct values to the node layer. Node code is a 3rd party realization of the contract for the native layer. It's good practice to have an abstraction for 3rd party parts in the project

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 100 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka9_e42zSqY71CCIqqo:-KaDWtmUNd__ahIzLZVu:b-xno3io) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84fcb1f694bcfc57402313c6a505e291dc20a170/src/android/java/io/jxcore/node/JXcoreExtension.java#L100)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

We don't need this call here.
</blockquote></details>

So can I expect a PR to remove it? :)

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 1 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka9eTZsvHsM0vBDyQbD:-KaDWyoi_V00smNQ65nu:b-rum1vn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84fcb1f694bcfc57402313c6a505e291dc20a170/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L1)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

JXcoreExtension.java is the point to communicate with node layer. This interface gives us flexibility to test  that we send correct values to the node layer. Node code is a 3rd party realization of the contract for the native layer. It's good practice to have an abstraction for 3rd party parts in the project
</blockquote></details>

But doesn't that logic apply to all of the API calls in JXcoreExtension.java? These are specifically for calls going from Android back to Node but then shouldn't we have a similar interface for calls from node to Android so we can test those at the native layer as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/android/java/io/jxcore/node/JXcoreExtension.java, line 100 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka9_e42zSqY71CCIqqo:-KaEB-1ybuHKoGTDY8Qt:b-vrrrn3) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84fcb1f694bcfc57402313c6a505e291dc20a170/src/android/java/io/jxcore/node/JXcoreExtension.java#L100)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

So can I expect a PR to remove it? :)
</blockquote></details>

Sure. It's PR #1718 

---

*[src/android/java/io/jxcore/node/SurroundingStateObserver.java, line 1 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700#-Ka9eTZsvHsM0vBDyQbD:-KaEBDgDMOejo7ILE1ez:b-eli15v) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/84fcb1f694bcfc57402313c6a505e291dc20a170/src/android/java/io/jxcore/node/SurroundingStateObserver.java#L1)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

But doesn't that logic apply to all of the API calls in JXcoreExtension.java? These are specifically for calls going from Android back to Node but then shouldn't we have a similar interface for calls from node to Android so we can test those at the native layer as well?
</blockquote></details>

In general when Node code calls Android code we call some method from ConnectionHelper. We can call methods on ConnectionHelper without any additional interface. I'll think about that opportunity and we'll add that when we have a case to test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1700)*

**Pull request merged**
