### PR TITLE
#899 Update thaliMobile for WiFi and Android (peerAvailabilityChanged)

### PR DESCRIPTION
**Pull request by chapko**
This PR contains logic related to the new "peerAvailabilityChanged" event format (#899).

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1328)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (87965e9)

**Comment by ThaliTester** [comment]
Test (Success) 89443314 build is completed (87965e9)

See https://github.com/ThaliTester/TestResults/tree/8944331487965e9__899_Update_thaliMobile_for_WiFi_and_Android__peerAvailabilityChanged__chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 8944331487965e9(87965e9) has failed

See https://github.com/ThaliTester/TestResults/tree/8944331487965e9__899_Update_thaliMobile_for_WiFi_and_Android__peerAvailabilityChanged__chapko/ for the fail logs

**Comment by yaronyg** [comment]
There is exactly one comment that is blocking (changing an or to an and). Once you resolve that then :lgtm: 

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/thaliMobile.js, line 830 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1328#-KU4UiB2j2JiA69cHQSr:-KU4UiB3cgrEaG55063h:b-secrtq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/87965e9d30b5c5cd7a276840ae5b341900404962/thali/NextGeneration/thaliMobile.js#L830)):*
> ```JavaScript
> };
> 
> // TODO: mode peer availability cache to the seaprate module
> ```

NB: /mode/move and /seaprate/seperate

---

*[thali/NextGeneration/thaliMobile.js, line 886 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1328#-KU4W3YsaqGNH7ATvS2a:-KU4W3YsaqGNH7ATvS2b:bbgnj5c) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/87965e9d30b5c5cd7a276840ae5b341900404962/thali/NextGeneration/thaliMobile.js#L886)):*
> ```JavaScript
>   var cachedPeer = peerAvailabilities[peer.connectionType][peer.peerIdentifier];
> 
>   if (!cachedPeer) {
> ```

NB: I would have preferred !cachedPeer && !peer.peerAvailable because I think nested ifs are harder to read but that's just me.

---

*[thali/NextGeneration/thaliMobile.js, line 1196 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1328#-KU4Zj-P9BzeKT5tAAMr:-KU4Zj-QiONCaiOcPWYa:bt8y6v7) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/87965e9d30b5c5cd7a276840ae5b341900404962/thali/NextGeneration/thaliMobile.js#L1196)):*
> ```JavaScript
>   if (networkChangedValue.bluetooth === 'off' ||
>       networkChangedValue.bluetoothLowEnergy === 'off') {
>     // If either Bluetooth or BLE is off, we mark Android peers unavailable.
> ```

The plan is to make it possible to manage bluetooth and BLE separately from each other for performance reasons. So I think we should change the logic to be an && instead of an ||.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1328#-:-KU4a5YGtT_b0ms8tHFP:b-ilc61l)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f0cdb0b)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a08dd73)

**Comment by ThaliTester** [comment]
Test (Fail) 89443314 build is completed (f0cdb0b)

See https://github.com/ThaliTester/TestResults/tree/89443314f0cdb0b__899_Update_thaliMobile_for_WiFi_and_Android__peerAvailabilityChanged__chapko/ for the logs

**Comment by chapko** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/NextGeneration/thaliMobile.js, line 830 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1328#-KU4UiB2j2JiA69cHQSr:-KUH4HGAPjXLMflrHAoc:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/87965e9d30b5c5cd7a276840ae5b341900404962/thali/NextGeneration/thaliMobile.js#L830)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: /mode/move and /seaprate/seperate
</details>
Fixed

---

*[thali/NextGeneration/thaliMobile.js, line 886 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1328#-KU4W3YsaqGNH7ATvS2a:-KUH4RFh1nxa7gyyTo-M:bx9datx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/87965e9d30b5c5cd7a276840ae5b341900404962/thali/NextGeneration/thaliMobile.js#L886)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: I would have preferred !cachedPeer && !peer.peerAvailable because I think nested ifs are harder to read but that's just me.
</details>
Agree. There had been some code after inner `if` which I removed but forgot to merge conditions.
Fixed.

---

*[thali/NextGeneration/thaliMobile.js, line 1196 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1328#-KU4Zj-P9BzeKT5tAAMr:-KUH5z8q6CcLUx-LVLQC:bt2vr1b) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/87965e9d30b5c5cd7a276840ae5b341900404962/thali/NextGeneration/thaliMobile.js#L1196)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> The plan is to make it possible to manage bluetooth and BLE separately from each other for performance reasons. So I think we should change the logic to be an && instead of an ||.
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1328)*

**Comment by ThaliTester** [comment]
Test (Fail) 89443314 build is completed (a08dd73)

See https://github.com/ThaliTester/TestResults/tree/89443314a08dd73__899_Update_thaliMobile_for_WiFi_and_Android__peerAvailabilityChanged__chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2f26427)

**Comment by ThaliTester** [comment]
Test (Success) 89443314 build is completed (2f26427)

See https://github.com/ThaliTester/TestResults/tree/894433142f26427__899_Update_thaliMobile_for_WiFi_and_Android__peerAvailabilityChanged__chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 894433142f26427(2f26427) has failed

See https://github.com/ThaliTester/TestResults/tree/894433142f26427__899_Update_thaliMobile_for_WiFi_and_Android__peerAvailabilityChanged__chapko/ for the fail logs

**Pull request merged**
