### PR TITLE
Story 001 tompaana 406

### PR DESCRIPTION
**Pull request by tompaana**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/426)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (37bcedb)

**Comment by ThaliTester** [comment]
Test (Success) 55467363 build is completed (37bcedb)

See https://github.com/ThaliTester/TestResults/tree/5546736337bcedb_Story_001_tompaana_406_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 5546736337bcedb(37bcedb) has failed

See https://github.com/ThaliTester/TestResults/tree/5546736337bcedb_Story_001_tompaana_406_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (832a26e)

**Comment by ThaliTester** [comment]
Test (Success) 55467363 build is completed (832a26e)

See https://github.com/ThaliTester/TestResults/tree/55467363832a26e_Story_001_tompaana_406_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 55467363832a26e(832a26e) has failed

See https://github.com/ThaliTester/TestResults/tree/55467363832a26e_Story_001_tompaana_406_tompaana/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/426)*

**Pull request merged**
