### PR TITLE
fix: Cannot find module 'child-process-promise' on CI in vNext #1012

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1013)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (88320bd)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (f6d448c)

**Comment by ThaliTester** [comment]
Test (Success) 84648740 build is completed (88320bd)

See https://github.com/ThaliTester/TestResults/tree/8464874088320bd_fix__Cannot_find_module__child-process-promise__on_CI_in_vNext__1012_larryonoff/ for the logs

**Comment by larryonoff** [comment]
@yaronyg please review

**Comment by ThaliTester** [comment]
Test 8464874088320bd(88320bd) has failed

See https://github.com/ThaliTester/TestResults/tree/8464874088320bd_fix__Cannot_find_module__child-process-promise__on_CI_in_vNext__1012_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 84648740 build is completed (f6d448c)

See https://github.com/ThaliTester/TestResults/tree/84648740f6d448c_fix__Cannot_find_module__child-process-promise__on_CI_in_vNext__1012_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 84648740f6d448c(f6d448c) has failed

See https://github.com/ThaliTester/TestResults/tree/84648740f6d448c_fix__Cannot_find_module__child-process-promise__on_CI_in_vNext__1012_larryonoff/ for the fail logs

**Comment by yaronyg** [comment]
Once you get this to pass CI then :LGTM:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1013#-:-KRGBX64aRis590RftTE:berbw8s)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (0fb5c63)

**Comment by ThaliTester** [comment]
Test (Success) 84648740 build is completed (0fb5c63)

See https://github.com/ThaliTester/TestResults/tree/846487400fb5c63_fix__Cannot_find_module__child-process-promise__on_CI_in_vNext__1012_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 846487400fb5c63(0fb5c63) has failed

See https://github.com/ThaliTester/TestResults/tree/846487400fb5c63_fix__Cannot_find_module__child-process-promise__on_CI_in_vNext__1012_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4bc066c)

**Comment by ThaliTester** [comment]
Test (Success) 84648740 build is completed (4bc066c)

See https://github.com/ThaliTester/TestResults/tree/846487404bc066c_fix__Cannot_find_module__child-process-promise__on_CI_in_vNext__1012_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 846487404bc066c(4bc066c) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/846487404bc066c_fix__Cannot_find_module__child-process-promise__on_CI_in_vNext__1012_larryonoff/ for the logs

**Comment by larryonoff** [comment]
LGTM was already provided. CI is passing.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1013#-:-KRY-CtTqmYs7YaLdtXT:b-scmjak)*

**Pull request merged**
