### PR TITLE
update thali development environment

### PR DESCRIPTION
**Pull request by larryonoff**
update node to 6.9.1
update npm to 3.10.8
update brew to 1.1.*
update jxcore to 0.3.1.6
update androidBuildTools to 25.0.0
update androidSupportLibraries to 40.0.0
update jxcoreCordova to 0.1.6

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1523)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ffe1d7c)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (ffe1d7c)

See https://github.com/ThaliTester/TestResults/tree/93765317ffe1d7c_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0e2f5bd)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (0e2f5bd)

See https://github.com/ThaliTester/TestResults/tree/937653170e2f5bd_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (bcf6765)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (bcf6765)

See https://github.com/ThaliTester/TestResults/tree/93765317bcf6765_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2a6f939)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (2a6f939)

See https://github.com/ThaliTester/TestResults/tree/937653172a6f939_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fadb314)

**Comment by ThaliTester** [comment]
Test (Success) 93765317 build is completed (fadb314)

See https://github.com/ThaliTester/TestResults/tree/93765317fadb314_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 93765317fadb314(fadb314) has failed

See https://github.com/ThaliTester/TestResults/tree/93765317fadb314_update_thali_development_environment_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (916e515)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (15755df)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (00d32ae)

**Comment by ThaliTester** [comment]
Test (Success) 93765317 build is completed (15755df)

See https://github.com/ThaliTester/TestResults/tree/9376531715755df_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (00d32ae)

See https://github.com/ThaliTester/TestResults/tree/9376531700d32ae_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 9376531715755df(15755df) has failed

See https://github.com/ThaliTester/TestResults/tree/9376531715755df_update_thali_development_environment_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c3759e9)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (c3759e9)

See https://github.com/ThaliTester/TestResults/tree/93765317c3759e9_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6a1f39f)

**Comment by ThaliTester** [comment]
Test (Success) 93765317 build is completed (6a1f39f)

See https://github.com/ThaliTester/TestResults/tree/937653176a1f39f_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 937653176a1f39f(6a1f39f) has failed

See https://github.com/ThaliTester/TestResults/tree/937653176a1f39f_update_thali_development_environment_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2c2e8c7)

**Comment by ThaliTester** [comment]
Test (Success) 93765317 build is completed (2c2e8c7)

See https://github.com/ThaliTester/TestResults/tree/937653172c2e8c7_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 937653172c2e8c7(2c2e8c7) has failed

See https://github.com/ThaliTester/TestResults/tree/937653172c2e8c7_update_thali_development_environment_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5ffa230)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (5ffa230)

See https://github.com/ThaliTester/TestResults/tree/937653175ffa230_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (06b1c3e)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b8f1257)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (06b1c3e)

See https://github.com/ThaliTester/TestResults/tree/9376531706b1c3e_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (57daca3)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (b8f1257)

See https://github.com/ThaliTester/TestResults/tree/93765317b8f1257_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (75fe588)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (75fe588)

See https://github.com/ThaliTester/TestResults/tree/9376531775fe588_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (2bc36f3)

**Comment by ThaliTester** [comment]
Test 9376531757daca3(57daca3) has failed

See https://github.com/ThaliTester/TestResults/tree/9376531757daca3_update_thali_development_environment_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (2bc36f3)

See https://github.com/ThaliTester/TestResults/tree/937653172bc36f3_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (170757b)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (fc97e3b)

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (170757b)

See https://github.com/ThaliTester/TestResults/tree/93765317170757b_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 93765317 (fc97e3b) build started.

undefined

**Comment by ThaliTester** [comment]
Test 93765317 (fc97e3b) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (fc97e3b)

See https://github.com/ThaliTester/TestResults/tree/93765317fc97e3b_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bb8f64d)

**Comment by ThaliTester** [comment]
Test 93765317 (bb8f64d) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (bb8f64d)

See https://github.com/ThaliTester/TestResults/tree/93765317bb8f64d_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5054e41)

**Comment by ThaliTester** [comment]
Test 93765317 (5054e41) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (5054e41)

See https://github.com/ThaliTester/TestResults/tree/937653175054e41_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (193e2dc)

**Comment by ThaliTester** [comment]
Test 93765317 (193e2dc) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (193e2dc)

See https://github.com/ThaliTester/TestResults/tree/93765317193e2dc_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (97bcf18)

**Comment by ThaliTester** [comment]
Test 93765317 (97bcf18) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (97bcf18)

See https://github.com/ThaliTester/TestResults/tree/9376531797bcf18_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7bae7be)

**Comment by ThaliTester** [comment]
Test 93765317 (7bae7be) build started.

**Comment by ThaliTester** [comment]
Test 93765317 (7bae7be) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (7bae7be)

See https://github.com/ThaliTester/TestResults/tree/937653177bae7be_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (141d42a)

**Comment by ThaliTester** [comment]
Test 93765317 (141d42a) build started.

**Comment by ThaliTester** [comment]
Test 93765317 (141d42a) build started.

**Comment by ThaliTester** [comment]
Test (Success) 93765317 build is completed (141d42a)

See https://github.com/ThaliTester/TestResults/tree/93765317141d42a_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 93765317141d42a(141d42a) has failed

See https://github.com/ThaliTester/TestResults/tree/93765317141d42a_update_thali_development_environment_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4b4be82)

**Comment by ThaliTester** [comment]
Test 93765317 (4b4be82) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3bdc6ec)

**Comment by ThaliTester** [comment]
Test 93765317 (3bdc6ec) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (4b4be82)

See https://github.com/ThaliTester/TestResults/tree/937653174b4be82_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (3bdc6ec)

See https://github.com/ThaliTester/TestResults/tree/937653173bdc6ec_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3a8cc8a)

**Comment by larryonoff** [comment]
@yaronyg please review. Please note that build fails since desktop tests.

**Comment by ThaliTester** [comment]
Test 93765317 (3a8cc8a) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (3a8cc8a)

See https://github.com/ThaliTester/TestResults/tree/937653173a8cc8a_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8c887bd)

**Comment by ThaliTester** [comment]
Test 93765317 (8c887bd) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (8c887bd)

See https://github.com/ThaliTester/TestResults/tree/937653178c887bd_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ded9f2f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (e026bf0)

**Comment by ThaliTester** [comment]
Test 93765317 (ded9f2f) build started.

**Comment by ThaliTester** [comment]
Test 93765317 (e026bf0) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (ded9f2f)

See https://github.com/ThaliTester/TestResults/tree/93765317ded9f2f_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (e026bf0)

See https://github.com/ThaliTester/TestResults/tree/93765317e026bf0_update_thali_development_environment_larryonoff/ for the logs

**Comment by yaronyg** [comment]
Other than my pushd comment and the fact that this doesn't seem to be passing CI :lgtm: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 5 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 12 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1523#-KX8a6s37OR5Y30xz4hp:-KX8a6s37OR5Y30xz4hq:bqd4x8d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e026bf07586c9d02c362a370ed2aa4f2889dfc5e/build.sh#L12)):*
> ```Shell
> 
> pushd "$(dirname $0)" > /dev/null
> SCRIPT_PATH="$(pwd -P)"
> ```

There has got to be an easier way to do this. Using pushd/popd is just crazy circuitous. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1523#-:-KX8arDNAYnouOTWR1Ag:b-ih1kqj)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d84ddb3)

**Comment by larryonoff** [comment]
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[build.sh, line 12 at r8](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1523#-KX8a6s37OR5Y30xz4hp:-KXAZ3nHhGyc1XkEKV0B:b3zshto) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e026bf07586c9d02c362a370ed2aa4f2889dfc5e/build.sh#L12)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> There has got to be an easier way to do this. Using pushd/popd is just crazy circuitous. 
</details>
I didn't fine easy construction for macOS. But anyway I replaced pushd/popd with `SCRIPT_PATH="$(cd "$(dirname "$0")"; pwd -P)"`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1523)*

**Comment by ThaliTester** [comment]
Test 93765317 (d84ddb3) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (d84ddb3)

See https://github.com/ThaliTester/TestResults/tree/93765317d84ddb3_update_thali_development_environment_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9e632f2)

**Comment by ThaliTester** [comment]
Test 93765317 (9e632f2) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 93765317 build is completed (9e632f2)

See https://github.com/ThaliTester/TestResults/tree/937653179e632f2_update_thali_development_environment_larryonoff/ for the logs

**Pull request merged**
