### PR TITLE
(#417) Replication

### PR DESCRIPTION
**Pull request by yaronyg**
@jareksl I know this is huge but it's not going to get any smaller and I need to check it in sometime. It won't pass CI tests because of the Express-PouchDB problem but that will hopefully just be a bug fix. Please ignore all the java files as those are part of #720 and will be reviewed there. So please just pay attention to, well, everything else. A lot of the changes are just linting so in reviewable it should be easy to see that something is just a spacing change and not changing content. Sorry for dumping this monster on you but somebody has to do it. :)

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/740)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dbcc44d)

**Comment by ThaliTester** [comment]
Test (Fail) 75173807 build is completed (dbcc44d)

See https://github.com/ThaliTester/TestResults/tree/75173807dbcc44d___417__Replication_yaronyg/ for the logs

**Comment by yaronyg** [comment]
We won't actually check this in until #720 is checked in and we can get the known test issues resolved.

---

Reviewed 8 of 30 files at r4, 23 of 54 files at r5.
Review status: 31 of 62 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/740#-KL3GFmy-Qmkg9McVNQC:-KL3GFmy-Qmkg9McVNQD:2131139920) (no related file):*
BTW I went through the files and marked as green the ones that were pure linting or part of #720. That actually got rid of about 1/2 the files in the PR. So you can just focus on the red ones.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/740#-:-KL3EKbtgGCjQGmPR2jN:641707547)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8130305)

**Comment by ThaliTester** [comment]
Test (Fail) 75173807 build is completed (8130305)

See https://github.com/ThaliTester/TestResults/tree/751738078130305___417__Replication_yaronyg/ for the logs

**Comment by jareksl** [comment]
*[test/www/jxcore/bv_tests/testThaliMobile.js, line 3 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/740#-KLQvVwgDaWqlOIKQiPm:-KLQvVwhYGLpiqOHSagT:-2082316116) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8130305ed2a11afe9cb9acb8e80628870e4298cf/test/www/jxcore/bv_tests/testThaliMobile.js#L3)):*
> ```JavaScript
> 'use strict';
> 
> var ThaliMobile = require('thali/NextGeneration/thaliMobile');
> ```

By the way as you corrected other lint warnings it would be good to correct the rest of variable names to be consistent with the rest of the code. They should start with a lower case letter. The PascalCase should be used for constructor functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/740)*

**Comment by yaronyg** [comment]
@jareksl When do you think you will have a chance to finish this review? Thanks!

**Comment by jareksl** [comment]
Reviewed 8 of 30 files at r4, 48 of 54 files at r5, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/740)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (56750c6)

**Comment by ThaliTester** [comment]
Test (Fail) 75173807 build is completed (56750c6)

See https://github.com/ThaliTester/TestResults/tree/7517380756750c6___417__Replication_yaronyg/ for the logs

**Comment by yaronyg** [comment]
Closing in favor of vNext_yarong_417_812

**Pull request closed without merging**
