### PR TITLE
Android changes to superbranch

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1183)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (f0eea6c)

**Comment by ThaliTester** [comment]
Test (Fail) 86930490 build is completed (f0eea6c)

See https://github.com/ThaliTester/TestResults/tree/86930490f0eea6c_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4783428)

**Comment by ThaliTester** [comment]
Test (Fail) 86930490 build is completed (4783428)

See https://github.com/ThaliTester/TestResults/tree/869304904783428_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b689f01)

**Comment by ThaliTester** [comment]
Test (Success) 86930490 build is completed (b689f01)

See https://github.com/ThaliTester/TestResults/tree/86930490b689f01_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 86930490b689f01(b689f01) has failed

See https://github.com/ThaliTester/TestResults/tree/86930490b689f01_Android_changes_to_superbranch_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6629475)

**Comment by ThaliTester** [comment]
Test (Success) 86930490 build is completed (6629475)

See https://github.com/ThaliTester/TestResults/tree/869304906629475_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 869304906629475(6629475) has failed

See https://github.com/ThaliTester/TestResults/tree/869304906629475_Android_changes_to_superbranch_evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
Please add the requested bug #s to the code and then :lgtm: 

---

Reviewed 2 of 45 files at r2, 10 of 82 files at r7, 6 of 70 files at r8, 9 of 53 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 436 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-KShMY4vWdijHpylCk5k:-KShMY4wwZ8wkAf0hr0v:b-7pc20w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6629475a362841dd82e9141e985d75e45a32b352/src/android/java/io/jxcore/node/ConnectionHelper.java#L436)):*
> ```Java
>         Log.e(TAG, "onConnectionFailed: Peer properties: " + peerProperties + ", error message: " + errorMessage);
> 
>         //TODO add notification here even if properties are null
> ```

Is there a bug # for this TODO so we can put it here and make sure we don't forget?

---

*[src/android/java/io/jxcore/node/OutgoingSocketThread.java, line 22 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-KShMvSEQZevzyU6nmUK:-KShMvSFVFzbjW8TSFD7:b-183aul) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6629475a362841dd82e9141e985d75e45a32b352/src/android/java/io/jxcore/node/OutgoingSocketThread.java#L22)):*
> ```Java
>     private ServerSocket mServerSocket = null;
>     private int mListeningOnPortNumber = ConnectionHelper.NO_PORT_NUMBER;
>     //TODO remove it. Just for logging and test purposes
> ```

Please enter the bug # so we don't forget :)

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 135 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-KShNxiDRCos57COlmLx:-KShNxiDRCos57COlmLy:b-xoqtqo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6629475a362841dd82e9141e985d75e45a32b352/src/android/java/io/jxcore/node/StreamCopyingThread.java#L135)):*
> ```Java
>                 totalNumberOfBytesRead += numberOfBytesRead;
> 
> //                Log.d(TAG, "Successfully readed");
> ```

NB: Please remove the commented out code unless you still need it for debugging

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 145 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-KShO4BHAe02WlyhTop4:-KShO4BHAe02WlyhTop5:btxq4jr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6629475a362841dd82e9141e985d75e45a32b352/src/android/java/io/jxcore/node/StreamCopyingThread.java#L145)):*
> ```Java
>                 isFlushing = false;
> 
> //                Log.d(TAG, "Wrote " + numberOfBytesRead + " bytes (thread ID: " + getId() + ", thread name: " + mThreadName + ")");
> ```

NB: Same here unless it is still needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-:-KShguYoqBHQBmTaH_g1:b-oke1ro)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9173baf)

**Comment by ThaliTester** [comment]
Test (Fail) 86930490 build is completed (9173baf)

See https://github.com/ThaliTester/TestResults/tree/869304909173baf_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
Review status: 28 of 32 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionHelper.java, line 436 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-KShMY4vWdijHpylCk5k:-KSk91xWVtccK2bGRjh1:b-zdlx0y) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6629475a362841dd82e9141e985d75e45a32b352/src/android/java/io/jxcore/node/ConnectionHelper.java#L436)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Is there a bug # for this TODO so we can put it here and make sure we don't forget?
</details>
It's outdated TODO. We don't need to do anything if there was incoming connection

---

*[src/android/java/io/jxcore/node/OutgoingSocketThread.java, line 22 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-KShMvSEQZevzyU6nmUK:-KSkB3b75YBrpvgBcSIj:b4i4a42) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6629475a362841dd82e9141e985d75e45a32b352/src/android/java/io/jxcore/node/OutgoingSocketThread.java#L22)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Please enter the bug # so we don't forget :)
</details>
Bug #1195 

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 135 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-KShNxiDRCos57COlmLx:-KSkB_TQj_Uca6vmfdt5:ba3dfob) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6629475a362841dd82e9141e985d75e45a32b352/src/android/java/io/jxcore/node/StreamCopyingThread.java#L135)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Please remove the commented out code unless you still need it for debugging
</details>
Removed

---

*[src/android/java/io/jxcore/node/StreamCopyingThread.java, line 145 at r14](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-KShO4BHAe02WlyhTop4:-KSkBhlFuSMwhf2i5nWA:ba3dfob) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6629475a362841dd82e9141e985d75e45a32b352/src/android/java/io/jxcore/node/StreamCopyingThread.java#L145)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Same here unless it is still needed
</details>
Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (d7f4847)

**Comment by ThaliTester** [comment]
Test (Success) 86930490 build is completed (d7f4847)

See https://github.com/ThaliTester/TestResults/tree/86930490d7f4847_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r15, 2 of 2 files at r16.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1183#-:-KSkHL4onJETcoOxcrpe:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 86930490d7f4847(d7f4847) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/86930490d7f4847_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (5c629c1)

**Comment by evabishchevich** [comment]
d7f4847 successfully passed, but  ThaliTester says DO NOT SEND PR.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (90de6dc)

**Comment by ThaliTester** [comment]
Test (Success) 86930490 build is completed (5c629c1)

See https://github.com/ThaliTester/TestResults/tree/869304905c629c1_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 869304905c629c1(5c629c1) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/869304905c629c1_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86930490 build is completed (90de6dc)

See https://github.com/ThaliTester/TestResults/tree/8693049090de6dc_Android_changes_to_superbranch_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 8693049090de6dc(90de6dc) has failed

See https://github.com/ThaliTester/TestResults/tree/8693049090de6dc_Android_changes_to_superbranch_evabishchevich/ for the fail logs

**Pull request merged**
