### PR TITLE
Add sinon's sandboxing functionality to the test framework #1347

### PR DESCRIPTION
**Pull request by opetkevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1847)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fa2680b)

**Comment by ThaliTester** [comment]
Test 112761991 (fa2680b) build started.

**Comment by ThaliTester** [comment]
Test (Success) 112761991 build is completed (fa2680b)

See https://github.com/ThaliTester/TestResults/tree/112761991fa2680b_Add_sinon_s_sandboxing_functionality_to_the_test_framework__1347_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
Test 112761991fa2680b(fa2680b) has failed

See https://github.com/ThaliTester/TestResults/tree/112761991fa2680b_Add_sinon_s_sandboxing_functionality_to_the_test_framework__1347_opetkevich/ for the fail logs

**Comment by chapko** [comment]
-@chapko +@opetkevich 

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testTests.js, line 45 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFIpzBM3JwYsa2tnwK:-KgFIpzBM3JwYsa2tnwL:b-630gwx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testTests.js#L45)):*
> ```JavaScript
> test('test sinon sansbox spy', tape.sinonTest(function (t) {
>   this.spy(testObject, 'testSpyMethod');
>   t.equal(testObject.testSpyMethod, testSanboxObject.testSpyMethod,
> ```

This is a bit strange check. It will be always successful (unless `spy` performs some really crazy stuff with `testObject`).

`testObject` and `testSandboxObject` are the same object, and they will always have the same `testSpyMethod`.

More appropriate check would be just calling method and checking `spy.callCount` or something similar.

---

*[test/www/jxcore/bv_tests/testTests.js, line 70 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFRNnrFuD6F4MubtrS:-KgFRNnrFuD6F4MubtrT:byex6yu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testTests.js#L70)):*
> ```JavaScript
>   mock.verify();
>   t.end();
> }));
> ```

Also there should be a test to checks that `sinonTest` indeed restores all the spies, stubs and mocks.

---

*[test/www/jxcore/bv_tests/testThaliManager.js, line 43 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFKS3aD5vPtZfmLIu9:-KgFKS3aD5vPtZfmLIuA:b-hejo6v) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testThaliManager.js#L43)):*
> ```JavaScript
> });
> 
> function Mocks(t, sandboxObject) {
> ```

NB: why don't just call it `sandbox`? :)

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 288 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFLP2nSUCn5bwmkOOG:-KgFLP2nSUCn5bwmkOOH:bcsaerw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testThaliMobile.js#L288)):*
> ```JavaScript
>     process.nextTick(function () {
>       t.equals(spy.callCount, 1, 'should not have been called more than once');
>       ThaliMobile.emitter.emit.restore();
> ```

This line can be removed.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1895 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFKveuJesKnzVoV4qc:-KgFKveuJesKnzVoV4qd:b-grkh4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testThaliMobile.js#L1895)):*
> ```JavaScript
>       t.equal(peerIdentifier, somePeerIdentifier, 'Peer still matches');
>       t.ok(connectionErrorReceived, 'We got the connection error');
>       ThaliMobileNativeWrapper.disconnect.restore();
> ```

This line can be removed too.

---

*[test/www/jxcore/bv_tests/testThaliNotificationClient.js, line 149 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFMGhQf4gjp22lUIfm:-KgFMGhRfU3U6jpqgn2A:bey8njo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testThaliNotificationClient.js#L149)):*
> ```JavaScript
> });
> 
> function stubGetPeerHostInfo() {
> ```

NB: I would pass sandbox explicitly as parameter to make it more readable and easier to use.

---

*[test/www/jxcore/bv_tests/testThaliNotificationLocal.js, line 82 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFMxBGRRmIIQ_QTNnZ:-KgFMxBGRRmIIQ_QTNn_:b-a8691y) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testThaliNotificationLocal.js#L82)):*
> ```JavaScript
> };
> 
> function stubGetPeerHostInfo() {
> ```

NB: same as above

---

*[test/www/jxcore/bv_tests/testThaliNotificationServer.js, line 139 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFNAMzpoGi9wuNFeFt:-KgFNAMzpoGi9wuNFeFu:b-jcbh4k) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testThaliNotificationServer.js#L139)):*
> ```JavaScript
>     globalVariables.kill().then(function () {
>       globalVariables.spyStartUpdateAdvertisingAndListening.restore();
>       globalVariables.spyStopAdvertisingAndListening.restore();
> ```

Why don't move it to the `kill` method itself? I think it belongs there.

---

*[test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js, line 293 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFOzT3DyNHxZE6Eqlr:-KgFOzT4zs6qrD15PF_b:b-r5efk1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/bv_tests/testThaliWifiInfrastructure.js#L293)):*
> ```JavaScript
>   }
> 
>   captureMessages.call(this, function (messages) {
> ```

NB: `captureMessages` is a local function in this test, so it probably would be simpler to use `self = this`.

---

*[test/www/jxcore/lib/SinonTest.js, line 4 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFHzsw_7UUyJQuZGas:-KgFHzsw_7UUyJQuZGat:b-hzcxs5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/lib/SinonTest.js#L4)):*
> ```JavaScript
> 
> var util     = require('util');
> var inherits = util.inherits;
> ```

please, lint this file, eslint reports 11 errors.

---

*[test/www/jxcore/lib/SinonTest.js, line 10 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgFGsdreGlapWSzONe0:-KgFGsdreGlapWSzONe1:b-n5io8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fa2680b7f4e58a759ee3c7aef41459b09ed2a1f6/test/www/jxcore/lib/SinonTest.js#L10)):*
> ```JavaScript
> 
> 
> function SinonTest (callback) {
> ```

This is not a constructor so don't capitalize it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-:-KgFQgu7x6UBcMN1d05D:byjtkux)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (de7a3d0)

**Comment by ThaliTester** [comment]
Test 112761991 (de7a3d0) build started.

**Comment by ThaliTester** [comment]
Test (Success) 112761991 build is completed (de7a3d0)

See https://github.com/ThaliTester/TestResults/tree/112761991de7a3d0_Add_sinon_s_sandboxing_functionality_to_the_test_framework__1347_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d9ed552)

**Comment by ThaliTester** [comment]
Test 112761991 (d9ed552) build started.

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/sinonTest.js, line 32 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-KgKYT9lZ8kPAcx382Rp:-KgKYT9m_wor4YcKuzER:b-j10hje) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/de7a3d0a278ff0769957881fb10affb6c8b876a4/test/www/jxcore/lib/sinonTest.js#L32)):*
> ```JavaScript
>       result = callback.apply(this, args.concat(sandbox.args));
>     } catch (e) {
>       t.fail(e);
> ```

I expect that a function wrapped in `sinonTest` should behave the same way as original one. So if original function throws, wrapped should throw too.

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-:-KgKcUwfveAqsfFe_bSE:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Success) 112761991 build is completed (d9ed552)

See https://github.com/ThaliTester/TestResults/tree/112761991d9ed552_Add_sinon_s_sandboxing_functionality_to_the_test_framework__1347_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
Test 112761991d9ed552(d9ed552) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/112761991d9ed552_Add_sinon_s_sandboxing_functionality_to_the_test_framework__1347_opetkevich/ for the logs

**Comment by yaronyg** [comment]
I can't imagine this was any more fun to write than it was to review but good work, this should hopefully cause many current and future hysenbugs to go away. :lgtm:

---

Reviewed 12 of 22 files at r1, 10 of 11 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1847#-:-KgPsIk-SCut4PW4XjM3:b-2su85s)*

**Pull request merged**
