### PR TITLE
Added PouchDB agent test

### LINKED ISSUE #730: Get thaliReplicationPeerAction to honor httpAgentPool
In order to work around https://github.com/pouchdb/pouchdb/issues/5231 we need to pass in agentClass rather than agent (which is what we would have set with the httpAgentPool argument in start). So for right now we are manually specifying the agent class and options and ignoring httpAgentPool all together. If 5231 is fixed then we can use httpAgentPool, otherwise we need to redesign the action class so it submits the agentClass and options.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #730.

Our pouch `5.4.5` is fine. It has some kind of `isPlainObject` and this function bypasses our agent.

@chapko found a [commit](https://github.com/pouchdb/pouchdb/commit/a3736c7d455b5a0133fc594a395e1800d90ac010), it adds this function.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1466)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (05a4ffb)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (02e3c3c)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (311954f)

**Comment by ThaliTester** [comment]
Test (Fail) 91778172 build is completed (05a4ffb)

See https://github.com/ThaliTester/TestResults/tree/9177817205a4ffb_Added_PouchDB_agent_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 91778172 build is completed (02e3c3c)

See https://github.com/ThaliTester/TestResults/tree/9177817202e3c3c_Added_PouchDB_agent_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 91778172 build is completed (311954f)

See https://github.com/ThaliTester/TestResults/tree/91778172311954f_Added_PouchDB_agent_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d0798bd)

**Comment by ThaliTester** [comment]
Test (Fail) 91778172 build is completed (d0798bd)

See https://github.com/ThaliTester/TestResults/tree/91778172d0798bd_Added_PouchDB_agent_test_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1466#-:-KVWKsW1bd5uAFbv2tWM:b-uwkowd)*

**Comment by yaronyg** [comment]
@andrew-aladev So I officially suck. I had no business checking this in. It turns out it doesn't pass tests! Something I just discovered. :( I'm investigating now.

**Pull request merged**
