### PR TITLE
416 Thali notification end to end tests

### PR DESCRIPTION
**Pull request by juhanak**
This pull request contains end to end test in testThaliNotification.js file and a small fix in thaliNotificationClient.js file. Rest of the changes are same as in #666.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/677)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (860dd96)

**Comment by ThaliTester** [comment]
Test (Success) 64065450 build is completed (860dd96)

See https://github.com/ThaliTester/TestResults/tree/64065450860dd96_416_Thali_notification_end_to_end_tests_juhanak/ for the logs

**Comment by ThaliTester** [comment]
Test 64065450860dd96(860dd96) has failed

See https://github.com/ThaliTester/TestResults/tree/64065450860dd96_416_Thali_notification_end_to_end_tests_juhanak/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 5 of 8 files at r1, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/677)*

**Pull request merged**
