### PR TITLE
New thali tape for super branch

### LINKED ISSUE #1063: Merge PR with new thali tape into new super branch

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1063

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1064)

### CODE REVIEW

**Comment by yaronyg** [comment]
Please respond to the non-blocking comments below but that shouldn't stop you from checking in as I have no blocking comments so :LGTM:

---

Reviewed 12 of 19 files at r1, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 158 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzCiWEn6o2PjOMyGug:-KRzCiWEn6o2PjOMyGuh:b-brz2bn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/CoordinatedClient.js#L158)):*
> ```JavaScript
> 
>     // We are waiting for 'disconnect' event.
>     self._state = CoordinatedClient.states.completed;
> ```

NB: I wonder if there is a possible race condition where between the emit and the then (it's theoretically possible for code to sneak in there, although not likely given how aggressive promises typically are) some other messages could be received. So why not set the state before the emit and that way there is no possible race condition? This same logic applies to the emits below.

---

*[test/www/jxcore/lib/CoordinatedTape.js, line 82 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzBq0J19lih5VdLPI9:-KRzBq0J19lih5VdLPIA:b7gafrg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/CoordinatedTape.js#L82)):*
> ```JavaScript
>   return new Promise(function (resolve, reject) {
>     self._testClient.once('finished', function (error) {
>       if (error) {
> ```

NB: Why not "error ? reject(error) : resolve();"?

---

*[test/www/jxcore/lib/SimpleTape.js, line 72 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRz9jeAc11o-u0bd-fW:-KRz9jeBDLr-damy9av_:b-82jke6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/SimpleTape.js#L72)):*
> ```JavaScript
>   );
> 
>   if (this._ignoreRemainingTests) {
> ```

NB: Ideally we would fail if there is more than one .only. But it's not worth blocking for. I created an issue and we can add it later if we want to. https://github.com/thaliproject/Thali_CordovaPlugin/issues/1076

---

*[test/www/jxcore/lib/SimpleTape.js, line 110 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRz5ecZcXrYdONPGyy8:-KRz5ecZcXrYdONPGyy9:bxojqer) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/SimpleTape.js#L110)):*
> ```JavaScript
>       var success = true;
>       function resultHandler (result) {
>         if (!result.ok) {
> ```

NB: Why not just put success = result.ok?

---

*[test/www/jxcore/lib/testUtils.js, line 201 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzDF_6iv_jCnogrJkO:-KRzDF_7KbKciNL_6Rj3:b-7if0f4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/testUtils.js#L201)):*
> ```JavaScript
>   .then(function (networkStatus) {
>     logger.debug(
>       'Device did not have required hardware capabilities!'
> ```

NB: Shouldn't we reject at this point?

---

*[test/www/jxcore/lib/testUtils.js, line 207 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzDJotNZO-ctN2Ndjr:-KRzDJouBMIFv9RyoWgd:bnxanri) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/testUtils.js#L207)):*
> ```JavaScript
>       // the network status for BLE must not be reported to be "on"
>       // which would mean "The radio is on and available for use."
>       return Promise.resolve(false);
> ```

NB: This design doesn't work the way I'm used to promises working. Instead of returning true or false shouldn't we return resolve or reject?

---

*[test/www/jxcore/lib/utils/asserts.js, line 3 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRusZcXiFA6OO93PnwG:-KRusZcXiFA6OO93PnwH:b-q5by7g) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/utils/asserts.js#L3)):*
> ```JavaScript
> 'use strict';
> 
> var format = require('util').format;
> ```

NB: It makes me sad that we have asserts.js, polyfills.js, process.js and promise.js both here and in the test server. Since the test server should always be run out of the cloned depot could we just have the test server point at the code in test/www/jxcore/lib/utils?

---

*[thali/thaliLogger.js, line 19 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzGTS9AXxvmZe108X4:-KRzGTSAbiaavnFio1oz:b6vq9ih) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/thali/thaliLogger.js#L19)):*
> ```JavaScript
> ThaliLogger.prototype.name = 'thaliLogger';
> 
> if (
> ```

NB: This function and some of the code below is repeated exactly in logger.js. Since logger.js can see thaliLogger.js but not vice versa I would suggest that logger.js be changed to call this code here, at least as utility functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-:-KRzHHu-2_qlpjcbvviv:b-zch6v)*

**Comment by andrew-aladev** [comment]
Currently I am working on PR for test server and thali tape.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (954c582)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (d5e5f65)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (904a9e7)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (478a184)

**Comment by ThaliTester** [comment]
Test (Fail) 85615572 build is completed (954c582)

See https://github.com/ThaliTester/TestResults/tree/85615572954c582_New_thali_tape_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 85615572 build is completed (d5e5f65)

See https://github.com/ThaliTester/TestResults/tree/85615572d5e5f65_New_thali_tape_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 85615572 build is completed (904a9e7)

See https://github.com/ThaliTester/TestResults/tree/85615572904a9e7_New_thali_tape_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 85615572d5e5f65(d5e5f65) has failed

See https://github.com/ThaliTester/TestResults/tree/85615572d5e5f65_New_thali_tape_for_super_branch_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test 85615572904a9e7(904a9e7) has failed

See https://github.com/ThaliTester/TestResults/tree/85615572904a9e7_New_thali_tape_for_super_branch_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 85615572 build is completed (478a184)

See https://github.com/ThaliTester/TestResults/tree/85615572478a184_New_thali_tape_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 85615572478a184(478a184) has failed

See https://github.com/ThaliTester/TestResults/tree/85615572478a184_New_thali_tape_for_super_branch_andrew-aladev/ for the fail logs

**Comment by andrew-aladev** [comment]
Review status: 11 of 43 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/lib/SimpleTape.js, line 110 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRz5ecZcXrYdONPGyy8:-KS6MM8cxT5OX4Ukvp3-:b-dcj17e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/SimpleTape.js#L110)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Why not just put success = result.ok?
</details>
Results can be `[true, false, true]` and we have to show 'failed' in this case. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064)*

**Comment by andrew-aladev** [comment]
Review status: 11 of 43 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/lib/CoordinatedTape.js, line 82 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzBq0J19lih5VdLPI9:-KS6ea7YmP9h3_n2Ck1M:blwqa72) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/CoordinatedTape.js#L82)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Why not "error ? reject(error) : resolve();"?
</details>
I prefer to use ternary operator only in expressions, like "fit " + (a? 1: 2)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064)*

**Comment by andrew-aladev** [comment]
Review status: 11 of 43 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/lib/CoordinatedClient.js, line 158 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzCiWEn6o2PjOMyGug:-KS6kF0ewJdwqE3ejpXg:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/CoordinatedClient.js#L158)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: I wonder if there is a possible race condition where between the emit and the then (it's theoretically possible for code to sneak in there, although not likely given how aggressive promises typically are) some other messages could be received. So why not set the state before the emit and that way there is no possible race condition? This same logic applies to the emits below.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064)*

**Comment by andrew-aladev** [comment]
Review status: 11 of 43 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/lib/SimpleTape.js, line 72 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRz9jeAc11o-u0bd-fW:-KS6kItYLEeZt5xj_P5Q:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/SimpleTape.js#L72)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Ideally we would fail if there is more than one .only. But it's not worth blocking for. I created an issue and we can add it later if we want to. https://github.com/thaliproject/Thali_CordovaPlugin/issues/1076
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064)*

**Comment by andrew-aladev** [comment]
I am working on the last comment about re-using utils.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (23fedb8)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0de616b)

**Comment by ThaliTester** [comment]
Test (Success) 85615572 build is completed (23fedb8)

See https://github.com/ThaliTester/TestResults/tree/8561557223fedb8_New_thali_tape_for_super_branch_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 8561557223fedb8(23fedb8) has failed

See https://github.com/ThaliTester/TestResults/tree/8561557223fedb8_New_thali_tape_for_super_branch_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 85615572 build is completed (0de616b)

See https://github.com/ThaliTester/TestResults/tree/856155720de616b_New_thali_tape_for_super_branch_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
Review status: 11 of 44 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/lib/utils/asserts.js, line 3 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRusZcXiFA6OO93PnwG:-KS7aIQ9jXyzPTIUoxw5:btgi25x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/utils/asserts.js#L3)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: It makes me sad that we have asserts.js, polyfills.js, process.js and promise.js both here and in the test server. Since the test server should always be run out of the cloned depot could we just have the test server point at the code in test/www/jxcore/lib/utils?
</details>
I've created an [issue](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1096).

---

*[thali/ThaliLogger.js, line 19 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzGTS9AXxvmZe108X4:-KS7_wHLZENtRMJUQ2SJ:btgi25x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/thali/ThaliLogger.js#L19)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: This function and some of the code below is repeated exactly in logger.js. Since logger.js can see thaliLogger.js but not vice versa I would suggest that logger.js be changed to call this code here, at least as utility functions.
</details>
I've created an [issue](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1096).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064)*

**Comment by andrew-aladev** [comment]
Review status: 11 of 44 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 201 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzDF_6iv_jCnogrJkO:-KS7awjufpp8NHirHdpq:btgi2wm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/testUtils.js#L201)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Shouldn't we reject at this point?
</details>
I've created an [issue](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1097).

---

*[test/www/jxcore/lib/testUtils.js, line 207 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064#-KRzDJotNZO-ctN2Ndjr:-KS7b0Ik7p9CADrI4VOd:btgi2wm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15631c8d0ab1078b668b09940433b3f86e58020a/test/www/jxcore/lib/testUtils.js#L207)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: This design doesn't work the way I'm used to promises working. Instead of returning true or false shouldn't we return resolve or reject?
</details>
I've created an [issue](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1097).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1064)*

**Comment by ThaliTester** [comment]
Test 856155720de616b(0de616b) has failed

See https://github.com/ThaliTester/TestResults/tree/856155720de616b_New_thali_tape_for_super_branch_andrew-aladev/ for the fail logs

**Pull request merged**
