### PR TITLE
Removed parameter UT

### PR DESCRIPTION
**Pull request by jareksl**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/832)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7c16410)

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/832#-:-KOJgrglYDFEIVBafkkp:1417088721)*

**Comment by ThaliTester** [comment]
Test (Success) 80038063 build is completed (7c16410)

See https://github.com/ThaliTester/TestResults/tree/800380637c16410_Removed_parameter_UT_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 800380637c16410(7c16410) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/800380637c16410_Removed_parameter_UT_jareksl/ for the logs

**Pull request merged**
