### PR TITLE
Update Android tools versions

### PR DESCRIPTION
**Pull request by czyzm**
Fix for #1762

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1763)

### CODE REVIEW

**Comment by ThaliTester** [comment]
Test 103691986 (c90445e) build started.

**Comment by ThaliTester** [comment]
Test (Success) 103691986 build is completed (c90445e)

See https://github.com/ThaliTester/TestResults/tree/103691986c90445e_Update_Android_tools_versions_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 103691986c90445e(c90445e) has failed

See https://github.com/ThaliTester/TestResults/tree/103691986c90445e_Update_Android_tools_versions_czyzm/ for the fail logs

**Comment by evabishchevich** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/validateBuildEnvironment.js, line 31 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1763#-Kbi_Qfo6PnN2XKJC4YI:-Kbi_Qfo6PnN2XKJC4YJ:bfndw2r) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c90445ecf7ece40dba569fc1ff3d673d87beb49b/thali/install/validateBuildEnvironment.js#L31)):*
> ```JavaScript
>   // we have but if they were installed recently enough then they will have
>   // what we need.
>   androidSupportLibraries: '41.0.0',
> ```

Does it work fine with "cordova-android" version=">=6.0.0"  engine?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1763)*

**Comment by czyzm** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/validateBuildEnvironment.js, line 31 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1763#-Kbi_Qfo6PnN2XKJC4YI:-KbihI0a5_YT63OrN-E6:bhwqtsq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c90445ecf7ece40dba569fc1ff3d673d87beb49b/thali/install/validateBuildEnvironment.js#L31)):*
<details><summary><i>Previously, evabishchevich wrote…</i></summary><blockquote>

Does it work fine with "cordova-android" version=">=6.0.0"  engine?
</blockquote></details>

It seems so. We are using it also for TeamONE and haven't noticed any issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1763)*

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/validateBuildEnvironment.js, line 31 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1763#-Kbi_Qfo6PnN2XKJC4YI:-Kbj2iSG7BJkzpNC_j26:b32wtd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/c90445ecf7ece40dba569fc1ff3d673d87beb49b/thali/install/validateBuildEnvironment.js#L31)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

It seems so. We are using it also for TeamONE and haven't noticed any issue.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1763#-:-Kbj2js30v3Ms1KXb7ub:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1763#-:-KblMLUpViyrXxs0ydti:bnfp4nl)*

**Pull request merged**
