### PR TITLE
Each pouchdb instance wants to sit in it's own directory

### PR DESCRIPTION
**Pull request by andrew-aladev**
Related to #968

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/998)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5c22abf)

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (5c22abf)

See https://github.com/ThaliTester/TestResults/tree/841658655c22abf_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by artemjackson** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/998#-:-KSHWOsOyI_BqDAy8auZ:bnfp4nl)*

**Comment by yaronyg** [comment]
@andrew-aladev Shouldn't this be going to vNext_yarong_417_812?

Also there is a blocking comment below on error handling. But once you resolve the branch issue and the error handling then you have a :lgtm: without having to check with me again.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[test/www/jxcore/bv_tests/disabled/testThaliManagerStopCoordinated.js, line 13 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/998#-KSJHPyFMfNCVWZK1hGC:-KSJHPyGP0w4p1xQ0G5W:bau2rxe) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5c22abf51afa2ac5e712c62761a9bac982ea3c9b/test/www/jxcore/bv_tests/disabled/testThaliManagerStopCoordinated.js#L13)):*
> ```JavaScript
> var path = require('path');
> var crypto = require('crypto');
> var Promise = require('lie');
> ```

Why is this still disabled?

---

*[test/www/jxcore/lib/testUtils.js, line 629 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/998#-KSJHzFs59FfYfYAU2U0:-KSJHzFtQxAkIXABVDk2:b8t1r1s) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5c22abf51afa2ac5e712c62761a9bac982ea3c9b/test/www/jxcore/lib/testUtils.js#L629)):*
> ```JavaScript
> 
> var pouchDBTestDirectory = path.join(tmpDirectory(), 'pouchdb-test-directory');
> fs.ensureDirSync(pouchDBTestDirectory);
> ```

It's possible for there to be an error. Such as the directory doesn't exist and the system couldn't create it. So we need an error handler that checks that we didn't get an error back and if we do fails out. This applies everywhere we use ensureDirSync.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/998#-:-KRUhiqsOu5SYRnUXANs:bhiu33c)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (5805273)

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (5805273)

See https://github.com/ThaliTester/TestResults/tree/841658655805273_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (dbb99c6)

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (dbb99c6)

See https://github.com/ThaliTester/TestResults/tree/84165865dbb99c6_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (f02e1ee)

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (016d3cf)

See https://github.com/ThaliTester/TestResults/tree/84165865016d3cf_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (f02e1ee)

See https://github.com/ThaliTester/TestResults/tree/84165865f02e1ee_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c5ca4c3)

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (c5ca4c3)

See https://github.com/ThaliTester/TestResults/tree/84165865c5ca4c3_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9b45f59)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (07ad716)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (b735791)

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (9b45f59)

See https://github.com/ThaliTester/TestResults/tree/841658659b45f59_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (07ad716)

See https://github.com/ThaliTester/TestResults/tree/8416586507ad716_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
This needs to be updated to master there is a merge conflict but this isn't blocking anybody so it isn't a priority right now.

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (b735791)

See https://github.com/ThaliTester/TestResults/tree/84165865b735791_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2f40a26)

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (2f40a26)

See https://github.com/ThaliTester/TestResults/tree/841658652f40a26_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (491889c)

**Comment by ThaliTester** [comment]
Test (Fail) 84165865 build is completed (491889c)

See https://github.com/ThaliTester/TestResults/tree/84165865491889c_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9998c06)

**Comment by ThaliTester** [comment]
Test (Success) 84165865 build is completed (9998c06)

See https://github.com/ThaliTester/TestResults/tree/841658659998c06_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 841658659998c06(9998c06) has failed

See https://github.com/ThaliTester/TestResults/tree/841658659998c06_Each_pouchdb_instance_wants_to_sit_in_it_s_own_directory_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/998#-:-KTVXvPoLsPER_GRt5a_:bnfp4nl)*

**Pull request merged**
