### PR TITLE
Test framework improvements

### PR DESCRIPTION
**Pull request by vjrantal**
* Use random set of devices from the ones that present to the server
* Allow tests to continue if socket.io gets reconnected
* Report success only if all succeed

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/685)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f00187f)

**Comment by ThaliTester** [comment]
Test (Success) 64613803 build is completed (f00187f)

See https://github.com/ThaliTester/TestResults/tree/64613803f00187f_Test_framework_improvements_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 64613803f00187f(f00187f) has failed

See https://github.com/ThaliTester/TestResults/tree/64613803f00187f_Test_framework_improvements_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8d447f5)

**Comment by ThaliTester** [comment]
Test (Success) 64613803 build is completed (8d447f5)

See https://github.com/ThaliTester/TestResults/tree/646138038d447f5_Test_framework_improvements_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 646138038d447f5(8d447f5) has failed

See https://github.com/ThaliTester/TestResults/tree/646138038d447f5_Test_framework_improvements_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (717efd7)

**Comment by ThaliTester** [comment]
Test (Success) 64613803 build is completed (717efd7)

See https://github.com/ThaliTester/TestResults/tree/64613803717efd7_Test_framework_improvements_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 64613803717efd7(717efd7) has failed

See https://github.com/ThaliTester/TestResults/tree/64613803717efd7_Test_framework_improvements_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6c5f71d)

**Comment by ThaliTester** [comment]
Test (Success) 64613803 build is completed (6c5f71d)

See https://github.com/ThaliTester/TestResults/tree/646138036c5f71d_Test_framework_improvements_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 646138036c5f71d(6c5f71d) has failed

See https://github.com/ThaliTester/TestResults/tree/646138036c5f71d_Test_framework_improvements_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (adf70b9)

**Comment by ThaliTester** [comment]
Test (Success) 64613803 build is completed (adf70b9)

See https://github.com/ThaliTester/TestResults/tree/64613803adf70b9_Test_framework_improvements_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 64613803adf70b9(adf70b9) has failed

See https://github.com/ThaliTester/TestResults/tree/64613803adf70b9_Test_framework_improvements_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8b5bc7c)

**Comment by ThaliTester** [comment]
Test 646138038b5bc7c(8b5bc7c) has failed

See https://github.com/ThaliTester/TestResults/tree/646138038b5bc7c_Test_framework_improvements_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 8 of 13 files at r3, 2 of 3 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/685#-:-KECfDKj71CDQPtagDs8:1417088721)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d18c8d9)

**Comment by ThaliTester** [comment]
Test (Success) 64613803 build is completed (d18c8d9)

See https://github.com/ThaliTester/TestResults/tree/64613803d18c8d9_Test_framework_improvements_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 64613803d18c8d9(d18c8d9) has failed

See https://github.com/ThaliTester/TestResults/tree/64613803d18c8d9_Test_framework_improvements_vjrantal/ for the fail logs

**Pull request merged**
