### PR TITLE
Get rid of recreatePeer logic on iOS

### PR DESCRIPTION
**Pull request by mlesnic**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1948)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3b7bbcf)

**Comment by ThaliTester** [comment]
Test 132007755 (3b7bbcf) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 132007755 build is completed (3b7bbcf)

See https://github.com/ThaliTester/TestResults/tree/1320077553b7bbcf_Get_rid_of_recreatePeer_logic_on_iOS_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (285fc7e)

**Comment by ThaliTester** [comment]
Test 132007755 (285fc7e) build started.

**Comment by ThaliTester** [comment]
Test (Success) 132007755 build is completed (285fc7e)

See https://github.com/ThaliTester/TestResults/tree/132007755285fc7e_Get_rid_of_recreatePeer_logic_on_iOS_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 132007755285fc7e(285fc7e) has failed

See https://github.com/ThaliTester/TestResults/tree/132007755285fc7e_Get_rid_of_recreatePeer_logic_on_iOS_mlesnic/ for the fail logs

**Comment by jareksl** [comment]
Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 1 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1948#-Kpoi3e14rQ6L_UTHoyE:-Kpoi3e14rQ6L_UTHoyF:bnwu0pk) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/285fc7e998e9b4763fb3aa928e536c71ee3251c8/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L1)):*
> ```JavaScript
> 
> ```

NB: This whitespace is not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1948)*

**Comment by jareksl** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1948#-:-KpoiaVzHmAQHEqVAOG8:bg7igkv)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6d760cd)

**Comment by ThaliTester** [comment]
Test 132007755 (6d760cd) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 132007755 build is completed (6d760cd)

See https://github.com/ThaliTester/TestResults/tree/1320077556d760cd_Get_rid_of_recreatePeer_logic_on_iOS_mlesnic/ for the logs

**Comment by enricogior** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1948#-:-KptYdOxmhBf5Mrb5ioZ:bnfp4nl)*

**Comment by enricogior** [comment]
Reviewed 1 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1948)*

**Comment by jareksl** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1948)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1948#-:-KpuTYaOC2CjAc-M1Yot:bnfp4nl)*

**Pull request merged**
