### PR TITLE
Can shift data via parallel connections fails on desktop #1857

### PR DESCRIPTION
**Pull request by opetkevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1858)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3fe8f92)

**Comment by ThaliTester** [comment]
Test 116780097 (3fe8f92) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 116780097 build is completed (3fe8f92)

See https://github.com/ThaliTester/TestResults/tree/1167800973fe8f92_Can_shift_data_via_parallel_connections_fails_on_desktop__1857_opetkevich/ for the logs

**Comment by evabishchevich** [comment]
Logs: https://gist.github.com/evabishchevich/083caaee7069031798ca83baa45d3042

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 345 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-KiBAZq5POE-bdIkUiOi:-KiBAZq6YPic0tJLWgJN:b-f8u5cn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ececf88c96c56b0586750ba910438bc8bc6c50ef/test/www/jxcore/bv_tests/testThaliMobileNative.js#L345)):*
> ```JavaScript
>     });
>     sock.on('end', function () {
>       t.equal(receivedData, exchangeData, 'got the same data back');
> ```

Why do we need to remove this? The only way I can see this failing is if after the call to sock.end() somehow more data showed up thus changing receivedData and causing the comparison to fail. And if that did happen isn't that an error we should catch? What am I missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858)*

**Comment by opetkevich** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 345 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-KiBAZq5POE-bdIkUiOi:-KiFqPIWRUo59WxmIi6X:b-9cz97q) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ececf88c96c56b0586750ba910438bc8bc6c50ef/test/www/jxcore/bv_tests/testThaliMobileNative.js#L345)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why do we need to remove this? The only way I can see this failing is if after the call to sock.end() somehow more data showed up thus changing receivedData and causing the comparison to fail. And if that did happen isn't that an error we should catch? What am I missing?
</blockquote></details>

@yaronyg
We already have the same check when we receive all the data.  If we check this again when the "end" event is received it can fail because it can compare current data with the data which came from another socket. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6d9437e)

**Comment by ThaliTester** [comment]
Test 116780097 (6d9437e) build started.

**Comment by ThaliTester** [comment]
Test (Success) 116780097 build is completed (6d9437e)

See https://github.com/ThaliTester/TestResults/tree/1167800976d9437e_Can_shift_data_via_parallel_connections_fails_on_desktop__1857_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
Test 1167800976d9437e(6d9437e) has failed

See https://github.com/ThaliTester/TestResults/tree/1167800976d9437e_Can_shift_data_via_parallel_connections_fails_on_desktop__1857_opetkevich/ for the fail logs

**Comment by yaronyg** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 345 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-KiBAZq5POE-bdIkUiOi:-KiGUm7c3yOdaXfLM9yF:b6lqs2v) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ececf88c96c56b0586750ba910438bc8bc6c50ef/test/www/jxcore/bv_tests/testThaliMobileNative.js#L345)):*
<details><summary><i>Previously, opetkevich (Olga Petkevich) wrote…</i></summary><blockquote>

@yaronyg
We already have the same check when we receive all the data.  If we check this again when the "end" event is received it can fail because it can compare current data with the data which came from another socket. 
</blockquote></details>

How is that possible? We pass a specific socket in. We are listening for the end event on that and only that socket. exchangeData is treated as a constant everywhere it is used so that can't change. And receivedData is defined inside of the function and can't change either. So I don't see what the problem is. Sorry if I'm being thick.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858)*

**Comment by yaronyg** [comment]
Still need an answer to the question I asked two weeks ago.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 345 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-KiBAZq5POE-bdIkUiOi:-KjOeMhND16-1HHKP28R:b-8isxr6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ececf88c96c56b0586750ba910438bc8bc6c50ef/test/www/jxcore/bv_tests/testThaliMobileNative.js#L345)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

How is that possible? We pass a specific socket in. We are listening for the end event on that and only that socket. exchangeData is treated as a constant everywhere it is used so that can't change. And receivedData is defined inside of the function and can't change either. So I don't see what the problem is. Sorry if I'm being thick.
</blockquote></details>

This question has been outstanding for two weeks. Any answer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-:-KjOeUl1-XwPc4YUTHZU:bebyzgb)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dac6cb4)

**Comment by ThaliTester** [comment]
Test 116780097 (dac6cb4) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 116780097 build is completed (dac6cb4)

See https://github.com/ThaliTester/TestResults/tree/116780097dac6cb4_Can_shift_data_via_parallel_connections_fails_on_desktop__1857_opetkevich/ for the logs

**Comment by dersim-davaod** [comment]
I've increased the size of data that we transfer between peers in our tests.


Also socket.end() calls were replaced with socket.destroy() calls, because node.js documentation says following:

socket.end([data][, encoding])
Half-closes the socket. i.e., it sends a FIN packet. It is possible the server will still send some data.
If data is specified, it is equivalent to calling socket.write(data, encoding) followed by socket.end().

It was done because not long ago we decided that the node side is responsible for closing connections, not the native, thus end() calls don't work for us anymore.
In short on the native side we have autoDisconnectOnClosedReadStream which is turned off, so FIN packets after end() call will be simply ignored. Please see https://github.com/thaliproject/thali-ios/pull/6#issuecomment-294909661 for mode details.

---

Reviewed 3 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 345 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-KiBAZq5POE-bdIkUiOi:-KjJMXna_oFcccYsZCkZ:b-rzfzc2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ececf88c96c56b0586750ba910438bc8bc6c50ef/test/www/jxcore/bv_tests/testThaliMobileNative.js#L345)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

This question has been outstanding for two weeks. Any answer?
</blockquote></details>

@yaronyg, you're absolutely right. I checked the code and ran some tests. For sure only specific socket is receiving the data. So I totally agree to have this check thus I've returned this line back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-:-KjcOpcgSsPe--ry8Cg6:b-fr45m)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1c74f09)

**Comment by ThaliTester** [comment]
Test 116780097 (1c74f09) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 116780097 build is completed (1c74f09)

See https://github.com/ThaliTester/TestResults/tree/1167800971c74f09_Can_shift_data_via_parallel_connections_fails_on_desktop__1857_opetkevich/ for the logs

**Comment by yaronyg** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 345 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-KiBAZq5POE-bdIkUiOi:-Kjci4TaN9lgnTm-6pR3:bs8gv24) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ececf88c96c56b0586750ba910438bc8bc6c50ef/test/www/jxcore/bv_tests/testThaliMobileNative.js#L345)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary><blockquote>

@yaronyg, you're absolutely right. I checked the code and ran some tests. For sure only specific socket is receiving the data. So I totally agree to have this check thus I've returned this line back.
</blockquote></details>

The line doesn't seem to have returned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858)*

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858)*

**Comment by dersim-davaod** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 345 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-KiBAZq5POE-bdIkUiOi:-KjcibMOsizy4-h5AWgp:b-9lj3nb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ececf88c96c56b0586750ba910438bc8bc6c50ef/test/www/jxcore/bv_tests/testThaliMobileNative.js#L345)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

The line doesn't seem to have returned.
</blockquote></details>

Could you please check it again? (Wrong selected revisions in file matrix above can be the reason of misunderstanding).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 345 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-KiBAZq5POE-bdIkUiOi:-KjdBSFKVIsZQXV_3LXl:b-ylmam6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/ececf88c96c56b0586750ba910438bc8bc6c50ef/test/www/jxcore/bv_tests/testThaliMobileNative.js#L345)):*
<details><summary><i>Previously, dersim-davaod wrote…</i></summary><blockquote>

Could you please check it again? (Wrong selected revisions in file matrix above can be the reason of misunderstanding).
</blockquote></details>

Yup. When I reset the matrix I could see the line. Sorry. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1858#-:-KjdBWbO5N_0MCukXyCY:bnfp4nl)*

**Pull request merged**
