### PR TITLE
Merge master into iOS

### PR DESCRIPTION
**Pull request by chapko**
I know this PR is huge, but it also contains several fixes I've added after the merges itself.

The following commits are the ones that contain actual changes:

- [fix test runner after merge](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1487/commits/8f1375d15e5b6dfc3726e3947fbb84c45e827340)
- [disable failing tests](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1487/commits/76471d4ebc404210ba2d15a51bd7ffd059c1ff53)
- [Temporarily disable failing tests. Fix mock bugs](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1487/commits/a88d5b0b1f9f5f060ef30328211181425a34c38f)
- [Re-tag disabled tests](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1487/commits/0b465fb52cd814cceff229033a9cb3c3dde04d95)
- [Implement listener recreation handling from PR](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1487/commits/027a6ede762a455d37a7b347152962b9a5c88347) #1490
- [Fix event name](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1487/commits/5cbbf682cff9e070e3787acbbdb43027a9d34eb6)
- [Fix `connectionType` of the after listener recreating](https://github.com/thaliproject/Thali_CordovaPlugin/pull/1487/commits/65c917025e56bdfa662a5dfb94fed565e83785aa)

I have disabled all the failing tests until #899 is done. All the remaining tests are passing on CI and locally (I didn't test on devices, only on desktop).

---
*Edit*: There is a bug in listener recreation handling that is fixed in #899 ([exact diff](https://github.com/thaliproject/Thali_CordovaPlugin/commit/76958ec084d0168970a1166f9bfd72bf4fb9aa80#diff-f2f101b08801e08c38ab271bcb4f69ed))

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1487)

### CODE REVIEW

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (883a779)

**Comment by ThaliTester** [comment]
Test (Success) 92339050 build is completed (883a779)

See https://github.com/ThaliTester/TestResults/tree/92339050883a779_DO_NOT_MERGE_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 92339050883a779(883a779) has failed

See https://github.com/ThaliTester/TestResults/tree/92339050883a779_DO_NOT_MERGE_chapko/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (883a779)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (412ea48)

**Comment by ThaliTester** [comment]
Test (Success) 92339050 build is completed (883a779)

See https://github.com/ThaliTester/TestResults/tree/92339050883a779_DO_NOT_MERGE_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 92339050883a779(883a779) has failed

See https://github.com/ThaliTester/TestResults/tree/92339050883a779_DO_NOT_MERGE_chapko/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Fail) 92339050 build is completed (412ea48)

See https://github.com/ThaliTester/TestResults/tree/92339050412ea48_DO_NOT_MERGE_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0b465fb)

**Comment by ThaliTester** [comment]
Test (Fail) 92339050 build is completed (0b465fb)

See https://github.com/ThaliTester/TestResults/tree/923390500b465fb_DO_NOT_MERGE_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4f6cab8)

**Comment by ThaliTester** [comment]
Test (Fail) 92339050 build is completed (4f6cab8)

See https://github.com/ThaliTester/TestResults/tree/923390504f6cab8_DO_NOT_MERGE_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ff6cf4a)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (65c9170)

**Comment by ThaliTester** [comment]
Test (Fail) 92339050 build is completed (ff6cf4a)

See https://github.com/ThaliTester/TestResults/tree/92339050ff6cf4a_DO_NOT_MERGE_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 92339050 build is completed (65c9170)

See https://github.com/ThaliTester/TestResults/tree/9233905065c9170_DO_NOT_MERGE_chapko/ for the logs

**Comment by yaronyg** [comment]
1. Please get the build to pass
2. Please add bug numbers as requested in comments
3. :lgtm: 

---

Reviewed 50 of 50 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testLocalSeqManagerCoordinated.js, line 74 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1487#-KWZvFQiXX8OatK9bLnH:-KWZvFQjJz-vPXKhMW8o:b-m6jdsz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/65c917025e56bdfa662a5dfb94fed565e83785aa/test/www/jxcore/bv_tests/testLocalSeqManagerCoordinated.js#L74)):*
> ```JavaScript
> test('Coordinated seq test',
>   function () {
>     // FIXME: this test is broken because it has race conditions
> ```

We need a bug number entered here so we don't forget to fix this.

---

*[test/www/jxcore/bv_tests/testThaliManagerCoordinated.js, line 147 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1487#-KWZvKYE3K-EoLBF1SS3:-KWZvKYE3K-EoLBF1SS4:br6evh6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/65c917025e56bdfa662a5dfb94fed565e83785aa/test/www/jxcore/bv_tests/testThaliManagerCoordinated.js#L147)):*
> ```JavaScript
> test('test write',
> function () {
>   // FIXME: temporarily disabled (iOS branch is not complete)
> ```

Sorry to be boring but we really need bug numbers for all of these so we don't forget.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1596 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1487#-KWZvffTa-0T2n7XTz5C:-KWZvffTa-0T2n7XTz5D:b-qrh2tz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/65c917025e56bdfa662a5dfb94fed565e83785aa/test/www/jxcore/bv_tests/testThaliMobile.js#L1596)):*
> ```JavaScript
> 
> test('can get data from all participants', function () {
>   // FIXME: temporarily disabled (iOS branch is not complete)
> ```

Yes, again... :) I'll stop now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1487#-:-KWZyeT6zu2mR72Jk1Vy:boyolls)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ee34ca8)

**Comment by ThaliTester** [comment]
Test (Fail) 92339050 build is completed (ee34ca8)

See https://github.com/ThaliTester/TestResults/tree/92339050ee34ca8_Merge_master_into_iOS_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (165300d)

**Comment by ThaliTester** [comment]
Test (Fail) 92339050 build is completed (165300d)

See https://github.com/ThaliTester/TestResults/tree/92339050165300d_Merge_master_into_iOS_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2f71cd8)

**Comment by ThaliTester** [comment]
Test (Success) 92339050 build is completed (2f71cd8)

See https://github.com/ThaliTester/TestResults/tree/923390502f71cd8_Merge_master_into_iOS_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 923390502f71cd8(2f71cd8) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/923390502f71cd8_Merge_master_into_iOS_chapko/ for the logs

**Comment by chapko** [comment]
Review status: 40 of 50 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testLocalSeqManagerCoordinated.js, line 74 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1487#-KWZvFQiXX8OatK9bLnH:-KWcKP6RiNb4zzfQG9XU:b-lbod4j) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/65c917025e56bdfa662a5dfb94fed565e83785aa/test/www/jxcore/bv_tests/testLocalSeqManagerCoordinated.js#L74)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> We need a bug number entered here so we don't forget to fix this.
</details>
I couldn't find issue related to this test and I'm not sure if it exists at all. And I'm not sure how to describe these race conditions because I haven't worked with this code yet.

---

*[test/www/jxcore/bv_tests/testThaliManagerCoordinated.js, line 147 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1487#-KWZvKYE3K-EoLBF1SS3:-KWcJGR71Atq5SX0AOLo:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/65c917025e56bdfa662a5dfb94fed565e83785aa/test/www/jxcore/bv_tests/testThaliManagerCoordinated.js#L147)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Sorry to be boring but we really need bug numbers for all of these so we don't forget.
</details>
Fixed

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1596 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1487#-KWZvffTa-0T2n7XTz5C:-KWcJI4MgkB-50UDBPEG:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/65c917025e56bdfa662a5dfb94fed565e83785aa/test/www/jxcore/bv_tests/testThaliMobile.js#L1596)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Yes, again... :) I'll stop now.
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1487)*

**Pull request merged**
