### PR TITLE
Added `platform` module for rertieving platform

### PR DESCRIPTION
**Pull request by artemjackson**
Let me refresh in your mind that before we used two approaches simultaneously:
* `jxcore.utils.OSInfo` - this requires `jxcore` to exist 
* `process.platform` - this is much better but not enough for example for testing purposes when `platform` should be overwritten.

This `platform` module implementation provides a common way for retrieving current platform. Also it has private methods for testing purpose that allow to override current `platform` value without affecting on `process.platform` value.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1118)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bb44470)

**Comment by ThaliTester** [comment]
Test 86310128bb44470(bb44470) has failed

See https://github.com/ThaliTester/TestResults/tree/86310128bb44470_Added_`platform`_module_for_rertieving_platform_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1118#-:-KSJ5edTBZjpxTIbwC1q:bnfp4nl)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1118#-:-KSLoMCZJqjHAN3jpcjg:bnfp4nl)*

**Pull request merged**
