### PR TITLE
networkType for thali manager

### LINKED ISSUE #1009: thaliManager needs to accept thaliMobile.networkTypes as an argument
The caller to thaliManager should be able to set the network type in the thaliManager constructor and it should be passed into the call to start on ThaliMobile.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1009

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1218)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (29ab45e)

**Comment by ThaliTester** [comment]
Test (Fail) 87339632 build is completed (29ab45e)

See https://github.com/ThaliTester/TestResults/tree/8733963229ab45e_networkType_for_thali_manager_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliManagerCoordinated.js, line 169 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1218#-KSsRtc0y2O-Fx_qQUi6:-KSsRtc0y2O-Fx_qQUi7:b-6z6ws0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/29ab45ee0d574d9edeac53e8d12f45833db2f1d2/test/www/jxcore/bv_tests/testThaliManagerCoordinated.js#L169)):*
> ```JavaScript
> }
> 
> var NETWORK_TYPE = global.NETWORK_TYPE || ThaliMobile.networkTypes.BOTH;
> ```

NB: This feels like a bug to me. We should be able to relay on global.NETWORK_TYPE being set. If it isn't then the tests should fail out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1218)*

**Comment by yaronyg** [comment]
Please look at the NB comment, it does worry me. Then repoint this to master (github now supports doing that in the PR) and then :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1218#-:-KSsS618b4gwFBG7fj88:b-2ytbtl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b75737d)

**Comment by andrew-aladev** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliManagerCoordinated.js, line 169 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1218#-KSsRtc0y2O-Fx_qQUi6:-KSvCi7eGGRsR9b1OPJp:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/29ab45ee0d574d9edeac53e8d12f45833db2f1d2/test/www/jxcore/bv_tests/testThaliManagerCoordinated.js#L169)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: This feels like a bug to me. We should be able to relay on global.NETWORK_TYPE being set. If it isn't then the tests should fail out
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1218)*

**Comment by ThaliTester** [comment]
Test (Success) 87339632 build is completed (b75737d)

See https://github.com/ThaliTester/TestResults/tree/87339632b75737d_networkType_for_thali_manager_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 87339632b75737d(b75737d) has failed

See https://github.com/ThaliTester/TestResults/tree/87339632b75737d_networkType_for_thali_manager_andrew-aladev/ for the fail logs

**Pull request merged**
