### PR TITLE
Added skip function to allow a test to be skipped over

### PR DESCRIPTION
**Pull request by jareksl**
Added skip function allowing to use test.skip() for tests

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1911)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d7519e7)

**Comment by ThaliTester** [comment]
Test 126503734 (d7519e7) build started.

**Comment by ThaliTester** [comment]
Test (Success) 126503734 build is completed (d7519e7)

See https://github.com/ThaliTester/TestResults/tree/126503734d7519e7_Added_skip_function_to_allow_a_test_to_be_skipped_over_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 126503734d7519e7(d7519e7) has failed

See https://github.com/ThaliTester/TestResults/tree/126503734d7519e7_Added_skip_function_to_allow_a_test_to_be_skipped_over_jareksl/ for the fail logs

**Comment by jareksl** [comment]
I know that similar feature allowing to skip a test is already available, it is powerful but requires some code to be added. I just wanted to have a possibility to simply and quickly skip test

**Comment by yaronyg** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/SimpleTape.js, line 74 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911#-Kn5LcEbbuFnu1JWi76B:-Kn5LcEcFyPSMzWJQeGr:bhh8xr9) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d7519e712b5476dd37d739636e21b4ce7bb03fa1/test/www/jxcore/lib/SimpleTape.js#L74)):*
> ```JavaScript
> };
> 
> SimpleThaliTape.prototype.skip = function (name, canBeSkipped, fun) {
> ```

Skip has a specific meaning in Tape, see https://www.npmjs.com/package/tape#testskipname-cb. It means 'skip'. There is no conditional. I would suggest we stick with the same approach so we don't surprise ourselves. In other words, I think we should remove canBeSkipped.

So if you just want a quick way to skip tests during debugging or something then you can use skip as defined in tape. If what you are looking for is a different way of implementing our existing skip function then I would suggest a different name like testWithSkip() or something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911)*

**Comment by jareksl** [comment]
*[test/www/jxcore/lib/SimpleTape.js, line 74 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911#-Kn5LcEbbuFnu1JWi76B:-Kn5Saq-gwMohUdbLtYk:b-y76p83) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d7519e712b5476dd37d739636e21b4ce7bb03fa1/test/www/jxcore/lib/SimpleTape.js#L74)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Skip has a specific meaning in Tape, see https://www.npmjs.com/package/tape#testskipname-cb. It means 'skip'. There is no conditional. I would suggest we stick with the same approach so we don't surprise ourselves. In other words, I think we should remove canBeSkipped.

So if you just want a quick way to skip tests during debugging or something then you can use skip as defined in tape. If what you are looking for is a different way of implementing our existing skip function then I would suggest a different name like testWithSkip() or something.
</blockquote></details>

The intention for `skip` is just to use it like in tape for skipping execution of test. My idea was to utilize `addTest()` with prepared parameter `canBeSkipped`. The reason for that is that this function has all the logic already implemented (e.g. it logs skipped tests). Initially I wanted to pass original parameters to `addTest` function and since`canBeSkipped` is an optional parameter I couldn't simply use `this.addTest.apply(this, arguments)`. But I agree, it could be misleading, I'll change it.    

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (15b391b)

**Comment by ThaliTester** [comment]
Test 126503734 (15b391b) build started.

**Comment by ThaliTester** [comment]
Test (Success) 126503734 build is completed (15b391b)

See https://github.com/ThaliTester/TestResults/tree/12650373415b391b_Added_skip_function_to_allow_a_test_to_be_skipped_over_jareksl/ for the logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testTests.js, line 43 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911#-Kn5km9AnTuckYnEtT-Q:-Kn5km9BsIC3v3flLcnF:bwauj3g) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15b391b748cd46f88e50ee9d279dbb8c8602e2d7/test/www/jxcore/bv_tests/testTests.js#L43)):*
> ```JavaScript
> });
> 
> test.skip('skip with skip function', function () { return true; },
> ```

We shouldn't need this test since we got rid of the function. IN fact I suppose this should be an error but it's probably not worth validating since the usual rule in JS land is to ignore extraneous arguments.

---

*[test/www/jxcore/bv_tests/testTests.js, line 49 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911#-Kn5l1XZylDsdSyyLGYO:-Kn5l1X_LV2raaTVO7E9:b-5nvoot) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15b391b748cd46f88e50ee9d279dbb8c8602e2d7/test/www/jxcore/bv_tests/testTests.js#L49)):*
> ```JavaScript
> });
> 
> test('skip function', function () { return true; },
> ```

Same issue as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911)*

**Comment by ThaliTester** [comment]
Test 12650373415b391b(15b391b) has failed

See https://github.com/ThaliTester/TestResults/tree/12650373415b391b_Added_skip_function_to_allow_a_test_to_be_skipped_over_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2651392)

**Comment by ThaliTester** [comment]
Test 126503734 (2651392) build started.

**Comment by jareksl** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testTests.js, line 43 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911#-Kn5km9AnTuckYnEtT-Q:-Kn5tEMKpggLZbRoKMeK:bjwhyvg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15b391b748cd46f88e50ee9d279dbb8c8602e2d7/test/www/jxcore/bv_tests/testTests.js#L43)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

We shouldn't need this test since we got rid of the function. IN fact I suppose this should be an error but it's probably not worth validating since the usual rule in JS land is to ignore extraneous arguments.
</blockquote></details>

Will be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911)*

**Comment by jareksl** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testTests.js, line 49 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911#-Kn5l1XZylDsdSyyLGYO:-Kn5tMEsQkXEr-XCPhHU:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/15b391b748cd46f88e50ee9d279dbb8c8602e2d7/test/www/jxcore/bv_tests/testTests.js#L49)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Same issue as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911)*

**Comment by ThaliTester** [comment]
Test (Success) 126503734 build is completed (2651392)

See https://github.com/ThaliTester/TestResults/tree/1265037342651392_Added_skip_function_to_allow_a_test_to_be_skipped_over_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 1265037342651392(2651392) has failed

See https://github.com/ThaliTester/TestResults/tree/1265037342651392_Added_skip_function_to_allow_a_test_to_be_skipped_over_jareksl/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911#-:-KnASLfyPvjDArMYimBb:bnfp4nl)*

**Comment by mlesnic** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1911#-:-KnAx5oe958HHvgWxPQf:bnfp4nl)*

**Pull request merged**
