### PR TITLE
Fixed logging to device screen

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1154)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fb80086)

**Comment by ThaliTester** [comment]
Test (Fail) 86707139 build is completed (fb80086)

See https://github.com/ThaliTester/TestResults/tree/86707139fb80086_Fixed_logging_to_device_screen_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3295e53)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (94ca0ed)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (46f5300)

**Comment by andrew-aladev** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1154)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1154#-:-KS_ud71xGDNSpTquwNi:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (045a0bd)

**Comment by ThaliTester** [comment]
Test (Success) 86707139 build is completed (3295e53)

See https://github.com/ThaliTester/TestResults/tree/867071393295e53_Fixed_logging_to_device_screen_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 867071393295e53(3295e53) has failed

See https://github.com/ThaliTester/TestResults/tree/867071393295e53_Fixed_logging_to_device_screen_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86707139 build is completed (94ca0ed)

See https://github.com/ThaliTester/TestResults/tree/8670713994ca0ed_Fixed_logging_to_device_screen_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8670713994ca0ed(94ca0ed) has failed

See https://github.com/ThaliTester/TestResults/tree/8670713994ca0ed_Fixed_logging_to_device_screen_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86707139 build is completed (46f5300)

See https://github.com/ThaliTester/TestResults/tree/8670713946f5300_Fixed_logging_to_device_screen_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 86707139 build is completed (045a0bd)

See https://github.com/ThaliTester/TestResults/tree/86707139045a0bd_Fixed_logging_to_device_screen_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8670713946f5300(46f5300) has failed

See https://github.com/ThaliTester/TestResults/tree/8670713946f5300_Fixed_logging_to_device_screen_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8d47255)

**Comment by ThaliTester** [comment]
Test (Fail) 86707139 build is completed (8d47255)

See https://github.com/ThaliTester/TestResults/tree/867071398d47255_Fixed_logging_to_device_screen_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f2ad8a0)

**Comment by ThaliTester** [comment]
Test (Fail) 86707139 build is completed (f2ad8a0)

See https://github.com/ThaliTester/TestResults/tree/86707139f2ad8a0_Fixed_logging_to_device_screen_artemjackson/ for the logs

**Pull request merged**
