### PR TITLE
#842 Removed the app.js work around

### PR DESCRIPTION
**Pull request by artemjackson**
Removed success log on `app.js` loading failure.
Added failure log on `app.js` loading failure.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/844)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (be6cebf)

**Comment by artemjackson** [comment]
Should be submitted to vNext. Closed.

**Comment by ThaliTester** [comment]
Test (Success) 80598264 build is completed (be6cebf)

See https://github.com/ThaliTester/TestResults/tree/80598264be6cebf__842_Removed_the_app_js_work_around_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 80598264be6cebf(be6cebf) has failed

See https://github.com/ThaliTester/TestResults/tree/80598264be6cebf__842_Removed_the_app_js_work_around_artemjackson/ for the fail logs

**Pull request closed without merging**
