### PR TITLE
Fixes for thaliMobile

### PR DESCRIPTION
**Pull request by vjrantal**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/662)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (23c66e9)

**Comment by ThaliTester** [comment]
Test (Fail) 63848581 build is completed (23c66e9)

See https://github.com/ThaliTester/TestResults/tree/6384858123c66e9_Fixes_for_thaliMobile_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 63848581 build is completed (23c66e9)

See https://github.com/ThaliTester/TestResults/tree/6384858123c66e9_Fixes_for_thaliMobile_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (358a1d8)

**Comment by ThaliTester** [comment]
Test (Success) 63848581 build is completed (358a1d8)

See https://github.com/ThaliTester/TestResults/tree/63848581358a1d8_Fixes_for_thaliMobile_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 63848581358a1d8(358a1d8) has failed

See https://github.com/ThaliTester/TestResults/tree/63848581358a1d8_Fixes_for_thaliMobile_vjrantal/ for the fail logs

**Comment by juhanak** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 54 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662#-KDY7hgxix-epzuYSsqN:-KDY7hgyJG-Jnaa7Sdpr:1802053729) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/358a1d809ec497507453c2cc6b9be0d456e6d4f3/test/www/jxcore/bv_tests/testThaliMobile.js#L54)):*
NB: would it make sense to replace this for loop with indexOf. Something like:
t.ok(ThaliMobile.connectionTypes.arrayOf(peer.connectionType) !== -1)

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 448 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662#-KDY93DdnzRBLAuDqjDY:-KDY93DeX7QOHHFanKX4:-1644310891) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/358a1d809ec497507453c2cc6b9be0d456e6d4f3/test/www/jxcore/bv_tests/testThaliMobile.js#L448)):*
Should you deduct one from participants? (tester can't listen itself?)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b00dd7c)

**Comment by vjrantal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 54 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662#-KDY7hgxix-epzuYSsqN:-KDYFN1Q_-lbiVL2s8Eo:-67080790) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/358a1d809ec497507453c2cc6b9be0d456e6d4f3/test/www/jxcore/bv_tests/testThaliMobile.js#L54)):*
The check is a bit more complicated and as far as I can tell it can't be turned into a one-liner like proposed.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 448 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662#-KDY93DdnzRBLAuDqjDY:-KDYFTryhC7Y4cJkvQhR:102533515) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/358a1d809ec497507453c2cc6b9be0d456e6d4f3/test/www/jxcore/bv_tests/testThaliMobile.js#L448)):*
Good point! Fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662)*

**Comment by juhanak** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 54 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662#-KDY7hgxix-epzuYSsqN:-KDYHycmKFqjFF0CyrVK:-1738616549) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/358a1d809ec497507453c2cc6b9be0d456e6d4f3/test/www/jxcore/bv_tests/testThaliMobile.js#L54)):*
I agree. It can't be turned into a one-liner. Sorry for useless proposal.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662)*

**Comment by ThaliTester** [comment]
Test (Success) 63848581 build is completed (b00dd7c)

See https://github.com/ThaliTester/TestResults/tree/63848581b00dd7c_Fixes_for_thaliMobile_vjrantal/ for the logs

**Comment by juhanak** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/662)*

**Comment by ThaliTester** [comment]
Test 63848581b00dd7c(b00dd7c) has failed

See https://github.com/ThaliTester/TestResults/tree/63848581b00dd7c_Fixes_for_thaliMobile_vjrantal/ for the fail logs

**Pull request merged**
