### PR TITLE
fixed failing Get same port when trying to connect multiple times on iOS

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1367)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8b90a24)

**Comment by ThaliTester** [comment]
Test (Fail) 89972587 build is completed (8b90a24)

See https://github.com/ThaliTester/TestResults/tree/899725878b90a24_fixed_failing_`Get_same_port_when_trying_to_connect_multiple_times`_on_iOS_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (58bc3fa)

**Comment by ThaliTester** [comment]
Test (Fail) 89972587 build is completed (58bc3fa)

See https://github.com/ThaliTester/TestResults/tree/8997258758bc3fa_fixed_failing_Get_same_port_when_trying_to_connect_multiple_times_on_iOS_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (64e1ee2)

**Comment by ThaliTester** [comment]
Test (Fail) 89972587 build is completed (64e1ee2)

See https://github.com/ThaliTester/TestResults/tree/8997258764e1ee2_fixed_failing_Get_same_port_when_trying_to_connect_multiple_times_on_iOS_baydet/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1367#-:-KUYS7JbLYoXgnDzcFRy:bnfp4nl)*

**Comment by dersim-davaod** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1367#-:-KUbM4fB8egjBAVNo63R:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f0e556f)

**Pull request merged**
