### PR TITLE
Removed polyfills, added ponyfill

### LINKED ISSUE #1123: Please remove prototyping on system objects, it isn't safe in ARM
This is for the polyfills. We'll need to switch to using dedicated functions instead of polyfills. Yes, this sucks.

The background is that we have found that JXcore on ARM gets into a weird state if you modify the prototype of an array object. We are still investigating but for now we need to make forward progress so we will have to avoid doing this ourselves.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1123

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1126)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8103677)

**Comment by ThaliTester** [comment]
Test (Fail) 86367767 build is completed (8103677)

See https://github.com/ThaliTester/TestResults/tree/863677678103677_Removed_polyfills__added_ponyfill_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (11d379c)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (34dc27a)

**Comment by ThaliTester** [comment]
Test (Success) 86367767 build is completed (11d379c)

See https://github.com/ThaliTester/TestResults/tree/8636776711d379c_Removed_polyfills__added_ponyfill_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 86367767 build is completed (34dc27a)

See https://github.com/ThaliTester/TestResults/tree/8636776734dc27a_Removed_polyfills__added_ponyfill_andrew-aladev/ for the logs

**Comment by yaronyg** [comment]
It looks like CI is in a bad place. I have seen this before. When it gets overloaded it gets into a weird state and needs to be reset.

**Comment by yaronyg** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/TestServer/package.json, line 14 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1126#-KSKLr5oDeluU-l2Z8r-:-KSKLr5oDeluU-l2Z8r0:bij4gae) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11d379ce2a244d9cbe9a138fc5a182ef72e1a705/test/TestServer/package.json#L14)):*
> ```JSON
>     "node-uuid": "1.4.7",
> 
>     "array-from": "2.1.1"
> ```

Please put this in alphabetic order

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 186 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1126#-KSKMDi5594dKR33bxUE:-KSKMDi6ofPg1udgldHQ:biwmmhk) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11d379ce2a244d9cbe9a138fc5a182ef72e1a705/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L186)):*
> ```JavaScript
>   var stackTrace = '';
>   try {
>     throw new Error("something");
> ```

Please tell me you aren't trying to debug in CI. That is insane. You need to debug locally. But in any case I assume this code is supposed to go.

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 280 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1126#-KSKM9JohuVy_y8nb7qB:-KSKM9JohuVy_y8nb7qC:bcpedqi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11d379ce2a244d9cbe9a138fc5a182ef72e1a705/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L280)):*
> ```JavaScript
>               Utils.serializePouchError(err)
>             );
>             console.error(
> ```

Why do we need console? Is logger busted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1126)*

**Comment by ThaliTester** [comment]
Test 8636776711d379c(11d379c) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8636776711d379c_Removed_polyfills__added_ponyfill_andrew-aladev/ for the logs

**Comment by artemjackson** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/TestServer/Socket.js, line 90 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1126#-KSL1TFExUvHa1vJLnpI:-KSL1TFExUvHa1vJLnpJ:b-29sz36) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11d379ce2a244d9cbe9a138fc5a182ef72e1a705/test/TestServer/Socket.js#L90)):*
> ```JavaScript
> Socket.prototype._apply = function (method) {
>   var self = this;
>   var args = arrayFrom(arguments).slice(1);
> ```

Did `Array.prototype.slice.call(arguments, 1)` become old-fashioned and we really need an extra library for that?

---

*[thali/NextGeneration/replication/thaliReplicationPeerAction.js, line 184 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1126#-KSL2gjVGVfVi6FNbYU-:-KSL2gjVGVfVi6FNbYU0:bh0mogj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/11d379ce2a244d9cbe9a138fc5a182ef72e1a705/thali/NextGeneration/replication/thaliReplicationPeerAction.js#L184)):*
> ```JavaScript
>   var self = this;
> 
>   var stackTrace = '';
> ```

What for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1126)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (23342cb)

**Comment by ThaliTester** [comment]
Test (Fail) 86367767 build is completed (23342cb)

See https://github.com/ThaliTester/TestResults/tree/8636776723342cb_Removed_polyfills__added_ponyfill_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (8d24e91)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (2134d31)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (1df66b8)

**Comment by ThaliTester** [comment]
Test (Success) 86367767 build is completed (8d24e91)

See https://github.com/ThaliTester/TestResults/tree/863677678d24e91_Removed_polyfills__added_ponyfill_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 863677678d24e91(8d24e91) has failed

See https://github.com/ThaliTester/TestResults/tree/863677678d24e91_Removed_polyfills__added_ponyfill_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86367767 build is completed (2134d31)

See https://github.com/ThaliTester/TestResults/tree/863677672134d31_Removed_polyfills__added_ponyfill_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 863677672134d31(2134d31) has failed

See https://github.com/ThaliTester/TestResults/tree/863677672134d31_Removed_polyfills__added_ponyfill_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86367767 build is completed (1df66b8)

See https://github.com/ThaliTester/TestResults/tree/863677671df66b8_Removed_polyfills__added_ponyfill_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 863677671df66b8(1df66b8) has failed

See https://github.com/ThaliTester/TestResults/tree/863677671df66b8_Removed_polyfills__added_ponyfill_andrew-aladev/ for the fail logs

**Comment by artemjackson** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 1 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1126#-:-KSMArRyEH8GY1m49eY4:bnfp4nl)*

**Pull request merged**
