### PR TITLE
Testing for corrupt data

### PR DESCRIPTION
**Pull request by yaronyg**
README - Lint

testThaliManagerCoordinated - Switching back to default pool manager

testThaliMobile - Enabling tests to run in CI since all devices are now
on public Wifi, this should be interesting. Also added test to detect
data corruption in a non-trivial scenario. Also fixed a test which wasn't
dealing well with zombies.

testUtils - Added utils to handle PUT requests

runCoordinatedTests - Linting

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1427)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5576f84)

**Comment by ThaliTester** [comment]
Test (Success) 90916415 build is completed (5576f84)

See https://github.com/ThaliTester/TestResults/tree/909164155576f84_Testing_for_corrupt_data_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 909164155576f84(5576f84) has failed

See https://github.com/ThaliTester/TestResults/tree/909164155576f84_Testing_for_corrupt_data_yaronyg/ for the fail logs

**Comment by chapko** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 670 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1427#-KV-prH1ahngdR6i2OHe:-KV-prH2gV7CpR7IfGgj:b-91xy4d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5576f846939982bcc713917be5167552ea5c6fc4/test/www/jxcore/bv_tests/testThaliMobile.js#L670)):*
> ```JavaScript
>     var requestBody = [];
>     req.on('data', function (chunk) {
>       requestBody.push(chunk);
> ```

NB: Why do you buffer entire message before sending it back?

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 693 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1427#-KV-zSfq5BX1u7-DeJnf:-KV-zSfq5BX1u7-DeJng:b-4qbw5v) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5576f846939982bcc713917be5167552ea5c6fc4/test/www/jxcore/bv_tests/testThaliMobile.js#L693)):*
> ```JavaScript
> 
> test('test for data corruption', function () {
>   return global.NETWORK_TYPE === ThaliMobile.networkTypes.WIFI;
> ```

This test should be also android only (it uses TCPServersManager API)

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 756 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1427#-KV-zqcIyT-5xwacemis:-KV-zqcIyT-5xwacemit:b-aeisi4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5576f846939982bcc713917be5167552ea5c6fc4/test/www/jxcore/bv_tests/testThaliMobile.js#L756)):*
> ```JavaScript
>           }, 1000);
>         });
>       });
> ```

There should be `done` call in this `catch` handler. Otherwise this test will never end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1427)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 670 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1427#-KV-prH1ahngdR6i2OHe:-KV1cpNGv9S6TjKr4Xk9:blgfxgb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5576f846939982bcc713917be5167552ea5c6fc4/test/www/jxcore/bv_tests/testThaliMobile.js#L670)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> NB: Why do you buffer entire message before sending it back?
</details>
I wanted to avoid using HTTP chunking. So I wanted to start with a really simple test where content-length and everything can be calculated.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 693 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1427#-KV-zSfq5BX1u7-DeJnf:-KV1cxtc9A0wPLzVjjMY:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5576f846939982bcc713917be5167552ea5c6fc4/test/www/jxcore/bv_tests/testThaliMobile.js#L693)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> This test should be also android only (it uses TCPServersManager API)
</details>
Fixed

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 756 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1427#-KV-zqcIyT-5xwacemis:-KV1dPZnVF_Z58Tl6IDt:b-52a2aj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5576f846939982bcc713917be5167552ea5c6fc4/test/www/jxcore/bv_tests/testThaliMobile.js#L756)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> There should be `done` call in this `catch` handler. Otherwise this test will never end.
</details>
The omission of the done call is intentional. I wanted to make the test robust to occasional Bluetooth failures so if a GET or PUT fails because the Bluetooth connection fails I don't want the test to end. So the idea is that either the test will pass OR the global test timeout will fire and the test will end that way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1427)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1d8f644)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f4fe0a6)

**Comment by ThaliTester** [comment]
Test (Success) 90916415 build is completed (1d8f644)

See https://github.com/ThaliTester/TestResults/tree/909164151d8f644_Testing_for_corrupt_data_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 909164151d8f644(1d8f644) has failed

See https://github.com/ThaliTester/TestResults/tree/909164151d8f644_Testing_for_corrupt_data_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 90916415 build is completed (f4fe0a6)

See https://github.com/ThaliTester/TestResults/tree/90916415f4fe0a6_Testing_for_corrupt_data_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 90916415f4fe0a6(f4fe0a6) has failed

See https://github.com/ThaliTester/TestResults/tree/90916415f4fe0a6_Testing_for_corrupt_data_yaronyg/ for the fail logs

**Pull request merged**
