### PR TITLE
fix: Cannot find module 'fs-extra-promise’ during install

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1335)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b5a16dd)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4fd14d5)

**Comment by ThaliTester** [comment]
Test (Success) 89614235 build is completed (b5a16dd)

See https://github.com/ThaliTester/TestResults/tree/89614235b5a16dd_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 89614235 build is completed (4fd14d5)

See https://github.com/ThaliTester/TestResults/tree/896142354fd14d5_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 89614235b5a16dd(b5a16dd) has failed

See https://github.com/ThaliTester/TestResults/tree/89614235b5a16dd_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
@yaronyg please review.

I'm almost sure that you won't like the [install.js, line 368](https://github.com/thaliproject/Thali_CordovaPlugin/blob/4fd14d5250af7bb55f74018bcb35ab096bfaa8bd/thali/install/install.js#L368), but this's line as a brother to the line `npm install --no-optional --production`.

**Comment by ThaliTester** [comment]
Test 896142354fd14d5(4fd14d5) has failed

See https://github.com/ThaliTester/TestResults/tree/896142354fd14d5_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the fail logs

**Comment by yaronyg** [comment]
I don't believe this checkin is necessary. Please see the comments.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/install/install.js, line 90 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335#-KUJrkKH0zKLT05-Txhg:-KUJrkKIxbsamiMa6OQ1:bgw1u6d) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fd14d5250af7bb55f74018bcb35ab096bfaa8bd/thali/install/install.js#L90)):*
> ```JavaScript
>           return conf.thaliInstall;
>         }
>         return Promise.reject('Configuration error!');
> ```

Shouldn't this return new Error('Configuration error!');?

---

*[thali/install/install.js, line 309 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335#-KUJrsqbtLR_occND_Gk:-KUJrsqc30OoDSGAJwzo:bnho80e) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fd14d5250af7bb55f74018bcb35ab096bfaa8bd/thali/install/install.js#L309)):*
> ```JavaScript
>   var thaliProjectName, thaliDepotName, thaliBranchName, btconnectorlib2;
> 
>   getReleaseConfig(thaliDontCheckIn)
> ```

Why are we passing thaliDontCheckIn to getReleaseConfig when it doesn't actually take an argument?

---

*[thali/install/install.js, line 354 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335#-KUJtI6tZfeT47brkSXy:-KUJtI6u0_9qr_7hqreL:bsrt6sd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4fd14d5250af7bb55f74018bcb35ab096bfaa8bd/thali/install/install.js#L354)):*
> ```JavaScript
>         return uninstallPluginsIfNecessary(weAddedPluginsFile, appRootDirectory)
>           .then(function () {
>             // this section isn't valid, but it has to be at the moment
> ```

This section isn't necessary. What I believe caused the problem is that Rockwell didn't follow the instruction in the readme to 'mkdir -p FooBar/thaliDontCheckIn/localdev'. This instruction tells the install script to just copy the contents of the cloned depot instead of downloading the zip file. If that command had been executed then later on when we call 'jx npm install ../../../Thali_CordovaPlugin/thali/' this would trigger the postInstall script which runs installCordovaPlugin.js which then runs npm on the install directory thus rending this new code unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335#-:-KUJtjCavcYoFWaOUk7d:b-lm9rhs)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (33949f2)

**Comment by ThaliTester** [comment]
Test (Success) 89614235 build is completed (33949f2)

See https://github.com/ThaliTester/TestResults/tree/8961423533949f2_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 8961423533949f2(33949f2) has failed

See https://github.com/ThaliTester/TestResults/tree/8961423533949f2_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/install/install.js, line 90 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335#-KUJrkKH0zKLT05-Txhg:-KUS9f6t5ZNPGgl7DS5Y:b1jm86i) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/33949f2e6318eafdeb1b76cb5fcf88f57924be65/thali/install/install.js#L90)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Shouldn't this return new Error('Configuration error!');?
</details>
The next `.then` block will receive error as a next value in case of returning `Error('Configuration error!')`, so returning Error isn't valid.

---

*[thali/install/install.js, line 309 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335#-KUJrsqbtLR_occND_Gk:-KUS9LKTRgiMCKV3vjl2:b-22g7en) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/33949f2e6318eafdeb1b76cb5fcf88f57924be65/thali/install/install.js#L309)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Why are we passing thaliDontCheckIn to getReleaseConfig when it doesn't actually take an argument?
</details>
Looks very reasonable. It looks that it comes from some old logic when this function took arguments.

I'll fix it.

---

*[thali/install/install.js, line 354 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335#-KUJtI6tZfeT47brkSXy:-KUS9yQVX0GPaZfs6C2L:b-qjo5qx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/33949f2e6318eafdeb1b76cb5fcf88f57924be65/thali/install/install.js#L354)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> This section isn't necessary. What I believe caused the problem is that Rockwell didn't follow the instruction in the readme to 'mkdir -p FooBar/thaliDontCheckIn/localdev'. This instruction tells the install script to just copy the contents of the cloned depot instead of downloading the zip file. If that command had been executed then later on when we call 'jx npm install ../../../Thali_CordovaPlugin/thali/' this would trigger the postInstall script which runs installCordovaPlugin.js which then runs npm on the install directory thus rending this new code unnecessary.
</details>
I've analysed readme and install.js. As result we have the following scenario.

1. `jx npm install ../../../Thali_CordovaPlugin/thali/ --save --no-optional --autoremove "*.gz"` is executed.
2. `thali` and `thali/install` packages are installed for the base directory `../../../Thali_CordovaPlugin/thali/`
3. `install.js` script downloads Thali from GitHub
4. `install.js` runs `cordova add` for the folder downloaded from GitHub

As result since Cordova hooks depend on installer packages and since we've downloaded clean copy from GitHub packages cannot be found.

So we need somehow install packages for Cordova hooks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (98e234c)

**Comment by larryonoff** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[thali/install/install.js, line 354 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335#-KUJtI6tZfeT47brkSXy:-KUSKtbjOFw2xX-G8dTj:b-2f38rz) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/98e234c8049748e97c3243f28c2454f4eb9e0db9/thali/install/install.js#L354)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I've analysed readme and install.js. As result we have the following scenario.
> 
> 1. `jx npm install ../../../Thali_CordovaPlugin/thali/ --save --no-optional --autoremove "*.gz"` is executed.
> 2. `thali` and `thali/install` packages are installed for the base directory `../../../Thali_CordovaPlugin/thali/`
> 3. `install.js` script downloads Thali from GitHub
> 4. `install.js` runs `cordova add` for the folder downloaded from GitHub
> 
> As result since Cordova hooks depend on installer packages and since we've downloaded clean copy from GitHub packages cannot be found.
> 
> So we need somehow install packages for Cordova hooks.
</details>
In addition

- "Why it works for build.sh"
- Because script created `thaliDontCheckIn/localdev` directory what means that local thali clone will be used.

When the local folder already has all packages installed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1335)*

**Comment by ThaliTester** [comment]
Test (Success) 89614235 build is completed (98e234c)

See https://github.com/ThaliTester/TestResults/tree/8961423598e234c_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 8961423598e234c(98e234c) has failed

See https://github.com/ThaliTester/TestResults/tree/8961423598e234c_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8bc729a)

**Comment by larryonoff** [comment]
@yaronyg I've analysed the problem deeper. As result I see that `README` is correct and `prepare.sh` is correct. The problem occurs since how Cordova runs its hooks. It copies it's hooks into installed plugin directory and then run it's scripts, the hooks folder is for example `ThaliTestApp/plugins/org.thaliproject.p2p/thali/install/cordova-hooks`, so this folder obviously not having required packages, since it's already installed Cordova plugin folder and not our thali installer folder.

**Comment by ThaliTester** [comment]
Test (Fail) 89614235 build is completed (8bc729a)

See https://github.com/ThaliTester/TestResults/tree/896142358bc729a_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (77ead0c)

**Comment by ThaliTester** [comment]
Test (Fail) 89614235 build is completed (77ead0c)

See https://github.com/ThaliTester/TestResults/tree/8961423577ead0c_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8645e5e)

**Comment by ThaliTester** [comment]
Test (Success) 89614235 build is completed (8645e5e)

See https://github.com/ThaliTester/TestResults/tree/896142358645e5e_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 896142358645e5e(8645e5e) has failed

See https://github.com/ThaliTester/TestResults/tree/896142358645e5e_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fd4d6ce)

**Comment by ThaliTester** [comment]
Test (Success) 89614235 build is completed (fd4d6ce)

See https://github.com/ThaliTester/TestResults/tree/89614235fd4d6ce_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 89614235fd4d6ce(fd4d6ce) has failed

See https://github.com/ThaliTester/TestResults/tree/89614235fd4d6ce_fix__Cannot_find_module__fs-extra-promise’_during_install_larryonoff/ for the fail logs

**Comment by larryonoff** [comment]
this should be fixed. the fix is just to run setUpDesktop.sh before thali install.

**Pull request closed without merging**
