### PR TITLE
Story 001 yarong 240

### PR DESCRIPTION
**Pull request by yaronyg**
@tompaana I figured I would submit this as a PR to at least put some kind of end to this branch. :) Obviously the file name for BluetoothConnectionLimits.js is wrong since that wouldn't kick off a perf test but that was intentional since we don't want it to be run until we have actual code there.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/362)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d291820)

**Comment by ThaliTester** [comment]
Test (Success) 52445159 build is completed (d291820)

See https://github.com/ThaliTester/TestResults/tree/52445159d291820_Story_001_yarong_240_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 52445159d291820(d291820) has failed

See https://github.com/ThaliTester/TestResults/tree/52445159d291820_Story_001_yarong_240_yaronyg/ for the fail logs

**Comment by tompaana** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/362)*

**Pull request merged**
