### PR TITLE
Updating publish instructions

### PR DESCRIPTION
**Pull request by yaronyg**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/203)

### CODE REVIEW

**Comment by yaronyg** [comment]
@tobybrad Please review and approve if you find the new instructions clear.

**Comment by tobybrad** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/203)

**Comment by tobybrad** [comment]
Fine.. left merge to you.

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Pull request merged**
