### PR TITLE
Fixed gen 0 problem

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1677)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (25d2e42)

**Comment by ThaliTester** [comment]
Test 99247393 (25d2e42) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 99247393 build is completed (25d2e42)

See https://github.com/ThaliTester/TestResults/tree/9924739325d2e42_Fixed_gen_0_problem_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a8ecbf4)

**Comment by ThaliTester** [comment]
Test 99247393 (a8ecbf4) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99247393 build is completed (a8ecbf4)

See https://github.com/ThaliTester/TestResults/tree/99247393a8ecbf4_Fixed_gen_0_problem_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 99247393a8ecbf4(a8ecbf4) has failed

See https://github.com/ThaliTester/TestResults/tree/99247393a8ecbf4_Fixed_gen_0_problem_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
Test 99247393 (4db55e8) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99247393 build is completed (4db55e8)

See https://github.com/ThaliTester/TestResults/tree/992473934db55e8_Fixed_gen_0_problem_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 992473934db55e8(4db55e8) has failed

See https://github.com/ThaliTester/TestResults/tree/992473934db55e8_Fixed_gen_0_problem_evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1677#-:-K_AMXjPXsXIe_u0JUvN:bnfp4nl)*

**Pull request merged**
