### PR TITLE
#378 thaliPeerPoolInterface

### PR DESCRIPTION
**Pull request by yaronyg**
@tobybrad I'm giving this to you because @vjrantal has enough PR in his inbox. Please review and let me know if it makes sense.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/487)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f6ec045)

**Comment by ThaliTester** [comment]
Test (Success) 57132760 build is completed (f6ec045)

See https://github.com/ThaliTester/TestResults/tree/57132760f6ec045__378_thaliPeerPoolInterface_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 57132760f6ec045(f6ec045) has failed

See https://github.com/ThaliTester/TestResults/tree/57132760f6ec045__378_thaliPeerPoolInterface_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
Closed in favor of #317

**Pull request closed without merging**
