### PR TITLE
remove unnecessary iOS cordova hook logic

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1371)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d961875)

**Comment by ThaliTester** [comment]
Test (Success) 90009723 build is completed (d961875)

See https://github.com/ThaliTester/TestResults/tree/90009723d961875_remove_unnecessary_iOS_cordova_hook_logic_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (439aaa5)

**Comment by ThaliTester** [comment]
Test 90009723d961875(d961875) has failed

See https://github.com/ThaliTester/TestResults/tree/90009723d961875_remove_unnecessary_iOS_cordova_hook_logic_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 90009723 build is completed (439aaa5)

See https://github.com/ThaliTester/TestResults/tree/90009723439aaa5_remove_unnecessary_iOS_cordova_hook_logic_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 90009723439aaa5(439aaa5) has failed

See https://github.com/ThaliTester/TestResults/tree/90009723439aaa5_remove_unnecessary_iOS_cordova_hook_logic_larryonoff/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1371)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1371#-:-KUTSNGjuF9MIWcr5UNy:bnfp4nl)*

**Pull request merged**
