### PR TITLE
Updated node ssdp

### LINKED ISSUE #1431: node-ssdp fails when wifi is turned on and off

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1431.

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1451)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (57d7cd0)

**Comment by ThaliTester** [comment]
Test (Success) 91371661 build is completed (57d7cd0)

See https://github.com/ThaliTester/TestResults/tree/9137166157d7cd0_Updated_node_ssdp_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 9137166157d7cd0(57d7cd0) has failed

See https://github.com/ThaliTester/TestResults/tree/9137166157d7cd0_Updated_node_ssdp_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1451#-:-KVBDbnZG3fuZiMfgiAJ:bnfp4nl)*

**Pull request merged**
