### PR TITLE
BT and WiFi always turned on before running tests. CI check #953 with #769

### PR DESCRIPTION
**Pull request by mlesnic**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1053)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (329c724)

**Comment by ThaliTester** [comment]
Test (Success) 85519194 build is completed (329c724)

See https://github.com/ThaliTester/TestResults/tree/85519194329c724_BT_and_WiFi_always_turned_on_before_running_tests__CI_check__953_with__769_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 85519194329c724(329c724) has failed

See https://github.com/ThaliTester/TestResults/tree/85519194329c724_BT_and_WiFi_always_turned_on_before_running_tests__CI_check__953_with__769_mlesnic/ for the fail logs

**Comment by mlesnic** [comment]
It looks like this problem was not related to old networkStatusUpdate function.

**Pull request closed without merging**
