### PR TITLE
Tweak build scripts for other OSes

### PR DESCRIPTION
**Pull request by chapko**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1575)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0aa0610)

**Comment by ThaliTester** [comment]
Test 95321062 (0aa0610) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 95321062 build is completed (0aa0610)

See https://github.com/ThaliTester/TestResults/tree/953210620aa0610_Fix_build_scrips_chapko/ for the logs

**Comment by larryonoff** [comment]
we should wait until master is merge into iOS branch. I don't want make any changes in iOS branch before merge.

**Comment by larryonoff** [comment]
I see that the base branch is iOS. So we need to get it pass on CI and the merge.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (378f266)

**Comment by ThaliTester** [comment]
Test 95321062 (378f266) build started.

**Comment by ThaliTester** [comment]
Test 95321062 (378f266) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95321062 build is completed (378f266)

See https://github.com/ThaliTester/TestResults/tree/95321062378f266_Fix_build_scripts_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 95321062378f266(378f266) has failed

See https://github.com/ThaliTester/TestResults/tree/95321062378f266_Fix_build_scripts_chapko/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (0aa0610)

**Comment by ThaliTester** [comment]
Test 95321062 (0aa0610) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95321062 build is completed (0aa0610)

See https://github.com/ThaliTester/TestResults/tree/953210620aa0610_Fix_build_scripts_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 953210620aa0610(0aa0610) has failed

See https://github.com/ThaliTester/TestResults/tree/953210620aa0610_Fix_build_scripts_chapko/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fff4ed0)

**Comment by ThaliTester** [comment]
Test 95321062 (fff4ed0) build started.

**Comment by ThaliTester** [comment]
Test (Success) 95321062 build is completed (fff4ed0)

See https://github.com/ThaliTester/TestResults/tree/95321062fff4ed0_Tweak_build_scripts_for_other_OSes_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 95321062fff4ed0(fff4ed0) has failed

See https://github.com/ThaliTester/TestResults/tree/95321062fff4ed0_Tweak_build_scripts_for_other_OSes_chapko/ for the fail logs

**Pull request merged**
