### PR TITLE
Update node test for #1747 PR #1751

### PR DESCRIPTION
**Pull request by opetkevich**
Android couldn't properly serialize null values before. But since it has
been already fixed I can update tests with proper null checks

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1853)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d2f007e)

**Comment by ThaliTester** [comment]
Test 114545238 (d2f007e) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 114545238 build is completed (d2f007e)

See https://github.com/ThaliTester/TestResults/tree/114545238d2f007e_Update_node_test_for__1747_PR__1751_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5e6e6e8)

**Comment by ThaliTester** [comment]
Test 114545238 (5e6e6e8) build started.

**Comment by ThaliTester** [comment]
Test (Success) 114545238 build is completed (5e6e6e8)

See https://github.com/ThaliTester/TestResults/tree/1145452385e6e6e8_Update_node_test_for__1747_PR__1751_opetkevich/ for the logs

**Comment by ThaliTester** [comment]
Test 1145452385e6e6e8(5e6e6e8) has failed

See https://github.com/ThaliTester/TestResults/tree/1145452385e6e6e8_Update_node_test_for__1747_PR__1751_opetkevich/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1853#-:-Kh2uZsrzrTWJWz3IyCN:bnfp4nl)*

**Pull request merged**
