### PR TITLE
Sanity check CI

### PR DESCRIPTION
**Pull request by tobybrad**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/304)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2c15f33)

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (2c15f33)

See https://github.com/ThaliTester/TestResults/tree/502892962c15f33_Sanity_check_CI_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ac49a25)

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (ac49a25)

See https://github.com/ThaliTester/TestResults/tree/50289296ac49a25_Sanity_check_CI_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (634deb4)

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (634deb4)

See https://github.com/ThaliTester/TestResults/tree/50289296634deb4_Sanity_check_CI_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f537d20)

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (f537d20)

See https://github.com/ThaliTester/TestResults/tree/50289296f537d20_Sanity_check_CI_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (72097d4)

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (72097d4)

See https://github.com/ThaliTester/TestResults/tree/5028929672097d4_Sanity_check_CI_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (58b6ce5)

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (58b6ce5)

See https://github.com/ThaliTester/TestResults/tree/5028929658b6ce5_Sanity_check_CI_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f099041)

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (f099041)

See https://github.com/ThaliTester/TestResults/tree/50289296f099041_Sanity_check_CI_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (f099041)

See https://github.com/ThaliTester/TestResults/tree/50289296f099041_Sanity_check_CI_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (beb5fc1)

**Comment by ThaliTester** [comment]
Test (Fail) 50289296 build is completed (beb5fc1)

See https://github.com/ThaliTester/TestResults/tree/50289296beb5fc1_Sanity_check_CI_tobybrad/ for the logs

**Comment by tobybrad** [comment]
Tidying up.. will do CI sanity check on a dedicated branch.

**Pull request closed without merging**
