### PR TITLE
CI TEST - DO NOT MERGE!

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/254)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (b386474)

**Comment by ThaliTester** [comment]
Test (Success) 49008559 build is completed (b386474)

See https://github.com/ThaliTester/TestResults/tree/49008559b386474_CI_TEST_-_DO_NOT_MERGE!_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (39737dd)

**Comment by ThaliTester** [comment]
Test (Success) 49008559 build is completed (39737dd)

See https://github.com/ThaliTester/TestResults/tree/4900855939737dd_CI_TEST_-_DO_NOT_MERGE!_vjrantal/ for the logs

**Comment by vjrantal** [comment]
Tests done so will close and delete this branch.

**Comment by ThaliTester** [comment]
Test 49008559b386474(b386474) has failed

See https://github.com/ThaliTester/TestResults/tree/49008559b386474_CI_TEST_-_DO_NOT_MERGE!_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 4900855939737dd(39737dd) has failed

See https://github.com/ThaliTester/TestResults/tree/4900855939737dd_CI_TEST_-_DO_NOT_MERGE!_vjrantal/ for the fail logs

**Pull request closed without merging**
