### PR TITLE
#419 Added PouchDB implementation with database size checkpoints

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/865)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (298ded4)

**Comment by ThaliTester** [comment]
Test (Success) 81316179 build is completed (298ded4)

See https://github.com/ThaliTester/TestResults/tree/81316179298ded4__419_Added_PouchDB_implementation_with_database_size_checpoints_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 81316179298ded4(298ded4) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/81316179298ded4__419_Added_PouchDB_implementation_with_database_size_checpoints_artemjackson/ for the logs

**Comment by artemjackson** [comment]
Should be started from and submitted to vNext_417_1. Closed.

**Pull request closed without merging**
