### PR TITLE
Returned setImmediate workaround

### PR DESCRIPTION
**Pull request by artemjackson**
This branch is needed for debugging CI

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1010)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d5e9757)

**Comment by ThaliTester** [comment]
Test (Success) 84618637 build is completed (d5e9757)

See https://github.com/ThaliTester/TestResults/tree/84618637d5e9757_Added_logging_for_radios_state_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 84618637d5e9757(d5e9757) has failed

See https://github.com/ThaliTester/TestResults/tree/84618637d5e9757_Added_logging_for_radios_state_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (840569c)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ad45253)

**Comment by ThaliTester** [comment]
Test (Success) 84618637 build is completed (840569c)

See https://github.com/ThaliTester/TestResults/tree/84618637840569c_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 84618637 build is completed (ad45253)

See https://github.com/ThaliTester/TestResults/tree/84618637ad45253_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (21be5f3)

**Comment by ThaliTester** [comment]
Test 84618637840569c(840569c) has failed

See https://github.com/ThaliTester/TestResults/tree/84618637840569c_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test 8461863721be5f3(21be5f3) has failed

See https://github.com/ThaliTester/TestResults/tree/8461863721be5f3_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8dcb506)

**Comment by ThaliTester** [comment]
Test (Success) 84618637 build is completed (8dcb506)

See https://github.com/ThaliTester/TestResults/tree/846186378dcb506_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 846186378dcb506(8dcb506) has failed

See https://github.com/ThaliTester/TestResults/tree/846186378dcb506_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
@artemjackson What magic do you have that this builds successfully in CI but super branch doesn't?!?! I have to assume that the build failure for super branch was a CI issue. :(

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (449017d)

**Comment by ThaliTester** [comment]
Test (Fail) 84618637 build is completed (449017d)

See https://github.com/ThaliTester/TestResults/tree/84618637449017d_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d986838)

**Comment by ThaliTester** [comment]
Test (Fail) 84618637 build is completed (d986838)

See https://github.com/ThaliTester/TestResults/tree/84618637d986838_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (daa9683)

**Comment by ThaliTester** [comment]
Test (Success) 84618637 build is completed (daa9683)

See https://github.com/ThaliTester/TestResults/tree/84618637daa9683_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 84618637daa9683(daa9683) has failed

See https://github.com/ThaliTester/TestResults/tree/84618637daa9683_DO_NOT_MERGE_Added_logging_for_radios_state_artemjackson/ for the fail logs

**Comment by artemjackson** [comment]
@yaronyg #928 tried to sync with `vNext` and got merge conflicts, so build failed

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9f428f5)

**Comment by artemjackson** [comment]
@yaronyg The workaround with `setImmediate` was removed in #928 and that PR was successfully tested on local devices (2 iOS and 3 Android). But CI devices don't work without this workaround, so I have to return it back just for CI devices.

**Comment by artemjackson** [comment]
@yaronyg Also there was found a race condition on Android devices described in the issue #1022.

**Comment by ThaliTester** [comment]
Test (Success) 84618637 build is completed (9f428f5)

See https://github.com/ThaliTester/TestResults/tree/846186379f428f5_Returned_setImmediate_workaround_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 846186379f428f5(9f428f5) has failed

See https://github.com/ThaliTester/TestResults/tree/846186379f428f5_Returned_setImmediate_workaround_artemjackson/ for the fail logs

**Comment by yaronyg** [comment]
@artemjackson If you remember I had a PR where I merged super branch with vNext but it brought up enough changes that you and @andrew-aladev asked me not to submit it now. Why don't we focus on getting super branch passing and then I can take another crack at merging with vNext?

**Comment by yaronyg** [comment]
@artemjackson BTW, does it worry you at all that the behavior we are seeing for our system is different in CI than on our desktop? That doesn't bode well. Is this because we are using different versions of JXcore?

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dc3f7e6)

**Comment by ThaliTester** [comment]
Test (Success) 84618637 build is completed (dc3f7e6)

See https://github.com/ThaliTester/TestResults/tree/84618637dc3f7e6_Returned_setImmediate_workaround_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 84618637dc3f7e6(dc3f7e6) has failed

See https://github.com/ThaliTester/TestResults/tree/84618637dc3f7e6_Returned_setImmediate_workaround_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4ed975d)

**Comment by ThaliTester** [comment]
Test (Success) 84618637 build is completed (4ed975d)

See https://github.com/ThaliTester/TestResults/tree/846186374ed975d_Returned_setImmediate_workaround_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 846186374ed975d(4ed975d) has failed

See https://github.com/ThaliTester/TestResults/tree/846186374ed975d_Returned_setImmediate_workaround_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (8976bee)

**Comment by ThaliTester** [comment]
Test (Success) 84618637 build is completed (8976bee)

See https://github.com/ThaliTester/TestResults/tree/846186378976bee_Returned_setImmediate_workaround_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 846186378976bee(8976bee) has failed

See https://github.com/ThaliTester/TestResults/tree/846186378976bee_Returned_setImmediate_workaround_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (2298193)

**Comment by ThaliTester** [comment]
Test (Fail) 84618637 build is completed (2298193)

See https://github.com/ThaliTester/TestResults/tree/846186372298193_Returned_setImmediate_workaround_artemjackson/ for the logs

**Comment by artemjackson** [comment]
Closed in favour of #1031 and #1033

**Pull request closed without merging**
