### PR TITLE
Battery test app

### LINKED ISSUE #1292: Create battery test app
Please create a Cordova application following the instructions in the top level readme in master. Create an app.js that includes thali in www/jxcore.

Please put in a variable that controls if we will use Wifi, Native or both in the settings below.

Please put in a switch that can be set to a value of:

Nothing - In this case the app should do nothing and the app.js should exit.

Listen_Only - If we are in Wifi mode then this should call the start method and then the startListeningForAdvertisements method in thaliWifiInfrastructure. If we are in native mode then this should call the same two methods but on thaliMobileNativeWrapper. And if both then, well, both.

Advertise_Only - Same as above but now we will use startUpdateAdvertisingAndListening rather than startListeningForAdvertisements.

Both - Yes, this is the combination of listen and advertise.

Don't worry about turning anything off.
Don't worry about displaying anything in the HTML.
The app's config arguments should be in the app.js (e.g. setting the network type and the switch value) and when the app starts up it should do what it's supposed to based on those settings.

Please check this app into a project under ThaliProject so we can use it easily in the future.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1292

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1326)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d4fcca1)

**Comment by ThaliTester** [comment]
Test (Success) 89388695 build is completed (d4fcca1)

See https://github.com/ThaliTester/TestResults/tree/89388695d4fcca1_Battery_test_app_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 89388695d4fcca1(d4fcca1) has failed

See https://github.com/ThaliTester/TestResults/tree/89388695d4fcca1_Battery_test_app_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d14a551)

**Comment by ThaliTester** [comment]
Test (Success) 89388695 build is completed (d14a551)

See https://github.com/ThaliTester/TestResults/tree/89388695d14a551_Battery_test_app_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 89388695d14a551(d14a551) has failed

See https://github.com/ThaliTester/TestResults/tree/89388695d14a551_Battery_test_app_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1326#-:-KU4b3blGiqPYUFns-uk:bnfp4nl)*

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1326#-:-KUGv3uVYsqm1FuJlkF8:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (3df03fb)

**Comment by ThaliTester** [comment]
Test (Success) 89388695 build is completed (3df03fb)

See https://github.com/ThaliTester/TestResults/tree/893886953df03fb_Battery_test_app_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 893886953df03fb(3df03fb) has failed

See https://github.com/ThaliTester/TestResults/tree/893886953df03fb_Battery_test_app_andrew-aladev/ for the fail logs

**Pull request merged**
