### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by yaronyg**
I got rid of our use of 'jx npm install' and 'jx npm link' and replaced with 'jx install' and 'jx link'. The problem
in JXcore that caused this issue should be fixed now but I thought to change this to JXcore's preferred
syntax to stay on the safe side.

I added a line in setuUpTests.sh @vjrantal suggested to remove a potential issue with folks who do desktop development and then do mobile development.

Everything else is just cleanup to pass the lint filter.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/505)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (19324d6)

**Comment by ThaliTester** [comment]
Test (Fail) 57924002 build is completed (19324d6)

See https://github.com/ThaliTester/TestResults/tree/5792400219324d6_Some_cleanup_yaronyg/ for the logs

**Comment by vjrantal** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/setUpDesktop.sh, line 12 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/505#-K9VvCBUgW9Ap1SCCKjk:-K9VvCBUgW9Ap1SCCKjl:1479773636) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19324d6073d997a8b87cf2aaf0943a937cdd5021/thali/install/setUpDesktop.sh#L12)):*
Even though `jx install` is a shortcut to `jx npm install`, `jx link` is not a valid command at all and fails.

Overall, my preference would be to keep the `npm` word in the commands, because people are generally familiar with `npm` and could more easily figure out what the commands do.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/505)*

**Comment by yaronyg** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/install/setUpDesktop.sh, line 12 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/505#-K9VvCBUgW9Ap1SCCKjk:-K9XrpyGhQkZ31i2CTKd:-1494429028) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/19324d6073d997a8b87cf2aaf0943a937cdd5021/thali/install/setUpDesktop.sh#L12)):*
On the issue of jx link, D'oh! I'll fix that.

On the issue of jx npm install I 100% agree but given the bug we just saw in JXcore it's pretty clear that they test 'jx install' but not 'jx npm install' as well as we would like. So it's a tradeoff and right now i'd like to reduce the probability of another multi-day disaster like we just had.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/505)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ce356e3)

**Comment by ThaliTester** [comment]
Test (Fail) 57924002 build is completed (ce356e3)

See https://github.com/ThaliTester/TestResults/tree/57924002ce356e3_Some_cleanup_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c37c307)

**Comment by ThaliTester** [comment]
Test (Fail) 57924002 build is completed (c37c307)

See https://github.com/ThaliTester/TestResults/tree/57924002c37c307_Some_cleanup_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (14fad2e)

**Comment by ThaliTester** [comment]
Test (Fail) 57924002 build is completed (14fad2e)

See https://github.com/ThaliTester/TestResults/tree/5792400214fad2e_Some_cleanup_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d5e0b14)

**Comment by ThaliTester** [comment]
Test (Success) 57924002 build is completed (d5e0b14)

See https://github.com/ThaliTester/TestResults/tree/57924002d5e0b14_Some_cleanup_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 57924002d5e0b14(d5e0b14) has failed

See https://github.com/ThaliTester/TestResults/tree/57924002d5e0b14_Some_cleanup_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a578a80)

**Comment by ThaliTester** [comment]
Test (Success) 57924002 build is completed (a578a80)

See https://github.com/ThaliTester/TestResults/tree/57924002a578a80_Some_cleanup_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 57924002a578a80(a578a80) has failed

See https://github.com/ThaliTester/TestResults/tree/57924002a578a80_Some_cleanup_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 3 of 12 files at r2, 4 of 18 files at r3, 5 of 6 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/505)*

**Pull request merged**
