### PR TITLE
DO_NOT_MERGE testing vNext_dersim_1134 branch

### PR DESCRIPTION
**Pull request by dersim-davaod**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1135)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5eac790)

**Comment by ThaliTester** [comment]
Test (Success) 86472885 build is completed (5eac790)

See https://github.com/ThaliTester/TestResults/tree/864728855eac790_DO_NOT_MERGE_testing_vNext_dersim_1134_branch_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 864728855eac790(5eac790) has failed

See https://github.com/ThaliTester/TestResults/tree/864728855eac790_DO_NOT_MERGE_testing_vNext_dersim_1134_branch_dersim-davaod/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (0b65ede)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (3590d1f)

**Comment by ThaliTester** [comment]
Test (Success) 86472885 build is completed (3590d1f)

See https://github.com/ThaliTester/TestResults/tree/864728853590d1f_DO_NOT_MERGE_testing_vNext_dersim_1134_branch_dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 864728853590d1f(3590d1f) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/864728853590d1f_DO_NOT_MERGE_testing_vNext_dersim_1134_branch_dersim-davaod/ for the logs

**Comment by yaronyg** [comment]
Shouldn't this be to vNext and not master?

---

Review status: 0 of 293 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1135#-:-KShr7eY5Im3yamS_FRa:betu20z)*

**Pull request closed without merging**
