### PR TITLE
Fix iOS native tests

### PR DESCRIPTION
**Pull request by mlesnic**
Note: This solution is based on Enrico's changes to ThaliCore which are currently on his branch. So for review, we use ThaliCore from his branch. After review, before merge, we should revert to ThaliCore master branch.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1917)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fdd070d)

**Comment by ThaliTester** [comment]
Test 127198710 (fdd070d) build started.

**Comment by ThaliTester** [comment]
Test (Success) 127198710 build is completed (fdd070d)

See https://github.com/ThaliTester/TestResults/tree/127198710fdd070d_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (d8e38b6)

**Comment by ThaliTester** [comment]
Test 127198710 (d8e38b6) build started.

**Comment by ThaliTester** [comment]
Test 127198710fdd070d(fdd070d) has failed

See https://github.com/ThaliTester/TestResults/tree/127198710fdd070d_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 127198710 build is completed (d8e38b6)

See https://github.com/ThaliTester/TestResults/tree/127198710d8e38b6_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 127198710d8e38b6(d8e38b6) has failed

See https://github.com/ThaliTester/TestResults/tree/127198710d8e38b6_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 40 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnL2h82-dXzkS2pcSCf:-KnL2h83oosRwf5Hru1G:b-3hutdf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d8e38b60ccd40d9dcc1d30488165c4799f57db9e/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L40)):*
> ```JavaScript
>         'must be stopped');
>       if (!platform.isAndroid) {
>         peerIdsToBeClosed.forEach(function (peerIdToBeClosed) {
> ```

This same pattern is showing up (for obvious reasons) in a bunch of places. That's usually a good sign that this should be turned into a function in one place and called.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 448 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnL5Wm7eDru8tRMV41o:-KnL5Wm7eDru8tRMV41p:b89zlqc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d8e38b60ccd40d9dcc1d30488165c4799f57db9e/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L448)):*
> ```JavaScript
>   var availablePeers = [];
> 
>   function removeFromAvailablePeers(peer) {
> ```

We shouldn't have the same function twice. Instead we should factor this out and just pass in peer and availablePeers as arguments.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 459 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnL6RL-m9e8B8eyIUQH:-KnL6RL-m9e8B8eyIUQI:blxzxbt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d8e38b60ccd40d9dcc1d30488165c4799f57db9e/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L459)):*
> ```JavaScript
> 
>   function tryToConnect() {
>     availablePeers.forEach(function (record) {
> ```

It's really confusing to use the same name availablePeers in both this and the previous function when they in fact have totally didn't values. For someone trying to read the code this is surprising.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by mlesnic** [comment]
Review status: 8 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 40 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnL2h82-dXzkS2pcSCf:-KnZRR2zRw1-DjW0UnWv:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d8e38b60ccd40d9dcc1d30488165c4799f57db9e/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L40)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

This same pattern is showing up (for obvious reasons) in a bunch of places. That's usually a good sign that this should be turned into a function in one place and called.
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 448 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnL5Wm7eDru8tRMV41o:-KnZRP9rAMehONfiipku:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d8e38b60ccd40d9dcc1d30488165c4799f57db9e/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L448)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

We shouldn't have the same function twice. Instead we should factor this out and just pass in peer and availablePeers as arguments.
</blockquote></details>

Done.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 459 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnL6RL-m9e8B8eyIUQH:-KnZROllqiz2gAr1YTYx:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d8e38b60ccd40d9dcc1d30488165c4799f57db9e/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L459)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

It's really confusing to use the same name availablePeers in both this and the previous function when they in fact have totally didn't values. For someone trying to read the code this is surprising.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by jareksl** [comment]
Reviewed 8 of 13 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 450 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnnDm25Cqa1xRvFPXe1:-KnnDm25Cqa1xRvFPXe2:bx9yz8m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/abbee73aefcb266b1c8f7404fe32b570b4e89bf3/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L450)):*
> ```JavaScript
>  * @param {function} testFunction
>  */
> function executeZombieProofTestCoordinated (t, server, testFunction) {
> ```

executeZombieProofTest and executeZombieProofTestCoordinated are very similar. I think that most of the code could be shared.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by enricogior** [comment]
*[lib/ios/Cartfile, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KoC1J__oZZc7BmMBKc_:-KoC1J__oZZc7BmMBKca:b4lb4mi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/dfabc2d4c5b6bf1a6b4a6e41badbac74097fb40f/lib/ios/Cartfile#L1)):*
> ```
> github "thaliproject/thali-ios" "master-enrico-error-handling"
> ```

Are you still using "master-enrico-error-handling"? 
"master-enrico-error-handling-tmp" have more fixes even if it's work in progress, do you want me to update "master-enrico-error-handling" with latest stable fixes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by mlesnic** [comment]
Review status: 12 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[lib/ios/Cartfile, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KoC1J__oZZc7BmMBKc_:-KoC85nAP4aL_MI2mXf1:bl66vtt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/dfabc2d4c5b6bf1a6b4a6e41badbac74097fb40f/lib/ios/Cartfile#L1)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

Are you still using "master-enrico-error-handling"? 
"master-enrico-error-handling-tmp" have more fixes even if it's work in progress, do you want me to update "master-enrico-error-handling" with latest stable fixes?

</blockquote></details>

By the time this PR was created, there was no tmp branch. Although, it would be nice to use only one branch. If it is possible, please update `master-enrico-error-handling` and use it as main development branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by enricogior** [comment]
*[lib/ios/Cartfile, line 1 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KoC1J__oZZc7BmMBKc_:-KoC9pq-IQFA6vJDHrhg:bibulxb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/dfabc2d4c5b6bf1a6b4a6e41badbac74097fb40f/lib/ios/Cartfile#L1)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary><blockquote>

By the time this PR was created, there was no tmp branch. Although, it would be nice to use only one branch. If it is possible, please update `master-enrico-error-handling` and use it as main development branch.
</blockquote></details>

OK, I've updated `master-enrico-error-handling`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by enricogior** [comment]
*[test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js, line 124 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KoCp8W1CE1RcMYeUziX:-KoCp8W1CE1RcMYeUziY:b-16lbht) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/dfabc2d4c5b6bf1a6b4a6e41badbac74097fb40f/test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js#L124)):*
> ```JavaScript
>         'returned');
>         t.equal(originalSyncValue, syncValue, 'SyncValue matches');
>         t.equal(error, 'Connection could not be established',
> ```

Having updated the `master-enrico-error-handling` branch, the expected error needs to be changed to `Peer is unavailable`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by enricogior** [comment]
*[test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js, line 124 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KoCp8W1CE1RcMYeUziX:-KoCu14cB7Fxj-4w3MpA:b-lzzyvc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/dfabc2d4c5b6bf1a6b4a6e41badbac74097fb40f/test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js#L124)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

Having updated the `master-enrico-error-handling` branch, the expected error needs to be changed to `Peer is unavailable`
</blockquote></details>

We need to do the same in `testThaliMobile.js` line 1803.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by mlesnic** [comment]
Review status: 12 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js, line 124 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KoCp8W1CE1RcMYeUziX:-KoGA9WIHTNyw86ceiVj:b-nuxkom) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/dfabc2d4c5b6bf1a6b4a6e41badbac74097fb40f/test/www/jxcore/bv_tests/testThaliMobileNativeiOS.js#L124)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

We need to do the same in `testThaliMobile.js` line 1803.
</blockquote></details>

I think we should wait for Yaron's comment about it, I don't know if it fits the Thali API. There is also separate issue for that, #1924.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (49fde15)

**Comment by ThaliTester** [comment]
Test 127198710 (49fde15) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 127198710 build is completed (49fde15)

See https://github.com/ThaliTester/TestResults/tree/12719871049fde15_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (49fde15)

**Comment by ThaliTester** [comment]
Test 127198710 (49fde15) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 127198710 build is completed (49fde15)

See https://github.com/ThaliTester/TestResults/tree/12719871049fde15_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (49fde15)

**Comment by ThaliTester** [comment]
Test 127198710 (49fde15) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 127198710 build is completed (49fde15)

See https://github.com/ThaliTester/TestResults/tree/12719871049fde15_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (49fde15)

**Comment by ThaliTester** [comment]
Test 127198710 (49fde15) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 127198710 build is completed (49fde15)

See https://github.com/ThaliTester/TestResults/tree/12719871049fde15_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (49fde15)

**Comment by ThaliTester** [comment]
Test 127198710 (49fde15) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 127198710 build is completed (49fde15)

See https://github.com/ThaliTester/TestResults/tree/12719871049fde15_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a8db48d)

**Comment by ThaliTester** [comment]
Test 127198710 (a8db48d) build started.

**Comment by ThaliTester** [comment]
Test 127198710a8db48d(a8db48d) has failed

See https://github.com/ThaliTester/TestResults/tree/127198710a8db48d_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c0cbe24)

**Comment by ThaliTester** [comment]
Test 127198710 (c0cbe24) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 127198710 build is completed (c0cbe24)

See https://github.com/ThaliTester/TestResults/tree/127198710c0cbe24_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c0cbe24)

**Comment by ThaliTester** [comment]
Test 127198710 (c0cbe24) build started.

**Comment by ThaliTester** [comment]
Test (Success) 127198710 build is completed (c0cbe24)

See https://github.com/ThaliTester/TestResults/tree/127198710c0cbe24_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 127198710c0cbe24(c0cbe24) has failed

See https://github.com/ThaliTester/TestResults/tree/127198710c0cbe24_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a2b6fb8)

**Comment by ThaliTester** [comment]
Test 127198710 (a2b6fb8) build started.

**Comment by ThaliTester** [comment]
Test (Success) 127198710 build is completed (a2b6fb8)

See https://github.com/ThaliTester/TestResults/tree/127198710a2b6fb8_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 127198710a2b6fb8(a2b6fb8) has failed

See https://github.com/ThaliTester/TestResults/tree/127198710a2b6fb8_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (31384d0)

**Comment by ThaliTester** [comment]
Test 127198710 (31384d0) build started.

**Comment by ThaliTester** [comment]
Test (Success) 127198710 build is completed (31384d0)

See https://github.com/ThaliTester/TestResults/tree/12719871031384d0_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 12719871031384d0(31384d0) has failed

See https://github.com/ThaliTester/TestResults/tree/12719871031384d0_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (31384d0)

**Comment by ThaliTester** [comment]
Test 127198710 (31384d0) build started.

**Comment by ThaliTester** [comment]
Test (Success) 127198710 build is completed (31384d0)

See https://github.com/ThaliTester/TestResults/tree/12719871031384d0_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 12719871031384d0(31384d0) has failed

See https://github.com/ThaliTester/TestResults/tree/12719871031384d0_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 6 files at r6, 3 of 5 files at r7, 1 of 1 files at r8, 5 of 5 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/ios/Cartfile, line 1 at r9](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KowoF4BCjA-H-_DadXg:-KowoF4CAPXeK0-VANTJ:b-3zkarp) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31384d0b279123fc0d1aa8e4180ea30784ff58c7/lib/ios/Cartfile#L1)):*
> ```
> github "thaliproject/thali-ios" "master-enrico-error-handling-tmp"
> ```

Do we really want to check in a -tmp?

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 101 at r9](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KowonAaWT45ZLmbvJll:-KowonAb8iAgjnkkL-vl:b-mxz8w) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31384d0b279123fc0d1aa8e4180ea30784ff58c7/test/www/jxcore/bv_tests/testThaliNotification.js#L101)):*
> ```JavaScript
>     // Clears timeout
>     if (notificationClient && notificationServer) {
>       notificationClient.stop();
> ```

Why are we calling stop twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by mlesnic** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lib/ios/Cartfile, line 1 at r9](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KowoF4BCjA-H-_DadXg:-Kp-2j8lkkCmVLcnXdk5:b-wptq3j) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31384d0b279123fc0d1aa8e4180ea30784ff58c7/lib/ios/Cartfile#L1)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Do we really want to check in a -tmp?
</blockquote></details>

This was done for test purposes, of course we will marge with master branch, however we will do it after ThaliCore master branch will be updated, without those changes it won't work properly.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 101 at r9](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KowonAaWT45ZLmbvJll:-Kp-2dvOygUO438fuo0h:b-n18yfo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31384d0b279123fc0d1aa8e4180ea30784ff58c7/test/www/jxcore/bv_tests/testThaliNotification.js#L101)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Why are we calling stop twice?
</blockquote></details>

We stop separately notificationClient and notificationServer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliNotification.js, line 101 at r9](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KowonAaWT45ZLmbvJll:-Kp0lZ00k_eb_IwUSdBu:bp0flaq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/31384d0b279123fc0d1aa8e4180ea30784ff58c7/test/www/jxcore/bv_tests/testThaliNotification.js#L101)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary><blockquote>

We stop separately notificationClient and notificationServer.
</blockquote></details>

Oh wow. My eyes failed me! Sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9197780)

**Comment by ThaliTester** [comment]
Test 127198710 (9197780) build started.

**Comment by ThaliTester** [comment]
Test (Success) 127198710 build is completed (9197780)

See https://github.com/ThaliTester/TestResults/tree/1271987109197780_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 1271987109197780(9197780) has failed

See https://github.com/ThaliTester/TestResults/tree/1271987109197780_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a8e6b92)

**Comment by ThaliTester** [comment]
Test 127198710 (a8e6b92) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 127198710 build is completed (a8e6b92)

See https://github.com/ThaliTester/TestResults/tree/127198710a8e6b92_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by enricogior** [comment]
*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 450 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnnDm25Cqa1xRvFPXe1:-KpYnnT7U3jhMz2PcVU9:b-m2p1iw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/abbee73aefcb266b1c8f7404fe32b570b4e89bf3/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L450)):*
> executeZombieProofTestCoordinated 
That has been fixed, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by enricogior** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-:-KpYoAiBfJYWxwQtbgV_:bnfp4nl)*

**Comment by enricogior** [comment]
*[lib/ios/Cartfile, line 1 at r12](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KpYoG-edv7bozuxP4as:-KpYoG-edv7bozuxP4at:b-touw27) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/be2f3e7bcd913c6debde14d22e5d11900010fcc6/lib/ios/Cartfile#L1)):*
> ```
> github "thaliproject/thali-ios" "master-enrico-error-handling-tmp"
> ```

"master-enrico-error-handling" is now up-to-date and the branch used to do the PR in the thali-ios repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by enricogior** [comment]
Reviewed 8 of 13 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, 1 of 6 files at r6, 1 of 5 files at r9, 5 of 5 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by jareksl** [comment]
Reviewed 1 of 6 files at r6, 2 of 5 files at r7, 1 of 1 files at r8, 1 of 5 files at r9, 5 of 5 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1781 at r12](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KpZnr_yE19s67_rWY77:-KpZnr_yE19s67_rWY78:b-6eg2b6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/be2f3e7bcd913c6debde14d22e5d11900010fcc6/test/www/jxcore/bv_tests/testThaliMobile.js#L1781)):*
> ```JavaScript
> });
> 
> test('We properly fire peer unavailable and then available when ' +
> ```

NB: We could also just use skip() here (as it is already merged to the master branch)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by jareksl** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-:-Kp_ONqDSBCNNUzOeqaB:bg7igkv)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-:-Kp_t8eSkuQwk2drx8wv:bnfp4nl)*

**Comment by mlesnic** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lib/ios/Cartfile, line 1 at r12](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KpYoG-edv7bozuxP4as:-KpmqdWRJNHRU9M0NgOG:bxl4jg2) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/be2f3e7bcd913c6debde14d22e5d11900010fcc6/lib/ios/Cartfile#L1)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

"master-enrico-error-handling" is now up-to-date and the branch used to do the PR in the thali-ios repo.
</blockquote></details>

Right before merging this PR, I will change it to 'master'.

---

*[test/www/jxcore/lib/thaliMobileNativeTestUtils.js, line 450 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917#-KnnDm25Cqa1xRvFPXe1:-KpmqV23t0amWCwClguE:btqqu5l) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/abbee73aefcb266b1c8f7404fe32b570b4e89bf3/test/www/jxcore/lib/thaliMobileNativeTestUtils.js#L450)):*
<details><summary><i>Previously, enricogior (Enrico Giordani) wrote…</i></summary><blockquote>

> executeZombieProofTestCoordinated 
That has been fixed, right?

</blockquote></details>

Correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1917)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (34799d6)

**Comment by ThaliTester** [comment]
Test 127198710 (34799d6) build started.

**Comment by ThaliTester** [comment]
Test (Success) 127198710 build is completed (34799d6)

See https://github.com/ThaliTester/TestResults/tree/12719871034799d6_Fix_iOS_native_tests_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 12719871034799d6(34799d6) has failed

See https://github.com/ThaliTester/TestResults/tree/12719871034799d6_Fix_iOS_native_tests_mlesnic/ for the fail logs

**Pull request merged**
