### PR TITLE
fix CI build fails #1463

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1484)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d00ab7e)

**Comment by ThaliTester** [comment]
Test (Success) 92300911 build is completed (d00ab7e)

See https://github.com/ThaliTester/TestResults/tree/92300911d00ab7e_fix_CI_build_fails__1463_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 92300911d00ab7e(d00ab7e) has failed

See https://github.com/ThaliTester/TestResults/tree/92300911d00ab7e_fix_CI_build_fails__1463_larryonoff/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b4fa317)

**Comment by larryonoff** [comment]
@yaronyg I'm merging this into iOS branch to fix it ASAP. But please review this fix.

**Comment by ThaliTester** [comment]
Test (Fail) 92300911 build is completed (b4fa317)

See https://github.com/ThaliTester/TestResults/tree/92300911b4fa317_fix_CI_build_fails__1463_larryonoff/ for the logs

**Pull request merged**
