### PR TITLE
Merge back timeout reverse connections

### PR DESCRIPTION
**Pull request by tobybrad**
Passing locally. Let's see what CI makes of this.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/629)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a869d4a)

**Comment by ThaliTester** [comment]
Test (Fail) 63012666 build is completed (a869d4a)

See https://github.com/ThaliTester/TestResults/tree/63012666a869d4a_Merge_back_timeout_reverse_connections_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c2ddc84)

**Comment by ThaliTester** [comment]
Test 63012666c2ddc84(c2ddc84) has failed

See https://github.com/ThaliTester/TestResults/tree/63012666c2ddc84_Merge_back_timeout_reverse_connections_tobybrad/ for the fail logs

**Comment by vjrantal** [comment]
@tobybrad: Two observations about the CI results:

1. We hit the newly implemented timeout 5 times in the tests that only have 2 connect calls (one to test connect and one to test data send):

```
$ grep "Timed out awaiting reverse connection" *
iOS_IpadAir2-1.md:,2016-03-16 06:32:45.271 ThaliTest[1548:2463587] jxcore: connect: fail: Timed out awaiting reverse connection
iOS_IpadAir2-1.md:,2016-03-16 06:33:10.817 ThaliTest[1548:2463587] jxcore: connect: fail: Timed out awaiting reverse connection
iOS_IpadAir2-1.md:,2016-03-16 06:33:23.830 ThaliTest[1548:2463587] jxcore: connect: fail: Timed out awaiting reverse connection
iOS_IpadAir2-1.md:,2016-03-16 06:33:36.841 ThaliTest[1548:2463587] jxcore: connect: fail: Timed out awaiting reverse connection
iOS_IpadAir2-1.md:,2016-03-16 06:33:50.523 ThaliTest[1548:2463587] jxcore: connect: fail: Timed out awaiting reverse connection
```
First question is if so many timeouts considered normal and second is if waiting for the timeout would contribute quite a lot of delay in a real-life scenario we often end up waiting for it just to move data around?

2. The tests fails like this:

```
{ clientPort: 0, serverPort: 62638, listeningPort: 0 }

,ok 155 Must have listeningPort

,ok 156 listeningPort must be a number

ok 157 Connection must have clientPort

ok 158 clientPort must be a number

ok 159 Connection must have serverPort

,ok 160 serverPort must be a number

,not ok 161 (unnamed assert)

,  ---

,    operator: ok

,    expected: true

,    actual:   false
,
,  ...
```

To me, the very first line doesn't look right, because if there is no listeningPort, the other two should be non-zero, but that is not the case.

**Comment by vjrantal** [comment]
@tobybrad: Actually, just realized that 1. above is probably because the test code was changed to do connect retries every 3 seconds. For that, I have the following concern. According to the specification, the connect call should fail to ` * | Alreading connect(ing/ed) | There already is a connection or a request to createone is already in process |` in case there is already a connection request ongoing to a particular peer. Shouldn't that error be thrown if the iOS code is waiting for the reverse connection timeout (i.e., hasn't returned from the first connect) and we try to do another one after 3 seconds in the test code?

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (388ed44)

**Comment by ThaliTester** [comment]
Test (Fail) 63012666 build is completed (388ed44)

See https://github.com/ThaliTester/TestResults/tree/63012666388ed44_Merge_back_timeout_reverse_connections_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bb4658c)

**Comment by ThaliTester** [comment]
Test (Fail) 63012666 build is completed (bb4658c)

See https://github.com/ThaliTester/TestResults/tree/63012666bb4658c_Merge_back_timeout_reverse_connections_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d6bb2e8)

**Comment by ThaliTester** [comment]
Test (Success) 63012666 build is completed (d6bb2e8)

See https://github.com/ThaliTester/TestResults/tree/63012666d6bb2e8_Merge_back_timeout_reverse_connections_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 63012666d6bb2e8(d6bb2e8) has failed

See https://github.com/ThaliTester/TestResults/tree/63012666d6bb2e8_Merge_back_timeout_reverse_connections_tobybrad/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 6 of 7 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/629)*

**Pull request merged**
