### PR TITLE
skip `Connect port dies if not connected to in time` for iOS

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1359)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (450ef7b)

**Comment by ThaliTester** [comment]
Test (Success) 89812065 build is completed (450ef7b)

See https://github.com/ThaliTester/TestResults/tree/89812065450ef7b_skip_`Connect_port_dies_if_not_connected_to_in_time`_for_iOS_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 89812065450ef7b(450ef7b) has failed

See https://github.com/ThaliTester/TestResults/tree/89812065450ef7b_skip_`Connect_port_dies_if_not_connected_to_in_time`_for_iOS_baydet/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1359)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1359#-:-KUTSRi52-IEq5zY1NGd:bnfp4nl)*

**Pull request merged**
