### PR TITLE
rename JavaScript method ExecuteNativeTests into executeNativeTests

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/924)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1ca4444)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (84424f3)

**Comment by ThaliTester** [comment]
Test (Success) 82518996 build is completed (1ca4444)

See https://github.com/ThaliTester/TestResults/tree/825189961ca4444_rename_JavaScript_method_ExecuteNativeTests_into_executeNativeTests_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 825189961ca4444(1ca4444) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/825189961ca4444_rename_JavaScript_method_ExecuteNativeTests_into_executeNativeTests_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 82518996 build is completed (84424f3)

See https://github.com/ThaliTester/TestResults/tree/8251899684424f3_rename_JavaScript_method_ExecuteNativeTests_into_executeNativeTests_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 8251899684424f3(84424f3) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8251899684424f3_rename_JavaScript_method_ExecuteNativeTests_into_executeNativeTests_larryonoff/ for the logs

**Comment by larryonoff** [comment]
@yaronyg please review this PR

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/924#-:-KPzACecvWXM3OkxOBnL:bnfp4nl)*

**Pull request merged**
