### PR TITLE
Update jxcore to 0.3.1.9

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1775)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c47ddeb)

**Comment by ThaliTester** [comment]
Test 104320879 (c47ddeb) build started.

**Comment by ThaliTester** [comment]
Test (Success) 104320879 build is completed (c47ddeb)

See https://github.com/ThaliTester/TestResults/tree/104320879c47ddeb_Update_jxcore_to_0_3_1_9_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 104320879c47ddeb(c47ddeb) has failed

See https://github.com/ThaliTester/TestResults/tree/104320879c47ddeb_Update_jxcore_to_0_3_1_9_evabishchevich/ for the fail logs

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1775#-:-Kc2TLOT6ltPx5Qlmt39:bnfp4nl)*

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1775#-:-Kc2TPn-PfnvXBEpCUWZ:bg7igkv)*

**Pull request merged**
