### PR TITLE
Skip 'onPeerDiscovered calls jxcore' and 'onPeerLost calls jxcore' on iOS

### PR DESCRIPTION
**Pull request by squid48**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1684)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5bf9b5a)

**Comment by ThaliTester** [comment]
Test 99373674 (5bf9b5a) build started.

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1684#-:-KZvXbzIR8OeJzcUi3hW:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 993736745bf9b5a(5bf9b5a) has failed

See https://github.com/ThaliTester/TestResults/tree/993736745bf9b5a_Skip__onPeerDiscovered_calls_jxcore__and__onPeerLost_calls_jxcore__on_iOS_squid48/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (1c2a2c8)

**Comment by ThaliTester** [comment]
Test 99373674 (1c2a2c8) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99373674 build is completed (1c2a2c8)

See https://github.com/ThaliTester/TestResults/tree/993736741c2a2c8_Skip__onPeerDiscovered_calls_jxcore__and__onPeerLost_calls_jxcore__on_iOS_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 993736741c2a2c8(1c2a2c8) has failed

See https://github.com/ThaliTester/TestResults/tree/993736741c2a2c8_Skip__onPeerDiscovered_calls_jxcore__and__onPeerLost_calls_jxcore__on_iOS_squid48/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dc17873)

**Comment by ThaliTester** [comment]
Test 99373674 (dc17873) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99373674 build is completed (dc17873)

See https://github.com/ThaliTester/TestResults/tree/99373674dc17873_Skip__onPeerDiscovered_calls_jxcore__and__onPeerLost_calls_jxcore__on_iOS_squid48/ for the logs

**Comment by ThaliTester** [comment]
Test 99373674dc17873(dc17873) has failed

See https://github.com/ThaliTester/TestResults/tree/99373674dc17873_Skip__onPeerDiscovered_calls_jxcore__and__onPeerLost_calls_jxcore__on_iOS_squid48/ for the fail logs

**Pull request merged**
