### PR TITLE
Switch to new Bluetooth library and fixes to test frameworks

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/338)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9ffd84d)

**Comment by ThaliTester** [comment]
Test (Fail) 50982847 build is completed (9ffd84d)

See https://github.com/ThaliTester/TestResults/tree/509828479ffd84d_Switch_to_new_Bluetooth_library_and_fixes_to_test_frameworks_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6dba52d)

**Comment by ThaliTester** [comment]
Test (Success) 50982847 build is completed (6dba52d)

See https://github.com/ThaliTester/TestResults/tree/509828476dba52d_Switch_to_new_Bluetooth_library_and_fixes_to_test_frameworks_vjrantal/ for the logs

**Comment by tobybrad** [comment]
Reviewed 8 of 11 files at r1, 4 of 8 files at r2, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[test/TestServer/index.js, line 62 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/338#-K3MJBe2wr6f5ZNziTUS:-K3MJBe2wr6f5ZNziTUT:183544612) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/6dba52deb84bd4f0b1047263c3efac8eac9b62d3/test/TestServer/index.js#L62)):_
hah. that's funny... I literally have an editor open in another window right now with this exact code in it.. and I was thinking WTF ?  I realise this is what you were talking about earlier this evening.. 

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/338)_

**Comment by tobybrad** [comment]
Good work !!

**Pull request merged**
