### PR TITLE
Peer unavailable event when port changes

### PR DESCRIPTION
**Pull request by vjrantal**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/676)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8400100)

**Comment by ThaliTester** [comment]
Test (Success) 64034619 build is completed (8400100)

See https://github.com/ThaliTester/TestResults/tree/640346198400100_Peer_unavailable_event_when_port_changes_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 640346198400100(8400100) has failed

See https://github.com/ThaliTester/TestResults/tree/640346198400100_Peer_unavailable_event_when_port_changes_vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliMobile.js, line 397 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/676#-KDdAO_h4OqwRbnzS6RG:-KDdAO_h4OqwRbnzS6RH:1428188626) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8400100c9b325e09289a7edf0ffed146551bf393/thali/NextGeneration/thaliMobile.js#L397)):*
NB: So believe it or not this wasn't an omission. I just figured the up stream code had to deal with the port change and recognize its implications but this is a fine addition. It will simplify things.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/676)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliMobile.js, line 397 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/676#-KDdAO_h4OqwRbnzS6RG:-KDdH8zA4rkCuOD2dNiV:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8400100c9b325e09289a7edf0ffed146551bf393/thali/NextGeneration/thaliMobile.js#L397)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/676)*

**Pull request merged**
