### PR TITLE
Added logging to TestRunner

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1136)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0901bf9)

**Comment by ThaliTester** [comment]
Test (Success) 86482582 build is completed (0901bf9)

See https://github.com/ThaliTester/TestResults/tree/864825820901bf9_Added_logging_to_TestRunner_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 864825820901bf9(0901bf9) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/864825820901bf9_Added_logging_to_TestRunner_baydet/ for the logs

**Comment by larryonoff** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift, line 15 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-KSLYQbxMGxKILIzW8gA:-KSLYQbxMGxKILIzW8gB:bywdlj8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0901bf999d16b0f01795682c1124c95a06395d2c/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift#L15)):*
> ```Swift
> // MARK: - Current version of TestRunner doesn't display in logs assertion failures.
> // This category `overrides` recordFailureWithDescription and adds logging for failures.
> extension XCTestCase {
> ```

NB:

I don't like idea of using swizzling, especially in Swift. But I understand that we don't have much time now.

I suggest two different approaches how we can follow.
1. Take a loot at `XCTestObservationCenter` and `XCTestObservation`. If it doesn't take you a lot of time to implement your task with this classes, please do it. Because it's a correct way of implementing what you need.
2. Leave swizzling as it is now. Create a separate issue which tells that it should be rewritten later as of option 1 above. Put the link of this issue it in the code.

It's up to you to decide how to follow, but please take a look at 1 before leaving as it is now. I think it wold be easy since you just need very simple logs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (7cea8e2)

**Comment by ThaliTester** [comment]
Test 864825827cea8e2(7cea8e2) has failed

See https://github.com/ThaliTester/TestResults/tree/864825827cea8e2_Added_logging_to_TestRunner_baydet/ for the fail logs

**Comment by larryonoff** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift, line 78 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-KSLvwFN-GlPpFin8VnZ:-KSLvwFN-GlPpFin8Vn_:bg7isql) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7cea8e22ebd8bff6e9cc8565d75ea1bad1fa7bf0/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift#L78)):*
> ```Swift
>         // Test must only be run on the main thread.
>         // Please note that it's important not using GCD, because XCTest.framework doesn't use GCD
>         if !NSThread.currentThread().isMainThread {
> ```

NB: This's very tricky place. It may not work if someone calls `runTest` via GDC methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136)*

**Comment by larryonoff** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-:-KSLwC_BrPtBqNu6wK-o:bnfp4nl)*

**Comment by baydet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift, line 15 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-KSLYQbxMGxKILIzW8gA:-KSLwy44xztGaUIrSqIZ:bkuuddu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/0901bf999d16b0f01795682c1124c95a06395d2c/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift#L15)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> NB:
> 
> I don't like idea of using swizzling, especially in Swift. But I understand that we don't have much time now.
> 
> I suggest two different approaches how we can follow.
> 1. Take a loot at `XCTestObservationCenter` and `XCTestObservation`. If it doesn't take you a lot of time to implement your task with this classes, please do it. Because it's a correct way of implementing what you need.
> 2. Leave swizzling as it is now. Create a separate issue which tells that it should be rewritten later as of option 1 above. Put the link of this issue it in the code.
> 
> It's up to you to decide how to follow, but please take a look at 1 before leaving as it is now. I think it wold be easy since you just need very simple logs.
</details>
I've replaced swizzling with XCTestObservation. It really looks nicer and clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136)*

**Comment by dersim-davaod** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136)*

**Comment by dersim-davaod** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-:-KSLyLAbtr8ffQCucvzb:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (895a768)

**Comment by ThaliTester** [comment]
Test (Success) 86482582 build is completed (895a768)

See https://github.com/ThaliTester/TestResults/tree/86482582895a768_Added_logging_to_TestRunner_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 86482582895a768(895a768) has failed

See https://github.com/ThaliTester/TestResults/tree/86482582895a768_Added_logging_to_TestRunner_baydet/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-:-KSNH8EUdzS1OklCavav:bnfp4nl)*

**Comment by baydet** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift, line 78 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-KSLvwFN-GlPpFin8VnZ:-KS_YuvSeqfFvqmftUVm:b-s5j4n0) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7cea8e22ebd8bff6e9cc8565d75ea1bad1fa7bf0/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift#L78)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> NB: This's very tricky place. It may not work if someone calls `runTest` via GDC methods.
</details>
Could you provide an example?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136)*

**Comment by larryonoff** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift, line 78 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-KSLvwFN-GlPpFin8VnZ:-KS_c5kzd2cm8EmARIAR:b1pikcd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7cea8e22ebd8bff6e9cc8565d75ea1bad1fa7bf0/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift#L78)):*
<details><summary><i>Previously, baydet (Alexander Evsyuchenya) wrote…</i></summary>
> Could you provide an example?
</details>
I'm lazy, so just posting article
http://blog.benjamin-encz.de/post/main-queue-vs-main-thread/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136)*

**Comment by baydet** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift, line 78 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136#-KSLvwFN-GlPpFin8VnZ:-KS_kvY1VutbhLKp5o3l:b3wz99y) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7cea8e22ebd8bff6e9cc8565d75ea1bad1fa7bf0/lib/ios/ThaliCore/ThaliCoreCITests/TestRunner/TestRunner.swift#L78)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I'm lazy, so just posting article
> http://blog.benjamin-encz.de/post/main-queue-vs-main-thread/
</details>
I'm not sure if it's a real problem in our case. Even if this mainThread check fails we're performing selector on main thread. I use this construction because I didn't use 3 calls of  performSelectorOnMainThread for these lines

```
        XCTestObservationCenter.sharedTestObservationCenter().addTestObserver(self)
        testSuite.runTest()
        XCTestObservationCenter.sharedTestObservationCenter().removeTestObserver(self)
```

PS
Since you marked this as NB could you just acknowledge this as viewed to make this annoying reviewable check passing :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1136)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (e70b00a)

**Comment by ThaliTester** [comment]
Test (Success) 86482582 build is completed (e70b00a)

See https://github.com/ThaliTester/TestResults/tree/86482582e70b00a_Added_logging_to_TestRunner_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 86482582e70b00a(e70b00a) has failed

See https://github.com/ThaliTester/TestResults/tree/86482582e70b00a_Added_logging_to_TestRunner_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (6cfc86f)

**Comment by ThaliTester** [comment]
Test (Success) 86482582 build is completed (6cfc86f)

See https://github.com/ThaliTester/TestResults/tree/864825826cfc86f_Added_logging_to_TestRunner_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 864825826cfc86f(6cfc86f) has failed

See https://github.com/ThaliTester/TestResults/tree/864825826cfc86f_Added_logging_to_TestRunner_baydet/ for the fail logs

**Pull request merged**
