### PR TITLE
Fix null pointer exception.

### PR DESCRIPTION
**Pull request by evabishchevich**
The initialization of the thread was moved before adding the thread to collection

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1801)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5403141)

**Comment by ThaliTester** [comment]
Test 106327918 (5403141) build started.

**Comment by ThaliTester** [comment]
Test (Success) 106327918 build is completed (5403141)

See https://github.com/ThaliTester/TestResults/tree/1063279185403141_Fix_null_pointer_exception__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 1063279185403141(5403141) has failed

See https://github.com/ThaliTester/TestResults/tree/1063279185403141_Fix_null_pointer_exception__evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
Couldn't connect to test server

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionModel.java, line 149 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1801#-Kd2SIYlDwb-5ur1H6GY:-Kd2SIYm30w8UEWwJfrb:bkirtnh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5403141246ec79c621da8f788a18c058e52908ae/src/android/java/io/jxcore/node/ConnectionModel.java#L149)):*
> ```Java
>      * @return True, if the thread was successfully added to the collection. False otherwise.
>      */
>     public synchronized boolean addConnectionThread(IncomingSocketThread incomingSocketThread) {
> ```

Does this method really need to be synchronized? I thought the whole point of CopyOnWriteArrayList is that it's thread safe? Same issue with addConnectionThread below.

---

*[src/android/java/io/jxcore/node/ConnectionModel.java, line 150 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1801#-Kd2S9l1fKOGqM1fiz0p:-Kd2S9l1fKOGqM1fiz0q:b-8ct9mm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5403141246ec79c621da8f788a18c058e52908ae/src/android/java/io/jxcore/node/ConnectionModel.java#L150)):*
> ```Java
>      */
>     public synchronized boolean addConnectionThread(IncomingSocketThread incomingSocketThread) {
>         return mIncomingSocketThreads.add(incomingSocketThread);
> ```

But don't we want to check that we aren't adding the same thread twice? Same issue in addConnectionThread below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1801)*

**Comment by evabishchevich** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/java/io/jxcore/node/ConnectionModel.java, line 149 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1801#-Kd2SIYlDwb-5ur1H6GY:-Kd5WaD6Lc65um5emCn4:b-h8n56u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5403141246ec79c621da8f788a18c058e52908ae/src/android/java/io/jxcore/node/ConnectionModel.java#L149)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Does this method really need to be synchronized? I thought the whole point of CopyOnWriteArrayList is that it's thread safe? Same issue with addConnectionThread below.
</blockquote></details>

No, it doesn't. We still have `synchronized`add method in CopyOnWriteArrayList

---

*[src/android/java/io/jxcore/node/ConnectionModel.java, line 150 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1801#-Kd2S9l1fKOGqM1fiz0p:-Kd5WsC27v8VdDxry_gj:b4m5h54) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5403141246ec79c621da8f788a18c058e52908ae/src/android/java/io/jxcore/node/ConnectionModel.java#L150)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

But don't we want to check that we aren't adding the same thread twice? Same issue in addConnectionThread below.
</blockquote></details>

We have contains for that. I think it's responsibility of the client. It's really arguable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1801)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (457c3ab)

**Comment by ThaliTester** [comment]
Test 106327918 (457c3ab) build started.

**Comment by ThaliTester** [comment]
Test (Success) 106327918 build is completed (457c3ab)

See https://github.com/ThaliTester/TestResults/tree/106327918457c3ab_Fix_null_pointer_exception__evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 106327918457c3ab(457c3ab) has failed

See https://github.com/ThaliTester/TestResults/tree/106327918457c3ab_Fix_null_pointer_exception__evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1801#-:-Kd8H7jKI6Gz7vk7MICW:bnfp4nl)*

**Pull request merged**
