### PR TITLE
Android tests from vNext

### PR DESCRIPTION
**Pull request by evabishchevich**
Fixed IncomingSocketThreadTest and OutgoingSocketThreadTest

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1225)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (cb99449)

**Comment by ThaliTester** [comment]
Test (Success) 87465790 build is completed (cb99449)

See https://github.com/ThaliTester/TestResults/tree/87465790cb99449_Android_tests_from_vNext_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 87465790cb99449(cb99449) has failed

See https://github.com/ThaliTester/TestResults/tree/87465790cb99449_Android_tests_from_vNext_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (9d14aa8)

**Comment by ThaliTester** [comment]
Test (Success) 87465790 build is completed (9d14aa8)

See https://github.com/ThaliTester/TestResults/tree/874657909d14aa8_Android_tests_from_vNext_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 874657909d14aa8(9d14aa8) has failed

See https://github.com/ThaliTester/TestResults/tree/874657909d14aa8_Android_tests_from_vNext_evabishchevich/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b4b0073)

**Comment by ThaliTester** [comment]
Test (Success) 87465790 build is completed (b4b0073)

See https://github.com/ThaliTester/TestResults/tree/87465790b4b0073_Android_tests_from_vNext_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 87465790b4b0073(b4b0073) has failed

See https://github.com/ThaliTester/TestResults/tree/87465790b4b0073_Android_tests_from_vNext_evabishchevich/ for the fail logs

**Comment by yaronyg** [comment]
@vasilevskayaem Why haven't we checked this in? Are any of the test failures new?

---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1225#-:-KTFgxjcSr1abnXFosOe:b-qq9s6i)*

**Comment by vasilevskayaem** [comment]
checked, this changes related only to native java tests that are running before coordination. The only one problem here is in IncomingSocketThreadTest and OutgoingSocketThreadTest (io.jxcore.node.StreamCopyingThread has "while" loop with try/catch). This code isn't cause any new test failures.

**Comment by vasilevskayaem** [comment]
:lgtm:

---

Reviewed 23 of 24 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1225#-:-KTJCegS1f-fO7zlkCK8:bg7igk9)*

**Pull request merged**
