### PR TITLE
Enable native layer and replication tests.

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/340)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (34e3b48)

**Comment by ThaliTester** [comment]
Test (Success) 51074821 build is completed (34e3b48)

See https://github.com/ThaliTester/TestResults/tree/5107482134e3b48_Enable_native_layer_and_replication_tests__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5107482134e3b48(34e3b48) has failed

See https://github.com/ThaliTester/TestResults/tree/5107482134e3b48_Enable_native_layer_and_replication_tests__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f72e61a)

**Comment by ThaliTester** [comment]
Test (Success) 51074821 build is completed (f72e61a)

See https://github.com/ThaliTester/TestResults/tree/51074821f72e61a_Enable_native_layer_and_replication_tests__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 51074821f72e61a(f72e61a) has failed

See https://github.com/ThaliTester/TestResults/tree/51074821f72e61a_Enable_native_layer_and_replication_tests__vjrantal/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/340)_

**Pull request merged**
