### PR TITLE
#1500 Fix wifi mode advertising/discovering after connecting to another WiFi access point

### LINKED ISSUE #1500: [WiFi mode] data added while WiFi network is not available is not replicated after reconnect.
The issue can be reproduced with ThaliTestApp (25fd8e88a03cd5b8f59537a20068829b70d45734) using Thali_CordovaPlugin (74892000d210f843e9ca68a5948859f3cb2e2bbf).

Steps to reproduce:
1. Start ThaliTestApp on 2 devices.
2. Select WiFi mode, initialize and start Thali.
3. Add data on both devices to check if replication works.
4. Turn off WiFi network - note that WiFi should be left enabled on phones, but the WiFi network should be turned down.
5. Add some data on any device.
6. Turn WiFi network on again.
7. After devices reconnect to network the data added in step 5 is not replicated to other device. Only after adding additional data replication starts.

Here are the logs from 2 Samsungs:
[S7_1](https://gist.github.com/czyzm/6f67ed88373c3f4854f0c697dbc81b83)
[S7_2](https://gist.github.com/czyzm/9c99db9ce8ec2b490bc42bf3a9071133)
After turning off WiFi network I added data on S7_2 at about 11:13:17. WiFi was turned back on at about 11:14:40. Additionall data was sent at 11:15:24.

### PR DESCRIPTION
**Pull request by chapko**
Fixes #1500

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1773)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b2af177)

**Comment by ThaliTester** [comment]
Test 104148244 (b2af177) build started.

**Comment by ThaliTester** [comment]
Test (Success) 104148244 build is completed (b2af177)

See https://github.com/ThaliTester/TestResults/tree/104148244b2af177_Fix_wifi_mode_advertising/discovering_after_connecting_to_another_WiFi_access_point_chapko/ for the logs

**Comment by yaronyg** [comment]
Please see comment and then :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testSSDPServer.js, line 89 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-KbvHlWiIcu6PqDx6zlT:-KbvHlWiIcu6PqDx6zlU:bgu0so5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b2af177be45ba7ec65a37b62666c999e248fb9f2/test/www/jxcore/bv_tests/testSSDPServer.js#L89)):*
> ```JavaScript
> 
> test(
>   'ssdp server should be restarted when bssid changed',
> ```

Shouldn't we have a similar set of tests for SSID? And should we also test cases such as the BSSID changes but the SSID doesn't and vice versa?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-:-KbvHwF4w3lefcPnb2p8:b-5jq9x5)*

**Comment by ThaliTester** [comment]
Test 104148244b2af177(b2af177) has failed

See https://github.com/ThaliTester/TestResults/tree/104148244b2af177_Fix_wifi_mode_advertising/discovering_after_connecting_to_another_WiFi_access_point_chapko/ for the fail logs

**Comment by chapko** [comment]
These changes were made on top of #1772 PR. My plan is to wait for review of the 1772, fix all comments and then merge this branch directly into `iOS` (or maybe even `master` at that time)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testSSDPServer.js, line 89 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-KbvHlWiIcu6PqDx6zlT:-Kby38bxIH5gDmAPQJ-9:bc4y9i6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/b2af177be45ba7ec65a37b62666c999e248fb9f2/test/www/jxcore/bv_tests/testSSDPServer.js#L89)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

Shouldn't we have a similar set of tests for SSID? And should we also test cases such as the BSSID changes but the SSID doesn't and vice versa?
</blockquote></details>

As far as I understand, if devices connects to another WiFi network (new SSID) it will also connect to the different access point (new BSSID). The only uncovered case is when the access point starts broadcast new SSID. I wasn't able to make this scenario work on devices, they first disconnect from the AP with an old SSID and then connect to the same AP with new SSID emitting 2 events covered by this test.

The only reason I see to add SSID check in the WifiInfrastructure is for the platforms that does not provide API to retrieve current BSSID, but we have this API on android and iOS so it is not worth it right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-:-KbyADhzc9VViCXaSfgE:bhkmbij)*

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-:-KbykPP-HBZb3JifirKd:bnfp4nl)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b516848)

**Comment by ThaliTester** [comment]
Test 104148244 (b516848) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (98b4517)

**Comment by ThaliTester** [comment]
Test (Success) 104148244 build is completed (b516848)

See https://github.com/ThaliTester/TestResults/tree/104148244b516848__1500_Fix_wifi_mode_advertising/discovering_after_connecting_to_another_WiFi_access_point_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 104148244 (98b4517) build started.

**Comment by ThaliTester** [comment]
Test 104148244b516848(b516848) has failed

See https://github.com/ThaliTester/TestResults/tree/104148244b516848__1500_Fix_wifi_mode_advertising/discovering_after_connecting_to_another_WiFi_access_point_chapko/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 104148244 build is completed (98b4517)

See https://github.com/ThaliTester/TestResults/tree/10414824498b4517__1500_Fix_wifi_mode_advertising/discovering_after_connecting_to_another_WiFi_access_point_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 10414824498b4517(98b4517) has failed

See https://github.com/ThaliTester/TestResults/tree/10414824498b4517__1500_Fix_wifi_mode_advertising/discovering_after_connecting_to_another_WiFi_access_point_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-:-Kbzrs2jHggX1ujY1CF-:bnfp4nl)*

**Comment by czyzm** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 166 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-Kc37DXV4q_5pmpEghUh:-Kc37DXWbj3QS87pEraq:b34j7qv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/98b4517e1f555420433526f1da5f69c057d2e2ba/thali/NextGeneration/thaliWifiInfrastructure.js#L166)):*
> ```JavaScript
>     })
>     .catch(function (error) {
>       self._errorStop(error);
> ```

Should be return self._errorStop(error)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773)*

**Comment by czyzm** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773)*

**Comment by evabishchevich** [comment]
This issues depends on #1772

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4b6f9b7)

**Comment by ThaliTester** [comment]
Test 104148244 (4b6f9b7) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 104148244 build is completed (4b6f9b7)

See https://github.com/ThaliTester/TestResults/tree/1041482444b6f9b7__1500_Fix_wifi_mode_advertising/discovering_after_connecting_to_another_WiFi_access_point_chapko/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b75019c)

**Comment by ThaliTester** [comment]
Test 104148244 (b75019c) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 104148244 build is completed (b75019c)

See https://github.com/ThaliTester/TestResults/tree/104148244b75019c__1500_Fix_wifi_mode_advertising/discovering_after_connecting_to_another_WiFi_access_point_chapko/ for the logs

**Comment by chapko** [comment]
I'm going to merge this PR, because the latest commit contains review comments fixes for the base branch PR and it was too difficult to fix them directly in the base branch without affecting this one.

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 166 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-Kc37DXV4q_5pmpEghUh:-Kcryzb-eBs6DSOVpFHV:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/98b4517e1f555420433526f1da5f69c057d2e2ba/thali/NextGeneration/thaliWifiInfrastructure.js#L166)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

Should be return self._errorStop(error)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1773#-:-Kcs34ykdoTn66m2NWaF:bbtr0s2)*

**Pull request merged**
