### PR TITLE
Add docs, fix lint warnings

### PR DESCRIPTION
**Pull request by chapko**
Clean up thaliMobile.js and testThaliMobile.js

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1746)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5707029)

**Comment by ThaliTester** [comment]
Test 102581708 (5707029) build started.

**Comment by ThaliTester** [comment]
Test 1025817085707029(5707029) has failed

See https://github.com/ThaliTester/TestResults/tree/1025817085707029_Add_docs__fix_lint_warnings_chapko/ for the fail logs

**Comment by czyzm** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliMobile.js, line 291 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746#-KbEDEK0Pv0h3iWumRzr:-KbEDEK0Pv0h3iWumRzs:b-pk6ed5) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5707029593598f1485b71c4d2cc22a110832a452/thali/NextGeneration/thaliMobile.js#L291)):*
> ```JavaScript
>  * @private
>  *
>  * TODO: remove this export and instead check thaliWifiInfrastructure and
> ```

Is there an issue created for this removal? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746)*

**Comment by czyzm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1566 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746#-KbEGRSRRgjTO5s8QvcX:-KbEGRSRRgjTO5s8QvcY:bf60gvj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5707029593598f1485b71c4d2cc22a110832a452/test/www/jxcore/bv_tests/testThaliMobile.js#L1566)):*
> ```JavaScript
>         return new Promise(function (resolve) {
>           function networkChangedHandler (networkStatus) {
>             // TODO Android can send event with 'wifi': 'off' and without 'bssidName' and 'ssidName'.
> ```

Line too long

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1568 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746#-KbEG6SN71y3IdLOhA6j:-KbEG6SN71y3IdLOhA6k:b8qpbpn) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5707029593598f1485b71c4d2cc22a110832a452/test/www/jxcore/bv_tests/testThaliMobile.js#L1568)):*
> ```JavaScript
>             // TODO Android can send event with 'wifi': 'off' and without 'bssidName' and 'ssidName'.
>             // t.equals(networkStatus.wifi, 'off', 'wifi should be off');
>             t.ok(networkStatus.bssidName == null, 'bssid should be null');
> ```

Change comparison to use ===

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (73f290a)

**Comment by ThaliTester** [comment]
Test 102581708 (73f290a) build started.

**Comment by chapko** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1566 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746#-KbEGRSRRgjTO5s8QvcX:-KbF8HZATVra5f4d5cW_:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5707029593598f1485b71c4d2cc22a110832a452/test/www/jxcore/bv_tests/testThaliMobile.js#L1566)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

Line too long
</blockquote></details>

Done.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 1568 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746#-KbEG6SN71y3IdLOhA6j:-KbF2aJ8h2G7s0-Mku-H:b2dvp58) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5707029593598f1485b71c4d2cc22a110832a452/test/www/jxcore/bv_tests/testThaliMobile.js#L1568)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

Change comparison to use ===
</blockquote></details>

I intentionally left it as is because it first should be fixed on native level. I created #1751 for this.

---

*[thali/NextGeneration/thaliMobile.js, line 291 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746#-KbEDEK0Pv0h3iWumRzr:-KbF4BIfrMAL0fnDV2AB:blqq2tr) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5707029593598f1485b71c4d2cc22a110832a452/thali/NextGeneration/thaliMobile.js#L291)):*
<details><summary><i>Previously, czyzm wrote…</i></summary><blockquote>

Is there an issue created for this removal? 
</blockquote></details>

I'm not sure there has to be an issue for this. It is not a bug or even enhancement, just a general TODO comment to guide the further refactoring and code cleanup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746)*

**Comment by ThaliTester** [comment]
Test (Success) 102581708 build is completed (73f290a)

See https://github.com/ThaliTester/TestResults/tree/10258170873f290a_Add_docs__fix_lint_warnings_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 10258170873f290a(73f290a) has failed

See https://github.com/ThaliTester/TestResults/tree/10258170873f290a_Add_docs__fix_lint_warnings_chapko/ for the fail logs

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1746#-:-KbFXERsKpATmd135PBu:bnfp4nl)*

**Pull request merged**
