### PR TITLE
#1531 Increase LocalSeqManager timers for iOS devices

### PR DESCRIPTION
**Pull request by chapko**
Related to thaliproject/Thali_CordovaPlugin#1618

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1678)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (0a19089)

**Comment by ThaliTester** [comment]
Test 99248131 (0a19089) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99248131 build is completed (0a19089)

See https://github.com/ThaliTester/TestResults/tree/992481310a19089__1531_Increase_LocalSeqManager_timers_for_iOS_devices_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 992481310a19089(0a19089) has failed

See https://github.com/ThaliTester/TestResults/tree/992481310a19089__1531_Increase_LocalSeqManager_timers_for_iOS_devices_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1678#-:-KZgiRIWigzUX3xFdQfA:bnfp4nl)*

**Pull request merged**
