### PR TITLE
Fix messed up SSDP binding language

### PR DESCRIPTION
**Pull request by yaronyg**
The original language I submitted made literally no sense. Hopefully this version will be slightly more sensible.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/470)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1a686b7)

**Comment by ThaliTester** [comment]
Test (Success) 56530712 build is completed (1a686b7)

See https://github.com/ThaliTester/TestResults/tree/565307121a686b7_Fix_messed_up_SSDP_binding_language_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 565307121a686b7(1a686b7) has failed

See https://github.com/ThaliTester/TestResults/tree/565307121a686b7_Fix_messed_up_SSDP_binding_language_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 137 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/470#-K8Se4kg00z_w9L24L_p:-K8Se4kg00z_w9L24L_q:252722188) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/1a686b701e4d32f1ab6c5c3b73edc55d8a370e8e/thali/NextGeneration/thaliWifiInfrastructure.js#L137)):*
The coordinated test runner I have done for desktop spawns multiple node processes that all use the same port for multicast traffic and I haven't noticed any issues. However, we can leave this open issue as long as the behavior is verified also on iOS and Android. There, probably some manual one-time verification would be required since you would need to run two different apps at the same time.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/470)*

**Pull request merged**
