### PR TITLE
#1189 Fixed socket connection events handlers

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1194)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (3c9f8d0)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (c13aaf2)

**Comment by ThaliTester** [comment]
Test (Success) 87083959 build is completed (3c9f8d0)

See https://github.com/ThaliTester/TestResults/tree/870839593c9f8d0__1189_Fixed_socket_connection_events_handlers_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 87083959 build is completed (c13aaf2)

See https://github.com/ThaliTester/TestResults/tree/87083959c13aaf2__1189_Fixed_socket_connection_events_handlers_artemjackson/ for the logs

**Comment by andrew-aladev** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1194)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1194#-:-KSkEjd3PFnV2PAG5eOo:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 870839593c9f8d0(3c9f8d0) has failed

See https://github.com/ThaliTester/TestResults/tree/870839593c9f8d0__1189_Fixed_socket_connection_events_handlers_artemjackson/ for the fail logs

**Pull request merged**
