### PR TITLE
Some instructions on using Thali

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1239)

### CODE REVIEW

**Comment by ThaliTester** [comment]
Skipping PR - No APP related changes

**Comment by larryonoff** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[readme.md, line 66 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239#-KTE1nY56CoScz-HxLOe:-KTE1nY56CoScz-HxLOf:b-hobh06) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/35e3416209e84abf4d63c6791141f2c9b61fcf73/readme.md#L66)):*
> ```Markdown
> 
> If you don't already have a package.json, this will create one for you. If you
> already have a package.json then you can skip the previous command.
> ```

I think we should emphasise the folder where this command should be run.

---

*[readme.md, line 69 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239#-KTE1yFJSs8wTzIH2O-9:-KTE1yFJSs8wTzIH2O-A:b-ylfg5y) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/35e3416209e84abf4d63c6791141f2c9b61fcf73/readme.md#L69)):*
> ```Markdown
> 
> ```
> jx npm install ../../../Thali_CordovaPlugin/thali/ --save --no-optional --autoremove "*.gz"
> ```

I think that we should get rid of using relative paths. So I think we should use something like
```
jx npm install ${Path_to_Thali_Cordova_Plugin}/thali/ --save --no-optional --autoremove "*.gz"
```

---

*[readme.md, line 75 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239#-KTE2iJ17JgMK_R4xei-:-KTE2iJ17JgMK_R4xei0:b-hobh06) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/35e3416209e84abf4d63c6791141f2c9b61fcf73/readme.md#L75)):*
> ```Markdown
> does a dizzying variety of things including setting up the Cordova environment
> with Thali's specific extensions as well as setting up the www/jxcore node
> app with all of Thali's dependencies.
> ```

I think we should emphasise the folder where this command should be run.

---

*[test/README.md, line 50 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239#-KTE5ODP4XFCq8VYjUhy:-KTE5ODP4XFCq8VYjUhz:bnpuhd8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/35e3416209e84abf4d63c6791141f2c9b61fcf73/test/README.md#L50)):*
> ```Markdown
> to your machine.
> 
> In terms of operating system we assume you are running on OS/X. In theory we can
> ```

OS/X isn't used anymore, now it's macOS :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239)*

**Comment by larryonoff** [comment]
@yaronyg I've added some comments

**Comment by chapko** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f8e43ee)

**Comment by yaronyg** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[readme.md, line 66 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239#-KTE1nY56CoScz-HxLOe:-KTGY0jnKZyCh_uun-w8:b-bu91xm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/35e3416209e84abf4d63c6791141f2c9b61fcf73/readme.md#L66)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I think we should emphasise the folder where this command should be run.
</details>
Updated

---

*[readme.md, line 69 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239#-KTE1yFJSs8wTzIH2O-9:-KTGXe8XACWEptPpPfCT:b-xax8eg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/35e3416209e84abf4d63c6791141f2c9b61fcf73/readme.md#L69)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I think that we should get rid of using relative paths. So I think we should use something like
> ```
> jx npm install ${Path_to_Thali_Cordova_Plugin}/thali/ --save --no-optional --autoremove "*.gz"
> ```
</details>
Actually I think using a relative path here is a feature because these are commands we expect the person to type in at the command line. This isn't a script. And the relative path will work regardless of what the name of the parent directory is. In other words I believe this is a feature, not a bug.

---

*[readme.md, line 75 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239#-KTE2iJ17JgMK_R4xei-:-KTGYbiVw3r3CITAagvk:b-bu91xm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/35e3416209e84abf4d63c6791141f2c9b61fcf73/readme.md#L75)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> I think we should emphasise the folder where this command should be run.
</details>
Updated

---

*[test/README.md, line 50 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239#-KTE5ODP4XFCq8VYjUhy:-KTGmd6HcLIKWCV2yFoB:b4orfxi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/35e3416209e84abf4d63c6791141f2c9b61fcf73/test/README.md#L50)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary>
> OS/X isn't used anymore, now it's macOS :)
</details>
Good to see somebody is protecting Apple's brands. :) Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1239)*

**Comment by ThaliTester** [comment]
Test (Success) 87784240 build is completed (f8e43ee)

See https://github.com/ThaliTester/TestResults/tree/87784240f8e43ee_Some_instructions_on_using_Thali_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 87784240f8e43ee(f8e43ee) has failed

See https://github.com/ThaliTester/TestResults/tree/87784240f8e43ee_Some_instructions_on_using_Thali_yaronyg/ for the fail logs

**Pull request merged**
