### PR TITLE
1 meg test

### LINKED ISSUE #1332: 1 Meg Raw 1 Way Native Test
This test uses the native interface to see how quickly we can move 1 meg of data to the other peers.
 * Step 1 - Elect a peer - the coordinator will have sent all the peers the UUIDs generated by the other peers. Whichever peer has the lexically smallest peerID (we already have code for this somewhere) is the 'leader'.
* Step 2 - Non-leader peers will call startUpdateAdvertisingAndListening and will point their listener at a TCP server in Node that will count all the bytes it gets and when they add up to 1 megabyte will return a single byte response with the value of 0.
* Step 3 - The leader peer will call start startListeningForAdvertisements. When a peer is found a timer will be started for that peer and the leader will connect to the port advertised in the peerAvailabilityChanged event to connect to the peer and start to push a random stream of data at it until it gets back the confirmation byte. At that point the leader will stop the timer for that peer. If the connection should fail for any reason the peer will immediately try to reconnect and start sending the data again until it gets that confirmation byte.
* Step 4 - Once the leader has gotten confirmation bytes from all the peers then the leader will output to the log a table with a list of the peers it connected to and the time it took to get the confirmation byte from each.
This test should be run 10 times in a row and average, median and standard deviation results published at the end.
The test should be run once in Native only mode and once in Wifi only mode.
This test should be run with 2 peers, 3 peers and 4 peers.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1332.

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1390)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (74424c9)

**Comment by ThaliTester** [comment]
Test 9015740074424c9(74424c9) has failed

See https://github.com/ThaliTester/TestResults/tree/9015740074424c9_1_meg_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (28b93f6)

**Comment by ThaliTester** [comment]
Test (Success) 90157400 build is completed (28b93f6)

See https://github.com/ThaliTester/TestResults/tree/9015740028b93f6_1_meg_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 9015740028b93f6(28b93f6) has failed

See https://github.com/ThaliTester/TestResults/tree/9015740028b93f6_1_meg_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (84a7855)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (a66ed30)

**Comment by ThaliTester** [comment]
Test (Fail) 90157400 build is completed (84a7855)

See https://github.com/ThaliTester/TestResults/tree/9015740084a7855_1_meg_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 90157400 build is completed (a66ed30)

See https://github.com/ThaliTester/TestResults/tree/90157400a66ed30_1_meg_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9516b37)

**Comment by ThaliTester** [comment]
Test 90157400a66ed30(a66ed30) has failed

See https://github.com/ThaliTester/TestResults/tree/90157400a66ed30_1_meg_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 90157400 build is completed (9516b37)

See https://github.com/ThaliTester/TestResults/tree/901574009516b37_1_meg_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 901574009516b37(9516b37) has failed

See https://github.com/ThaliTester/TestResults/tree/901574009516b37_1_meg_test_andrew-aladev/ for the fail logs

**Comment by andrew-aladev** [comment]
We need to work further with this test.

**Pull request closed without merging**
