### PR TITLE
Implemented mobile test

### LINKED ISSUE #1316: Implement tests for new Wifi related functionality in Node
Issue thaliproject/Thali_CordovaPlugin#1314 which is closed by PR thaliproject/Thali_CordovaPlugin#1315 defines that networkChanged should return BSSID and SSID for both Android and iOS. We need tests in Node to confirm we are getting those values.

The PR also adds a new method to turn WiFi on and off. We need to run a test on Android only where we check current network status, turn Wifi to the opposite, check status again and then turn Wifi back to its original state.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1316.

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1368)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d940446)

**Comment by ThaliTester** [comment]
Test (Success) 89975734 build is completed (d940446)

See https://github.com/ThaliTester/TestResults/tree/89975734d940446_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 89975734d940446(d940446) has failed

See https://github.com/ThaliTester/TestResults/tree/89975734d940446_Implemented_mobile_test_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
Unfortunately the PR is not complete. The expectation was that you would add the setWifiRadioState method to thaliMobileNativeWrapper.js, thaliMobile.js and thaliManager.js. And then test those apis to make sure they work. The idea is that this API will be used by folks writing peer policies to provide more fine grained control over our radio behavior.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 303 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KUT_5cjFJd7UBxfJ0fr:-KUT_5ckrTAahm89ZtuE:b-g4ryla) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d9404464e7dbe6a783dce10a276ab28639acb9c9/test/www/jxcore/bv_tests/testThaliMobile.js#L303)):*
> ```JavaScript
>     });
>   })
> ```

NB: Personally I find that putting spaces between then clauses makes it harder to read. It makes my eye forget that they are all part of the same promise chain.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 342 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KUT_L4dSouQGmQbyEFn:-KUT_L4dSouQGmQbyEFo:b8ad3lw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d9404464e7dbe6a783dce10a276ab28639acb9c9/test/www/jxcore/bv_tests/testThaliMobile.js#L342)):*
> ```JavaScript
>     toggle()
>     .then(function () {
>       process.nextTick(function () {
> ```

Shouldn't this be setImmediate and not nextTick? By using nextTick aren't we putting our code at the top of the event loop so we wouldn't give the events a chance to be emitted? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-:-KUTZ0ivBMEFC3HnwuQL:bc71tlm)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1f57d46)

**Comment by ThaliTester** [comment]
Test (Success) 89975734 build is completed (1f57d46)

See https://github.com/ThaliTester/TestResults/tree/899757341f57d46_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 303 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KUT_5cjFJd7UBxfJ0fr:-KV5YwOOu0hvxT5dBJ65:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d9404464e7dbe6a783dce10a276ab28639acb9c9/test/www/jxcore/bv_tests/testThaliMobile.js#L303)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Personally I find that putting spaces between then clauses makes it harder to read. It makes my eye forget that they are all part of the same promise chain.
</details>
Done.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 342 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KUT_L4dSouQGmQbyEFn:-KV5YzAHR6RezoxaEmtq:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d9404464e7dbe6a783dce10a276ab28639acb9c9/test/www/jxcore/bv_tests/testThaliMobile.js#L342)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Shouldn't this be setImmediate and not nextTick? By using nextTick aren't we putting our code at the top of the event loop so we wouldn't give the events a chance to be emitted? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368)*

**Comment by ThaliTester** [comment]
Test 899757341f57d46(1f57d46) has failed

See https://github.com/ThaliTester/TestResults/tree/899757341f57d46_Implemented_mobile_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (636a1a7)

**Comment by ThaliTester** [comment]
Test (Fail) 89975734 build is completed (636a1a7)

See https://github.com/ThaliTester/TestResults/tree/89975734636a1a7_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by evabishchevich** [comment]
@andrew-aladev Is that PR is complete now?

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a4e6217)

**Comment by ThaliTester** [comment]
Test 89975734 (a4e6217) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 89975734 build is completed (a4e6217)

See https://github.com/ThaliTester/TestResults/tree/89975734a4e6217_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by andrew-aladev** [comment]
Done

**Comment by yaronyg** [comment]
Reviewed 9 of 12 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/config.json, line 2 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHVqn-aZEsepVELQFP:-KXHVqn-aZEsepVELQFQ:b-slq4hw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/config.json#L2)):*
> ```JSON
> {
>   "env": {
> ```

Should this file be checked in at all?

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 345 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHXdqTXZ4VGGxmcqU7:-KXHXdqTXZ4VGGxmcqU8:b-18pa70) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L345)):*
> ```JavaScript
>   'network changes emitted correctly',
>   function () {
>     return global.NETWORK_TYPE !== ThaliMobile.networkTypes.WIFI;
> ```

But shouldn't we also run this test with BOTH as well as WIFI? Heck, I don't see why we don't also run it with Native. Our ability to manipulate Wifi shouldn't be limited by what network mode we are in. I'm guessing that all that should matter is if we are on Android or iOS.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 414 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHY2I3xUfnCjn4Gque:-KXHY2I4DsOP6HhCqRrc:bmafzjs) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L414)):*
> ```JavaScript
>   'network changes not emitted in started state',
>   function () {
>     return global.NETWORK_TYPE !== ThaliMobile.networkTypes.WIFI;
> ```

Same point as above, perhaps we should run this test on all network modes. It's really if we are android or iOS that matters.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 453 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHYDA3BtZISgGaC-J9:-KXHYDA4lfBGTilzMDXA:b-5nvoot) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L453)):*
> ```JavaScript
>   'calls correct starts when network changes',
>   function () {
>     return global.NETWORK_TYPE !== ThaliMobile.networkTypes.WIFI;
> ```

Same issue as above.

---

*[test/www/jxcore/lib/testUtils.js, line 56 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHXCgrW4MphFK40i3c:-KXHXCgsI6xGs97l-yIG:bkhjg6s) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/lib/testUtils.js#L56)):*
> ```JavaScript
>   if (platform.isIOS) {
>     logger.warn('Mobile(\'setWifiRadioState\') is not implemented on ios');
>     return Promise.resolve();
> ```

Shouldn't we return a reject? Somebody called this function expecting us to be able to change wifi's state and that won't work on iOS so if they called us while we are iOS then isn't the test that called us broken?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 720 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHW0-JLMxRC3OMvYFK:-KXHW0-JLMxRC3OMvYFL:bq52xpd) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/thali/NextGeneration/thaliMobileNativeWrapper.js#L720)):*
> ```JavaScript
> /**
>  * This method is to enable/disable wifi.
>  *
> ```

Don't we need to document what the type and purpose is of the argument to the function?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 726 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHW7xCqU8hJipsL6r_:-KXHW7xDUaRskGGRIGxr:bmm1q1l) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/thali/NextGeneration/thaliMobileNativeWrapper.js#L726)):*
> ```JavaScript
>   if (platform.isIOS) {
>     var error = 'Mobile(\'setWifiRadioState\') is not implemented on ios';
>     console.error(error);
> ```

Why are we returning an error directly to the console? Shouldn't this be to the logger? And even then, why? Perhaps we can just remove this line?

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 733 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHWNa1gMIJqAOfJapt:-KXHWNa2uFNjg7WyNitP:b-ylsxdx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/thali/NextGeneration/thaliMobileNativeWrapper.js#L733)):*
> ```JavaScript
>     Mobile('setWifiRadioState').callNative(value, function (error) {
>       if (error) {
>         logger.error(
> ```

Why is this so important that it should be logger.error? Why even log it at all? But if we do log it shouldn't it be a lower priority?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2c9a24d)

**Comment by ThaliTester** [comment]
Test 89975734 (2c9a24d) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f2db9ce)

**Comment by ThaliTester** [comment]
Test (Success) 89975734 build is completed (2c9a24d)

See https://github.com/ThaliTester/TestResults/tree/899757342c9a24d_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 89975734 (f2db9ce) build started.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (f660a83)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (0363162)

**Comment by ThaliTester** [comment]
Test 899757342c9a24d(2c9a24d) has failed

See https://github.com/ThaliTester/TestResults/tree/899757342c9a24d_Implemented_mobile_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (f913715)

**Comment by ThaliTester** [comment]
Test (Success) 89975734 build is completed (f2db9ce)

See https://github.com/ThaliTester/TestResults/tree/89975734f2db9ce_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 89975734 (f660a83) build started.

**Comment by ThaliTester** [comment]
Test 89975734f2db9ce(f2db9ce) has failed

See https://github.com/ThaliTester/TestResults/tree/89975734f2db9ce_Implemented_mobile_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 89975734 build is completed (f660a83)

See https://github.com/ThaliTester/TestResults/tree/89975734f660a83_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 89975734 (0363162) build started.

**Comment by ThaliTester** [comment]
Test 89975734f660a83(f660a83) has failed

See https://github.com/ThaliTester/TestResults/tree/89975734f660a83_Implemented_mobile_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 89975734 build is completed (0363162)

See https://github.com/ThaliTester/TestResults/tree/899757340363162_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 89975734 (f913715) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 89975734 build is completed (f913715)

See https://github.com/ThaliTester/TestResults/tree/89975734f913715_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 899757340363162(0363162) has failed

See https://github.com/ThaliTester/TestResults/tree/899757340363162_Implemented_mobile_test_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1305340)

**Comment by ThaliTester** [comment]
Test 89975734 (1305340) build started.

**Comment by andrew-aladev** [comment]
Review status: 5 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/www/jxcore/config.json, line 2 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHVqn-aZEsepVELQFP:-KXQY31CebVEMzeqtH-d:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/config.json#L2)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Should this file be checked in at all?
</details>
Done.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 345 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHXdqTXZ4VGGxmcqU7:-KXQY4A886XfYtQ5v0yo:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L345)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> But shouldn't we also run this test with BOTH as well as WIFI? Heck, I don't see why we don't also run it with Native. Our ability to manipulate Wifi shouldn't be limited by what network mode we are in. I'm guessing that all that should matter is if we are on Android or iOS.
</details>
Done.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 414 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHY2I3xUfnCjn4Gque:-KXQY55jCxlZs_xFr7Ru:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L414)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Same point as above, perhaps we should run this test on all network modes. It's really if we are android or iOS that matters.
</details>
Done.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 453 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHYDA3BtZISgGaC-J9:-KXQY62P1qf0PxAgj5dP:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L453)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Same issue as above.
</details>
Done.

---

*[test/www/jxcore/lib/testUtils.js, line 56 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHXCgrW4MphFK40i3c:-KXQY82XHiF93ampIUC5:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/lib/testUtils.js#L56)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Shouldn't we return a reject? Somebody called this function expecting us to be able to change wifi's state and that won't work on iOS so if they called us while we are iOS then isn't the test that called us broken?
</details>
Done.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 720 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHW0-JLMxRC3OMvYFK:-KXQYB-aommQYZ2aUC06:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/thali/NextGeneration/thaliMobileNativeWrapper.js#L720)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Don't we need to document what the type and purpose is of the argument to the function?
</details>
Done.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 726 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHW7xCqU8hJipsL6r_:-KXQYBr-XYrENZjKVeJ4:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/thali/NextGeneration/thaliMobileNativeWrapper.js#L726)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Why are we returning an error directly to the console? Shouldn't this be to the logger? And even then, why? Perhaps we can just remove this line?
</details>
Done.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 733 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHWNa1gMIJqAOfJapt:-KXQYDUwAxknekWK46qh:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/thali/NextGeneration/thaliMobileNativeWrapper.js#L733)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Why is this so important that it should be logger.error? Why even log it at all? But if we do log it shouldn't it be a lower priority?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368)*

**Comment by ThaliTester** [comment]
Test (Fail) 89975734 build is completed (1305340)

See https://github.com/ThaliTester/TestResults/tree/899757341305340_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (180bfa4)

**Comment by ThaliTester** [comment]
Test 89975734 (180bfa4) build started.

**Comment by ThaliTester** [comment]
Test (Success) 89975734 build is completed (180bfa4)

See https://github.com/ThaliTester/TestResults/tree/89975734180bfa4_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 89975734180bfa4(180bfa4) has failed

See https://github.com/ThaliTester/TestResults/tree/89975734180bfa4_Implemented_mobile_test_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
Two comments were marked as fixed which weren't actually fixed. Once those are fixed then :lgtm:

---

Reviewed 1 of 1 files at r7, 1 of 1 files at r8, 1 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 345 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHXdqTXZ4VGGxmcqU7:-KXgOos5pv9RkP100cPc:b-xq4e28) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L345)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any change to the code.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 453 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHYDA3BtZISgGaC-J9:-KXgOuEZTMCWdzEtd26n:bbv58if) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L453)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any changes to the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-:-KXgPFVB4sGQa8uJJX56:b-n1v62n)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3ca8584)

**Comment by ThaliTester** [comment]
Test 89975734 (3ca8584) build started.

**Comment by andrew-aladev** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 345 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHXdqTXZ4VGGxmcqU7:-KXjljGBR61Kf0NfxuDl:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L345)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I don't see any change to the code.
</blockquote></details>

Done.

---

*[test/www/jxcore/bv_tests/testThaliMobile.js, line 453 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368#-KXHYDA3BtZISgGaC-J9:-KXjlkMBAo5fsyOfC83D:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a4e6217d8971745ea5bf7790f2d028a20a262f7f/test/www/jxcore/bv_tests/testThaliMobile.js#L453)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

I don't see any changes to the code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1368)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5c94b49)

**Comment by ThaliTester** [comment]
Test 89975734 (5c94b49) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 89975734 build is completed (3ca8584)

See https://github.com/ThaliTester/TestResults/tree/899757343ca8584_Implemented_mobile_test_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 89975734 build is completed (5c94b49)

See https://github.com/ThaliTester/TestResults/tree/899757345c94b49_Implemented_mobile_test_andrew-aladev/ for the logs

**Pull request merged**
