### PR TITLE
Workaround for pouchdb error handlers

### PR DESCRIPTION
**Pull request by andrew-aladev**
Related to #970. This wont close issue. We need to investigate the reason of assertion failed.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1211)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (45538d6)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (7fedbd5)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (fc0c702)

**Comment by artemjackson** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/utils/pouchDBGenerator.js, line 69 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1211#-KSpSnSNChV9sppLnPIY:-KSpSnSOrLaPkglk_2BU:b-ysooef) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fc0c7027bfdfc19cefaf19c7878ebcc732adb1a6/thali/NextGeneration/utils/pouchDBGenerator.js#L69)):*
> ```JavaScript
> 
>   // This is a workround for #970.
>   var CustomEventEmitter = function () {
> ```

It's unused. Isn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1211)*

**Comment by ThaliTester** [comment]
Test (Success) 87282954 build is completed (45538d6)

See https://github.com/ThaliTester/TestResults/tree/8728295445538d6_Workaround_for_pouchdb_error_handlers_andrew-aladev/ for the logs

**Comment by artemjackson** [comment]
Merged as hotfix.

**Comment by ThaliTester** [comment]
Test 8728295445538d6(45538d6) has failed

See https://github.com/ThaliTester/TestResults/tree/8728295445538d6_Workaround_for_pouchdb_error_handlers_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87282954 build is completed (7fedbd5)

See https://github.com/ThaliTester/TestResults/tree/872829547fedbd5_Workaround_for_pouchdb_error_handlers_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 87282954 build is completed (fc0c702)

See https://github.com/ThaliTester/TestResults/tree/87282954fc0c702_Workaround_for_pouchdb_error_handlers_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 872829547fedbd5(7fedbd5) has failed

See https://github.com/ThaliTester/TestResults/tree/872829547fedbd5_Workaround_for_pouchdb_error_handlers_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test 87282954fc0c702(fc0c702) has failed

See https://github.com/ThaliTester/TestResults/tree/87282954fc0c702_Workaround_for_pouchdb_error_handlers_andrew-aladev/ for the fail logs

**Pull request merged**
