### PR TITLE
added peer generation to peerAvailabilityChanged

### PR DESCRIPTION
**Pull request by baydet**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/945)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (977a8d1)

**Comment by ThaliTester** [comment]
Test (Success) 83070177 build is completed (977a8d1)

See https://github.com/ThaliTester/TestResults/tree/83070177977a8d1_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 83070177977a8d1(977a8d1) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/83070177977a8d1_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ios/AppContext.swift, line 26 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/945#-KQNR-ySkOSbMlkOlOJC:-KQNR-ySkOSbMlkOlOJD:bo40u4u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/977a8d1ce79d62062b094d3ca3dffba19cb6c622/src/ios/AppContext.swift#L26)):*
> ```Swift
> }
> 
> private extension PeerAvailability {
> ```

Where is the test where we make sure that generation is being returned properly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/945)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (56d9cc6)

**Comment by baydet** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ios/AppContext.swift, line 26 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/945#-KQNR-ySkOSbMlkOlOJC:-KQPQ2VwLbKk_JdtMD8P:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/977a8d1ce79d62062b094d3ca3dffba19cb6c622/src/ios/AppContext.swift#L26)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Where is the test where we make sure that generation is being returned properly?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/945)*

**Comment by ThaliTester** [comment]
Test (Fail) 83070177 build is completed (56d9cc6)

See https://github.com/ThaliTester/TestResults/tree/8307017756d9cc6_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (cd46680)

**Comment by dersim-davaod** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/945#-:-KQzmKtbnB5ZbWsaDuP2:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/945#-:-KR5cWisaCunPgOrDi6b:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test (Fail) 83070177 build is completed (cf3327f)

See https://github.com/ThaliTester/TestResults/tree/83070177cf3327f_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a1e367c)

**Comment by ThaliTester** [comment]
Test (Fail) 83070177 build is completed (a1e367c)

See https://github.com/ThaliTester/TestResults/tree/83070177a1e367c_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (1a7aee8)

**Comment by ThaliTester** [comment]
Test (Success) 83070177 build is completed (1a7aee8)

See https://github.com/ThaliTester/TestResults/tree/830701771a7aee8_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 830701771a7aee8(1a7aee8) has failed

See https://github.com/ThaliTester/TestResults/tree/830701771a7aee8_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (a758936)

**Comment by ThaliTester** [comment]
Test (Success) 83070177 build is completed (a758936)

See https://github.com/ThaliTester/TestResults/tree/83070177a758936_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 83070177a758936(a758936) has failed

See https://github.com/ThaliTester/TestResults/tree/83070177a758936_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5d60530)

**Comment by ThaliTester** [comment]
Test (Success) 83070177 build is completed (5d60530)

See https://github.com/ThaliTester/TestResults/tree/830701775d60530_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Comment by ThaliTester** [comment]
Test 830701775d60530(5d60530) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/830701775d60530_added_peer_generation_to_peerAvailabilityChanged_baydet/ for the logs

**Pull request merged**
