### PR TITLE
Use OS temporary folder as the download cache.

### PR DESCRIPTION
**Pull request by vjrantal**
A part of the installation is the download of the required version of the
JXCore Cordova plugin (currently ~90MB download) and unpacking that with `jx`
before adding it as Cordova plugin using Cordova commands.

This commit implements caching of the unpacked plugin folder so that the
overall installation process becomes faster. The OS temporary folder is used
for caching instead of any Thali-app folder so that full benefits of the cache
are received even if the app-folder is re-generated (this is the case with CI
scripts, for example).

This commit also adds some catches to the promise-chains so that in case of
errors, it is easier to see where the issue was.

Relates to #192.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/246)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3cc150e)

**Comment by ThaliTester** [comment]
Test (Fail) 48858863 build is completed (3cc150e)

See https://github.com/ThaliTester/TestResults/tree/488588633cc150e_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (346f65e)

**Comment by ThaliTester** [comment]
Test (Success) 48858863 build is completed (346f65e)

See https://github.com/ThaliTester/TestResults/tree/48858863346f65e_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (248832f)

**Comment by ThaliTester** [comment]
Test (Success) 48858863 build is completed (248832f)

See https://github.com/ThaliTester/TestResults/tree/48858863248832f_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 48858863346f65e(346f65e) has failed

See https://github.com/ThaliTester/TestResults/tree/48858863346f65e_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (00fa2e2)

**Comment by ThaliTester** [comment]
Test (Success) 48858863 build is completed (00fa2e2)

See https://github.com/ThaliTester/TestResults/tree/4885886300fa2e2_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 48858863248832f(248832f) has failed

See https://github.com/ThaliTester/TestResults/tree/48858863248832f_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 4885886300fa2e2(00fa2e2) has failed

See https://github.com/ThaliTester/TestResults/tree/4885886300fa2e2_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (00fa2e2)

**Comment by ThaliTester** [comment]
Test (Success) 48858863 build is completed (00fa2e2)

See https://github.com/ThaliTester/TestResults/tree/4885886300fa2e2_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the logs

**Comment by vjrantal** [comment]
One disclaimer that I haven't myself tested this yet on Windows and I have asked @DrJukka to try it out since he has the setup in place. Tomorrow, I will also setup Thali-dependencies to my Windows machine so that I can verify this works there as well (in theory, it should).

**Comment by ThaliTester** [comment]
Test 4885886300fa2e2(00fa2e2) has failed

See https://github.com/ThaliTester/TestResults/tree/4885886300fa2e2_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e5434ba)

**Comment by vjrantal** [comment]
Closing this one in favor of same changes targeting branch `story_001` at https://github.com/thaliproject/Thali_CordovaPlugin/pull/251.

**Comment by ThaliTester** [comment]
Test (Success) 48858863 build is completed (e5434ba)

See https://github.com/ThaliTester/TestResults/tree/48858863e5434ba_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 48858863e5434ba(e5434ba) has failed

See https://github.com/ThaliTester/TestResults/tree/48858863e5434ba_Use_OS_temporary_folder_as_the_download_cache__vjrantal/ for the fail logs

**Pull request closed without merging**
