### PR TITLE
SHA256 the PSK Identity

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/688)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1c69957)

**Comment by juhanak** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliNotificationBeacons.js, line 486 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/688#-KE86lLVHYBd_5opW0SV:-KE86lLVHYBd_5opW0SW:1907130028) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/1c6995749277c89f00941430b11cdf93e0b03cdf/test/www/jxcore/bv_tests/testThaliNotificationBeacons.js#L486)):*
NB: BEACON_SIZE constant could be used.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/688)*

**Comment by ThaliTester** [comment]
Test (Success) 64686283 build is completed (1c69957)

See https://github.com/ThaliTester/TestResults/tree/646862831c69957_SHA256_the_PSK_Identity_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 646862831c69957(1c69957) has failed

See https://github.com/ThaliTester/TestResults/tree/646862831c69957_SHA256_the_PSK_Identity_yaronyg/ for the fail logs

**Pull request merged**
