### PR TITLE
Fix failing test (#1725 and #1731)

### LINKED ISSUE #1725: Fix test calls correct starts when network changes
Logs:
https://gist.github.com/evabishchevich/8ea9479182ac06a671839a8f6aaaa297

### PR DESCRIPTION
**Pull request by chapko**
Fixes #1725 and #1731.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1735)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e732e55)

**Comment by ThaliTester** [comment]
Test 101910573 (e732e55) build started.

**Comment by ThaliTester** [comment]
Test (Success) 101910573 build is completed (e732e55)

See https://github.com/ThaliTester/TestResults/tree/101910573e732e55_Fix_failing_test___1725_and__1731__chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 101910573e732e55(e732e55) has failed

See https://github.com/ThaliTester/TestResults/tree/101910573e732e55_Fix_failing_test___1725_and__1731__chapko/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (09b3d0c)

**Comment by ThaliTester** [comment]
Test 101910573 (09b3d0c) build started.

**Comment by ThaliTester** [comment]
Test (Success) 101910573 build is completed (09b3d0c)

See https://github.com/ThaliTester/TestResults/tree/10191057309b3d0c_Fix_failing_test___1725_and__1731__chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 10191057309b3d0c(09b3d0c) has failed

See https://github.com/ThaliTester/TestResults/tree/10191057309b3d0c_Fix_failing_test___1725_and__1731__chapko/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9e32531)

**Comment by ThaliTester** [comment]
Test 101910573 (9e32531) build started.

**Comment by ThaliTester** [comment]
Test (Success) 101910573 build is completed (9e32531)

See https://github.com/ThaliTester/TestResults/tree/1019105739e32531_Fix_failing_test___1725_and__1731__chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 1019105739e32531(9e32531) has failed

See https://github.com/ThaliTester/TestResults/tree/1019105739e32531_Fix_failing_test___1725_and__1731__chapko/ for the fail logs

**Comment by chapko** [comment]
Turns out tests on devices are failing because bluetooth stack crashes on devices itself.

**Comment by chapko** [comment]
I've tested this branch locally on 3 Nexuses 6P and all tests passed 3 times in a row

**Comment by yaronyg** [comment]
One super minor nit that you can safely ignore. :lgtm: 

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/testUtils.js, line 73 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1735#-KarfRyulTxbAj856jYG:-KarfRyvyTS-Wq67cRbv:bn062mv) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e325312501de23c70fc7cd0fffa518d92710b69/test/www/jxcore/lib/testUtils.js#L73)):*
> ```JavaScript
>   var valueString = value? 'on' : 'off';
>   function check (networkStatus) {
>     return networkStatus[type] === valueString && (customCheck? customCheck(networkStatus) : true);
> ```

NB: I think "valueString && (!customCheck || customCheck(networkStatus))" would be more elegant. But this is obviously nit picking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1735#-:-KargH7V0A1anjFMIE2J:bic34vy)*

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1735#-:-Kaukg5onEikr1JhYp_m:bg7igkv)*

**Comment by chapko** [comment]
*[test/www/jxcore/lib/testUtils.js, line 73 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1735#-KarfRyulTxbAj856jYG:-KavkJkQ3XjeqYf2mSeu:bqw9fcf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9e325312501de23c70fc7cd0fffa518d92710b69/test/www/jxcore/lib/testUtils.js#L73)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary><blockquote>

NB: I think "valueString && (!customCheck || customCheck(networkStatus))" would be more elegant. But this is obviously nit picking.
</blockquote></details>

I was thinking about making `customCheck` required and move `valueString` comparing to the `ensureWifi` and `ensureBluetooth`. But then just created #1742 issue which addresses other possible problems here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1735)*

**Pull request merged**
