### PR TITLE
update jxcore cordova plugin to 0.1.6

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1501)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ce1f385)

**Comment by ThaliTester** [comment]
Test (Fail) 92949233 build is completed (ce1f385)

See https://github.com/ThaliTester/TestResults/tree/92949233ce1f385_update_jxcore_cordova_plugin_to_0_1_6_larryonoff/ for the logs

**Comment by larryonoff** [comment]
@vasilevskayaem please run tests locally on devices.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4560b66)

**Comment by ThaliTester** [comment]
Test (Fail) 92949233 build is completed (4560b66)

See https://github.com/ThaliTester/TestResults/tree/929492334560b66_update_jxcore_cordova_plugin_to_0_1_6_larryonoff/ for the logs

**Comment by vasilevskayaem** [comment]
on wi-fi mode fails "mode test fails network changes emitted correctly"

https://gist.github.com/vasilevskayaem/56d2961af8ba4a8f1fcd6e6e586ca481
https://gist.github.com/vasilevskayaem/3ff6dc3593c2983bd5abb135e942bd5f
https://gist.github.com/vasilevskayaem/5fed3b3a8b9c74b4af446f7bf82a1d07

**Comment by vasilevskayaem** [comment]
network changes not emitted in stopped state

https://gist.github.com/vasilevskayaem/0870dfdc0376f7afefaab8a5e422796f
https://gist.github.com/vasilevskayaem/85218598daf755220e5d2c0af3ba5d9f
https://gist.github.com/vasilevskayaem/934098d0efb15692d7c5a1a8eae88e25

**Comment by vasilevskayaem** [comment]
calls correct starts when network changes

https://gist.github.com/vasilevskayaem/a979c2c9b17d9771c9b0fbaf50d37667
https://gist.github.com/vasilevskayaem/117e10da2cbc3dbf056a65611cd7a63c
https://gist.github.com/vasilevskayaem/6694bb09829667da6f057c062d5cdcbe

**Comment by vasilevskayaem** [comment]
when network connection is lost a peer should be marked unavailable

https://gist.github.com/vasilevskayaem/78770256a81c7b4286684c922fadf559
https://gist.github.com/vasilevskayaem/39f7da616f38ab240592ea838cdddcb2
https://gist.github.com/vasilevskayaem/3d350d6e425d62c149f811bdf3f4d0bd

**Comment by vasilevskayaem** [comment]
native mode

oordinated seq test
https://gist.github.com/vasilevskayaem/00f1798f91980cbff84edc689db24faf
https://gist.github.com/vasilevskayaem/09d8cb5a9b638d7d8cf050f657c0ce96
https://gist.github.com/vasilevskayaem/c8797f256d32090bbe89750feb874ead

**Comment by vasilevskayaem** [comment]
#startUpdateAdvertisingAndListening - ending remote peers connection kills the local connection

initial peer discovery

check latest peer discovery

One action on bluetooth
https://gist.github.com/vasilevskayaem/689aab45961e8a628273df842ed0cfd6
https://gist.github.com/vasilevskayaem/034b1a38f558f23a46b07283aff32a69
https://gist.github.com/vasilevskayaem/56025d0b1f5a5958300ff14a74d71869

**Comment by vasilevskayaem** [comment]
checked on master branch tests network changes emitted correctly, network changes not emitted in stopped state, calls correct starts when network changes also fails

**Comment by vasilevskayaem** [comment]
check on master branch we also have the same errors

**Pull request merged**
