### PR TITLE
Remove race in tests

### PR DESCRIPTION
**Pull request by tobybrad**
Problem: A race exists whereby TestServer can send event to device before it's installed socket.io handler for that event (it's very awkward to ensure device install handlers before sending event that will lead to them being called because tape.js is in charge of scheduling all this). 

Soln:  Have server keep sending the event until it receives an ack from the devices that it positively was received.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/511)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3341f94)

**Comment by ThaliTester** [comment]
Test (Fail) 58135655 build is completed (3341f94)

See https://github.com/ThaliTester/TestResults/tree/581356553341f94_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 58135655 build is completed (3341f94)

See https://github.com/ThaliTester/TestResults/tree/581356553341f94_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c662d33)

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (c662d33)

See https://github.com/ThaliTester/TestResults/tree/58135655c662d33_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 58135655c662d33(c662d33) has failed

See https://github.com/ThaliTester/TestResults/tree/58135655c662d33_Remove_race_in_tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (32fb33b)

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (32fb33b)

See https://github.com/ThaliTester/TestResults/tree/5813565532fb33b_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 5813565532fb33b(32fb33b) has failed

See https://github.com/ThaliTester/TestResults/tree/5813565532fb33b_Remove_race_in_tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (677c32f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e794d2c)

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (677c32f)

See https://github.com/ThaliTester/TestResults/tree/58135655677c32f_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (e794d2c)

See https://github.com/ThaliTester/TestResults/tree/58135655e794d2c_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 58135655e794d2c(e794d2c) has failed

See https://github.com/ThaliTester/TestResults/tree/58135655e794d2c_Remove_race_in_tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a685cd3)

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (a685cd3)

See https://github.com/ThaliTester/TestResults/tree/58135655a685cd3_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 58135655a685cd3(a685cd3) has failed

See https://github.com/ThaliTester/TestResults/tree/58135655a685cd3_Remove_race_in_tests_tobybrad/ for the fail logs

**Comment by vjrantal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/UnitTestFramework.js, line 93 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/511#-K9gcbJVtY82aT7x3aRn:-K9gcbJVtY82aT7x3aRo:273668926) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a685cd389ffc7787bbd09af0f86516d99011833a/test/TestServer/UnitTestFramework.js#L93)):*
This seems to have either one too many %d or one argument missing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/511)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a1ee273)

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (a1ee273)

See https://github.com/ThaliTester/TestResults/tree/58135655a1ee273_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 58135655a1ee273(a1ee273) has failed

See https://github.com/ThaliTester/TestResults/tree/58135655a1ee273_Remove_race_in_tests_tobybrad/ for the fail logs

**Comment by vjrantal** [comment]
@tobybrad: I wonder if before merging this in, some of the logging should be reduced? Currently, the main output from the test server is pretty verbose https://github.com/ThaliTester/TestResults/blob/58135655a1ee273_Remove_race_in_tests_tobybrad/test_log.md.

Or, should we still run this in CI a few times with the logging to get confidence the fix works?

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (812b57f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0b07fff)

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (812b57f)

See https://github.com/ThaliTester/TestResults/tree/58135655812b57f_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (0b07fff)

See https://github.com/ThaliTester/TestResults/tree/581356550b07fff_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 58135655812b57f(812b57f) has failed

See https://github.com/ThaliTester/TestResults/tree/58135655812b57f_Remove_race_in_tests_tobybrad/ for the fail logs

**Comment by ThaliTester** [comment]
Test 581356550b07fff(0b07fff) has failed

See https://github.com/ThaliTester/TestResults/tree/581356550b07fff_Remove_race_in_tests_tobybrad/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 1 of 3 files at r2, 1 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/TestServer/UnitTestFramework.js, line 86 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/511#-KA4kC1Jr3FtWxjuziq8:-KA4kC1Jr3FtWxjuziq9:1392210489) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e9e7eb804e3c4a4d467a9cb3271c91009e5e5439/test/TestServer/UnitTestFramework.js#L86)):*
Some trailing whitespace, but I'd say these can be fixed when the file is otherwise refactored to pass the linter.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/511)*

**Comment by tobybrad** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/UnitTestFramework.js, line 93 \[r6\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/511#-K9gcbJVtY82aT7x3aRn:-KA4lHY5Xve8j9ywiTXj:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/a685cd389ffc7787bbd09af0f86516d99011833a/test/TestServer/UnitTestFramework.js#L93)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/511)*

**Comment by tobybrad** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/TestServer/UnitTestFramework.js, line 86 \[r9\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/511#-KA4kC1Jr3FtWxjuziq8:-KA4mElRO-vkA4XyZFno:-499146009) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/e9e7eb804e3c4a4d467a9cb3271c91009e5e5439/test/TestServer/UnitTestFramework.js#L86)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/511)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e9e7eb8)

**Comment by ThaliTester** [comment]
Test (Success) 58135655 build is completed (e9e7eb8)

See https://github.com/ThaliTester/TestResults/tree/58135655e9e7eb8_Remove_race_in_tests_tobybrad/ for the logs

**Comment by ThaliTester** [comment]
Test 58135655e9e7eb8(e9e7eb8) has failed

See https://github.com/ThaliTester/TestResults/tree/58135655e9e7eb8_Remove_race_in_tests_tobybrad/ for the fail logs

**Pull request merged**
