### PR TITLE
Send data test improvements and refactoring.

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/346)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c93db41)

**Comment by ThaliTester** [comment]
Test (Success) 51790364 build is completed (c93db41)

See https://github.com/ThaliTester/TestResults/tree/51790364c93db41_Send_data_test_improvements_and_refactoring__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 51790364c93db41(c93db41) has failed

See https://github.com/ThaliTester/TestResults/tree/51790364c93db41_Send_data_test_improvements_and_refactoring__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a0f6051)

**Comment by ThaliTester** [comment]
Test (Success) 51790364 build is completed (a0f6051)

See https://github.com/ThaliTester/TestResults/tree/51790364a0f6051_Send_data_test_improvements_and_refactoring__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 51790364a0f6051(a0f6051) has failed

See https://github.com/ThaliTester/TestResults/tree/51790364a0f6051_Send_data_test_improvements_and_refactoring__vjrantal/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 19 of 22 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/346)*

**Pull request merged**
