### PR TITLE
Fixed dictionary and related tests

### LINKED ISSUE #1687: Crash in test repeat write 2 teardown
https://raw.githubusercontent.com/ThaliTester/TestResults/9937456522c40ea_Refactor_incoming_and_outgoing_socket_thread_tests_evabishchevich/build.md

find 
uncaught exception, error: 'AssertionError: entry exists

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1687.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1708)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7fc9b76)

**Comment by ThaliTester** [comment]
Test 99681052 (7fc9b76) build started.

**Comment by ThaliTester** [comment]
Test (Success) 99681052 build is completed (7fc9b76)

See https://github.com/ThaliTester/TestResults/tree/996810527fc9b76_Fixed_dictionary_and_related_tests_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 996810527fc9b76(7fc9b76) has failed

See https://github.com/ThaliTester/TestResults/tree/996810527fc9b76_Fixed_dictionary_and_related_tests_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1708#-:-Ka9Ry_pQndXNS-djFBC:bnfp4nl)*

**Comment by jareksl** [comment]
*[thali/NextGeneration/notification/thaliPeerDictionary.js, line 209 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1708#-KaCBqsF9d2r0l7ymViN:-KaCBqsF9d2r0l7ymViO:bu07kzc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/7fc9b760b46e9bb27c2f3517b570a0ef32fd04f3/thali/NextGeneration/notification/thaliPeerDictionary.js#L209)):*
> ```JavaScript
>     entry.notificationAction.kill();
>   }
> }
> ```

NB: missing semicolon

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1708)*

**Pull request merged**
