### PR TITLE
#472 Promise Queue

### PR DESCRIPTION
**Pull request by yaronyg**
I've run into an odd error where I'm getting an unhandledRejection error on a rejection that is handled. I think that the promise structure I'm using may have confused lie (or, more likely, I'm just confused). For the moment I've disabled the test for the error but I'm concerned that the error could cause a failure in the CI environment. Let's see!

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/474)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (92c3c91)

**Comment by mattpodwysocki** [comment]
@yaronyg have you tried with the base ES6 Promise using Node v4+ to see if it is a problem with lie or your implementation in general?

**Comment by ThaliTester** [comment]
Test (Fail) 56672827 build is completed (92c3c91)

See https://github.com/ThaliTester/TestResults/tree/5667282792c3c91__472_Promise_Queue_yaronyg/ for the logs

**Comment by yaronyg** [comment]
@mattpodwysocki An excellent idea. I just tried it out and it works fine with ES6 on Node 4. See https://github.com/calvinmetcalf/lie/issues/30 for the details.

**Comment by ThaliTester** [comment]
Test (Fail) 56672827 build is completed (92c3c91)

See https://github.com/ThaliTester/TestResults/tree/5667282792c3c91__472_Promise_Queue_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b6f75d5)

**Comment by ThaliTester** [comment]
Test (Success) 56672827 build is completed (b6f75d5)

See https://github.com/ThaliTester/TestResults/tree/56672827b6f75d5__472_Promise_Queue_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (039a409)

**Comment by yaronyg** [comment]
@vjrantal Please review

**Comment by ThaliTester** [comment]
Test (Success) 56672827 build is completed (039a409)

See https://github.com/ThaliTester/TestResults/tree/56672827039a409__472_Promise_Queue_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 56672827b6f75d5(b6f75d5) has failed

See https://github.com/ThaliTester/TestResults/tree/56672827b6f75d5__472_Promise_Queue_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
Test 56672827039a409(039a409) has failed

See https://github.com/ThaliTester/TestResults/tree/56672827039a409__472_Promise_Queue_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPromiseQueue.js, line 7 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x26XpOMibJKumSiAB:-K8x26XpOMibJKumSiAC:-1278686938) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/test/www/jxcore/bv_tests/testPromiseQueue.js#L7)):*
For consistency, `unHandled` might not require camel-casing.

---

*[test/www/jxcore/bv_tests/testPromiseQueue.js, line 26 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x2zW0qzxE5G0L8mTc:-K8x2zW0qzxE5G0L8mTd:304401052) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/test/www/jxcore/bv_tests/testPromiseQueue.js#L26)):*
This function might not provide that much value, because at least based on my testing, the tape implementation we use already prints the expected and actual values in case they differ.

---

*[test/www/jxcore/bv_tests/testPromiseQueue.js, line 77 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x3_5FYhIL0t0TBYJL:-K8x3_5FYhIL0t0TBYJM:1397312881) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/test/www/jxcore/bv_tests/testPromiseQueue.js#L77)):*
A typo in `thirdPromis6e`.

---

*[thali/NextGeneration/promiseQueue.js, line 13 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x3lUJuQxZyuq429jI:-K8x3lUJuQxZyuq429jJ:-347031697) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/thali/NextGeneration/promiseQueue.js#L13)):*
By the way, do we have any file name convention for this kind of cases? Somehow, it would feel more natural that the file name would be starting with a capital letter in case requiring it returns a "class-like" and "new'able" -object.

---

*[thali/NextGeneration/promiseQueue.js, line 31 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x5f8mksgCumdBM-Iu:-K8x5f8nxpq-5XUlom9J:-876946118) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/thali/NextGeneration/promiseQueue.js#L31)):*
Why is this null assignment done?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/www/jxcore/bv_tests/testPromiseQueue.js, line 7 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x26XpOMibJKumSiAB:-K8yurYM88O564Uu6J_X:-1619987526) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/test/www/jxcore/bv_tests/testPromiseQueue.js#L7)):*
I thought in Javascript both variables and methods use camel casing? Classes use pascal casing and constants use all upper case? In which case isn't this variable named correctly?

---

*[test/www/jxcore/bv_tests/testPromiseQueue.js, line 26 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x2zW0qzxE5G0L8mTc:-K8yy23MqX6KTiP8gyNJ:1245638893) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/test/www/jxcore/bv_tests/testPromiseQueue.js#L26)):*
100% agree. My mistake.

---

*[test/www/jxcore/bv_tests/testPromiseQueue.js, line 77 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x3_5FYhIL0t0TBYJL:-K8yy3mGUWdlUQ0qmiCL:-467915377) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/test/www/jxcore/bv_tests/testPromiseQueue.js#L77)):*
fixed

---

*[thali/NextGeneration/promiseQueue.js, line 13 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x3lUJuQxZyuq429jI:-K8yyE8qbCJ9PRH_LGht:-631264092) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/thali/NextGeneration/promiseQueue.js#L13)):*
Right now all of our file names are camel case but TCPServersManager which is just silly. We aren't even consistent with ourselves! So I fixed tcpServersManager to also be lower case.

If you want to come up with general naming conventions that aren't "just give files a camel case name" then I'm up for it but that should be filed as a separate bug.

---

*[thali/NextGeneration/promiseQueue.js, line 31 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x5f8mksgCumdBM-Iu:-K8yzImZBKpa49vfDxmy:657773377) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/thali/NextGeneration/promiseQueue.js#L31)):*
Because it feels less icky? I just hate "PromiseQueue.prototype.globalPromise;" I realize that Javascript will automatically make it null but it just feels so... icky. Old habits die hard? Old dogs don't learn new tricks? It makes me feel warm and fuzzy inside to intentionally initialize variables? I don't have a good argument here. I just like it. :(

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (62e056f)

**Comment by ThaliTester** [comment]
Test (Success) 56672827 build is completed (62e056f)

See https://github.com/ThaliTester/TestResults/tree/5667282762e056f__472_Promise_Queue_yaronyg/ for the logs

**Comment by vjrantal** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testPromiseQueue.js, line 7 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x26XpOMibJKumSiAB:-K8z6USG-juETj8dzz79:1165132615) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/test/www/jxcore/bv_tests/testPromiseQueue.js#L7)):*
What I meant was that above you have variable called `unhandledRejectionHandler`, but the name of the function starts `unHandled` (big H). Since this is so minor thing, no need to fix :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474)*

**Comment by ThaliTester** [comment]
Test 5667282762e056f(62e056f) has failed

See https://github.com/ThaliTester/TestResults/tree/5667282762e056f__472_Promise_Queue_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[test/www/jxcore/bv_tests/testPromiseQueue.js, line 7 \[r3\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474#-K8x26XpOMibJKumSiAB:-K9-Xinp18CC5nhxKfFU:1864588876) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/039a409328c5151f1754375a4b0ca9c6cbde51db/test/www/jxcore/bv_tests/testPromiseQueue.js#L7)):*
AAAAAHHHH!!! Sorry... I didn't see that. I will fix this in the mondo checkin for #317 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/474)*

**Comment by mattpodwysocki** [comment]
@yaronyg could we make this its own NPM module instead of keeping it internally?

**Comment by yaronyg** [comment]
@mattpodwysocki seems like a bunch of work for 90 lines of code. Is it really worth it?

**Comment by mattpodwysocki** [comment]
@yaronyg absolutely even if just one person finds it useful then it's well worth it. I've done the same with parts of RxJS throwing them out into the open and people have been using them with great success

**Comment by yaronyg** [comment]
@mattpodwysocki O.k. I'll file a bug on it. But we must not do this right now. If it isn't for March, it doesn't happen.

**Pull request merged**
