### PR TITLE
Closing Issue #383

### PR DESCRIPTION
**Pull request by mpodwysocki**
Fixing the merge errors from P4merge for Issue #383.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/384)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8dfd01f)

**Comment by mpodwysocki** [comment]
@vjrantal please review for the PR

**Comment by ThaliTester** [comment]
Test (Success) 53429675 build is completed (8dfd01f)

See https://github.com/ThaliTester/TestResults/tree/534296758dfd01f_Closing_Issue_#383_mpodwysocki/ for the logs

**Comment by ThaliTester** [comment]
Test 534296758dfd01f(8dfd01f) has failed

See https://github.com/ThaliTester/TestResults/tree/534296758dfd01f_Closing_Issue_#383_mpodwysocki/ for the fail logs

**Comment by mpodwysocki** [comment]
@obastemur what is the issue with CI here?  And how can I get to this to ensure that the URLs are accessible?

**Comment by obastemur** [comment]
@mattpodwysocki  Here is the correct link https://github.com/ThaliTester/TestResults/tree/534296758dfd01f_Closing_Issue_%23383_mpodwysocki 

Updated title generation with some more exceptions including this. Thanks

**Comment by vjrantal** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/384)*

**Pull request merged**
