### PR TITLE
Master 1274 trivial

### PR DESCRIPTION
**Pull request by yaronyg**
I'm not super happy checking this in but I think it's better to check it in and then later delete thaliPeerPoolOneAtATime it in favor of the fat policy manager when it's ready.

Please keep in mind that the thaliPeerPoolOneAtATime and testThaliPeerPoolOneAtATime are NOT meant to be production quality. There are quick hacks meant to unblock Rockwell that will be deleted when the
fat policy manager is ready.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1399)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ac5738a)

**Comment by yaronyg** [comment]
@chapko Note that this includes the changes from 1398. But the only substantive changes should be the thaliPeerPoolOneAtATime files. My goal in this review is primarily to see if you can catch anything obviously screaming wrong. Thanks!

**Comment by ThaliTester** [comment]
Test (Success) 90309748 build is completed (ac5738a)

See https://github.com/ThaliTester/TestResults/tree/90309748ac5738a_Master_1274_trivial_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 90309748ac5738a(ac5738a) has failed

See https://github.com/ThaliTester/TestResults/tree/90309748ac5738a_Master_1274_trivial_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4962c39)

**Comment by ThaliTester** [comment]
Test (Success) 90309748 build is completed (4962c39)

See https://github.com/ThaliTester/TestResults/tree/903097484962c39_Master_1274_trivial_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 903097484962c39(4962c39) has failed

See https://github.com/ThaliTester/TestResults/tree/903097484962c39_Master_1274_trivial_yaronyg/ for the fail logs

**Comment by chapko** [comment]
Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/mux/thaliTcpServersManager.js, line 292 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399#-KUrCZZr3JUxPcuo2Dwv:-KUrCZZr3JUxPcuo2Dww:b-5es5bu) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4962c39d13238748d4946fe04e1e2d90cffadc45/thali/NextGeneration/mux/thaliTcpServersManager.js#L292)):*
> ```JavaScript
>       return Promise.resolve(null);
>     }
>     createPeerListener.closeServer(this, peerServer.server, null, false);
> ```

It should return promise.

---

*[thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js, line 121 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399#-KUrGxJIG8lXAqXj5kfZ:-KUrGxJIG8lXAqXj5kf_:b-40hcoa) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4962c39d13238748d4946fe04e1e2d90cffadc45/thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js#L121)):*
> ```JavaScript
>     }
>     case 2: {
>       return peerAction.kill();
> ```

For bluetooth connection we enqueue new actions and they are started after the old ones are killed. But here we just kill new actions. Is it intended?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7c12bc7)

**Comment by yaronyg** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/mux/thaliTcpServersManager.js, line 292 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399#-KUrCZZr3JUxPcuo2Dwv:-KUssqlimnhD5vTNLck8:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4962c39d13238748d4946fe04e1e2d90cffadc45/thali/NextGeneration/mux/thaliTcpServersManager.js#L292)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> It should return promise.
</details>
Fixed

---

*[thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js, line 121 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399#-KUrGxJIG8lXAqXj5kfZ:-KUstRAvO_q2FOkf31yl:b-7t657n) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4962c39d13238748d4946fe04e1e2d90cffadc45/thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js#L121)):*
<details><summary><i>Previously, chapko (Eugene Chapko) wrote…</i></summary>
> For bluetooth connection we enqueue new actions and they are started after the old ones are killed. But here we just kill new actions. Is it intended?
</details>
The difference is that in wifi we allow for an unlimited number of parallel beacon requests and we even allow an unlimited number of replication requests for different peers. But if a single peer has more than two simultaneous replication requests against it we kill any new ones until one of the two old ones is completed. The reason we allow 2 instead of one has to do with some nasty race conditions which will be fixed in the 'real' policy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399)*

**Comment by ThaliTester** [comment]
Test (Success) 90309748 build is completed (7c12bc7)

See https://github.com/ThaliTester/TestResults/tree/903097487c12bc7_Master_1274_trivial_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 903097487c12bc7(7c12bc7) has failed

See https://github.com/ThaliTester/TestResults/tree/903097487c12bc7_Master_1274_trivial_yaronyg/ for the fail logs

**Comment by yaronyg** [comment]
@chapko I'm assigning this back to you for review since I didn't have a LGTM on your previous review.

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/mux/thaliTcpServersManager.js, line 292 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399#-KUrCZZr3JUxPcuo2Dwv:-KUv4xnkMQtsUhE-UTWF:b32w0x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4962c39d13238748d4946fe04e1e2d90cffadc45/thali/NextGeneration/mux/thaliTcpServersManager.js#L292)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Fixed
</details>
OK

---

*[thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js, line 121 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399#-KUrGxJIG8lXAqXj5kfZ:-KUv5-rDUTX3TD7xUbi9:b32w0x) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4962c39d13238748d4946fe04e1e2d90cffadc45/thali/NextGeneration/thaliPeerPool/thaliPeerPoolOneAtATime.js#L121)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> The difference is that in wifi we allow for an unlimited number of parallel beacon requests and we even allow an unlimited number of replication requests for different peers. But if a single peer has more than two simultaneous replication requests against it we kill any new ones until one of the two old ones is completed. The reason we allow 2 instead of one has to do with some nasty race conditions which will be fixed in the 'real' policy.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1399#-:-KUv540vJJ5xIwNWCyY2:bnfp4nl)*

**Pull request merged**
