### PR TITLE
Get basic end to end connections working

### PR DESCRIPTION
**Pull request by yaronyg**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/640)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (e63d34f)

**Comment by ThaliTester** [comment]
Test (Fail) 63289344 build is completed (e63d34f)

See https://github.com/ThaliTester/TestResults/tree/63289344e63d34f_Get_basic_end_to_end_connections_working_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 63289344 build is completed (e63d34f)

See https://github.com/ThaliTester/TestResults/tree/63289344e63d34f_Get_basic_end_to_end_connections_working_yaronyg/ for the logs

**Comment by vjrantal** [comment]
I am so happy that we got the E2E test finally working!

I merged the PR as is, but I was myself thinking will we need the "sleazy trick" with the connections without a peer now that we have the connection working with a peer? I left it there in case you @yaronyg  benefit from it when debugging TCP servers manager. If you think it can be removed one day, please do so.

**Pull request merged**
