### PR TITLE
Fix testThaliMobileNativeTest tests.

### PR DESCRIPTION
**Pull request by dersim-davaod**
Improve handling events in VirtualSocket.swift.

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1429)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0d9cf47)

**Comment by ThaliTester** [comment]
Test (Fail) 91020878 build is completed (0d9cf47)

See https://github.com/ThaliTester/TestResults/tree/910208780d9cf47_Fix_testThaliMobileNativeTest_tests__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1fece07)

**Comment by ThaliTester** [comment]
Test (Fail) 91020878 build is completed (1fece07)

See https://github.com/ThaliTester/TestResults/tree/910208781fece07_Fix_testThaliMobileNativeTest_tests__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1fece07)

**Comment by ThaliTester** [comment]
Test (Fail) 91020878 build is completed (1fece07)

See https://github.com/ThaliTester/TestResults/tree/910208781fece07_Fix_testThaliMobileNativeTest_tests__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9f3a884)

**Comment by ThaliTester** [comment]
Test (Success) 91020878 build is completed (9f3a884)

See https://github.com/ThaliTester/TestResults/tree/910208789f3a884_Fix_testThaliMobileNativeTest_tests__dersim-davaod/ for the logs

**Comment by ThaliTester** [comment]
Test 910208789f3a884(9f3a884) has failed

See https://github.com/ThaliTester/TestResults/tree/910208789f3a884_Fix_testThaliMobileNativeTest_tests__dersim-davaod/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1429#-:-KWjK0UXr8thbOK6-aVQ:bnfp4nl)*

**Comment by evabishchevich** [comment]
@dersim-davaod What are we going to do with that PR?

**Pull request closed without merging**
