### PR TITLE
Handling variable number of devices in CI and failing native tests

### PR DESCRIPTION
**Pull request by czyzm**
Change for #847

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/918)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5fdde63)

**Comment by ThaliTester** [comment]
Test (Success) 82147046 build is completed (5fdde63)

See https://github.com/ThaliTester/TestResults/tree/821470465fdde63_Handling_variable_number_of_devices_in_CI_and_failing_native_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 821470465fdde63(5fdde63) has failed

See https://github.com/ThaliTester/TestResults/tree/821470465fdde63_Handling_variable_number_of_devices_in_CI_and_failing_native_tests_czyzm/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d1155fd)

**Comment by ThaliTester** [comment]
Test (Success) 82147046 build is completed (d1155fd)

See https://github.com/ThaliTester/TestResults/tree/82147046d1155fd_Handling_variable_number_of_devices_in_CI_and_failing_native_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 82147046d1155fd(d1155fd) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/82147046d1155fd_Handling_variable_number_of_devices_in_CI_and_failing_native_tests_czyzm/ for the logs

**Comment by jareksl** [comment]
*[test/TestServer/UnitTestFramework.js, line 41 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918#-KPlzm57wuq8XOfv3Sgj:-KPlzm57wuq8XOfv3Sgk:b-ngc78m) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d1155fdaaef7cbee3b483eddb1ff67594048b3ba/test/TestServer/UnitTestFramework.js#L41)):*
> ```JavaScript
> util.inherits(UnitTestFramework, TestFramework);
> 
> UnitTestFramework.prototype.abortRun =
> ```

NB: This function is almost identical with finishRun() so maybe it would be worth to extract common part

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918)*

**Comment by jareksl** [comment]
*[test/www/jxcore/lib/thaliTape.js, line 316 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918#-KPm8mTekgrNMte1-jCT:-KPm8mTekgrNMte1-jCU:byly0a8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d1155fdaaef7cbee3b483eddb1ff67594048b3ba/test/www/jxcore/lib/thaliTape.js#L316)):*
> ```JavaScript
>   // On mobile, or outside of jxcore (some dev scenarios) we use
>   // the server-coordinated thaliTape
>   exports = thaliTape;
> ```

I wonder why we're introducing a global variable here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918)*

**Comment by jareksl** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918)*

**Comment by czyzm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/TestServer/UnitTestFramework.js, line 41 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918#-KPlzm57wuq8XOfv3Sgj:-KPq3OpYlEtv1AF_p3bC:bnwinim) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d1155fdaaef7cbee3b483eddb1ff67594048b3ba/test/TestServer/UnitTestFramework.js#L41)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary>
> NB: This function is almost identical with finishRun() so maybe it would be worth to extract common part
</details>
Will refactor it.

---

*[test/www/jxcore/lib/thaliTape.js, line 316 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918#-KPm8mTekgrNMte1-jCT:-KPpu_uPvvsm50v3DVAe:bex8p1l) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/d1155fdaaef7cbee3b483eddb1ff67594048b3ba/test/www/jxcore/lib/thaliTape.js#L316)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary>
> I wonder why we're introducing a global variable here?
</details>
It is a bit tricky. module.exports and exports initially reference the same object and can be used interchangeably. Such construction was probably introduced in order to keep the consistency (exports pointing to the same object as module.exports). I would change it a bit to keep the consistency but to make it more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3bd5c99)

**Comment by ThaliTester** [comment]
Test (Success) 82147046 build is completed (3bd5c99)

See https://github.com/ThaliTester/TestResults/tree/821470463bd5c99_Handling_variable_number_of_devices_in_CI_and_failing_native_tests_czyzm/ for the logs

**Comment by ThaliTester** [comment]
Test 821470463bd5c99(3bd5c99) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/821470463bd5c99_Handling_variable_number_of_devices_in_CI_and_failing_native_tests_czyzm/ for the logs

**Comment by jareksl** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918#-:-KPq8z9f_s7pFZl56-Uq:bnfp4nl)*

**Comment by czyzm** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/918)*

**Pull request merged**
