### PR TITLE
Mostly linting, maybe fixing

### PR DESCRIPTION
**Pull request by yaronyg**
UnitTest_app.js - These changes make Bluebird happy, otherwise it will
complain about "a promise was created in a handler but was not returned
from it"

testThaliManagerCoordinated - Linting

thaliSendNotificationBasedOnReplication - Added an assert on one of
our constructor arguments, covered a theoretical edge case where we
could end up with a negative time value. Clarified that one of the functions
handles an arg different than stated.

thaliManager - Linting

pouchDBGeneratior - Linting

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1248)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (43945da)

**Comment by yaronyg** [comment]
@andrew-aladev If this looks o.k. then please just merge it since in theory @vasilevskayaem and @chapko needs to deal with a failing test

@vasilevskayaem / @chapko - The change here is the equivalent of what Artyom did. But I can't give you any reason why it should fix the bug. :( I tried repro'ing this on the desktop with 15 nodes, 10 nodes, repeated runs, etc. The assert never repro'd.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5a81739)

**Comment by ThaliTester** [comment]
Test (Success) 87974041 build is completed (43945da)

See https://github.com/ThaliTester/TestResults/tree/8797404143945da_Mostly_linting__maybe_fixing_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 8797404143945da(43945da) has failed

See https://github.com/ThaliTester/TestResults/tree/8797404143945da_Mostly_linting__maybe_fixing_yaronyg/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 87974041 build is completed (5a81739)

See https://github.com/ThaliTester/TestResults/tree/879740415a81739_Mostly_linting__maybe_fixing_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 879740415a81739(5a81739) has failed

See https://github.com/ThaliTester/TestResults/tree/879740415a81739_Mostly_linting__maybe_fixing_yaronyg/ for the fail logs

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1248#-:-KTJ92SOEvr7blb_PT6B:bnfp4nl)*

**Comment by vasilevskayaem** [comment]
still can caught "write test" failure on wifi mode

**Pull request merged**
