### PR TITLE
Remove unnecessary getInstance call

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1718)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (c3f654c)

**Comment by ThaliTester** [comment]
Test 101023113 (c3f654c) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 101023113 build is completed (c3f654c)

See https://github.com/ThaliTester/TestResults/tree/101023113c3f654c_Remove_unnecessary_getInstance_call_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
Test fail fixed in https://github.com/thaliproject/Thali_CordovaPlugin/pull/1714

**Comment by czyzm** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1718)*

**Comment by czyzm** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1718#-:-KaGrfYqnmSeSqe-Tt-U:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1718#-:-KaIkwXaAd5Y52FAEn-8:bnfp4nl)*

**Pull request merged**
