### PR TITLE
Removed unnecessary import

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1639)

### CODE REVIEW

**Comment by evabishchevich** [comment]
PR #1639

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (0ff5ea8)

**Comment by ThaliTester** [comment]
Test 97920233 (0ff5ea8) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 97920233 build is completed (0ff5ea8)

See https://github.com/ThaliTester/TestResults/tree/979202330ff5ea8_Removed_unnecessary_import_evabishchevich/ for the logs

**Comment by evabishchevich** [comment]
Tests failed because of 
Exit code: null. Exit signal: SIGSEGV

**Comment by evabishchevich** [comment]
Created #1640

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (248158d)

**Comment by ThaliTester** [comment]
Test 97920233 (248158d) build started.

**Comment by ThaliTester** [comment]
Test 97920233 (248158d) build started.

**Comment by ThaliTester** [comment]
Test 97920233 (248158d) build started.

**Comment by ThaliTester** [comment]
Test 97920233 (248158d) build started.

**Comment by ThaliTester** [comment]
Test (Success) 97920233 build is completed (248158d)

See https://github.com/ThaliTester/TestResults/tree/97920233248158d_Removed_unnecessary_import_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 97920233248158d(248158d) has failed

See https://github.com/ThaliTester/TestResults/tree/97920233248158d_Removed_unnecessary_import_evabishchevich/ for the fail logs

**Pull request merged**
