### PR TITLE
Disable android-only tests on iOS platform

### PR DESCRIPTION
**Pull request by chapko**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1760)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c2804f2)

**Comment by ThaliTester** [comment]
Test 103295431 (c2804f2) build started.

**Comment by ThaliTester** [comment]
Test (Success) 103295431 build is completed (c2804f2)

See https://github.com/ThaliTester/TestResults/tree/103295431c2804f2_Disable_android-only_tests_on_iOS_platform_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 103295431c2804f2(c2804f2) has failed

See https://github.com/ThaliTester/TestResults/tree/103295431c2804f2_Disable_android-only_tests_on_iOS_platform_chapko/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1760#-:-KbQz8l0YpISslqMOLMJ:bnfp4nl)*

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1760#-:-KbUBRHxCeR7dXLug2Il:bnfp4nl)*

**Pull request merged**
