### PR TITLE
Fix calling t.end before assertion in testThaliMobileNative

### PR DESCRIPTION
**Pull request by mlesnic**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1916)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (af4ea1b)

**Comment by ThaliTester** [comment]
Test 127148139 (af4ea1b) build started.

**Comment by ThaliTester** [comment]
Test (Success) 127148139 build is completed (af4ea1b)

See https://github.com/ThaliTester/TestResults/tree/127148139af4ea1b_Fix_calling_t_end_before_assertion_in_testThaliMobileNative_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 127148139af4ea1b(af4ea1b) has failed

See https://github.com/ThaliTester/TestResults/tree/127148139af4ea1b_Fix_calling_t_end_before_assertion_in_testThaliMobileNative_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (fecb998)

**Comment by ThaliTester** [comment]
Test 127148139 (fecb998) build started.

**Comment by jareksl** [comment]
*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 1237 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1916#-KnJ9NNwgT4HeRGytoSi:-KnJ9NNwgT4HeRGytoSj:b-4rlolq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af4ea1b19c3cd4475f329e7e587710eb3a0cb1a7/test/www/jxcore/bv_tests/testThaliMobileNative.js#L1237)):*
> ```JavaScript
>           promises.push(new Promise(function (resolve, reject) {
>             Mobile('stopListeningForAdvertisements').callNative(function (err) {
>               if (!err) {
> ```

Be consistent. You're using shorthand for if-else statement for other cases,  use it also here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1916)*

**Comment by ThaliTester** [comment]
Test (Success) 127148139 build is completed (fecb998)

See https://github.com/ThaliTester/TestResults/tree/127148139fecb998_Fix_calling_t_end_before_assertion_in_testThaliMobileNative_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 127148139fecb998(fecb998) has failed

See https://github.com/ThaliTester/TestResults/tree/127148139fecb998_Fix_calling_t_end_before_assertion_in_testThaliMobileNative_mlesnic/ for the fail logs

**Comment by mlesnic** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/bv_tests/testThaliMobileNative.js, line 1237 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1916#-KnJ9NNwgT4HeRGytoSi:-KnK49LO2StoDTHBjGm3:bb6un1j) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/af4ea1b19c3cd4475f329e7e587710eb3a0cb1a7/test/www/jxcore/bv_tests/testThaliMobileNative.js#L1237)):*
<details><summary><i>Previously, jareksl (Jarosław Słota) wrote…</i></summary><blockquote>

Be consistent. You're using shorthand for if-else statement for other cases,  use it also here.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1916)*

**Comment by jareksl** [comment]
:lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1916#-:-KnKjLP4TwRv7EruJFdm:bg7igkv)*

**Comment by jareksl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1916)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1916#-:-KnL76RByYkoOq0-J1NB:bnfp4nl)*

**Pull request merged**
