### PR TITLE
Run coordinated desktop tests in CI

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/508)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1a47cc5)

**Comment by ThaliTester** [comment]
Test (Fail) 58099771 build is completed (1a47cc5)

See https://github.com/ThaliTester/TestResults/tree/580997711a47cc5_Run_coordinated_desktop_tests_in_CI_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 58099771 build is completed (1a47cc5)

See https://github.com/ThaliTester/TestResults/tree/580997711a47cc5_Run_coordinated_desktop_tests_in_CI_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (05d9cee)

**Comment by ThaliTester** [comment]
Test (Fail) 58099771 build is completed (05d9cee)

See https://github.com/ThaliTester/TestResults/tree/5809977105d9cee_Run_coordinated_desktop_tests_in_CI_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 58099771 build is completed (05d9cee)

See https://github.com/ThaliTester/TestResults/tree/5809977105d9cee_Run_coordinated_desktop_tests_in_CI_vjrantal/ for the logs

**Comment by vjrantal** [comment]
This one is waiting for the test server race condition fix https://github.com/thaliproject/Thali_CordovaPlugin/pull/511.

**Pull request closed without merging**
