### PR TITLE
Story 001 tompaana 345

### PR DESCRIPTION
**Pull request by tompaana**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/351)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2a05488)

**Comment by ThaliTester** [comment]
Test (Success) 52277365 build is completed (2a05488)

See https://github.com/ThaliTester/TestResults/tree/522773652a05488_Story_001_tompaana_345_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 522773652a05488(2a05488) has failed

See https://github.com/ThaliTester/TestResults/tree/522773652a05488_Story_001_tompaana_345_tompaana/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (15c0ad4)

**Comment by ThaliTester** [comment]
Test (Fail) 52277365 build is completed (15c0ad4)

See https://github.com/ThaliTester/TestResults/tree/5227736515c0ad4_Story_001_tompaana_345_tompaana/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ddd560d)

**Comment by ThaliTester** [comment]
Test (Fail) 52277365 build is completed (ddd560d)

See https://github.com/ThaliTester/TestResults/tree/52277365ddd560d_Story_001_tompaana_345_tompaana/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (58f1fb0)

**Comment by ThaliTester** [comment]
Test (Success) 52277365 build is completed (58f1fb0)

See https://github.com/ThaliTester/TestResults/tree/5227736558f1fb0_Story_001_tompaana_345_tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 5227736558f1fb0(58f1fb0) has failed

See https://github.com/ThaliTester/TestResults/tree/5227736558f1fb0_Story_001_tompaana_345_tompaana/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/351)*

**Pull request merged**
