### PR TITLE
#317 #378 Replication and life cycle

### PR DESCRIPTION
**Pull request by yaronyg**
Adds spec for handling replication as well as life cycle issues.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/482)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8138a64)

**Comment by ThaliTester** [comment]
Test (Success) 56818254 build is completed (8138a64)

See https://github.com/ThaliTester/TestResults/tree/568182548138a64_Replication_and_life_cycle_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 568182548138a64(8138a64) has failed

See https://github.com/ThaliTester/TestResults/tree/568182548138a64_Replication_and_life_cycle_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[thali/NextGeneration/makeIntoCloseAllServer.js, line 27 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K8y5aIDyS6WBycpD0IZ:-K8y5aIDyS6WBycpD0I_:-684632929) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8138a64cfc74efce82cf6df87cc0fa1523232fbe/thali/NextGeneration/makeIntoCloseAllServer.js#L27)):*
Seems that a logging statement is missing from there..?

---

*[thali/NextGeneration/makeIntoCloseAllServer.js, line 39 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K8y5PeG_XuCA6RifwAc:-K8y5PeG_XuCA6RifwAd:-1970337791) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8138a64cfc74efce82cf6df87cc0fa1523232fbe/thali/NextGeneration/makeIntoCloseAllServer.js#L39)):*
The function `close` is asynchronous and takes an optional callback. There might be value in making `closeAll` also take an optional callback and pass that to `close`.

---

*[thali/NextGeneration/thaliPullReplicationFromNotification.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K8yKkMGLx-O8O19FuP7:-K8yKkMGLx-O8O19FuP8:67877021) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8138a64cfc74efce82cf6df87cc0fa1523232fbe/thali/NextGeneration/thaliPullReplicationFromNotification.js#L3)):*
Will there be something like a "replication manager" on top of this module that is the new "Thali public API for replication use cases"?

---

*[thali/NextGeneration/thaliReplicationPeerAction.js, line 129 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K8yC0ivtSxNFlE8O_uh:-K8yC0iwsEvQjHmAmhLS:-1032131667) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8138a64cfc74efce82cf6df87cc0fa1523232fbe/thali/NextGeneration/thaliReplicationPeerAction.js#L129)):*
This parameter could be explained in a bit more detail since it wasn't very clear after first read what is expected to be passed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0458528)

**Comment by yaronyg** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[thali/NextGeneration/makeIntoCloseAllServer.js, line 27 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K8y5aIDyS6WBycpD0IZ:-K8zQq1-R_PdJ9e__dCE:1186110075) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8138a64cfc74efce82cf6df87cc0fa1523232fbe/thali/NextGeneration/makeIntoCloseAllServer.js#L27)):*
This is just a "spec", it's not intended as running code yet. That's why there are no tests yet.

---

*[thali/NextGeneration/makeIntoCloseAllServer.js, line 39 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K8y5PeG_XuCA6RifwAc:-K8zSEgiHIJeI5Tg8y3k:771756655) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8138a64cfc74efce82cf6df87cc0fa1523232fbe/thali/NextGeneration/makeIntoCloseAllServer.js#L39)):*
An excellent idea

---

*[thali/NextGeneration/thaliPullReplicationFromNotification.js, line 3 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K8yKkMGLx-O8O19FuP7:-K9-W5pCrYiqYWxu8w4I:673058947) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8138a64cfc74efce82cf6df87cc0fa1523232fbe/thali/NextGeneration/thaliPullReplicationFromNotification.js#L3)):*
And there went my day. :) There is now. Called thaliReplicationManager. And as a consequence of it's creation I had to combine my various PRs all together. The reason is that creating it proved to me that the current structure sucked badly and could be simplified. But that meant bringing my various changes back together so I could make the changes everywhere.

---

*[thali/NextGeneration/thaliReplicationPeerAction.js, line 129 \[r1\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K8yC0ivtSxNFlE8O_uh:-K9-WtNqpsW1KAWmM3R9:-1994014083) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8138a64cfc74efce82cf6df87cc0fa1523232fbe/thali/NextGeneration/thaliReplicationPeerAction.js#L129)):*
Your wish is my command. :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by yaronyg** [comment]
Putting in the new thaliReplicationManager class to bring it all together, per @vjrantal's suggestion, exposed a bunch of nasty bugs and inefficiencies that cleaning up required bring together my various PRs. So now we have this mega PR. :(

**Comment by ThaliTester** [comment]
Test (Success) 56818254 build is completed (0458528)

See https://github.com/ThaliTester/TestResults/tree/568182540458528__317__378_Replication_and_life_cycle_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 568182540458528(0458528) has failed

See https://github.com/ThaliTester/TestResults/tree/568182540458528__317__378_Replication_and_life_cycle_yaronyg/ for the fail logs

**Comment by vjrantal** [comment]
Reviewed 16 of 17 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[thali/NextGeneration/thaliMobile.js, line 174 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91KgvHCgA_6Y3_UiMJ:-K91KgvIa1cieh77PZ9v:-52111435) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliMobile.js#L174)):*
I wonder would it make more sense to implement this using https://github.com/jxcore/jxcore-cordova#mobilegetconnectionstatus?

The reason I brought it up is that if there is a case where a Thali app starts while all radios are on and there is nobody toggling them for a long time (or ever). Then, we may even never get any changed-events and this call might wait forever.

---

*[thali/NextGeneration/thaliReplicationManager.js, line 13 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91NurOrGiRMimmGYvr:-K91NurOrGiRMimmGYvs:306304800) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliReplicationManager.js#L13)):*
It might be nice if only the database is a mandatory parameter, but everything else optional. Or, would it be impossible to implement good defaults for the rest of the parameters if they aren't given?

---

*[thali/NextGeneration/thaliReplicationManager.js, line 17 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91OHX4sjiINh7jzqdq:-K91OHX5rRLza0G4H5pH:1731435790) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliReplicationManager.js#L17)):*
This parameter probably requires more explanation. Let's say someone outside of Thali comes and just wants to get some basic replication up and running. How would we explain to them what this router must contain and why they should pass it?

---

*[thali/NextGeneration/thaliReplicationManager.js, line 55 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91PC8rwQSge2ul9z9V:-K91PC8rwQSge2ul9z9W:-741513743) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliReplicationManager.js#L55)):*
Similar comment as above, i.e., could all parameters to `start` be optional?

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 269 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91Q4BwnMrGk9zjYyLO:-K91Q4BwnMrGk9zjYyLP:-1978336010) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliWifiInfrastructure.js#L269)):*
Hmm.. `Mobile.getConnectionStatus` is a function implemented in jxcore-cordova that isn't really used in desktop scenarios. Do you mean that on desktop, we would just mock that function and on mobile, it would work as expected?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 250 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91qsZJx6q_A5FRLexZ:-K91qsZJx6q_A5FRLex_:1016672310) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliWifiInfrastructure.js#L250)):*
Can you remind me why the Wifi infrastructure code must hook into the `nonTCPPeerAvailabilityChangedEvent` when we are on mobile devices?

Also, if I understood right, the main point of `discoveryAdvertisingStateUpdateEvent` is that it is fired if network conditions change and the Wifi code itself must turn off listening or advertising. However, since the Wifi code also fires `networkChangedWifi` is that discovery event necessary or could the upper layers make right choices just based on `networkChangedWifi`?

I guess what I am thinking is that what use case would be impossible to implement if the Wifi code would not ever fire `discoveryAdvertisingStateUpdateEvent`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (030e5cb)

**Comment by ThaliTester** [comment]
Test (Fail) 56818254 build is completed (030e5cb)

See https://github.com/ThaliTester/TestResults/tree/56818254030e5cb__317__378_Replication_and_life_cycle_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8e9b001)

**Comment by ThaliTester** [comment]
Test (Fail) 56818254 build is completed (8e9b001)

See https://github.com/ThaliTester/TestResults/tree/568182548e9b001__317__378_Replication_and_life_cycle_yaronyg/ for the logs

**Comment by yaronyg** [comment]
Review status: 13 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[thali/NextGeneration/thaliMobile.js, line 174 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91KgvHCgA_6Y3_UiMJ:-K933XMp4DZiH7vIJmAh:860710926) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliMobile.js#L174)):*
So there was supposed to be an explicit requirement that when the first call subscription to the event was received that it would fire its current state. I just updated thaliMobileNativeWrapper to make this clear and put in a pointer to that in thaliWifiInfrastructure.js.

---

*[thali/NextGeneration/thaliReplicationManager.js, line 13 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91NurOrGiRMimmGYvr:-K933sfhuBCcGNywlEVh:1286551271) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliReplicationManager.js#L13)):*
thaliPeerPoolInterface - Yeah, we can do that, but boy will we regret it. :)
ecdhForLocalDevice - That one we can't default to since the entire system depends on that value being constant across invocations.

---

*[thali/NextGeneration/thaliReplicationManager.js, line 17 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91OHX4sjiINh7jzqdq:-K934a8baO4LqjMZ5s3c:-1951146751) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliReplicationManager.js#L17)):*
I just put in some new text. Let me know if it works for you.

---

*[thali/NextGeneration/thaliReplicationManager.js, line 55 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91PC8rwQSge2ul9z9V:-K934nvro6QH1cCIOUo1:2111495323) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliReplicationManager.js#L55)):*
Actually I want to simplify it first to being one argument. And since it can be empty it is effectively optional so I have marked it as such.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 250 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91qsZJx6q_A5FRLexZ:-K935ov5ONWB6gLLM9OT:1942933310) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliWifiInfrastructure.js#L250)):*
nonTCPPeerAvailabilityChangedEvent - Because it's a typo? :) Sorry. It's supposed to be networkChangedNonTCP.

discoveryAdvertisingStateUpdateEvent - This is wider than networkChangedWifi since the advertising state could have been changed by an API call, not a network event. So this event allows the app to know that someone, somewhere, has turned off/on advertising. For example, the app may show a UX when it is discoverable and if discovery is turned off then it wants a notification so it can remove that UX. Note that I've been suspicious of the discoveryAdvertisingStateUpdate event both here and in thaliMobileNativeWrapper. So we should feel free to leave it unimplemented for now and see if it matters.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 269 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91Q4BwnMrGk9zjYyLO:-K937LKcEWJl7ElxTa6B:121701135) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliWifiInfrastructure.js#L269)):*
In an ideal world we would use some native code to check if WiFi is actually on or not. I also want a pony. So when we aren't on mobile we can just make this a thunk. Please see the new text in the js file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by vjrantal** [comment]
Reviewed 1 of 17 files at r2.
Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[thali/NextGeneration/thaliMobile.js, line 174 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91KgvHCgA_6Y3_UiMJ:-K967SdTaYB68t0rt_X0:-486649063) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliMobile.js#L174)):*
Got it.

I am recapping here just to check I understood correctly. The EventEmitter itself (for example, `ThaliWifiInfrastructure`) listens for https://nodejs.org/api/events.html#events_event_newlistener to know when someone subscribes to this event and on the first subscription, fires the status based on a call similar to `Mobile.getConnectionStatus`. The "first" in this context is defined as first since the app startup and the event doesn't have to be re-fired in case subscription goes to 0 and then back to 1.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 250 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91qsZJx6q_A5FRLexZ:-K964cscZB71OOgdVGzb:1218732720) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliWifiInfrastructure.js#L250)):*
Got it. After reading about `networkChangedNonTCP` I was reminded that the Wifi infrastructure needs to subscribe to it to know about the BSSID changes, because it wouldn't get that information otherwise. I think other than BSSID changes, there is no use for this event in the Wifi layer.

I think we could leave out the `discoveryAdvertisingStateUpdate` event in the *first iteration* since the app developer can handle these cases in their own code. For example, if there is a UX module somewhere in the app, that module can "internally" pass information about user's actions to the rest of the app. I do recognize that having the event would be sometimes convenient, but not mandatory for basic functionality.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by vjrantal** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 267 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K977MfxTnZXleqWSfQy:-K977MfxTnZXleqWSfQz:-1415135195) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliWifiInfrastructure.js#L267)):*
By the way, if you don't see this as nit-picking and too much work, I'd propose changing the typing of bluetooth-related variables to be bluetooth or Bluetooth. That is, not using big T in the middle. I think this aligns better how the term is written elsewhere and in other places in our code-base.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by yaronyg** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[thali/NextGeneration/thaliMobile.js, line 174 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91KgvHCgA_6Y3_UiMJ:-K987P-CO3026eR5aIE9:1131518747) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliMobile.js#L174)):*
Absolutely correct.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 267 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K977MfxTnZXleqWSfQy:-K988DMRQb9dwGX8kgW-:-353105852) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliWifiInfrastructure.js#L267)):*
I fixed this but in 417 (it was easier for me) so I'll check this in when I check in 417.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by vjrantal** [comment]
Reviewed 1 of 17 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by yaronyg** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 250 \[r2\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K91qsZJx6q_A5FRLexZ:-K99NFyMYxhoN9Y0umFm:-2000898700) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/045852813914cd929c3fa507239b384e7b96f5e9/thali/NextGeneration/thaliWifiInfrastructure.js#L250)):*
Actually I would think that networkChangedNonTCP would be needed by wifi for two reasons:

1 - To know if the WiFi radio is on or not
2 - To find out the BSSID

Agreed with discoveryAdvertisingStateUpdate. Let's omit and see what blows up.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[thali/NextGeneration/thaliMobile.js, line 522 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K9C2SNS1aOuJKy8JDbG:-K9C2SNS1aOuJKy8JDbH:-1490987249) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8e9b0012c9aa31e2e2a8f9e291d48b2a7f03c342/thali/NextGeneration/thaliMobile.js#L522)):*
Was it intentional that we would export a property called `emitter`?

Or, should we export the `ThaliMobile` object which would inherit from `EventEmitter` and would be used to subscribe?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by vjrantal** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[thali/NextGeneration/thaliMobile.js, line 522 \[r4\]](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482#-K9C2SNS1aOuJKy8JDbG:-K9C3sfJ52mdBJD9YZWQ:2110882295) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/8e9b0012c9aa31e2e2a8f9e291d48b2a7f03c342/thali/NextGeneration/thaliMobile.js#L522)):*
After reading the entire file more carefully, realized that all the functions were specifies as "static methods" rather than methods of a new'able object. This makes sense since the idea is that there can be only one instance of `thaliMobile`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/482)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e6f5c3b)

**Comment by ThaliTester** [comment]
Test (Success) 56818254 build is completed (e6f5c3b)

See https://github.com/ThaliTester/TestResults/tree/56818254e6f5c3b__317__378_Replication_and_life_cycle_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
Test 56818254e6f5c3b(e6f5c3b) has failed

See https://github.com/ThaliTester/TestResults/tree/56818254e6f5c3b__317__378_Replication_and_life_cycle_yaronyg/ for the fail logs

**Pull request merged**
