### PR TITLE
Add check if radio is on before starting the advertising and listening

### PR DESCRIPTION
**Pull request by evabishchevich**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1769)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b3b02b3)

**Comment by ThaliTester** [comment]
Test 103941844 (b3b02b3) build started.

**Comment by ThaliTester** [comment]
Test (Success) 103941844 build is completed (b3b02b3)

See https://github.com/ThaliTester/TestResults/tree/103941844b3b02b3_Add_check_if_radio_is_on_before_starting_the_advertising_and_listening_evabishchevich/ for the logs

**Comment by ThaliTester** [comment]
Test 103941844b3b02b3(b3b02b3) has failed

See https://github.com/ThaliTester/TestResults/tree/103941844b3b02b3_Add_check_if_radio_is_on_before_starting_the_advertising_and_listening_evabishchevich/ for the fail logs

**Comment by evabishchevich** [comment]
Connected with #1743

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1769#-:-KbyjA1gjj2WiVw9kcll:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1769#-:-KbzsCh6lXBSk52sfW5K:bnfp4nl)*

**Pull request merged**
