### PR TITLE
#1601

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1610)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (c47eb1f)

**Comment by ThaliTester** [comment]
Test 96532753 (c47eb1f) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96532753 build is completed (c47eb1f)

See https://github.com/ThaliTester/TestResults/tree/96532753c47eb1f__1601_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (9de641b)

**Comment by ThaliTester** [comment]
Test 96532753 (9de641b) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96532753 build is completed (9de641b)

See https://github.com/ThaliTester/TestResults/tree/965327539de641b__1601_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 965327539de641b(9de641b) has failed

See https://github.com/ThaliTester/TestResults/tree/965327539de641b__1601_vasilevskayaem/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (71f1bf1)

**Comment by ThaliTester** [comment]
Test 96532753 (71f1bf1) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96532753 build is completed (71f1bf1)

See https://github.com/ThaliTester/TestResults/tree/9653275371f1bf1__1601_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (de9d535)

**Comment by ThaliTester** [comment]
Test 96532753 (de9d535) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 96532753 build is completed (de9d535)

See https://github.com/ThaliTester/TestResults/tree/96532753de9d535__1601_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (164b9eb)

**Comment by ThaliTester** [comment]
Test 96532753 (164b9eb) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96532753 build is completed (164b9eb)

See https://github.com/ThaliTester/TestResults/tree/96532753164b9eb__1601_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 96532753164b9eb(164b9eb) has failed

See https://github.com/ThaliTester/TestResults/tree/96532753164b9eb__1601_vasilevskayaem/ for the fail logs

**Comment by evabishchevich** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610#-:-KYJaWmlEX-tdVvLUaa_:bnfp4nl)*

**Comment by larryonoff** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/lib/testUtils.js, line 62 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610#-KYJilMO0-unGxsErHvf:-KYJilMO7MWLsxhEdfKq:b6r2k1u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/164b9ebd329d1029a49825ac03d00d7c5603065b/test/www/jxcore/lib/testUtils.js#L62)):*
> ```JavaScript
>   }
>   return new Promise(function (resolve, reject) {
>     Mobile['toggleWiFi'](value, function (error) {
> ```

is it correct way of calling native methods ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610)*

**Comment by larryonoff** [comment]
@andrew-aladev please review

**Comment by andrew-aladev** [comment]
Reviewed 2 of 5 files at r1, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 62 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610#-KYJilMO0-unGxsErHvf:-KYNoSNF1d-vxmtJk9gP:bwv3yeo) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/164b9ebd329d1029a49825ac03d00d7c5603065b/test/www/jxcore/lib/testUtils.js#L62)):*
<details><summary><i>Previously, larryonoff (larryonoff) wrote…</i></summary><blockquote>

is it correct way of calling native methods ?
</blockquote></details>

We want Mobile.toggleWiFi here.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 732 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610#-KYNohfL1QYbu9mUPVNH:-KYNohfLATdHezhkhh6J:bqujbyh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/164b9ebd329d1029a49825ac03d00d7c5603065b/thali/NextGeneration/thaliMobileNativeWrapper.js#L732)):*
> ```JavaScript
> 
>   return gPromiseQueue.enqueue(function (resolve, reject) {
>     Mobile['toggleWiFi'](value, function (error) {
> ```

Here too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (da2ef75)

**Comment by vasilevskayaem** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/www/jxcore/lib/testUtils.js, line 62 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610#-KYJilMO0-unGxsErHvf:-KYNvBRn3_oclhPO9B2-:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/164b9ebd329d1029a49825ac03d00d7c5603065b/test/www/jxcore/lib/testUtils.js#L62)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary><blockquote>

We want Mobile.toggleWiFi here.
</blockquote></details>

Done.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 732 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610#-KYNohfL1QYbu9mUPVNH:-KYNvFHn8O3EhGiaV7ii:b-896fix) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/164b9ebd329d1029a49825ac03d00d7c5603065b/thali/NextGeneration/thaliMobileNativeWrapper.js#L732)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1610#-:-KYNvfYUBqhPeySRBs71:bnfp4nl)*

**Comment by ThaliTester** [comment]
Test 96532753 (da2ef75) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96532753 build is completed (da2ef75)

See https://github.com/ThaliTester/TestResults/tree/96532753da2ef75__1601_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 96532753da2ef75(da2ef75) has failed

See https://github.com/ThaliTester/TestResults/tree/96532753da2ef75__1601_vasilevskayaem/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4acc906)

**Comment by ThaliTester** [comment]
Test 96532753 (4acc906) build started.

**Comment by ThaliTester** [comment]
Test (Success) 96532753 build is completed (4acc906)

See https://github.com/ThaliTester/TestResults/tree/965327534acc906__1601_vasilevskayaem/ for the logs

**Comment by ThaliTester** [comment]
Test 965327534acc906(4acc906) has failed

See https://github.com/ThaliTester/TestResults/tree/965327534acc906__1601_vasilevskayaem/ for the fail logs

**Pull request merged**
