### PR TITLE
Enable tests that were disabled due to #1600, #1618 and #1767

### PR DESCRIPTION
**Pull request by mlesnic**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1886)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (80258fe)

**Comment by ThaliTester** [comment]
Test 123025163 (80258fe) build started.

**Comment by ThaliTester** [comment]
Test (Success) 123025163 build is completed (80258fe)

See https://github.com/ThaliTester/TestResults/tree/12302516380258fe_Enable_tests_that_were_disabled_due_to__1600___1618_and__1767_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 12302516380258fe(80258fe) has failed

See https://github.com/ThaliTester/TestResults/tree/12302516380258fe_Enable_tests_that_were_disabled_due_to__1600___1618_and__1767_mlesnic/ for the fail logs

**Comment by mlesnic** [comment]
It looks like tests related to #1618 passes even without #1868 resolved, but anyway, we should wait with this PR after PR for #1868 will be accepted.

**Comment by mlesnic** [comment]
Jxcore-cordova was updated to 0.1.12 so we are free to merge this PR.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (056ff77)

**Comment by ThaliTester** [comment]
Test 123025163 (056ff77) build started.

**Comment by ThaliTester** [comment]
Test (Success) 123025163 build is completed (056ff77)

See https://github.com/ThaliTester/TestResults/tree/123025163056ff77_Enable_tests_that_were_disabled_due_to__1600___1618_and__1767_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 123025163056ff77(056ff77) has failed

See https://github.com/ThaliTester/TestResults/tree/123025163056ff77_Enable_tests_that_were_disabled_due_to__1600___1618_and__1767_mlesnic/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1886)*

**Comment by yaronyg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1886#-:-Km0nvf8U6P0shDhESNO:bnfp4nl)*

**Comment by jareksl** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1886#-:-Km0oQyqVvP4hDizvXF4:bnfp4nl)*

**Comment by jareksl** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1886)*

**Pull request merged**
