### PR TITLE
Address test setup issue

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/506)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (3a29850)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (99148df)

**Comment by ThaliTester** [comment]
Test (Success) 57972094 build is completed (3a29850)

See https://github.com/ThaliTester/TestResults/tree/579720943a29850_Address_test_setup_issue_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 57972094 build is completed (99148df)

See https://github.com/ThaliTester/TestResults/tree/5797209499148df_Address_test_setup_issue_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (912017a)

**Comment by ThaliTester** [comment]
Test 579720943a29850(3a29850) has failed

See https://github.com/ThaliTester/TestResults/tree/579720943a29850_Address_test_setup_issue_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 57972094 build is completed (912017a)

See https://github.com/ThaliTester/TestResults/tree/57972094912017a_Address_test_setup_issue_vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5797209499148df(99148df) has failed

See https://github.com/ThaliTester/TestResults/tree/5797209499148df_Address_test_setup_issue_vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 57972094912017a(912017a) has failed

See https://github.com/ThaliTester/TestResults/tree/57972094912017a_Address_test_setup_issue_vjrantal/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/506)*

**Pull request merged**
