### PR TITLE
#1190 Added Bluebird debuggability switcher

### PR DESCRIPTION
**Pull request by artemjackson**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1197)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6b1b86b)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5a9e832)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (9ada2da)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (08dfc97)

**Comment by andrew-aladev** [comment]
Reviewed 3 of 4 files at r1, 3 of 3 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/runCoordinatedTests.js, line 130 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1197#-KSkLfSEwzRkxyraVymO:-KSkLfSEwzRkxyraVymP:brcoiy1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ada2da9fdfdb844518dc20d2528675ac596e3cc/test/www/jxcore/runCoordinatedTests.js#L130)):*
> ```JavaScript
>   })
> });
> var instanceOpts = objectAssign({}, { env: instanceEnv });
> ```

This variable is unused.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1197)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1197#-:-KSkMCI8wuU8oFz5WhSw:bnfp4nl)*

**Comment by artemjackson** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/www/jxcore/runCoordinatedTests.js, line 130 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1197#-KSkLfSEwzRkxyraVymO:-KSkMV-zDLgvmBkeCe0S:b-886gsx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/9ada2da9fdfdb844518dc20d2528675ac596e3cc/test/www/jxcore/runCoordinatedTests.js#L130)):*
<details><summary><i>Previously, andrew-aladev (Andrew Aladjev) wrote…</i></summary>
> This variable is unused.
</details>
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1197)*

**Comment by ThaliTester** [comment]
Test (Success) 87092945 build is completed (6b1b86b)

See https://github.com/ThaliTester/TestResults/tree/870929456b1b86b__1190_Added_Bluebird_debuggability_switcher_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 87092945 build is completed (5a9e832)

See https://github.com/ThaliTester/TestResults/tree/870929455a9e832__1190_Added_Bluebird_debuggability_switcher_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 87092945 build is completed (9ada2da)

See https://github.com/ThaliTester/TestResults/tree/870929459ada2da__1190_Added_Bluebird_debuggability_switcher_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 5. task. (8a5466f)

**Comment by ThaliTester** [comment]
Test 870929456b1b86b(6b1b86b) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/870929456b1b86b__1190_Added_Bluebird_debuggability_switcher_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 87092945 build is completed (08dfc97)

See https://github.com/ThaliTester/TestResults/tree/8709294508dfc97__1190_Added_Bluebird_debuggability_switcher_artemjackson/ for the logs

**Comment by ThaliTester** [comment]
Test 8709294508dfc97(08dfc97) has failed

See https://github.com/ThaliTester/TestResults/tree/8709294508dfc97__1190_Added_Bluebird_debuggability_switcher_artemjackson/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Fail) 87092945 build is completed (8a5466f)

See https://github.com/ThaliTester/TestResults/tree/870929458a5466f__1190_Added_Bluebird_debuggability_switcher_artemjackson/ for the logs

**Pull request merged**
