### PR TITLE
#898 Updates to thaliWifiInfrastructure

### PR DESCRIPTION
**Pull request by chapko**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1103)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f3366c4)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (5ecb88c)

**Comment by ThaliTester** [comment]
Test (Fail) 86147834 build is completed (f3366c4)

See https://github.com/ThaliTester/TestResults/tree/86147834f3366c4__898_Updates_to_thaliWifiInfrastructure_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86147834 build is completed (5ecb88c)

See https://github.com/ThaliTester/TestResults/tree/861478345ecb88c__898_Updates_to_thaliWifiInfrastructure_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 861478345ecb88c(5ecb88c) has failed

See https://github.com/ThaliTester/TestResults/tree/861478345ecb88c__898_Updates_to_thaliWifiInfrastructure_chapko/ for the fail logs

**Comment by artemjackson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 8 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSCHxHocyHIhgx2Iz0G:-KSCHxHocyHIhgx2Iz0H:b3mwgxb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5ecb88ca5e61fa95fabec0ac1fe0e684a56f83e7/thali/NextGeneration/thaliWifiInfrastructure.js#L8)):*
> ```JavaScript
> var url = require('url');
> 
> var Promise = require('lie');
> ```

go `bluebird` :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (7f75dc8)

**Comment by ThaliTester** [comment]
Test (Success) 86147834 build is completed (7f75dc8)

See https://github.com/ThaliTester/TestResults/tree/861478347f75dc8__898_Updates_to_thaliWifiInfrastructure_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 861478347f75dc8(7f75dc8) has failed

See https://github.com/ThaliTester/TestResults/tree/861478347f75dc8__898_Updates_to_thaliWifiInfrastructure_chapko/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4380252)

**Comment by ThaliTester** [comment]
Test (Fail) 86147834 build is completed (4380252)

See https://github.com/ThaliTester/TestResults/tree/861478344380252__898_Updates_to_thaliWifiInfrastructure_chapko/ for the logs

**Comment by yaronyg** [comment]
Please humor me and switch usn.js to be prototype based and then :lgtm: 

---

Reviewed 5 of 6 files at r1, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[.jshintrc, line 14 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSDYZJ3JnikE-sUo3jo:-KSDYZJ4Ss2N_BV60-Ap:b-tk80wf) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/.jshintrc#L14)):*
> ```JSON
>   "expr": true,
>   "nonew": true,
>   "singleGroups": false,
> ```

NB: So I always liked this rule because it showed me when I didn't really understand how an operator worked. Why do you want to turn it off?

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 93 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSD_J30ZpkzZPsCj-28:-KSD_J30ZpkzZPsCj-29:ba8w1ut) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/thali/NextGeneration/thaliWifiInfrastructure.js#L93)):*
> ```JavaScript
>   var serverOptions = {
>     adInterval: thaliConfig.SSDP_ADVERTISEMENT_INTERVAL,
>     udn: thaliConfig.SSDP_NT,
> ```

NB: We shouldn't have the , at the end, I'm surprised the linter didn't complain

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 223 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSD_rNYAUo34mqbRIE5:-KSD_rNYAUo34mqbRIE6:b-tjhzzq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/thali/NextGeneration/thaliWifiInfrastructure.js#L223)):*
> ```JavaScript
> };
> 
> ThaliWifiInfrastructure.prototype._isOwnMessage = function (data) {
> ```

NB: We typically want to define functions before they are used. Eventually the linter will scold you about this.

---

*[thali/NextGeneration/utils/usn.js, line 23 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSDZPXaSlUUELJzbuwS:-KSDZPXaSlUUELJzbuwT:b-kxexi1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/thali/NextGeneration/utils/usn.js#L23)):*
> ```JavaScript
>   /**
>    * @param {string} usn
>    * @returns {{peerIdentifier: string, generation: number}}
> ```

NB: Why does this have two brackets around it instead of one?

---

*[thali/NextGeneration/utils/usn.js, line 27 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSDZjwhU0LL8dpejvqL:-KSDZjwhU0LL8dpejvqM:bnynsgb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/thali/NextGeneration/utils/usn.js#L27)):*
> ```JavaScript
>    * 'data:'), has incorrect number of segments or its generation is not a number.
>    */
>   parse: function (usn) {
> ```

We generally prefer using prototypes rather than the class like structure. E.g. declare USN and then declare USN.prototype.parse. It's not so much a question of correctness (since either works and both have their pluses and minuses) but consistency with the code so devs always know what to expect when they read our code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-:-KSDcSqrgKwf_MgBQiu5:bai3b59)*

**Comment by yaronyg** [comment]
Arg sorry, not prototype!!! Each function in usn.js should be defined directly on the USN object as in USN.parse. I clearly didn't get enough sleep last night.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (a13d096)

**Comment by chapko** [comment]
Review status: 3 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[.jshintrc, line 14 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSDYZJ3JnikE-sUo3jo:-KSGAN1e8JZWfVEkogD-:bfs3tc1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/.jshintrc#L14)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: So I always liked this rule because it showed me when I didn't really understand how an operator worked. Why do you want to turn it off?
</details>
1. Sometimes code is just more readable with extra parens.
2. There are cases when it is required, like after `return` (because of ASI in js):

    ```
        return (
            !localDocString &&
            newRemoteDocStrings.length === 0 &&
            oldRemoteDocStrings.length === 0
        );
    ```

3. There are already many places with unnecessary grouping (in test/www/jxcore I've found 10 occurrences)

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 8 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSCHxHocyHIhgx2Iz0G:-KSCLLEEOGV5OsmI0Pm5:b-ou1yi4) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/5ecb88ca5e61fa95fabec0ac1fe0e684a56f83e7/thali/NextGeneration/thaliWifiInfrastructure.js#L8)):*
<details><summary><i>Previously, artemjackson (Artyom Stepanishchev) wrote…</i></summary>
> go `bluebird` :)
</details>
Yeah, I would totally go for it, but we already have separated PR for this thing

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 93 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSD_J30ZpkzZPsCj-28:-KSGKWkRPEnZT2ml5B-k:bxqg647) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/thali/NextGeneration/thaliWifiInfrastructure.js#L93)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: We shouldn't have the , at the end, I'm surprised the linter didn't complain
</details>
Both linters were silent about this, but I've updated styling to make it consistent

---

*[thali/NextGeneration/thaliWifiInfrastructure.js, line 223 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSD_rNYAUo34mqbRIE5:-KSGK6EUUmadS2m3qNY9:b6t83f1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/thali/NextGeneration/thaliWifiInfrastructure.js#L223)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: We typically want to define functions before they are used. Eventually the linter will scold you about this.
</details>
This is a method of `ThaliWifiInfrastructure` and all methods here are defined in the order of execution (more or less). I prefer to be consistent

---

*[thali/NextGeneration/utils/usn.js, line 23 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSDZPXaSlUUELJzbuwS:-KSGLBj6-YjDgA5RnoUd:b-62tybk) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/thali/NextGeneration/utils/usn.js#L23)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Why does this have two brackets around it instead of one?
</details>
Inner brackets are just a js object, that defines structure of returned object ([example from docs](http://usejsdoc.org/tags-type.html)). May be it would be better to use `@typedef` to define custom type but it is the only place where I have used it and there are no links to this type

---

*[thali/NextGeneration/utils/usn.js, line 27 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-KSDZjwhU0LL8dpejvqL:-KSGNaweCYNB0i2XWflL:b-xt63dt) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4380252c6f78cb452688c99b780f9a572d5a0150/thali/NextGeneration/utils/usn.js#L27)):*
> Arg sorry, not prototype!!! Each function in usn.js should be defined directly on the USN object as in USN.parse. I clearly didn't get enough sleep last night.

I think it is not blocking anymore :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103)*

**Comment by ThaliTester** [comment]
Test (Success) 86147834 build is completed (a13d096)

See https://github.com/ThaliTester/TestResults/tree/86147834a13d096__898_Updates_to_thaliWifiInfrastructure_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 86147834a13d096(a13d096) has failed

See https://github.com/ThaliTester/TestResults/tree/86147834a13d096__898_Updates_to_thaliWifiInfrastructure_chapko/ for the fail logs

**Comment by chapko** [comment]
> Arg sorry, not prototype!!! Each function in usn.js should be defined directly on the USN object as in USN.parse. I clearly didn't get enough sleep last night.

@yaronyg you mean it should like this?

```javascript
USN.parse = function (usn) {
  // ...
}
USN.stringify = function (peer) {
  // ...
}
module.exports = USN;
```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 8. task. (e15a0bc)

**Comment by ThaliTester** [comment]
Test (Fail) 86147834 build is completed (e15a0bc)

See https://github.com/ThaliTester/TestResults/tree/86147834e15a0bc__898_Updates_to_thaliWifiInfrastructure_chapko/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-:-KSNwHAqtybReemKrKpO:bnfp4nl)*

**Comment by yaronyg** [comment]
PLEASE DO NOT CHECK THIS INTO VNEXT_YARONG_417_812. IT WILL BREAK ALL THE NODE CODE UPSTREAM! We need to instead check this into a new iOS branch. I'll send a long boring mail with many details.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-:-KSNwU0Me8tYJGLgIvsr:b-vjeyee)*

**Comment by yaronyg** [comment]
This will be merged into whatever branch @artemjackson and @chapko agree to hold their breaking node changes in until we are ready to merge them.

**Comment by artemjackson** [comment]
@chapko Please, submit to `superbranch_android`

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0d0f41a)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (358da51)

**Comment by ThaliTester** [comment]
Test (Fail) 86147834 build is completed (0d0f41a)

See https://github.com/ThaliTester/TestResults/tree/861478340d0f41a__898_Updates_to_thaliWifiInfrastructure_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 86147834 build is completed (358da51)

See https://github.com/ThaliTester/TestResults/tree/86147834358da51__898_Updates_to_thaliWifiInfrastructure_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 86147834358da51(358da51) has failed

See https://github.com/ThaliTester/TestResults/tree/86147834358da51__898_Updates_to_thaliWifiInfrastructure_chapko/ for the fail logs

**Comment by yaronyg** [comment]
Something has gone very screwy with this PR so I'm going to kill it and recreate it.

**Comment by yaronyg** [comment]
Unfortunately I made a complete mess of this PR so I'm closing it.

---

Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1103#-:-KTHDe6CZ8Jzxi8jb4b0:b-bnfbmx)*

**Pull request closed without merging**
