### PR TITLE
We shouldn't force desired platforms equals required platforms

### LINKED ISSUE #1121: We shouldn't force desired platforms equals required platforms
Required platforms can not be equals to desiged platforms. Required platforms should be included in desired platforms. For example: desired platforms are `[ 'android', 'desktop', 'ios' ]`, required platforms are `[ 'android', 'ios' ]`.

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1121

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1122)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (115ab5f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (4f6286f)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (855e6ef)

**Comment by ThaliTester** [comment]
Test (Success) 86333246 build is completed (115ab5f)

See https://github.com/ThaliTester/TestResults/tree/86333246115ab5f_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 86333246115ab5f(115ab5f) has failed

See https://github.com/ThaliTester/TestResults/tree/86333246115ab5f_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86333246 build is completed (4f6286f)

See https://github.com/ThaliTester/TestResults/tree/863332464f6286f_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 863332464f6286f(4f6286f) has failed

See https://github.com/ThaliTester/TestResults/tree/863332464f6286f_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86333246 build is completed (855e6ef)

See https://github.com/ThaliTester/TestResults/tree/86333246855e6ef_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 86333246855e6ef(855e6ef) has failed

See https://github.com/ThaliTester/TestResults/tree/86333246855e6ef_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
Once it passes CI then :lgtm: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/TestServer/config/UnitTest.js, line 10 at r3](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1122#-KSJ3BiOcG-62YcOj0B4:-KSJ3BiOcG-62YcOj0B5:b6kmkoh) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/855e6efdb854a9efbea197764579316c44880717/test/TestServer/config/UnitTest.js#L10)):*
> ```JavaScript
>     // All required platform should have minDevices entry.
>     // So all required platforms should be listed in desired platform list.
>     ios: 3,
> ```

NB: Shouldn't these all be -1?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1122#-:-KSJ3Gew4naVPHMBvE7S:b-md1q0r)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 6. task. (4e64f14)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 7. task. (03eeb8f)

**Comment by ThaliTester** [comment]
Test (Success) 86333246 build is completed (4e64f14)

See https://github.com/ThaliTester/TestResults/tree/863332464e64f14_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 863332464e64f14(4e64f14) has failed

See https://github.com/ThaliTester/TestResults/tree/863332464e64f14_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 86333246 build is completed (03eeb8f)

See https://github.com/ThaliTester/TestResults/tree/8633324603eeb8f_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 8633324603eeb8f(03eeb8f) has failed

See https://github.com/ThaliTester/TestResults/tree/8633324603eeb8f_We_shouldn_t_force_desired_platforms_equals_required_platforms_andrew-aladev/ for the fail logs

**Pull request merged**
