### PR TITLE
Update pouchdb and related dependencies.

### LINKED ISSUE #512: Update tests to use latest pouchdb

### PR DESCRIPTION
**Pull request by vjrantal**
Dependency to supertest was added, because supertest-as-promised lists it as
peer dependency.

Fixes #512.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/513)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (381ca4f)

**Comment by vjrantal** [comment]
@yaronyg: I tested locally that the replication manager test passes on iOS with this change included so it should be okay to take this into `vNext`. Please review and if all good, I'll merge.

**Comment by ThaliTester** [comment]
Test 58259810381ca4f(381ca4f) has failed

See https://github.com/ThaliTester/TestResults/tree/58259810381ca4f_Update_pouchdb_and_related_dependencies__vjrantal/ for the fail logs

**Comment by vjrantal** [comment]
In the CI, the other iOS device crashed, but we have seen crashes with the unit test app also before so I would not say it is due to the dependency updates.

Here is the crash for convenience:

```
About to call stopBroadcasting

2016-02-04 10:51:21.768 ThaliTest[2519:7778417] jxcore: stopBroadcasting
2016-02-04 10:51:21.768 ThaliTest[2519:7778417] THEMultipeerSession stopping peer
2016-02-04 10:51:21.768 ThaliTest[2519:7778417,] multipeer session: stop timer
2016-02-04 10:51:21.769 ThaliTest[2519:7778417] jxcore: stopBroadcasting: success
Got callback from stopBroadcasting with err undefined

,mux server bridge listener closed

# setup
,
,* thread #1: tid = 0x76af5f, 0x3979d2c6 libsystem_platform.dylib`<redacted> + 34, queue = 'com.apple.main-thread'
  * frame #0: 0x3979d2c6 libsystem_platform.dylib`<redacted> + 34
    frame #1: 0x3972d350 libsystem_malloc.dylib`<redacted> + 548
    frame #2: 0x397b435e libsystem_trace.dylib`_os_log_internal + 542
    frame #3: 0x29d72b64 MultipeerConnectivity`<redacted> + 60
    frame #4: 0x27113984 CFNetwork`<redacted> + 120
    frame #5: 0x2711332c CFNetwork`<redacted> + 36
    frame #6: 0x27071062 CFNetwork`<redacted> + 90
    frame #7: 0x277e87c6 CoreFoundation`<redacted> + 14
    frame #8: 0x277e8348 CoreFoundation`<redacted> + 344
    frame #9: 0x277e671e CoreFoundation`<redacted> + 806
    frame #10: 0x277390d8 CoreFoundation`CFRunLoopRunSpecific + 516
    frame #11: 0x27738ecc CoreFoundation`CFRunLoopRunInMode + 108
    frame #12: 0x30aaeaf8 GraphicsServices`GSEventRunModal + 160
    frame #13: 0x2b9c22dc UIKit`UIApplicationMain + 144
    frame #14: 0x000bc1f2 ThaliTest`main + 50
```

**Comment by yaronyg** [comment]
@vjrantal Who is investing that crash?

**Comment by yaronyg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/513)*

**Comment by yaronyg** [comment]
:shipit:

**Comment by vjrantal** [comment]
> @vjrantal Who is investing that crash?

@yaronyg: I mentioned it to @tobybrad today and now also added a reference to https://github.com/thaliproject/Thali_CordovaPlugin/issues/461 . I wasn't sure if this was the same root cause so didn't create a new issue.

**Pull request merged**
