### PR TITLE
Improve CoordinatedClient logging

### PR DESCRIPTION
**Pull request by chapko**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1522)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (9d40c45)

**Comment by ThaliTester** [comment]
Test (Success) 93748500 build is completed (9d40c45)

See https://github.com/ThaliTester/TestResults/tree/937485009d40c45_Improve_CoordinatedClient_logging_chapko/ for the logs

**Comment by ThaliTester** [comment]
Test 937485009d40c45(9d40c45) has failed

See https://github.com/ThaliTester/TestResults/tree/937485009d40c45_Improve_CoordinatedClient_logging_chapko/ for the fail logs

**Comment by andrew-aladev** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1522)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1522#-:-KWhQ7tW1lNCs_wlO8Th:bnfp4nl)*

**Pull request merged**
