### PR TITLE
For terminateListener and terminateConnection return an error if we get called on iOS

### PR DESCRIPTION
**Pull request by squid48**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1486)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (461bb6c)

**Comment by ThaliTester** [comment]
Test (Fail) 92301105 build is completed (461bb6c)

See https://github.com/ThaliTester/TestResults/tree/92301105461bb6c_For_terminateListener_and_terminateConnection_return_an_error_if_we_get_called_on_iOS_squid48/ for the logs

**Comment by chapko** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 619 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1486#-KWI5g2HpCyG4jYFXOP7:-KWI5g2HpCyG4jYFXOP8:b-si6mld) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/461bb6c57c1c26f5332ff155a9f0c3ee4fd8994a/thali/NextGeneration/thaliMobileNativeWrapper.js#L619)):*
> ```JavaScript
> module.exports._terminateConnection = function (incomingConnectionId) {
>   if(platform.isIOS) {
>     throw new Error('Not connect platform');
> ```

This method should return `Promise`. 

The simple rule here is that function should be either synchronous or asynchronous. Not both.

---

*[thali/NextGeneration/thaliMobileNativeWrapper.js, line 683 at r1](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1486#-KWI6cyZ2gNNnP1sddns:-KWI6cyZ2gNNnP1sddnt:b-nwrpmw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/461bb6c57c1c26f5332ff155a9f0c3ee4fd8994a/thali/NextGeneration/thaliMobileNativeWrapper.js#L683)):*
> ```JavaScript
> module.exports.terminateListener = function (peerIdentifier, port) {
>   if(platform.isIOS) {
>     throw new Error('Not connect platform');
> ```

The same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1486)*

**Comment by yaronyg** [comment]
@squid48 please assign this to me once you have resolved @chapko's comments. @chapko owns the primary review. I do the final one. Thanks!

**Comment by chapko** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1486#-:-KWrEf1oK7R1Dujrsm8U:bnfp4nl)*

**Comment by yaronyg** [comment]
Please fix the typo and also make sure it passes CI. The only build I see failed. Once that is done then :lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js, line 343 at r2](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1486#-KWuC4BucbkZSx8HfH8T:-KWuC4BvX2w9GMS1lQKA:b6z5xhw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/4d9ddc5700d162b701112a64867917fd882470f2/test/www/jxcore/bv_tests/testThaliMobileNativeWrapper.js#L343)):*
> ```JavaScript
> );
> 
> test('make sure terminateListener is return error if we get called on iOS',
> ```

/terminateListener/terminateConnection/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1486#-:-KWuCBv44xkXu9xOeK6t:bci2h27)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (9df6c3a)

**Comment by ThaliTester** [comment]
Test 92301105 (9df6c3a) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 92301105 build is completed (9df6c3a)

See https://github.com/ThaliTester/TestResults/tree/923011059df6c3a_For_terminateListener_and_terminateConnection_return_an_error_if_we_get_called_on_iOS_squid48/ for the logs

**Pull request closed without merging**
