### PR TITLE
Fixed already connecting

### PR DESCRIPTION
**Pull request by andrew-aladev**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1243)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2ebec60)

**Comment by ThaliTester** [comment]
Test (Success) 87899936 build is completed (2ebec60)

See https://github.com/ThaliTester/TestResults/tree/878999362ebec60_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 878999362ebec60(2ebec60) has failed

See https://github.com/ThaliTester/TestResults/tree/878999362ebec60_Fixed_already_connecting_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (8e6766e)

**Comment by ThaliTester** [comment]
Test (Success) 87899936 build is completed (8e6766e)

See https://github.com/ThaliTester/TestResults/tree/878999368e6766e_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 878999368e6766e(8e6766e) has failed

See https://github.com/ThaliTester/TestResults/tree/878999368e6766e_Fixed_already_connecting_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cccc5f7)

**Comment by ThaliTester** [comment]
Test (Success) 87899936 build is completed (cccc5f7)

See https://github.com/ThaliTester/TestResults/tree/87899936cccc5f7_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 87899936cccc5f7(cccc5f7) has failed

See https://github.com/ThaliTester/TestResults/tree/87899936cccc5f7_Fixed_already_connecting_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (caa6543)

**Comment by ThaliTester** [comment]
Test (Success) 87899936 build is completed (caa6543)

See https://github.com/ThaliTester/TestResults/tree/87899936caa6543_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 87899936caa6543(caa6543) has failed

See https://github.com/ThaliTester/TestResults/tree/87899936caa6543_Fixed_already_connecting_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b5b588f)

**Comment by ThaliTester** [comment]
Test (Success) 87899936 build is completed (b5b588f)

See https://github.com/ThaliTester/TestResults/tree/87899936b5b588f_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 87899936b5b588f(b5b588f) has failed

See https://github.com/ThaliTester/TestResults/tree/87899936b5b588f_Fixed_already_connecting_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (28a1e44)

**Comment by ThaliTester** [comment]
Test (Success) 87899936 build is completed (28a1e44)

See https://github.com/ThaliTester/TestResults/tree/8789993628a1e44_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 8789993628a1e44(28a1e44) has failed

See https://github.com/ThaliTester/TestResults/tree/8789993628a1e44_Fixed_already_connecting_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (338a246)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (c6f2ee9)

**Comment by ThaliTester** [comment]
Test (Fail) 87899936 build is completed (338a246)

See https://github.com/ThaliTester/TestResults/tree/87899936338a246_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 87899936 build is completed (c6f2ee9)

See https://github.com/ThaliTester/TestResults/tree/87899936c6f2ee9_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cd481c0)

**Comment by ThaliTester** [comment]
Test (Fail) 87899936 build is completed (cd481c0)

See https://github.com/ThaliTester/TestResults/tree/87899936cd481c0_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (285db68)

**Comment by ThaliTester** [comment]
Test (Success) 87899936 build is completed (285db68)

See https://github.com/ThaliTester/TestResults/tree/87899936285db68_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 87899936285db68(285db68) has failed

See https://github.com/ThaliTester/TestResults/tree/87899936285db68_Fixed_already_connecting_andrew-aladev/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b4f2b1c)

**Comment by ThaliTester** [comment]
Test (Success) 87899936 build is completed (b4f2b1c)

See https://github.com/ThaliTester/TestResults/tree/87899936b4f2b1c_Fixed_already_connecting_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 87899936b4f2b1c(b4f2b1c) has failed

See https://github.com/ThaliTester/TestResults/tree/87899936b4f2b1c_Fixed_already_connecting_andrew-aladev/ for the fail logs

**Comment by yaronyg** [comment]
@andrew-aladev Have you tried this test out on Android and confirmed that it passes reliably?

---

Reviewed 11 of 13 files at r1.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1243#-:-KToxCsH1YqTTAByuADI:b585kh3)*

**Comment by yaronyg** [comment]
@andrew-aladev / @larryonoff - BTW, I just want to know if this PR 'as is' passes on Android wifi and native mode. If it does then we can check it in. If it does not then I do NOT want any bug fixes on this. This test can't be our priority. Instead I want the new test put back into disabled and the old test re-activated. If the old test isn't behaving itself I'll take care of the bugs.

**Comment by vasilevskayaem** [comment]
still fails in native mode

**Pull request closed without merging**
