### PR TITLE
Fix for issue #47: Outgoing connections can now be initiated even when we are not listening for incoming connections.

### PR DESCRIPTION
**Pull request by tompaana**
The major part of this fix was implemented to the Bluetooth connector library. This PR is almost only about making the plug-in to use the latest version of the library.

[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/600)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4bd7322)

**Comment by ThaliTester** [comment]
Test (Success) 61716163 build is completed (4bd7322)

See https://github.com/ThaliTester/TestResults/tree/617161634bd7322_Fix_for_issue__47__Outgoing_connections_can_now_be_initiated_even_when_we_are_not_listening_for_incoming_connections__tompaana/ for the logs

**Comment by ThaliTester** [comment]
Test 617161634bd7322(4bd7322) has failed

See https://github.com/ThaliTester/TestResults/tree/617161634bd7322_Fix_for_issue__47__Outgoing_connections_can_now_be_initiated_even_when_we_are_not_listening_for_incoming_connections__tompaana/ for the fail logs

**Comment by yaronyg** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/600)*

**Pull request merged**
