### PR TITLE
Disable testing infrastructure for release version for iOS

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1722)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ce5cc54)

**Comment by ThaliTester** [comment]
Test 101430970 (ce5cc54) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 101430970 build is completed (ce5cc54)

See https://github.com/ThaliTester/TestResults/tree/101430970ce5cc54_Disable_testing_infrastructure_for_release_version_for_iOS_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (dc8263d)

**Comment by ThaliTester** [comment]
Test 101430970 (dc8263d) build started.

**Comment by ThaliTester** [comment]
Test (Fail) 101430970 build is completed (dc8263d)

See https://github.com/ThaliTester/TestResults/tree/101430970dc8263d_Disable_testing_infrastructure_for_release_version_for_iOS_larryonoff/ for the logs

**Comment by larryonoff** [comment]
@jareksl @mlesnic @jareksl please try this PR, it should fix thaliproject/Thali_CordovaPlugin#1709

**Comment by mlesnic** [comment]
@larryonoff The build itself fails with error ``error: exportArchive: No applicable devices found.
`` but when I open the project in XCode 7.3.1, it builds correctly.

**Comment by larryonoff** [comment]
The first part of the issue is fixed, but this's another failure. So I'll reassign the issue to @dersim-davaod, he'll proceed with the issue.

**Comment by evabishchevich** [comment]
@dersim-davaod Do we need something to do here or this PR works fine?

**Comment by larryonoff** [comment]
@evabishchevich we may need to update build process in `setUpTests.sh`, but I think it should be separate PR.

**Comment by czyzm** [comment]
For me the same result as for @mlesnic . I can build ThaliTestApp from xCode but when calling `cordova build ios --device` from terminal I am getting `error: exportArchive: No applicable devices found.`

**Comment by dersim-davaod** [comment]
I've created #1757 issue.

**Comment by evabishchevich** [comment]
@mlesnic @jareksl  @czyzm  @larryonoff Let's merge this PR and work with #1757 as a separate issue

**Comment by czyzm** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1722#-:-KbUAI3eqLat9ssE5-x7:bnfp4nl)*

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1722#-:-KbLJpZ2NGYq0CO826uw:bnfp4nl)*

**Pull request merged**
