### PR TITLE
Fixed task cancel

### LINKED ISSUE #1713: Replication peer action coordinated hangs on desktop in BOTH mode

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #1713.

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1714)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4485454)

**Comment by ThaliTester** [comment]
Test 100690826 (4485454) build started.

**Comment by ThaliTester** [comment]
Test (Success) 100690826 build is completed (4485454)

See https://github.com/ThaliTester/TestResults/tree/1006908264485454_Fixed_task_cancel_andrew-aladev/ for the logs

**Comment by ThaliTester** [comment]
Test 1006908264485454(4485454) has failed

See https://github.com/ThaliTester/TestResults/tree/1006908264485454_Fixed_task_cancel_andrew-aladev/ for the fail logs

**Comment by jareksl** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1714#-:-Ka6nxVhs5WAuRPTYIMo:bg7igkv)*

**Comment by mlesnic** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1714#-:-Ka7LWZ5bx0W1rufD35q:bnfp4nl)*

**Pull request merged**
