### PR TITLE
Native UT for cordova plugin (android) - build test

### PR DESCRIPTION
**Pull request by jareksl**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/743)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5063316)

**Comment by ThaliTester** [comment]
Test (Fail) 75789268 build is completed (5063316)

See https://github.com/ThaliTester/TestResults/tree/757892685063316_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2b188b4)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (51a8f91)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (e91aba5)

**Comment by ThaliTester** [comment]
Test (Fail) 75789268 build is completed (2b188b4)

See https://github.com/ThaliTester/TestResults/tree/757892682b188b4_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (51a8f91)

See https://github.com/ThaliTester/TestResults/tree/7578926851a8f91_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test (Fail) 75789268 build is completed (e91aba5)

See https://github.com/ThaliTester/TestResults/tree/75789268e91aba5_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 7578926851a8f91(51a8f91) has failed

See https://github.com/ThaliTester/TestResults/tree/7578926851a8f91_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2551a10)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (2551a10)

See https://github.com/ThaliTester/TestResults/tree/757892682551a10_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892682551a10(2551a10) has failed

See https://github.com/ThaliTester/TestResults/tree/757892682551a10_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6fd65a6)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (6fd65a6)

See https://github.com/ThaliTester/TestResults/tree/757892686fd65a6_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892686fd65a6(6fd65a6) has failed

See https://github.com/ThaliTester/TestResults/tree/757892686fd65a6_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2308ffa)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (2308ffa)

See https://github.com/ThaliTester/TestResults/tree/757892682308ffa_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892682308ffa(2308ffa) has failed

See https://github.com/ThaliTester/TestResults/tree/757892682308ffa_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (0c366d1)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (0c366d1)

See https://github.com/ThaliTester/TestResults/tree/757892680c366d1_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892680c366d1(0c366d1) has failed

See https://github.com/ThaliTester/TestResults/tree/757892680c366d1_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (eab05ed)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (eab05ed)

See https://github.com/ThaliTester/TestResults/tree/75789268eab05ed_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 75789268eab05ed(eab05ed) has failed

See https://github.com/ThaliTester/TestResults/tree/75789268eab05ed_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1403989)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (1403989)

See https://github.com/ThaliTester/TestResults/tree/757892681403989_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892681403989(1403989) has failed

See https://github.com/ThaliTester/TestResults/tree/757892681403989_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5fc4836)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (5fc4836)

See https://github.com/ThaliTester/TestResults/tree/757892685fc4836_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892685fc4836(5fc4836) has failed

See https://github.com/ThaliTester/TestResults/tree/757892685fc4836_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5041341)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (5041341)

See https://github.com/ThaliTester/TestResults/tree/757892685041341_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892685041341(5041341) has failed

See https://github.com/ThaliTester/TestResults/tree/757892685041341_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a22e351)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (a22e351)

See https://github.com/ThaliTester/TestResults/tree/75789268a22e351_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (5345aa0)

**Comment by ThaliTester** [comment]
Test 75789268a22e351(a22e351) has failed

See https://github.com/ThaliTester/TestResults/tree/75789268a22e351_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (5345aa0)

See https://github.com/ThaliTester/TestResults/tree/757892685345aa0_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892685345aa0(5345aa0) has failed

See https://github.com/ThaliTester/TestResults/tree/757892685345aa0_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (21ef376)

**Comment by yaronyg** [comment]
I don't understand why win_delay_load_hook.c is being loaded twice. What changed on appveyor? None of our dependencies have changed as near as I can tell.

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (21ef376)

See https://github.com/ThaliTester/TestResults/tree/7578926821ef376_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 7578926821ef376(21ef376) has failed

See https://github.com/ThaliTester/TestResults/tree/7578926821ef376_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d2ecd3a)

**Comment by ThaliTester** [comment]
Test 75789268d2ecd3a(d2ecd3a) has failed

See https://github.com/ThaliTester/TestResults/tree/75789268d2ecd3a_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5a40176)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (5a40176)

See https://github.com/ThaliTester/TestResults/tree/757892685a40176_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892685a40176(5a40176) has failed

See https://github.com/ThaliTester/TestResults/tree/757892685a40176_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (514fc25)

**Comment by ThaliTester** [comment]
Test 75789268514fc25(514fc25) has failed

See https://github.com/ThaliTester/TestResults/tree/75789268514fc25_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (257fa25)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (257fa25)

See https://github.com/ThaliTester/TestResults/tree/75789268257fa25_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by yaronyg** [comment]
Waiting for the next release of JXcore before we continue to work on this because there is a blocking bug in JXcore.

**Comment by yaronyg** [comment]
This is just a test project, it isn't intended to actually be accepted

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6f45c73)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (6f45c73)

See https://github.com/ThaliTester/TestResults/tree/757892686f45c73_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892686f45c73(6f45c73) has failed

See https://github.com/ThaliTester/TestResults/tree/757892686f45c73_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ed88ae2)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (ed88ae2)

See https://github.com/ThaliTester/TestResults/tree/75789268ed88ae2_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 75789268ed88ae2(ed88ae2) has failed

See https://github.com/ThaliTester/TestResults/tree/75789268ed88ae2_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4714826)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (4714826)

See https://github.com/ThaliTester/TestResults/tree/757892684714826_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 757892684714826(4714826) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/757892684714826_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (a387c77)

**Comment by ThaliTester** [comment]
Test (Success) 75789268 build is completed (a387c77)

See https://github.com/ThaliTester/TestResults/tree/75789268a387c77_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the logs

**Comment by ThaliTester** [comment]
Test 75789268a387c77(a387c77) has failed

See https://github.com/ThaliTester/TestResults/tree/75789268a387c77_Native_UT_for_cordova_plugin__android__-_build_test_jareksl/ for the fail logs

**Comment by jareksl** [comment]
This PR was created for testing purposes and was not meant to be merged.

**Pull request closed without merging**
