### PR TITLE
Use updated version exec with live streaming of stdout, stderr

### PR DESCRIPTION
**Pull request by larryonoff**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1380)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ba1c304)

**Comment by larryonoff** [comment]
@yaronyg please review

**Comment by ThaliTester** [comment]
Test (Success) 90046416 build is completed (ba1c304)

See https://github.com/ThaliTester/TestResults/tree/90046416ba1c304_Use_updated_version_exec_with_live_streaming_of_stdout__stderr_larryonoff/ for the logs

**Comment by ThaliTester** [comment]
Test 90046416ba1c304(ba1c304) has failed

See https://github.com/ThaliTester/TestResults/tree/90046416ba1c304_Use_updated_version_exec_with_live_streaming_of_stdout__stderr_larryonoff/ for the fail logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1380#-:-KUTbMuMVGv93GFCO6_y:bnfp4nl)*

**Pull request merged**
