### PR TITLE
Fix bug causing tests to fail

### PR DESCRIPTION
**Pull request by yaronyg**
I checked in #1466 without noticing that it had broken some tests. This fixes that problem.

build.sh - Time to run all 3 flavors if only on Android and only on desktop

testThaliReplicationPeerAction - Fix null pool so tests pass

thaliReplicationPeerAction - Linting

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1468)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (785bb88)

**Comment by ThaliTester** [comment]
Test (Fail) 91909192 build is completed (785bb88)

See https://github.com/ThaliTester/TestResults/tree/91909192785bb88_Fix_bug_causing_tests_to_fail_yaronyg/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bf1135c)

**Comment by ThaliTester** [comment]
Test (Fail) 91909192 build is completed (bf1135c)

See https://github.com/ThaliTester/TestResults/tree/91909192bf1135c_Fix_bug_causing_tests_to_fail_yaronyg/ for the logs

**Comment by andrew-aladev** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1468)*

**Comment by andrew-aladev** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1468#-:-KV_pq5FomFeDprUVQos:bnfp4nl)*

**Comment by yaronyg** [comment]
The failure in CI is due to a bug in CI. We have independently confirmed that this passes so I'm going to submit.

**Pull request merged**
