### PR TITLE
added 10 attempts to test in case if something bad happens with socket

### PR DESCRIPTION
**Pull request by vasilevskayaem**
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1321)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5c04986)

**Comment by ThaliTester** [comment]
Test (Fail) 89372302 build is completed (5c04986)

See https://github.com/ThaliTester/TestResults/tree/893723025c04986_added_10_attempts_to_test_in_case_if_something_bad_happens_with_socket_vasilevskayaem/ for the logs

**Comment by yaronyg** [comment]
This PR is a month old, didn't pass tests and isn't assigned to anyone. @vasilevskayaem what do you want us to do with it?

**Comment by vasilevskayaem** [comment]
since branch vNext_yarong_417_812_1205 contains not only "10 attempt run test" logic and wasn't merged in master branch, I'll close this pull request and add "10 attempts" logic to master branch code and create new pr

**Pull request closed without merging**
