### PR TITLE
Upgraded tests #977 clean

### PR DESCRIPTION
**Pull request by mlesnic**
Implemented #977

---
This change is [Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/1054)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (57d25d6)

**Comment by ThaliTester** [comment]
Test (Success) 85525887 build is completed (57d25d6)

See https://github.com/ThaliTester/TestResults/tree/8552588757d25d6_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 8552588757d25d6(57d25d6) has failed

See https://github.com/ThaliTester/TestResults/tree/8552588757d25d6_Upgraded_tests__977_clean_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (6377119)

**Comment by ThaliTester** [comment]
Test (Fail) 85525887 build is completed (6377119)

See https://github.com/ThaliTester/TestResults/tree/855258876377119_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (42df921)

**Comment by ThaliTester** [comment]
Test (Success) 85525887 build is completed (42df921)

See https://github.com/ThaliTester/TestResults/tree/8552588742df921_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 8552588742df921(42df921) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8552588742df921_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (50d17b9)

**Comment by ThaliTester** [comment]
Test (Success) 85525887 build is completed (50d17b9)

See https://github.com/ThaliTester/TestResults/tree/8552588750d17b9_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 8552588750d17b9(50d17b9) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8552588750d17b9_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by yaronyg** [comment]
The PR has a consistent pattern where it polls for some event to occur and if that event doesn't occur then there is a log of the failure. Which is great, it gives us a way to detect what is going on. But unfortunately it doesn't stop the test dead in its tracks which is what it should do. But this is pretty easy to fix. 

One way is to use setUncaughtExceptionHandler on the thread object and have the polling thread throw an exception if it fails. 

But for this PR a probably simpler solution is to use [Callable](https://developer.android.com/reference/java/util/concurrent/Callable.html) which looks just like Runnable but is designed to return a result (such as - did the polling work or not). So the parent thread will use the Executors to run the task and then get the result which can be a boolean specifying if the polling worked or not.

---

Reviewed 11 of 11 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/android/test/com/test/thalitest/RegisterExecuteUT.java, line 27 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpAmA-mlPwznkJBY4A:-KRpAmA-mlPwznkJBY4B:bdobq4c) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/com/test/thalitest/RegisterExecuteUT.java#L27)):*
> ```Java
>         int caseInt = 0;
> 
>         if (methodName.equals("onPeerLost")) {
> ```

As of JDK 7, which Android supports, we can switch on strings. Please switch the code to use that feature.

---

*[src/android/test/com/test/thalitest/ThaliTestRunner.java, line 38 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpD8lJpfxOa6dU0DqA:-KRpD8lJpfxOa6dU0DqB:b-2o16xi) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/com/test/thalitest/ThaliTestRunner.java#L38)):*
> ```Java
>                     }
>                 }
>                 if (counter >= ThaliTestRunner.counterLimit) Log.e(mTag, "Radios didn't start after 5s!");
> ```

It's great that we log this but we need more than that. We need to make the tests fail if this if statement is true.

---

*[src/android/test/com/test/thalitest/ThaliTestRunner.java, line 66 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpDM0fiQhhcnwJ62Fj:-KRpDM0gJya27yGPeKFs:b6d9erq) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/com/test/thalitest/ThaliTestRunner.java#L66)):*
> ```Java
> 
>             try {
>                 Thread.sleep(10000);
> ```

This count should not start until after createCheckRadiosThread passes its checks on btAdapter.isEnabled() and wifiManager.isWifiEnabled(). With the callable pattern this will be easy to set up.

---

*[src/android/test/io/jxcore/node/StreamCopyingThreadTest.java, line 55 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpH3lmsO_4pxZVgqqU:-KRpH3lmsO_4pxZVgqqV:bxaizm8) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/io/jxcore/node/StreamCopyingThreadTest.java#L55)):*
> ```Java
>                     mIsClosed = fIsClosed.getBoolean(mStreamCopyingThread);
>                 } catch (NoSuchFieldException e) {
>                     e.printStackTrace();
> ```

If we got these exceptions how can the test continue?

---

*[src/android/test/io/jxcore/node/StreamCopyingThreadTest.java, line 121 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHCYoVdAAWvy2KTJj:-KRpHCYp4xFPNf29Ibbw:bdfnnje) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/io/jxcore/node/StreamCopyingThreadTest.java#L121)):*
> ```Java
>         mStreamCopyingThread.start();
>         
>         Thread.sleep(2000);
> ```

Why are we waiting 2 seconds?

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 27 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHf_AyZB9vpJRgbjT:-KRpHf_AyZB9vpJRgbjU:b-xicf5h) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/test/www/jxcore/bv_tests/testNativeMethod.js#L27)):*
> ```JavaScript
>     setImmediate(function () {
>       Mobile('peerAvailabilityChanged').registerToNative(function (peers) {
>         //clearTimeout(timeOut);
> ```

NB: This commented out call is probably not needed, right?

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 30 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHm1Tk801wGXoC5-e:-KRpHm1Tk801wGXoC5-f:bws5atc) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/test/www/jxcore/bv_tests/testNativeMethod.js#L30)):*
> ```JavaScript
>         if (typeof peers.forEach !== 'function') {
>           peers = [peers];
>           t.fail('peers callback should be an array!');
> ```

NB: I would be the t.fail first, it felt weird that you set peers and then called t.fail. I'm thinking "what for"? It took me a second to realize that you were going to try to continue the test anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-:-KRpEfA5Y9h6sSNAFuYL:bbjkjax)*

**Comment by mlesnic** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/android/test/com/test/thalitest/RegisterExecuteUT.java, line 27 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpAmA-mlPwznkJBY4A:-KS0CPWY05bqTusIZJqS:b-ap2ha3) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/com/test/thalitest/RegisterExecuteUT.java#L27)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> As of JDK 7, which Android supports, we can switch on strings. Please switch the code to use that feature.
</details>
Added method to before_compile.js that replace JavaVersion 1.6 with JavaVersion 1.7

---

*[src/android/test/io/jxcore/node/StreamCopyingThreadTest.java, line 121 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHCYoVdAAWvy2KTJj:-KS0IWRyE5dNfWytoc7f:b-dau5hb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/io/jxcore/node/StreamCopyingThreadTest.java#L121)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Why are we waiting 2 seconds?
</details>
Here we wait for Stream Copying Thread to do some job, I mean, copy some input to output. And after 2s I close it and check if input stream content matches output stream's.  

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 27 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHf_AyZB9vpJRgbjT:-KS0J6w9hWwvyYGfjlOz:bb77ufg) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/test/www/jxcore/bv_tests/testNativeMethod.js#L27)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: This commented out call is probably not needed, right?
</details>
Yes.

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 30 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHm1Tk801wGXoC5-e:-KS0J8ouLkqla_ym1O51:b-ff2nou) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/test/www/jxcore/bv_tests/testNativeMethod.js#L30)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: I would be the t.fail first, it felt weird that you set peers and then called t.fail. I'm thinking "what for"? It took me a second to realize that you were going to try to continue the test anyway.
</details>
I did as it was done in other test classes. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task. (fe3c967)

**Comment by ThaliTester** [comment]
Test (Success) 85525887 build is completed (fe3c967)

See https://github.com/ThaliTester/TestResults/tree/85525887fe3c967_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 85525887fe3c967(fe3c967) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/85525887fe3c967_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by yaronyg** [comment]
So close!!!! The main issue is how we update the Java version. Please see my comment for details on how we can do it in a more cordova friendly way.

---

Reviewed 15 of 15 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[scripts/android/before_compile.js, line 185 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KS37NuNToblgAkLNeV_:-KS37NuNToblgAkLNeVa:b-gz7zyb) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe3c967fabd08abcbb4feac03db8da3ab686a27a/scripts/android/before_compile.js#L185)):*
> ```JavaScript
> };
> 
> var updateJavaVersion = function (appRoot) {
> ```

Editing a source file is always an act of absolute desperate last resort. It is fragile. It is not discoverable. And most importantly, it isn't how Cordova is intended to be used. 

When I run into something like "How do I tell Cordova what version of Java to use?" I figure there is some answer and I bet it isn't "go manually edit a file". As explained [here](http://stackoverflow.com/questions/30874824/how-to-change-java-version-used-by-cordova-subprojects) we can introduce a build-extras.gradle file under src/android/java (just like we have already done for src/android/test) and we can set the Java version there.

Now anyone who knows gradle knows where to look when they want to configure our environment.

---

*[src/android/test/io/jxcore/node/StreamCopyingThreadTest.java, line 121 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHCYoVdAAWvy2KTJj:-KS36Gr3hRH2IgD9G8g6:b-3ud1) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/io/jxcore/node/StreamCopyingThreadTest.java#L121)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary>
> Here we wait for Stream Copying Thread to do some job, I mean, copy some input to output. And after 2s I close it and check if input stream content matches output stream's.  
</details>
Wouldn't a poll be more appropriate? If it takes 2001 ms the test will fail. It seems like we should poll and then set up an upper limit.

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 29 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KS36WXaWsXx8NPHCKlp:-KS36WXb0Kg7NvT_zo2k:bec5ie6) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe3c967fabd08abcbb4feac03db8da3ab686a27a/test/www/jxcore/bv_tests/testNativeMethod.js#L29)):*
> ```JavaScript
>         if (typeof peers.forEach !== 'function') {
>           peers = [peers];
>           t.fail('peers callback shoul  d be an array!');
> ```

NB: Why are there a bunch of spaces or a tab or something between shoul and the d?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-:-KS39dT3BdJ0bEGi78TS:b35b6c9)*

**Comment by mlesnic** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[scripts/android/before_compile.js, line 185 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KS37NuNToblgAkLNeV_:-KS54kmxdCVM8KnwDLtP:bxnh3kw) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe3c967fabd08abcbb4feac03db8da3ab686a27a/scripts/android/before_compile.js#L185)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Editing a source file is always an act of absolute desperate last resort. It is fragile. It is not discoverable. And most importantly, it isn't how Cordova is intended to be used. 
> 
> When I run into something like "How do I tell Cordova what version of Java to use?" I figure there is some answer and I bet it isn't "go manually edit a file". As explained [here](http://stackoverflow.com/questions/30874824/how-to-change-java-version-used-by-cordova-subprojects) we can introduce a build-extras.gradle file under src/android/java (just like we have already done for src/android/test) and we can set the Java version there.
> 
> Now anyone who knows gradle knows where to look when they want to configure our environment.
</details>
Agree. I will set it in gradle-extras.gradle.

---

*[src/android/test/io/jxcore/node/StreamCopyingThreadTest.java, line 121 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHCYoVdAAWvy2KTJj:-KS5-7ZRC2-62zuZGXrK:b-61q5qm) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/io/jxcore/node/StreamCopyingThreadTest.java#L121)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> Wouldn't a poll be more appropriate? If it takes 2001 ms the test will fail. It seems like we should poll and then set up an upper limit.
</details>
This is just some time to work for StreamCopyingThread. It doesn't matter if it is 1999ms or 2001ms. The only difference will be in the size of stream to copy, because here I have implemented infinite stream. The content of stream isn't hardcoded.

---

*[test/www/jxcore/bv_tests/testNativeMethod.js, line 29 at r5](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KS36WXaWsXx8NPHCKlp:-KS5-qO94JOc7mARLAua:bfk7h5u) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/fe3c967fabd08abcbb4feac03db8da3ab686a27a/test/www/jxcore/bv_tests/testNativeMethod.js#L29)):*
<details><summary><i>Previously, yaronyg (Yaron Y Goland) wrote…</i></summary>
> NB: Why are there a bunch of spaces or a tab or something between shoul and the d?
</details>
Yes, that's weird. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (43283b2)

**Comment by ThaliTester** [comment]
Test (Success) 85525887 build is completed (43283b2)

See https://github.com/ThaliTester/TestResults/tree/8552588743283b2_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 8552588743283b2(43283b2) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/8552588743283b2_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by yaronyg** [comment]
I only have 2 issues but they are both blockers. If you aren't sure how to resolve please talk to me on stack tomorrow.

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/android/test/build-extras.gradle, line 16 at r6](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KSDkfo8bmvZQXS15ROp:-KSDkfo9QWK4sAtKmyfg:bwqmfoj) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/43283b2f720635dbe58a68435038e08e8c2e6865/src/android/test/build-extras.gradle#L16)):*
> ```Gradle
> }
> 
> ext.postBuildExtras = {
> ```

Don't we need to set this in src/android/java as well so that it's available both to our production Java code as well as our test code?

---

*[src/android/test/io/jxcore/node/StreamCopyingThreadTest.java, line 121 at r4](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-KRpHCYoVdAAWvy2KTJj:-KSDjyA1g-T-XrRki5yd:b4ij4lx) ([raw file](https://github.com/thaliproject/thali_cordovaplugin/blob/50d17b9a090aaaa3d1dc1ae1c8ea9363c8e6695c/src/android/test/io/jxcore/node/StreamCopyingThreadTest.java#L121)):*
<details><summary><i>Previously, mlesnic (Marcin Lesniczek) wrote…</i></summary>
> This is just some time to work for StreamCopyingThread. It doesn't matter if it is 1999ms or 2001ms. The only difference will be in the size of stream to copy, because here I have implemented infinite stream. The content of stream isn't hardcoded.
</details>
But that is pretty unreliable and it means that running the test multiple times can give inconsistent results depending on how much time actually did pass which isn't great for finding bugs. Shouldn't we have some kind of definitive test with a fixed amount? For example, I see that there is a mNotifyStreamCopyingProgress in StreamCopyingThread. Why not use that to measure how much data has been copied and then close when we have the desired amount?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-:-KSDkoe4hH6uDm_JWA5O:b-7vkycf)*

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (2e8b4bc)

**Comment by ThaliTester** [comment]
Test (Success) 85525887 build is completed (2e8b4bc)

See https://github.com/ThaliTester/TestResults/tree/855258872e8b4bc_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 855258872e8b4bc(2e8b4bc) has failed

See https://github.com/ThaliTester/TestResults/tree/855258872e8b4bc_Upgraded_tests__977_clean_mlesnic/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (4296799)

**Comment by ThaliTester** [comment]
Test (Success) 85525887 build is completed (4296799)

See https://github.com/ThaliTester/TestResults/tree/855258874296799_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by ThaliTester** [comment]
Test 855258874296799(4296799) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/855258874296799_Upgraded_tests__977_clean_mlesnic/ for the logs

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/1054#-:-KSJ-aRolE4B0SACMy-L:bnfp4nl)*

**Pull request merged**
