### PR TITLE
Update to jxcore-cordova release 0.0.8.

### PR DESCRIPTION
**Pull request by vjrantal**
[Review on Reviewable](https://reviewable.io/reviews/thaliproject/thali_cordovaplugin/344)

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e387105)

**Comment by ThaliTester** [comment]
Test (Success) 51517283 build is completed (e387105)

See https://github.com/ThaliTester/TestResults/tree/51517283e387105_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 51517283e387105(e387105) has failed

See https://github.com/ThaliTester/TestResults/tree/51517283e387105_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (28249f0)

**Comment by ThaliTester** [comment]
Test (Success) 51517283 build is completed (28249f0)

See https://github.com/ThaliTester/TestResults/tree/5151728328249f0_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (ad8b554)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (57c3700)

**Comment by ThaliTester** [comment]
Test (Success) 51517283 build is completed (ad8b554)

See https://github.com/ThaliTester/TestResults/tree/51517283ad8b554_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 51517283 build is completed (57c3700)

See https://github.com/ThaliTester/TestResults/tree/5151728357c3700_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 5151728328249f0(28249f0) has failed

See https://github.com/ThaliTester/TestResults/tree/5151728328249f0_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (acd5ddf)

**Comment by ThaliTester** [comment]
Test (Success) 51517283 build is completed (acd5ddf)

See https://github.com/ThaliTester/TestResults/tree/51517283acd5ddf_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (57c3700)

**Comment by ThaliTester** [comment]
Test (Success) 51517283 build is completed (57c3700)

See https://github.com/ThaliTester/TestResults/tree/5151728357c3700_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 51517283acd5ddf(acd5ddf) has failed

See https://github.com/ThaliTester/TestResults/tree/51517283acd5ddf_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test 5151728357c3700(57c3700) has failed

See https://github.com/ThaliTester/TestResults/tree/5151728357c3700_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5a91168)

**Comment by ThaliTester** [comment]
Test (Success) 51517283 build is completed (5a91168)

See https://github.com/ThaliTester/TestResults/tree/515172835a91168_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 515172835a91168(5a91168) has failed

See https://github.com/ThaliTester/TestResults/tree/515172835a91168_Update_to_jxcore-cordova_release_0_0_8__vjrantal/ for the fail logs

**Comment by tobybrad** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/thaliproject/thali_cordovaplugin/344)_

**Pull request merged**
